### ISSUE TITLE
/system/scripts/jquery/themes/images/ajax-loader.gif not found

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#10]
Hallo,
die Grafik  /system/scripts/jquery/themes/images/ajax-loader.gif existiert nicht.

**Comment by mschlenstedt** [comment]
Fixed

**Comment by Woersty** [comment]
Funktioniert hier noch nicht. 
Hast du das schon commited?
http://loxberry/system/scripts/jquery/themes/images/ajax-loader.gif
