### ISSUE TITLE
Probleme bei den Plugins nach Speichern / Abbrechen

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#100]
Ich bastel gerade an einem Plugin und stelle fest, dass das so nicht geht wie wir es bisher gemacht haben. 

_Szenario:_
-Loxberry aufrufen - http://loxberry.woersty/
Ich lande auf http://loxberry.woersty/admin/index.cgi und sehe das Menü
-Miniserver Backup anklicken
URL im Browser http://loxberry.woersty/admin/index.cgi
Ich sehe die Seite vom Miniserver Backup Plugin
-Speichern klicken
URL im Browser http://loxberry.woersty/admin/plugins/miniserverbackup/index.cgi
Ich sehe die success Seite (Alles OK) vom Miniserver Backup Plugin
OK klicken
URL im Browser http://loxberry.woersty/admin/plugins/miniserverbackup/index.cgi
Ich sehe die Seite vom Miniserver Backup Plugin
Unten auf Home klicken
URL im Browser http://loxberry.woersty/admin/plugins/miniserverbackup/index.cgi
(Sollte die nicht besser auf "default" springen?)
Ich sehe das Menü 
-Miniserver Backup anklicken
URL im Browser http://loxberry.woersty/admin/plugins/miniserverbackup/index.cgi
**Ich sehe "Alles ok" => Das ist inkorrekt.** 
Es sollte die Pluginseite kommen (neu geladen)

Kannst du das soweit nachvollziehen oder ist das nur bei mir so? 
Die Plugin-nexturl ist ./index.cgi?do=form

Liebe Grüße aus Berlin
Wörsty

**Comment by Woersty** [comment]
Was auch damit zusammenhängt ist, dass er weiter backupstate.txt abfragt obwohl die Miniserver Backup Seite gar nicht mehr zu sehen ist.
Vermutlich hast das dann auch mit dem Logviewer Thema zu tun

**Comment by mschlenstedt** [comment]
Ich schaue mir das mal an - solche Phänomene habe ich auch schon festgestellt. Hängt meiner Meinung nach mit dem Cache-Verhalten vom JQUERY Mobile zusammen. Man findet dazu bei einer Googlesuche auch zahlreiche Einträge. Ich habe schon versucht über die Headerdatei das Cachen so deaktivieren - aber so richtig scheint es noch nicht gelungen zu sein.

**Comment by mschlenstedt** [comment]
Mach mal ein Pull oder füge folgenden Code in die header.html unter templates hinzu:

`<script>
    $.mobile.page.prototype.options.domCache = false;
    $(document).on('pageshow', function (event, ui) {
    // Remove the previous page
    $(ui.prevPage).remove();
    });
</script>`

Eventuell Browser-Cache vorher löschen bzw. Browser neu starten. Bei mir (getestet mit Chrome) funktioniert es damit.

Der Home-Button führt bei mir zurück ins Hauptmenü. Bei Dir nicht?

**Comment by Woersty** [comment]
Geht bei mir nicht.
Browser neu gestartet und Cache gelöscht.
Im header unter mobileinit habe ich das o.g. eingetragen.
Aber wenn ich nach 1x Speichern aus dem Hauptmenu zum Plugin zurück kehre sehe ich immer "Alles ok...."

**Comment by Woersty** [comment]
Gucke hier...
[Bug100.zip](https://github.com/mschlenstedt/Loxberry/files/439682/Bug100.zip)

**Comment by mschlenstedt** [comment]
Mmhh, bei mir geht es (siehe Anhang). Hast Du den Header genau so angepasst wie ich? Habe meine  header.html mal mit angehängt.

[bug100-2.zip](https://github.com/mschlenstedt/Loxberry/files/439893/bug100-2.zip)

(Konnte mein Video im VLC nicht anspielen, aber der Mediaplayer geht)

**Comment by Woersty** [comment]
Oh wie peinlich. Ich hatte das englische Template geändert.
Jetzt geht es. Entschuldige. :sob: 
Hatte die Freundin im Nacken sitzen und war unkonzentriert :see_no_evil:

**Comment by Woersty** [comment]
Dafür hopst das ui-content div jetzt immer hoch - ich finde aber nicht wieso.

**Comment by Woersty** [comment]
Probier mal das statt deines Schnipsels:
$(document).on("pagehide", "div[data-role=page]", function(event){
  $(event.target).remove();
});

Damit sieht es zumindestens hier besser aus.

**Comment by mschlenstedt** [comment]
Ja, sieht auch bei mir gut aus - ich pushe es gleich mal.

Ich habe übrigens noch einige Dinge zusätzlich in den Header und Footer aufgenommen, damit es konsistenter ist. Damit braucht es die einleitenden

`<div role="main" class="ui-content">......`

nicht mehr im eigentlichen Template und auch die schließenden `<div>`'s nicht mehr. Leider müssen damit die ganzen Templates in den Plugins nochmal angepasst werden. Aber besser jetzt als später.

Habe Dir für das Backup-Plugin das deutsche Template mal angehängt.

[settings.zip](https://github.com/mschlenstedt/Loxberry/files/440519/settings.zip)

**Comment by Woersty** [comment]
> Aber besser jetzt als später.

Deutsch fertig.

Mit freundlichem Gruß
Christian Wörstenfeld

---

Christian Wörstenfeld
Kalkbergeweg 10
D-12589 Berlin
Telefon: +49 30 50 15 8484
Mailbox: +49 30 55 15 1230
Fax:     +49 30 55 15 1232
Handy:   +49 30 55 15 1234
e-mail:christian@woerstenfeld.de
Threema: SV3C7MUX
Web: www.woerstenfeld.de
¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯

Am 27.08.2016 um 08:57 schrieb mschlenstedt:

**Comment by Woersty** [comment]
Gelöst mit #106
