### ISSUE TITLE
Hardcoded Path in ssdbd Daemon

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1001]
https://github.com/mschlenstedt/Loxberry/blob/35744c2dccf6235428eaa02c9cdf58b8f55e1b94/system/daemons/system/01-ssdpd#L27

Sollten wir die Service-Dateien von data eventuell nach system verschieben? Kommen ja noch weitere dazu, da finde ich ein Unterverzeichnis in system besser.

**Comment by christianTF** [comment]
Grundsätzlich ja, aber system müssen wir in Update-Scripts berücksichtigen. Das wäre zu überlegen, ob wir das wollen, oder lieber automatisch per rsync gesynct.

**Comment by mschlenstedt** [comment]
Das stimmt. Andererseits musst du den Service sowieso irgendwie per Updateskript installieren und aktivieren.

**Comment by svethi** [comment]
Bin verwundert, dass da der Pfad drinsteht ... hab ich bestimmt mal die Testdatei gepusht. Egal, das muss raus.

**Comment by christianTF** [comment]
PUSH :-)

**Comment by mschlenstedt** [comment]
Da das ein Daemin ist, müsste man einfach $LBHOME nutzen können.
