### ISSUE TITLE
Wizard not work

### ISSUE THREAD

**Issue by madito** [mschlenstedt/Loxberry#1009]
In the development branch the wizard does not work correctly, if you select a username/password different from the predefined ones, it does not show the SecurePin/root password.

**Comment by christianTF** [comment]
I couldn't reproduce this in the 2.0.0 master branch.

Behaviour:
- Chrome 77.0.xxx
- It takes a while for step 2 to step 3
- All credentials are displayed, and on top a logon dialog from Chrome appears
- I've logged on with the new credentials
- After pressing "Next Step 4", LB states, that you should reboot to extend the sd card.

What browser/os are you using?
Have you got the same login dialog from your browser?
If yes, have you entered the new credentials?
