### ISSUE TITLE
Boot without display

### ISSUE THREAD

**Issue by madito** [mschlenstedt/Loxberry#1010]
In the development branch it is necessary to add the support for the boot without display, modifying the file /boot/config.txt

Fix: Uncomment hdmi_force_hotplug=1

**Comment by christianTF** [comment]
Could not reproduce.

Image 1.5.0
I've no display attached, Pi 4 boots up normal.

**Comment by mschlenstedt** [comment]
Please test Image 2.0: https://download.loxberry.de/testing/images/rasppi/
