### ISSUE TITLE
Apt-get Update Hang: InRelease’ changed its ‘Suite’ value from ‘testing’ to ‘stable’ “error”

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1011]
http://kraaima.com/inrelease-changed-its-suite-value-from-testing-to-stable-error/

**Comment by mschlenstedt** [comment]
Betrifft uns nicht.

**Comment by mschlenstedt** [comment]
Bzw. nur uns, weil wir während testing noch auf Stable gewechselt sind.

**Comment by christianTF** [comment]
Ich mach es zur Erinnerung/Validierung wieder auf, bis es in einem neueren Image nicht mehr auftritt.

**Comment by mschlenstedt** [comment]
Kann zu, war nur ein Thema während Buster noch "testing" war.
