### ISSUE TITLE
Flags to recognize plugin changes (install, update, uninstall)

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1017]
Save timestamps (epoch) of 
- last installation
- last update
- last uninstall

of plugins to recognize changes of the plugins in a daemon. (one file at all, not one file per plugin)

Changes of plugin properties (e.g. loglevel) should _not_ trigger an update of the timestamps.

Use-Case: 
MQTT Gateway plugin monitors the other plugin directories for configuration files. 
It needs some trigger to know that a new plugin was installed, updated or uninstalled, to re-read the plugin database.

**Comment by mschlenstedt** [comment]
In die Plugin Database aufnehmen?

**Comment by christianTF** [comment]
Bist du bereit für einen Wechsel auf json?
plugindatabase wäre ziemlich einfach, man müsste nur die Lib-Funktionen nachziehen, die auch viel kleiner würden.

**Comment by mschlenstedt** [comment]
Meinst du die Plugin Database? Meinetwegen. 

Geht aber auch mit der bestehenden csv.

**Comment by mschlenstedt** [comment]
Dann bauen wir aber plugininstall auch gleich auf die Libfunktionen um. 

Aber ehrlich gesagt klingt das mit dem MQTT Plugin irgendwie nach ziemlichem gefrickel :-)

**Comment by christianTF** [comment]
Das mit der Plugindb ist nice-to-have. Änderungen an den Plugins zu erkennen, würde ermöglichen, dass die Config im MQTT-Plugin (oder in jedem Daemon, der von anderen Plugins abhängig ist) sofort erkannt wird.

Die Change-Flags sollten in der RAM-Disk als eigenes File liegen, sonst muss ich die Plugin-DB erst recht wieder von der SD lesen

Aber das im MQTT Gateway, das wird Spitze! Und ganz primitiv für‘n Plugin-Entwickler.
Es ist eigentlich auch schon fertig, muss nur noch commiten.

**Comment by mschlenstedt** [comment]
Siehe #1018

**Comment by christianTF** [comment]
Umgesetzt mit 91d420cd5592c9396294a0ebb712f3edc78d78a7
