### ISSUE TITLE
PluginDB auf JSON umstellen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1018]
siehe Titel

**Comment by christianTF** [comment]
## Adjust existing library functions 
- [x] Perl: LoxBerry::System::get_plugins
- [x] Perl: LoxBerry::System::plugindb_changed_time
- [x] PHP: get_plugins
- [x] PHP: plugindb_changed_time

## Other code accessing the plugindatabase.dat
- [x] sbin/plugininstall.pl -> Remove plugin function
- [x] sbin/plugininstall.pl -> Add and modify plugin
- [x] sbin/plugininstall.pl -> Shadow copy of plugindb
- [x] sbin/plugininstall.pl -> Sorting (not needed anymore)
- [x] sbin/pluginsupdate.pl -> Reads update urls from shadow copy
- [x] webfrontend/htmlauth/system/tools/ajax-config-handler.cgi -> Change loglevel and Autoupdate -> Include as Lib functions

## Migration
- [x] Migration script
- [x] LBUpdate script

## Things to check
- [x] Shadow file handling
- [x] File locking in LoxBerry::JSON
- [x] File locking in general
- [x] Changing loglevel and AutoUpdate in Plugin widget
- [x] Changing loglevel in Log Manager (possibly add setter to the loglevel function)
- [x] Possibly requirement of a downscaled PHP loxberry_json module
- [x] UTF-8 on read and write (Perl tends to mess up things)
- [x] Install plugin (all entries in DB?)
- [x] Update plugin (entries updated and no entries lost?)
- [x] Uninstall plugin (Plugin entry removed?)

**Comment by christianTF** [comment]
Ich mach mal ein Migrationsscript nur um das json zu erzeugen.

**Comment by christianTF** [comment]
Haupt-Commit: https://github.com/mschlenstedt/Loxberry/commit/c303bc7c929abe1af049e41f81bd5050ddc5c5a1
