### ISSUE TITLE
Migrate MQTT Gateway to Core

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1019]
Migrate the MQTT Gateway plugin to LoxBerry-Core

# Base Installation
- [x] Mosquitto installation in update script and image creation routine
- [x] Replace all lbp variables by lbs
- [x] Set new location of configuration files
- [x] Adjust logging constructors
- [x] Option to disable local Mosquitto installation
- [ ] Generate password on installation
- [x] Widget 

# Migration of installed plugins
- [x] Copy mqtt.json and cred.json
- [x] Take care of broker settings 
- [x] Disable installation (maxlb version) < ...
- [x] Uninstall plugin
- [x] Keep legacy /opt/loxberry/webfrontend/htmlauth/plugin/mqttgateway/mqtt.php

# Libraries
- [x] Enhance LoxBerry::IO and loxberry_io.php
- [x] Include PHP MQTT lib

**Comment by christianTF** [comment]
Ich setze das vorläufig auf WONTFIX.
Der Aufwand ist doch erheblicher als gedacht, insbesondere die Kompatibilität.
Außerdem brauche ich für Fixes manchmal einen schnelleren Release-Zyklus als LB-Core.

**Comment by Woersty** [comment]
Was spricht denn dagegen das als Plugin zu lassen - ich finde es gut so.￼ ich nutze es ohne Probleme.￼

**Comment by christianTF** [comment]
Changes:

### Files
| File | Old | New |
| ---- |---- | ----- |
| mqttgateway.pl | /bin/plugins/mqttgateway/mqttgateway.pl | /sbin/mqttgateway.pl | 
| Basics and Credentials | /config/plugins/mqttgateway/cred.json | /config/system/general.json |
| Subscriptions, Filters | /config/plugins/mqttgateway/mqtt.json | /config/system/mqttgateway.json |
| Logfile | /log/plugins/mqttgateway/mqttgateway.log | $lbstmpfslogdir/mqttgateway.log |
| Generic receiver | /webfrontend/html/plugins/mqttgateway/receive*.php | /webfrontend/html/mqtt/receive*.php |
| Transformers shipped | /data/plugins/mqttgateway/transform/shipped/ | /bin/mqtt/transform/shipped/ |
| Transformers custom| /data/plugins/mqttgateway/transform/custom/ | /bin/mqtt/transform/custom/ |
| Transformers datastore | /data/plugins/mqttgateway/transform/datastore/ | /bin/mqtt/datastore/ |

**Comment by mschlenstedt** [comment]
Ich lehne mich weit aus dem Fenster und mach mal zu :-)
