### ISSUE TITLE
System Status Ubersichtsseite

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#102]
Eine Übersichtsseite so in der Art würde ich gut finden:

![image](https://cloud.githubusercontent.com/assets/16830799/17996890/b47bbe52-6b6b-11e6-9251-7997a76f6c03.png)

**Comment by Woersty** [comment]
Würde ich übernehmen sobald ich mein BLE Plugin fertig habe.

**Comment by mschlenstedt** [comment]
Super!

**Comment by mschlenstedt** [comment]
Super Plugin: http://plugins.loxberry.de/plugin/rpi-monitor/
