### ISSUE TITLE
Plugin Interface: Cron.reboot

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1021]
Ergänzung des Plugininterfaces zu den Crons:
cron.reboot
(Wie die anderen Cron-Scripts)

Läuft, wie die cron.... im Kontext von loxberry mit @reboot Eintrag 

Hat den Vorteil, dass man eine Ausführung bei Reboot nicht speziell im Daemon coden muss, wo man als root unterwegs ist.

**Comment by mschlenstedt** [comment]
Meiner Meinung nach nicht notwendig. Du kannst eine komplette crontab mitliefern. Darin kannst Du alles machen, was cron unterstützt. z. B.

```
MAILTO=""
PATH=/usr/sbin:/usr/sbin:/usr/bin:/sbin:/bin

# m h  dom mon dow   command
@reboot loxberry perl $lbhomedir/bin/plugins/PLUGIN/scriptreboot > /dev/null 2>&1
```

**Comment by christianTF** [comment]
Das sind aus meiner Sicht zwei unterschiedliche Baustellen:
In crontab kann ich alles machen, muss aber für jede Änderung eine eigene Prozedur starten und die komplette Crontab neu installieren.
Auf der anderen Seite sind die vorgegebenen Crons, die ich einfach linken und unlinken kann. Einen reboot-Eintrag würde ich als Plugin-Entwickler beispielsweise nie angreifen, wenn ich den Zeitplan ändere.

Stört‘s dich, wenn ich es reinnehme?

**Comment by mschlenstedt** [comment]
Nö, passt. Wollte nur drauf aufmerksam machen, dass das heute schon geht :-)

**Comment by christianTF** [comment]
- [x] Plugininstall.pl: Copy Cronfiles
- [x] ~/system/cron/cron.d/lbdefaults
- [x] Update-Script für cron.d/lbdefaults
- [x] ~/system/cron/ Ordner
- [x] Doku Plugin Interface

**Comment by christianTF** [comment]
Implementiert mit 3337d5a91a8003606c085df05ac613775aa5eb47
