### ISSUE TITLE
Reboot: Das Sichern und/oder Rücksichern der LogDB funktioniert nicht mehr zuverlässig

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1034]
Am Pi2-DEV hatte ich das Verhalten, dass nach dem Reboot die LogDB komplett leer war, allerdings hatte ich da nicht die letzten Änderungen von Michael.

Am Pi3A - letzter Commit - bekomme ich nach dem Reboot immer eine alte Datenbank präsentiert.

Use-Case:
- LBUpdate auf letztes Commit
- Prüfen der Update Logs - Zeile ist da mit Datum 18.09.2019
- Reboot über Reboot-Widget
- Prüfen des Logs - Aktuellste Zeile ist von 17.09.2019, der Eintrag des gerade durchgeführten Updates ist weg.

Das kann nur bedeuten, dass die Datenbank beim Shutdown nicht mehr RAM->SD gesichert wird, und die Rücksicherung SD->RAM deswegen immer einen alten Stand zurückkopiert.

**Comment by christianTF** [comment]
PS: CloudDNS wird auch beim Shutdown gesichert/rückgesichert. Wenn was für die LogDB zu fixen ist, muss man das auch gleich mit berücksichtigen, sollte das auch nicht mehr gehen.

**Comment by mschlenstedt** [comment]
Wenn Du als root /opt/loxberry/createtmpfsfoldersinit.sh stop ausführst und dann rebootest, geht es dann?

Ich vermute, dass createtmpfsfoldersinit.sh beim Reboot zu spät kommt und dann die tmpfs schon alle wieder weg sind.

**Comment by mschlenstedt** [comment]
Eventuell durch diesen Eintrag verursacht:

```Conflicts=shutdown.target reboot.target halt.target```

> Conflicts=
A space-separated list of unit names. Configures negative requirement dependencies. If a unit has a Conflicts= setting on another unit, starting the former will stop the latter and vice versa. Note that this setting is independent of and orthogonal to the After= and Before= ordering dependencies.

> If a unit A that conflicts with a unit B is scheduled to be started at the same time as B, the transaction will either fail (in case both are required parts of the transaction) or be modified to be fixed (in case one or both jobs are not a required part of the transaction). In the latter case, the job that is not required will be removed, or in case both are not required, the unit that conflicts will be started and the unit that is conflicted is stopped.

**Comment by mschlenstedt** [comment]
Bitte testen. Sollte mit 671114ce6456c004c3560116161dc4e5ad20e3fb behoben sein. Achtung! Version auf 1.99 zurücksetzen, damit das 2.0er Updateskript nochmal durchläuft.

**Comment by christianTF** [comment]
Passt!
