### ISSUE TITLE
NTFS USB-Strick wird RO gemounted

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1038]
![image](https://user-images.githubusercontent.com/14220265/65393377-058a1a80-dd80-11e9-9a21-9b629976fe9b.png)

![image](https://user-images.githubusercontent.com/14220265/65393351-ceb40480-dd7f-11e9-90ad-622f6cf35a53.png)

[usbstorage_debug.log](https://github.com/mschlenstedt/Loxberry/files/3640088/usbstorage_debug.log)

**Comment by mschlenstedt** [comment]
Schau mal in Dein Log...

```
[   43.295397] ntfs: driver 2.1.32 [Flags: R/W MODULE].
[   43.450784] ntfs: volume version 3.1.
[   43.457235] ntfs: (device sda1): load_system_files(): $LogFile is not clean.  Mounting read-only.  Mount in Windows.
```

**Comment by christianTF** [comment]
ntfs-3g ins Update aufgenommen: 98821ceb6537f670fea4b3915d733823158e1cf4
Scheint besser zu funktionieren als der Kernel-Treiber

**Comment by christianTF** [comment]
Bei mir und Bullit funktionierts.
