### ISSUE TITLE
Browser cached Update-Webseite

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1040]
Ich habe schon einmal einige Dinge von https://stackoverflow.com/questions/49547/how-do-we-control-web-page-caching-across-all-browsers implementiert.

Andere Idee:

Per Javascript URL-Parameter kontrollieren und ohne sessrand=.... die Update-Webseite sofort reloaden mit index.cgi?sessrand=blah

Nach erfolgreichem Update nicht auf Update-Logseite umleiten sondern auf index.cgi mit anderer/geänderter ?sessrand=...

https://html-online.com/articles/get-url-parameters-javascript/.

**Comment by mschlenstedt** [comment]
Habe mir noch einmal Gedanken gemacht. Mein Vorschlag wäre:

1. Im Updatereboot-Script setzen wir einen Update-Flag, der per Webserver abrufbar ist
2. power.cgi (power.html) prüft auf das Update-Flag. Ist es vorhanden, wird nicht auf "/" reloaded, wenn der LB wieder erreichbar ist, sondern auf "/updatereboot": https://github.com/mschlenstedt/Loxberry/blob/c49fcd7f099b698020df42015cb7359ebe105fa4/templates/system/power.html#L135

Damit wäre der Update-Webserver gar nicht unter "/" aufgerufen und landet somit auch nicht im Cache.

**Comment by mschlenstedt** [comment]
@christianTF  Baust Du das Javascript in power.hrml dazu (Zeile 135)?

Flag ist /updaterunning mit JSON-Inhalt:

https://github.com/mschlenstedt/Loxberry/blob/master/templates/system/reboot_updaterunning_flag.html

**Comment by mschlenstedt** [comment]
@christianTF  Hat sich schon erledigt - Danke trotzdem ;-) Habe es noch vereinfacht und hier als Test schon laufen.

**Comment by christianTF** [comment]
Update Pi3A -> NOK (Seite weiterhin im Cache)
Update VM -> NOK (Seite weiterhin im Cache)
Lösung in Chrome: Wenn die Seite (kurz) angezeigt wird, das Lade-X-Drücken, danach Shift-Aktualisieren.

**Comment by mschlenstedt** [comment]
Änderungen sind noch nicht committed.

**Comment by mschlenstedt** [comment]
Gelöst mit 0fdbb30518703467fc7acefc576991a6ba8b47d1
