### ISSUE TITLE
CPU Temp beim Healthcheck

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1047]
Ist noch nicht ganz behoben. Temp wird jetzt ohne den Watchdog zu konfigurieren angezeigt, aber der Text passt nicht.

![image](https://user-images.githubusercontent.com/16830799/65811072-569c7300-e1b3-11e9-849b-16cbc7c17041.png)

**Comment by christianTF** [comment]
Von AlexAn
![image](https://user-images.githubusercontent.com/14220265/66750203-211ea780-ee8c-11e9-80cd-ab342dac3a49.png)
