### ISSUE TITLE
Pip Und pip3 File im dpkg-Plugin-Ordner 

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1050]
Um Python/Python3 Libs - so wie derzeit mit apt - bei der Plugin-Installation mitzuinstallieren.

**Comment by mschlenstedt** [comment]
Ist das wirklich notwendig? Zahlreiche Python-Libs gibt es als apt-Pakete. Den Rest macht man über postinstall.sh. Oder?

**Comment by mschlenstedt** [comment]
Machen wir nicht - zuviele Probleme mit Python/PIP nach dist-upgrade. Muss sich jeder Pluginautor selbst drum kümmern.
