### ISSUE TITLE
LB2.0: Vor Release Updatescript umstellen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1054]
Umstellen von "latest" auf "release":

https://github.com/mschlenstedt/Loxberry/blob/9976b5a35814205376e7cb3b8b59c75ba63719e2/sbin/loxberryupdate/updatereboot_v2.0.0.pl#L333

**Comment by christianTF** [comment]
Jetzt wird aus der general.cfg ausgelesen, was dort als Updatetype eingestellt ist, und damit weitergemacht.
