### ISSUE TITLE
LoxBerry Wizard-Titelbild gegen Zitronenbild tauschen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1055]
Und bei Release auch im Wiki tauschen.

**Comment by christianTF** [comment]
Animation bereitet Probleme, weil da im Chrome was auf deprecated gesetzt wurde.

![LB_V2_650](https://user-images.githubusercontent.com/14220265/66437276-a1c34b00-ea29-11e9-8582-43ec1a3fee46.png)
![LB_V2_1100](https://user-images.githubusercontent.com/14220265/66437277-a25be180-ea29-11e9-9db4-372635f81832.png)

[LBV2.zip](https://github.com/mschlenstedt/Loxberry/files/3704730/LBV2.zip)

**Comment by christianTF** [comment]
![LB_V2_1100](https://user-images.githubusercontent.com/14220265/66437837-26629900-ea2b-11e9-8288-5189badd210a.png)
[LBV2.zip](https://github.com/mschlenstedt/Loxberry/files/3704762/LBV2.zip)
![LB_V2_650](https://user-images.githubusercontent.com/14220265/66437838-26629900-ea2b-11e9-8ae9-0c768f2d9d27.png)

**Comment by mschlenstedt** [comment]
@Woersty  Bauste was?

https://github.com/mschlenstedt/Loxberry/tree/master/webfrontend/html/system/splash
