### ISSUE TITLE
Wenn Update fehl schlägt, dann kein Reboot

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1056]
Wenn das Updatescript einen Fehler ausgibt, sollte kein Zwangsreboot stattfinden. Macht keinen Sinn, da der LB anschließend sowieso zurückgesetzt werden muss.

![image](https://user-images.githubusercontent.com/16830799/66447258-2a53e280-ea4e-11e9-9474-b68883ec46a6.png)

**Comment by christianTF** [comment]
Ich fixe das nicht, weil das bedeuten würde, dass ich im 30-Sekunden-Takt die general.cfg lesen müsste.
Bisher reduzieren sich die Dateioperationen auf Prüfen auf Existenz zweier Files in der Ramdisk.

Das ist dann halt einfach Pech, wenn der User erst rebootet, und nachher nochmal muss.
