### ISSUE TITLE
Forum: Pi3 bootet nicht mit 2.0 Image

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1059]
https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/213419-vorankündigung-loxberry-2-0-bitte-lesen?p=215584#post215584

**Comment by mschlenstedt** [comment]
Komisch, auf einem Pi2 und einem Pi4 geht's, und ein Pi3 soll nicht funktionieren?! Ich schaue es mir an.

**Comment by christianTF** [comment]
Pi 3: Nicht reproduzierbar, funktioniert wie gewünscht.
