### ISSUE TITLE
Forum: zram Fehler in VM

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1062]
Eigenes Image/VM, zram buffer Error

https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/213419-vorankündigung-loxberry-2-0-bitte-lesen?p=214319#post214319

**Comment by mschlenstedt** [comment]
Der Link oben scheint falsch zu sein - finde leider den Post auch nicht über die Suche.

Aber VM ist VM und nicht Raspi, oder?

**Comment by christianTF** [comment]
Ich teste das implizit mit der Virtual Box (ehem. Svens VMware) VM mit.
Wenn's nix gibt, schließ ich es eh wieder - mehr können wir nicht testen.

**Comment by mschlenstedt** [comment]
Bei @svethi  nicht aufgetreten. Außerdem gibt es ein FallBack auf tmpfs, wenn zram vom Kernel nicht unterstützt wird.

Wer weiß, was das für eine VM war....
