### ISSUE TITLE
Forum: Mail senden geht nach Update nicht

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1063]
Nach Update
Test Mail geht wahrscheinlich, Notify-Mail nicht

https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/213419-vorankündigung-loxberry-2-0-bitte-lesen?p=213962#post213962

**Comment by christianTF** [comment]
Alle Tests als `loxberry`

## Raspberry 3A+
### 1.4.2
- [x] OK -> Mailsettings korrekt
- [x] OK -> Notify (unten) alles aktiviert
- [x] OK -> Testmail geht
- [x] OK -> /opt/loxberry/libs/perllib/LoxBerry/testing/test_htmlmail.pl (1 Mail)
- [x] OK -> /opt/loxberry/libs/perllib/LoxBerry/testing/notif.pl (2 Mails)
- [x] OK -> /opt/loxberry/libs/phplib/testing/testnotify.php (2 Mails)

### 2.0.x
- [x] OK-> Mailsettings korrekt
- [x] OK -> Notify (unten) alles aktiviert
- [x] OK -> Testmail geht
- [x] OK -> /opt/loxberry/libs/perllib/LoxBerry/testing/test_htmlmail.pl
- [x] OK -> /opt/loxberry/libs/perllib/LoxBerry/testing/notif.pl
- [x] OK -> /opt/loxberry/libs/phplib/testing/testnotify.php (2 Mails)

## VMWare VM
### 1.4.2
- [x] OK -> Mailsettings korrekt
- [x] OK -> Notify (unten) alles aktiviert
- [x] OK -> Testmail geht
- [x] OK -> /opt/loxberry/libs/perllib/LoxBerry/testing/test_htmlmail.pl
- [x] OK -> /opt/loxberry/libs/perllib/LoxBerry/testing/notif.pl
- [x] OK -> /opt/loxberry/libs/phplib/testing/testnotify.php (2 Mails)

### 2.0.x
- [x] Mailsettings korrekt
- [x] Notify (unten) alles aktiviert
- [x] OK -> Testmail geht
- [x] OK -> /opt/loxberry/libs/perllib/LoxBerry/testing/test_htmlmail.pl
- [x] OK -> /opt/loxberry/libs/perllib/LoxBerry/testing/notif.pl
- [x] OK -> /opt/loxberry/libs/phplib/testing/testnotify.php (2 Mails)

**Comment by christianTF** [comment]
![image](https://user-images.githubusercontent.com/14220265/66685935-24444880-ec7e-11e9-8608-6724b38e346b.png)
Offenbar gleich nach dem Update

![image](https://user-images.githubusercontent.com/14220265/66686120-a5034480-ec7e-11e9-9b1b-51ba7c8d1e98.png)

Irgendein Permission-Fehler
![image](https://user-images.githubusercontent.com/14220265/66686336-691caf00-ec7f-11e9-947b-0f95028e9f8d.png)

Das .msmtprc File kann von `loxberry` über den Symlink bearbeitet werden (mit nano probiert)
![image](https://user-images.githubusercontent.com/14220265/66686467-df211600-ec7f-11e9-826c-55f507b171ed.png)

![image](https://user-images.githubusercontent.com/14220265/66686647-653d5c80-ec80-11e9-9763-1f9e76ab5ef7.png)

Test per Shell:
![image](https://user-images.githubusercontent.com/14220265/66686933-47242c00-ec81-11e9-9825-65b67299cd05.png)

**Comment by christianTF** [comment]
Sorry, ich weiß nicht weiter

**Comment by christianTF** [comment]
Keinen Plan. Alle Permissions durchprobiert....
Nur wenn ich das Configfile auf `/etc/msmtprc` kopiere, funktionierts.

**Comment by mschlenstedt** [comment]
Ich denke eher, dass Root die Mail verschicken will. Und da das Configfile im Homeverzeichnis von loxberry liegt (/opt/loxberry/.msmtprc), gilt es auch nur für den User loxberry. Root hat damit kein Configfile und die Email kann nicht gesendet werden. Er meckert oben in Deinen Screenshots auch, dass er das Configfile nicht findet.

/etc/msmtprc scheint dann das Systemweite Configfile zu sein. Ich meine mich zu erinnern, dass aber loxberry das nicht verwendet. Weiß ich aber nicht mehr genau.

Ich teste mal.

**Comment by mschlenstedt** [comment]
Ah, sehe jetzt erst, dass er beim Senden der Testmail bei Dir über die Permissions meckert. Bei mir aber nicht!

![image](https://user-images.githubusercontent.com/16830799/66695686-e585b100-ecc4-11e9-9200-559b2f0fedbe.png)

Einrichtung aber erst nach Upgrade. Permissions sehen aber auch so aus wie bei Dir?!

![image](https://user-images.githubusercontent.com/16830799/66695707-22ea3e80-ecc5-11e9-9e3a-ac37f642f2e7.png)

**Comment by mschlenstedt** [comment]
@christianTF  Ah, der Symlink gehört bei Dir Root! Das kommt vom Upgrade. Chowne den mal auf loxberry:loxberry.

**Comment by mschlenstedt** [comment]
Trotz Fix in 63a1cdbfe102f0922ea093f7ca880c1be5c31512 wird der Link immer noch mit root:root angelegt. Chown geht vermutlich so bei SymLinks nicht.

![image](https://user-images.githubusercontent.com/16830799/66699559-3ce94880-ece8-11e9-8c44-e665f0db297d.png)

**Comment by mschlenstedt** [comment]
> If you'd like to change ownership of the link itself, you need to use the -h option to chown

https://unix.stackexchange.com/questions/218557/how-to-change-ownership-from-symbolic-links

**Comment by christianTF** [comment]
Ich hatte das probiert, hat aber nicht geholfen. Restart Hab ich aber nicht gemacht, ich weiß nicht - ist msmtp ein Service?

**Comment by mschlenstedt** [comment]
Nein, kein Service. Hast Du wirklich "chown -h ....." gemacht? Der Symlink muss loxberry:loxberry sein, nicht nur das Ziel!

**Comment by mschlenstedt** [comment]
Ist gefixt. @christianTF  Musst Deine Tests oben noch machen oder Issue zumachen bitte.

**Comment by christianTF** [comment]
Funktioniert weiterhin nicht in der VM nach Update 1.4.2.2->2.0.0.1

**Comment by mschlenstedt** [comment]
Ist doch oben alles abgehakt?!

**Comment by mschlenstedt** [comment]
apparmor auf x64 Systemen nach Upgrade deinstallieren.

**Comment by christianTF** [comment]
apparmor wird jetzt deinstalliert in updatereboot_v2.0.0.pl 65e70517ef58839819ac5c0093a6eb8570188fe3
