### ISSUE TITLE
Forum: Mosquitto startet nicht nach Update

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1064]
Nach dem Update startet der Mosquitto nicht mehr, wenn man LB  gebootet

https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/213419-vorankündigung-loxberry-2-0-bitte-lesen?p=213577#post213577

https://www.loxforum.com/forum/projektforen/loxberry/plugins/176025-loxberry-mqtt?p=214727#post214727

https://www.loxforum.com/forum/projektforen/loxberry/plugins/176025-loxberry-mqtt?p=214922#post214922

https://www.loxforum.com/forum/projektforen/loxberry/plugins/176025-loxberry-mqtt?p=215485#post215485

**Comment by mschlenstedt** [comment]
Das Logverzeichnis wird nach dem upgrade auf Buster zu spät angelegt.

```Oct 10 06:47:54 loxberry mosquitto[922]: 1570682874: Error: Unable to open log file /var/log/mosquitto/mosquitto.log for writing.```

**Comment by mschlenstedt** [comment]
Mmmhh, kann aber eigentlich nicht sein, da Mosquitto ja anscheinend als Daemon gestartet wird und somit vom loxberryinit.sh gestartet wird:

```Oct 10 06:47:52 loxberry loxberry[529]: run-parts: executing /opt/loxberry/system/daemons/plugins/mqttgateway
Oct 10 06:47:53 loxberry systemd[1]: Starting Mosquitto MQTT v3.1/v3.1.1 Broker...
Oct 10 06:47:53 loxberry mosquitto[916]: Loading config file /etc/mosquitto/conf.d/mqttgateway.conf
Oct 10 06:47:53 loxberry mosquitto[916]: 1570682873: Error: Unable to open log file /var/log/mosquitto/mosquitto.log for writing.```

**Comment by mschlenstedt** [comment]
Muss ein Berechtigungsproblem sein.

**Comment by mschlenstedt** [comment]
Ah, der Mosquitto scheint auch früher im Bootprozess schon einmal über ein Service-File gestartet zu werden. Das kommt zu früh, sodass das Logverzeichnis noch nicht existiert. Das sieht man hier:

```Oct 10 06:47:14 loxberry mosquitto[478]: 1570682834: Error: Unable to open log file /var/log/mosquitto/mosquitto.log for writing.
Oct 10 06:47:14 loxberry systemd[1]: mosquitto.service: Main process exited, code=exited, status=1/FAILURE
Oct 10 06:47:14 loxberry systemd[1]: mosquitto.service: Failed with result 'exit-code'.
Oct 10 06:47:14 loxberry systemd[1]: Failed to start Mosquitto MQTT v3.1/v3.1.1 Broker.
Oct 10 06:47:14 loxberry wpa_supplicant[490]: Successfully initialized wpa_supplicant
Oct 10 06:47:14 loxberry kernel: EXT4-fs (zram0): mounted filesystem with ordered data mode. Opts: (null)
Oct 10 06:47:14 loxberry createtmpfs[203]: Creating temporary system folders...
Oct 10 06:47:14 loxberry createtmpfs[203]: Creating folders in /opt/loxberry/log/ramlog...
Oct 10 06:47:14 loxberry systemd[1]: mosquitto.service: Service RestartSec=100ms expired, scheduling restart.
Oct 10 06:47:14 loxberry systemd[1]: mosquitto.service: Scheduled restart job, restart counter is at 4.
Oct 10 06:47:14 loxberry systemd[1]: Stopped Mosquitto MQTT v3.1/v3.1.1 Broker.
Oct 10 06:47:14 loxberry systemd[1]: Starting Mosquitto MQTT v3.1/v3.1.1 Broker...
Oct 10 06:47:14 loxberry kernel: random: crng init done
Oct 10 06:47:14 loxberry kernel: random: 7 urandom warning(s) missed due to ratelimiting
Oct 10 06:47:14 loxberry mosquitto[501]: Loading config file /etc/mosquitto/conf.d/mqttgateway.conf
Oct 10 06:47:14 loxberry mosquitto[501]: 1570682834: Error: Unable to open log file /var/log/mosquitto/mosquitto.log for writing.
Oct 10 06:47:14 loxberry systemd[1]: mosquitto.service: Main process exited, code=exited, status=1/FAILURE
Oct 10 06:47:14 loxberry systemd[1]: mosquitto.service: Failed with result 'exit-code'.
Oct 10 06:47:14 loxberry systemd[1]: Failed to start Mosquitto MQTT v3.1/v3.1.1 Broker.
Oct 10 06:47:14 loxberry createtmpfs[203]: Binding systemfolders to temporary folders in /opt/loxberry/log/ramlog...
Oct 10 06:47:14 loxberry createtmpfs[203]: Restoring Syslog and LoxBerry system log folders...
Oct 10 06:47:14 loxberry systemd[1]: mosquitto.service: Service RestartSec=100ms expired, scheduling restart.
Oct 10 06:47:14 loxberry systemd[1]: mosquitto.service: Scheduled restart job, restart counter is at 5.
Oct 10 06:47:14 loxberry systemd[1]: Stopped Mosquitto MQTT v3.1/v3.1.1 Broker.
Oct 10 06:47:14 loxberry systemd[1]: mosquitto.service: Start request repeated too quickly.
Oct 10 06:47:14 loxberry systemd[1]: mosquitto.service: Failed with result 'exit-code'.
Oct 10 06:47:14 loxberry systemd[1]: Failed to start Mosquitto MQTT v3.1/v3.1.1 Broker.```

**Comment by mschlenstedt** [comment]
Berechtigungen auf 1.4.2:

```drwxr-xr-x 2 mosquitto        root          60 Oct  5 07:34 mosquitto```

Berechtigungen auf 2.0.0.1:

```drwxr-xr-x 2 loxberry loxberry   4096 Oct 10 06:47 mosquitto```

**Comment by mschlenstedt** [comment]
Irgendetwas bügelt die Berechtigungen in skel_syslog kaputt:

![image](https://user-images.githubusercontent.com/16830799/66621866-eeec1c00-ebe5-11e9-8e33-bcaea9c12897.png)

So sieht das auf einem 1.4.2 aus und muss auch so sein:

![image](https://user-images.githubusercontent.com/16830799/66621905-0aefbd80-ebe6-11e9-89f8-f7c049128497.png)

**Comment by mschlenstedt** [comment]
So, mit den korrekten Berechtigungen des Logfolders startet auch der Mosquitto wieder. 

Das Service-File sollten wir trotzdem noch anpassen, da der Mosquitto jetzt erst über den Daemon gestartet wird. Das sollte wieder direkt mit dem eigentlichen Servicefile gemacht werden.

Jetzt müssen wir herausfinden, wer die Berechtigungen in skel_syslog beim Upgrade mit loxberry:loxberry überschrieben hat.

**Comment by mschlenstedt** [comment]
Nach rsync/resetpermissions alles noch OK.

![image](https://user-images.githubusercontent.com/16830799/66699060-c9453c80-ece3-11e9-8520-7a3f9c32e74b.png)

**Comment by mschlenstedt** [comment]
Nach /opt/loxberry/sbin/loxberryupdate/update_v2.0.0.pl alles noch OK.

![image](https://user-images.githubusercontent.com/16830799/66699161-95b6e200-ece4-11e9-9cd9-4bbddbdf37f5.png)

**Comment by mschlenstedt** [comment]
Nach Reboot alles noch OK.

![image](https://user-images.githubusercontent.com/16830799/66699208-f9d9a600-ece4-11e9-80b6-cad7dbddc256.png)

**Comment by mschlenstedt** [comment]
Nach updatereboot_v2.0.0.pl und Reboot NICHT OK:

![image](https://user-images.githubusercontent.com/16830799/66700573-1cbe8700-ecf2-11e9-9b70-3db96018068d.png)

Irgendwann nach dem Firmware-Update muss es passiert sein. Bis dahin alles ok. Eventuell werdne auch die Permissions in /var/log überschrieben. Das wird dann ja nur nach skel_syslog gespiegelt.

**Comment by mschlenstedt** [comment]
Gelöst mit 09a11ad1aa7d5eaa6a87ea080b62966933e014df
