### ISSUE TITLE
Forum: LMS geht nicht mehr nach Update

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1065]
LMS nach Update nicht mehr erreichbar, Plugin sagt, LMS läuft

https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/213419-vorankündigung-loxberry-2-0-bitte-lesen?p=215719#post215719

**Comment by mschlenstedt** [comment]
![image](https://user-images.githubusercontent.com/16830799/66623073-6a4fcc80-ebea-11e9-9823-e0e976c42622.png)

**Comment by mschlenstedt** [comment]
https://forums.slimdevices.com/showthread.php?109707-perl-5-28-support

https://github.com/Logitech/slimserver/pull/209

**Comment by mschlenstedt** [comment]
Update auf Plugin 0.1.4.0 notwendig. Es muss auf LMS 7.9.2 nightly build (von 7.9.1) upgedatet werden wegen neuer Perl-Version 5.28 (Stretch: 5.26).
