### ISSUE TITLE
Network Templates

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1066]
Sind die jetzt überhaupt noch nötig oder kann das aus dem Uupdate raus? Ich steig da nicht mehr durch...

https://github.com/mschlenstedt/Loxberry/blob/ce60d5b2811fb4e96a6039dfb800f458e175533b/sbin/loxberryupdate/update_v2.0.0.pl#L33

**Comment by christianTF** [comment]
Passt so wie es ist:
Wir löschen alle nicht mehr benötigten Templates in `$lbhomedir/system/network`, weil die aktuellen Templates jetzt in `$lbhomedir/templates/system/network/` liegen und damit automatisch per rsync ausgerollt werden.
