### ISSUE TITLE
Power-handler.php: Falscher json-Status bei Reboot, deswegen startet Laufleiste nicht

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1069]
![image](https://user-images.githubusercontent.com/14220265/66685494-06c2af00-ec7d-11e9-9d96-8d995c8e87e5.png)

Es ist fast so, als käme das auch aus dem Cache. Sobald Shift-F5, rebootet LB sofort und es kommt ein Fehler.

**Comment by christianTF** [comment]
![image](https://user-images.githubusercontent.com/14220265/66685659-75a00800-ec7d-11e9-8bd3-430e14989869.png)

Kommt wirklich vom Cache, während LB schon rebootet. Drecks-Chrome.

**Comment by mschlenstedt** [comment]
Bei mir alles OK.

**Comment by mschlenstedt** [comment]
Also ich habe jetzt 3 updates durch und bei keinem trat das Thema noch auf.

**Comment by christianTF** [comment]
Na dann 😀
