### ISSUE TITLE
Plugin-Idee: Bei Klingeln Mail mit Kamerabild als Anhang

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#107]
Aus dem Forum: https://www.loxforum.com/forum/hardware-zubehör-sensorik/19159-vorstellung-loxberry-projekt-und-umfrage?p=53990#post53990

Könnte ich auch gebrauchen, finde das daher eine gute Idee. Videobild könnte man mit VLC grabben.

**Comment by Woersty** [comment]
Kann mein cam-connect Plugin miterledigen.
Ich passe es an.

**Comment by mschlenstedt** [comment]
Super!

Ich baue gerade noch einen Mailserver (Ausgang) mit ein, damit Skripte direkt per sendmail Mails rausschicken können. 

Finde ich besser als wenn jedes Plugin das selbst mitbringen muss.

**Comment by Woersty** [comment]
Kann für LoxBerry geschlossen werden. Mache ich auf Plugin-Seite fertig.
https://github.com/Woersty/LoxBerry-Plugin-cam-connect/issues/1

**Comment by mschlenstedt** [comment]
Und zu.
