### ISSUE TITLE
generatelegacytemplates wirft Warnung aus

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1070]
Daher warnt LBUpdate, dass Fehler im update aufgetreten sind.

```12:50:03.568 INFO: Updating LoxBerry legacy templates...
generatelegacytemplates.pl: Forcing creation of new templates.
generatelegacytemplates.pl: Checking language /opt/loxberry/templates/system/lang/language_cs
generatelegacytemplates.pl: Cannot open /opt/loxberry/templates/system/cs/header.html. File will be created.
[Sun Oct 13 12:50:05 2019] generatelegacytemplates.pl: stat() on closed filehandle $tmpllang_fh at /opt/loxberry/webfrontend/htmlauth/system/tools/generatelegacytemplates.pl line 89.
[Sun Oct 13 12:50:05 2019] generatelegacytemplates.pl: Use of uninitialized value in numeric lt (<) at /opt/loxberry/webfrontend/htmlauth/system/tools/generatelegacytemplates.pl line 89.
generatelegacytemplates.pl: Cannot open /opt/loxberry/templates/system/cs/footer.html. File will be created.
[Sun Oct 13 12:50:05 2019] generatelegacytemplates.pl: stat() on closed filehandle $tmpllang_fh at /opt/loxberry/webfrontend/htmlauth/system/tools/generatelegacytemplates.pl line 89.
[Sun Oct 13 12:50:05 2019] generatelegacytemplates.pl: Use of uninitialized value in numeric lt (<) at /opt/loxberry/webfrontend/htmlauth/system/tools/generatelegacytemplates.pl line 89.
generatelegacytemplates.pl: Cannot open /opt/loxberry/templates/system/cs/success.html. File will be created.
[Sun Oct 13 12:50:05 2019] generatelegacytemplates.pl: stat() on closed filehandle $tmpllang_fh at /opt/loxberry/webfrontend/htmlauth/system/tools/generatelegacytemplates.pl line 89.
[Sun Oct 13 12:50:05 2019] generatelegacytemplates.pl: Use of uninitialized value in numeric lt (<) at /opt/loxberry/webfrontend/htmlauth/system/tools/generatelegacytemplates.pl line 89.
generatelegacytemplates.pl: Cannot open /opt/loxberry/templates/system/cs/error.html. File will be created.
[Sun Oct 13 12:50:05 2019] generatelegacytemplates.pl: stat() on closed filehandle $tmpllang_fh at /opt/loxberry/webfrontend/htmlauth/system/tools/generatelegacytemplates.pl line 89.
[Sun Oct 13 12:50:05 2019] generatelegacytemplates.pl: Use of uninitialized value in numeric lt (<) at /opt/loxberry/webfrontend/htmlauth/system/tools/generatelegacytemplates.pl line 89.
generatelegacytemplates.pl: Language /opt/loxberry/templates/system/lang/language_cs WILL BE RE-CREATED
max_tmpl_epoch: 1570954100 min_tmpllang_epoch: 0
[Sun Oct 13 12:50:05 2019] generatelegacytemplates.pl: HTML::Template->new() : can't mkdir /tmp/templatecache (file_cache => 1): Permission denied at /opt/loxberry/libs/perllib/LoxBerry/Web.pm line 122.
12:50:05.156 WARNING: generatelegacytemplates returned errorcode 13. Despite errors loxberryupdate.pl will continue.
12:50:05.157 INFO: Updating Skels for Logfolders...
12:50:06.277 OK: Skels for Logfolders successfully updated.
12:50:06.278 INFO: LoxBerry's config version is updated from v2.0.0 to v2.0.0.1
12:50:06.278 INFO: Commit SHA is updated to 8ba78c73ba0977ce32bd1e9b8637faa106464a3a
12:50:06.290 INFO: Cleaning up temporary download folder
12:50:06.745 INFO: All procedures finished.
12:50:10.097 WARNING: LoxBerry Update was SUCCESSFULL, but skipped at least 1 warnings or errors. Check the log.```

**Comment by mschlenstedt** [comment]
Vielleicht wirklich irgendwas mit meinem Image:

![image](https://user-images.githubusercontent.com/16830799/66728002-ca40b000-ee42-11e9-8a6d-2986208a61fc.png)

Auf dem LB2.0.0.1 meckert wer jedenfalls nicht.

**Comment by christianTF** [comment]
![image](https://user-images.githubusercontent.com/14220265/66731520-10ecd500-ee58-11e9-8995-d4aaa776440e.png)

Irgendeine Änderung des Setzens der Permissions in den letzten 2 Tagen bewirkt, dass die Templates jetzt root gehören, statt loxberry.

**Comment by christianTF** [comment]
Also was ich *vermute*:
Schon vor dem lbupdate-Aufruf in updatereboot melden Installationen, dass sie in /tmp nicht schreiben können:
![image](https://user-images.githubusercontent.com/14220265/66779046-9d85aa80-eecd-11e9-902f-bd4f1a6cf0c6.png)


Das generatelegacytemplate im lbupdate-Aufruf im updatereboot scheitert, weil loxberry keine Rechte hat, in /tmp den Templatecache anzulegen.
![image](https://user-images.githubusercontent.com/14220265/66778590-695dba00-eecc-11e9-8d8a-3970cb3d3ccb.png)

Dann passiert auch noch etwas, nämlich lbupdate startet generatelegacytemplate als root.
Der Aufruf ist eigentlich https://github.com/mschlenstedt/Loxberry/blob/4c5fb752ed66100e5d81f0373aa7b8ba400acfce/sbin/loxberryupdate.pl#L453
Dass die neuen Legacytemplates erst von generatelegacytemplates erzeugt werden, ist deswegen fix, weil wir diese Templates gar nicht mitliefern, und diese von rsync vorher weggeräumt werden.

Also entweder funktioniert alles zusammen deswegen nicht, weil /tmp nicht schreibbar ist (und als Folgefehler su auch nicht funktioniert), oder es liegt am --nofork bei lbupdate, oder es braucht vorher einen Reboot wegen irgendwas. 

@mschlenstedt Das mit /tmp könntest du dir das ansehen, vielleicht löst das alle weiteren Probleme.

**EDIT:** Mit dem LB20-Image, wo man LB-Update ganz normal via WebIf ausführt, funktioniert es richtig. Es kann nur am Processing über updatereboot liegen.

**Comment by mschlenstedt** [comment]
Ist nach der apt-get Orgie eventuell die Ramdisk voll? /tmp liegt in der Ramdisk und apt cached ja alles irgendwo in /var/cache.

**Comment by mschlenstedt** [comment]
Erledigt mit Fortsetzen des Updates nach einem Reboot nach dist-upgrade: f58c5d984573578bcc4ca36ed816d8b7059c8cda
