### ISSUE TITLE
IPv6: DUID should not change on reboot

### ISSUE THREAD

**Issue by emes** [mschlenstedt/Loxberry#1072]
A "static" DHCPv6 lease is configured using the host's DUID (like the hw-mac address is used for DHCPv4).

Currently the DUID is being regenerated on reboot.  This appears to be because /var/lib/dhcp has been linked to /tmp, so the lease files are lost with each reboot.  ISC DHCPv6 client stores the DUID in the dhclient6 lease file.  I'm not sure if that link was intentional or something specific to my host from the upgrade.  Happy to test when a 2.0 install image is available.  In any case the DUID has to be stable.

**Comment by christianTF** [comment]
@mschlenstedt emes is right, we should consider to revoke the symlink from /var/lib/dhcp as it stores the lease information from dhcp, or we backup and restore the information on every reboot.

Myself I have issues with the VM, getting a new ip address after reboot (dnsmasq is dhcp server). Requesting a new ip address at boot time from the same mac might be recognized by the dhcp server (giving the same ip), but might be not. In the case of a lease renew with a known ip, the dhcp server more likely will assign the same ip.

The write frequency of the *.leases file is dependent to the dhcp server lease time. It is `leasetime/2`. So it is not predictable how often the file is written.

**Comment by christianTF** [comment]
Hi emes,

in the "Latest" master, I've added a backup and restore routine for the *.leases files of dhcp, that runs on startup and shutdown.

I couldn't clearly figure out if dhcp is using the restored file (it seems so from the file content).

Would you test this, by updating to the "Latest commit" in LoxBerry Update (or LB2.2 Pre-Release, as soon as we have released) and test this in your configuration.

Thanks!
Christian

**Comment by emes** [comment]
Hey @christianTF I updated to v2.2.0.0 and duid remained stable.  Thanks!

**Comment by christianTF** [comment]
Thanks for the feedback!
I try to figure out the other ipv6 things before the final LB2.2 release.
