### ISSUE TITLE
Forum: BLE Plugin funktioniert nicht

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1075]
https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/213419-vorankündigung-loxberry-2-0-bitte-lesen?p=216249#post216249

> Hallo,
habe heute LB 2.0 auf einem Rasp 4 installiert, danach das BLE Plugin installiert. Leider kommt folgender Fehler:
"Fehler0003: Daemon Prozess läuft (noch) nicht"
Das war mit dem Rasp 3B+ auch schon ein Fehler, auf einem 3B lief es ohne Problme, auch jetzt nach dem SW-Update auf 2.0. Wäre sehr schade, wenn auch mit Rasp 4 BLE 5.0 nicht gehen würde.
Gruß, Johny.

Problem mit dem Bluetooth-Modul auf 3B+ und 4?

**Comment by mschlenstedt** [comment]
https://www.loxforum.com/forum/projektforen/loxberry/plugins/68266-loxberry-ble-scanner?p=227671#post227671

**Comment by svethi** [comment]
Das Problem ist nicht das Plugin. Die Einbindung des BT im Betriebssystem (Buster) ist derzeit noch auf sehr wackeligen Füßen. Bei vielen funktioniert das BT gar nicht. Auf unserem Testsystem startet es zwar, es hängt aber an einigen Ecken und der Versuch (vom Plugin z.B., oder auch manuell) den Dienst neu zu starten schlägt mit timeout fehl. Ob es sich hier um ein Firmware oder Treiberproblem handelt kann derzeit nicht gesagt werden. Es muss auf alle Fälle erst einmal korrekt im Buster integriert werden.

**Comment by Woersty** [comment]
https://www.loxforum.com/forum/projektforen/loxberry/plugins/68266-loxberry-ble-scanner?p=235694#post235694

**Comment by Woersty** [comment]
Ich kann mangels 4er RPi nix testen

**Comment by christianTF** [comment]
Was brauchst du denn?
Ich hab einen Pi4 via Remote Support dauerhaft im VPN.
Oder brauchst einen Pi4?

**Comment by Woersty** [comment]
Muss ich mal sehen. Melde mich per WhatsApp

**Comment by mschlenstedt** [comment]
Ich mach zu.
