### ISSUE TITLE
LBUpdate Funktion für Major Releases

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1078]
> Vielleicht bauen wir dazu noch eine Funktion in lbupdate ein. Ich könnte mir vorstellen, dass lbupdate ein Notify absetzt, wenn es neuere Updates findet als aktuell erlaubt sind. Dann muss der User einmal aktivieren, dass er auch Major Updates zulassen will. Hat er das aktiviert, wird einfach per wget das neue lbupdate.pl aus dem GIT geholt und ab da installiert er dann auch die neueren Updates des neuen Major Releases.

Befehle aus der Image-Bau-Anleitung:

```rm /opt/loxberry/sbin/loxberryupdate*.pl
wget https://raw.githubusercontent.com/mschlenstedt/Loxberry/master/sbin/loxberryupdate.pl -P /opt/loxberry/sbin
wget https://raw.githubusercontent.com/mschlenstedt/Loxberry/master/sbin/loxberryupdatecheck.pl -P /opt/loxberry/sbin
chmod +x /opt/loxberry/sbin/loxberryupdate*.pl
```

**Comment by mschlenstedt** [comment]
Das Notify soll die Releasebeschreibung mit anzeigen. So können wir die Known Issues gleich als Warnung mit anzeigen und auch den Link zum Whats new mitliefern.:

![image](https://user-images.githubusercontent.com/16830799/67543169-6646a300-f6f0-11e9-805a-9aacdbcdf4aa.png)

**Comment by christianTF** [comment]
- [ ] Im lbupdatecheck Response-Json zurückliefern: LBMAX-Version, Aktuellster (Pre-)Release (geblockte Version)
- [ ] Update-Template: JS zur Anzeige der Daten und Button, um Update von lbupdatecheck zu triggern
- [ ] Update.cgi: Routine zum Aktualisieren von lbupdatecheck (BRANCH= berücksichtigen)
- [ ] Language Strings
- [ ] Rückführung auf 1.4.3
- [ ] Hinweis im UI _nicht_ anzeigen, wenn FAILED_SCRIPT gesetzt ist

**Comment by christianTF** [comment]
- Loxberryupdatecheck.pl verwendet jetzt General.json Update->max_version
- Wenn Schlüssel nicht verfügbar: major_version.99.99
- Knopf zum Update setzt max_version auf (major_version+1).99.99

Anzeige der Release-Info:
- Pre-Release zeigt die ERSTE *Pre-Release* nach max_version
- Release zeigt die ERSTE *Release* nach max_version
- Latest habe ich nicht getestet (liest die Releaseliste nicht, keine Ahnung, was das tut 😉)
- Installiert wird aber immer der _aktuellste_ Pre-/Release/Latest, der erlaubt ist.

D.h. je nach Benutzereinstellung kann etwas Unterschiedliches angezeigt werden.


Rückführung auf 1.4.3:
- [x] loxberryupdatecheck.pl
- [x] ajax-Config-handler.cgi
- [x] updates.html
- [x] Sprachvariablen lbu_* kopieren
