### ISSUE TITLE
logfile.html

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#108]
`Schließen`muss `Schlie&szlig;en` sein

**Comment by mschlenstedt** [comment]
Werden direkte Umlaute bei dir nicht korrekt dargestellt? Der Webserver läuft eigentlich auf UTF8, sodass eine Transskription nicht nötig sein sollte.

**Comment by Woersty** [comment]
`ß` ist aber nicht UTF8.

**Comment by mschlenstedt** [comment]
Mmmhh, vielleicht stehe ich gerade auf dem Schlauch oder sehe den Wald vor lauter Bäumen nicht. 

ß an sich ist natürlich kein UTF-8, aber die Datei ist in UTF-8 codiert, der Webserver unterstützt ebenfalls UTF-8. Somit sollte er Umlaute, Sonderzeichen etc. in den HTML-Dateien korrekt (de)codieren. Was er meiner Meinung nach auch tut:

![30-08-_2016_09-06-22](https://cloud.githubusercontent.com/assets/16830799/18079519/84f576a4-6e91-11e6-9146-88a8e53d1b9e.jpg)

**Comment by Woersty** [comment]
Ist sie? Hier nicht. 
Aber: :bulb: Da kommen wir der Sache doch schon näher...
Ich wandle sie mal. Und schon geht's.
(Ich entwickle auf Windows, ist mir vorher schon aufgefallen, dass er manchmal am Encoding was ändert...)

Vorher:
loxberry@loxberry:~ $ file /opt/loxberry/templates/system/de/logfile.html
/opt/loxberry/templates/system/de/logfile.html: HTML document, ASCII text, with CRLF line terminators
Nachher:
loxberry@loxberry:~ $ file /opt/loxberry/templates/system/de/logfile.html
/opt/loxberry/templates/system/de/logfile.html: HTML document, UTF-8 Unicode text, with CRLF line terminators
oder
loxberry@loxberry:~ $ file /opt/loxberry/templates/system/de/logfile.html
/opt/loxberry/templates/system/de/logfile.html: HTML document, UTF-8 Unicode text

Was hast du?

PS: Warum geht das eigentlich obwohl in der charset.conf vor Charset eine # ist?

**Comment by mschlenstedt** [comment]
Ich habe:

loxberry@loxberry:~/templates/system/de $ file logfile.html
logfile.html: HTML document, UTF-8 Unicode text
loxberry@loxberry:~/templates/system/de $

Aber ich entwickle auch direkt auf dem RaspPi mit vim.

Das geht, weil im header.html steht:

`<meta http-equiv="content-type" content="text/html; charset=utf-8">`

Wenn Du es in der charset.conf direkt setzt, dann nutzt der Apache es für alle Dateien, auch wenn die anders kodiert sind. Davon wird im Allgemeinen abgeraten. Ich muss zugeben, dass es aber am Anfang auch ein Stück Arbeit war dieses Encoding-Knäuel zu entflechten :-) Hat mich einige Nerven gekostet...

**Comment by Woersty** [comment]
Dann habe ich es jetzt auch verstanden :+1: 
Alles klar.
