### ISSUE TITLE
Caching im Browser verhindern

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1080]
Zum Beispiel so: https://github.com/pfsense/pfsense/blob/0b4c14a491664053aad3cc76e1ffd67b70ff2da1/src/usr/local/www/getqueuestats.php#L29

Müsste in die Libs eingebaut werden.

**Comment by christianTF** [comment]
Ich schließe das ab. 
Das Relevante ist korrigiert, und fürs normale Webinterface ist der Cache in der Regel egal.
