### ISSUE TITLE
WLAN Settings funktionieren nicht mehr

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1081]
![image](https://user-images.githubusercontent.com/16830799/68548264-44853580-03eb-11ea-96c8-c237058696ed.png)

Wohl seit dem Umbau auf ipV6.

**Comment by christianTF** [comment]
Muss ich mir ansehen. Beim Implementieren hat er definitiv korrekt zwischen LAN und WIFI unterscheiden können.

Ist das Onboard-WiFi?

**Comment by mschlenstedt** [comment]
Nein, USB. Ging aber früher.

**Comment by svethi** [comment]
WLAN0 cabled Network???

**Comment by svethi** [comment]
USB kann ich gar nicht testen und hört sich wohl auch eher nach einem Treiberproblem an

**Comment by mschlenstedt** [comment]
Ging alles mit 1.4.2 problemlos.

**Comment by svethi** [comment]
Muss ein cache Problem sein ;-)

Naja, 1.4 war Stretch, jetzt ist’s Buster. Ein komplett neues BS

Oder besser gesagt, was genau funktioniert denn nicht? Gibts kein wlan if oder werden die Daten vom WebIF nicht gespeichert?

**Comment by mschlenstedt** [comment]
![image](https://user-images.githubusercontent.com/16830799/68562549-7e395900-044a-11ea-85ac-e8881031ff51.png)

**Comment by mschlenstedt** [comment]
Er scheint das WLAN0 nicht als WLAN sondern all LAN zu erkennen und baut damit das WebIf falsch (ich habe keinen Button um nach WLANs zu suchen und ich kann auch nirgends SSID und Passwort eingeben.

**Comment by christianTF** [comment]
Gefixt mit https://github.com/mschlenstedt/Loxberry/commit/3dd76580eab15660883f56d2b17f4de692a51b8c
