### ISSUE TITLE
plugininstall.pl: Warning bei Installation

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1082]
Warnung im Plugin-Installations-Log

`Use of uninitialized value $aptpackages in concatenation (.) or string at /opt/loxberry/sbin/plugininstall.pl line 1216, <F> line 1.`

Dürfte das Auslesen des apt-Files sein (aufgetreten beim FHEM-Plugin, hab ich aber schon öfter gesehen)

https://github.com/mschlenstedt/Loxberry/blob/3dd76580eab15660883f56d2b17f4de692a51b8c/sbin/plugininstall.pl#L1216

**Comment by mschlenstedt** [comment]
Hab ich auch schon öfter gesehen. Ich meine aber, dass das mit 1.4.2 nicht so war.

**Comment by christianTF** [comment]
Kommt von "use warnings; use strict;"

Ich bessere es aus.
