### ISSUE TITLE
plugininstall.pl: Add LBMIN/LBMAX to plugindatabase.json

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1084]
- [ ] plugininstall: Min/Max-Version in Plugindb speichern
- [ ] lbupdatecheck: Kompatibilität vor Update prüfen

**Comment by mschlenstedt** [comment]
Meinste, dass das eine gute Idee ist? Was machste dann, wenn nicht kompatibel? update nicht durchführen?

**Comment by christianTF** [comment]
Ja. außer bei Latest.
Andererseits steht der Aufwand eigentlich auch nicht dafür. Aber speichern kann man‘s mal.

**Comment by mschlenstedt** [comment]
Finde ich eher keine gute Idee. Dann blockieren wir für ein altes Plugin das LB Update und handeln uns damit wieder neue Probleme ein.

Das sollen die Pluginentwickler lösen. Ich setze es mal auf Wont Fix und mache es zu. Wir können es ja wieder aufmachen wenn Bedarf besteht.
