### ISSUE TITLE
SupportVPN: SecurePIN geht nicht bei PluginInstall

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1088]
PluginInstall benutzt noch nicht die Lib-Funktion der SecurePIN?

**Comment by christianTF** [comment]
Check ich nicht, ist doch da: https://github.com/mschlenstedt/Loxberry/blob/66e31535f1c6f0cf0aec2148d6921ea5d5d14d9d/sbin/plugininstall.pl#L248

**Comment by mschlenstedt** [comment]
Weiß nicht. Ging auf jeden Fall nicht. Ich teste das nochmal.
