### ISSUE TITLE
Validierung: special:number-min/max-value mit Dezimalzahlen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1093]
special:number-min-value:0.1 funktioniert nicht.

**Comment by Woersty** [comment]
Ist ja auch keine ganze Zahl 

Ich gucke mal- muss ich auf Kommazahlen umbauen

**Comment by mschlenstedt** [comment]
Richtig. Wäre trotzdem nett, wenn es gehen würde. Oder eine neue Regel Min/Max float oder so.

**Comment by Woersty** [comment]
Hast du was, wo du das testen kannst? Ist im aktuellen Master einfach von Int auf Float umgebaut.
Ungetestet.

**Comment by Woersty** [comment]
Soll noch , durch . ersetzt werden vor dem Vergleich?
Sonst funktioniert es bisher nur mit .

**Comment by mschlenstedt** [comment]
Funktioniert leider nicht:

![image](https://user-images.githubusercontent.com/16830799/70371640-e5292100-18d5-11ea-83f1-a13fdc38c062.png)

**Comment by mschlenstedt** [comment]
Zum Testen: https://github.com/mschlenstedt/LoxBerry-Plugin-1-Wire-NG/archive/master.zip

**Comment by Woersty** [comment]
Ich hoffe jetzt passt es. 😃
