### ISSUE TITLE
Log-Lib müllt STDERR zu

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1094]
![image](https://user-images.githubusercontent.com/16830799/70386790-597ac780-199d-11ea-8c57-d8ed59dab0cd.png)

**Comment by mschlenstedt** [comment]
Mit LOGSTART tritt das Problem nicht auf. Mein Fehler.

**Comment by christianTF** [comment]
In der Fehlermeldung einen Hinweis auf fehlendes LOGSTART aufnehmen („Possibly LOGSTART is missing?“)
