### ISSUE TITLE
Plugin Uninstall: Reihenfolge ändern

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1095]
Im Plugininstall:
https://github.com/mschlenstedt/Loxberry/blob/604e05ca1dc8dca00fb7c642de93ef7b65fed8f9/sbin/plugininstall.pl#L1556

Erst uninstall-Script ausführen, dann erst Verzeichnisse und Plugin-Eintrag löschen.

Aufpassen bezüglich Plugin-Updates

Request von 
https://www.loxforum.com/forum/projektforen/loxberry/entwickler/225722-entwickler-wuensche-fuer-zukuenftige-loxberry-version#post225748

**Comment by mschlenstedt** [comment]
Um kompatibel zu bleiben besser ein zusätzliches preuninstall Skript. Wäre dann auch die gleiche Logik wie bei den install-Skripten.

Und wir bleiben kompatibel zu bestehenden Plugins.

**Comment by christianTF** [comment]
Ich habe nochmal darüber nachgedacht. Ich würde kein neues preuninstall Script einführen. 
Es hat sich bisher eh kaum jemand um die Deinstallation gekümmert, und es wird noch unübersichtlicher mit den Scripts.

Wenn wir die Reihenfolge anpassen können, sodass trotzdem alles kompatibel bleibt, würde ich das bevorzugen.
Außerdem müssen wir besser dokumentieren, wann genau das uninstall bei der Deinstallation dran kommt.
https://www.loxwiki.eu/pages/viewpage.action?pageId=23462653#Pluginf%C3%BCrdenLoxberryentwickeln(abVersion1.x)-Unterverzeichnis:uninstallYellowOptional

**Comment by christianTF** [comment]
Uninstall Ablauf (LB1.x, LB2.x):
_(hab ich jetzt auch in die Plugin-Entwickler-Anleitung geschrieben)_

1. Löschen der Plugin-Ordner (config, bin, data, templates, webfrontend, temporäre Backups, Plugin-Icons)
2. Löschen des Daemons
3. Löschen der Cronjobs
4. Löschen des Sudoers-Files
5. Löschen des Installationslogs
6. Entfernen des Plugins aus der Plugin-Datenbank
7. Löschen der Logfiles
8. Ausführen des Uninstall-Scripts (als root)
9. Löschen des Uninstall-Scripts
10. Löschen des individuellen crontab-Files
11. Löschen der Notifications aus der Datenbank

Ich sehe spontan kein Problem, dass wir 8. weiter nach oben schieben.
Warum crontab extra gelöscht wird und nicht mit den anderen Crons, konnte ich nicht herauslesen.

Ich würde beginnen mit dem Löschen der Cronjobs, dann uninstall ausführen, Plugin aus der DB entfernen, dann alle Verzeichnisse löschen und die anderen Dateien.
Das Install-Log löschen wir nicht mehr, sondern appenden das Uninstall direkt dort dran.
Ans uninstall-Script übergeben wir alle Variablen wie bei den Install-Scripten.

**Comment by git-olicat** [comment]
Christian,

mein Problem besteht aber darin, dass ich mit dem Plugin selbst noch irgendwelche Aufraeumarbeiten taetigen moechte. Um das zu realisieren muesste man Punkt 8 also ganz nach vorn als Punkt 1 stellen.
Ich kann mir so spontan auch kein Szenario vorstellen, wo das zu Komplikationen fuehren sollte. Es gibt aber eben schon sehr viele Plugins - und vielleicht hakt es dann doch bei einem.
Voellig unkritisch ist aber eine Loesung, die bisher noch nicht genutzt wurde. Die bisherigen Plugins kennen ein preuninstall nicht. Das waere in meine Augen auch optional - ist es nicht da, wird es auch nicht ausgefuehrt.
Insofern koennte ich auch gut mit einem preuninstall als Punkt 0 leben.
Ja, es ist ein (optionales) Script mehr. Aber im uninstall-Folder gibt es ja bisher nur eins.
;-)

Danke fuer Deine Muehe, Oliver

**Comment by christianTF** [comment]
Ab **2.0.1.1**

1. Löschen der Cronjobs
2. Löschen des individuellen crontab-Files
3. Ausführen des Uninstall-Scripts (als root)
4. Löschen des Uninstall-Scripts
5. Löschen des Daemons
6. Löschen des Sudoers-Files
7. Löschen der Plugin-Ordner (config, bin, data, templates, webfrontend, temporäre Backups, Plugin-Icons)
8. Entfernen des Plugins aus der Plugin-Datenbank
9. Löschen der Logfiles
10. Löschen der Notifications aus der Datenbank

WIRD NICHT MEHR AUSGEFÜHRT
Löschen des Installationslogs
