### ISSUE TITLE
Plugin Uninstall: Logfile 

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1096]
Request von
https://www.loxforum.com/forum/projektforen/loxberry/entwickler/225722-entwickler-wuensche-fuer-zukuenftige-loxberry-version#post225748

Log der Deinstallation speichern 
Soll nach dem Uninstall auch im Log Manager erhalten bleiben

**Comment by mschlenstedt** [comment]
Sollte ja kein Problem sein mit existierenden Plugins.
