### ISSUE TITLE
miniserverbackup settings.html und index.cgi

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#11]
Hallo,
ich habe die Anzahl der Backups geändert. 
Inklusive Prüfung des Feldes auf vernünftige Werte.
\templates\plugins\miniserverbackup\de\settings.html
[settings.zip](https://github.com/mschlenstedt/Loxberry/files/363492/settings.zip)

\webfrontend\cgi\plugins\miniserverbackup\index.cgi
[index.zip](https://github.com/mschlenstedt/Loxberry/files/363495/index.zip)

Wenn du willst kannste das ja übernehmen.

**Comment by mschlenstedt** [comment]
Danke für den Fix, hatte ich aber bereits im Entwickler-Branch integriert. Da sieht man, dass ein Bugtracking-System Not getan hat :-)
