### ISSUE TITLE
general.cfg mailinfo missing

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#110]
MAIL=/usr/sbin/sendmail

Könnte man automatisch hinzufügen, wenn nicht da.

PS: Testmail-Button geht auch nicht und die Testmail beim Save sendet er auch nicht bei mir.

Ich habe heute aber keine Lust mehr zu schauen warum :)

**Comment by mschlenstedt** [comment]
Hi,

Testmail ist im Image schon gefixt, bin nur noch nicht dazu gekommen es hier auf GIT zu aktualisieren. Reloade die Seite mal - dann geht es :-)

Von meinem iPad gesendet

**Comment by mschlenstedt** [comment]
Gefixt.
