### ISSUE TITLE
Lokales dpkg repo

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1105]
Um Legacy Packages direkt mitzuliefern (zb Wiringpi)

https://unix.stackexchange.com/a/87131
https://askubuntu.com/a/176546/761119

Verschiedene Architekturen angeben
https://wiki.debian.org/Multiarch/HOWTO#Setting_up_apt_sources

**Comment by christianTF** [comment]
```
export LBHOME=/opt/loxberry

echo deb [trusted=yes arch=armel,armhf] file:///opt/loxberry/data/system/packages armhf/ > /etc/apt/sources.list.d/loxberry.list
echo deb [trusted=yes arch=amd64] file:///opt/loxberry/data/system/packages amd64/ >> /etc/apt/sources.list.d/loxberry.list

mkdir --parents $LBHOME/data/system/packages/armhf
mkdir --parents $LBHOME/data/system/packages/amd64
```
Irgendwas ins Repo legen
```
wget https://project-downloads.drogon.net/wiringpi-latest.deb -P $LBHOME/data/system/packages/armhf
```
Packages-File erzeugen lassen
```
cd $LBHOME/data/system/packages
dpkg-scanpackages armhf | gzip > $LBHOME/data/system/packages/armhf/Packages.gz
dpkg-scanpackages amd64 | gzip > $LBHOME/data/system/packages/amd64/Packages.gz

apt-get update
```
Paket installieren
```
apt-get install wiringpi
```

Das apt-scanpackages kann in LBUpdate automatisch ausgeführt werden.

**Comment by mschlenstedt** [comment]
Aber du wolltest doch nicht, dass wir z. B.  Wiring-Pi mitliefern. Wegen eventueller Abhängigkeiten. 

Da verstehe ich nicht, was das bringen soll.

**Comment by christianTF** [comment]
Repo pflegen zu viel Aufwand
