### ISSUE TITLE
Plugin Uninstall: Logfile-Erstellung

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1108]
Hi @mschlenstedt , kannst du bitte noch ein Review des Uninstall-Logs im Plugininstall.pl machen und das richtig stellen:

Bei der Install-Routine führst du die die ganzen Install-Scripte mit system(...") aus und "sammelst" irgendwie deren Output ein.

Ich hab nicht genau verstanden, wie du das machst, und deswegen im sub uninstall wahrscheinlich eine Routine auskommentiert, die dafür zuständig ist:
https://github.com/mschlenstedt/Loxberry/blob/1b1007cfd2f2ae1fd3c323d992584b90d8170956/sbin/plugininstall.pl#L238

Für den Uninstall-Prozess verwende ich fürs Uninstall-Script LoxBerry::System::execute 
https://github.com/mschlenstedt/Loxberry/blob/1b1007cfd2f2ae1fd3c323d992584b90d8170956/sbin/plugininstall.pl#L1652
Der Output landet in $output.
Ich habe dann versucht, den Output einfach mit `print $output;` auszugeben, aber das ist nirgends angekommen (deswegen habe ich es dann geändert, dass es mit `&loginfo` ausgegeben wird.

Ich hab nicht herausgefunden, wie du normalen STDOUT-Output beim Install ins Logfile bringst. 

Es ist nicht dringend, aber es sollte - wenn schon - gleich für install und uninstall funktionieren.

**Comment by mschlenstedt** [comment]
Das ist historischer Code. Ich checke, ob der system() Aufruf erfolgreich war. Wenn nein, gibt er eine im language-File definierte Fehlermeldung aus (NICHT die Ausgabe des system()-Aufrufs). Diese Fehlermeldung gebe ich nicht nur aus, sondern pushe sie zusätzlich noch in ein Hash (@errors). Warnings gehen ins Hash @warnings.

Beispiel:
https://github.com/mschlenstedt/Loxberry/blob/1b1007cfd2f2ae1fd3c323d992584b90d8170956/sbin/plugininstall.pl#L1482

Am Ende printe ich die beiden Hashes (@errors, @warnings) einfach wieder aus:

https://github.com/mschlenstedt/Loxberry/blob/1b1007cfd2f2ae1fd3c323d992584b90d8170956/sbin/plugininstall.pl#L1573

Der von Dir auskommentierte Code sichert einfach das Uninstall-Log. Das hat mit der Routine nix zu tun.

**Comment by christianTF** [comment]
Ok, dann lassen wir es so.

**Comment by christianTF** [comment]
Uninstall-Logfile ist implementiert.
Zu finden im Log Manager unter "Plugin Installation" in der Gruppe "Uninstall".
