### ISSUE TITLE
plugininstall.pl: Remove language specific phrases

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1112]
In plugininstall.pl sollten alle  sprachspezifischen Variablen (außer die Abschlussmeldungen) durch English (hardcoded) ersetzt werden. 
Es sind keine Phrasen enthalten, die für das UI oder den Benutzer eine wirkliche Relevanz hätten. Im Fehlerfall müssen es sowieso nur wir selbst lesen.

- Analyse und Abgleich mit dem Script wird einfacher
- Die Wartung des Codes wird einfacher (Übersetzung fällt weg)
- Das language-File wird schlanker
- Die Übersetzer werden entlastet 

Grundsätzlich bin ich der Meinung, dass wir für Logfile-Output keine Übersetzung anzubieten brauchen.

**Comment by mschlenstedt** [comment]
Finde ich eine gute Idee.

**Comment by christianTF** [comment]
- plugininstall.pl now has an own %LL (Local Language) hash on the bottom of the file
- All %LL phrases are English-only
- Some phrases are still %SL from system language (final messages)
- For new adaptions in the script, it is neither required nor recommended to use the %LL hash. It was simply the easiest way to migrate from %SL
- All language files (EN, DE, CS, ES, NL) are updated
