### ISSUE TITLE
Verwendungsstatistik: Legende formatieren, nur die letzten 6 Monate zeigen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1118]
Die Statistik soll nur noch die letzten 6 Monate zeigen. Zudem muss die Legende korrekt formatiert sein für diele Einträge.

![image](https://user-images.githubusercontent.com/16830799/73156129-0390e900-40dd-11ea-8107-e5e36d8308d4.png)

**Comment by christianTF** [comment]
Änderung der `index.php` (Vorgängerversion heißt nun `index_plot7.php`)
https://stats.loxberry.de

Es werden nur noch folgende Versionen angezeigt:
- Die höchste Versionsnummer in der Datenbank
- Versionen, die in den letzten 8 Wochen mindestens einmal über 1,2% der Gesamtinstallationszahl hatten

Alle anderen Versionen werden pro Woche summiert und als "Other versions" immer ganz unten angezeigt.

Ich habe die Höhe des Versionsdiagramms aus 500px erhöht, sowie die Breite aller Diagramme auf 900px.

Außerdem habe ich per css die Breite der Legende erhöht, damit die Versionsnamen ganz rein passen.
