### ISSUE TITLE
V0.2.1: Samba Paawort wird bei Erstinstallation nicht gesetzt

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#112]
Ursache unklar.

**Comment by Woersty** [comment]
Bei mir ist es in der index.cgi unter system/setup gar nicht drin?

**Comment by mschlenstedt** [comment]
War mal zusammen mit dem Unixpasswort in einem Skript (setloxberrypasswd.exp), im neuen Image ist es getrennt. Habe ich nur noch nicht auf GITHub aktualisiert.

Aber es geht trotzdem irgendwie nicht. Muss ich mir noch näher anschauen.

Von meinem iPad gesendet

**Comment by Woersty** [comment]
Ähm, ich habe das neue Image gerade mal aufgesetzt und bei mir setzt er auch das Konsole PW nicht mehr.

**Comment by mschlenstedt** [comment]
Ok, schaue ich mir an.

**Comment by mschlenstedt** [comment]
Fixed in 0.2.2
