### ISSUE TITLE
MSv2 showclouddns.pl: Prüfen ob noch verwendet und IPv6 kompatibel

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1125]
https://github.com/mschlenstedt/Loxberry/blob/master/webfrontend/htmlauth/system/tools/showclouddns.pl

**Comment by mschlenstedt** [comment]
Das stammt noch von mir. Bin mir aber ziemlich sicher, dass das nie jemand verwendet hat. Wenn dann maximal @Woersty 

Wenn es keiner verwendet schmeißen wir es raus.

**Comment by christianTF** [comment]
Das hängt direkt mit setdatetime.pl #1126 zusammen.

Wenn setdatetime.pl auf LoxBerry::System bzw. LoxBerry::IO (ms_httpcall) umgebaut wird, ist das Script obsolet, und setdatetime.pl automatisch ipv6/https kompatibel

![image](https://user-images.githubusercontent.com/14220265/74246853-74432280-4ce5-11ea-9131-e9688b290ff8.png)
