### ISSUE TITLE
MSv2 general.cfg/Miniserver widget: Nachziehen der Labels

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1128]
In der general.cfg heißen die neuen Labels:
- PREFERSSL
- SSLPORT

In get_miniservers heißen die Eigenschaften
- PreferHttps
- PortHttps

Die Properties in der general.cfg sollen gleich heißen wie bei get_miniservers (PREFERHTTPS, PORTHTTPS).
- [x] miniserver.cgi anpassen
- [x] miniserver.html anpassen
- [x] ajax-check-miniserver.cgi prüfen/anpassen
- [x] healtcheck.pl prüfen/anpassen
- [x] LoxBerry::System (Lesen der Config)
- [x] loxberry_system.php (Lesen der Config)
- [ ] Updatescript (alle neuen Felder in die general.cfg schreiben beim Update)

**Comment by mschlenstedt** [comment]
Pack es gleich in General.json

Wir wollen ja mittelfristig die General.cfg sterben lassen.

**Comment by christianTF** [comment]
Bin ich derzeit noch nicht glücklich damit 😕

In den Libs muss ich dann auch zwei Dateien lesen, und die Plugins müssen das dann auch. Das finde ich nicht gut.

Wenn, dann müssten wir zb den gesamten MINISERVERx Key ins json rüberholen, und die General.cfg generieren lassen.
Wenn wir das zu zweit/dritt/viert gemeinsam machen, dann ok, aber alleine schaff ich das nicht.

**Comment by mschlenstedt** [comment]
Dann sollten wir das angehen. Aber die General.cfg lassen wir nicht automatisch generieren. Plugins sollen da eh nicht direkt draus lesen. Die Datei ist LoxBerry System.
