### ISSUE TITLE
Validate: domainname_or_ipaddr doch noch falsch

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1130]
Der Hostname `0.at.pool.ntp.org` validiert nicht mehr gegen meine neue, IPv6-kompatible Expression von diesem Commit: https://github.com/mschlenstedt/Loxberry/commit/add00fbc05ff602a3ad117bbb0b850205491ef2c

@Woersty Kannst du dir das doch nochmal ansehen, dass wir eine Validierung hinbekommen, die sowohl IPv4, IPv6 als auch Hostnamen (kurz oder FQDN) hinbekommt.

**Comment by Woersty** [comment]
Ja, ich gucke mal
