### ISSUE TITLE
LoxBerry update to 2.0.1.3 failure 

### ISSUE THREAD

**Issue by AndreasSausner** [mschlenstedt/Loxberry#1131]
Hi core team, 

habe auf 2.0.1.3 upgedated und bekam diese Fehlermeldung :

"Current Version: 2.0.1.3 / No newer Release available. LoxBerry Update recognized a failed update script (Version v2.0.0.1). Your LoxBerry is in an inconsistent state. Please manually retry the installation in LoxBerry Update, and check the update logfiles for errors.	Wiki" 

Habe auf 2.0.0.1 die Version Zurückgesetzt und das update wiederholt , Fehler bleibt bestehen 

HW rapi B+ als reiner LoxBerry 

lg Andreas 

[20200216_174750_265_update.log](https://github.com/mschlenstedt/Loxberry/files/4210341/20200216_174750_265_update.log)

**Comment by christianTF** [comment]
Hallo Andreas!

Hast du, oder hattest du mal das MQTT Gateway installiert?

Wenn du es nicht mehr installiert hast:

Entweder:

- Mit putty anmelden 
- sudo apt-get purge mosquitto 

Oder

- Neueste Version von MQTT Gateway installieren
- Dann wieder deinstallieren

Wenn du das MQTT Gateway *aktuell installiert hast*, gib kurz Bescheid.

Lg Christian

**Comment by AndreasSausner** [comment]
Hallo Christian,


danke für die schnelle antwort . Habe kein MQTT GW installiert nur  Lox und MiniServer backup , text2sip und wether4lox der rest läuft auf einem VLox auf der synology NAS . 

habe mosquitto ge-purged und das updat durchgeführt —> alles OK 

Ich habe bisher nichts/wenig zur update möglichkeit des  VLox  gelesen , ich versuchte es am anfang aber ohne erfolg, habe dann das backup wieder installiert (geht ja komfortabel dank Loxbackup).


Grüße und vielen dank Andreas 

PS spende für euer projekt folgt - gehen die mittel aus den “spenden link”  in euer budget oder für gemeinnuetzige einrichtungen ?

**Comment by christianTF** [comment]
Hallo Andreas, 

Wir haben ein gemeinsam verwaltetes Konto, aus dem wir Ausgaben für Hardware zum Testen von uns und den Plugin-Entwicklern bezahlen.

Lg, Christian

**Comment by AndreasSausner** [comment]
Hi Christian,

Ich habe mein root PW nicht mehr. Gibt es eine moeglichkeit/hilfe ausser den loxberry neu aufzusetzen ?

Lg Andreas

**Comment by mschlenstedt** [comment]
@AndreasSausner  Schick mir bitte eine Mail an info(AT)loxberry.de Wir können das Passwort per Remote Unterstützung zurücksetzen. Ich schicke Dir den dazu notwendigen Support Key per Email.

LG
Micha

**Comment by christianTF** [comment]
Geschlossen wegen Inaktivität
