### ISSUE TITLE
Yarn Key Update 

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1134]
https://www.loxforum.com/forum/projektforen/loxberry/entwickler/236315-apt-the-following-signatures-were-invalid-expkeysig-23e7166788b63e1e-yarn

**Comment by Woersty** [comment]
In V2.0.1.3+ kommt das nicht mit rein?
So als V2.0.1.4 oder so?

```
Err:3 https://dl.yarnpkg.com/debian stable InRelease
The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging
Reading package lists...
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging
W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by christianTF** [comment]
Es macht derzeit niemand einen Release, deswegen passiert nichts.
Ich hab keine Zeit, in zwei Wochen kommt mein Dach runter und ich weiß garnicht, was ich am Haus zuerst machen soll, weil noch so viel vorzubereiten ist.

Außerdem haben wir in 2.0.2 eine halbfertige general.json, die man entweder fertig baut, oder alle anderen Fixes rückführt.

**Comment by mschlenstedt** [comment]
Geht mir auch so, aktuell einfach keine Zeit für ein richtiges Update. 

Sommerzeit ≠ LoxBerryzeit :-)

**Comment by mschlenstedt** [comment]
Lösung: https://github.com/yarnpkg/yarn/issues/7866

**Comment by christianTF** [comment]
Den Commit mit dem Fix hab ich eh schon am 22.2. gemacht ;-)
