### ISSUE TITLE
LoxBerry update to 2.0.1.3 failure: no acces anymore with a browser plugins still running fine 

### ISSUE THREAD

**Issue by HenkVlug** [mschlenstedt/Loxberry#1135]
Hi core team,

I have updated to 2.0.1.3 and cannot access the Loxberry menu within a browser.

The loxberry is working fine ... i can access plugin webpages and the plugin is working fine. 
There seems to be something wrong with the web interface from the loxberry itself.

The error:
Error 404 
The URL /admin/system/index.cgi does not exist.

The loxberry is accessable with putty, and I have root acces (know my superuser password).
How can i reinstall, upgrade or downgrade with putty?
And how do i get those files.

I'm a newbee with linux commands so i hope you can give me all the commands.

Thank you in advance

**Comment by mschlenstedt** [comment]
If all the files are missing, mostly this is a problem with your SDCard or with the Apache Webserver. If the files are missing, no way to install all the files manually.

Try getting help in the loxforum: https://www.loxforum.com/
