### ISSUE TITLE
SupportVPN: Notiz/Kommentarfeld am Server

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1137]
Beim Erzeugen eines SupportVPN Tokens ein Notiz-Feld dazu nehmen, dass in der Übersicht angezeigt wird.
Dann kann man sich einen Namen oder sowas eintragen, damit man den richtigen Key wieder findet.

**Comment by mschlenstedt** [comment]
Schon länger erledigt.
