### ISSUE TITLE
Mailserver 

### ISSUE THREAD

**Issue by MBeeken73** [mschlenstedt/Loxberry#1140]
Hallo zusammen,

ich bekomme beim Mailserver folgende Fehlermeldung (siehe Anhang).
LoxBerry V2.0.1.3
Was kann der Grund dafür sein bzw. wie kann ich den Fehler beheben?

Vielen Dank für eure Hilfe!

![Fehler](https://user-images.githubusercontent.com/48216471/76121293-946bb600-5ff3-11ea-926e-b30c4b4d2a9f.JPG)

**Comment by mfuerni** [comment]
Hallo,

habe das gleiche Problem mit Loxberry 2.0.1.3 auf Proxmox.
Ist ein Problem mit dem msmtp AppArmor Profil.

Log-Auszug:
```
apparmor="DENIED" operation="open" profile="/usr/bin/msmtp" name="/opt/loxberry/system/msmtp/msmtprc" pid=17583 comm="sendmail" requested_mask="r" denied_mask="r" fsuid=1001 ouid=1001
```

### Temporäre Lösung
Die folgende Zeile im AppArmor Profil `/etc/apparmor.d/usr.bin.msmtp` einfügen:
```
/opt/loxberry/system/msmtp/msmtprc  r,
```
Anschließend muss AppArmor neu gestartet werden: `systemctl restart apparmor.service`

Wirklich sinnvoll scheint mir die Lösung nicht, da das AppArmor Profil eventuell beim nächsten apt Update überschrieben wird. Man sollte wohl das Config-File in eines der erlaubten Verzeichnisse verschieben.

**Comment by mschlenstedt** [comment]
Das sid zwei unterschiedliche Probleme.  Oben gibt es Probleme mit dem Zugriff auf das Configfile (warum auch immer - nicht klar), bei Dir blockiert apparmor den Zugriff aus Sicherheutsgründen.

/etc ist der korrekte Ort für Configfiles oder bei msmtp alternativ das Homeverzeichnis des Users (was auf einem Original-Image /opt/loxberry ist).

Apparmor ist auf dem originalen LoxBerry nicht installiert. Daher ist das ein Problem mit Deinem Proxmox-Image

**Comment by mfuerni** [comment]
Ah okay, bei mir war die Fehlermeldung in der LoxBerry UI genau die gleiche.

**Comment by MBeeken73** [comment]
Danke für die Hilfe.
AppArmor blockiert!
Ich habe es jetzt mit der Temporäre Lösung am "laufen".

Gibt es noch einen anderen Workaround?

**Comment by mschlenstedt** [comment]
AppAmor deinstallieren.

**Comment by christianTF** [comment]
Bitte wiedereröffnen, wenn noch was ist.
