### ISSUE TITLE
USB Storage: Größenanzeige

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1142]
![image](https://user-images.githubusercontent.com/14220265/76998365-43de4c00-6955-11ea-8fda-4f10d1418b95.png)

Zeigt keine GB an, sondern Bytes (Stand 2.0.1.3)

**Comment by christianTF** [comment]
BTW Netshares zeigt's richtig an
![image](https://user-images.githubusercontent.com/14220265/76998570-9ddf1180-6955-11ea-8970-26166d55d31e.png)

**Comment by mschlenstedt** [comment]
Das scheint irgendwie vom Datenträger abhängig zu sein. Bei mit zeigt's einen korrekt in GB an, den anderen in Bytes:

![image](https://user-images.githubusercontent.com/16830799/77030275-6052a680-699e-11ea-877f-4d2f594c6684.png)

Das WebIf nutzt die Lib-Funktion LoxBerry::Storage::get_usbstorage("H");

Sehe ich das richtig, oder gibt es die Option "H" gar nicht mehr in der Lib?

https://github.com/mschlenstedt/Loxberry/blob/2167658223baaf06fe9b25b70c5348a2cf76b34f/libs/perllib/LoxBerry/Storage.pm#L248

**Comment by christianTF** [comment]
Doch, H gibt’s noch, ist ein paar Zeilen weiter unten.

https://github.com/mschlenstedt/Loxberry/blob/2167658223baaf06fe9b25b70c5348a2cf76b34f/libs/perllib/LoxBerry/Storage.pm#L256

Ich glaub das bytes_humanreadable macht was falsch.
