### ISSUE TITLE
Prüfen ob ~/log/ramlog/var/log von logrotate berücksichtigt wird

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1144]
das log_maint.pl scheint in das Verzeichnis nicht hineinzusehen.

Forumsthread dazu: https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/181640-error-the-logfile-database-sends-an-error-and-cannot-automatically-be-recovered?p=241743#post241743

**Comment by mschlenstedt** [comment]
Darf er auch nicht. /var/log wird auf jeden Fall von Logrotate berücksichtigt. Ist nur die Frage, ob das eventuell wegem dem Symlink von /var/log auf ~/log/ramlog/var/log nicht geht.

**Comment by mschlenstedt** [comment]
Ich mach zu.
