### ISSUE TITLE
Watchdog: Irgendwas mit dem Temperatur-Check stimmt nicht

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#1145]
> Healthcheck reports 1 errors. Please run Healthcheck for details.
> Current errors:
> Current CPU Temperature is 77.4°C. This reaches or nearly reaches your configured watchdog limit of 65°C. This is NOT fine. Since last reboot the cpu never reached Raspberry's soft or critical temperature limit. This is fine.

Fuhr aber nicht runter.
Dann Logging aktiviert, gespeichert und schwupp war er aus:

> Message from watchdog:
> It is too hot to keep on working. The system will be halted!

**Comment by Woersty** [comment]
Temp + vlc CPU consumption check in a 1s loop:
[command.txt](https://github.com/mschlenstedt/Loxberry/files/4381777/command.txt)

**Comment by mschlenstedt** [comment]
Mmhhh, das muss dann am Watchdog liegen. Ist der gar nicht aktiv, wenn das "logging" deaktiviert ist? Wo hast Du denn das logging genau aktiviert? Im Watchdog-Widget?

**Comment by Woersty** [comment]
Kann mich nicht erinnern.

**Comment by mschlenstedt** [comment]
Ich glaub das haben wir mal gefixt...

**Comment by christianTF** [comment]
Michael hat mal (im Healthcheck?) was gefixt, dass der Healthcheck gar nicht zur Temperatur kam, wenn der Watchdog abgedreht war. Daran kann ich mich erinnern.

**Comment by mschlenstedt** [comment]
Ich mach zu,
