### ISSUE TITLE
NodesJS funktioniert nicht auf einem RPI1

### ISSUE THREAD

**Issue by romanlum** [mschlenstedt/Loxberry#1146]
Mit Loxberry 2.0 wurde NodeJS-12 installiert, welches leider bei RPI1 "illegal instruction" liefert.
Das Problem ist, dass NodeJS-12 nur mehr für armV7 kompiliert ist und nicht mehr für armV6 (RPI1, Zero) zur Verfügung steht.

![image](https://user-images.githubusercontent.com/464862/78986681-1b98d600-7b2c-11ea-98b2-e5c889f131b0.png)

Für RPI1,Zero  könnte NodeJS 10 verwendet werden

**Comment by mschlenstedt** [comment]
Du könntest probieren NodeJS10 manuell zu installieren: https://gist.github.com/Koenkk/11fe6d4845f5275a2a8791d04ea223cb

Bin mir nicht sicher, ob NodeJS12 dazu deinstalliert werden muss.

Ist die Frage wie wir damit umgehen. Der Pi1/Zero ist ja stark begrenzt, bin mir nicht sicher, ob NodeJS überhaupt "Spaß" auf den Dingern macht.

**Comment by christianTF** [comment]
Wir haben als Standard Node V12 festgelegt (LTS) und installieren aus dem Original-Repo von Node.
Wir werden für Pi1/Zero keine Sonder-Installation von Node V10 machen, weil das nur ein Durcheinander mit Plugins gibt (was geht wo mit welcher Version usw.).

Wenn du eine ältere Version benötigst, dann bitte manuell installieren.

**Comment by christianTF** [comment]
PS: Am besten wäre es, den Node V12 ARMv6 Wunsch direkt bei Node zu deponieren, dass die das wieder ins Repo aufnehmen sollen.

**Comment by romanlum** [comment]
Eventuell sollte es irgendwo vermerkt werden, dass Node bei RPI1 nicht funktioniert.
Mein Plugin zigbee2mqtt verwendet node und ist damit nicht lauffähig auf dem RPI1

**Comment by mschlenstedt** [comment]
Als "WürgAround" könntest Du in Deinem Plugin prüfen, ob Du auf einem Pi1 bist und LoxBerry V2. Dann könntest Du eine Warnung ausgeben.

https://www.loxwiki.eu/display/LOXBERRY/LoxBerry%3A%3ASystem%3A%3Albversion
/opt/loxberry/bin/showpitype

**Comment by christianTF** [comment]
Wiki KB-Artikel - Node.js auf Pi1/Zero nicht unterstützt: https://www.loxwiki.eu/pages/viewpage.action?pageId=74286648
