### ISSUE TITLE
Error while update to Current Version: 2.0.1.3

### ISSUE THREAD

**Issue by loxatsonnenberg** [mschlenstedt/Loxberry#1149]
While updating from v2.0.0.0.999 to v2.0.1.3 the update script log informed me about some update errors:
 INFO: Installing rfkill...
 ERROR: Error configuring dkpg with /usr/bin/dpkg --configure -a - Error 1
 INFO: Clean up apt-databases and update
 ERROR: Error autoremoving apt packages - Error 100
 CRITICAL: Error installing rfkill - Error 100
 INFO: Install Python/pip as a standard...
 CRITICAL: Error installing python-pip python3-pip - Error 100
 ERROR: Update script /opt/loxberry/sbin/loxberryupdate/update_v2.0.0.1.pl finished with errors.
11:08:20.520 INFO: exec_perl_script /opt/loxberry/sbin/loxberryupdate/update_v2.0.0.1.pl release=v2.0.1.3 logfilename=/opt/loxberry/log/system/loxberryupdate/20200527_110322_290_update.log cron= updatedir=/tmp/loxberryupdate/mschlenstedt-Loxberry-65df3d5 with user  - errcode 4
11:08:20.520 ERROR: Update-Script update_v2.0.0.1 returned errorcode 4. Despite errors loxberryupdate.pl will continue.
 INFO: (Re-)Installing Perl library libemail-mime-perl and libemail-sender-perl ...
 CRITICAL: Error installing libemail-mime-perl libemail-sender-perl - Error 100
 ERROR: Update script /opt/loxberry/sbin/loxberryupdate/update_v2.0.0.4.pl finished with errors.
11:08:57.164 INFO: exec_perl_script /opt/loxberry/sbin/loxberryupdate/update_v2.0.0.4.pl release=v2.0.1.3 logfilename=/opt/loxberry/log/system/loxberryupdate/20200527_110322_290_update.log cron= updatedir=/tmp/loxberryupdate/mschlenstedt-Loxberry-65df3d5 with user  - errcode 1
11:08:57.164 ERROR: Update-Script update_v2.0.0.4 returned errorcode 1. Despite errors loxberryupdate.pl will continue.
WARNING: Update scripts were processed, but 2 did return an error code. Please check these files and create an issue at GitHub including your log.
[20200527_110322_290_update.log](https://github.com/mschlenstedt/Loxberry/files/4707316/20200527_110322_290_update.log)

Due to the fact, that this update fails, I set the version back to v2.0.0.0.999 and tried to update again, but the error still exists:
WARNING: In a previous run of LoxBerry Update this update script failed: v2.0.0.1. LoxBerry Update will continue. Please check the logfiles of previous updates for errors.

Hope, that you can assist me with fixing this issue.
Thank you
.:Chris:.

**Comment by christianTF** [comment]
owftpd.service reports an error during update.
Remove owftpd from the shell, by sudo apt-get purge owftpd and retry the update.
Your 1-Wire stuff will stop to work, as owftpd is part of one of the 1-Wire plugins. Reinstall the plugin later.

**Comment by loxatsonnenberg** [comment]
issue solved.

I removed the 1-wire-ng plugin before purging owftpd.
After successful update I re-installed 1-wire-ng with an error message because of an already existing conf file "usr/share/owfs/owfs.conf". I deleted this file manually and the plugin setup runs smooth.

Thank you for helping
