### ISSUE TITLE
Raspberry 1 nach Plugininstallation ewig im Wald

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#115]
Der cgi-Logviewer ist irgendwie Mist.
Bei mir ist auch mit dem neuen Image der LoxBerry nach einer Plugin-Installation minutenlang platt.
Die Plugin-Installation vom BLE Plugin dauert über eine halbe Stunde.
6x logviewer.cgi mit je 15% CPU-Last ....

**Comment by mschlenstedt** [comment]
Wenn du den logviewer deaktivierst - ist er dann schneller? Bei mir z.b. dauert apt-get update ewig, das liegt allerdings an den Raspbian Servern...

Ich kann mir das mit dem Logviewer irgendwie schwer vorstellen, weil der eigentlich nix macht. Aber wenn er wirklich der Übeltäter ist könnten wir ihn ja auch durch deinen Logviewer auf PHP Basis ersetzen.

Ich nutze einen RaspPi2, da habe ich die Themen bisher nicht. Ich installiere mal morgen dein BLE Plugin, mal sehen ob er bei mir auch so lange braucht.

Von meinem iPad gesendet

**Comment by mschlenstedt** [comment]
Habe mir das Ganze jetzt nochmal angeschaut. Ich nutze einen RaspPi2 mit 8 GB SD-Karte. Installation des BLE-Plugins beobachtet mit "tail -f /tmp/uploads/LOGFILE.log" und "top".

**1. Installation BLE-Plugin Standard mit Logviewer** 
Dauer: 55 Sekunden (90% davon braucht "apt-get update")

**2. Installation BLE-Plugin ohne Logviewer** 
Logviewer im Template deaktiviert (auskommentiert).
Dauer: 45 Sekunden (wieder 90% davon braucht "apt-get update")

Ich glaube nicht, dass der Logviewer das Problem ist. Würde mich auch wundern, da er nur eine Textdatei einliest und wieder ausgibt. Selbst wenn ich den 100x starte dürfte das auch einen RaspPi1 nicht aus dem Tritt bringen.

Hast Du auf der Konsole mal ein "apt-get update" ausgeführt und das System dabei beobachtet? Geht er dabei auch in die Knie?

**Comment by Woersty** [comment]
Wenn es bei dir nicht so ist, vergiss es erstmal.
Habe mir eine VM gebaut - die reicht zum Entwickeln.
Vielleicht beschwert sich ja noch jemand anders, dann greifen wir es nochmal auf.

**Comment by christianTF** [comment]
Meine Beobachtung ist (RPi1):
6x logfile.cgi wenn der Fertig/OK-Dialog schon da ist.
Klickt man auf OK, kommt man nicht mehr zurück zur Hauptseite.
Öffnet man die loxberry-Website neu, verschwinden schön langsam die logfile.cgi Prozesse.
Autoscroll war INaktiv.

**Comment by Woersty** [comment]
Habe das gleiche Problem bei mir.

**Comment by mschlenstedt** [comment]
Siehe #130
