### ISSUE TITLE
fstab geht verloren

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1150]
Offensichtlich geht bei einigen die SD auf Read-Only wegen einer leeren fstab.

Siehe ab
https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/251974-filesystem-read-only?p=252448#post252448

Da wir auch an der fstab hantieren, sollten wir da mal genauer drauf schauen.

**Comment by mschlenstedt** [comment]
Wir beschreiben die Datei in einigen Updates um LB1.2.0 und dann auch regelmäßig bei jedem Herunterfahren:

https://github.com/mschlenstedt/Loxberry/blob/0762834add4c63c1bc3cb5cd7ab13908e9a86a83/sbin/loxberryinit.sh#L161

**Comment by mschlenstedt** [comment]
Idee aus Chat:

Ja, dann hängt er beim Booten. Auch wenn das SMB-Share oder NFS Share nicht mehr existiert oder die USB Platte abgezogen wurde. Ich denke wir müssen einfach besser auf Plausibilität prüfen. Z. B. sollten wir nur neu schreiben, wenn irgendwo die nofail-Otion auch wirklich fehlt. Danach kontrollieren wir, ob in fstab.new mindestens die Rootpartition und die Bootpartition vorhanden sind. Erst dann ersetzen wir.
