### ISSUE TITLE
Rasp 4 / 8 GB

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1152]
Braucht neue Firmware (bootet nicht)

https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/254157-awi?p=254174#post254174

**Comment by mschlenstedt** [comment]
8gb geht vermutlich eh nur mit 64Bit?

**Comment by christianTF** [comment]
Fixed with https://github.com/mschlenstedt/Loxberry/commit/97ac1eb70f3d84d622f20c89c7fc4fd997803e36

**Comment by christianTF** [comment]
Image selbst fehlt noch ;-)
