### ISSUE TITLE
Automatischer Logoff nach Inaktivität

### ISSUE THREAD

**Issue by Shogun1978** [mschlenstedt/Loxberry#116]
Aktuell bleibt man angemeldet, auch wenn man nach Tagen sich wieder auf die GUI verbindet. Ein wählbarer Auto-Logoff (0 = disabled, 10 Minuten, 30 Minuten, 1 Stunde) würde die Sicherheit des Systems weiter steigern.

**Comment by mschlenstedt** [comment]
Wir nutzen die Authentifizierung des Apache Webservers (htaccess). Die eigegegebenen Daten sind so lange gültig, bis der Browser geschlossen wird.

Das können wir leider nicht ändern.
