### ISSUE TITLE
Custom loglevel change is ignored

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#1174]
Wenn ich ein Plugin per Autoupdate von CUSTOM_LOGLEVELS=false auf CUSTOM_LOGLEVELS=true umstelle, funktioniert es nicht.
Ich muss das Plugin löschen und neu installieren. Die Plugin-DB sollte aber besser den Wert einfach anpassen.

**Comment by christianTF** [comment]
Ich dachte, das hätte ich schon mal behoben...
Seh ich mir an.
