### ISSUE TITLE
Plugininstall pfolder vs. pname

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#118]
Meinste nicht, dass pfolder besser als pname wäre für Daemon und so.
Name könnte blöde Zeichen haben...

**Comment by mschlenstedt** [comment]
$pname ist der Kurzname. $pfolder könnte man auch nehmen, da ist es aber genauso möglich "komische Sachen" reinzuschreiben.

Ich denke wir sollten beide Variablen filtern - baue ich mit ein.

**Comment by mschlenstedt** [comment]
Fixed. Variablen werden gefiltert.
