### ISSUE TITLE
log_maint: Als root laufen lassen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1191]
Das Script kann keine Logs löschen, die root gehören, dann läuft das tmpfs voll. 

- log_maint als root starten
- Beim Zippen wieder den richtigen owner setzen

**Comment by mschlenstedt** [comment]
Das geht nicht. Das macht ein riesiges Sicherheitsloch auf. Damit kannst Du als user "loxberry" den gesamten Loxberry killen.

Symlink von ~/log/plugins auf / und ab geht die wilde Fahrt. Löscht dann zwar nur .gz und .log, ist aber schlimm genug.

Man könnte das Risiko ambildern, in dem man vorher prüft, ob das Zielverzeichnis ein Symlink ist. Bin mir aber nicht sicher, ob das ausreicht....

**Comment by mschlenstedt** [comment]
Ich schließe es.
