### ISSUE TITLE
PHP get_miniservers() gibt FullURI nicht zurück

### ISSUE THREAD

**Issue by kieslinger** [mschlenstedt/Loxberry#1192]
Hallo zusammen, bei der Verwendung der Funktion mshttp_send bzw. mshttp_send_mem tritt bei mir der Fehler auf, dass FullURI nicht gefüllt ist und somit keine Anfrage ausgelöst wird.

Ein var_dump der Miniserver von get_miniservers() zeigt ebenfalls das der Eintrag nicht vorhanden ist. Kommentiere ich die Cachzeile if (isset($cfgwasread)) { return $miniservers; } in get_miniservers() aus, wird die FullURI korrekt ermittelt und alles funktioniert wie erwartet.

Könnt ihr das bitte mal prüfen und mir meinen Fehler aufzeigen?

**Comment by christianTF** [comment]
Danke! Es ist ein Bug!

Workaround wäre derzeit, dass du get_miniservers als erste Funktion aufrufst, bevor du irgendeine andere Funktion verwendest, die ebenfalls die Config ausliest.

lg, Christian

**Comment by kieslinger** [comment]
Danke für den Hinweis, das werde so machen, bzw. die Änderung von dir einspielen.
