### ISSUE TITLE
Scan funktioniert nicht mehr

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#12]
Der scannt und schreibt dann "Gefundene IP-Adresse testen" aber
beim Anklicken kommt "about:blank" und die IP trägt er auch nicht ein.

**Comment by Woersty** [comment]
PS: Betrifft die aktuelle Development Version

**Comment by mschlenstedt** [comment]
Bitte nochmal testen. Bei mir funktioniert es (wieder).
