### ISSUE TITLE
Healthcheck-Summary: Liefert Fehler nach Reboot

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1201]
https://github.com/mschlenstedt/Loxberry/blob/03b9782a5224312415da8d3a2e039239562d5e37/webfrontend/htmlauth/system/healthcheck.cgi#L221

Nach einem. Reboot existieren beide Dateien nicht, deswegen kommt der Fehler. 

https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/288914-healthcheck-web-ui-vs-action-summary

**Comment by mschlenstedt** [comment]
Sollte beim Reboot einmal sofort ausgeführt werden.

**Comment by Woersty** [comment]
Wollte das fixen aber verstehe gar nicht was du da machst.
Das json wird ja gar nicht erzeugt wenn man die checks laufen lässt.

**Comment by christianTF** [comment]
Ich habe den Commit reverted, weil 
- das besser in `cron.reboot` ausgeführt wird (dabei ist der Aufruf auch völlig identisch wie in `cron.daily`).
- es keine Lösung sein kann, in loxberryinit den Sourcecode von healthcheck.pl nach Kommentaren zu durchsuchen.

Allerdings konnte ich das Problem auch mit `cron.reboot` nicht lösen:
- Solange der cron nicht gelaufen ist, liefert http://loxberryvm/admin/system/healthcheck.cgi?action=summary weiterhin zurück, dass die json-Files nicht existieren.
- Wenn der cron.reboot läuft, sind Plugins noch gar nicht fertig gestartet, und deren Healthchecks liefern erst recht Fehler zurück, die erst mit cron.daily zurückgesetzt werden.

Ich checke jetzt cron.reboot mit dem Healthcheck um 60 Sekunden verzögert ein. Plugins sollten dann schon laufen.

D.h. für 60 Sekunden kommt weiterhin der Fehler laut Issue, danach sind die json-Files wieder up-to-date.
