### ISSUE TITLE
Image-Erstellung vollständig gescriptet

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1202]
Die Image-Erstellung soll vollständig gescriptet werden.
Die Anleitung ist extrem komplex, und dadurch fehleranfällig. Es muss wieder möglich werden, auf einfache Weise ein neues Image zu erstellen. 

Update-Scripts müssen im Script, und dann fortlaufend, berücksichtigt werden, oder im Zuge des Image-Erstellung-Prozesses ausgeführt werden.

- Final soll es möglich sein, mittels eines Scriptaufrufes einen neuen LoxBerry zu "erstellen"
- In weiterer Folge wäre das womöglich auch VM- und Container-tauglich

**Comment by mschlenstedt** [comment]
Mit dem LoxBerry Installer realisiert: https://github.com/mschlenstedt/Loxberry_Installer
