### ISSUE TITLE
Heimdall App für Loxberry

### ISSUE THREAD

**Issue by Noschvie** [mschlenstedt/Loxberry#1205]
https://github.com/linuxserver/Heimdall-Apps/issues/303

Bin auf der Suche nach einem passenden Image zur Erstellung einer Heimdall App (Dashboard).
Siehe https://apps.heimdall.site/

Thanks!

**Comment by mschlenstedt** [comment]
Wird mir Core nicht umgesetzt. Ausschließlich raspi aktuell. Bitte im Forum diskutieren.
