### ISSUE TITLE
Log-Filename vom Maintanance Skript beinhaltet einfache Anführungsstriche

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1209]
![image](https://user-images.githubusercontent.com/16830799/108620917-9e1e4180-742f-11eb-955b-c9192e97bccb.png)

**Comment by christianTF** [comment]
Das ist nur die `ls`-Ausgabe der Bash bei Leerzeichen im Dateinamen. Tatsächlich haben die Dateinamen keine Quotes.

![image](https://user-images.githubusercontent.com/14220265/119346526-9d00e880-bc9a-11eb-9945-00f611975342.png)

Siehe auch Log Viewer
![image](https://user-images.githubusercontent.com/14220265/119346662-cc175a00-bc9a-11eb-9a21-5c95fcdfe995.png)

File Download im Log Viewer:
![image](https://user-images.githubusercontent.com/14220265/119346854-05e86080-bc9b-11eb-847f-760af982ceed.png)
