### ISSUE TITLE
Createlegacytemplate creates template with HTML::Template error

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1223]
![4A3001F9-F6B4-4F59-89B9-AA644C8F1E57](https://user-images.githubusercontent.com/14220265/114826512-e15db680-9dc7-11eb-8502-256eeae62427.png)

**Comment by Noschvie** [comment]
https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/242152-ramlog-voll?p=296671#post296671

**Comment by christianTF** [comment]
Fixed with reverting https://github.com/mschlenstedt/Loxberry/commit/db6e4058f65fb4984e78e85b65bb538c30fe9d4a
Disabled template cache permanently https://github.com/mschlenstedt/Loxberry/commit/d049022cfd5e4e59ed51beb7bf85967c2222009d
