### ISSUE TITLE
diskspaceinfo: Issues with spaces and large disks

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#1226]
Bei großen Platten kommt Schrott zurück

**Comment by Woersty** [comment]
Teste morgen noch weiter.

**Comment by Woersty** [comment]
Der Fix funktioniert bei mir - könnte geschlossen werden.

**Comment by christianTF** [comment]
Fix: Diskspace-Info wird 2x aufgerufen, weil der Output von df so schlecht formatiert ist, dass man die Zahlen nicht ordentlich parsen kann.
