### ISSUE TITLE
Automatische Bereinigung LogDB

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1228]
Wenn die LogDB eine gewisse Größe überschreitet, soll sie automatisch bereinigt werden. Die Sicherung einer zu großen Datenbank auf die SD-Karte und anschließende Wiederherstellung nach dem nächsten Reboot soll unterdrückt werden.

https://www.loxforum.com/forum/projektforen/loxberry/plugins/227489-plugin-1-wire-ng?p=301267#post301267

**Comment by christianTF** [comment]
Die Problematik ist für mich nicht nachvollziehbar.
- Log_maint reduziert jede Gruppe auf 25 Logs.
- LogDB-Einträge älter 60 Tage werden grundsätzlich gelöscht.
- Das Log-Backup macht ein Shrink der DB.

Das ist die erste derartige Meldung - möglicherweise ist diese DB noch aus der Zeit, wo es in 1.2 oder so mal einen Bug gab.

Ich würde hier jetzt erstmal nichts angreifen, wenn das ein Einzelfall bleibt.
