### ISSUE TITLE
sh-Fehler bei Install: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1229]
```
...
26.04.2021 07:14:05 INFO: 62 found out of 80 ...
26.04.2021 07:14:05 INFO: 78 found out of 100 ...
sh: 1: Syntax error: "(" unexpected
26.04.2021 07:14:06 OK: Found 84 files to be text files
26.04.2021 07:14:06 INFO: Checking for hardcoded paths to /opt/loxberry
...
```
[installlog.log](https://github.com/mschlenstedt/Loxberry/files/6374461/installlog.log)

Setup war S4L-NG, das Install hat keinen generellen Fehler geworfen.

Wahrscheinlich Escaping von Leerzeichen...?

**Comment by Woersty** [comment]
Wurde ausgelöst von Leerzeichen in "/opt/loxberry/data/system/tmp/uploads/QofP3cjxSw/LoxBerry-Plugin-Stats4Lox-NG-main/templates/grafana/templates/**Dashboard with 1 panel**.txt"
