### ISSUE TITLE
Zeitzoneneinstellung - Deutschsprachige/europäische Länder hoch holen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#123]
Kleinigkeit, die mir so aufgefallen ist:
Im Wizzard, Schritt 4, hast du die Zeitzone für Berlin in der Liste nach oben geholt.
Könntest du die anderen deutschsprachigen Länder (Europe/Vienna und Europe/Zurich) oder überhaupt alle europäischen Länder noch nach oben holen.
lg, Christian

**Comment by Woersty** [comment]
Kann ich machen.

**Comment by mschlenstedt** [comment]
Ok, ich mache noch einen neuen Branch 0.3.0 für die neuen Features - möchte 0.2.2 nur für Bugfixes nutzen.
