### ISSUE TITLE
Fix yarn key

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1232]
https://www.loxforum.com/forum/projektforen/loxberry/plugins/146726-plugin-habridge?p=304751#post304751

**Comment by Woersty** [comment]
Alternativ kannst du die Package ja auch rausschmeißen, wie du geplant hattest.

**Comment by christianTF** [comment]
Fix von Wörsty: Yarn-Key wird bei jedem Plugin-Install (max. 1x täglich) aktualisiert.
