### ISSUE TITLE
SQLite3::exec(): near &quot;s&quot;: syntax error in /opt/loxberry/libs/phplib/loxberry_log.php on line 370

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#1236]
Bei
`LOGSTART ($L["LOGGING.LOG_002_CHECK_STARTED"]);`
kommt
` SQLite3::exec(): near &quot;s&quot;: syntax error in /opt/loxberry/libs/phplib/loxberry_log.php on line 370`

Der String ist:
`LOG_002_CHECK_STARTED="Check started..."`

Die Query ist:
`UPDATE logs_attr SET value = 'Check started...' WHERE keyref = 292726 AND attrib = 'LOGSTARTMESSAGE';`

Was mach ich falsch? 😞

**Comment by christianTF** [comment]
Er mag deine Quotes im String nicht.
Wird offensichtlich nicht escaped.

**Comment by Woersty** [comment]
Wo sind da quotes? Der String ist **Check started...**

**Comment by christianTF** [comment]
Ach, ich dachte, der ganze String ist der String.
Muss ich ausprobieren.

**Comment by christianTF** [comment]
Ich brauch den _echten_ Code.

Bei mir funktioniert das alles korrekt.

```php
#!/usr/bin/env php
<?php
require_once "loxberry_log.php";

error_log("Hallo");

$L["LOGGING.LOG_002_CHECK_STARTED"]="Check started...";

$mylog = LBLog::newLog(array("addtime" => "1", "name" => "PHPLog", "package" => "Test", "logdir" => $lbslogdir, "loglevel" => 7));

echo "Logfile: " . $mylog->filename . "\n";

LOGSTART($L["LOGGING.LOG_002_CHECK_STARTED"]);

echo "DBKey: " . $mylog->dbkey . "\n";

LOGOK("OK");

LOGEND("Das ist das gl Log Ende");

?>
```

**Comment by christianTF** [comment]
`&quot;s&quot;`
Das ist ja irgendein HTML. Wo kommt das her?

**Comment by Woersty** [comment]
Verstehe ich nicht. Ist nicht mehr nachstellbar?! Egal. Wenn ich es nochmal sehe gucken wir nochmal...

**Comment by christianTF** [comment]
Wenn du den Fall hast, dann schick mir einen Link auf den Code, wo das passiert.
Vielleicht sehe ich dann mehr.
