### ISSUE TITLE
Webinterface in neuem Fenster öffnen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#124]
Ich hätte gerne noch einen Button, mit dem ich direkt das Webinterface vom MS aufrufen kann :-)

**Comment by Woersty** [comment]
Ok, bau ich ein.

**Comment by mschlenstedt** [comment]
Ok, ich mache noch einen neuen Branch 0.3.0 für die neuen Features - möchte 0.2.2 nur für Bugfixes nutzen.

**Comment by christianTF** [comment]
Gefixt und gepusht von Wörsty
