### ISSUE TITLE
Fix possible reboot loop

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1242]
https://github.com/mschlenstedt/Loxberry/commit/4e72b5d0d41f661e8f7188b31108d24c8cb56bbb

Follow up of #992 

Wenn das nicht vor Pre-Release überarbeitet ist, reverten wir die Änderung. Das Risiko ist zu groß, dass wir einen LB deswegen endgültig zerstören.

**Michael (WhatsApp):**

Meiner Meinung nach landest Du in einer Rebootschleife, wenn "touch /readonlycheck" nicht funktioniert. Speichert einen Zähler in /boot und macht das maximnal 5x mal (oder meinetwegen 10x). Sonst landest Du nie an einem Prompt, wo Du noch was machen kannst. https://github.com/mschlenstedt/Loxberry/blob/9883f91692cb53cee6064c31a085e055a4808375/sbin/loxberryupdate/updatereboot_v2.2.0.pl#L52

**Christian**:
IMHO reicht ein Versuch. Wenn das Kopieren und Rebooten einmal nicht klappt, klappt es auch 5x nicht.

Evt. machen wir keinen Reboot, sondern setzen einfach reboot.required und informieren damit den Benutzer, was wir getan haben.

**Comment by mschlenstedt** [comment]
Fixes with 08086648d84a305345c2b5f432d3d616ef76cf03
