### ISSUE TITLE
Reboot.force code nicht ausgeblendet und an mobilen Geräten im Hintergrund zu sehen

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#1244]
Siehe Foto

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/20454116/120009471-466a1600-bfdc-11eb-94fa-092ccc64a8ae.png)

**Comment by christianTF** [comment]
Hab ich noch nie im Hintergrund gesehen. Das Popup gibt es seit LB 2.0.

Perl oder PHP?
UI mit den Lib-Funktionen generiert, oder die legacy-Templates benutzt?
reboot.force gesetzt oder nicht?

Der Code-Block im Template ist HTML-valide, und das Öffnen des Popups wird mit der JQm-Funktion ausgeführt.

Deswegen tippe zuerst auf invalides HTML in deinem Code.

**Comment by Woersty** [comment]
Möglich. Ich gucke es mir an.

**Comment by Woersty** [comment]
War ein HTML Fehler
