### ISSUE TITLE
UPdate des Yarn Keys in Init() der LoxBerry::Update Lib

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1250]
Macht immer wieder Ärger. Wir updaten es bei jedem Updateskript automatisch:

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -

**Comment by christianTF** [comment]
Closed with https://github.com/mschlenstedt/Loxberry/commit/f08490fb2bc736e5e33bd1d3ae56b9f790400cee
