### ISSUE TITLE
Update from v2.2.0.4 to v2.2.1.1 ends with error

### ISSUE THREAD

**Issue by sissibieber** [mschlenstedt/Loxberry#1252]
While updating from 2.2.0.4 to 2.2.1.1 the update ends in the following errors:
```
 OK: Apt packages autoremoved successfully.
 ERROR: Error updating apt database - Error 100
Hit:1 https://deb.nodesource.com/node_12.x buster InRelease
Get:2 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster InRelease [15.0 kB]
Get:3 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster InRelease [15.0 kB]
Hit:4 http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian buster InRelease
Hit:5 https://dl.yarnpkg.com/debian stable InRelease
Update rpimonitor Packages Status
Reading package lists...

 OK: Apt cache cleaned successfully.
 OK: Packages libsys-filesystem-perl libipc-run3-perl libhash-merge-perl successfully installed
 ERROR: Update script /opt/loxberry/sbin/loxberryupdate/update_v2.2.1.1.pl finished with errors.
12:51:52.718 INFO: exec_perl_script /opt/loxberry/sbin/loxberryupdate/update_v2.2.1.1.pl release=v2.2.1.1 logfilename=/opt/loxberry/log/system/loxberryupdate/20210822_125108_725_update.log cron= updatedir=/tmp/loxberryupdate/mschlenstedt-Loxberry-cb9c89a with user  - errcode 1
12:51:52.718 ERROR: Update-Script update_v2.2.1.1 returned errorcode 1. Despite errors loxberryupdate.pl will continue.
12:51:52.718 INFO: Setting update script update_v2.2.1.1 as failed in general configuration.
12:51:52.718 INFO: Updating update script fail state in general configuration...
12:51:52.720 WARNING: LoxBerry Update was SUCCESSFULL, but skipped at least 1 warnings or errors. Check the log.
12:51:52.720 CRITICAL: LoxBerry Update exited or terminated with an error. Errorcode: 1
```

attached the full log.
[20210822_125108_725_update.log](https://github.com/mschlenstedt/Loxberry/files/7027215/20210822_125108_725_update.log)

active plugins:
- CalDAV-4-Lox
- LoxBerry Backup
- Miniserver Backup
- MQTT Gateway
- Nuki SmartLock
- RPi Monitor
- Weather 4 Loxone

**Comment by christianTF** [comment]
Please re-run the update.
Does it fail again?

**Comment by sissibieber** [comment]
yes, that was already the output of the second try.

**Comment by bobbythemoh** [comment]
Hey Christian, same issue here.
[20210823_211011_415_update.log](https://github.com/mschlenstedt/Loxberry/files/7034385/20210823_211011_415_update.log)

**Comment by MBeeken73** [comment]
Bei mir kommt es auch zu einen Fehler.
[20210826_095445_451_update.log](https://github.com/mschlenstedt/Loxberry/files/7053654/20210826_095445_451_update.log)

**Comment by christianTF** [comment]
Hi,

could you please try to update to the fresh 2.2.1.2 Pre-Release.
We fixed some troubles with apt repos in this update.

Would be nice to get feedback if it works.

lg, Christian 

https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/316196-loxberry-v2-2-1-2-pre-release

**Comment by MBeeken73** [comment]
> Hi,
> 
> could you please try to update to the fresh 2.2.1.2 Pre-Release.
> We fixed some troubles with apt repos in this update.
> 
> Would be nice to get feedback if it works.
> 
> lg, Christian
> 
> https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/316196-loxberry-v2-2-1-2-pre-release

Hat jetzt alles funktioniert.
Vielen Dank.

**Comment by sissibieber** [comment]
I will try the pre-release this weekend and let you know.

**Comment by git-olicat** [comment]
Hi!

I also got the error 100 when updating to the release. With the pre-release everything is ok.

Regards, Oliver

**Comment by Woersty** [comment]
2.2.1.2 ist raus. Damit sollte es wieder ok sein.

**Comment by sissibieber** [comment]
Closing this issue, eventhough I had no time to test it yet, but won't have time in the near future. If neccessary I will reopen or check back. Thank you.

ETA: works!
