### ISSUE TITLE
Falsche IP Adresse

### ISSUE THREAD

**Issue by BattloXX** [mschlenstedt/Loxberry#126]
Ich habe folgendes Problem mit dem Loxberry Image, bin mir aber nicht sicher woran es liegt.

Mein Loxberry sendet via UDP Signale an Loxone. Komischerweise verwendet er eine IP-Adresse die er bei der Ersteinrichtung via DHCP (192.168.0.104) erhalten hat. Ich habe ihm bei der Einrichtung jedoch die statische IP 192.168.0.5 vergeben. Das seltsame ist jetzt das ich ihn über beide IP-Adressen per Web erreiche.

Die /etc/network/interfaces schaut aber normal aus:

`
auto lo
iface lo inet loopback

allow-hotplug eth0
iface eth0 inet static
  address 192.168.0.5
  netmask 255.255.255.0
  gateway 192.158.0.254
  dns-domain loxberry.local
  dns-nameservers 8.8.8.8
`

Bin mir dadurch nicht sicher wo das Problem liegen könnte. Verwende einen RPI3 und V 0.2.1

**Comment by mschlenstedt** [comment]
Was sagt denn ein "ifconfig"?

**Comment by BattloXX** [comment]
leider auch nicht mehr:

loxberry@loxberry:~ $ ifconfig
eth0      Link encap:Ethernet  HWaddr b8:27:eb:12:7b:3a
          inet addr:192.168.0.5  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::456e:51f6:79e1:d0f7/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:16991 errors:0 dropped:9 overruns:0 frame:0
          TX packets:5248 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:4031017 (3.8 MiB)  TX bytes:920000 (898.4 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:244 errors:0 dropped:0 overruns:0 frame:0
          TX packets:244 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:18857 (18.4 KiB)  TX bytes:18857 (18.4 KiB)

wlan0     Link encap:Ethernet  HWaddr b8:27:eb:47:2e:6f
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:1 errors:0 dropped:1 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:60 (60.0 B)  TX bytes:0 (0.0 B)

Laut meinem DHCP Server holt sich Loxberry wirklich noch eine dyn. IP.

**Comment by mschlenstedt** [comment]
Seltsam...

Probiere bitte mal folgendes:
1. LoxBerry herunterfahren
2. Router neu starten
3. LoxBerry neu starten

**Comment by mschlenstedt** [comment]
Da keine Rückantwort - closed.
