### ISSUE TITLE
Maintenance Skript erzeugt Logfiles mit Single Quotes

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1265]
![image](https://user-images.githubusercontent.com/16830799/141676989-b1c911b3-0309-43a1-8038-81573a25bfe0.png)

**Comment by christianTF** [comment]
Das ist die Ausgabe von Bash, wenn Leerzeichen im Namen sind.

![image](https://user-images.githubusercontent.com/14220265/141678031-d846900d-4f26-4916-ae75-7121ab0a5ddf.png)

**Comment by christianTF** [comment]
https://github.com/mschlenstedt/Loxberry/issues/1209 :joy: 😂
