### ISSUE TITLE
Loxberry 2.0

### ISSUE THREAD

**Issue by escalate** [mschlenstedt/Loxberry#127]
Hallo zusammen,

ich finde die Idee hinter Loxberry wirklich klasse. Es fehlt tatsächlich an einfachem Tooling um die Loxone herum damit man diese schnell und günstig erweitern kann.

Schade finde ich leider, dass Loxberry es einem Entwickler schwer macht mit einzusteigen.
Ich bin kein wirklich guter Perl-Entwickler. Davon abgesehen habe ich keine Tests im Projekt gefunden, die mir zeigen, ob alles nach einer Änderung von mir noch funktioniert.
Ein Vagrantfile wäre auch sehr hilfreich um das System einmal ohne Raspberry zum Laufen zu bekommen.

Ich habe das Issue "Loxberry 2.0" genannt, um einen Anstoß zu geben, dass Projekt für eine breitere Masse attraktiv zu machen.

Vorschläge für Veränderungen:
- Neuere Scriptsprache wie Python oder Ruby
- MVC-/HTML-/CSS-Frameworks für die Umsetzung des Webfrontends
- Einführung von Tests
- From Scratch Installation mittels Konfigurationsmanagementtools wie Ansible, Puppet oder Chef

Ich hoffe hier auf eine konstruktive Diskussion zu dem Thema. Bitte diesen Issue nicht als Rant verstehen.

Beste Grüße
Felix

**Comment by Woersty** [comment]
> Neuere Scriptsprache wie Python oder Ruby

Geht jetzt schon.
Ich selbst verwende im BLE Plugin Python und PHP 

> MVC-/HTML-/CSS-Frameworks für die Umsetzung des Webfrontends

JQuery UI ist doch ein Framework - und wird verwendet.

**Comment by Woersty** [comment]
Nachtrag: Du kannst dein Plugin programmieren wie du willst.
Allein die Konfigurations (Admin) Seite muss Perl sein.
Aber auch hier kannst du einfach den Seiteninhalt in einem eigenen "System" zusammenbauen
und dann einfach  in den "Inhalts-Bereich" parsen.
Im Grunde eine Zeile Code.

**Comment by mschlenstedt** [comment]
Hi,

Du musst unterscheiden zwischen dem Basissystem und den Plugins.

Das Basissystem ist in Perl geschrieben - für mich war es die einfachste Lösung, da ich Perl am Besten kann :-) Zudem halte ich Perl auch heute noch für ideal, wenn man im System Dinge verändern möchte, Konfigurstionsdateien bearbeiten/parsen/lesen möchte etc. Ist aber sicherlich auch mit einer anderen programmiersprache denkbar.

Die Plugins können alles mögliche an Programmiersprachen - bis hin zu C - verwenden. Wenn Du also den Funktionsumfang des LoxBerry mit einem Plugin erweitern möchtest, hast Du die absolute Wahl. Selbst wenn Du am Basissystem eine Funktion hinzufügen möchtest, kannst Du eine andere Sprache als Perl verwenden.

Kennst Du die Seite? http://www.loxwiki.eu:80/x/vICO

Grüße,
Micha

**Comment by mschlenstedt** [comment]
Da die Diskussion anscheinend verebbt ist und zudem wenig "spezifisch" mache ich hier mal zu. Bitte neue Postings erstellen wenn konkrete Dinge anstehen bzw. konkrete Änderungswünsche da sind.
