### ISSUE TITLE
Frame in LoxBerry

### ISSUE THREAD

**Issue by scharrin2** [mschlenstedt/Loxberry#129]
Hallo,

ich bin mir nicht sicher, ob es am Plugin (RPi-Monitor) liegt.

Ich kann auf der Seite zwar nach unten scrollen - allerdings wird der Frame irgendwann abgeschnitten.
Ich verwende Safari.

<img width="1280" alt="bildschirmfoto 2016-09-20 um 17 38 30" src="https://cloud.githubusercontent.com/assets/22325491/18677448/185b521a-7f59-11e6-8d79-991b5d078948.png">

Es müsste eigentlich noch was unter WiFi angezeigt werden, allerdings kann man nicht mehr weiter scrollen.

Viele Grüße,
Christian

**Comment by Woersty** [comment]
Probier mal von hier zu installieren: https://github.com/Woersty/LoxBerry-Plugin-RPi-Monitor/archive/master.zip
(Ist die aktuelle Entwicklungsversion)

**Comment by Woersty** [comment]
Wenn https://github.com/Woersty/LoxBerry-Plugin-RPi-Monitor/commit/931c1aaf9287e03556988c45ec4924042a15bc48 das nicht löst, bitte [hier](https://github.com/Woersty/LoxBerry-Plugin-RPi-Monitor/issues) als Issue melden.

**Comment by scharrin2** [comment]
Hallo Woersty,

super - jetzt passt es.

Gruß
Christian
