### ISSUE TITLE
Kein LAN-Device auf einem Pi3+

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1299]
Eventuell auch noch andere Pis betroffen? Screenshot von einem upgegradeten Pi3+, aktuell verbunden per LAN:

![image](https://user-images.githubusercontent.com/16830799/146782655-331b3656-dca0-4b71-bac3-f941bbf8b1bd.png)

**Comment by mschlenstedt** [comment]
Das könnte mein defekter Pi3 gewesen sein... Müssten wir nochmal prüfen.

**Comment by alexdie** [comment]
Ich kann das Problem auf einem Pi4 reproduzieren. Mit dem standard RaspberryPi OS 64bit Kernel 5.15.61-v8+ funktioniert der Ethernet Port wie erwartet.  
Mit dem aktuellen Loxberry-Image, egal mit welchen Updates, auch dem aktuellen development Stand, ist der Ethernet Port komplett weg und nirgendwo zu finden, nicht mal als device. 
Interessant ist dass mit Loxberry lsusb und lspci keinen Output liefern. In dmesg steht auch nichts auffälliges.

**Comment by mschlenstedt** [comment]
HIer geht es um den zukünftigen LB3.0.

Dein Problem wird mit einer neuen Revision des Pi4 Boards zusammenhängen. Vermutlich gehen auch die USB Ports nicht. Du musst beide Images testen, welches auf Deinem Board funktioniert:

http://download.loxberry.de/stable/images/rasppi/loxberry-image-rasppi-2.2.0e_pippin.img.7z

oder

http://download.loxberry.de/stable/images/rasppi/obsolete/loxberry-image-rasppi-2.2.0d_pippin.img.7z

**Comment by alexdie** [comment]
Nachdem es mit dem 2.2 Image nicht funktioniert hat habe ich es auch mit dem aktuellen 3.0 Stand versucht, und da das gleiche Verhalten beobachtet. Deswegen der Kommentar in dieses Issue. 

Mit dem e Image funktioniert es. Ich gehe davon aus dass der Upgrade-Pfad von dort aus dann auch funktioniert, werde das aber mal ausprobieren. Danke 👍
