### ISSUE TITLE
Logfile.cgi blockiert RaspPi (1)

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#130]
Tritt auch bei anderen auf.

Vermutlich nur RaspPi betroffen.

https://www.loxforum.com/forum/hardware-zubehör-sensorik/19159-vorstellung-loxberry-projekt-und-umfrage?p=57015#post57015

**Comment by mschlenstedt** [comment]
Was haltet ihr davon das Logfile gar nicht über irgendetwas zu parsen sondern direkt über Javascript einzulesen und fertig. Ist dann erst einmal ohne Syntax Highlighting, aber das ist meiner Meinung nach verschmerzbar. Damit läuft gar nix mehr auf dem RaspPi und gut ist.

Und Syntax Highlighting könnte man sicherlich auch irgendwie noch in Javascript implementieren (meine Kenntnisse reichen dazu allerdings nicht...)

**Comment by Woersty** [comment]
Ich schau mir das mal mit PHP und Ajax an.

**Comment by mschlenstedt** [comment]
Super. Per Ajax wird es schon eingelesen, aber eben nicht direkt aus einem Textfile sondern die Ausgabe von logfile.cgi. Man könnte im ersten Schritt einfach Deinen PHP-Logfileviewer aus dem Miniserverbackup-Plugin nehmen (der war Vorbild für meinen Perl-Logviewer :-)) und die fehlende Funktionalität aus logfile.cgi ergänzen.

**Comment by mschlenstedt** [comment]
Hopefully fixed in 0.2.3

**Comment by christianTF** [comment]
Bei der Installation passt's jetzt.
Geht man zu den Plugins, und dort auf "Zeige Logfile", kommt wieder der logfile.cgi
Ist aber nicht so wichtig.

**Comment by mschlenstedt** [comment]
Ja, für "einzelne" Anzeigen habe ich es gelassen. Hier wird nur eine 
Instanz aufgerufen und nicht permanent neu geladen (also ein normales 
CGI). Sollte also kein Problem darstellen.

Grüße,
Michael
