### ISSUE TITLE
uninstall und daemon mit beliebigen Dateiendungen zulassen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1308]
Aktuell dürfen die Skripte keine Dateiendung haben. Das verwirrt. Alle Endungen und alle Skriptsprachen sollen möglich sein.

**Comment by christianTF** [comment]
Ist das nicht genau das hier?
https://github.com/mschlenstedt/Loxberry/issues/1282

**Comment by mschlenstedt** [comment]
Jein. Ich habe das nur für die pre- und post-Skripte implementiert. Und nur für "ohne Dateiendung" oder mit ".sh". In allen Fällen wird aber der Shebang verwendet. Du kannst also ein Perl-Skript als "postinstall" oder "postinstall.sh" abspeichern. Aber **nicht** als "postinstall.pl".

Abgesehen davon, dass jetzt bei "uninstall" und "daemon" auch "uninstall.sh" und "daemon.sh" gehen soll, wäre die Frage, ob wir unbedingt auch "uninstall.pl" oder "uninstall.php" möglich machen wollen. Oder ob es ausreicht, dass man "uninstall" nimmt mit passendem Shebang.

**Comment by mschlenstedt** [comment]
Es gehen jetzt alle Dateiendungen bei allen Skripten, also auch .pl, .php, .py usw. Natürlich ist "keine Endung" auch möglich. Es können auch mehrere Skripte hinterlegt werden, die der Reihe nach ausgeführt werden, also z. B. uninstall.sh und uninstall.pl gemeinsam.
