### ISSUE TITLE
Nachinstallierte Pakete nach Plugin-Deinstallation wieder deinstallieren

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#131]
Mit apt-get autoremove

Es muss vorher sichergestellt werden, dass kein weiteres Plugin diese Pakete benötigt (Datenbank).

Anpassung der Plugin-Schnittstelle notwendig.

**Comment by andweber** [comment]
wenn man die Plugin-Schnittstelle anpasst, wäre zu überlegen ob nicht ein "deinstall.sh"-Skript sinnvoll wäre. Es besteht natürlich die Gefahr, dass das Plugin Dinge aufräumt, welche auch andere Plugins verwenden - aber es gibt sicher auch Fälle, wo das Plugin eindeutig der einzige Nutzer ist.

z.B. installiert das RPi-Monitor packet sein eigenes dep Archiv. Es wirkt im Moment nicht so, dass dies jemand beim deinstall wieder aufräumt.

**Comment by Woersty** [comment]
Haben wir schon auf dem Schirm ist aber nicht so einfach. Deshalb bisher nicht drin.
Halte ich aber auch für notwendig.

**Comment by christianTF** [comment]
Das ist sehr gefährlich. Dafür müsste es auch als Blacklist alle im Standard installierten Pakete geben.

Sonst schreib ich Perl ins apt, kein anderes Plugin installiert Perl, also Uninstall.

Sehr gefährlich.

**Comment by mschlenstedt** [comment]
Man könnte noch gegen /opt/loxberry/packages.txt prüfen.

**Comment by mschlenstedt** [comment]
Ich schlage vor das Feature nicht zu realisieren. Die Gefahr ist wie @christianTF  schon gesagt hat sehr groß, dass man das System zerschiesst. Der Nutzen ist zudem marginal - eine 32 GB SD-Karte ist ja fast schon Standard... Da kommt's auf die paar zusätzlich installierten pakete nicht an.

Oder hat schonmal jemand Pakete tatsächlich aus seiner Linuxinstallation entfernt?
