### ISSUE TITLE
PHP Templatebuilder

### ISSUE THREAD

**Issue by Liver64** [mschlenstedt/Loxberry#1313]
File loxberry_loxonetemplatebuilder.php require amendment in row 158:

As is: elseif ($this->_type == "VirtualInUdpCmd") {
To be: elseif ($this->_type == "VirtualInUdp") {

in addition usage of backslash results in not readable character: example "Check="MQTT:\iSonos4lox/vol/kids=\i"
the  is displayed as TV. Should be "Check="MQTT:\iSonos4lox/vol/kids=\i\v"

Escaping backslash works: "Check="MQTT:\iSonos4lox/vol/kids=\i\\v"

**Comment by christianTF** [comment]
Der Code ist gefixt.

Das mit dem Backslash ist normales PHP/Perl-Verhalten, wenn du doppelte Anführungszeichen verwendest. Dann muss der \ per \ escaped werden. Mit einfachen Anführungszeichen brauchst du nichts zu escapen.
Ich habe das in der Doku als Info ergänzt.
