### ISSUE TITLE
Nachträgliche Installation von LoxBerry auf einem Raspberry mit bereits installiertem Raspberry Pi OS (Raspbian)

### ISSUE THREAD

**Issue by toburger** [mschlenstedt/Loxberry#1317]
Ich wollte fragen, wie sich LoxBerry auf einem Raspberry System mit bereits installiertem OS installieren lässt.

Ich betreibe einen Raspberry PI Headless mit einigen Services (Samba, minidlna, pi-hole, ...) und er kommt dabei bei weitem nicht an seine Grenze was CPU oder RAM Auslastung anbelangt und da ich gerne selbst die volle Kontrolle über das System behalten möchte (OS Version, Services, die darauf laufen) würde ich gerne LoxBerry nachträglich auf dem bestehenden Server installieren.

Gibt es dafür eine Dokumentation oder ist es von den Systemanforderungen notwendig, dass man LoxBerry auf einem dedizierten Raspberry PI laufen lässt?

**Comment by mschlenstedt** [comment]
Eine automatische Installation gibt es nicht. Hier findest du die Anleitung wie wir ein Image erstellen. Die könntest du durcharbeiten. 

https://loxwiki.atlassian.net/wiki/spaces/LOXBERRY/pages/1201276236

**Comment by toburger** [comment]
Danke @mschlenstedt für die rasche Antwort! Ich werd mir die Anleitung mal durchlesen und dann entscheiden ob sich die manuelle Installation lohnt oder ob ich nicht ein par Euro in die Hand nehme und diese in einen zweiten Raspberry PI investiere. 😄

**Comment by Noschvie** [comment]
@toburger : wäre dann interessant zu wissen, wie du dich entschieden hast.

**Comment by toburger** [comment]
Nachtrag: habs jetzt doch auf einem eigenen Raspberry installiert.
