### ISSUE TITLE
Neue Hardware

### ISSUE THREAD

**Issue by bobmorane77** [mschlenstedt/Loxberry#1318]
Wird in Zukunft der Raspberry PI400 unterstützt?
Er bootet weder von SD noch USB-Stick.
Ein Raspi 4B 4GB normal bootet ohne Probleme.

Vielen Dank für die Info

**Comment by mschlenstedt** [comment]
Kannst du bitte einmal das folgende Image testen? Wenn, dann bootet es aber vermutlich nur von SDKarte. 

https://download.loxberry.de/testing/images/rasppi/loxberry-image-rasppi-2.2.0e_pippin.img.7z

**Comment by bobmorane77** [comment]
Perfekt
ja die Version 0e bootet sauber
Danke

**Comment by bobmorane77** [comment]
Nachtrag - booten von USB funktioniert auch mit der Version

**Comment by Noschvie** [comment]
Gibt es vielleicht für die "Raspberry Pi Compute Module 4" / CM4 Version ein Image zum Testen ? Danke

**Comment by mschlenstedt** [comment]
Nein, gibt es leider nicht.

**Comment by mschlenstedt** [comment]
Der Kernel des e-Image wird in den LoxBerry 3.0 integriert.
