### ISSUE TITLE
Netzwerkprobleme 2.2.0d_pippin

### ISSUE THREAD

**Issue by dmyrenne** [mschlenstedt/Loxberry#1319]
Mit dem 2.2.0d_pippin Image bekomme ich mit dem Raspberry Pi 4 4GB mit PoE Hat keine Netzwerkverbindung. Die Fehlermeldung lautet: "Can't raise network device"

Wenn ich die etwas ältere Version 2.2.0c_pippin auf dem selben Pi installiere, funktioniert alles ohne Probleme.

**Comment by Marlight96** [comment]
Geht mir genauso, schön wäre es wenn man es einfach auf dem PI nachinstallieren könnte... Bekomme es auf meinem PI einfach nicht zum laufen. Auf meinem NAS läuft es aber da funktionieren die Plugins nicht die ich brauche...

**Comment by mschlenstedt** [comment]
Dann nehmt einfach das 2.2.0c Image. Das d-Image ist nur ein Workaround für neuere Pi-Boards.  Wenn das C-Image bei euch funktioniert ist doch alles fein.

**Comment by mschlenstedt** [comment]
Das Problem liegt an dem neuen Chipsatz, der vomn Kernel des LB 2.2.x nicht unterstützt wird. Aktuell ist das e-Image, welches die Probleme behebt: http://download.loxberry.de/testing/images/rasppi/

Kernelupdate kommt mit der nächsten LB Revision. Dann  ist das Problem behoben.
