### ISSUE TITLE
Fehlermeldung bei Miniserver-Name"

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#132]
- Fehlermeldung nicht eindeutig
- Feld "Name" sollte weiter hoch und eventuell umbenennen?

**Comment by christianTF** [comment]
Formular redesigned, Validation auf Zeilenbasis, Fehlermeldungen klarer.
https://github.com/mschlenstedt/Loxberry/commit/d66c437e0ea047605f3ec2a00a0dd1c4f513aa0b
