### ISSUE TITLE
Navbar nicht bei 100% width

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1333]
Auf meinem Laptop wird die Navbar nicht mit width 100% angezeigt. Auflösung ist 1366x768.

![image](https://user-images.githubusercontent.com/16830799/192575671-0a5af937-6818-40ed-8349-46c8cf1544c2.png)

**Comment by christianTF** [comment]
Könnte mit dem Notification Bullet zu tun haben (#1338 )

**Comment by christianTF** [comment]
Gefixt mit https://github.com/mschlenstedt/Loxberry/commit/dc6808f6aa07e43c49740e2a9b0828f7f4e6d105
