### ISSUE TITLE
Alignment new NavBar and "Knödel"

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1338]
Missalignment when a "Knödel" is set in the navbar

![image](https://user-images.githubusercontent.com/16830799/194470099-1512bc2c-c95c-4732-82c0-5cfb9f31755d.png)

![image](https://user-images.githubusercontent.com/16830799/194473735-c8dce44b-6a3f-40d3-8017-62de866e7aa7.png)

**Comment by christianTF** [comment]
Wie hätt ma's denn gerne? :wink:

**Comment by mschlenstedt** [comment]
Ohne schwarzen Rand rechts 😉
