### ISSUE TITLE
Python lässt sich nicht Aktualisieren :-( bei vielen Plugins Installation (MiRobot2Lox-NG, FOSHKplugin)

### ISSUE THREAD

**Issue by Wunni73** [mschlenstedt/Loxberry#1340]
OK: Rust Toolchain installed successfully.
 INFO: Start installing Python Wheel...
Traceback (most recent call last):
File "/usr/local/bin/pip3", line 6, in 
from pip._internal.main import main
ModuleNotFoundError: No module named 'pip._internal.main'
yes: standard output: Broken pipe
Traceback (most recent call last):
File "/usr/local/bin/pip3", line 6, in 
from pip._internal.main import main
ModuleNotFoundError: No module named 'pip._internal.main'
 WARNING: Python Setuptools installation failed! We will continue anyway.
 INFO: Start installing Python Setuptools...
Traceback (most recent call last):
File "/usr/local/bin/pip3", line 6, in 
from pip._internal.main import main
ModuleNotFoundError: No module named 'pip._internal.main'
yes: standard output: Broken pipe
Traceback (most recent call last):
File "/usr/local/bin/pip3", line 6, in 
from pip._internal.main import main
ModuleNotFoundError: No module named 'pip._internal.main'
 WARNING: Python Setuptools installation failed! The plugin will not work without.
 WARNING: Giving up.
07.10.2022 20:06:41 CRITICAL: Script fails. Installation cannot be continued.
Use of uninitialized value in concatenation (.) or string at /opt/loxberry/sbin/plugininstall.pl line 1810.
Use of uninitialized value in concatenation (.) or string at /opt/loxberry/sbin/plugininstall.pl line 1811.

**Comment by mschlenstedt** [comment]
Siehe hier: https://github.com/mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG/issues/43

Ich hatte Dir dazu noch etwas geschrieben.
