### ISSUE TITLE
Init logfile database is ok. Error executing the test

### ISSUE THREAD

**Issue by scharrin2** [mschlenstedt/Loxberry#1341]
Beim Ausführen des Selbsttests erhalte ich folgende Meldung:

ERROR      Log Database        Init logfile database is ok. Error executing the test

Die im Wiki angegebene Lösung hat leider auch nicht zum Ziel geführt.

https://wiki.loxberry.de/haufig_gestellte_fragen_faq/message_the_logfile_database_sends_an_error_and_cannot_automatically_be_recovered

Auch das Löschen des gesamten Verzeichnisinhalts mit anschließendem Neustart konnte den Fehler nicht beheben.

Viele Grüße,
Christian

**Comment by scharrin2** [comment]
Ich habe noch folgende Fehlermeldung dazu gefunden:

Init logfile database is ok. Error executing the test: <DBD::SQLite::db selectrow_array failed: database disk image is malformed at /opt/loxberry/sbin/healthcheck.pl line 666.
>

**Comment by christianTF** [comment]
Imho ist bzw. war die Datenbank defekt. NUR die Dateien logs_sqlite.dat.* gehören zur Datenbank, nichts anderes!
Ich habe die Anleitung ergänzt, dass man auch das stündliche Backup löschen kann unter /opt/loxberry/logs/system/logs_sqlite.dat.bkp
Wenn das Löschen ohne Neustart nicht funktioniert, dann ggf. einen LoxBerry Neustart machen.

Das sind die einzigen Dateien, die mit der Datenbank zusammenhängen. Wenn das Log sagt, dass die DB kaputt ist, hilft nur das Löschen dieser Dateien.

lg, Christian

**Comment by scharrin2** [comment]
Hallo Christian,

danke - das war es.

Viele Grüße,
Christian
