### ISSUE TITLE
3.0 Update error setting permissions

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1348]
![image](https://user-images.githubusercontent.com/14220265/200656709-89833ade-35fd-406f-b00f-5947b4dca4a1.png)

https://github.com/mschlenstedt/Loxberry/blob/e6ebfb659ebbbacc55e590376c9f80bef7cda50b/sbin/loxberryupdate.pl#L296

**Comment by mschlenstedt** [comment]
Diese Zeile wurde geändert (kein resetpermissions in Plugin Verzeichnissen). Syntaxfehler?

https://github.com/mschlenstedt/Loxberry/blob/e6ebfb659ebbbacc55e590376c9f80bef7cda50b/sbin/resetpermissions.sh#L34

Originalzeile ist auskommentiert oben drüber.
