### ISSUE TITLE
LoxBerry bekommt 2 IP-Adressen zugewiesen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#135]
Eins ist mir aber aufgefallen: der Loxberry bekommt eine DHCP Adresse beim ersten Start. Soweit so gut. Ich setze die feste IP, auch ok. Trotzdem ist der Loxberry nachher unter der DHCP und der statischen IP erreichbar - er hat also zwei IPs! Nicht, dass es beim Otto-Normal-Verbraucher irgendwie auffallen würde oder in einem kleinen LAN Probleme verursacht. Ist trotzdem recht unschön. Ist das beim Raspi-Image auch der Fall? Ansonsten muss ich mal mein Image checken - ich sehe nämlich in der /etc/network/interfaces die richtigen Informationen...

**Comment by Shogun1978** [comment]
Kann durch sudo apt-get remove dhcpcd5 behoben werden. Empfehlung für nächstes Release: im Debian dem ersten Start deinstallieren mit o.g. Befehl. DHCP sollte nach wie vor funktionieren. Für alle laufenden Images: einfach via ssh mit dem loxberry User anmelden, sudo apt-get remove dhcpcd5 eingeben, fertig.

**Comment by mschlenstedt** [comment]
Besteht das Problem mit Debian Stretch immer noch?

**Comment by mschlenstedt** [comment]
Tritt seit LB3.0 wieder auf. Es hilft systemctl stop dhcpcd und systemctl disable dhcpcd

Diet Pi:
dhcpcd wird bei der Installation removed. --> Wird das wieder (nach)installiert?

LoxBerry Upgrade:
?
