### ISSUE TITLE
log_maint soll als root laufen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1352]
Es räumt die Daemons nicht zusammen, die als root laufen.
Logrotate hatte auch root-Dateien zusammengeräumt.

**Comment by mschlenstedt** [comment]
Das Thema hatten wir schon einmal. Das ist zu gefährlich. Da kannst du im Logverzeichnis einen Symlink auf /etc machen und er löscht dir das gesamte System weg.
