### ISSUE TITLE
Backup geht nicht 

### ISSUE THREAD

**Issue by Wunni73** [mschlenstedt/Loxberry#1357]
================================================================================
<LOGSTART> 24.11.2022 19:40:04 TASK STARTED
<LOGSTART> Clone SD card
<INFO> LoxBerry Version 2.2.2.2 ( is_raspberry.cfg )
<INFO> Loglevel: 6
<INFO> Version of this script: 3.0.1
<INFO> Executing user is root
<INFO> Executing command 'lsblk -b -O -J'...
<OK> Command executed successfully. - Exitcode 0
<INFO> Executing command 'findmnt / -b -J'...
<OK> Command executed successfully. - Exitcode 0
<INFO> Executing command 'findmnt /boot -b -J'...
<OK> Command executed successfully. - Exitcode 0
<INFO> /     is on partition /dev/mmcblk0p2
<INFO> /boot is on partition /dev/mmcblk0p1
<INFO> Boot device is mmcblk0
<INFO> Waiting 15s in case you changed your mind...
<INFO> Creating destination image file, size 5.8GB
<INFO> Executing command 'dd if=/dev/zero of=/opt/loxberry/system/storage/usb/USBC/loxberry_image_20221124_194005.img bs=1 count=0 seek=6274530304'...
<ERROR> ERROR executing command - Exitcode 1
<CRITICAL> Could not create Imagefile.
<LOGEND> Finished
<LOGEND> 24.11.2022 19:40:20 TASK FINISHED

**Comment by mschlenstedt** [comment]
Wenn du Fat32 als Dateisystem auf dem Stick hast, kann das nur Dateien bis 4 GB anlegen.  Welches Filesystem hast du auf dem Stick?

**Comment by Wunni73** [comment]
Fat32 usb Standart

**Comment by mschlenstedt** [comment]
Ja damit geht es nicht. Fat32 kann nur maximal 4 GB.

**Comment by Wunni73** [comment]
was dann

**Comment by mschlenstedt** [comment]
Ich bevorzuge eine nette Kommunikation in ganzen Sätzen und nicht einfach irgendwelche patzig hingeworfenen Wortbrocken. Ein wenig Höflichkeit kann man denke ich erwarten, wenn wir Dir in unserer Freizeit hier helfen.

So nicht.

**Comment by Wunni73** [comment]
Hallo 
Sehr geehrter Herr mschlenstedt
was ist dir Beste Formatierung für ein Backup USB StiCk
.
:;
