### ISSUE TITLE
Plugin-Tests: APT Performance

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#136]
Hi,

zwei Punkte fürs Testen von Plugins:

Zum einen, bei der Plugininstallation bei APT werden, wenn ich mich nicht getäuscht hab, die Pakete einzeln in einer Schleife installiert. Das dauert bei mir am RPi1 viel länger als wenn die Pakete einmal "in einer Wurst" übergeben werden.

Zum zweiten, wäre es für mich beim Testen angenehm, wenn nicht bei jedem Lauf apt-get update ausgeführt würde (das dauert am Rpi1 wirklich mind. 5 Minuten!). Hab leider keine bessere, verfügbare Hardware.
Vielleicht lässt sich das auch irgendwie zeitlich steuern, dass das bei einer Plugininstallation nur einmal pro Tag ausgeführt wird oder so. 
(ich hab's im Code jetzt mal auskommentiert)

lg, Christian

> foreach (@data){
>       s/[\n\r]//g;
>       # Comments
>       if ($_ =~ /^\s_#._/) {
>         next;
>       }
>       $message = "Command: $sudobin $aptbin -q -y install $_";
>       &loginfo;
>       system("$sudobin $aptbin -q -y install $_ 2>&1");
>       if ($? ne 0) {
>         $message = $phrase->param("TXT0079");
>         &logerr; 
>       } else {
>         $message = $phrase->param("TXT0080");
>         &logok;
>       }<

**Comment by mschlenstedt** [comment]
Gute Idee. Ich werde es so ändern, dass "apt-get update" nur ausgeführt wird, wenn der letzte Lauf 24h alt ist. Das dürfte für 99.9% aller Fälle ausreichen. Zudem füge ich noch hinzu, dass bei einem Fehler von "apt-get install" nochmal "apt-get update" ausgeführt wird und dann die Installation wiederholt wird. Dann dürften wir sauber sein.

Bzgl. der Installations-Scheife: werde ich integrieren. Du kannst dir helfen, indem du die ganzen Pakete in der Datei "apt" einfach in eine einzige Zeile schreibst, getrennt durch Leerzeichen. Bei der Installation wird einfach jede Zeile der Reihe nach an "apt-get install" übergeben. Wenn du alles in eine Zeile packst wird die komplette Zeile an "apt-get install" übergeben.

**Comment by Woersty** [comment]
Finde es ausreichend, dass man die Pakete in einer Zeile schreiben kann. Mache ich auch so.
Update der Doku sollte hier ausreichen.

**Comment by christianTF** [comment]
Wenn das geht, ok

**Comment by christianTF** [comment]
Wenn du die Pakete in der DB speicherst  (#131) , musst du das mit den Paketen in einer Zeile mit berücksichtigen.

**Comment by Woersty** [comment]
Split am Leerzeichen, fertig.

**Comment by christianTF** [comment]
War nur eine Gedankenstütze :-)

**Comment by mschlenstedt** [comment]
Fixed in 0.2.3:
- apt-get update wird nur alle 24h ausgeführt. Wenn die Istallation eines Pakets fehl schlägt, wird es direkt ausgeführt und die Installation noch einmal versucht
- Es werden alle Zeilen in der Plugin-apt-Datei gesammelt und dann "in einer Wurst" an apt-get install übergeben

Was noch fehlt: #131
