### ISSUE TITLE
Modifiziertes Icon für das Wiki 

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1367]
Ich kann bei den Browser-Tabs einen LoxBerry nicht mehr vom Wiki unterscheiden. 

Vielleicht können wir beim Wiki-Icon ein W oder sowas reinzeichnen.

![image](https://user-images.githubusercontent.com/14220265/204475745-6cb21848-b0fb-49f8-a1d8-f0b52f50d86c.png)

**Comment by mschlenstedt** [comment]
![image](https://user-images.githubusercontent.com/16830799/208380999-be03932c-94e7-481f-af79-4ea172c5af8e.png)

Erledigt.
