### ISSUE TITLE
Fehler im Aktuellen Master

### ISSUE THREAD

**Issue by Wunni73** [mschlenstedt/Loxberry#1368]
<img width="1422" alt="Bildschirm­foto 2022-11-29 um 21 37 47" src="https://user-images.githubusercontent.com/69694624/204642773-98f66cb8-c6c0-4dca-8ec0-9268c8e4c92b.png">
 
Fehler im aktuellen Master

**Comment by christianTF** [comment]
Von https://github.com/mschlenstedt/Loxberry/commit/2942b803bc507bc74235bc1afdc5d65e7ad28a34
