### ISSUE TITLE
Daemon wird nicht nach Installation ausgeführt

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#137]
Das Daemon-Script wird nicht am Ende der Installation ausgeführt, sondern nur bei Reboot.

Das ist konzeptionell ein Problem, weil ich im Daemon erst die Rechte setze, damit ich meine Prozesse starten und killen kann.

Michael, das solltest du nochmal überdenken, ob du nicht das postinstall als root ausführen kannst. Sicherheitstechnisch ist es wohl egal.

Alternativ wäre ein reboot_required-Switch in der Plugin-Config eine Idee, mit der du eine Jetzt/später rebooten Abfrage am Ende bringst.

lg, Christian

**Comment by mschlenstedt** [comment]
Von der Sicherheit her dürfte es wirklich egal sein. Was haltet ihr davon, wenn wir neben den Skripten noch ein weiteres Skript "root_install" o.ä. hinzufügen, was am Ende der Installation mit Rootrechten ausgeführt wird?

 Wenn wir "postinstall" mit Rootrechten ausführen müsste man ziemlich aufpassen mit welchen Rechten und unter welchem Besitzer und Gruppe die Dateien angelegt/gespeichert werden.

**Comment by Woersty** [comment]
root_install finde ich okay.
Details siehe eMail.
(PW Abfrage usw.)

**Comment by christianTF** [comment]
Jep, finde ich gut. Ich brauch darin nur mein Daemonscript aufrufen, also die Änderung fürs Plugin ist minimal.

**Comment by mschlenstedt** [comment]
#144
