### ISSUE TITLE
8000 CPUs

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1376]
![Screenshot_20221216-214656~2](https://user-images.githubusercontent.com/14220265/208186336-1d2dd116-b1a0-4076-89fe-879f925d02a2.png)

Debian VM

**Comment by mschlenstedt** [comment]
Ein Odroid hat 256 CPUs ;-)

![image](https://user-images.githubusercontent.com/16830799/222972604-efe36692-dae3-48ed-b3c9-95151dbb6a5a.png)
