### ISSUE TITLE
Reboot Switch bei Plugin-Installation

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#138]
Am Ende der Plugininstallation einen Button mit "Reboot" anzeigen, wenn das Plugin das benötigt.

Workaround heute: Per "echo" in postinstall.sh eine Meldung ausgeben - wird aber sicherlich oft übersehen.

**Comment by Woersty** [comment]
Dafür 👍🏻

**Comment by mschlenstedt** [comment]
Erledigt

**Comment by christianTF** [comment]
@mschlenstedt 
my $reboot_required_file = "$lbslogdir/reboot.required";

Wenn das File existiert, zeigt das Template in der Fußzeile auch eine Info an.
Man kann ins File einen Text schreiben (am besten appenden), dann wird im Power.cgi dieser Text angezeigt. Da könnte drinstehen, welches/welche Plugins den Reboot anfordern.

**Comment by mschlenstedt** [comment]
Bei der Plugininstallation wird ein Statusfile in /tmp angelegt, wo das WebGUI erkennen kann, ob die Installation noch läuft oder abgeschlossen ist. Heute wird nach Abschluss der ausgegraute Button "Weiter" aktiviert. Der Status wird dazu auf "0" gesetzt, während der Installation ist er "1". In Zukunft wird es einen weiteren Button "Reboot" gegeben, der nach Installation aktiviert wird, wenn das Plugin das anfordert (dann wird der Status auf 3 gesetzt). Der Benutzer kann dann immer noch entscheiden, ob er auf "Weiter" oder auf "Reboot" klickt.

**Comment by christianTF** [comment]
Ok, schreibst du trotzdem das File, dann bleibt es bis zum Reboot persistent im UI.
