### ISSUE TITLE
Known Issues LoxBerry 3.0

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1386]
- [x] LAN Devices nach Upgrade nicht mehr verfügbar (mindestens auf Pi1, Pi3)
- [x] Camstream4Lox funktioniert nicht mehr (vlc nicht mehr verfügbar?) --> ENDOFLIFE auf LB3.0
- [x] apcupsd zerschiesst das Upgrade (aus welchem Plugin stammt das?!)
- [x] Miniserver Backup funktioniert nicht mehr (Problem mit PHP Skript?)
- [x] Zigbee2Mqtt geht nach Upgrade nicht mehr, Neuinstallation nur bis 2.99 möglich
- [x] 1-Wire-NG installiert nicht (owfs Paket wird nicht gefunden)
- [x] HaBridge lässt sich nicht mehr installieren - Plugininterface 1.0)
- [x] S4L Untermenüs verschwinden
- [x] MotionEye: Basiert auf Python2, notwendige Installation ändert sich

**Comment by LoxMichael** [comment]
haBridge kann nicht installiert werden (The Plugin Interface is not supported by this LoxBerry Version)

**Comment by mschlenstedt** [comment]
Miniserver Backup läuft bei mir auf dem LB3.0 (frische Installation, Upgrade nicht getetstet).

**Comment by mschlenstedt** [comment]
Camstream4Lox wird "End of Life" - VLC unterstützt in Bullseye keine RSTP Streams mehr.

**Comment by mschlenstedt** [comment]
1-Wire-NG: MQTT Settings müssen umgestellt werden. Wird bis zum Release LB3.0 verfügbar sein. Umgesetzt ist es bereits, aber es fehlen noch weitere Bugfixes zur Geschwindigkeit.

**Comment by mschlenstedt** [comment]
apcupsd habe ich mal abgehakt - ich kenne kein Plugin, wo das integriert ist (Printer Daemon). War wohl selbst installiert...

**Comment by anghelcatalingeorge** [comment]
Grafana and Inlfuxdata: signatures couldn't be verified because the public key is not available
[20230205_230436_380_update-reboot-9.log](https://github.com/mschlenstedt/Loxberry/files/10661805/20230205_230436_380_update-reboot-9.log)

It tried for 10 times by rebooting and than stopped

**Comment by mschlenstedt** [comment]
You have to update Stats4Lox to the latest version (do not forget to backup your existing installation!) and then restart the LB Update.

**Comment by sennevb** [comment]
Can be added to known issues list: 
Miniserver backup not working since V3.0

**Comment by mschlenstedt** [comment]
Miniserverbackup added. Close this issue here now since LB3 is out now as RELEASE.
