### ISSUE TITLE
Network.txt: Ignore white spaces on parsing

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1397]
https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/372084-installation-von-loxberry?p=373843#post373843

Leerzeilen, Whitespaces etc. sollen ignoriert werden beim Übernehmen der Settings.

**Comment by mschlenstedt** [comment]
Die Datei war kaputt. Es war ein UTF8 Zeichen (Space) in der Datei.

Leerzeilen sind explizit erlaubt, Windows-Dateiendings werden schon jetzt automatisch nach Unix konvertiert.

Kein Handlungsbedarf.
