### ISSUE TITLE
Download des Images nicht möglich

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#14]
Also der Download des Images bricht immer wieder ab.
Mit dem Chrome kann man nicht mal neu ansetzen.
Daher empfehle doch den Download auf deiner Seite mit dem IE. 
Oder besser: Lade es auf Google Drive oder so hoch.
Oder ändere den Link auf meinen Google Drive Link. 
Ich habe es dort schon hochgeladen.

**Comment by mschlenstedt** [comment]
Ja, vermutlich liegt das am Webserver. Ich werde das nächste Image auf einen anderen Server legen - mal schauen ob das besser funktioniert.

**Comment by Woersty** [comment]
Das aktuelle liegt auch hier:

https://drive.google.com/file/d/0B8wa0dPIHusbUGJyaHZvbHhXZEE/view?usp=sharing

Mit freundlichem Gruß
Christian Wörstenfeld

---

Christian Wörstenfeld
Kalkbergeweg 10
D-12589 Berlin
Telefon: +49 30 50 15 8484
Mailbox: +49 30 55 15 1230
Fax:     +49 30 55 15 1232
Handy:   +49 30 55 15 1234
e-mail:christian@woerstenfeld.de
Threema: SV3C7MUX
Web: www.woerstenfeld.de
¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯

Am 14.07.2016 um 15:57 schrieb mschlenstedt:

**Comment by mschlenstedt** [comment]
Neuer Server.
