### ISSUE TITLE
Ajax Scripte finden Logdir nicht mehr

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1401]
Stats4Lox:
![image](https://user-images.githubusercontent.com/16830799/213967509-4fed5ddc-c3a9-4102-b632-c26bf00eeb29.png)

MotionEye:
![image](https://user-images.githubusercontent.com/16830799/213967559-31bee63c-7a97-4940-92b2-86b48acda74e.png)

Beide erzeugen das Log so:

```
my $log = LoxBerry::Log->new (
    name => 'AJAX',
        stderr => 1,
        loglevel => 7
);
```

**Comment by christianTF** [comment]
Das hängt sicher direkt mit dem https://github.com/mschlenstedt/Loxberry/issues/1403 zusammen.

**Comment by mschlenstedt** [comment]
Fixed in 03f0cf445e2eb949833cc8f50ae4a14165c406d8
