### ISSUE TITLE
User loxberry fix in die Gruppe audio aufnehmen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#141]
Hi Michael,

Kannst du bitte den loxberry-User fix in die audio-Gruppe aufnehmen.
gpasswd -a loxberry audio

Ich brauche jetzt sogar zwei Reboots, weil nach dem ersten Reboot wird der Command abgesetzt, aber da ist der User (ohne den audio-Gruppenkontext) schon angemeldet.

Da möglicherweise noch andere weitere Audio-Anwendungen kommen (z.B. Sprachausgabe), und die audio-Gruppe auch risikofrei ist, sollte das machbar sein.
Vielen Dank!

lg, Christian

**Comment by mschlenstedt** [comment]
Würde sich das erledigen, wenn es ein "post_install_root.sh" Skript gibt, welches mit Rootrechten nach der Installation aufgerufen wird?

**Comment by christianTF** [comment]
Ja, würde sich für mich erledigen (ich erzeuge jetzt einen eigenen Benutzer)! 
Für andere Plugins wird's eine Stolperfalle bleiben.

**Comment by mschlenstedt** [comment]
Ich packe den User mit in die Gruppe.

**Comment by mschlenstedt** [comment]
Fixed.
