### ISSUE TITLE
NodeJS Upgrade

### ISSUE THREAD

**Issue by romanlum** [mschlenstedt/Loxberry#1423]
Wäre es möglich Node von Version 12 auf mind.  14 zu heben?
Weil Zigbee2Mqtt braucht jetzt mind. 14.
Falls das nicht in absehbarer Zeit möglich ist, muss ich einen Workaround einbauen und für zigbee2mqtt eine eigene Node Instanz installieren.

Danke

**Comment by mschlenstedt** [comment]
Mit LB3.0 kommt NodeJS18. Ich denke das wird in den nächsten Tagen rauskommen (eventuell schon dieses WE). Du könntest bei Dir dann in der plugin.cfg LBMIN auf 3.0 setzen.

**Comment by romanlum** [comment]
sehr gut.
Danke für die schnelle Rückmeldung.

Dann lasse ich die aktuelle Version auf LB < 3.0 laufen und die nächste gibts dann erst mit LB >= 3.0
