### ISSUE TITLE
Healthcheck on Non-Raspberrys show no Architecture

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1425]
![image](https://user-images.githubusercontent.com/16830799/222972487-82595fe8-637f-4921-9e23-cc47d2570162.png)

Umbauen auf die DietPi-Routinen, wenn LoxBerry auf DeitPi läuft.

**Comment by matlab22** [comment]
Zeigt auch beim RP4 nicht alles korrekt an:
![image](https://user-images.githubusercontent.com/46869303/224942213-4e82b327-8b5c-49c4-84e3-7c9a4a802079.png)

**Comment by mschlenstedt** [comment]
Der von Dir gezeigte Report stammt von Linfo (einer externen Komponente, die wir mit eingebaut haben). Das werden wir nicht selbst fixen. Unseren eigenen Healthcheck hingegen können wir anpassen.
