### ISSUE TITLE
Kernel panic - Not Syncing: VFS - upgrade to v3

### ISSUE THREAD

**Issue by sennevb** [mschlenstedt/Loxberry#1428]
After upgrade from latest v2 version to V3.

Running on a synology VM.

Update was running for hours, when i came back it was not booting, giving kernel panic error.
I managed to boot using previous kernel- using afvanced options and selecting the previous kernel.

but then when icheck the logfiles it is having issues again installing the kernel  5.10.0-21-amd64

see log in attachment.

Any ideas? i'm using v2 again untill further notice
[kernel issues.txt](https://github.com/mschlenstedt/Loxberry/files/10892625/kernel.issues.txt)

**Comment by mschlenstedt** [comment]
We do not support these images officially. It is an issue with your distribution or the image. It installs a standard kernel amd64, which then let your Synology crashes.

I would recommend to install a fresh official image (DietPi - see https://wiki.loxberry.de/installation_von_loxberry/die_installation_von_loxberry/start) or ask the image maintainer in the LoxForum for help.

**Comment by sennevb** [comment]
Okay thanks, will try install dietPI as VM
