### ISSUE TITLE
Apache "Legacy"-Verzeichnis für Scripts ohne Plugin

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#143]
In der Apache-Config und im Filesystem sollte ein eigenes Directory existieren, in dem "Legacy"-Funktionen, also Code, für das es kein Plugin gibt, bereitgestellt werden kann.

Wenn es mal ein Loxberry-Backup gibt, sollte das Verzeichnis auch berücksichtigt werden.

Vielleicht einfach ein statisches Unterverzeichnis /opt/loxberry/webfrontend/cgi/legacy/, oder /opt/loxberry/webfrontend/cgi/plugins/legacy/

**Comment by mschlenstedt** [comment]
Kommt rein.

**Comment by christianTF** [comment]
@mschlenstedt Kannst du den Ort/Umsetzung kurzfristig einplanen, weil ich die Pfade für die Exclusion List des Auto-Updates bräuchte.
Danke! Christian 

PS: Es könnte grundsätzlich etwas außerhalb des /opt/loxberry Verzeichnisses sein, wenn der Pfad in der apache Config aufgenommen wird.

**Comment by mschlenstedt** [comment]
Integriert: f12e6387db0036ce64529585dda511b5b8080e49

Es gibt jetzt das Verzeichnis ~/webfrontend/legacy für Webserver-Dinge außerhalb eines Plugins. Die URL ist /legacy/....

Im Verzeichnis kann Perl/CGI, PHP und HTML verwendet werden und alle Webserveroptionen können per .htaccess gesetzt/überschrieben werden.
