### ISSUE TITLE
Security mail warnings after clean installation to dietPI

### ISSUE THREAD

**Issue by sennevb** [mschlenstedt/Loxberry#1430]
loxberry : Mar  6 19:20:59 : root : problem with defaults entries ; PWD=/opt/loxberry/webfrontend/htmlauth/system ; USER=loxberry ;

loxberry : Mar  6 19:20:59 : root : unable to resolve host loxberry: Name or service not known

**Comment by mschlenstedt** [comment]
The first one could be from cron.d - there was a permission problem there. This is fixed now with update 3.0.0.1

Last one is a problem on your system/network (no local name resolving).

**Comment by mschlenstedt** [comment]
Closed because of no response
