### ISSUE TITLE
bug in node module loxberry-express-dev-server.getLanguage

### ISSUE THREAD

**Issue by christophmoar** [mschlenstedt/Loxberry#1434]
Hi, durch den nodejs-plugin-generator landen im templates/lang Verzeichnis die Dateien

```
de.js
en.js
language_de.ini
language_en.ini
```

in der Methode getLanguage() wirft es dann beim Verarbeiten der *.ini Dateien eine Exception und die Translations sind dann alle nicht mehr verfügbar.

ich habe (für mich, in der Zwischenzeit) so gepatcht, dass ich

`if(file.endsWith('.js'))`

hinzugefügt habe.
Hier Code Snippet von funktonierender Funktion.

```
const getLanguage = async (defaultLanguage, templatePath, logger) => {
  let languages = {};
  try {
    const files = await fs.readdir(templatePath);
    languages = _.reduce(
      files,
      (acc, file) => {
        if(file.endsWith('.js')) {
          const content = require(path.resolve(templatePath, file));
          const language = file.replace('.js', '');
          acc[language] = {
            translation: content
          };
          return acc;
        }
        else
          return acc;
      },
      {}
    );
  } catch (e){
    logger.error(e);
    logger.info('No language files available');
  }

```

**Comment by christianTF** [comment]
Ich denke, du bist bei uns nicht richtig.
Frag bitte mal bei Ronald: https://www.loxforum.com/forum/projektforen/loxberry/entwickler/341239-plugin-generator-f%C3%BCr-neue-plugins

lg, Christian

**Comment by christophmoar** [comment]
ach, sorry vielmals, hab wohl falschen link verfolgt. (－‸ლ)
melde mich drüben, thx.
