### ISSUE TITLE
Could not set up Samba Config

### ISSUE THREAD

**Issue by AND-8** [mschlenstedt/Loxberry#1436]
Frische Installation auf **Hyper-V**

────────────
Configuring Samba...
───────────

mv: cannot stat '/etc/samba': No such file or directory
/dev/fd/63: line 626: testparm: command not found

[FAILED ] .... Could not set up Samba Config.

**Comment by AND-8** [comment]
Windows 11, Hyper-V, Installation am 13.3.2023. 
<img width="467" alt="image" src="https://user-images.githubusercontent.com/67679720/224684437-36f2d056-2457-490b-af40-82a4018e9c8b.png">


Log 
<img width="843" alt="image" src="https://user-images.githubusercontent.com/67679720/224685837-6bcea208-524b-450e-853d-f7b82c4ec11a.png">

**Comment by mschlenstedt** [comment]
Kannst du bitte das gesamte Logfile hier anhängen? Liegt in /boot

**Comment by AND-8** [comment]
[loxberry_install.log](https://github.com/mschlenstedt/Loxberry/files/10956822/loxberry_install.log)
Anbei das Log File

**Comment by mschlenstedt** [comment]
Kann ich leider gerade nicht nachvollziehen noch nachstellen - habe aber auch kein HyperV. Er hat bei Dir Samba korrekt installiert (zumindest laut Log) - komisch ist aber, dass /etc/samba dann angeblich nicht existieren soll.

Seltsam auch die Fehlermeldung "/dev/fd/63". Hier steht, dass es etwas mit dem SSH Client zu tun hat. Nutzt Du Putty?

https://askubuntu.com/questions/1086617/dev-fd-63-no-such-file-or-directory

**Comment by AND-8** [comment]
Danke für deine schnelle Hilfe, dann kannst du hier schließen.
Ich habe es heute versucht mit der 3.0.0.2 nachzustellen.
Leider konnte ich es NICHT reproduzieren.

Gestern hatte ich die 3.0.0.1.

**Comment by andy0172** [comment]
Ich habe genau den gleichen Fehler, komplett neue Installation auf einem Loxberrry v2 ArmV7
Ich nutze Putty von Windows aus.

Das ist etwas was ich im Log finden konnte:

Created symlink /etc/systemd/system/multi-user.target.wants/nmbd.service → /lib/systemd/system/nmbd.service.
Failed to preset unit: Unit file /etc/systemd/system/samba-ad-dc.service is masked.
/usr/bin/deb-systemd-helper: error: systemctl preset failed on samba-ad-dc.service: No such file or directory
Created symlink /etc/systemd/system/multi-user.target.wants/smbd.service → /lib/systemd/system/smbd.service.
samba-ad-dc.service is a disabled or a static unit, not starting it.

**Comment by mschlenstedt** [comment]
Loxberry V2? Der ist nicht aktuell.
