### ISSUE TITLE
DietPi: Timezone not CEST

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#1440]
Nach der Neuinstallation ist die Zeitzone nicht CEST, sondern irgendwas "BET" (kann mich nicht mehr erinnern, irgendwas mit B) und geht eine Stunde hinten.
Es muss erst einmal die Zeitzone im Widget gesetzt werden, damit es CEST wird.

Wenn das Zeit-Widget entfällt, gehört die Zeitzoneneinstellung ins My Loxberry Widget.

**Comment by christianTF** [comment]
[setdatetime.log](https://github.com/mschlenstedt/Loxberry/files/11147746/setdatetime.log)

Hier sieht man beim Log der Uhrzeit, dass er die Zeitzone übernimmt.

**Comment by mschlenstedt** [comment]
Ich setze die Timezone im Installer nicht. Daher wird im Widget die (falsche) Timezone aus der Default-Config angezeigt, während der LoxBerry auf der Default-Timezone von DietPi läuft. nach dem einmaligen Speichern müsste es korrekt sein.

Das Widget würde ich belassen, nur die Synchronisation mit dem Miniserver entfernen und zum Setzen des NTP-Servers die Default-Funktionen von DietPi nutzen. Auf einem Raspbian-System bleibt alles wie es ist.

**Comment by mschlenstedt** [comment]
Fixed in https://github.com/mschlenstedt/Loxberry_Installer/commit/6471c8c61430d92c438ba14d49bcf58271acf3f1
