### ISSUE TITLE
Network shares not connecting

### ISSUE THREAD

**Issue by KrisDeCaluwe** [mschlenstedt/Loxberry#1441]
Hi Michael,

Whilst doing some testing I noticed my network shares on version 3003 did not connect to my sinology. It turned out the smbclient was not working. I did resolve this by running the following command:
apt-get install  samba-common smbclient samba-common-bin smbclient  cifs-utils
[netshare_debug.log](https://github.com/mschlenstedt/Loxberry/files/11152563/netshare_debug.log)

**Comment by mschlenstedt** [comment]
Well, all your samba packages were missing. Cannot find the problem here on my installations. Was this a fresh DietPi installation or an upgrade from LoxBerry 2.0?

**Comment by KrisDeCaluwe** [comment]
This was an upgrade from the loxberry 2.0. Also my usb disk refused to work. In the meantime I restored my system back to loxberry 2.0

**Comment by mschlenstedt** [comment]
Ok, then we cannot help anymore. With no access to the broken system analysing is not possible.

We fixed some problems in latest 3.0.0.6, mayber this helps.
