### ISSUE TITLE
Sonderzeichen bei Miniserver User/Passwort gehen nicht

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#145]
Siehe Titel

**Comment by Woersty** [comment]
Ist das ein generelles Problem oder nur eins vom Miniserverbackup-Plugin?

**Comment by mschlenstedt** [comment]
Nee, generell geht das nicht.

**Comment by christianTF** [comment]
https://github.com/christianTF/Loxberry/commit/c6432456c8d1717d0f3de05af266cccaac65c23e

URL-Encoding von User/PW im Setuzp-Wizzard und Miniserver-Dialog
Ich muss das generell noch mit Sonder-Sonderzeichen durchtesten, dann kann man auch mal versuchen, die Limitierung des Formulars zu entfernen.

Verhalten danach: 

- Alte Plugins bekommen die Credentials aus der general.cfg dann URL-encoded --> solange User keine Sonderzeichen verwenden, keine Änderung für die Plugins

- Werden die Credentials aus einem Plugin für Webaufrufe verwendet, funktionieren diese dann auch mit Sonderzeichen.

- Werden die Credentials vom Plugin für andere Programme benötigt, die URL-Encoded nicht verstehen oder benötigen, funktionieren diese weiter, solange der Benutzer keine Sonderzeichen verwendet.

- Werden die Credentials vom Plugin für andere Programme benötigt, die URL-Encoded nicht verstehen oder benötigen, und der Benutzer verwendet Sonderzeichen, werden diese Plugins aufschlagen --> Umstellung auf LoxBerry::System und {Admin_RAW} bzw. {Pass_RAW}
