### ISSUE TITLE
Permission denied Apache log

### ISSUE THREAD

**Issue by matlab22** [mschlenstedt/Loxberry#1450]
Dead link:
![image](https://user-images.githubusercontent.com/46869303/235324386-bcc5a871-d601-4fba-859b-f69597f3f5f8.png)

```
Software error:

Cannot open file: Permission denied at /opt/loxberry/webfrontend/htmlauth/system/tools/logfile.cgi line 232.

Depending of what you have done, report this error to the plugin developer or the LoxBerry-Core team.
Further information you may find in the error logs. 
```

**Comment by mschlenstedt** [comment]
Are you on an upgraded LoxBerry from V2.x or on a fresh installation via DietPi? Which architecture? Raspberry, VM, something else?

**Comment by matlab22** [comment]
It is a DietPi clean installation on a Raspberry Pi4. Everything is running from an external SSD.

I have a second Rp4 wich I set up later running on a SD card. And I just checket this raspberry has no issue to show the Apache Log. It might be a problem to my installation.

**Comment by mschlenstedt** [comment]
Checked on my Developement LoxBerry (DietPi VM) without any problems. As you already said: Must be a problem of your installation.
