### ISSUE TITLE
ALSA-Mixer als Basis-Komponente

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#146]
Hi Michael,

bezüglich ALSA-Mixer:
Ich kann die Integration gerne als Basiskomponente erstellen. Ich würde mich aber auf jeden Fall auf ein bestehendes CPAN-ALSA-Modul stützen, und primär ein UI dazu machen. Man muss das Rad nicht neu erfinden.

Was ich auf jeden Fall haben möchte, ist, dass sich der Mixer "abdocken" lässt, also in einem eigenen Fenster aufrufbar ist. Als Basis-Funktion könnte man das Abdocken auf einen Link im eingebetteten Mixer legen.

Womit ich mich noch nicht beschäftigt habe, ist, wie der Aufbau sein müsste.
Wenn ich den Mixer wie ein Plugin-CGI schreibe (mit Einbinden von Header, Footer), kannst du das dann leicht in Basis-Feature umbauen?

lg, Christian

**Comment by mschlenstedt** [comment]
Hi,

finde ich klasse! Im Ersteinrichtungsassistenten benutze ich bei der WLAN-Einrichtung auch bereits "externe" Fenster, das ist problemlos realisierbar. Das Ganze auf Basis des CPAN-moduls zu machen ist ebenfalls vernünftig.

Im Prinzip hast Du 2 Möglichkeiten: Du machst es als Plugin und ich integriere es später oder Du "forkst" den LoxBerry-Branch und integrierst es direkt (so machen es Wörsty und ich zur Zeit). Anschließend kannst Du Deine Änderungen per Pull Request zurück zu meinem Original-Branch schicken, wo es dann direkt integriert wird.

Der aktuelle Entwicklerbranch ist "loxberry-0.3.0-saruman".

**Comment by mschlenstedt** [comment]
Gibts ja seit langem als Plugin. Ich mache es also hier mal zu.
