### ISSUE TITLE
configure upstream repo/account in general.json

### ISSUE THREAD

**Issue by nufke** [mschlenstedt/Loxberry#1469]
In order to facilitate testing of Loxberry updates, it would be good to configure the upstream repo/account in the `general.json` file.
Currently this github repo is hardcoded in many files, which makes it quite difficult to point to another account.
Please let me know if you would support this request, then I will create a PR for this.

**Comment by mschlenstedt** [comment]
I merged your changes into https://github.com/mschlenstedt/Loxberry/tree/mqtt_tls

Currently we do not plan to make the repo/account configurable. It's fixed to our main dev repo. But you can configure the branch in general.json via Update.Branch - see https://wiki.loxberry.de/entwickler/advanced_developers/generaljson

**Comment by nufke** [comment]
Thanks for updating this branch. Yes I did already use the Update Branch option for early testing using my own master, but for this I had to change the account at several places, not very practical.. 
In the end it is a *chicken-egg* problem: how to make sure a PR is tested before it is actually created :-)
