### ISSUE TITLE
LoxBerry UI 

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#147]
Hallo Michael,

Punkt 1:
Ich hätte mich "als Plugin" gerne ins Menü links "eingehängt" (mit Submenüs).
Wenn man mehr Einstellungen hat, muss man sonst im Plugin selbst eine eigene Menüführung erzeugen.

Punkt 2: 
Allgemein finde ich, dass die ganzen Systemmenüs zu dominant sind, und die Plugins unten verschwinden. Die ganzen System-Settings selbst sollten - so finde ich - auch in einem Hauptpunkt mit einem aufklappenden Submenü verschwinden. 
Das ganz wichtige (z.B. Neustart oder sowas) könnte auf oberster Ebene bleiben.

Punkt 3:
Die einblendbare Hilfe (rechts) sollte fest eingeblendet bleiben. Es ist aus meiner Sicht nicht hilfreich, wenn sie beim Starten nicht sichtbar ist, und auch nicht hilfreich, wenn der Main-Frame beim Hilfe-Klicken nach links hinausgeschoben wird, und man beim Anzeigen der Hilfe nichts einstellen/tippen kann.

lg, Christian

**Comment by mschlenstedt** [comment]
**Zu 1:**

Einverstanden. Wir könnten es so machen, dass man im Plugin eine Datei mit der Menüstruktur hinterlegen kann. Damit könnte man auch selbst entscheiden, auf welche Datei das Icon aus dem Hauptmenü zeigen soll (heute fest auf webfrontend/cgi/.../index.cgi). Einige Plugins benutzen Perl gar nicht, sodass mir das heute nicht so recht gefällt. Wenn keine entsprechende Datei im Plugin vorhanden ist wird der Default (=so wie heute) verwendet.

Einzigstes Problem: Ich sitze gerade nicht am meinem Rechner, aber wenn ich mich recht erinnere habe ich für das Seitenmenü das Listview-Element von JQuery Mobile "missbraucht" - und das bietet keien aufklappbaren Menüs. Man könnte aber etwas mit dem "Collapsible listview" machen: http://demos.jquerymobile.com/1.4.5/listview-collapsible-item-flat/

Ich schaue mal was da geht. Ich möchte nur ungern auf ein anderes Framework wechseln (zu viel Arbeit bei noch zu vielen anderen Baustellen).

**Zu 2:**

Völlig einverstanden, fliegen raus. Reboot usw. braucht gar nicht ins Seitenmenü, ist sowieso permanent am unteren Bildschirm verfügbar.

**Zu 3:**

Das sehe ich etwas anders. Ich arbeite überwiegend am Laptop mit 1300 oder 1400 Pixeln oder in der Größenordnung. Nicht alle sind solche "IT-Cracks" wie Wörsty und Du :-) Mit meinem kleinen Bildschirm würde ein permanentes Seitenmenü einfach zu viel Platz wegnehmen! Das man keine Eingaben machen kann wenn das Seitenmenü aufgeklappt ist, ist in der Tat unschön. Nur bietet das Framework soweit ich gesehen habe leider nichts anderes: http://demos.jquerymobile.com/1.4.5/panel/ Und wie gesagt: zum jetzigen Zeitpunkt würde ich ungern wechseln...

**Comment by christianTF** [comment]
Zu 3: 
Ich kenn mich mit node.js praktisch nicht aus, und Prio hat das gar nicht, wenn es technisch nicht leicht umsetzbar ist. 
Im Responsive Panel Demo (http://demos.jquerymobile.com/1.4.5/panel-responsive/) schaffen sie's, das linke Menü einzublenden und die page bleibt bedienbar. Ich hab mich mit den Developer Tools des Chromes etwas gespielt, die class ins HTML hineinzupatchen, hab's aber nicht geschafft.
Alle drei Punkte haben keine Prio - Punkt 1 sollte man als Plugin-Framework nicht unbeachtet lassen, und deine Idee mit dem Menüfile find ich sehr gut!

**Comment by Woersty** [comment]
Bin auch kein IT-Crack - aber mit Platzproblemen auf den Monitoren habe ich nicht zu kämpfen, das stimmt 😁 
![workspace](https://cloud.githubusercontent.com/assets/20454116/19085437/980994d8-8a6a-11e6-9ee8-abe81740f6d1.png)

Man könnte als schnelle Lösung die Plugins ganz einfach nach oben holen.
Und die Systemeinstellungen nach unten schieben. Der Aufwand dafür ist fast Null.

**Comment by mschlenstedt** [comment]
Du bist krank :-) :-) :-) Unglaublich!

Die Umgestaltung des linken Menüs (Plugins mehr Platz vor Systemeinstellungen) ist nicht das Thema - das machen wir. 

Beim rechten Menü muss ich mir das Responsive Design mal genau anschauen (Link von Christian). Da geht es tatsächlich beim **linken** Menü - ich hatte mir immer nur das rechte Menü angeschaut und da geht es auch nicht. 

Mal sehen, vielleicht geht da etwas. Arbeitsauftrag auf jeden Fall verstanden :-)

Und Punkt 1 nehme ich mit auf, das kommt definitiv in die Pluginschnittstelle Version 2.

**Comment by christianTF** [comment]
> Punkt 1:
>Ich hätte mich "als Plugin" gerne ins Menü links "eingehängt" (mit Submenüs).

Obsolet bzw. Erledigt: NavBar ist nun Bestandteil von LoxBerry::Web.

> Punkt 2:
> Allgemein finde ich, dass die ganzen Systemmenüs zu dominant sind

Erledigt in der neuen index.cgi

> Punkt 3:
> Die einblendbare Hilfe (rechts) sollte fest eingeblendet bleiben. 

Erledigt mit der Überarbeitung der header/footer auf responsive.

Deswegen: Closed.
