### ISSUE TITLE
WebUI for SSL is broken

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#1478]
In my stable installation:

![image](https://github.com/mschlenstedt/Loxberry/assets/16830799/d10cfe9e-c455-434e-b074-794e51c2c370)

**Comment by svethi** [comment]
Hast Du da irgendwas umgestellt bei Dir? In meiner 3.0.0.6. stable ist da nichts. Ist ja auch kein Fehler, sondern ein Hinweis.

**Comment by Noschvie** [comment]
V3.0.0.6 am Desktop und am iPad getestet und nicht reproduzierbar.

**Comment by svethi** [comment]
Changed behaviour.

**Comment by mschlenstedt** [comment]
Sorry, hatte ich aus Versehen beim Testen aktiviert.
