### ISSUE TITLE
Weiterleitung auf Antwortseite nach Neustart-/Herunterfahrenbefehl

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#148]
Es wäre sehr von Vorteil die Antwort nach Neustart-/Herunterfahrbefehl auf eine neue Seite weiterzuleiten (neue URL im Browser) so besteht nämlich das Problem, dass beim Wechseln auf die Seite des Loxberry nach einem vorherigen Restart/Shutdown fährt den Loxberry dummerweise gleich wieder runter.

**Comment by mschlenstedt** [comment]
Kannst Du das bitte noch einmal etwas genauer beschreiben? Wieso fährt 
der LoxBerry dann gleich noch einmal herunter? Ich hatte es vor so zu 
lösen wie beim Ersteinrichtungsassisten, kannst Du den bitt emal 
probieren? Da funktioniert es meiner Meinung nach.

**Comment by svethi** [comment]
Wie kann ich eigentlich die Labels setzen? Ist ja nichts Wichtiges :-)

Also. Der Fall war so. Ich hatte nachmittags was getestet und den Loxberry runter gefahren (ist ja nur Test für Pluginentwicklung). Dann hatte ich mir überlegt, dass ich später noch etwas spielen möchte und hab ihm wieder Strom gegeben.
Als ich auf die Adminoberfläche drauf wollte, war da leider noch die Seite mit "wird jetzt runtergefahen ... OK"  Der Browser hat aber gleich die Seite aktualisiert/neu geladen und damit ist der Loxberry gleich wieder runtergefahren. Kannst Du mir folgen?

Gruß Sven

Von meinem iPhone gesendet

**Comment by Woersty** [comment]
Ich kann dir folgen 😀

**Comment by mschlenstedt** [comment]
Auch kapiert - Danke :-)
