### ISSUE TITLE
templates/plugins/miniserverbackup/de/settings.html

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#15]
<input id="bkpcounts" name="bkpcounts" type="text" data-validation="number" data-validation-allowing="range[1;200]" class="textfield"
-          value="" data-validation-error-msg="\* **BItte** eine Zahl zwischen 1 und 200 eingebe**n.i D**iese Anzahl an (alten) Backup-Dateien wird zum Download bereitgestellt. Ältere Archive werden gelöscht.">

Ich schlage 365 vor und der Text hat auch 2 kleine Fehler.

**Comment by mschlenstedt** [comment]
Nochmals Danke :-) Es ist manchmal schon etwas spät wenn ich die Templates bearbeite :-) Ich habe es jetzt auf 500 erweitert - das sollte reichen.
