### ISSUE TITLE
Webaufruf nur über Namen

### ISSUE THREAD

**Issue by torro10** [mschlenstedt/Loxberry#152]
Hi,
ich habe heute Loxberry erstmalig installiert und bei der Installation eine feste IP Nummer zugewiesen. 
Nach dem Abschluss der Installation ist der Aufruf der Startseite zwar mit der IP Nummer möglich, aber sämtliche Untermenues sind so nicht erreichbar. Mann muss zwingend die Weboberflaeche mit den Namen aufrufen, dann funktioniert es.
Das soll so doch sicher nicht sein, oder?

**Comment by mschlenstedt** [comment]
Kannst Du mal einen Sceenshot von Deinem Browser machen (so, dass ich die Adressleiste sehe), nachdem Du auf einen Menüeintrag geklickt hast?

Das von Dir geschilderte Verhalten dürfte nicht passieren und passiert hier auch nicht (ich rufe den Loxberry immer über die IP-Adresse auf).

**Comment by torro10** [comment]
Hallo,
habe es gerade nochmal probiert, allerdings mit einem neuen Aufruf im Browser, da hat es funktioniert. Es scheint also so zu sein, dass es nur nach der Installation so ist. Sobald man das im Browser neu aufruft, ist es in Ordnung. 
Keine Ahnung, wie ich das jetzt nochmal nachstellen kann.
