### ISSUE TITLE
Passwort

### ISSUE THREAD

**Issue by Strike1988** [mschlenstedt/Loxberry#153]
Ich habe mein PW aus versehen beim Login etwas anders geschrieben. Kam aber trotzdem rein. Original PW z.B. "XXXXXXX1" und falsch war "XXXXXXX2".

**Comment by mschlenstedt** [comment]
Hi,

kann ich nicht repoduzieren. Kannst Du uns mal ein reales Beispiel geben?

**Comment by Strike1988** [comment]
Probier mal die letze Stelle deines PW abzuändern! Z.b. "Passwort" gegen "Password". Ich möchte hier mein PW nicht nennen.

**Comment by Strike1988** [comment]
Habe jetzt "passwort123" festgelegt! Und Passwort "passwort122" eingegeben! Bekomme trotzdem Zugriff!

**Comment by mschlenstedt** [comment]
Konnte es auch reproduzieren. Da wir die Passwortroutine des Apache Webservers in Kombination mit dem System crypt() Modul verwenden, kann ich da wenig tun. Das muss ein generelles Problem sein, bin aber kein Cryptoexperte....

Kann ich mir aktuell nicht erklären...

**Comment by Woersty** [comment]
Ist ein Session Problem vom Chrome, vermute ich.

Probier mal den Browser zu schließen.

Am 10.10.2016 um 21:48 schrieb mschlenstedt:

**Comment by mschlenstedt** [comment]
Das scheint nicht nur ein Session-Problem zu sein. Ich habe jetzt einfach mal einen Browser genommen, mit dem ich mich noch nie auf dem LoxBerry eingeloggt habe. Und auch da geht weiterhin das alte Passwort...

Neues Passwort: gEheim25
Altes Passwort: gEheim24

Ich kann's mir nicht erklären. Finde aber auch bei Google nichts vergleichbares. Eventuell hat es damit zu tun wie ich den Salt generiere?

**Comment by Woersty** [comment]
Nimm doch auch einfach mal einen anderen Algorithmus. => bcrypt
[https://www.dailycred.com/article/bcrypt-calculator](https://www.dailycred.com/article/bcrypt-calculator)
https://httpd.apache.org/docs/2.4/misc/password_encryptions.html

**Comment by mschlenstedt** [comment]
Danke, hab' mir schon so etwas gedacht. Wird in 0.3.0 gefixt.

**Comment by mschlenstedt** [comment]
Gemäß Apache Doku https://httpd.apache.org/docs/2.4/misc/password_encryptions.html

"Note that using myPasswo instead of myPassword will produce the same result because only the first 8 characters of CRYPT passwords are considered."
