### ISSUE TITLE
locales reduzieren

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#155]
Mein Pi 1 braucht während apt-get upgrade circa eine Stunde, um die locales zu generieren.
Eingestellt ist im Image "all" (dpkg-reconfigure locales), d.h. aller Herrgotts Ländereinstellungen werden neu generiert.
Optimal wäre hier, das auf die deutschsprachigen Länder, sowie englisch und die "Loxone"-Nachbarländer einzuschränken.

Jedes UTF-8-Locale braucht ca. 12-13 Sekunden, jedes ISO-8859 ca. 7 Sekunden. 
Es gibt ca. 460 locales, also ca. 75 Minuten. 

lg, Christian

**Comment by mschlenstedt** [comment]
Nehme ich mit auf.

**Comment by mschlenstedt** [comment]
Erledigt.
