### ISSUE TITLE
Plugin-Installation php5 php5-curl

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#156]
Hallo Michael,

ich glaub, ich habe auf Helmuts LoxBerry mit der Installation von php5 und php5-curl im Plugin die apt-Datenbank angeknackst.

Bei der Erstinstallation kam:
<INFO> Command: /usr/bin/sudo /usr/bin/apt-get -q -y install  php5 php5-curl
...
The following extra packages will be installed:
  libapache2-mod-php5 php5-cli php5-common php5-gd php5-mcrypt php5-mysql
  php5-readline php5-sqlite
Suggested packages:
  php-pear php5-user-cache
The following packages will be upgraded:
  libapache2-mod-php5 php5 php5-cli php5-common php5-curl php5-gd php5-mcrypt
  php5-mysql php5-readline php5-sqlite
10 upgraded, 0 newly installed, 0 to remove and 89 not upgraded.

und eine Menge Meldungen 

debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 

Beim Plugin-Update kommt nun

<INFO> Command: /usr/bin/sudo /usr/bin/apt-get -q -y install  php5 php5-curl
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
<ERROR> Paket konnte nicht installiert werden

Meine php5-curl Installation hat php irgendwie durcheinander gebracht.

Ich werde das, wenn Helmut heute Abend Zeit hat, direkt auf seinem Pi fixen. 
Mir ist aber nicht klar, warum aus dem Basis-Image heraus so viele PHP5-Komponenten nachinstalliert werden...?

Jedenfalls muss man das im Auge behalten, nicht dass beim nächsten Update alle LoxBerrys "sterben".
Wenn's am Wochenende baustellenmäßig geht, werd ich das mal mit einem neuen Image probieren.

[logfile 1.cgi.txt](https://github.com/mschlenstedt/Loxberry/files/543693/logfile.1.cgi.txt)
[logfile 2.cgi.txt](https://github.com/mschlenstedt/Loxberry/files/543694/logfile.2.cgi.txt)

lg, Christian

**Comment by mschlenstedt** [comment]
Diese Fehlermeldungen kommen weil ich stdout und stderr auf das Logfile umbiege. Aber die apt-Datenbank dürfte nicht zerscossen werden.

Ich habe Dein Plugin jetzt auch mal getestet und mein LoxBerry hing komplett bei der PHP-Installationsorgie. Wenn man dann abbricht ist die APT-Datenbank defekt.

Ich denke das Image ist mittlerweile auch schon recht alt - wird Zeit für ein komplettes "apt-get upgrade" und "apt-get dist-upgrade". Das plane ich für das LoxBerry 0.3.0-Image.

Es wird vermutlich kein einzelnes Upgrade-Paket von 0.2.x auf 0.3.x geben sondern nur die Möglichkeit über ein frisches Image upzugraden, damit wir die LoxBerrys wieder auf eine Stand haben. Ist zwar etwas blöd für alle, die den LoxBerry produktiv einsetzen, aber irgendetwas ist ja immer

**Comment by christianTF** [comment]
Darf ich dazu einen 0.2.4er Vorschlag machen, nämlich ein Config-Backup zum Downloaden und Uploaden, mit den Config-Verzeichnissen von System und Plugins.
Wenn es nämlich aufwändigere Configs werden...

**Comment by Woersty** [comment]
Bei mir:

root@loxberry:/opt/loxberry# apt-get remove dnsmasq
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to 
correct the problem.
root@loxberry:/opt/loxberry# dpkg --configure -a
Setting up libapache2-mod-php5 (5.6.26+dfsg-0+deb8u1) ...
apache2_invoke php5: already enabled

Man könnte "dpkg --configure -a" einfach generell einbauen, oder?

Mit freundlichem Gruß
Christian 

Am 21.10.2016 um 09:08 schrieb christianTF:

**Comment by mschlenstedt** [comment]
Diese Fehlermeldungen kommen weil ich stdout und stderr auf das Logfile 
umbiege. Aber die apt-Datenbank dürfte nicht zerscossen werden.

Ich habe Dein Plugin jetzt auch mal getestet und mein LoxBerry hing 
komplett bei der PHP-Installationsorgie. Wenn man dann abbricht ist die 
APT-Datenbank defekt.

Ich denke das Image ist mittlerweile auch schon recht alt - wird Zeit 
für ein komplettes "apt-get upgrade" und "apt-get dist-upgrade". Das 
plane ich für das LoxBerry 0.3.0-Image.

Es wird vermutlich kein einzelnes Upgrade-Paket von 0.2.x auf 0.3.x 
geben sondern nur die Möglichkeit über ein frisches Image upzugraden, 
damit wir die LoxBerrys wieder auf eine Stand haben. Ist zwar etwas blöd 
für alle, die den LoxBerry produktiv einsetzen, aber irgendetwas ist ja 
immer :-)

**Comment by christianTF** [comment]
Duplikat von #184
