### ISSUE TITLE
Security: X-Frame-Options

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#157]
Ich schlage vor, in die .htaccess  Datei die Zeile 
`Header always append X-Frame-Options SAMEORIGIN` 
aufzunehmen.

**Comment by Woersty** [comment]
Achso - mod_headers muss dazu mit in den Apache rein

```
a2enmod headers
apache2 -k graceful
```

**Comment by Woersty** [comment]
Vielleicht auch gleich noch die anderen mit rein

```
Header append X-FRAME-OPTIONS "SAMEORIGIN"
Header set X-XSS-Protection "1; mode=block"
Header set X-Content-Security-Policy "allow 'self';"
Header set X-Content-Type-Options "nosniff"
```

**Comment by mschlenstedt** [comment]
@Woersty  ist das noch aktuell? Wozu? Risiken?

**Comment by christianTF** [comment]
Keine Antwort ist auch eine Antwort 😘 -> Close
