### ISSUE TITLE
Enhancement: Zeilenumbruch bei vielen Plugins 

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#158]
![screen_many_plugins](https://cloud.githubusercontent.com/assets/20454116/19839387/ed2ca29a-9ee0-11e6-8e3d-aa94d314176c.png)

**Comment by mschlenstedt** [comment]
Ist eigentlich vorgesehen, vermutlich verzählt er sich hier.

**Comment by christianTF** [comment]
Umgesetzt mit https://github.com/mschlenstedt/Loxberry/commit/35319dc243de4a42d971f5e2a29f3e96c830ea87
