### ISSUE TITLE
Spendenlink tot

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#159]
Neu: https://www.krebshilfe.de/spenden-aktiv-werden/

**Comment by Woersty** [comment]
Es gibt keinen Direktlink auf die **Kinder**krebshilfe. Man muss aus einem Dropdown wählen:
Link zum Formular:
https://www.krebshilfe.de/spenden-aktiv-werden/spenden-service/jetzt-spenden/

**Comment by mschlenstedt** [comment]
Für mich zur Erinnerung: wird geändetr auf kinderlaecheln.com

**Comment by Woersty** [comment]
Die haben sich nicht gemeldet. Also nimm irgendwas. Mir jetzt auch egal. Aber Onlinespende sollte schon gehen. Am besten one-click-donate. Ohne viel Trallala. Sonst macht das eh keeeeena.

**Comment by christianTF** [comment]
Ich wäre dafür, dass wir das so handhaben wie das Loxforum:
Spenden gehen an Michael (PayPal), laufende Ausgaben werden damit gedeckt, evt. irgendwelche Projekt-Anschaffungen für LoxBerry getätigt, und der Überschuss z.B. jährlich von Michael an das Projekt seiner Wahl gespendet.

Es ist beispielsweise problematisch, im englischen LoxBerry einen Link auf die deutsche (und deutschsprachige) Krebshilfe zu haben. Da kommt sicher nie was an.
Außerdem freuen sich die Spender mehr, wenn sie wissen, dass wir wissen, dass sie gespendet haben. 

lg, Christian

**Comment by mschlenstedt** [comment]
Das geht leider nicht. Ich habe ein Gewerbe angemeldet - da sind solche "Spenden" an mich kritisch (Finanzamt). Auf jeden Fall will ich da nicht in "Erklärungsnöte" kommen. Ich spende die laufenden Serverkosten für den LoxBerry gerne.

Wie wäre es, wenn wir einfach noch ein paar Institutionen aus Österreich und der Schweiz hinzufügen? Da dürften wir doch einen großen Teil abgedeckt haben, oder?

Ich mag die Idee, dass OpenSource-Projekte als Spende etwas an eine gemeinnützige Organisationen weitergeben.
