### ISSUE TITLE
Hinweis bei Plugin-Deinstallation

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#161]
Bei der Deinstallation sollte ein deutlicher (roter) Hinweis kommen, dass alle Daten des Plugins gelöscht werden,

**Comment by Woersty** [comment]
Ich würde sogar soweit gehen und einen Dialog benutzen - ähnlich dem BLE-Scanner Löschen Dialog,
wo man die Möglichkeit bekommt, das Plugin - oder wenigstens den /config Ordner zu sichern.
Was meinst du?
Beim Deinstallieren einen 3. Button im Dialog für 'Konfiguration sichern' und wenn man klickt kommt ein zip-Download mit den cfg-Dateien, logs usw. 
Ich könnte das mit ins Pluto Plugin einbauen, dass man das dann später mit Pluto zurücksichern könnte?

Sowas schwebt mir vor.
Wollte eh eine LoxBerry-Backup Funktion ins Pluto einbauen wo ich meine Plugin-Daten sichern kann.
(logs/data/config/...)
Ein Logo hab ich schon:
![icon_64](https://cloud.githubusercontent.com/assets/20454116/19958519/37b5a8f4-a1a0-11e6-9c11-945c61bc9440.png)

Gruß

**Comment by christianTF** [comment]
Dass ein Dialog statt nur dem Hinweis kommt, finde ich sehr gut!

Im Basissystem würde ich aber nicht auf Funktionen von Plugins linken. Wenn dort ein Backup angeboten wird, muss das auch immer funktionieren, d.h. das Backup im Basissystem (das wäre sowieso wünschenswert!)
