### ISSUE TITLE
Suhosin

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#162]
Ich würde gern die Suhosin Extension ins Basissystem mit aufnehmen.

https://suhosin.org/stories/index.html

Bitte um Kommentare.
```

/etc/apt/sources.list
deb http://repo.suhosin.org/ debian-jessie main

wget https://sektioneins.de/files/repository.asc
apt-key add repository.asc

apt-get update
apt-get install php5-suhosin-extension

```
Ich habe irgendwo gelesen, dass Probleme auftreten können, 
wenn der Zend Optimizer zusammen mit Suhosin eingesetzt wird. 
Ab Zend Optimizer Version 3.2.1 funktioniert der Einsatz ohne Schwierigkeiten, 
sofern suhosin.stealth = On in der Konfiguration verwendet wird stand da.
Aber ich habe bisher keine Problem feststellen können.
EDIT: Sehe gerade, dass die [opcache] sektion in der /etc/php5/apache2/php.ini gar nicht aktiv ist.

https://suhosin.org/stories/configuration.html#suhosin-stealth

**Comment by mschlenstedt** [comment]
Ich persönlich habe immer irgendwie ein ungutes Gefühl, wenn man keine Standard-Reopistories in das Basis-System einbinden will. Das wird ein Faß ohn Boden...

Braucht man das wirklich (bin kein PHP-Experte)? Gibt's das nicht im Standard-Debian-Repository?

Wenn's unbedingt notwendig ist kann ich es gerne einbinden. Ich hoffe nur nicht, dass es doch irgendwelche komischen Inkompatibilitäten gibt, die wir dann nie finden...

**Comment by Woersty** [comment]
Ich kann es ja als Plugin machen, was meinst du?
Übrigens sollten wir uns mal eine saubere De-Installationsroutine überlegen.
Sowas wie root_uninstall.sh welche mir root-Rechten vom System ausgeführt wird
und die Anpassungen des root_install.sh wieder zurückbaut z.B. Anpassungen in der php.ini

Genau wie das Thema apt-get remove xxx inkl. Check ob von anderen Plugins noch benutzt.
Sonst hat man irgendwann nur Leichen und Reste überall.

**Comment by mschlenstedt** [comment]
Als Plugin wäre mein Favorit, wenn das machbar wäre. Die 
Deinstallationsroutine mit root_install.sh usw. kommt mit Version 2 der 
Pluginschnittstelle (LoxBerry 0.3.0). Kommt aber erst wenn ich das 
Statistikplugin soweit fertig habe das es in Grundzügen läuft.
