### ISSUE TITLE
Plugin-Übersichtsseite

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#164]
In der Tabelle fehlt `<td style='vertical-align:middle'>` ...

Beim Erzeugen der Tabelle ist ein Fehler beim Überspringen der Kommentar-Zeilen (print F....)

**Comment by christianTF** [comment]
@mschlenstedt Betrifft das die Plugin-Übersicht (Startseite), oder die Plugin-Installationsseite?

**Comment by mschlenstedt** [comment]
Ufff, gute Frage... Keine Ahnung (mehr). Könnte sogar sein, dass ich das in 0.2.3 schon gefixt habe. Ich schaue mir das mal an.

**Comment by christianTF** [comment]
Close. index.cgi ist neu, und plugininstall.cgi wird von Michael noch überarbeitet.
