### ISSUE TITLE
GPIO / WiringPI

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#166]
- User loxberry in die Gruppe gpio
- WiringPi in Basissystem

**Comment by christianTF** [comment]
WiringPi sollte optimalerweise optional nachinstallierbar sein, nicht dass es dann Probleme mit irgendwelchen Aufsteckmodulen (ala Enocean Pi, HiFiBerry, LCDs usw.) gibt.
Den "Switch" zum Nachinstallieren sollte dann auch ein Plugin setzen können.

**Comment by mschlenstedt** [comment]
Habe den user loxberry jetzt erst einmal nur in die Gruppe "gpio" aufgenommen. WiringPi muss ein eventuelles Plugin dann selbst installieren/mitbringen.
