### ISSUE TITLE
FTP Port für alle Miniserver editierbar nicht nur für die über CloudDNS

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#167]
siehe https://www.loxforum.com/forum/german/software-konfiguration-programm-und-visualisierung/69912-loxberry-miniserver?p=69926#post69926

**Comment by christianTF** [comment]
LoxBerry::System::get_ftpport muss dabei berücksichtigt werden.

get_ftpport liefert derzeit entweder den CloudDNS-FTP-Port, oder den echten FTP-Port des MS (per REST-Abfrage) zurück.

**Comment by christianTF** [comment]
Die Konstellationen, die hier abgedeckt werden müssten:

1. Lokaler Miniserver --> IP / Port / kein FTP-Port
2. Externer Miniserver über Cloud-DNS --> keine IP / MAC / FTP-Port
3. Externer Miniserver über anderen Kanal --> IP / Port / FTP-Port

Das heißt: 

Darüber hinaus, finde ich, sollte das Formular so umgebaut werden, dass die Verbindung direkt getestet werden kann (Check-Button mittels AJAX-Call), dafür lässt sich auch ohne funktionierender Verbindung speichern (#170).

Es gibt von mir einen kleinen AJAX-Handler, den man dafür erweitern könnte:
https://github.com/mschlenstedt/Loxberry/blob/loxberry-0.3.0-saruman/webfrontend/cgi/system/tools/ajax-config-handler.cgi

**Comment by mschlenstedt** [comment]
Ist das noch relevant? Braucht das aktuell irgendjemand?

**Comment by Woersty** [comment]
Nein. Nicht mal mehr für Miniserverbackup. Kann komplett raus. Dann muss ich es aber evt. auch aus dem Miniserverbackup Code rausnehmen.

**Comment by Woersty** [comment]
Allerdings gehen dann die alten Miniserverbackup Plugins nicht mehr ... Aber dafür gibt es ja Updates.

**Comment by christianTF** [comment]
Weggeben tun wir das bestehende nicht, aber hinzufügen auch nichts.
Alles bleibt wie es war, du brauchst nichts ändern.
