### ISSUE TITLE
Bei Hostname für Miniserver auch - und _ akzeptieren

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#168]
Siehe https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/69912-loxberry-miniserver?p=70078#post70078

**Comment by christianTF** [comment]
Wird jetzt akzeptiert
https://github.com/mschlenstedt/Loxberry/commit/d66c437e0ea047605f3ec2a00a0dd1c4f513aa0b
