### ISSUE TITLE
Ersteinrichtung - Erster Start

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#17]
Du scheinst Deinen LoxBerry das **aller erste mal** zu starten. 

allererste Mal

**Comment by Woersty** [comment]
Würde vielleicht auch Assistenten starten auf den Button schreiben. Nicht Assistent.

**Comment by Woersty** [comment]
"informieren möchtest, ist das "
Auf der Hallo Seite - Komma nach möchtest - oder nicht?

**Comment by Woersty** [comment]
" können schnell " 
schnell lass mal weg - nachher meckern wieder alle wenn es nicht schnell geht...

**Comment by mschlenstedt** [comment]
Fixed.
