### ISSUE TITLE
Timeout erhöhen (Test ob Miniserver erreichbar ist)

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#170]
und überspringbar machen (Installation ohne Miniserver sollte möglich sein)

**Comment by christianTF** [comment]
Timeout ist jetzt 5 Sekunden.
https://github.com/mschlenstedt/Loxberry/commit/d66c437e0ea047605f3ec2a00a0dd1c4f513aa0b

Das Überspringen im Wizzard ist grundsätzlich für alle Seiten eine gute Idee.

**Comment by christianTF** [comment]
Timeout ist ja schon erhöht. 

Überspringen ist im Issue #316
