### ISSUE TITLE
Fehler: Error reading general config! SSID darf kein ! enthalten

### ISSUE THREAD

**Issue by neminor** [mschlenstedt/Loxberry#171]
Beim Konfigurieren des BLE Scanner Plugins ist mir aufgefallen, dass es ein Problem mit SSIDs gibt, die ein "!" enthalten. (z.b. bei Fritzbox werden SSIDs Standardmäßig "Fritz!Box 1234" gesetzt)
Zunächst hatte ich den Fehler im BLE Repository eingestellt, doch es ist wohl generell ein loxberry Config Problem:

https://github.com/Woersty/LoxBerry-Plugin-BLE-Scanner/issues/9

_BLE Scanner Log_
`2017-01-04 20:12:03 Error reading general config! [direct]
[04-Jan-2017 20:25:05 Europe/Berlin] PHP Warning: syntax error, unexpected '!' in ../../../../config/system/general.cfg on line 16
in /opt/loxberry/webfrontend/html/plugins/ble_scanner/index.php on line 136
2017-01-04 20:25:05 Error reading general config! [direct]
2017-01-04 20:31:29 [OK] Scan: 3 Tag(s) found [http://192.168.3.35/admin/index.cgi]`

Ich habe als Workaround die general.cfg angepasst, so dass dort nun SSID="Fritz!Box 7330" (also mit Ausrufezeichen steht) und ein reboot gemacht. Nun funktioniert es fehlerfrei.
M.E. sollte die Loxberry Config das aber automatisch handeln so dass auch die Standard-AVM SSIDs nicht auf ein Fehler laufen.

**Comment by christianTF** [comment]
@neminor 

> Ich habe als Workaround die general.cfg angepasst, so dass dort nun SSID="Fritz!Box 7330" (also mit Ausrufezeichen steht)

Meinst du Anführungszeichen?

Generell ist es grundsätzlich ein Problem von PHP parse_ini_file, das keine Sonderzeichen verträgt. 

Die general.cfg kann aber aus Perl mit Anführungszeichen für die Werte erstellt werden, sollte kein Problem sein.

**Comment by christianTF** [comment]
@Woersty Das ist ein Problem des Plugins mit PHP. Du musst parse_ini_file im RAW-Mode aufrufen, damit du die Strings der general.cfg 1:1 zurück bekommst. 
Sonst versucht parse_ini_file zu interpretieren und schlägt auf.
In der general.cfg werden wir hier vorerst keine Änderung vornehmen.
