### ISSUE TITLE
Zugriffe von localhost ohne Auth

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#172]
`Order allow,deny`
`Allow from localhost`
`Allow from 127.0.0.1`
`Satisfy Any`

**Comment by christianTF** [comment]
Das sollte unbedingt ins Image, weil das die eine Kommunikation unter den Plugins ermöglicht. Ich denke dabei an die Sprachausgabe.
Bei meiner aktuellen Sprachausgabe am Raspberry ist es genauso, dass CalDav, Wunderground, Waze, Loxone jeweils mit URLs abgerufen werden, und in einem zentralen Script generiere ich dann die Strings für die Texte, die wiederum lokal per URL an ein anderes PHP gesendet werden.
