### ISSUE TITLE
Wunsch: Perl Library für Standardsachen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#173]
Sowas wie 

use LoxBerry
use LoxBerry::squeezelite

Nach den paar Plugins fällt mir auf, dass ich für Standardsachen des LoxBerry-Frameworks immer sehr lange brauche (meist 2/3 der Zeit für ein Plugin). Klar, ich muss noch für jeden Funktionsaufruf googlen :-)

Eine LoxBerry Library könnte da vieles vereinfachen.

Ein paar Beispiele bei einem schnellen Blick durch den Code:

Beispiele für Funktionen:
- Das ganze Handling der Pfadvariablen (Pluginname, alle Pluginpfade wie html, cgi, template, data, log per Default als globale Variablen verfügbar

- Fertiges Logging (ohne sich ums Filehandling zu kümmern)

- Miniserver-Daten fertig in einem Array/Hash - 
@miniservers = GetMiniseverList(); 
oder
%myms = GetMiniserver(1);
print "Deine IP: " . $myms{IPADDRESS} ;

- Fertige Funktionen für Loxone HTTP-REST und UDP
sendmsvalue($msnr, 'http', 'LichtWohnzimmer', 1);
$badtemp = getmsvalue($msnr, 'TemperaturBad');

- Logfileviewer einbinden
print LoxBerry::printLogViewer();

Es wäre auch einfacher, was für LoxBerry zu contributen,wenn es abgeschlossene Subs sind.

Dann wär's noch cool, wenn die Plugins bei der Installation ihre eigenen Module-Pfade bekommen.
use LoxBerry::squeezelite
use LoxBerry::stats2lox
...

Weißt du, was ich meine? :-)

lg, Christian

**Comment by mschlenstedt** [comment]
Ich weiß was Du meinst und das finde ich eine richtig gute Idee! Hab' ich nur noch nie gemacht so etwas :-)

Wir sollten das in Angriff nehmen. Habe mir vorgenommen nach dem Statistik-Plugin an der nächsten LoxBerry-Version zu arbeiten (Version 0.3.0). Die Library würde ich vermutlich dann in 0.4.0 sehen.

**Comment by christianTF** [comment]
Ich hab's gestern mal probiert, weil ich für mein LMS-UDP-Gateway immer wieder die gleichen Funktionen in verschiedenen Scripts brauche, und wie bei PHP includen wollte.
Bei Perl ist das sogar viel cooler als bei PHP :-)

Ich hab das mal im squeezelite probiert, finde ich sehr cool.
https://github.com/christianTF/LoxBerry-Plugin-squeezelite/blob/dev/webfrontend/cgi/lib/Basics.pm

Eingebunden mit 
use lib './lib'; (zum Hinzufügen des Lib-Pfades)
use Basics; (zum Einbinden von Basics.pm)

**Comment by christianTF** [comment]
LoxBerry::System und LoxBerry::Web gibt's ja nun.

- In 0.2x muss die Library mit dem Plugin mitgeliefert werden, und der Pfad im Plugin angegeben werden, so wie hier: https://github.com/christianTF/LoxBerry-Plugin-Any/blob/4c9d6a20a71214f862a2bed968824490f1a5af65/webfrontend/cgi/index.cgi#L19

- Ab 0.3x genügt ein use LoxBerry::System; und use LoxBerry::Web im Perl-Code.
