### ISSUE TITLE
LoxBerry 0.2.2 wizard complains about something...

### ISSUE THREAD

**Issue by pmatos** [mschlenstedt/Loxberry#174]
While starting the wizard there's a complaint that:
	
`* Only the following characters are allowed: a-z A-Z 0-9 _- (Maximum length is 64)`

but there's absolutely no information what this refers to.
Check attached screenshot.

**Comment by pmatos** [comment]
![2017-01-27-130540_1175x954_scrot](https://cloud.githubusercontent.com/assets/7911/22370449/c5e202c4-e491-11e6-8df2-d7f75d3c7a11.png)

**Comment by mschlenstedt** [comment]
Yes, indeed not very clear... It refers to the "Name" field - no blanks are allowed.

**Comment by Woersty** [comment]
Micha, ich hatte das schon in einigen Plugins von mir umgebaut, dass er das direkt beim Feld anzeigt.
Vielleicht kannst du ja den Codeschnipsel übernehmen.
Siehe KNXd Plugin z.B.
![knx_screen](https://cloud.githubusercontent.com/assets/20454116/23376189/937e6310-fd2b-11e6-9384-c40fe9222821.png)

Siehe auch https://github.com/Woersty/LoxBerry-Plugin-KNXd/blob/master/templates/de/settings.html#L215

**Comment by christianTF** [comment]
@Woersty Vielleicht hast du mal Zeit, dir das im miniserver.cgi auf LB0.2.3 anzusehen, was man dort einfügen müsste.

Ich habe für LB0.3 heute längere Zeit damit verbracht, die Ausgabe irgendwie zu verbessern, aber Validate tut einfach gar nicht, was ich will...

**Comment by Woersty** [comment]
Momentan habe ich kaum Zeit. Ich versuche mal dran zu denken - irgendwann.

**Comment by christianTF** [comment]
Hat sich erledigt.
Ursache, dass es nicht gegangen ist, war ein `<div class="form-group">` über das ganze Formular. Deswegen ist der Fehler immer ganz unten gestanden.
