### ISSUE TITLE
Wunsch: Miniserver Log Viewer direkt in LB

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#177]
Zum Anschauen des Miniserver Logs
Unterstützung für alle definierten MS

**Comment by Woersty** [comment]
Du beziehst dich auf das `http://miniserver/dev/fsget/log/def.log `?

**Comment by christianTF** [comment]
Ja, genau!

**Comment by Woersty** [comment]
Baue ich bei den MS mit ein. 
Kleinen Knopf bei jedem miniserver.
Kommt mit in den LB Core 😊

**Comment by Woersty** [comment]
Stimmt ja...

**Comment by christianTF** [comment]
Ist schon drin, denk ich. Hab ich in einem Commit von dir gelesen

**Comment by christianTF** [comment]
Yeah!
