### ISSUE TITLE
Wunsch: /opt/loxberry/log in Ramdisk

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#178]
- Als Switch einstellbar im LB-System (nicht Plugin, da zu systemnahe)
- Mounten unmittelbar beim Boot 
- Verschieben des Originalinhalts samt Struktur und Rechten
- Ggf. Zurückkopieren bei Shutdown
- Logrotate anpassen für kleinere Logfiles

(PS @mschlenstedt Ich erfasse das primär auch für mich selbst, soweit ich dir beim LB-Core unter die Arme greifen kann)

**Comment by Woersty** [comment]
Bin dafür!

**Comment by mschlenstedt** [comment]
Ich überlege, ob das wirklich konfigurierbar sein muss oder ob wir log nicht einfach in die RAM Disk schieben und gut ist. Möchte die Konfiguration des LoxBerry nicht zu kompliziert machen.

Was denkt ihr?

**Comment by christianTF** [comment]
"Weg" damit! 
Was wirklich Wichtiges ist nicht drin, oder?

Logrotate muss dann noch weiter heruntergedreht werden - Bei einem schnell geprüften Produktiv-LB ist das Log-Verzeichnis 97 MB groß, davon 96 MB Apache-Logs. 

Ein kleines Problem gibt's aber schon - wenn ein Plugin sein (auch initiales/leeres) Log erwartet. Beim miniserverbackup glaub ich, dass ich da einen Fall hatte, dass es einen Fehler gab, als das Log weg war. Aber das muss man dann einfach im jeweiligen Plugin ausbessern.
log fällt dann als Verzeichnis auch aus dem Plugin-ZIP.

**Comment by mschlenstedt** [comment]
Erledigt.

**Comment by johny-mnemonic** [comment]
@mschlenstedt I am not sure, whether you know about that, but you can close issues automatically, by using [specific](https://help.github.com/articles/closing-issues-using-keywords/) format of commit message. You don't need to do that manually.

**Comment by mschlenstedt** [comment]
@johny-mnemonic Thanks! I haven't know that!
