### ISSUE TITLE
PHP5 Modul kann nicht geladen werden - neues Image nötig

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#18]
● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2)
   Active: failed (Result: exit-code) since Thu 2016-07-14 16:47:25 CEST; 3min 49s ago
  Process: 879 ExecStart=/etc/init.d/apache2 start (code=exited, status=1/FAILURE)

Jul 14 16:47:25 loxberry apache2[879]: Starting web server: apache2 failed!
Jul 14 16:47:25 loxberry apache2[879]: The apache2 configtest failed. ... (warning).
Jul 14 16:47:25 loxberry apache2[879]: Output of config test was:
Jul 14 16:47:25 loxberry apache2[879]: apache2: Syntax error on line 140 of /etc/apache2/apache2.conf: Syntax error on line 1 of /opt/loxberry/system/apache2/mods-enabled/php5.load: Cannot load /usr/lib/apache2/modules/libphp5.so into server: /usr/lib/apache2/modules/libphp5.so: cannot open shared object file: No such file or directory
Jul 14 16:47:25 loxberry apache2[879]: Action 'configtest' failed.
Jul 14 16:47:25 loxberry apache2[879]: The Apache error log may have more information.
Jul 14 16:47:25 loxberry systemd[1]: apache2.service: control process exited, code=exited status=1
Jul 14 16:47:25 loxberry systemd[1]: Failed to start LSB: Apache2 web server.
Jul 14 16:47:25 loxberry systemd[1]: Unit apache2.service entered failed state.

Der Apache startet wie vorhin bereits geschrieben seit deiner PHP5 Implementation nicht mehr,
Entweder baust du die Prüfung / Installation des Moduls mit ein oder erstellst ein neues Image.

**Comment by mschlenstedt** [comment]
Kommt im neuen Image.
