### ISSUE TITLE
REPLACEINSTALLFOLDER etc. automatisch ersetzen bei Installation

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#182]
Siehe https://www.loxforum.com/forum/projektforen/loxberry/entwickler/86723-replaceinstallfolder-in-cron-job-dateien

**Comment by christianTF** [comment]
Damit es einheitlich zu LoxBerry::System wird/bleibt, würde ich diese REPLACE-Variablen anlegen wie die globalen Variablen in LoxBerry::System (http://www.loxwiki.eu:80/x/vAzL)

Beispielsweise:
REPLACELBHOMEDIR
REPLACELBPLUGINDIR
REPLACELBCGIDIR
REPLACELBLOGDIR
usw.

**Comment by mschlenstedt** [comment]
Ich brauche mal Eure Meinung: In welchen Dateien wollen wir das realisieren?

Ich sehe das aktuell so:

- Installationsskripte und das neue Uninstall-Skript: /etc/environment wird eingelesen, Pluginspezifisches als Option dem Skript übergeben. -> Replacement nicht notwendig
- Sämtliche CGI/PHP-Skripte: Können/sollen die LoxBerry-Libs nutzen -> Replacement nicht notwendig

Bleiben noch übrig:

- Config-Dateien
- Cron
- daemon
- sudoers

Habe ich etwas übersehen?

**Comment by christianTF** [comment]
Ich würde es bei den Files einfach drüberziehen. Dann ist die Funktion mal da, ob nun primär oder als Alternative.

Wir müssen noch tiefergehend analysieren, wo die Environments gehen und wo nicht.

Bei den Daemons hatten Sven und ich Schwierigkeiten mit den Environments, obwohl ich im initloxberry schon probiert habe, diese nachzuladen. Mir ist das immer ein Rätsel, wann und wie lange die den Userkontext überleben.

**Comment by mschlenstedt** [comment]
Meiner Meinung nach müsste es funktionieren, wenn wir sie direkt in ~/.bashrc jeweils vom User "loxberry" als auch vom user "root" sourcen:

```bash
if [ -f /etc/environment ]; then
    . /etc/environment
fi
```

Die meisten Sckripte (auch init) dürften "#!/bin/bash" verwenden.

**Comment by mschlenstedt** [comment]
Erledigt
