### ISSUE TITLE
Installskripte für Plugins werden mit sh aufgerufen

### ISSUE THREAD

**Issue by andweber** [mschlenstedt/Loxberry#183]
Es ist entweder ein Bug oder Feature - aber derzeit nicht konsistent bzw. klar dokumentiert:

Die Installskripte der Plugins besitzen einen Shebang und suggieren damit, dass man die ausführende Shell wählen kann. Die Installroutine ruft diese mit der in der Config festgelegten Shell auf. Dort ist:
```
BASH=/bin/sh
```
Auf dem RPi ist /bin/sh wiederum ein Symlink zur Dash. D.h. Installskripte werden mit der Dash ausgeführt unabhängig vom Shebang. Daemon Skripte vom System entsprechend dem Shebang.

Einige Tipps für Entwickler z.B. http://www.loxwiki.eu/pages/viewpage.action?pageId=13307504
benutzen explizit die bash.

Vorschlag 1:
Ein Hinweis in die  Installskripte, dass diese SH-kompatible sein müssen.
Es wäre gut, wenn dann auch Tipps SH-kompatible sind. 

Vorschlag 2:
Tatsächlich die Bash verwenden, d.h. in general.cfg
```
BASH=/bin/bash
```

**Comment by mschlenstedt** [comment]
Ja, da hast Du recht. Ist mir auch schon auf die Füße gefallen, da die Dash sich teilweise anders verhält als die Bash.

Ich würde vorschlagen den Aufruf der Skripte nicht mehr fest über $BASH zu realisieren sondern über den Shebang. Dann kann jeder verwenden was er möchte.

**Comment by mschlenstedt** [comment]
Umgesetzt in Pluginschnittstelle V2.
