### ISSUE TITLE
dpkg --configure -a

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#184]
Während Plugin-Installation zur Reparatur apt-Datenbank.

**Comment by christianTF** [comment]
@mschlenstedt Das wäre noch Plugin-Schnittstelle, richtig? Das einfach vorm apt-get install laufen zu lassen.

**Comment by mschlenstedt** [comment]
Ja, das kommt noch rein. Und auch, dass man direkt dpkg Pakete mit dem Plugin mitliefern kann.
