### ISSUE TITLE
Plugins: daemon oder daemon.sh

### ISSUE THREAD

**Issue by andweber** [mschlenstedt/Loxberry#185]
Eine Kleinigkeit - ich hätte sie direkt korrigiert, habe aber das Sample-Plugin im Quelltext nirgends gefunden?

Im Sample-Plugin unter daemon/daemon steht im Kommentarkopf u.a.

```
# Name this file "daemon.sh" in your plugin-archive. It will be renamed to NAME
# during installation
```

Das ist nicht korrekt. Die Datei muss ihren Namen ohne Endung behalten: ```daemon```. Ansonsten wird sie nicht installiert.

**Comment by mschlenstedt** [comment]
Fixed in https://github.com/mschlenstedt/LoxBerry-Plugin-SamplePlugin-V2/commit/e3f90591dfb4ada94a1867d7b8c7118ae3b36714
