### ISSUE TITLE
loxberry connect to miniserver not working

### ISSUE THREAD

**Issue by jan1379** [mschlenstedt/Loxberry#187]
When I try to connect the miniserver using local network (not dnscloud) I get an error message that I can only use regular characters. I am only using regular characters and I do not know what to do. When I try to find the miniserver with the scan function, I find the router, not the miniserver. What can I do?

**Comment by christianTF** [comment]
@janbultman 
Is your issue solved already?
If not, please give more information about your network, what hardware (Pi?), and if you have form-filled the name property in the wizzard without blanks.

Thanks,
Christian

**Comment by christianTF** [comment]
Closed due to missing feedback.

**Comment by jan1379** [comment]
Christian, I have moved to a temporary house and getting ready to install loxone and loxberry. I still have the same problem. I can't connect to the loxone miniserver in loxberry. If I fill in the user and password, it says I'm using a password with ^^&amp;^^&amp; like characters. However, that is not the case. I do not use spaces or capitals in the user name either.



When I perform the scan to look for the miniserver, it never finishes or finds the miniserver either. I presume it is not going over the dns cloud/ftp? I'm trying to keep the miniserver (and loxberry) in the local lan only and connect through openvpn outside the home (I got that working for loxone).



I'm pretty frustrated because I don't understand how such a simple activity fails.

Jan






---- On Tue, 03 Oct 2017 13:03:38 -0400 Christian Fenzl &lt;notifications@github.com&gt; wrote ----




@janbultman

 Is your issue solved already?

 If not, please give more information about your network, what hardware (Pi?), and if you have form-filled the name property in the wizzard without blanks.


Thanks,

 Christian

**Comment by christianTF** [comment]
Could you try it with another web browser.
Don’t forget to fill in a name at the bottom.

**Comment by jan1379** [comment]
Thanks for the answer. I had a capital in the name and changed that. Now I got in! ---- On Tue, 19 Dec 2017 13:06:53 -0500  Christian Fenzl<notifications@github.com> wrote ----Could you try it with another web browser. Don’t forget to fill in a name at the bottom.  —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
