### ISSUE TITLE
Englisch?

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#19]
@mschlenstedt wann planst du Englisch dazu zu bauen? Vielleicht kann ich dir dabei helfen. Bin zwar kein nativ Englisch sprechender Mensch aber für ein Gerüst, welches die Community dann bemängeln kann sollte es reichen.

**Comment by mschlenstedt** [comment]
Prinzipiell kann das sofort hinzugefügt werden - am Besten gleich im aktiellen Development-Branch. Alle Dateien aus /templates/system/de/ müssen übersetzt werden.

Ich selbst arbeite gerade an der Plugin-Schnittstelle, daher würde bei mir die Übersetzung erst sehr viel später kommen.

**Comment by Woersty** [comment]
Ich schaus mir gleich an.

**Comment by Woersty** [comment]
https://github.com/mschlenstedt/Loxberry/commit/e7e4e4f
https://github.com/mschlenstedt/Loxberry/commit/6cb245f
bzw.
https://github.com/mschlenstedt/Loxberry/pull/26
