### ISSUE TITLE
Fehlermails per BCC an loxberry@loxberry.local

### ISSUE THREAD

**Issue by gbrehmer** [mschlenstedt/Loxberry#190]
Habe jedoch nicht das Loxberry Image verwendet, sondern bin nach der Entwickler Doku gegangen und hab eine vorhandene Raspbian Installation angepasst (0.2.3).
Betrifft z.B. die Mails, die bei Fehlern der Cron Jobs auftreten.
Wisst ihr, wo man den BCC Empfänger entfernen kann? Bekomme vom Mail Provider für jede Mail noch eine Fehlermail, dass der Empfänger ungültig ist.

**Comment by mschlenstedt** [comment]
Mmhhh, habe dazu nichts gefunden. Man kann ganz oben in der crontab ein "MAILTO:" setzen. Das müsste man aber explizit abfragen. Ich schaue mal ob ich das beim mailer irgendwo mit einbauen kann.

**Comment by christianTF** [comment]
Hallo @gbrehmer ,
bitte trag in /etc/crontab ganz oben ein:
`MAILTO=""`
Der explizite, leere Eintrag deaktiviert die Fehlermails,

Ich habe das in die Image-Erstellung für LB0.3 / Crontab aufgenommen.
