### ISSUE TITLE
dhclient sending requests to invalid IP

### ISSUE THREAD

**Issue by johny-mnemonic** [mschlenstedt/Loxberry#191]
My syslog is filled with dhclient requests to weird IP like below:

> May 08 10:52:17 loxberry dhclient[1386]: DHCPREQUEST on wlan0 to 192.168.3.1 port 67
> May 08 10:52:29 loxberry dhclient[1386]: DHCPREQUEST on wlan0 to 192.168.3.1 port 67
> May 08 10:52:43 loxberry dhclient[1386]: DHCPREQUEST on wlan0 to 192.168.3.1 port 67
> May 08 10:52:50 loxberry dhclient[1386]: DHCPREQUEST on wlan0 to 192.168.3.1 port 67
> May 08 10:52:59 loxberry dhclient[1386]: DHCPREQUEST on wlan0 to 192.168.3.1 port 67

As I am not using 192.168.3.0 network on any interface in my house, it bothers me why I see this in the log.
I have checked /var/lib/dhcp/dhclient.wlan0.leases and there are two sections for wlan0 interface, one containing information regarding 192.168.3.0 network and also this suspicious line:
`option domain-name "fritz.box";`

Is this something, that you forgot to wipe before publishing the image? I was unable to find any config for this network in /etc.

**Comment by mschlenstedt** [comment]
Yes, this is from my Home network. Seems like a cached config or so. I will remove it in the next image.

**Comment by johny-mnemonic** [comment]
OK, I thought so :-)
Thanks.

**Comment by mschlenstedt** [comment]
Fixed.
