### ISSUE TITLE
LoxBerry weitestgehend Readonly umbauen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#193]
Viele korrupte Dateisysteme. Möglichst alles nach /var/shm schieben (Ramdisk), nicht nur die LoxBerry Logdateien sondern auch die des eigentlichen Linuxsystems.

Zusätzlich umsetzen: http://andicelabs.com/2014/07/automatic-root-filesystem-repair-boot/

**Comment by christianTF** [comment]
- GUI-Setting: Logs to RAM-Disk (Default)
- --> /loxberry/log 
- --> /var/log
tmpfs /var/log tmpfs defaults,noatime,nosuid,mode=0755,size=100m 0 0

LogRotate anpassen (weniger aufheben)

https://raspberrypi.stackexchange.com/questions/169/how-can-i-extend-the-life-of-my-sd-card

**Comment by mschlenstedt** [comment]
https://kofler.info/raspbian-lite-fuer-den-read-only-betrieb/

**Comment by mschlenstedt** [comment]
Fixed
