### ISSUE TITLE
Automatische Sicherheitsupdates 

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#196]
- Sicherheitsupdates werden regelmäßig automatisch installiert.
- Deaktivierbar im "Upgrade"-->"Updates" Menü

**Comment by mschlenstedt** [comment]
https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/108974-aktualisierung-des-loxberrys

**Comment by christianTF** [comment]
http://www.tim-bormann.de/update-debian-server-durch-cron-apt/

https://help.ubuntu.com/community/AutomaticSecurityUpdates
https://wiki.debian.org/UnattendedUpgrades
https://github.com/mvo5/unattended-upgrades/blob/master/README.md

Verhindern des Shutdowns während der Installation:
systemd-inhibit --why="Doing weekly backup" bash my-backups.sh

**Comment by mschlenstedt** [comment]
Paket ist installiert. Das Config-File habe ich nach /opt/loxberry/system/unattended-upgrades geschoben und aus /etc/apt/apt.conf.d verlinkt.

Was mir noch nicht ganz klar ist: Aus welchen Cronjob wird das Ding gestartet?

**Comment by christianTF** [comment]
Bin nicht am PC, ich glaube der ist in cron.daily.

**Comment by christianTF** [comment]
Konkret geht's so:
In /etc/cron.daily ist apt hinterlegt, wo geprüft wird, ob in APT die Optionen
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
gesetzt sind.
Ist das der Fall, wird unattended-upgrades ausgeführt.

https://wiki.debian.org/UnattendedUpgrades

Ich würde das über /etc/apt/apt.conf.d/02periodic (muss man erzeugen) implementieren.

Soll das File dann im Zuge der Image-Erstellung dann wieder in /opt/loxberry/system/unattended-upgrades verlinkt werden, oder am Originalort erstellt?

**Comment by christianTF** [comment]
Image-Erstellungs-Artikel aktualisiert (7.12 Unattended-Upgrades) 
http://www.loxwiki.eu:80/x/VoU_AQ

Default ist 7 Tage.

Fertig mit http://www.loxwiki.eu:80/x/VoU_AQ

**Comment by johny-mnemonic** [comment]
@christianTF Are you really sure about this option?
"Unattended-Upgrade::Automatic-Reboot-WithUsers "true""
It looks like a pretty nasty and dangerous thing to me. I guess, that's why it is not enabled by default ;-)
In case you think it is good idea, could you at least make it optional?

**Comment by christianTF** [comment]
Hi!
I honestly don’t know what the feature check against.
I have concerns that running daemon scripts will prevent required reboots.
So, I will add another option to disable automatic reboots, but keep it enabled by default.

**Comment by johny-mnemonic** [comment]
Daemons should not run under logged in users.
I didn't check the code, but I would expect it to check for opened interactive user sessions (like local or remote console).
This option should be just a measure to ensure reboot is done even when you forget to close your ssh session. Unless you regularly keep open sessions to Loxberry, this shouldn't be needed.

**Comment by christianTF** [comment]
Closed with merge https://github.com/mschlenstedt/Loxberry/pull/225

**Comment by mschlenstedt** [comment]
Irgendetwas funktioniert da noch nicht: Kapitel 7.13 der Anleitung zur Image-Erstellung. Könnte sein, dass sich auf Stretch da etwas geändert hat.

Zudem scheint apt die symlinks nicht zu mögen:

N: Ignoring '02periodic' in directory '/etc/apt/apt.conf.d/' as it is not a regular file
N: Ignoring '50unattended-upgrades' in directory '/etc/apt/apt.conf.d/' as it is not a regular file

**Comment by christianTF** [comment]
Ok, schau ich mir mit stretch nochmal an!

**Comment by mschlenstedt** [comment]
Warte mal aufs nächste Image. Lade ich vermutlich heute Abend noch hoch.

**Comment by christianTF** [comment]
Sind da vielleicht CRLF's drin?

**Comment by mschlenstedt** [comment]
Teilweise gibt es die Dateien nicht (mehr) oder sie liegen woanders - habe ich mir noch nicht angeschaut.. APT mäkelt sobald es Symlinks anstelle echter Dateien sind.

**Comment by christianTF** [comment]
Fixed.
Ich habe in der Image-Anleitung einen falschen Pfad für die beiden Dateien übernommen. Die Softlinks sind ins Leere gegangen.
