### ISSUE TITLE
Upgrade Skript von LoxBerry 0.2.3 auf 1.0

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#199]

**Comment by christianTF** [comment]
Ein richtiges Upgrade per Script kann es nicht geben (Betriebssystem-Upgrade). 

Mein Vorschlag ist:
Ein Config-Backup-Script (ggf. als Plugin):
- Strippt aus der Config alles, was man am neuen LB auf jeden Fall neu konfigurieren muss 
- Erstellt eine Liste der zuvor installierten Plugins, die irgendwo beim Wiedherherstellungsprozess angezeigt wird. 
- Erstellt eine ZIP-Sicherung von system- und plugin-Config und Data

Im LB0.3/0.4 gibt es dann ein Widget, dass erklärt wie's geht (erst alle Plugins nachinstallieren, dann Rücksichern des ZIP) und das auch macht.

Wer mehr will, soll das LBBackup-Plugin installieren, damit bekommt man alle Files und/oder ein Image des alten LB. 
Was die Leute (mich eingeschlossen) so manuell am LB getrieben haben, da muss sich jeder selbst drum kümmern.

Für einen LB V1.0 kann man sich überlegen, ob man das vereinfacht (Plugins mitsichern), aber grundlegend sollte das Setup per Image sein.

lg, Christian

**Comment by mschlenstedt** [comment]
Wird jetzt nicht anders möglich sein. In Zukunft könnte man eine Art "Plugin-Backup" anbieten, der die installierten Plugins in ein Archiv sichert und auch wieder zurückspielen kann. Voraussetzung ist aber #220, sonst geht es nicht.

Somit wohl erst verfügbar bei der übernächsten Version 0.5/0.6

**Comment by christianTF** [comment]
Das Core-Team macht es, wie angekündigt, nicht. 
Von den Plugin-Entwicklern hat es auch niemand in die Hand genommen.

Ich hab einen Wiki-Artikel erstellt, wie es fürs System geht, und den Rest müssen die Plugin-Entwickler selbst handhaben.

http://www.loxwiki.eu/x/-YSdAQ
