### ISSUE TITLE
Feature Request: Samba support

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#20]
Du hast geschrieben, dass du eine Samba-Unterstützung planst.
Hast du da was fertiges im Sinn oder willst du das selbst entwickeln?

Wofür genau soll das dann genutzt werden?

**Comment by Woersty** [comment]
Als Zwischenlösung:
sudo apt-get install samba samba-common-bin
sudo mv /etc/samba/smb.conf /etc/samba/smb.conf$(date +%F)
grep -ve ^# -ve '^;' -ve ^$ /etc/samba/smb.conf$(date +%F) > /etc/samba/smb.conf #Kommentare löschen

echo "[Backups]" >>/etc/samba/smb.conf
echo "comment = Miniserver Backups" >>/etc/samba/smb.conf
echo "path = /opt/loxberry/webfrontend/html/plugins/miniserverbackup/files/" >>/etc/samba/smb.conf
echo "browseable = yes" >>/etc/samba/smb.conf
echo "read only = no" >>/etc/samba/smb.conf

service smbd restart
service nmbd restart

smbpasswd -a loxberry

**Comment by mschlenstedt** [comment]
Ich plane Samba und FTP mit zu aktivieren und dem User "loxberry" per Samba kompletten Zugriff auf /templates, /config, /data und /log zu geben, per FTP Komplettzugriff. Die Backups werden noch nach /data wandern - da passen sie besser hin.

Wird im nächsten Image aktiviert sein.

**Comment by mschlenstedt** [comment]
Feature added.
