### ISSUE TITLE
Flexiblere Cronjobs

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#203]
Die vorgegebenen Cronjobs sind z.b. fürs Backup zu unflexibel.

Es sollte aus dem Plugincode heraus möglich sein, eigene Crontab-Einträge zu erstellen, die aber trotzdem eindeutig dem Plugin zugeordnet sind.
Ob es (wie bei sudoers) sowas auch für cron gibt, muss ich mir anschauen.

**Comment by mschlenstedt** [comment]
Könnte man realisieren. Man kann per Skript einen Job zur eigenen crontab hinzufügen:
echo "*/8 * * * * /führe/mich/aus/script.sh" | crontab -

Willst Du die Cronjobs zur Laufzeit hinzufügen oder bei der Plugininstallation?

**Comment by christianTF** [comment]
Die Cron-Einträge sollen zur Laufzeit erstellt werden können.

So einfach mit Hineinschreiben in die Crontab ist das aber nicht. 
Damit ich im Plugin sauber "arbeiten" kann, brauche ich im Plugin auch noch die Kontrolle, welche Cronjobs "ich" gerade habe. Und die LoxBerry-Plugin-Deinstallation soll auch (ohne dass das vom Plugin selbst gehandled wird) die Plugin-Croneinträge wieder entfernen.

Ich hab aber gerade das richtige gefunden:
/etc/cron.d
Darin kann man (wie bei den sudoers) mehrere Files anlegen, die alle cron-Jobs enthalten.

Also wäre der Weg:
- Die Setup-Routine von LB legt in cron.d ein File namens "pluginname" an, auf das User loxberry Schreibrechte hat.
- Das Plugin kann darin tun und lassen was es will.
- Die Uninstall-Routine von LB löscht bei Deinstallation das File wieder.

**Comment by mschlenstedt** [comment]
Ich hätte einen Tag verwendet, z. B. den Pluginnamen, um die Einträge zu identifizeren, also z. B.:

echo "*/8 * * * * /führe/mich/aus/script.sh #PLUGINNAME" | crontab -

Aber /etc/cron.d ist wesentlich eleganter. Das wäre dann ein File im Crontab-Format, richtig?

**Comment by christianTF** [comment]
Richtig, crontab-Format mit User

**Comment by christianTF** [comment]
Übernimmst du das Erstellen und das Rechtesetzen in die Plugin-Install-Routine, sowie das Löschen des Files?

Ich mach mir einen Issue zum Schreiben eines Wiki-Artikels, ggf. mach ich dafür auch Funktionen im LB::System.
https://github.com/mschlenstedt/Loxberry/issues/209

**Comment by christianTF** [comment]
http://www.loxwiki.eu:80/x/aAFmAQ

Bei einem Plugin-Update darf das Cron-File nicht gelöscht werden.

**Comment by mschlenstedt** [comment]
Ja, würde ich übernehmen, Kommt in die Plugin-Schnittstelle V2.0.

**Comment by mschlenstedt** [comment]
Blöd ist, dass man in den Files unter /etc/cron.d auch explizit anweisen kann, dass die Befehle als root ausgeführt werden. Das ist schon ein ganz schönes Sicherheitsrisiko...

**Comment by christianTF** [comment]
Genau wie daemon.
Da muss man sich auf den Plugin-Entwickler verlassen, dass er dem Benutzer keine Eingabezeile aufmacht, wo er seinen Befehl hineinschreiben kann?

**Comment by mschlenstedt** [comment]
Erledigt
