### ISSUE TITLE
Feature: Multiple Miniserver Support for Backups

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#21]
Ich würde das gern für Kunden benutzen. 
Schwebt dir da schon was vor?
Ansonsten würde ich das gern entwickeln.
Wäre nur doof wenn zwei Leute daran arbeiten.
Die Design-Frage ist nur, ob man den LoxBerry generell multiserverfähig machen will oder nicht.
Dann wäre der Ansatz komplett anders.
Ich für meinen Teil könnte mit einem LoxBerry pro Miniserver leben - außer für das Backup-Plugin.
Aber im Forum wurde schon erwähnt, dass jemand 4 hat.
Ich glaube aber das ist nicht die Masse und rechtfertigt den Entwicklungsaufwand nicht.
Wenn du das aber willst, sollte man das zuerst einbauen bevor weitere Plugins usw. kommen.

**Comment by Woersty** [comment]
Ich würde in diesem Zusammenhang gern einen MySQL Server auf dem LoxBerry installieren.
Das macht die Verwaltung dann deutlich einfacher.
Lass mal deine Meinung wissen.

**Comment by mschlenstedt** [comment]
MySQL sollten wir mit aufnehmen und auch das root-Passwort dafür gleich beim Installationsassistenten mit vergeben. Auch wenn der RaspPi mit MySQL nicht gerade sehr performant ist (so läuft LoxStats z. B. leider gar nicht...).

Multiple Miniserver: An diesen (vielleicht) Spezialfall hatte ich überhaupt nicht gedacht. Ich denke aber, dass man das doch vorsehen sollte. Viele Installationen kommen ja doch mit einem Miniserver an ihre Grenzen (ca. 3500 Objekte max.). Ich würde das lieber gleich jetzt vorsehen als später, wenn der Loxberry vielleicht mal weit verbreitet ist. Dann müsste nicht nur das Grundsystem sondern auch alle Plugins wieder angepasst werden.

Ich überlege mir etwas dazu.

**Comment by mschlenstedt** [comment]
Feature added.
