### ISSUE TITLE
Wunsch: PHP Library für Standardsachen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#211]
Wie für Perl LoxBerry::System und LoxBerry::Web soll es sowas auch für PHP geben.

**Comment by mschlenstedt** [comment]
Bin sehr dafür! Auch wenn ich es nicht verstehe :-) fällt PHP doch den Meisten sehr viel leichter als Perl. 

Als "Plugin-Webseite" (index.cgi) wird zukünftig auch ein index.html oder index.php möglich sein, sodass sich ein Pluginentwickler vollständig aussuchen kann in was er programmiert.

**Comment by christianTF** [comment]
PHP libs are available and function complete compared to the Perl modules
