### ISSUE TITLE
Apache2 Logs abschalten

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#212]
http://www.s6z.de/cms/index.php/raspberry-pi/51-apache-logs-abschalten

**Comment by christianTF** [comment]
Ich bin gerade dabei, das Logrotate runterzuschrauben, damit's besser in die RAM-Disk passt.
Apache redet wirklich viel....

**Comment by mschlenstedt** [comment]
Ich würde das ganz abschalten. Wer braucht das schon im normalen Betrieb? Pluginentwickler können es sich aj jederzeit wieder einschalten. Oder was denkst Du?

**Comment by christianTF** [comment]
Zum Mitschauen ist das Logging schon gut, und ich hab beim Fehlersuchen auch schon das Apache-Log nachgefragt. Also ganz abschalten würde ich nicht.

Meine Apache access-Logs sind so wahnsinnig riesig und lassen sich auch nicht gut zippen.

**Comment by mschlenstedt** [comment]
Mmhh, ok. Hatte gedacht, dass ich das Logging als Plugin-Entwickler einfach wieder einschalte. Der Rest der Welt braucht es sicher nicht.

Aber wir können es auch "geschrumpft" in die Ramdisc packen. Ich würde allerdings 2 Logs des Systemloxberries auf der SD-Karte belassen: upgrade.txt und die Logs der Plugininstallation.
