### ISSUE TITLE
MiniDLNA ersetzen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#214]
Gibt zahlreiche Probleme (Fernseher gehen automatisch an etc.), und der LoxBerry nutzt es nur um sich in der Windows Netzwerkumgebung "zu zeigen", falls ein unerfahrener User die IP des LoxBerries nicht herausbekommt.

Kann MiniDLNA ersetzt werden durch einen eigenen kleinen Client? http://perlupnp.sourceforge.net/DeviceManager.html

**Comment by svethi** [comment]
Hier habe ich wohl noch nicht reingesehen. Das sieht vielversprechend aus. Das muss ich mir mal ansehen.

**Comment by christianTF** [comment]
Der MiniDLNA könnte deaktiviert werden, indem man einfach die minidlna.conf umbenennt in z.B. minidlna.conf.off.
Wird die conf nicht gefunden, startet das daemon-Script den Dienst nicht. 

Im Webinterface kann mit dem Dateinamen (minidlna.conf oder minidlna.conf.off) auch leicht eine Checkbox aktiviert oder deaktiviert dargestellt werden, und über den ajax-config-handler.cgi die Umbenennung (ggf. kill oder start) durchgeführt.

Beim Umbenennen der Datei muss das in changehostname.pl berücksichtigt werden, dass die Datei so oder so heißen könnte, und die Änderung des Files durch changehostname.cgi auf jeden Fall passieren soll.

**Comment by mschlenstedt** [comment]
"Sauberer" würde ich eine entsprechende Option in general.cfg finden (startminidlna=true|false) und das im DAEMON-Skript auswerten. Der Minidlna wird über ~/system/daemons/system/01-minidlna gestartet.

Aber wie schon geschrieben: Ich "will" eigentlich nur, dass der LoxBerry genau so wie der Miniserver in der Netzwerkumgebung auftaucht. Den Rest vom minidlna braucht es nicht. Daher wäre ein kleiner eigener Client ideal. So schwer kann das nicht sein: Loxone hat es im Miniserver ja auch geschafft :-)

**Comment by svethi** [comment]
Nun zerbrecht Euch mal nicht meinen Kopf ;-) Irgendwie bin nur ich dem Thema zugeordnet. Habt Ihr keine anderen Tätigkeitsfelder 😂😂

**Comment by christianTF** [comment]
🤣

**Comment by mschlenstedt** [comment]
Wir geben halt gerne überall unseren Senf dazu :-)

**Comment by svethi** [comment]
Wie sieht das denn aus? Soll miniDNLA dann ganz raus oder nur deaktiviert werden?
Wenn ganz raus einfach nur aus der packages.txt rausnehmen oder wie gehen wir da vor?
Wie ist das mit Paketen die gebraucht werden für den core? In die packages.txt eintragen oder wie macht Ihr das?

**Comment by christianTF** [comment]
Wenn du ihn durch einen anderen Dienst ersetzt, kommt er ganz raus.

Es gibt eine Config im system/ Ordner, die dann ersetzt werden muss, und die Installationsanleitung entsprechend angepasst. Minidnla ist auch noch im daemon-Ordner.
Die changehostname.sh muss angepasst werden, weil die auch die minidnla Config ändert.

Im What's New Artikel im Wiki Sollte es auch erwähnt werden.

**Comment by mschlenstedt** [comment]
Genau wie @christianTF sagt: Der MiniDLNA kann raus, wenn wir was anderes finden. Die ganze Funktionialität ist sowieso schon soweit es geht per Config deaktiviert. Ich wollte den Loxberry nur in der Netzwerkumgebung von Windows haben - für absolute Anfänger, die nicht einmal die IP-Adresse herausfinden können.

Wenn wir diesen einen Dienst irgendwie mit Perl oder sonstwie hinbekommen, dann kann der restliche UPNP-Kram raus und damit auch MiniDLNA.

Der MiniDLNA ist selbst kompiliert (wegen dem LoxBerry-Icon) und die Binaries liegen unter /opt/loxberry. Damit funktioniert er sowieso nur auf ARM, was auch blöd ist. Andere Platformen hatte ich nicht berücksichtigt. Wenn wir was anderes haben fliegt der sofort raus.

Für andere Pakete, die wir für den Core brauchen: Bitte macht ein kurzes Issue auf und weist mir das zu. Ich berücksichtige das dann beim nächsten Image. Die packages.txt erzeuge ich dann automatisch aus dem fertigen Image heraus.

**Comment by christianTF** [comment]
@svethi ssdpd funktioniert! Cool!
Ich hab bei der <modelNumber> im description.php die LB-Versionsnummer eingefügt.

Ein individuelles Icon bekomme ich unter Windows aber nicht dargestellt. Geht das bei dir?

**Comment by svethi** [comment]
Die LB Version hatte ich doch schon drin. Da muss noch ne Abfrage rein ob friendlyname gesetzt ist oder nicht.
Nein, die Icons nimmt Windows nicht an. Loxone liefert auch Icons die werden ja auch nicht angezeigt.

**Comment by christianTF** [comment]
Dann hattest du das mgwl. noch nicht commited. Auf GitHub stand noch modelNumber 1.
Finde ich voll cool, dass das "einfach so" geht.

**Comment by svethi** [comment]
Ach ja, stimmt. Bei Modell stand noch die 1

**Comment by mschlenstedt** [comment]
Ich müsste es nachher noch einmal testen, aber unter Win10 werden bei den alten LBs die Icons angezeigt. Meinen Dev-Loxberry auf 0.3.1 konnte ich noch nicht testen, werde ich aber heute im laufe des tages mal machen:

![19-12-_2017_08-01-01](https://user-images.githubusercontent.com/16830799/34144787-69e7e0e4-e493-11e7-82f7-d1431451fca1.jpg)

**Comment by svethi** [comment]
Das macht Windows nur bei Multimediageräten. Die Icons stehen zur Verfügung, werden nur nicht genutzt.
Kann das zum Test gern mal auf Multimedia umstellen

**Comment by mschlenstedt** [comment]
Ah, ok. Das icon ist zwar hübsch, aber ich würde das trotzdem nicht dauerhaft auf Multimedia setzen. Das hat ja gerade bei vielen die Probleme bereitet (Samsung-Fernseher, die angingen wenn der LoxBerry bootete usw.).

Ich mach das hier wieder zu.

**Comment by svethi** [comment]
Bei mir wurden gestern unter Win10 noch nicht einmal mehr die Icons vom QNAP angezeigt.
Komisch
