### ISSUE TITLE
Re-Engineering der Templates header, footer, mainmenu_*

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#217]
- Sprachspezifische Templates ersetzen durch --> ein Template und mehrere Sprachfiles
- Die Plugins im Flyout-Menü (links) müssen gerechnet werden (aktuell werden sie irgendwo direkt ins HTML-File geschrieben)

Evt. generell leichte optische Überarbeitung? Die Plugins näher ins Zentrum rücken.

**Comment by christianTF** [comment]
Ok, das geht leider systembedingt nicht mehr, weil sonst alle Plugins gepatched werden müssten - die greifen direkt auf die Header- und Footer-HTMLs zu. Hmm. Das lassen wir dann lieber.

**Comment by mschlenstedt** [comment]
Ich würde das gerne trotzdem in Angriff nehmen und für eine LB-Version Header und Footer parallel pflegen (neu und alt). Zusätzlich ein Hinweis in den alten Header: Das Plugin ist veraltet. Bitte informieren Sie den Entwickler."  

Im LB 0.5 fliegt der alte Header dann raus.

**Comment by christianTF** [comment]
Ich hab gestern nur upgrade auf updates geändert, und war wirklich ewig damit beschäftigt. Deswegen hab ich das Issue aufgemacht. Da ist vieles ineinander verstrickt, da verliert man schnell den Durchblick. Ich hoffe, "Updates" funktioniert noch :-)

**Comment by christianTF** [comment]
Ich würde damit anfangen, die Plugins aus dem Flyout zu werfen. Ich glaube, das wird gar nicht genutzt von dort aus.
Rechnest du die bei der Plugin-Installation in den header?

**Comment by mschlenstedt** [comment]
Ja, die Plugineinträge werden nach jeder Plugininstallation neu aufgebaut und in die Datei geschrieben.

Ehrlich gesagt habe ich persönlich den Flyout noch NIE verwendet... Ich denke wir können das auch einfach rausnehmen.

**Comment by christianTF** [comment]
:-)

**Comment by christianTF** [comment]
Ich hätte einen Vorschlag:
Ich beginne damit, header und footer auf HTML::Template und Multi-Language umzustellen.
Für Kompatibilität der Plugins rendere ich header und footer on-the-fly entweder als Task für die Image-Erstellung, oder als Task beim ersten Starten des LB.

In LoxBerry::Web gibt es schon Header- und Footer-Funktionen, die multilingual arbeiten - die würde ich auch auf HTML::Template umbauen und sollen dann Standard werden.

Die ganzen anderen CGIs kann man dann scheibchenweise nachziehen.

PS: Ist das Repo bei github aktuell (sind deine Änderungen hier commited)?

**Comment by mschlenstedt** [comment]
Vom Verständnis her: Müssten foot.html, head.html, network.html, pageend.html und pagestart.html nicht mach "multi" verschoben werden?

**Comment by christianTF** [comment]
Da es jetzt einen lang-Ordner gibt, wo alle Übersetzungsdateien drin sind, hat es keinen Sinn mehr gemacht, die Templates in einen eigenen Unterordner zu legen, deswegen sind die im Template-Root. 

Ich dachte, das macht die Verzeichnisstruktur übersichtlicher, weil so viele Dateien gibt es ja nicht.

Wenn Widget und Hilfe multilingual ist, gibt es nur noch im Template-Root die Widget-Templates, in help die Hilfe-Templates und in lang alle Sprachdateien.

Nur wenn man die Hilfe nicht als Template, sondern mit sprachspezifischen HTML-Dateien machen möchte, braucht es noch die en/de/... Unterordner (Legacy).

Der Multi-Ordner kommt noch weg, dafür muss ich das Updates.cgi noch umbauen.

**Comment by christianTF** [comment]
Alles erledigt - Close
