### ISSUE TITLE
System-Environment-Variablen für Loxberry und Perl

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#218]
- Standard-System-Variablen für Loxberry-Verzeichnisse (überall verfügbar)
- Pfad für Loxberry Perlmodule 
- Apache-Config mod_env
- Wiki-Artikel

**Comment by christianTF** [comment]
Erledigt:
--> System-Variablen
--> Perl-Pfad
https://github.com/mschlenstedt/Loxberry/pull/216/commits/95da742bb1f93f27a299991aa8bf511f9abfb7a3

**Comment by christianTF** [comment]
Ich schaff es nicht, mit PassEnv LBHOMEDIR in der Apache-Config die Variable an PHP durchzureichen.

Beispiel-PHP:

`<?php
echo "Remote Address: " . getenv('REMOTE_ADDR'). "<br>";
echo "LoxBerry Home:  " . getenv('LBHOMEDIR') . "<br>";
?>
`


Rufe ich das Script direkt an der CLI auf, funktioniert es. Über den Webserver nicht.
Demnach funktioniert entweder die Einstellung in Apache nicht, oder die php.ini für Apache blockiert das.
Nur wenn ich mich in die Datei /etc/apache2/envvars setze, funktioniert es.

**Comment by mschlenstedt** [comment]
Könnte es sein, dass /etc/enviroment erst nach dem Start von Apache geparst wird?

Vielleicht muss man den Umweg über /opt/loxberry/system/apache2/envvars gehen?

**Comment by christianTF** [comment]
Restart vom Apache bringt nichts.
Ich werd das über die envvars machen.

**Comment by christianTF** [comment]
Das setenvironment.sh piped die Variablen jetzt in die envvars.
Im Zuge dessen habe ich ein libs Verzeichnis im LBHOME angelegt, perllib dort hineinverschoben und auch ein phplib angelegt.
Ein zukünftiges LoxBerry_System.php würde jetzt gleich im libs/phplib/ gesucht.

Im 0.3er Image muss man jetzt nochmal setenvironment.sh ausführen, damit alles ergänzt wird.

Fertig implementiert:
https://github.com/mschlenstedt/Loxberry/commit/dfb93a9a87ceb35e0fb80038b06e51cf424bb63c

**Comment by mschlenstedt** [comment]
Muss ich da noch etwas ins Init-Skript einbauen oder wann werden die Variablen jeweils aktualisiert?

**Comment by christianTF** [comment]
In der Image-Erstellen Anleitung ist der Aufruf von setenvironment.sh drin - da werden alle Files entsprechend aktualisiert.
Wenn jemand einen anderen Pfad als /opt/loxberry verwenden will, muss er setenvironment.sh vorher anpassen. Ein nachträgliches Ändern geht nur per Hand.

Eine Aktualisierung der Variablen ist sonst nicht vorgesehen.

**Comment by mschlenstedt** [comment]
Ok, alles klar.
