### ISSUE TITLE
Backup Log View ohne Backup vorher - Text fehlerhaft + Zurück ohne Funktion

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#22]
" Eventuell wu**rd en**och"

 Eventuell wurde noch 

Und der Zurück-Button geht nicht.

Und bei der Fehlermeldung bei mehr als 200 Dateien ist auch noch was falsch.
"**BIt**te" kleines i
"200 eingebe**n.i D**iese Anzahl" i weg

Im aktuellen Branch schon gelöst habe ich gesehen. (500 max)
Aber das es generell nicht mehr geht, bleibt.

Gruß

**Comment by Woersty** [comment]
Das Logfile kann auch nach dem Starten des Backups nicht aufgerufen werden.
Edit: Bei mir ist der Pfad zum backuplog.log gar nicht da?!
Habe den Pfad dann manuell angelegt. Könnte man ja ggf. noch abfangen und ggf. automatisch anlegen.

**Comment by mschlenstedt** [comment]
Zurückbutton: Ist ohne Funktion, da Logfile mit target="_blank" aufgerufen wird. Möchte hier trotzdem das Standardtemplate für Errors verwenden und nicht noch ein extra Template erfinden. Ist vielleicht unschön, für mich aber akzeptabel da es nur auftritt wenn wirklich noch gar kein Backup gelaufen ist. Man könnte letztendlich auch einfach ein leeres Logfile mitliefern... Ist vielleicht sogar noch die elegantere Lösung.

Logfile: Bei mir wird es angelegt, sobald das erste Backup getsartet wurde. Auch läuft das backup einwandfrei durch. Hast Du du die Skripte aus dem aktuelle Dev-Branch verwendet? Ich habe da heute noch etwas gefixt.

**Comment by Woersty** [comment]
Liefere ein leeres Logfile aus bzw. schreib doch während des Setups des Miniservers einfach eine Zeile rein. Das wäre doch ausreichend.

**Comment by mschlenstedt** [comment]
Fixed.
