### ISSUE TITLE
Plugins.loxberry.de

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#224]
Möglichkeit, dass man im Plugin-Eintrag sowas wie ein Archiv anlegt, oder eine alte und neue Version ablegen kann.

Z.B. miniserverbackup ab LB 0.3, und die alte Version ab LB 0.23

**Comment by mschlenstedt** [comment]
Ich fürchte das wird mit dem aktuellen System nicht funktionieren. Das ist ein Downloadmanager-Plugin für WordPress und das Anpassen der Templates ist schon jetzt ein Horror :-) 

Vielleicht haben wir ja irgendwann mal einen Webmaster, der sich darum intensiver kümmern kann. Für jetzt bleibt nur ein zweites Plugin anzulegen a la „Miniserverbackup Classic“ ;-)

**Comment by mschlenstedt** [comment]
Ach, jetzt beim Lesen verstehe ich erst, was du meinst :-) Sorry. Ich nehme es mit in die ToDo Liste auf.

Wobei ich es recht kompliziert finde. Ich würde eher eine Versionsabfrage des LoxBerry implementieren und die Installation des Plugins verweigern wenn der LoxBerry zu alt ist. Dann können sich die Leute eventuell die alte Version herunterladen. Oder?

**Comment by mschlenstedt** [comment]
Oder meinst du doch das Plugin Archiv auf LoxBerry.de?

Uff, ich glaube ich gehe schlafen ;-)

**Comment by christianTF** [comment]
ich hatte schon die Webseite gemeint.
Egal, notfalls kann man das alte Plugin ins Wiki legen.
