### ISSUE TITLE
PHP-Modul - CloudDNS nicht implementiert

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#229]
Im PHP-Modul ist das CloudDNS-Auslesen nicht implementiert, weil ich nicht weiß, wie CloudDNS funktioniert.

In Perl wird diese Commandline aufgerufen:
`curl -I http://$clouddnsaddress/CloudURL --connect-timeout 5 -m 5 2>/dev/null | grep Location | awk -F/ '{print \$3}'`;

Ich weiß nicht, was dieser Output zurückgibt, und deswegen auch nicht, wie ich es verarbeiten muss.
Wenn jemand der in Verwendung von CloudDNS ist, einen Beispiel-Output des curl-Aufrufs posten könnte, oder der gesamten Commandline.

https://github.com/mschlenstedt/Loxberry/blob/b1891b641c7737013b7714734b4fdfdcdc8fe9c1/libs/phplib/loxberry_system.php#L215

Danke,
Christian

**Comment by gahujipo** [comment]
Kannst du mir den Inhalt der Variable $clouddnsaddress sagen, dann kann ich den cURL Aufruf testen und den Inhalt geben.

**Comment by christianTF** [comment]
Das ist dns.loxonecloud.com
Die CloudURL ist die MAC-Adresse ohne Trennzeichen, die man im Miniserver-Setup einstellt.

Demnach müsste es so aussehen:
`curl -I http://dns.loxonecloud.com/AABBCCDDEEFF --connect-timeout 5 -m 5 2>/dev/null | grep Location | awk -F/ '{print \$3}';`

**Comment by gahujipo** [comment]
```bash
curl -I http://dns.loxonecloud.com/AABBCCDDEEFF --connect-timeout 5 -m 5 2>/dev/null | grep Location
```
gibt 
```bash
Location: http://AABBCCDDEEFF.dns.loxonecloud.com
``` 
aus. 
Wenn das aber dann gepiped wird nach | awk -F/ '{print \$3}'; gibt mir das einen Fehler 
awk: {print \\$3}
awk:        ^ backslash not last character on line

Wenn ich das mit doppelten Anfürhungszeichen schreibe, dann funktioniert ist. Nachdem -F/ den Slash als Field-Separator definiert wird print \$3 das dritte Feld ausgeben sollen. D.h. EEE000780086.dns.loxonecloud.com

**Comment by christianTF** [comment]
Super!
Kann sein, dass ich beim Copy/Paste was "verloren" hab, aber mit dem Output komme ich zurecht.
Ich glaub, dass das möglicherweise im Perl-Modul auch kaputt ist.

Danke!
lg, Christian
