### ISSUE TITLE
Hilfe bei Plugins

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#23]
Wenn ich das Miniserver Backup Plugin benutze und auf die Hilfe gehe, wird die vom Neustart-Menü angezeigt.
Außerdem heißt der Button dort Ausschalten der Hilfetext bezieht sieh aber auf Herunterfahren.

**Comment by Woersty** [comment]
Klickt man auf ausführliche Hilfe kommt ein 404 => http://loxberry/help/de/power.html
(Gilt für alle Punkte soweit ich das sehe)

**Comment by mschlenstedt** [comment]
Danke, kommt noch daher, dass ich ursrpünglich eine lokale Hilfe mitliefern wollte, die ausführliche Hilfe jetzt aber im LoxWiki mit aufgenommen wird.

Werde ich noch fixen.

**Comment by mschlenstedt** [comment]
Fixed.
