### ISSUE TITLE
Notification Center

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#232]
Systemweite Notifier-Komponente

- Notification als Message am UI
- Notification als E-Mail
- Notification per VTI und/oder VI
- Severity levels Low, Medium, High
- Template zum Einbinden in ein Plugin zum Anzeigen der aktuellen Plugin-Notifications
- Benutzereinstellung für Notifications um UI (welche Notification bei welcher Severity)
- Einfacher Call per Perl, PHP und Bash triggert Notification

Web-Darstellung z.B. 
http://www.cssflow.com/snippets/menu-with-notification-badges/demo

**Comment by mschlenstedt** [comment]
Notify is implemented.
