### ISSUE TITLE
plugindatabase.dat: 8. Spalte Loglevel

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#234]
Für die zentrale Logging-Komponente benötige ich in der plugindatabase.dat eine 8. Spalte mit dem Loglevel.

Die möglichen Loglevels entsprechend syslog- und systemd-Priority-Liste:
          0    Emergency
          1    Alert
          2    Critical
          3    Error
          4    Warning
          5    Notice
          6    Informational
          7    Debug

Für die Plugin-Installation ist es egal - die Logging-Komponente wird NULL = Loglevel 3 annehmen.

Todo:
- @mschlenstedt Jede Bearbeitung der Plugindatabase.dat muss grundsätzlich die neue Spalte berücksichtigen (beibehalten) 
- @christianTF Plugins-UI mit der Möglichkeit, den Loglevel pro Plugin zu setzen.

**Comment by mschlenstedt** [comment]
Achtung! plugindatabse.dat hat jetzt insgesamt 11 Spalten! Bitte berücksichtigen.

**Comment by mschlenstedt** [comment]
```bash
#
# Database for installed Plugins
#
#  0: MD5 Checksum of AUTHORNAME,AUTHOREMAIL,NAME,FOLDER (without commas!) from plugin.cfg
#  1: AUTHOR NAME
#  2: AUTHOR EMAIL
#  3: VERSION
#  4: NAME
#  5: FOLDER
#  6: TITLE
#  7: INTERFACE
#  8: AUTOMATIC UPDATES (0/1)
#  9: RELEASECFG
# 10: PRERELEASECFG
# 11: LOGLEVEL (0-7)
#
# Delimiter: | (Pipe)
#
```

**Comment by christianTF** [comment]
Hallo @mschlenstedt ,

kannst du kurz die Spalten 9 und 10 erklären?
(PS: Am besten direkt, kurz und gut im Wiki-Artikel http://www.loxwiki.eu/display/LOXBERRY/plugindatabase.dat)

lg, Christian

PS: Mir fällt auf: Man kann das Logging nicht ausschalten ;-)
Ich glaube, das ist aber egal, oder was meinst du? Wenn jemand auf 0...Emergency stellt, sollte ein Plugin  das eh nur dann loggen, wenn der Raspberry in Flammen steht... :-)

**Comment by mschlenstedt** [comment]
@christianTF  In den Spalten steht die URL, unter der das Release- und Prerelease-CFG-File zu finden ist. Die werden im plugin.cfg eingetragen.

Ein Cronjob holt sich eine oder beide Dateien (je nachdem ob nur Releases oder Prereleases), vergleicht die Versionsnummer und holt dann von der URL aus den beiden Files das Downlaodarchiv.

So hatten es wir meiner Meinung nach hier diskutiert: https://github.com/mschlenstedt/Loxberry/issues/235

**Comment by christianTF** [comment]
Weißt eh wie das ist - aus den Augen, aus dem Sinn! ;-)
Kann mich jetzt auch wieder erinnern!

**Comment by mschlenstedt** [comment]
Das geht mir auch immer so :-)
