### ISSUE TITLE
Eigenes Raspbian-Image erstellen?

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#236]
Und LoxBerry-spezifische Sachen gleich zum Zeitpunkt der Erstellung mit einbauen?

https://github.com/RPi-Distro/Pi-gen

**Comment by christianTF** [comment]
Habs zweimal gelesen und nicht verstanden, worum's bei pi-gen genau geht :-)

**Comment by mschlenstedt** [comment]
Mit pi-gen werden die Raspbian Images gebaut. Man könnte die Skripte so anpassen, dass gleich die LoxBerry spezifischen Dinge eingebaut werden. Das würde das Imagebauen erheblich vereinfachen und beschleunigen. Wäre aber auch ein großer Aufwand im Vorfeld. Mal schauen...

**Comment by mschlenstedt** [comment]
Mit setenvironment und resetpermissions nicht mehr nötig.
