### ISSUE TITLE
jQuery Seitenstruktur ist "beschädigt"

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#237]
Wenn ich das richtig analysiert habe, dürfte die jQuery Seitenstruktur im Header/Plugin/Footer-Konstrukt fehlerhaft sein, bzw. lässt sie sich nicht für AJAX Overlays nutzen.

http://demos.jquerymobile.com/1.0a4.1/docs/pages/docs-pages.html

Ich habe es nicht geschafft, mit bestehendem header.html, network.html und footer.html ein Overlay (Popup) zu öffnen. 

Ich glaube, es fehlt die data-role="content" und die Verschachtelung der Div's passt nicht ganz.

Für LB0.4 oder so realistisch, kommt drauf an.

**Comment by mschlenstedt** [comment]
JQueryMobile zickt gerne mal rum - da habe ich schon Nächste vor verbracht :-( Oft hat es geholfen auf die neueste Version zu gehen.

**Comment by christianTF** [comment]
Geht mir genauso!

**Comment by mschlenstedt** [comment]
Irgendwie ist das Design komplett zerschossen :-( Sowohl das "Error Loading" Overlay passt nicht mehr als auch die Menüs Links/Rechts sehen irgendwie oben kaputt aus...

**Comment by christianTF** [comment]
Das war bestimmt ich. Ist wohl browserabhängig :-(
Ich habe einen CSS-Tag verwendet, der die Boxen auf volle Seite erweitert. Muss ich mal schauen, das beim Fehlerdialog zu überschreiben.
Links/Rechts ist mir nix aufgefallen.

**Comment by christianTF** [comment]
Schaut das bei dir nicht so aus?

Das ist Chrome 62 / Win10

![lb030_links](https://user-images.githubusercontent.com/14220265/32752314-07bfccd2-c8c9-11e7-86d0-5325aad90df7.JPG)
![lb030_rechts](https://user-images.githubusercontent.com/14220265/32752315-07defada-c8c9-11e7-804e-77cc79ddc8ef.JPG)

**Comment by mschlenstedt** [comment]
Doch - ich dachte, das wäre nicht so geplant gewesen ;-) Das Help-Menü auf der rechten Seite sah so komisch/ungewollt aus ;-)

Der CSS-Tag erklärt aber den Fehler beim Error-Loading-Overlay, das wird bis ganz unten an den Seitenrand gezogen.

Ich denke wenn man rechts das Help-Menü noch etwas breiter zieht mit einem kleinen inneren Rand, dann passt es auch :-)

**Comment by christianTF** [comment]
Müsste man probieren, ob man die Footer-Zeile auch auf die Panels anwenden kann, damit der grüne Balken durchgeht. Gleiches auch oben. Dann schaut es „förmiger“ aus. Die Hilfe kann durchaus etwas breiter werden.
Ich habe geschaut, ob man die Icons (Menü, Home) größer machen kann (am Tablet/Mobile schwer zu erwischen), das geht aber nur mit eigenen Symbolen (es gibt kein Size-Tag).

Eines möchte ich einbauen: Einen Page-Selector oben so wie hier, den das Plugin selbst aktivieren und befüllen kann: http://www.loxwiki.eu/download/attachments/10911995/squeezelite0_4_pic1.JPG?version=1&modificationDate=1487876845000&api=v2

Nur eben ganz oben unter dem Header, und nur „on-demand“.

**Comment by christianTF** [comment]
Diesbezüglich würde ich im Zuge des Template-Konzeptes noch was ändern:

In "jQuery-Sprache" wird derzeit im header.html alles bis zur eigentlichen Inhalts-Box ausgegeben. Im Footer wird das wieder abgeschlossen.
Damit nimmt man sich aber die Möglichkeit, mit den Pages von jquery zu arbeiten.

Deswegen hätte ich die Idee, dass man den Aufbau der Seite aus LoxBerry::Web aufteilt auf mehrere Templates.
Als Beispiel würde das im Code dann so aussehen:

LoxBerry::Web::get_html_head();
LoxBerry::Web::get_page_start();
LoxBerry::Web::get_page_end();
LoxBerry::Web::get_html_foot();

- In get_html_head kommt der ganze head mit den eingebundenen JScripts.
- In get_page_start kommt der Start-Tag der jQuery Page mit der header-Zeile und Navigation.
- Dann macht seinen Content.
- Mit get_page_end schließt man die Page ab.
- Nun könnte man wieder eine neue Page beginnen und beenden, sooft man will.
- Am Schluss kommt get_html_foot um das HTML abzuschließen.

Diese Funktionen könnte man auch für PHP wrappen, sodass die nicht nur in LoxBerry::Web verfügbar sind, sondern auch in PHP.

**Comment by mschlenstedt** [comment]
Finde ich eine gute Idee. Mein Vorschlag wäre den alten Header und footer so zu belassen wie er ist, damit alte Plugins weiterhin funktionieren. Die neue Funktion über die libs würde ich dann auch mit neuen Templates realisieren, damit wir das strikt voneinander getrennt haben.

**Comment by christianTF** [comment]
Die Seitenstruktur passt. Warum ich keinen Dialog erzeugen konnte, weiß ich nicht, aber ist erstmal egal.

Ich schließe den Issue - für die Errorbox habe ich einen neuen Issue gemacht. #252 
Wenn wir das absolut nicht lösen können, dann überarbeite ich das CSS nochmal.
