### ISSUE TITLE
Loxberry Usage Counter

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#240]
Wäre es denkbar, dass wir einen Usage-Counter für LoxBerry einbauen?

Gedacht hätte ich das so:

- Funktion im UI abschaltbar
- Bei der Installation wird eine zufällige ID generiert und irgendwo gespeichert.
- Per cron wird täglich ID und LB-Version an https://loxberry.de gepostet.
- Statistik auf der Website

Oder ist das zu viel?

Mich würde interessieren, wie viele LBs es da draußen gibt, für die wir entwickeln.

LG, Christian

**Comment by mschlenstedt** [comment]
Ehrlich gesagt mag ich solche offensichtlichen Trackings nicht. Ich kriege auch Pickel dabei, dass die Updateanfrage meines Miniservers die MAC mit an Loxone schickt.

Trotzdem würde mich das auch interessieren. Wir hatten ja mal überlegt, dass die LoxBerry Libraries automatisch über den Webserver upgedatet werden können. Wie wäre es, wenn wir diese Updateanfragen in eine Statistik packen?

**Comment by Woersty** [comment]
Bin nicht abgeneigt. Klingt interessant.
Wir entwickeln das doch für uns, Christian.
Die anderen sind nur Nutznießer 😁

**Comment by christianTF** [comment]
Ich mag offensichtliche Trackings, die ich ausschalten kann. Wenn mich eine Software fragt, dann lass ich sie tracken. Wenn ich aber nur irgendwo im letzten Untermenü mit einer Wischiwaschi-Angabe über den Inhalt abschalten kann, oder gar nicht (Windows 10), dann mag ich auch kein Tracking.

Über die Update-Funktion zu machen, weiß ich nicht, weil die erst mal gebaut werden muss.
Bei einem einfachen UID-Tracker hingegen ist nur die Serverseite zu bauen. HTTPS wäre auf loxberry.de schon da, und wenn nur eine zufällig generierte ID und die Version übermittelt wird, ist das auch sehr anonym. 

geht PHP oder Perl auf loxberry.de?

**Comment by mschlenstedt** [comment]
Einverstanden :-) Auf loxberry.de geht alles.

**Comment by mschlenstedt** [comment]
Hallo @christianTF 

ich baue gerade mal ein Skript, welches die ID erzeugt und übermittelt. Dabei wollte ich gleich Deine neuen Libraries verwenden. 

Mit use LoxBerry::System habe ich aber noch nicht alle Variablen, die setenvironment.sh erzeugt, oder? Konkret fehlt mir LBSCONFIG.

Andererseits könnte man vielleicht auch LoxBerry::System wieder entschlacken, denn ich bekomme die Variablen in Perl auch über $ENV{LBSCONFIG}, was auch ziemlich einfach ist finde ich.

**Comment by mschlenstedt** [comment]
Ah, die Variablen scheint es doch schon zu geben - da war nur die Doku veraltet :-)

**Comment by christianTF** [comment]
#238 
Ich habe noch keine PassEnv's in die Config eingebaut. 
Ohne die PassEnv's scheinen die Umgebungsvariablen in Perl nicht anzukommen.
Vielleicht ist das mit Stretch schon anders.

**Comment by mschlenstedt** [comment]
Nee, geht auch unter Stretch nicht.

**Comment by christianTF** [comment]
Ich probier mal die Serverseite. PHP und MySQL ist ok?
Daten per POST?

**Comment by mschlenstedt** [comment]
Ja PHP und MySQL ist OK. Ich dachte wir sammeln Wochenweise alle IDs und erzeugen dann eine RRD mit den aktiven LoxBerrys/Woche?

Ich sende aktuell:

$curlbin -f -k -s -S https://stats.loxberry.de/cgi-bin/get.cgi?id=$lbid&timestamp=$timestamp

$lbid ist 128 Zeichen lang (A-Za-z0-9)
$timestamp ist Epoche.

URL usw. passen wir dann an wenn Du PHP nutzt.

**Comment by christianTF** [comment]
https://gist.github.com/christianTF/189fc0d4ce256e66a60efbe92cd974dd

Die Versionsnummer fehlt von dir noch.
Timestamp braucht man nicht, weil den generiert direkt das INSERT. Ist auch sicherer.

Getestet am LB mit mysql.

**Comment by christianTF** [comment]
Funktioniert!

Das müsste noch in den Wizzard (dort Default ein) und in die Widgets, aber hab keinen Platz gefunden dafür.
Zu den Updates dazu?

**Comment by mschlenstedt** [comment]
Hab' ich auch schon überlegt. Ich würde es auch in die Updates packen. Den Wizard würde ich erst ganz zum Schluss aktualisieren wenn alle Features drin sind und wir das Template System überarbeitet haben.

Ich werde noch eine zufällige Verzögerung im Cronjob einbauen, sodass nicht alle LoxBerries zur gleichen Zeit an den Webserver melden.

**Comment by christianTF** [comment]
Grafik auf der Webseite fehlt noch, alles andere dürfte funktionieren.
