### ISSUE TITLE
Translation Web UI

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#242]
Web UI to select source Language File and create destination language file with editor for phrases.
Should work for system and plugin phrases.

Language files currently are in INI file style (TAG=Phrase) and can but need not to have sections (both types needs to be possible).

**Comment by johny-mnemonic** [comment]
Sounds like a nice idea to spread Loxberry faster to non-german speaking people.
Are there any plans to switch whole development/wiki to English, to bring more people in?
Following the project in German is sometimes really tough, as google translator is notoriously bad while translating your beautiful compound words into English, let alone other languages like mine ;-)

**Comment by christianTF** [comment]
We would create an English version of LoxBerry Wiki if someone (else) would do the translation.

My commits are in English, so you can follow up what’s happening.

I, of course, would have a problem to write the Template Guide and Module documentation for LB0.3 I’m English (but not in German anymore).

@mschlenstedt What’s your opinion?

**Comment by christianTF** [comment]
I would NOT have an issue. Sorry auto-correction ;-)

**Comment by johny-mnemonic** [comment]
@christianTF Nasty auto-correction :-)
I guess starting with creating new things in English would be the best least-effort way to move on, but who am I to tell you what to do with your project.
I am really grateful that you are working on this and having some basic German knowledge (few years in elementary school), I can mostly understand everything with the help of google translate.
This was more in a way, that having the project completely in English usually brings more people in, as you open it for much larger public.
