### ISSUE TITLE
LB031: ARRAY() in Formularen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#244]
Anmerkung: Ich hab noch nichts gespeichert und den Setup-Wizzard nicht gemacht.

![image](https://user-images.githubusercontent.com/14220265/32811687-60778508-c9a1-11e7-9ce4-5b0c278c1e50.png)
-------------
![image](https://user-images.githubusercontent.com/14220265/32811717-8402bd12-c9a1-11e7-85d3-22f8942d035b.png)
-------------
![image](https://user-images.githubusercontent.com/14220265/32811734-9b8cbc76-c9a1-11e7-86c0-39509165c81d.png)

In der General.cfg stehen im [NETWORK] Bereich tatsächlich diese Werte drin.

[general.zip](https://github.com/mschlenstedt/Loxberry/files/1472968/general.zip)

**Comment by mschlenstedt** [comment]
Das habe ich bereits gefixt. Ich scheine es nicht mit gepusht zu haben. Alle Werte müssen in Quotes gesetzt werden, dann geht es. Eine leere Angabe dann als "".

Müssen wir sowieso überall fixen wegen der Sonderzeichen-Thematik.

**Comment by christianTF** [comment]
Das ist Mist, weil dann müssen einige Plugins nachziehen :-(

**Comment by christianTF** [comment]
Ein anderer Fix wäre:

$mcfg               = new Config::Simple(filename =>"$home/config/system/mail.cfg", syntax=>'ini');
($email)              = $mcfg->param("SMTP.EMAIL");
($smtpserver)         = $mcfg->param("SMTP.SMTPSERVER");
($smtpport)           = $mcfg->param("SMTP.PORT");
($smtpuser)           = $mcfg->param("SMTP.SMTPUSER");
($smtppass)           = $mcfg->param("SMTP.SMTPPASS");

Also alle Variablenzuweisungen in Klammer.

Das ist richtig Mist.
Das betrifft eine ganze Latte Plugins, und wenn Quotes drin sind, dann auch deren Bash-Scripts, die die eigene Config lesen.

Hast du eine Idee, warum das jetzt anders ist? Versteh nicht, wie sich das in einer Sprache in der gleichen Version ändern kann.

**Comment by christianTF** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=593043

Da müsste es irgendwo einen Fix geben - ich bin den Bugreport noch nicht ganz durch, aber da tauschen wir vorher Config::Simple gegen eine andere gepatchte Version aus, als alles umzubauen.

**Comment by christianTF** [comment]
Ich habs gefunden! :relaxed:

In der Anleitung installierst du Config::Simple aus cpan UND über packages.txt das libconfig-simple-perl.

Das Debian-Paket hat den Fix, aber die CPAN-Version wird vorher genommen.

rm /usr/share/perl5/Config/Simple.pm
apt-get purge libconfig-simple-perl
apt-get install libconfig-simple-perl

Hab die Anleitung aktualisiert.
Beim nächsten Image müsste es passen. Die Anführungszeichen-Sache kann man reverten.

**Comment by mschlenstedt** [comment]
Cool!

Eigentlich hätte der Fehler dann auch schon im alten Image 0.2.3 auftauchen müssen. Hat sich aber vielleicht auch mit Wechsel auf Stretch geändert...

Cool, dass du das gefunden hast. Die Variablenzuweisung in Klammern sollten wir uns trotzdem angewöhnen.

**Comment by mschlenstedt** [comment]
Ich habe den Fix jetzt bei mir eingespielt und rebootet, kriege aber trotzdem diese ARAY() in den Formularen.

**Comment by christianTF** [comment]
Deinstallier (purge) nochmal das Deb-Lib.
Such Dann mal alles mit Simple.pm oder Config auf der SD ab. Vielleicht hab ich mehr gelöscht als nur das eine File.
Apache muss man glaub ich auch neu starten. 
Wenn ARRAY mal im Configfile als String drin steht, dann bleibts natürlich .

**Comment by mschlenstedt** [comment]
Es hat noch folgendes gefehlt:

rm /usr/local/share/perl/5.24.1/Config/Simple.pm

Das dürfte die per cpan installierte Version gewesen sein.

Jetzt klappt's :-)
