### ISSUE TITLE
Plugin-Schnittstelle: sbin / bin?

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#247]
Derzeit gibt es keinen richtigen Ort für Scripts/Executables, die nicht direkt über den Browser aufgerufen können werden sollen.
Beispielsweise Restartscripts für Daemons, oder irgendwelche Aktionen ausführen, die nicht direkt vom Client-Webbrowser erreichbar sein sollen.

Eingebürgert hat sich /opt/loxberry/webfrontend/cgi/plugins/plugin/bin oder irgendwo im cgi-Verzeichnis, weil die Files dort gleich Executable sind. Diese Executables sind aber im Prinzip direkt vom Browser erreichbar, wenn man's weiß.

Deswegen meine Idee, ein sbin- und ggf. ein bin-Verzeichnis im Plugin einzuführen.

Der Content beider Verzeichnisse würde beim Setup +x gesetzt werden.
Dateien im sbin könnte man automatisch ins Plugin-eigene sudoers-File schreiben.

Die Ausführung aus dem Webbrowser ist dann unterbunden, und das CGI könnte ohne Umstände und Rechteprobleme die enthaltenen Scripts ausführen (aus dem sbin mit sudo meinscript.sh).

**Comment by mschlenstedt** [comment]
Finde ich gut. Baue ich mit ein.

**Comment by mschlenstedt** [comment]
Wenn wir das Standard-sudo-Verhalten wieder herstellen: Brauchen wir dann noch ein Plugin-eigenes sudoers file?

**Comment by christianTF** [comment]
Standard-Sudo gibt's nicht, also dann das sudoers File?

**Comment by christianTF** [comment]
@mschlenstedt Wo kommen die Plugin-Verzeichnisse bin und sbin nach der Installation hin?

bin und sbin gibt es jetzt ja schon fürs System, da liegt aber alles direkt drin.
Machst du dort wieder plugin-Unterverzeichnisse (`sbin/plugins/<pluginname>/`)?
Wenn ja, dort zeigen jetzt schon die globalen Plugin-Variablen hin.

**Comment by mschlenstedt** [comment]
Ich habe entsprechende Verzeichnisse ~/sbin/plugins und ~/bin/plugins angelegt.

Konsequenterweise müsste man die System-Skripte dann auch in ein system-Unterverzeichnis packen. Ich befürchte nur, dass wir dann irgendwo einen direkten Aufruf aus ~/sbin übersehen.

oder wollen wir das gerade ziehen?

**Comment by christianTF** [comment]
Hmm - du bist da eindeutig ehrgeiziger bei sowas :-)

https://github.com/mschlenstedt/Loxberry/search?utf8=%E2%9C%93&q=sbin&type=

Ist überschaubar. Bissl aufpassen muss man mit /sbin und /opt/loxberry/sbin.
Die Doku gehört auch geändert.
Von den Sachen, die im ~/sbin liegen, wird sicher nichts von einem Plugin genutzt.

Wäre danach ein schöner Test fürs automatische Update ;-)
Würde man für sowas ein Update-Script brauchen? Jedenfalls einen Reboot.

**Comment by mschlenstedt** [comment]
Coole Suchfunktion - kannte ich noch gar nicht!

Ich habe mich entschieden für Plugins /sbin nicht zu öffnen. Plugins können nur /bin/plugins verwenden und müssen bei Bedarf diese Skripte in ihr eigenes sudoers-file aufnehmen.

/sbin ist ausschließlich für's system.

Funktion umgesetzt in Pluginschnittstelle V2.

**Comment by christianTF** [comment]
`$lbpsbindir` aus Modulen entfernen
