### ISSUE TITLE
LB031 apt: Probleme beim DNS auflösen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#248]
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/libs/libswitch-perl/libswitch-perl_2.17-2_all.deb Temporary failure resolving 'mirrordirector.raspbian.org'

Der DNS ist ein lokaler DNS (bei mir DD-WRT mit dnsmasq), IP und DNS kommt via DHCP.

Beim Ping am Loxberry kommt:

loxberry@loxberry:~$ ping mirrordirector.raspbian.org
PING mirrordirector.raspbian.org (93.93.128.193) 56(84) bytes of data.
64 bytes from 93.93.128.193 (93.93.128.193): icmp_seq=1 ttl=56 time=43.0 ms
From ddwrt.brunnenweg.lan (192.168.0.250): icmp_seq=2 Redirect Host(New nexthop:                                192.168.0.251 (192.168.0.251))
64 bytes from 93.93.128.193 (93.93.128.193): icmp_seq=2 ttl=56 time=39.6 ms
64 bytes from 93.93.128.193 (93.93.128.193): icmp_seq=3 ttl=56 time=39.7 ms

/etc/resolv.conf:
// Generated by resolvconf
domain brunnenweg.lan
nameserver 192.168.0.250

Das Issue ist offenbar weit verbreitet. Bisher waren alle Lösungen, die ich gefunden habe, in die resolv.conf fest die Google-DNS zu schreiben. Das kann nicht die Lösung sein.
Das scheint auch nur bei APT ein Problem zu sein. 

Das Problem hat es mit LB23 in meinem Netz auf dem gleichen Pi mit DHCP nicht gegeben. Irgendwas ist mit APT faul.

**Das Problem mit APT tritt bei mir nicht in der Shell auf, nur bei der Plugin-Installation.** Vielleicht hat das was mit Apache als Service zu tun.

EDIT: Egal was ich in die resolv.conf hineinschreibe, es funktioniert keine DNS-Auflösung bei der Plugin-Installation.

**Comment by christianTF** [comment]
Ich habe jetzt den Fehler gefunden!

die /etc/resolv.conf ist ein Symlink auf /tmp/resolv.conf
Damit funktioniert es nicht.

Wenn ich den Symlink lösche und wieder die "echte" /etc/resolv.conf herstelle, funktioniert sofort alles normal.

Wer macht denn diesen Link ins /tmp/ ?

**Comment by mschlenstedt** [comment]
Das kommt aus dieser Anleitung: https://kofler.info/raspbian-lite-fuer-den-read-only-betrieb/

**Comment by christianTF** [comment]
Mit systemd funktioniert das Verlagern des resolv.conf auf /tmp/ nicht.
Beim apt-Aufruf aus dem Plugin-Install-CGI kann apt keine Nameserver mehr auflösen, egal was in /tmp/resolv.conf drin steht.

Fixed: 
Das Verlinken der resolv.conf aus der Image-Anleitung entfernt.

**Comment by engpire** [comment]
Habe in meiner Loxberry 2.3 Installation ebenfalls ein Problem mit der Namensauflösung. Sowohl bei der Konfiguration per DHCP als auch bei händischer Konfiguration wird in der resolv.conf der DNS auf 127.0.0.1 gesetzt. Händische Änderung auf meinen bzw. Googles DNS lösen das Problem bis zum nächsten Reboot.
/etc/resolv.conf ist eine "echte" Datei, kein link.

**Comment by christianTF** [comment]
@engpire Die resolv.conf wird generiert. Der DNS-Server muss entweder vom DHCP kommen, oder er kommt in die interfaces.
https://wiki.debian.org/NetworkConfiguration#The_resolvconf_program

**Comment by engpire** [comment]
Hallo Christian,
woraus wird sie generiert? In meiner general.cfg steht 

```
[NETWORK]
INTERFACE=eth0
SSID=
DNS=8.8.8.8
TYPE=manual
GATEWAY=172.16.2.1
IPADDRESS=172.16.2.5
MASK=255.255.255.0

```
Inhalt meiner /etc/network/interfaces
```
auto lo
iface lo inet loopback
allow-hotplug eth0
iface eth0 inet static
  address 172.16.2.5
  netmask 255.255.255.0
  gateway 172.16.2.1
  dns-domain loxberry.local
  dns-nameservers 8.8.8.8

```

Ursprünglich hatte ich den Loxberry per DHCP versorgt, dann allerdings wegen DNS Problemen (die nur auf dem Loxberry auftreten) auf manuelle Config gesetzt. Nach jedem Reboot ist der NS in der resolf.conf aufs loopback gesetzt.

**Comment by christianTF** [comment]
Hmm - ich weiß es nicht. Im Code kommt 127.0.0.1 nirgends vor. 
Verwendest du irgendwo DNSMasq oder sowas (lokal am Pi oder woanders)? Eventuell das Wunderground-Plugin von Michael?
Mit dem DNS-Problem von diesem Issue hat es sicher nichts zu tun, das wäre besser im Forum aufgehoben.

**Comment by engpire** [comment]
Ich verwende zwar das Wunderground-Plugin, allerdings erst seit der (temporären) Lösung, vorher war ja auch keine Plugininstallation möglich... 

Die einzige Stelle an der ich die 127.0.0.1 entdecke ist 
`/usr/lib/avahi/avahi-daemon-check-dns.sh`

so wie ich das script lese ist es aber nicht ursächlich für mein Problem. Rumgespielt habe  ich damit sowieso nicht...

**Comment by johny-mnemonic** [comment]
@engpire in case you are using the latest version of Wunderground plugin, it can be the source of your issue, as it installs DNSMasq. This would explain, why your DNS is set for localhost...
