### ISSUE TITLE
Hostname muss mit in den Header

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#249]
Damit man weiß, auf welchem LoxBerry man gerade ist. Ich verliere den Überblick - habe heute meinen 5. in Betrieb genommen :-)

**Comment by christianTF** [comment]
#163 
#194 

Im neuen Template-System ist der friendlyname (frei vergebbarer Name im network Widget) im Header, wenn dieser nicht definiert ist, der Hostname.

Schau mal network_LB30.cgi (habe gerade noch einen Fix commited)

https://github.com/mschlenstedt/Loxberry/commit/b7f3f820c6e23afdd0a25ebd93aa0a24bbc70460


![image](https://user-images.githubusercontent.com/14220265/32979756-9638b736-cc5b-11e7-8ee3-dd83bcf39530.png)

**Comment by christianTF** [comment]
Edit: Den Hostnamen wenn leer habe ich aus Performancegründen wieder herausgenommen, weil das für jeden Request ein zusätzlicher Diskzugriff ist.

**Comment by mschlenstedt** [comment]
Perfekt.
