### ISSUE TITLE
Plugin-Installation: Fehler irgendeiner Komponente am Ende melden

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#250]
Beispiel:

Der APT-Teil meldet:

    E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
    <ERROR> Paket konnte nicht installiert werden

Am Ende der Plugin-Installation kommt:
```
    <INFO> Räume auf und lösche temporäre Dateien
    <OK> Installation erfolgreich abgeschlossen!
```
Die PluginInstall-Routine soll sich einen Fehler irgendeiner der aufgerufenen Komponenten merken und am Ende die Fehler reporten. 

Wer z.B. bei diesem Setup nicht das Log anschaut, würde das beim Plugin-Entwickler melden, dass das Plugin nicht geht.

**Comment by mschlenstedt** [comment]
Ich habe sowieso vor bei solchen Fehlern die Plugininstallation abzubrechen. Dafür wird es in Zukunft auch in den Bash-Skripten verschiedene Exit-Codes geben.

**Comment by mschlenstedt** [comment]
Umgesetzt
