### ISSUE TITLE
Pluginliste in mainmenupanel (header.html)

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#251]
Hi Michael,

kannst du die Routine hinauswerfen, die die Plugins in die header.html's schreibt. 

```
<!-- STARTPLUGINSHERE --> <!-- Never remove this tag! -->
<!-- ENDPLUGINSHERE --> <!-- Never remove this tag! -->
```

Wenn wir die Pluginliste da drin lassen, machen wir irgendwie anders, z.B. HTML::Template

**Comment by christianTF** [comment]
BTW Code hier bei GitHub kann man einleiten und beenden mit jeweils drei Backticks. (hab jetzt doch mal die Hilfe gelesen, weil das so nervig war ;) )

**Comment by mschlenstedt** [comment]
Schmeiss es raus - braucht kein Mensch :-)

**Comment by christianTF** [comment]
Soll'ma das linke Panel generell für was anderes verwenden?

**Comment by mschlenstedt** [comment]
Wäre für mich auch ok. Hast du eine Idee?

**Comment by christianTF** [comment]
Ich hatte mal an irgendwelche Status-Infos gedacht, aber das macht keinen Sinn, wenn das bei jedem Request mitgeladen wird.
Lassen wir‘s mal so mit den System-Einstellungen, so wie es jetzt ist.

**Comment by mschlenstedt** [comment]
```
<!-- STARTPLUGINSHERE --> <!-- Never remove this tag! -->
<!-- ENDPLUGINSHERE --> <!-- Never remove this tag! -->
```

Ist draussen.
