### ISSUE TITLE
Setup-Wizard: Zusammenbauen aus den bestehenden Widgets und HTML::Template

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#253]
Wenn alle System-Widgets auf HTML::Template basieren, kann der Setup-Wizard mit den bestehenden Widgets zusammengebaut werden. Eine extra Pflege des gleichen Codes in zwei CGIs entfällt dann.

Idee: 
- Es gibt ein Steuerscript.
- Mit TMPL_IF werden aus den normalen Widgets Elemente ausgeblendet, die im Wizard nicht benötigt werden.
- Mit TMPL_IF wird für die Submit-Buttons unterschieden, welche dargestellt werden, und wohin die Aktion führt.
- Ich weiß nicht, wie das derzeit mit der Session im Wizard funktioniert und ob man das übernehmen kann.
- Wenn im Wizard nicht sofort in die General.cfg gespeichert werden soll, könnte im Widget-Code unterschieden werden, ob normal oder Wizzard, und eine temporäre General.cfg (und was es noch gibt) erzeugt werden. 
- Im Wizard-Ende könnte man die temporären Configs einfach in die richtigen Configs übertragen, oder ggf. verwerfen.

Evt. ist es auch möglich, eine der Wizard-Libraries für jQuery zu verwenden, allerdings sind die eher dafür ausgelegt, ein einzelnes Form auf mehrere Seiten zu zerlegen.

**Comment by christianTF** [comment]
Reihenfolge und Infos zum Wizard (Assistent):

Alle Seiten können mit Vor/Zurück und Skip durchgegangen werden (außer Admin-Zugang).

1. Startseite
- Großes Logo, Einführung
- Sprachauswahl hab ich überhaupt noch nirgends gesehen --> muss hierher, und noch in ein Widget

2. Admin-Zugang

3. Miniserver

4. Netzwerk

5. Timeserver

6. My Loxberry (Usage statistic ein/aus)

7. Spenden

@mschlenstedt @Woersty @svethi 
Ich frage mich, ob wir nicht Teile davon überhaupt aus dem Wizard streichen können. 
Beispielsweise "Netzwerk", "Timeserver" (ist wegen der Zeitzone blöd), aber evt. sogar "Miniserver"

**Comment by mschlenstedt** [comment]
1. Startseite:

Die Sprachauswahl ist heute im Wizard auch auf der ersten Seite. Aber der restliche Text muss komplett neu.

2. Admin-Zugang

- Setzen des LoxBerry-Passworts
- Setzen der SecurePIN (4-6-stellig) -> fehlt auch noch im Widget

3. Miniserver

Würde ich lassen, aber zum überspringen falls man keinen Miniserver hat oder der aus irgendeinem Grund nicht erreichbar ist.

4. Netzwerk

Kann meiner Meinung nach raus.

5. Timeserver

Würde ich wegen der Timezone drin lassen.

6. MyLoxBerry

Würde ich nicht als separate Seite machen sondern vielleicht gleich auf die Startseite oder die letzte Seite.

7. Spenden

Vielleicht auch nicht als separate Seite sondern auf die Startseite?

Generell zur Realisierung:

Ich würde den Start-Wizard schon als eigenen Wizard mit eigenen Templates programmieren. Die vorhandene Basis ist ganz gut. Es wird schon ketzt ein Session-Management benutzt, welches ein Vor/Zurück erlaubt. Ist heute auch schon realisiert.

Heute ist er allerdings so realisiert, dass das Wizard-CGI dann direkt auch die Config-Dateien bearbeitet. Ich würde es jetzt eher so machen, dass der Wizard am Schluss die einzelnen CGIs unter /system per CURL oder LWP::Useragent aufruft und die Daten per POST übergibt. So braucht man die Logik nur einmal pflegen,

**Comment by christianTF** [comment]
Das bestehende Wizard-Script könnte zumindest die neuen Templates einbinden. Dann wäre zumindest das ganze JavaScript (inkl. validate) an einem einzigen Ort. 
Die Button-Reihe könnte man mit tmpl_if's auswechseln, und Funktionen, die man im Wizard nicht will, damit ausblenden.
Hintergrund ist: Mich stört es ein wenig, dass man bei jeder Änderung an einem Widget den (fast) identischen Code an einer zweiten Stelle mitpflegen muss. Das ist eine dauerhafte, potentielle Fehlerquelle, weil dann natürlich keiner daran denkt.

Bezüglich Config hätte ich gedacht, dass man beim Start vielleicht die entsprechenden Configs kopiert, alles in temporäre Configs speichert, und am Schluss damit die Originalconfig überschreibt. Dann wäre man safe, und man könnte den Wizard ggf. sogar abbrechen und später weitermachen.

Mit POST übermitteln wäre eine Möglichkeit, die OK/Error-Page müsste man unterdrücken.

**Comment by christianTF** [comment]
Willst du den Wizard machen?


Ich hätte jetzt noch auf dem Plan: 
LoxBerry::Log für PHP und BASH
Translate für Plugins

Wobei das alles (inkl. Wizard)  erst mit dem richtigem Release fertig sein muss, für eine Beta-Phase braucht das noch nicht fertig sein.

**Comment by mschlenstedt** [comment]
> Bezüglich Config hätte ich gedacht, dass man beim Start vielleicht die entsprechenden Configs kopiert, alles in temporäre Configs speichert, und am Schluss damit die Originalconfig überschreibt. Dann wäre man safe, und man könnte den Wizard ggf. sogar abbrechen und später weitermachen.

Das ist gar nicht nötig, da alles nur in der Session gespeichert wird. Erst wenn man wirklich auf "Installieren" klickt, werden die Configs geschrieben. Und das Schreiben würde ich wie gesagt den einzelnen CGIs überlassen.

Die gleichen Templates zu übernehmen ist eine gute Idee, dan entfällt die doppelte Pflege. Und mit HTML::Template ist es jetzt ja auch möglich.

Wizard kann ich machen, aber vorher muss ich die Plugin WebGUI machen (und mein Urlaub ist zu Ende :-))

Und wir sollten vorher alle einzelnen Widgets fertig haben, da gibt es auch noch was zu tun.

Ich schlage mal folgendes vor:

- Ich aktualisiere gerade das Image auf 0.3.3. Damit sollte das Basis-System (Raspbian-Grundgerüst) eingefroren werden. Das wird die Basis zum Fertigstellen der Widgets im Admin-Bereich.
- Einzelne Widgets überarbeiten
- LoxBerry::Log für PHP und BASH
- Plugin-Autoupdate integrieren
- Offene Punkte von @svethi ? Bin mir nicht sicher was da noch fehlt.

Dann ein neues Image 0.3.4, welches die öffentliche Beta wird und Feature Freeze hat. Damit machen wir dann auch den Wizard fertig.

**Comment by christianTF** [comment]
Mein Urlaub ich auch aus :-(
Ich mache gerade Bugfixing und habe Network.cgi in der Mangel.
Ich hätte gesagt, wenn Plugins fertig ist, und die Major issues, machen wir gleich eine Closed Beta nur für die Plugin-Entwicklern, die primär testen sollen, ob deren 0.23 Plugins funktionieren.
In der Zeit überarbeiten wir noch alles Widgets, ich mach LoxBerry::Log fertig, du macht Plugin-Autoupdate fertig, und den Wizard.
Wir bekommen dann wahrscheinlich auch Feedback zu den Widgets, wenn wir die sowieso noch überarbeiten müssen.

Sessions ist gut, das ist noch besser wie herumkopieren.

**Comment by christianTF** [comment]
Der Setup-Assistent wurde neu und "lightweight" implementiert und setzt nur die Sprache und die Passwörter. Es macht keinen Sinn, alles doppelt zu pflegen.
