### ISSUE TITLE
Validate: JavaScript-Code prüfen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#260]
Beim jQuery Validator habe ich die Doku so verstanden, dass die Fehler von Feldern standardmäßig im label for Tag angezeigt werden.
Im LoxBerry werden die immer unten angezeigt, sodass der Bezug zum Eingabefeld fehlt.

Das sollte man nochmal überprüfen, weil das Standardverhalten eigentlich genau richtig wäre.

Betrifft auch #174

**Comment by Woersty** [comment]
Umgebaut. Sollte jetzt passen.
