### ISSUE TITLE
LoxBerry WebUI with SSL (443) and self-signed certificate

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#262]
no text

**Comment by johny-mnemonic** [comment]
What about supporting https://letsencrypt.org for automated certificate management, instead of only self-signed one?

**Comment by mschlenstedt** [comment]
I tried letsencrypt in LoxBerry 0.2.3 but they do not support local up addresses and domains. So that is not possible.

**Comment by mschlenstedt** [comment]
Man muss dann beachten, dass man sowohl ein Zertifikat für die IPAdresse als auch für den lokalen Namen erzeugt.

**Comment by johny-mnemonic** [comment]
Well, I thought, that main point of having SSL is when you plan to open LoxBerry to the internet and then you will need some domain name anyway.

**Comment by christianTF** [comment]
Of course, opening to the internet is a reason too.
At the first, Self-signed to get familiar with it (users and us), more could follow up.

**Comment by svethi** [comment]
Hmm, viele aktuelle Browser lassen Verbindungen über selfsigned Certs nicht mehr zu. Da stellt sich die Frage ob es Sinn macht diese noch einzubinden.

**Comment by christianTF** [comment]
@johny-mnemonic I read a bit at letsencrypt and certbot, and I like it.

**Comment by johny-mnemonic** [comment]
@christianTF Yeah, what @svethi wrote is another reason to either don't bother with SSL and certificates at all, or provide users with easy way how to have Loxberry protected by signed certificate accepted by modern browsers.

**Comment by mschlenstedt** [comment]
"Irgendwann" von Svethi implementiert worden.

**Comment by Noschvie** [comment]
Im wiki habe ich dazu nur einen Abschnitt beim Download Server gefunden.

**Comment by mschlenstedt** [comment]
LoxBerry-Dienste -> Webserver

Das ist ein Wiki - jeder darf und kann an der Verbesserung der Dokumentation mitarbeiten.
