### ISSUE TITLE
Back- bzw. Cancel-Button in Templates

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#263]
Fehlt in:
updates.cgi
plugininstall.cgi
donate.cgi

**Comment by christianTF** [comment]
@mschlenstedt 

Was ist denn deine Ansicht dazu? Sollen wir an den genannten Seiten einen Button einbauen?

Und sollen wir _Back_ oder _Cancel_ machen. _Cancel_ ist in manchen Fällen falsch, wenn Einstellungen bereits per AJAX gespeichert wurden, deswegen bin ich eher in der "Back"-Fraktion.

**Comment by mschlenstedt** [comment]
Mit dem zusätzlichen Button in der Fusszeile habe ich Back bzw. Cancel nicht vermisst.

Einen Back Button erwarte ich eigentlich nur auf Fehlerseiten.
