### ISSUE TITLE
network.cgi: validate funktioniert nicht

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#266]
- Bei IP-Adressen kommen keine clientseitigen Fehlermeldungen.
Möglicherweise durch das Aktivieren/Deaktivieren der Felder im JavaScript. Evt. muss validate dabei neu aufgerufen werden.

- Keine serverseitige Validierung
Fehlerhafte Syntax bringt serverseitigen Perl-Fehler

**Comment by Woersty** [comment]
Schau ich mir an.

**Comment by christianTF** [comment]
Abgesehen davon, dass validate gerade auf dieser Seite gar nicht funktioniert, sollte die Netmask richtig validiert werden (nicht nur Syntax).
Eine 255.255.255.255 sollten wir beispielsweise nicht erlauben.
Auf die Art hat sich jemand im Forum seinen MS zum Klotz gemacht (-->SD-Karte restoren)

**Comment by Woersty** [comment]
Sollte jetzt gelöst sein. Testet mal.
@christianTF  @mschlenstedt @svethi

**Comment by christianTF** [comment]
Warum sind denn die Felder so gequetscht?
![screenshot_2018-01-07-21-29-24](https://user-images.githubusercontent.com/14220265/34653810-ece2b20e-f3f1-11e7-8bcb-5780b2e40ff8.png)

**Comment by christianTF** [comment]
Wenn ich kein Gateway eingebe und Speichern drücke, kommt kurz der Client-Fehler, und dann die Serverseite "an Error occured".


Blöd ist auch, dass dann bei Zurück alles weg ist. Aber das ist eine andere Baustelle.

**Comment by christianTF** [comment]
Die Client- und Server-Validierung ist nicht konsistent.
Ohne Gateway lässt mich der Client durch und ich bekomme einen Fehler vom Server.
Gleiches bei DNS und Subnet.
IP hab ich nicht probiert, wollte mich nicht hinausschießen.

**Comment by Woersty** [comment]
Achja. Submit blocken habe ich vergessen. Mache ich noch,

**Comment by Woersty** [comment]
Muss das noch einbauen, dass alle Felder beachtet werden.

**Comment by christianTF** [comment]
@Woersty Ich krieg noch einen Herzkasperl - ich will das nicht mehr testen.

Du löscht wirklich alles heraus, wenn man mit Fehler "Submit" drückt.
Warum kannst denn den Fehler nicht einfach darunter hinschreiben. 

Was mir auch noch nicht klar ist, warum du in den Templates alle `<input>`-Fields auf DIVs änderst. Geht das als Input nicht? Muss ich das verstehen? 

Ich werd einfach nicht warm damit.

![image](https://user-images.githubusercontent.com/14220265/34900081-5e1533e8-f7fd-11e7-8aa3-bbb4d5eaeb31.png)

PS: Ich hab natürlich bei dem Screenshot nur Fehler gemacht, schaut wild aus wenn nur noch Fehler dastehen und man garnicht mehr richtig ausbessern kann.

**Comment by christianTF** [comment]
Ich schließe es jetzt ab, weil es ist besser als das vorher.

Wenn du noch Mut findest, dann bau das Herauslöschen der Werte noch um (es sollen die fehlerhaften Werte zum Korrigieren drinbleiben).

Wenn du mir das mit dem DIV erklären könntest, und warum nicht INPUT?
Dir ist klar, dass du damit für jetzt und in alle Ewigkeit der Validate-Beauftragte bist ;-)

**Comment by Woersty** [comment]
> Dir ist klar, dass du damit für jetzt und in alle Ewigkeit der Validate-Beauftragte bist ;-)

Japp. Kein Problem.

**Comment by Woersty** [comment]
http://www.loxwiki.eu/display/LOXBERRY/Validierung+von+Eingabefeldern
