### ISSUE TITLE
jQuery Mobile: right panel width

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#267]
The right jQuery mobile panel is used to display the form help.
In jQuery mobile it has a fixed width of 17em.

I put in some CSS to enhance the right panel's width to 30em: 
https://github.com/mschlenstedt/Loxberry/blob/8f66c0b407d3cead20ed20736e6b6e38c976559e/webfrontend/html/system/css/main.css#L221

Unfortunately, what happens is:
- The panel width itself is enhanced to 30em. 
- But the main content only moves the default 17em to the left.
- Therefore, part of the 30em-help is still overlaid by the main content 

It seems that a transform-Tag for the content is missing, or the content is not reduced properly in size.

fyi, the panel CSS disables the .ui-panel-dismiss layer that usually disables using the content during open panels (some lines above the commented PANEL width CSS).

To reproduce the behaviour:
- Uncomment the block PANEL START to PANEL END in the main.css

Maybe someone has a clue what is missing to enhance the right panel to 30em.

**Comment by mschlenstedt** [comment]
Noch aktuell?

**Comment by christianTF** [comment]
Ja, ist noch aktuell, aber nicht mehr zu schaffen für 1.0

**Comment by christianTF** [comment]
Kein Bedarf mehr, es hat sich jeder daran gewöhnt.
