### ISSUE TITLE
"Ausführliche Hilfe" Link soll aus der Übersetzung kommen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#273]
Aktuell ist der "Ausführliche Hilfe" Link in den cgi's hardcoded. Somit kann diese Hilfe nie zu sprachspezifischen Hilfeseiten führen.

Der Hilfelink soll aus dem System-Sprachfile language_xx.ini kommen.
Jede Section (z.B. `[NETWORK]` bekommt einen `HELP_LINK=http://linkzurhilfe`

In den CGI's kann der Hilfelink mit `%SL{NETWORK.HELP_LINK}` ausgelesen und an LoxBerry::Web::lbheader bzw. head übergeben werden.

**Comment by mschlenstedt** [comment]
Oder soll der mit als Option in die plugin.cfg?

**Comment by christianTF** [comment]
Geht nicht, weil es könnte ja mehrere Links geben
Der Issue war für die System-Hilfe gedacht

**Comment by mschlenstedt** [comment]
Zu machen?

**Comment by christianTF** [comment]
Machen wir, wenn die Hilfe selbst templifiziert ist.

**Comment by christianTF** [comment]
Machen wir doch nicht. Hilfe zweisprachig zu pflegen ist zu aufwändig.
Stattdessen #938
