### ISSUE TITLE
Effizientere Installation der benötigten Packages in /opt/loxberry/sbin/installpackages.pl

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#278]
Effizientere Installation der benötigten Packages in /opt/loxberry/sbin/installpackages.pl
-> derzeit wird für jedes Paket eine neue apt-get install session gestartet. Besser wäre ein Installationsdurchlauf mit allen paketen: apt-get install Paket1 Paket2, etc. auch sollte der Parameter -no-install-recommends zu apt-get hinzugefügt werden

**Comment by Woersty** [comment]
Vorschlag in https://github.com/mschlenstedt/Loxberry/commit/e6b0a9b5a4cec7b8683e29b303650aa0ce314b6b
