### ISSUE TITLE
Installer für python Pakete

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#279]
Wie für apt sowas auch für python

**Comment by Woersty** [comment]
Einfach python-pip ins apt schreiben und dann mit pip installieren.
So macht der BLE Scanner das

**Comment by christianTF** [comment]
Geht das ohne Root? Oder startest du pip dann im Daemon?

**Comment by mschlenstedt** [comment]
Die neue Pluginschnittstelle kann ja Dinge als Root durchführen, damit wär's ok, oder?

**Comment by mschlenstedt** [comment]
Ich nehme den Punkt fürs nächste Image und packe dort python-pip mit rein. Entweder dann installation oder die neue Pluginschnittstelle oder wir füden es visudoers hinzu.

**Comment by mschlenstedt** [comment]
Image 0.3.2
