### ISSUE TITLE
network.cgi error message

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#284]
```
Software error:
HTML::Template::param() : attempt to set parameter 'network.ipaddress' with an array ref - parameter is not a TMPL_LOOP! at /opt/loxberry/webfrontend/cgi/system/network.cgi line 172.
For help, please send mail to the webmaster ([no address given]), giving this error message and the time and date of the error.
```

```
============= network.cgi ================
lbhomedir: /opt/loxberry
FORM called
== head == prints html head including <body> start =================

Detected language: de
[Sat Dec  2 23:56:58 2017] network.cgi: NETWORK.FRIENDLYNAME not defined.
[Sat Dec  2 23:56:58 2017] network.cgi:  at /opt/loxberry/libs/perllib/LoxBerry/Web.pm line 103.
friendlyname:
== pagestart == prints page including panels =================

Detected language: de
friendlyname:
-- SYSTEM Help Template --
We are in LEGACY help mode
templatepath: /opt/loxberry/templates/system/de/help/help_network.html
template_title:  LoxBerry Toolbox: Network
helplink:       http://www.loxwiki.eu/display/LOXBERRY/LoxBerry
Home string: Home
[Sat Dec  2 23:56:58 2017] network.cgi: HTML::Template::param() : attempt to set parameter 'network.ipaddress' with an array ref - parameter is not a TMPL_LOOP! at /opt/loxberry/webfrontend/cgi/system/network.cgi line 172.
```

**Comment by Woersty** [comment]
Ist da schon jemand dran oder habe nur ich das Problem?

**Comment by christianTF** [comment]
Hast du Config::Simple repariert?
Steht in deinen cfg-Dateien irgendwo ARRAY?

**Comment by Woersty** [comment]
Das hatte ich nur bei der ersten Fummelei mit der 0.3.x - das mit dem ARRAY xy sonstwas.
Momentan sieht es aber ok aus.

**Comment by christianTF** [comment]
Ok, dann ist es wirklich ein Bug?
Bei mir kommt der Fehler nicht.
@mschlenstedt @svethi Könnt ihr das Mal probieren?

**Comment by christianTF** [comment]
Das _muss_ aus deinen cfg-Dateien kommen, das ist nur das Ausgeben des HTMLs mit den Daten aus der general.cfg.

**Comment by svethi** [comment]
Also bei mir kommt da kein Fehler. Was genau machst Du denn wenn der Fehler kommt? Was gibst Du ein?

**Comment by Woersty** [comment]
Ich gebe gar nix ein. Ich rufe das nur aus dem Mainmenu aus auf.
Meine Network section sieht so aus:

> [NETWORK]
> IPADDRESS=
> TYPE=dhcp
> GATEWAY=
> MASK=
> INTERFACE=eth0
> SSID=
> DNS=

**Comment by Woersty** [comment]
Nachtrag: Fülle ich alles mit ausgedachten Werten aus, geht es. 
Er verträgt es nicht, wenn die Werte nicht ausgefüllt sind - ist bei mir aber normal, da DHCP

**Comment by christianTF** [comment]
Irgendwas passt bei dir nicht. Das funktioniert, auch wenn ich die general.cfg leere:

```
[NETWORK]
FRIENDLYNAME=LB31-dev
TYPE=dhcp
GATEWAY=
DNS=
IPADDRESS=
INTERFACE=eth0
MASK=
SSID=
```

**Comment by svethi** [comment]
Ja, geht bei mir auch. Irgend etwas passt da bei Dir nicht. Hast Du denn /opt/loxberry gelöscht und aus dem git geclont? Ich glaube, ich hatte Config::Simple vorher gefixt.

**Comment by Woersty** [comment]
> Du denn /opt/loxberry gelöscht und aus dem git geclont?

Ja, hatte ich.

**Comment by christianTF** [comment]
Das ist die Zeile, die aufschlägt:
https://github.com/mschlenstedt/Loxberry/blob/loxberry-0.3.0-saruman/webfrontend/cgi/system/network.cgi#L172

Die Variable wird gar nicht mehr im Code geschrieben, sondern das cfg direkt an HTML::Template übergeben:
https://github.com/mschlenstedt/Loxberry/blob/e320d215db17adf25d2c21678099f9b9a1cde104/webfrontend/cgi/system/network.cgi#L92

Laut HTML::Template wird ein nicht existierender Wert leer übergeben.
Da sich HTML::Template über einen Array aufregt, und das genau der Config::Simple Issue ist, dass leere Configzeilen einen Array auslösen, würde ich sagen, du deinstalliert nochmal erst die Config-Simple Lib von Debian, löscht dann alle Config/Simple.pm Files am LB, und installierst wieder die Debian-Lib.

**Comment by christianTF** [comment]
Testen mit dem neuen Image, wenn's nicht mehr auftritt, kann man das schließen.
#266 muss noch gefixt werden.

**Comment by christianTF** [comment]
@Woersty Auch hier schiebe ich dir den Ball zu, ob du Mal ein paar Experimente mit diesem Widget (und überhaupt) machen kannst, ob die Sachen funktionieren :-)

**Comment by christianTF** [comment]
Ich schließe mal, das war sicher Config::Simple aus CPAN.
