### ISSUE TITLE
For help, please send mail to the webmaster ([no address given])...

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#287]
>Software error:
> bla bla bla
> For help, please send mail to the webmaster ([no address given]), giving this error message and the time and date of the error.

Könnte man mal auf was die GitHub Issue Seite verlinken.
Oder wenigstens das "no address given" ändern. Oder?

**Comment by Woersty** [comment]
Vorschlag:
```
use CGI::Carp qw(fatalsToBrowser set_message);
set_message('You can report this error <a target="bugreport" href="https://github.com/mschlenstedt/Loxberry/issues/new">here</a> if you think it is a general problem and not your fault...');
```
![errormsg](https://user-images.githubusercontent.com/20454116/33529463-8cd4b722-d871-11e7-8af9-8e66b4cf3827.gif)

Könnte man auch über die Templates in der entsprechenden Sprache laufen lassen - natürlich...

**Comment by christianTF** [comment]
Wäre wahrscheinlich am besten in LoxBerry::Web aufgehoben?

**Comment by Woersty** [comment]
Wo auch immer - so wie momentan jedenfalls unschön - wenn auch nicht sooooo wichtig - zugegeben.

**Comment by christianTF** [comment]
Probier das mal aus - ich bring den Fehler ja nicht zusammen:
https://github.com/mschlenstedt/Loxberry/blob/loxberry-0.3.0-saruman/libs/perllib/LoxBerry/Web.pm

**Comment by Woersty** [comment]
Geh in die general config und schmeiß testweise ein paar Werte raus.
Dann sollte das bei dir auch nicht mehr gehen, oder?!

**Comment by christianTF** [comment]
Yep - Fehlermeldung getestet, funktioniert - Closed with https://github.com/mschlenstedt/Loxberry/commit/c4ade2a09eb6ddf82f59b534d9abca4c8d4b5824

**Comment by Woersty** [comment]
Ja, greift. Habe die Web.pm geändert. Message bleibt. (obwohl aus network cgi wieder raus)
Damit kann auch **use CGI::Carp qw(fatalsToBrowser);** aus den cgis raus. z.B. network.cgi
