### ISSUE TITLE
New index.cgi: Systemzeit "tanzt" aus der Reihe

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#288]
Ein CSS-Issue
Alle Widgets haben einen eigenen Block, aber die Uhr hat oben 0px Abstand.
Ich hab es nicht herausgefunden, wie man die Uhr verschiebt.
Die Uhr ist im main.css gestyled.

![image](https://user-images.githubusercontent.com/14220265/33531329-efcbc64e-d88b-11e7-880c-4a8df4ee2aa3.png)

**Comment by mschlenstedt** [comment]
Die Uhr kommt von @Woersty  Da kann er sicherlich helfen.

**Comment by christianTF** [comment]
Wenn alles andere nach oben rutscht, ist es auch okay!
Hab es gestern nicht mehr geschafft.

**Comment by Woersty** [comment]
Ich gucke heute Abend.

**Comment by Woersty** [comment]
Achso - kannste mal die aktuelle Version ins Git schieben? Dann kann ich mir die syncen.

**Comment by christianTF** [comment]
Alles oben

**Comment by Woersty** [comment]
In welchem Branch? Bei mir zeigt er die Uhr gar nicht an?!

**Comment by Woersty** [comment]
Ah ok - Cache löschen...

**Comment by christianTF** [comment]
Danke!

**Comment by christianTF** [comment]
Das sind die falschen Dateien.
Das neue index.cgi lädt als Template /opt/loxberry/templates/system/index.html

**Comment by christianTF** [comment]
Die Templates aus en/de/es werden überhaupt nicht mehr benutzt (Ausnahme: help). 
Nur noch das plugininstall, bis es Michael umbaut.

Die alten Templates sind nur noch deswegen da, weil wir das für die Übersetzung brauchen.
