### ISSUE TITLE
Wenn friendlyname leer, wird nicht LoxBerry als Fenstertitel gesetzt

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#289]
Der Fenstertitel des Browsers zeigt die URL, wenn friendlyname leer ist.
Dort soll LoxBerry stehen.

**Comment by svethi** [comment]
Was mir nicht so ganz klar ist, ist der Sinn und Zweck des friendlyname. Ich finde das führt zu Problemen. Leute, die sich jetzt mehrere von den Loxberry's hinstellen und keine Ahnung von der Materie haben, könnten der Meinung sein, dass es reicht den Loxberry zu benennen. Wenn allerdings der hostname nicht geändert wird, gibt das Probleme. Viel wichtiger ist für mach da der hostname. Schließlich ist es auch der, der im Windows, Fritzbox etc. angezeigt wird. Friendlyname finde ich allerdings besser als hostname, da da vllt nicht so viele etwas anfangen können. Ich würde den hostname rausnehmen, oder nur noch anzeigen und mit dem friendlyname den hostname setzen.
Was sagst Du dazu?

**Comment by christianTF** [comment]
Ich will aber Wohnzimmer dortstehen haben, auch wenn der Hostname wopi heißt.

Ein Button zum Übernehmen des Hostnamens als Friendlyname könnte man machen. Ich hab das ganz bewusst getrennt.
Es steht auch kursiv dort, dass das nicht der Hostname ist und man den unter Netzwerk ändern kann.

**Comment by svethi** [comment]
Okay, Okay, War ja nur so eine Frage :-)

**Comment by Woersty** [comment]
WoPi ? 😂 
Dann ist meiner HaPi im HWR. Grins.
Sorry, musste sein.
BüPi ist dann der im Büro :)

**Comment by christianTF** [comment]
wopi, papi, buepi.
Nur der LB31-DEV heißt einfach nur "loxberry" :-)

![image](https://user-images.githubusercontent.com/14220265/33625903-667cc6bc-d9f9-11e7-87a5-0ce745a0c2e5.png)

**Comment by svethi** [comment]
Das geht ja aber nicht mehr lange gut bei Dir. Solltest auf 10.0.0.0/16 oder gar 8 umbauen ;-)
Wo ist denn eigentlich der Schlapi? 😂

**Comment by christianTF** [comment]
Schlapi ist verboten :-) Schlafzimmer ist netzfrei :-)
