### ISSUE TITLE
eMail Adresse invalid

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#29]
Du hast u.a. im index.cgi von Miniserver-Backup-Plugin den Eintrag:
Copyright 2016 Michael Schlenstedt, michael ät loxberry pkt de
Die Adresse gibt es aber nicht. Eventuell auf info ät loxberry pkt com oder eine extra dafür ändern?

Gruß

**Comment by mschlenstedt** [comment]
Fixed
