### ISSUE TITLE
Plugin-Datenbank lesen in LoxBerry::System

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#292]
@mschlenstedt 
FYI 
Ich baue in LoxBerry::System eine Funktion ein, mit der die Plugindatenbank komplett **gelesen** werden kann.
Ich habe das jetzt selbst zweimal gebraucht, und du brauchst das sicher auch noch bei der Plugin-Installation.

Schreiben hab ich aber nicht vorgesehen, außer das macht Sinn?

Ich werde die Funktion so machen, dass die Kommentare nicht verloren gehen. Dann kannst du das Resultset direkt verwenden, um das geänderte pluginfile neu zu schreiben.

**Comment by mschlenstedt** [comment]
Schreiben wäre eigentlich nur bei der Installation notwendig und wenn man die Autoupdate-Funktion ein/ausschalten will. Den einen Einsatzzweck kann ich direkt in plugins.cgi einbauen.

**Comment by christianTF** [comment]
Closed with https://github.com/mschlenstedt/Loxberry/commit/334d25e0687e0b9aa777ec345e8208135ea4f7b2

@mschlenstedt 
Ich habe ein Demo-CGI und Demo-HTML in /webfrontend/cgi/system/demo/ gelegt.

Wenn du die Felder erweiterst, dann an dieser Stelle:
https://github.com/mschlenstedt/Loxberry/blob/334d25e0687e0b9aa777ec345e8208135ea4f7b2/libs/perllib/LoxBerry/System.pm#L445


lg, Christian
