### ISSUE TITLE
Fehlermeldungen bei apt

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#294]
beim apt-get bekomme ich 2 Fehler von defekten repositorys hat die jemand selber hinzugefügt??

N: Ignoring '02periodic' in directory '/etc/apt/apt.conf.d/' as it is not a regular file
N: Ignoring '50unattended-upgrades' in directory '/etc/apt/apt.conf.d/' as it is not a regular file

**Comment by christianTF** [comment]
Kennen wir schon :-)
#196 

Die Links in apt/apt.conf.d/ zeigen auf falsche Dateien in /opt/loxberry/system/unattended-upgrades/

War ein Fehler in der Image-Anleitung. Du musst die Dateien glaub ich nur richtig umbenennen oder so irgendwie war das.

In der aktuellen Image-Anleitung ist das schon richtig.

**Comment by svethi** [comment]
Achso, den Topic hatte ich jetzt nicht dazu geordnet :-)

**Comment by mschlenstedt** [comment]
Das ist schon ein Problem. Wir haben Symlinks angelegt und er meckert, dass es sich um keine regulären Dateien handelt.

**Comment by christianTF** [comment]
Nein, ist kein Problem. Problem war, dass ich die Namen falsch in der Anleitung hatte. Die Symlinks zeigen im Image ins Leere, die Anleitung ist aber gefixt.

**Comment by christianTF** [comment]
Duplicate of #196 (Image creation manual linked wrong files)
