### ISSUE TITLE
LoxBerry 1.0?

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#295]
Ich stelle das in den Raum, dass der RELEASE nach den vielen Erweiterungen, und der Reife nach dann über einem Jahr schon eine "richtige" Versionsnummer verdient hat.

**Comment by christianTF** [comment]
PS: Loxone ist bei 9.1. Vor sieben Jahren, als ich den Saunabaustein in Betrieb genommen habe, habe ich gemeldet, dass die Temperatur falsch angezeigt wird, und das ist heute noch so. 
Da brauchen _wir_ uns nicht hinter BETA verstecken 😎

**Comment by svethi** [comment]
Das stimmt. Bin ich auch für. Patches kann man immernoch ausrollen ;-)

**Comment by mschlenstedt** [comment]
Ist mir eigentlich zu schnell. Loxone muss das aus Marketinggründen machen.

Lasst uns noch ein Release abwarten. 0.2 war die erste brauchbare Version, aber wir haben gemerkt, dass die Pluginschnittstelle nicht ausreichend ist. Die haben/werden wir jetzt noch einmal umfangreich umbauen. Und dann hoffe ich, dass sich daran nichts mehr ändern muss. Dann werden wir noch einmal umfangreich an den Systemrechten schrauben. Auch da bin ich mir absolut nicht sicher, ob das alles der Weisheit letzter Schluss ist.

Wenn diese beiden größten Baustellen behoben sind, dann ist es Zeit für eine 1.0

**Comment by christianTF** [comment]
Ok!

**Comment by mschlenstedt** [comment]
Ich hab mir das nochmal überlegt: ich finde den neuen LB so geil, wir machen doch die 1.0. Das neue Updatefeature von @christianTF  ist der Hammer. Und die ganze Geschichte mit Berechtigungen, der neuen Pluginschnittstelle, der ausgemerzte MiniDLNA, Pluginupdates, SystemLIBs.... 

Das ist eine 1.0 Wert :-)
