### ISSUE TITLE
LoxWiki Englisch

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#296]
Das zweite, was ich neben LB1.0 in den Raum stellen möchte, ist ein zweiter LoxWiki Bereich in Englisch.
Ich würde zumindest meine Modul-Dokumentation schon in Englisch führen (und dann _nur_ noch in Englisch).
Die Links für "Ausführliche Hilfe" könnten dann je nach Sprache ins Deutsche und/oder englische Wiki zeigen.

Bevor die ganze Doku ums Template-System und die Übersetzungs-Guides mache, sollten wir überlegen, ob wir das gleich in einem englischen Bereich machen, oder ich in jetzigen Wiki diese Artikel in englisch erfasse.
Für Entwickler darf reine englische Doku kein Problem sein, und bei den Plugins soll sich jeder Plugin-Entwickler selbst überlegen, in welcher/welchen Sprachen er seine Anleitungen anbietet.

LG, Christian

**Comment by mschlenstedt** [comment]
Ich ganz persönlich finde , dass sich der Aufwand im Moment nicht lohnt. Gefühlte 95% des LoxForums und LoxWikis sind deutschsprachige Benutzer. Das LoxBerry-Wiki wird mehr oder weniger von 1-2 Personen gepflegt. Wir haben meiner Meinung nach einfach noch zu viele andere Baustellen. Ich finde wir könnten im ersten Schritt auch mal darüber nachdenken auf den LoxWiki-Seiten ein Google-Translate Form unterzubringen, so wie hier: http://www.geopainting.com/ Vielleicht gibt es da sogar schon was fertiges - müsste man mal die Wiki-Macher fragen.

Aber ich stelle mich dem auch nicht in den Weg! Wenn ihr gerne auch einen englischsprachigen Bereich pflegen wollt, ist das für mich absolut in Ordnung!

**Comment by johny-mnemonic** [comment]
@mschlenstedt I may be completely wrong, but I would bet, that the sole reason why 95% of LoxWiki and LoxForum users are German is, that these pages are in German and for majority of people not speaking German it is not worth the effort to join there. Google Translate is not exactly great translating German to English (albeit much better than translating my own language to English ;-) ).
I completely respect your decision to not spend time on switching to English, but do not base it on current percentage of non-German users please ;-) By keeping it in German you are simply locking it to German userbase, which is completely fine, if that is what you want.

**Comment by christianTF** [comment]
D.h. für dich ist es okay, wenn ich die Anleitung fürs Template-System in Englisch (im deutschen Bereich) schreibe. In einen englischen Bereich kann man es immer noch verschieben, hingegen hätte ich keine Lust, es dann doppelt schreiben zu müssen.

@johny-mnemonic We already have an English LoxWiki, and the response is stuttering. People (Germans and others) are not very "contributing-happy" to write articles. Most post comments, ignoring the idea of contributing _inside_ of the article.
Therefore, I have no problem of writing some developer guides in English. But as we develop, someone else should document (at least the easy stuff like installation).
This is where Michael is right - at LoxWiki non-german speakings ask for an English space. Now it's there, and - however - it is (nearly) empty.

I see it more clear some days after my initial issue: There is too little demand. Beside you, no-one asked for it. We have to ask if someone would like it. That's too little demand.

**Comment by mschlenstedt** [comment]
@christianTF  Ja klar! Ich will Euch absolut nichts verbieten - schließlich stammen 99% der aktuellen LoxBerry-Version von Euch und ohne Euch wären wir lange nicht soweit wie jetzt! Schließlich ist das ein Gemeinschaftsprojekt.

Die Aussage oben gilt mehr oder weniger für mich. Und eine Plugin-Doku nur in English finde ich absolut ok.

**Comment by johny-mnemonic** [comment]
@christianTF Yeah, people are generally lazy to create something meaningful and valuable for others :-)
That's why you guys are our super heroes and I wouldn't dare to demand anything from you.

**Comment by christianTF** [comment]
I've asked Max (Wiki admin) if we can use the Composition Plugin from Confluence.
With that, every page can use tabs to switch between languages. That's more easy to manage as no new area needs to be build up from scratch.
That would be a trade-off of effort. Also every plugin author could use it if he wants to provide multiple languages.

Max will have to check the licence agreement, but I think it's free for community based wikis.
