### ISSUE TITLE
Cockpit / Webadministration

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#298]
Gerade in der ct gelesen: http://cockpit-project.org

Finde ich ganz cool, es gibt sogar eine Kommandozeile.

**Comment by mschlenstedt** [comment]
Ich finde das Ding nicht schlecht - insbesondere das Terminal könnte hilfreich sein! Da braucht man kein Putty mehr, was Anfängern durchaus helfen könnte.

Ihr könnt es ja mal testen - vielleicht machen wir es zum festen Bestandteil? Alternativ als Plugin.

Installation:
echo 'deb http://deb.debian.org/debian stretch-backports main' > /etc/apt/sources.list.d/backports.list
apt-get update
apt-get install cockpit

Aufruf dann über http://loxberry:9090

**Comment by mschlenstedt** [comment]
Und wenn man sich als Root einloggt hat man sogar einfachen Zugriff auf alle Logfiles des Systems.

**Comment by christianTF** [comment]
Ich habs grad installiert - schaut wirklich cool aus.

Bezüglich LoxBerry-Systembestandteil, da habe ich sehr gemischte Gefühle... :fearful:

**Comment by mschlenstedt** [comment]
Einverstanden. Ist ja auch RatzFatz als Plugin erstellt. Das kommt dann aber erst für den V0.3 :-)
