### ISSUE TITLE
500 internal Server Error in index.cgi

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#299]
Hi,
wenn es NETWORK.FRIENDLYNAME nicht gibt, steigt die WebGUI aus
line 45

**Comment by svethi** [comment]
Ist nicht nur NETWORK.FRIENDLYNAME
Durch das Zurücksetzen meiner general.cfg auf git Version stand die wieder auf firststart und wollte in den Assistenten springen was total daneben geht. Nun ist der Assistent ja nicht fertig und es wird sich wohl von selber beheben wenn der Assistent dann mal einsatzbereit ist?!

**Comment by christianTF** [comment]
Es muss alles auch ohne Assistent gehen. Ich schau mir das an.

**Comment by mschlenstedt** [comment]
Ich dachte Du fährst Ski?!? :-)

**Comment by christianTF** [comment]
Bin gerade heimgekommen!

**Comment by svethi** [comment]
Ja, das ging auch alles vor Deinen letzten Änderungen. Setze mal in der general.cfg diesen Wert für den startassistenen auf 1. dann siehst Du was ich meine

**Comment by christianTF** [comment]
Den Startassistenten hab ich in der index.cgi auskommentiert.
Kann sein, dass das Schmerzen bereitet.

**Comment by christianTF** [comment]
Der friendlyname war nur eine debug-Meldung von mir, das führte nicht zum Fehler.
Ich habe das if für den Wizzard drin gelassen, aber innerhalb des if's ist nichts mehr passiert. Deswegen Fehler 500.
Ich hab jetzt auch das if startup auskommentiert
