### ISSUE TITLE
Setup - Einführungsseite

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#3]
Auf der Einführungsseite fehlt bei 'Plgins' das u.
Weiterhin: Deines 'LoxBerry' oder 'LoxBerrys'?
Außerdem: 'zeitpunkt' wird groß geschrieben
Und 'In nun folgenden' oder 'Im nun folgenden' Setup-Assistenten?

**Comment by mschlenstedt** [comment]
Fixed
