### ISSUE TITLE
Scroll-Bar WLAN

### ISSUE THREAD

**Issue by hismastersvoice** [mschlenstedt/Loxberry#30]
Werden mehr WLAN Netzwerke angezeigt als auf den Bildschirm passen sollte ein Scrollbar kommen.
Bei Firefox und IE wird keiner angezeigt und man kann nur mit den Cursor-Tasten runter fahren.

**Comment by mschlenstedt** [comment]
Habe es mit

iExplorer 11
Edge
Chrome

getestet. Überall kommt die Scrollleiste. Diese wird vom Template/Javascript und auch nicht unterdrückt. Bitte nochmal testen - vielleicht irgendeine lokale Einstellung bei Dir?

Habe trotzdem "scrollbars=true" mal explizit gesetzt.
