### ISSUE TITLE
Apache und PHP:  AH01265: attempt to invoke directory as script

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#301]
```
 AH01265: attempt to invoke directory as script: /opt/loxberry/webfrontend/cgi/plugins/phptest/
```
wenn es in einem Plugin-Ordner (hier phptest) ein index.php gibt, und nicht index.php direkt aufgerufen wird, sondern nur das Verzeichnis (http://loxberry/admin/plugins/phptest/)

**Comment by svethi** [comment]
Das Problem an der Sache ist, dass PHPs im CGI eigentlich gar nichts zu suchen haben und in einem als Scriptalias deklarierten Ordner Dein "Problem" ein Sicherheitsrisiko darstellen kann. Ist jetzt halt die Frage ob man das ändern möchte.

**Comment by christianTF** [comment]
Der HTML-Ordner ist aber ohne Auth, das will auch keiner.
Wenn man Index.php angibt, dann geht es, ist halt nicht sehr schön.

**Comment by mschlenstedt** [comment]
Das gab es auch schon mal als Issue. Einige Entwickler benötigten CGIs ohne Auth bzw. PHPs mit Auth.

Ich wäre dafür den CGI-Ordner sterben zu lassen und nur noch 2 Ordner zu haben:

html
html_protected

In beiden Ordnern kann man CGIs, PHPs und statisches HTML verwenden. Beim Aufruf des Ordners wird zuerst index.cgi versucht, dann index.php und schließlich index.html

Einzige Bedingung: Aus dem LoxBerry-Menü wird immer html_protected/PLUGINNAME aufgerufen. Da muss also das Hauptmenü des Plugins liegen.

Den alten CGI-Ordner lassen wir als Alias oder Symlink noch aus Kompatibilitätsgründen.

**Comment by christianTF** [comment]
Noch besser. Jetzt Check ich auch, was das protected im Sample Plugin bedeutet.

**Comment by mschlenstedt** [comment]
Ich baue mal was ein.

**Comment by christianTF** [comment]
Html_protected ist bisschen lang, wenn man z.b. im Browser ein Plugin direkt aufrufen möchte. Vielleicht fällt dir noch was kürzeres bzw. tippbareres ein :-)

**Comment by mschlenstedt** [comment]
/admin ist ja der Alias auf html_protected, also /admin /PLGUNINAME

Aber wie wär's mit "htmlauth"?

**Comment by christianTF** [comment]
An den Alias hab ich nicht gedacht.
Htmlauth ist gut, ist klarer was das ist

**Comment by mschlenstedt** [comment]
Ich habe das entsprechend geändert:

- /opt/loxberry/webfrontend/cgi ist jetzt ein Symlink auf /opt/loxberry/webfrontend/htmlauth
- Sowohl in /opt/loxberry/webfrontend/htmlauth als auch in /opt/loxberry/webfrontend/html kann man nun statisches HTML, CGI und PHP verwenden
- Beim Verzeichnisaufruf ist die Reihenfolge: index.cgi index.php index.html
- /admin ist weiterhin ein Alias auf /opt/loxberry/webfrontend/htmlauth
- /auth ist ein weiterer Alias auf /opt/loxberry/webfrontend/htmlauth (genau wie bisher /admin), der beim Direktaufruf verwendet werden sollte

Ich bekomme allerdings jetzt beim Hauptmenü ein Fehler:

![11-12-_2017_20-46-52](https://user-images.githubusercontent.com/16830799/33850853-80fa0ab6-deb5-11e7-82a3-b2ce53b61aff.jpg)

Liegt das an der Änderung oder ist das noch ein aktuelles anderes Problem?

**Comment by christianTF** [comment]
Naja, LoxBerry::System und LoxBerry::Web kennen den neuen Pfad noch nicht? Hast du alles umbenannt und die ganzen CGIDIR-Variablen mitgeändert? 

Ich muss die Module auch noch durchsehen, ob dort sicher kein statisches cgidir mehr vorkommt

**Comment by mschlenstedt** [comment]
Äh, nö :-) Wo muss ich denn da überall ran? Nur an /etc/environment? Oder auch direkt in den Modulen?

**Comment by christianTF** [comment]
Ich schau in die Module - schaust du dir das setenvironment.sh an

**Comment by mschlenstedt** [comment]
Geht los!

**Comment by mschlenstedt** [comment]
Das nenn' ich mal coole AWK-Skripte! Das ist ja fast so gut wie Perl :-)

**Comment by mschlenstedt** [comment]
Wollen wir den Variablennamen bei LBCGI/LBPCGI belassen?

**Comment by christianTF** [comment]
Gute Frage.
Im System.pm sind alle Pfade hardcoded mit `$lbhomedir/webfrontend/...`

**Comment by christianTF** [comment]
Wie geht das bei den Plugins, die ins CGI installieren?

**Comment by mschlenstedt** [comment]
Das müsste trotzdem gehen, weil es einen Symlink von CGI auf htmlauth gibt (im Filesystem).

Konsequenterweise müssten wir LBCGI in LBHTMLAUTH umbenennen. Wenn nicht jetzt, dann vermutlich nie, oder?

**Comment by mschlenstedt** [comment]
Soll ich System.pm anpassen? Mit VIM ist das recht scnell gemacht.

**Comment by christianTF** [comment]
Ich habe Mal im System.pm die Variableninhalte der CGI's auf den Pfad htmlauth geändert (commit)

**Comment by christianTF** [comment]
Wenn nicht jetzt, dann nie - richtig :)

**Comment by mschlenstedt** [comment]
%s/LBSCGI//LBSHTMLAUTH//g

Also los :-) Ich mach setenvironment,sh

**Comment by christianTF** [comment]
Geht's bei dir jetzt?

**Comment by mschlenstedt** [comment]
Ja geht.

**Comment by christianTF** [comment]
D.h. neu klonen :-)

**Comment by christianTF** [comment]
Ich hab gerade die System.pm commited

**Comment by mschlenstedt** [comment]
Jetzt müssen wir nur noch alles finden, wo wir schon lbscgi und lbpcgi verwendet haben :-)

**Comment by christianTF** [comment]
Stimmt, das wären mal alle system/*.cgi's

**Comment by christianTF** [comment]
Für Plugins habe ich  $lbcgidir drinnen gelassen, mit Zuweisung auf $lbhtmlauthdir.
Ich hoffe, diese Änderungen machen mit den Plugins keine Probleme 🐇

**Comment by christianTF** [comment]
Bei mir geht grad garnichts mehr 😉
Edit: Apache restart, und es wird wieder bunt!

**Comment by christianTF** [comment]
Das war unerwartet einfach :-)
In drei Dateien hab ich's noch ausgetauscht

**Comment by christianTF** [comment]
Bei mir geht http://LoxBerry/admin/plugins/phptest/ immer noch nicht
Http 403

Mit index.php gehts

**Comment by mschlenstedt** [comment]
Hast Du den Apache neu gestartet? /etc/init.d/apache2 restart

**Comment by mschlenstedt** [comment]
Argh, ich habe noch vergessen die .htaccess zu commiten!

**Comment by mschlenstedt** [comment]
Doch nicht - sorry. Ist alles im Repo drin.

**Comment by svethi** [comment]
Ähm, was ist hier los? ;-)
Ich hatte gestern hier Internetausfall und hab nichts mitbekommen.
Wenn ihr im Filesystem Symlinks habt, müsst Ihr Symlinks im Apache freigeben. Das macht der normal nämlich auch nicht.

**Comment by christianTF** [comment]
Die htaccess wird's sein, die habe ich nicht kopiert

**Comment by mschlenstedt** [comment]
@svethi Guckst du hier: https://github.com/mschlenstedt/Loxberry/blob/loxberry-0.3.0-saruman/system/apache2/sites-available/000-default.conf

**Comment by svethi** [comment]
Okay
@Christian geht das denn jetzt?
Die Verzeichnisse sind ja noch immer als ScriptAlias gesetzt. So wie ich das verstanden habe, kommt genau dann das Problem

**Comment by christianTF** [comment]
mit dem /opt/loxberry/webfrontend/htmlauth/.htaccess file geht's jetzt bei mir.

**Comment by christianTF** [comment]
Probier mal http://loxberry/admin/plugins/phptest/

**Comment by christianTF** [comment]
@svethi Geht das jetzt bei dir? Dann Close?

**Comment by mschlenstedt** [comment]
Ich mach mal zu. Das muss gehen :-)
