### ISSUE TITLE
general.cfg commited

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#304]
Da wurde die general.cfg commited was mir jetzt Probleme beim mergen einbringt. Da mit dem Ignore scheint nicht richtig zu funktionieren.

**Comment by christianTF** [comment]
Schmeiß das gitignore wieder hinaus, wenn's nicht funktioniert. Einen Versuch war's wert☺

**Comment by svethi** [comment]
Der will bei mir aber nicht mergen. Kann ich da Dateien rausnehmen, oder muss ich mir meine Version sichern und dann einfach drüberbügelm?

**Comment by christianTF** [comment]
Ich hab keine Idee....

**Comment by mschlenstedt** [comment]
Versuch mal Deine lokale general.cfg einfahc zu löschen und dann ein Pull zu machen.

**Comment by Woersty** [comment]
Ich kann gar nix mehr machen weil mein Entwicklungssystem ne volle root Partition hat und tot ist. 👎 
Da müsste mal jemand über die Partitionsgrößen nachdenken.

```

loxberry@loxberry:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       2.5G  2.4G     0 100% /
devtmpfs        213M     0  213M   0% /dev
tmpfs           218M     0  218M   0% /dev/shm
tmpfs           218M   23M  195M  11% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           218M     0  218M   0% /sys/fs/cgroup
tmpfs            25M  2.2M   23M   9% /var/log
tmpfs            25M     0   25M   0% /var/tmp
tmpfs            50M  8.0K   50M   1% /tmp
tmpfs            25M     0   25M   0% /opt/loxberry/log/plugins
/dev/mmcblk0p1   42M   21M   21M  51% /boot
tmpfs            44M     0   44M   0% /run/user/1001

```

**Comment by mschlenstedt** [comment]
Hat er bei dir das Dateisystem nicht auf downvote SDKarte erweitert?

**Comment by svethi** [comment]
Stimmt, hat er bei mir auch nicht gemacht. Würde das vielleicht durch die Autoconfig initiiert und die geht ja zur Zeit noch nicht?

**Comment by svethi** [comment]
@Woersty mach mal als root raspi-config und dann auf advanced Options und dann expand filesystem

**Comment by Woersty** [comment]
Stimmt. Jetzt wo ich die Größen sehe....
Dachte auch das macht er von selbst.
Aber nun genug offtopic.
Lööft wieder 🥇

**Comment by christianTF** [comment]
Täuscht es mich, oder habe ich das FS-Erweitern in der loxberryinit.sh auskommentiert gesehen?

**Comment by mschlenstedt** [comment]
Ja, ist auskommentiert. Seit stretch ist das Out of the Box dabei. Hat bei mir eigentlich auch immer geklappt...

**Comment by svethi** [comment]
Michael, hab meine erstmal wegkopiert dann zurückgesetzt, dann pull, dann zurückkopiert, dann assume-unchanged

**Comment by christianTF** [comment]
und geht wieder?

**Comment by svethi** [comment]
Hör mal zu, bin Profi ;-)
Obwohl, ich hänge schon wieder Tage an Perl und Bash und Init und systemd fest.
