### ISSUE TITLE
LoxBerry Update

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#306]
Kurz zusammengefasst, wie das funktionieren wird. 
Feedback Willkommen!!

- User kann einstellen, ob er Releases oder auch Prereleases bekommen möchte. **OK**
- Er kann Notify Aus, Notify Ein oder Automatisch updaten einstellen. **OK**
- Per Cron wird regelmäßig die GitHub Releaselist des Repos gezogen. Im Script kann auch Major/Minor/Builds gefiltert werden (damit z.B. nur 0.3er oder 0.3 und 0.4, aber nicht 0.5 upgedated wird) 
- Aus der Releaselist wird dann der neueste Release oder Prerelease gesucht, Versionsnummer geprüft und im Updatefall die URL retourniert. **OK**
- Wenn der User automatische Updates aktiviert hat, wird das Release-Zip gezogen und entpackt. **OK**
- Mit rsync --clear und einer exclude list wird über /opt/loxberry drüber gebügelt. Die rsync-Backup-Option bleibt vorerst aktiv. **OK**
- Die exclude list wird die Config, die Plugin-Verzeichnisse, das Legacy-Verzeichnis enthalten. **OK**
- Inwieweit die system/ Files mitgenommen werden, muss man sich noch überlegen. **nicht enthalten**
- Pro Release KANN es optional ein Update-Script mit der Release-Nummer geben. **OK**
- ALLE Update-Scripts von Quellversion+1 bis Zielversion werden ausgeführt. Damit kann man dann z.B. Systemsettings nachziehen, die nicht in /opt/loxberry liegen, oder die die Config ändern müssen. **OK**
- Ein Updatescript soll auch ein Reboot-Required File erstellen können, dass von der Ende-Routine ausgewertet werden kann. 

Das Notify (ohne Update) hab ich mir schon grundsätzlich überlegt, aber noch nicht ausgereift genug, um es in Code zu gießen. Das kommt dann mit einem automatischen Update ;-)

Optional möchte ich dann (später) noch einbauen, dass man (manuell getriggert) einen vorgegebenen Branch Auf Letztstand heben kann. Das bietet sich für Debugging/Fehlerbehebung an, wo man jemandem sofort was fixen kann, ohne einen Release zu erzeugen.

Wer logische Fehler oder potentielle Probleme findet, immer her damit!

**Comment by Woersty** [comment]
Beim drüber lesen ist mir nix aufgefallen.
Klingt ganz ok soweit.
Teste dann mal später wenns soweit ist.

 Komme kaum hinterher- ihr seid extrem fleißig...

**Comment by mschlenstedt** [comment]
Warum nehmen wir denn nicht den vorhandenen Update Prozess? Das ZIP wird runtergeladen und gespeichert.  Beim anschließenden Reboot wird das Update während des Init eingespielt. Die Updatescripte sind Bashskripte, die als Root ausgeführt werden. Also extrem flexibel. Die Überprüfung der Versionsnummer ist ebenfalls schon integriert. 

Das einzige was fehlt ist die Überprüfung der Versionsnummer mit Überprüfung Prerelease/Release und dem anschließenden Download des ZIPs. Also ebenfalls ein simples Cronscript.

**Comment by christianTF** [comment]
Das wäre kein Problem.
Es kommt immer das ganze Repo herunter (soweit hab ich's schon), die Versionsprüfung ist davor schon drin (das mach ich vor dem Download).


Die ganze Logik mit entpacken usw. hab ich noch nicht. Da hab ich mir die Upgrade-Logik auch noch nicht angesehen.
Das Update erst bei Reboot finde ich nicht so schön, weil man's häufig gar keinen Reboot braucht.

**Comment by christianTF** [comment]
https://github.com/mschlenstedt/LoxBerry-Upgrade-0.2.x/blob/master/upgrade.sh

Das Konzept vom aktuellen System-Upgrade ist schon ganz anders (umgekehrt) als das, das du jetzt für das Plugin-Update implementierst und ich mir auch für LoxBerry vorgestellt habe.

Ein Script für jeden (Pre-)Release soll niemand schreiben müssen. Das müssen wir optional gestalten. 
Den kontrollierenden Code des Updates (das was jetzt das upgrade.sh im Upgrade-Repo macht) müssen wir ins LoxBerry-Repo holen, damit es zentral weiterentwickelt und ggf. per automatischem Update angepasst/korrigiert werden kann.

Im üblichen Fall, wenn nichts an den Linux-Settings geändert werden muss (sondern z.B. nur ein cgi ersetzen), wäre dann der Ablauf zur Erzeugung eines Releases:

- Auf Github auf die "Releases" gehen
- "Draft a new release" drücken
- Versionsnummer eingeben
- Ggf. "Pre-Release" anklicken
- Speichern drücken.

Damit können wir Bugfixes wirklich in Minuten hinausfeuern, wenn wir das wollen.  

Ich würde die jetzige Upgrade-Routine so umbauen, dass das geht. Dann könnte man beim jetzigen manuellen Upgrade auch einen Clone hinaufladen und wäre auf der aktuellen Version.

**Comment by mschlenstedt** [comment]
Ein einfacherer Prozess wäre schon gut - da gebe ich Dir recht. Das alte Update zu erzeugen war immer ein Haufen Arbeit.

BTW: Für die LIBs würde ich mir ein Extra-Update wünschen. So könnte man den LoxBerry immer auf der alten Version belassen (Never touch a running system), würde aber immer aktuelel Libs haben, damit die Plugins immer kompatibel sind. Oder ist das dann alles für den user wieder zu kompliziert bzw. schwer zu verstehen?

**Comment by svethi** [comment]
Ja, die User, das ist immer so ein Thema was ich auch nicht richtig einzuschätzen weiß. Da kommt man mit den einfachsten ausgereiftesten Plugins und dann lies Dir teilweise die Frage durch ;-)

Christian, welches Weihnachten wolltest Du noch gleich releasen? 😂

**Comment by christianTF** [comment]
Ich habe keine so differenzierte Betrachtungsweise Core<-->Module. Wenn eines davon kaputt ist, ist LoxBerry kaputt. Das ist schon zu sehr verstrickt.
Wie macht man die hypothetischen Kompatibilitätstests?
Die User sind mir dabei noch eher egal, aber was sagst du einem Plugin-Entwickler: Die Funktion geht nur, wenn der User nicht nur die Modules, sondern auch den Core aktualisiert?
Ich sehe gerade die Problematik nicht, warum das nicht zusammen gehören soll?

@svethi Wir sind eh fast fertig? ;-) 
Schau Mal die kleine Bug-Liste an, und denk dir alles weg, wo das Problem vorm Bildschirm sitzt :-)

PS: Von so kleinen Buildnummern wie (0.2.) 3 werden wir uns aber verabschieden müssen.

**Comment by svethi** [comment]
@christianTF damit die Liste nicht zu klein wird, habe ich gleich mal was angefügt ;-)

**Comment by christianTF** [comment]
Das zähle ich jetzt einfach mal zu den Bildschirm-Problemen *ggg*

**Comment by christianTF** [comment]
Doku: http://www.loxwiki.eu:80/x/bgR7AQ

Damit auf der "alten" LB31-Basis alles funktioniert, ist folgendes erforderlich:

- LB auf den letzten Stand bringen 
- /opt/loxberry/sbin/setenvironment.sh neu ausführen
- apt-get install libjson-perl 

Was fehlt noch in der Implementierung:

- Cronjobs werden angelegt, aber noch mit den falschen Parametern
- Setzen der BASE.VERSION ist noch auskommentiert
- Erstellen eines richtigen Logfiles (derzeit alles STDERR)
- UI-Update fährt derzeit noch im DRYRUN 
- Logfile-Button im UI
- Update History (File und UI)
- Reboot-Required - Definition eines Pfades (/tmp/) und UI
- Notifications für Update und Auto-Installation (anlegen, auslesen) fehlt noch
- Keine Idee, wie das Handling bei einem fehlerhaften Updateskript (aus mehreren erfolgreichen) aussehen soll. Zu dem Zeitpunkt ist auch das Repo schon ausgetauscht.
- @mschlenstedt Du musst dir das /config/system/update-exclude.system nochmal ganz genau anschauen. Ich habe glaube ich alles Spezifische exkludiert. Mein LB geht jedenfalls noch ;-)

**Comment by mschlenstedt** [comment]
> Keine Idee, wie das Handling bei einem fehlerhaften Updateskript (aus mehreren erfolgreichen) aussehen soll. Zu dem Zeitpunkt ist auch das Repo schon ausgetauscht.

Ich würde das fehlerhafte Update rückgängig machen (geht das?). Beispiel: ich habe LB 0.2.3 und will auf LB 0.4 upgraden.

1. Das Update auf 0.2.4 wird ausgeführt
2. Das Uodate auf 0.2.5 wird ausgeführt
3. Das Update auf 0.4.0 wird ausgeführt. Hier kommt es zu einem Fehler.

Jetzt würde das Update auf 0.4 rückgängig gemacht werden und der LB würde auf 0.2.5 stehen bleiben.

Update-exclude schaue ich mir an. Irgendetwas hatte ich da schon entdeckt. Muss ich nochmal schauen. War nur wegen Magen-Darm die letzten Tage außer Gefecht gesetzt.

**Comment by christianTF** [comment]
Das Mit den Update-Scripts ist nicht ganz trivial.
Das rsync geht direkt auf die neueste Version. Das /opt/loxberry ist schon Release (z.b. 0.4.0), wenn die Update-Scripts dran kommen. Die Scripte muss ich hinterher ausführen, weil es ggf. was ändert, was erst mit dem neuen /opt/loxberry funktioniert.

Es gibt eigentlich nur zwei Wege, um das 100% sauber zu lösen:

1. Die Update-Scripte funktionieren einfach und müssen sehr fehlertolerant implementiert sein.
2. Beim Update werden schrittweise wirklich alle Releases aufsteigend einzeln heruntergeladen und mit rsync und Update-Script installiert.

Das Rückgängig machen eines fehlgeschlagenen Update-Scripts geht auch nicht so einfach, weil ich weiß ja nicht, was dort gemacht wird. Da müsste ich vorher den ganzen Raspberry sichern. Da hört der Spaß auf ;-)

Ich bin für Option 1 (Option 2 wäre mit der Codebasis aber sogar in angemessener Zeit möglich).
Die Update-Scripte müssen alles abfangen, was passieren könnte. Es darf zu keinen Exceptions kommen, jeder einzelne Aufruf muss Fehler melden, muss aber das Script weiterlaufen lassen. Viel `or print STDERR "Could not do ...";` ohne `die`.

PS: Eins ist noch ein wichtiger Punkt: Es werden auch bei "Release" ALLE Update-Scripts, auch von Prereleases, ausgeführt. Für Option 2 müsste ich bei "Release"->"Release" auch alles Prereleases dazwischen installieren. Auch kein Problem, dauert halt länger.
