### ISSUE TITLE
LB Services Widget

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#307]
Es steht ja auch immer wieder auf der Liste ... Verwaltung der der Plugin Daemons.
Ich stelle mir da so die Frage wie wir das angehen wollen. Dienste Verwaltung, da hängt ja schon etwas mehr dran. Im Grunde gibt es ja eine gute Verwaltung im Linux. Nun habe ich gerade selbst festgestellt, dass man da bei der Programmierung doch einige Dinge beachten muss wenn das alles konform sein soll.
Wie stellt Ihr Euch denn so die Dienste Verwaltung vor?

**Comment by christianTF** [comment]
Da gibt es eigentlich noch gar nichts.
Meinst du Linux Dienste oder Plugin-Dienste (daemon)?

**Comment by svethi** [comment]
Ja, ich meine die Plugin-daemons. Da besteht ja auch immer wieder der Wunsch die im Widget auch mal Neustarten zu können. Die Frage ist da ja, soll das stets vom Plugin selbst gemanaged werden? Oder über das letztens besprochene localservices Widget? Oder wolltest Du da tatsächlich rein die LB eigenen Dinge drin haben?

**Comment by christianTF** [comment]
Bezüglich Daemons ist jetzt folgendes geplant:

Die Plugin-Schnittstelle V2 liefert ein sbin-Verzichnis mit, dessen Befehle automatisch im plugin-Sudoers stehen.
Aus einem Pluign-UI-Script (Perl oder PHP) kann man mit 
`system(sudo sbin/restart.sh)` 
zum Beispiel ein restart-Script triggern.

Apropos... https://github.com/mschlenstedt/Loxberry/issues/309

**Comment by svethi** [comment]
Ah, Okay, dann kann sich der Entwickler selber drum kümmern.
Was wolltest Du dann alles in Widget packen?
Apache Port; SSDP enabled/disabled ...?

**Comment by christianTF** [comment]
Mein Bild vor Augen ist ein Services Widget mit NavBar (logisch!)

Ein Tab heißt "Webserver" und beinhaltet (erstmal) den Apache Port https://github.com/mschlenstedt/Loxberry/issues/270
Da könnte später mal SSL dazukommen.

Ein Tab könnte dann SSDP sein.

Oder zu viel des Guten? Dann alles auf eine Seite.

**Comment by svethi** [comment]
Webserver mit eventuell SSL ein Tab geht ja noch in Ordnung, aber ein Tab SSDP an/aus ist vielleicht etwas viel des Guten ;-)
Vielleicht Einer Webserver und erst einmal einer Options oder so

**Comment by christianTF** [comment]
Wie's dir gefällt :-)

**Comment by christianTF** [comment]
@svethi Kann man description.php so umbenennen, dass man gleich sieht, dass das zum ssdp Dienst gehört, oder muss die genau so heißen?

**Comment by svethi** [comment]
kann auch anders heißen denke ich

**Comment by svethi** [comment]
Heißt jetzt ssdpdesc.php, Okay?

**Comment by christianTF** [comment]
Yesss

**Comment by svethi** [comment]
Oh Schreck Christian, was hast Du getan??!
Jetzt muss ich mich erst einmal mit dem Template System beschäftigen ;-)

**Comment by svethi** [comment]
So, jetzt könnt Ihr Euch auslassen ;-)
Services Widget mit PHP ist nach meiner Meinung soweit fertig und daher mache ich das hier mal zu :-)

**Comment by christianTF** [comment]
Funktioniert!

Eine kleinen Vorschlag hätt ich noch dazu:
Es steht immer groß dort, "Everything is ok", und darunter klein, was gerade passiert.
Jedenfalls hab ich das unten dann (als ich am neuen Port war) gar nicht mehr gelesen, und während des "Aufräumens" hab ich mich dann auch gleich per Haus-Klick ins Hauptmenü verabschiedet.

Vielleicht würde es Sinn machen, die jeweilige Überschrift textuell wie einen Wizard zu machen (Schritt 1: Ich tu das, Schritt 2: ich tu jenes, Schritt 3: jetzt räum ich noch zusammen).

Und noch eine Kleinigkeit hab ich:
Bei "The port you've given is already in use." macht es aus meiner Sicht Sinn, wenn du den User beim Button "Continue" wieder zurück auf den Portwechsel bringst. Der User wird vermutlich nicht sagen, "asso, dann mach ich halt was ganz anderes", sondern wird es nochmal probieren wollen :-)

**Comment by svethi** [comment]
Mit der großen Überschrift habe ich auch schon überlegt. Hatte mich dann erst einmal an die Anderen Widgets gehalten.
Wenn da schon steht, dass aufgeräumt wird, wird eh nur wieder auf die lbsystempage verwiesen. Da ist alles durch. Beim vorhergehenden Schritt wäre es schwieriger. Wenn Du da abbrichst und nicht auf weiter drückst, sind ja dann beide Ports aktiv. Wollte zuerst auch automatisch weiterleiten, doch irgendwie macht iOS das nicht mehr. Es wird alles richtig angegeben und der Firefox macht das auch. Daher musste ich dann auf den weiter Button setzen.
Beim Speichern werden beide Ports aktiviert und der Weiter Button verbindet auf den den neuen Port und prüft ob man auf dem gespeicherten Port angekommen ist, löscht aus den Configs die alten Ports und startet den Webserver wieder neu. Wenn Du liest, dass auf geräumt wird, ist alles schon vorbei. Steht da nur um die Zeit zu erklären die gewartet werden soll. Die 10 Sekunden sind eigentlich auch viel zu lang. 5 Sekunden sollten reichen.
Wer weiß was der User so alles macht ;-) der gewünschte Port geht nicht, also lässt er es ;-) Ja, sollte gehen, dass man dann wieder zur Porteingabe kommt.
