### ISSUE TITLE
Git macht micht verrückt

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#308]
Seht doch mal, was der da wieder gemacht hat. Ich weiß auch nicht seit wann da nun wieder ist.
Neuerdings muss ich beim pull einen comment angeben. Bzw. kommt gar dieser Editor. Hab den Vorgegebenen Text gelassen. Jetzt hat der aber tatsächlich bei meinem Push diesen Comment auch wieder hochgeladen und nun steht da Merge ... blah, blah, blah ... wieso kann der denn nicht einfach den Comment von Christian belassen?

**Comment by mschlenstedt** [comment]
Dieses "Merge commit...." kommt bei mir auch. Kannste ignorieren: Das sind die Änderungen von Christian, die bei Dir ins Repo "gemergt" worden sind. Ich übernehme da auch immer den Standardtext.

Wenn Du selbst einen Commit machen willst kannst Du das entweder mit "git commit -m "Meine Nachricht" machen oder Du nimmst "git commit" und der Editor öffnet sich. Dann kannst Du etwas mehr Text eingeben oder Anstriche verwenden etc.

**Comment by christianTF** [comment]
Ja, die Merges sind normal. Ich verwende GitHub Desktop, der macht das immer automatisch ohne dass ich was davon mitbekomme (außer in der History).

**Comment by svethi** [comment]
Ja, wo das herkommt ist mir schon klar, doch ich verstehe den Sinn nicht. Christian fixed da was und setzt den entsprechenden Kommentar. Ist doch klar das wir das mergen müssen. Wir machen dann daran gar nichts und wenn wir dann pushen ist der eigentliche Comment weg. Der Sinn erschließt sich mir bei so einer Zusammenarbeit nicht ;-) Okay, ich ignoriere es einfach
