### ISSUE TITLE
[gollum-0.1] Umlaute bei Usernamen

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#31]
https://github.com/mschlenstedt/Loxberry/issues/4

"Wörsty" als Username geht noch nicht:

"The Username must be 3-20 characters long and consist of alphanumeric characters"

**Comment by Woersty** [comment]
Vorschlag: Füge in den de und en Templates beim Usernamen **data-validation-allowing="\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u00FF"** hinzu.
Hilfetext um ÄÖÜ äöü ß erweitern:
Allowed characters: A-Z a-z 0-9 ÄÖÜ äöü ß

**Comment by mschlenstedt** [comment]
Es war nur im deutschen Template geändert (Änderung von alphanumeric auf letternumeric bei data-validation).

Vermutlich hat sich das englische Template und meine Änderung überschnitten...

**Comment by mschlenstedt** [comment]
Fixed
