### ISSUE TITLE
LoxBerry::Web::readlanguage() ohne HTML::Template

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#312]
Ich würde gerne in einem Skript LoxBerry::Web::readlanguage() verwenden, um Sprachphrases einzulesen. Da es aber ein Kommandozeilen-Skript ist, brauche ich kein Template dazu. Das geht aber aktuell nicht. Ich würde das gerne so verwenden:

```perl
our %SL = LoxBerry::Web::readlanguage(undef);
print $SL{'MYLOXBERRY.WIDGETLABEL'};
````

@christianTF  Könntest Du das noch einbauen?

**Comment by christianTF** [comment]
Bau ich dir ein. In PHP geht das ja schon ;-)

**Comment by christianTF** [comment]
In progress...

**Comment by christianTF** [comment]
Gefixt mit https://github.com/mschlenstedt/Loxberry/commit/e56ba633cae7915e3d27e43ae552d2cf83febf27
für System-Module.

%SL = LoxBerry::Web::readlanguage();

Kann sein, dass ich gleich noch was nach-commite für Plugins, aber fürs System bleibt es wie es ist.

**Comment by mschlenstedt** [comment]
@christianTF 

Danke, aber ich hätte noch etwas zu meckern ;-) Wenn ich reine Commandline-Skripte schreibe, wird bei Verwendung von LoxBerry::Web immer auch CGI.pm mit eingebunden und alle Fehlermeldungen kommen in HTML-Syntax.

Könnte man readlanguage() auch in LoxBerry::System einbinden? Oder bei LoxBerry::Web das Laden von CGI.pm per Parameter unterbinden?

**Comment by mschlenstedt** [comment]
Ansonsten muss ich sagen: Ich tue mich gerade etwas schwer mit den ganzen Neuigkeiten (Module und Templates), was mir früher per Copy&Paste leicht von der Hand gegangen ist dauert nun deutlich länger.

Aber es ist COOL und wenn man sich dran gewöhnt hat um einiges leichter! Man muss nicht jedes Mal das Rad neu erfinden!

**Comment by christianTF** [comment]
Das hab ich auch schon gemerkt, aber das liegt glaube ich nicht an CGI.pm.
Das verwende ich beispielsweise auch in loxberryupdatecheck.pl wo das keine Probleme macht.
In loxberryupdate.pl ist LoxBerry::Web eingebunden, da hab ich auch das Phänomen. 

Irgendwas ist da faul, aber CGI ist es, denke ich, nicht.

Ich suche...

Für den Schnellstart empfehle ich myloxberry.cgi  - das ist ganz einfach gestrickt.
Oder updates.cgi - das ist zwar schon relativ komplex, aber das cgi ist noch überschaubar.

**Comment by mschlenstedt** [comment]
Ist jetzt aber vielleicht auch nicht Prio 1. Passiert ja nur, wenn man noch einen Fehler in der Programmierung hat...

**Comment by christianTF** [comment]
Ich glaube das könnte von https://github.com/mschlenstedt/Loxberry/issues/287 kommen.

Ich kann's aber gerade nicht mehr reproduzieren. Hast du etwas (File im Repo, oder Code Snippet), dass das auslöst?

**Comment by mschlenstedt** [comment]
```perl
#!/usr/bin/perl
use LoxBerry::Web;
print "Hier ist ein "" Fehler
```

Das gibt folgenden Fehler:
```html
[Tue Dec 19 19:52:29 2017] test.pl: String found where operator expected at test.pl line 6, at end of line
[Tue Dec 19 19:52:29 2017] test.pl:     (Missing semicolon on previous line?)
Status: 500
Content-type: text/html

<h1>Software error:</h1>
<pre>syntax error at test.pl line 6, near &quot;print&quot;
Can't find string terminator '&quot;' anywhere before EOF at test.pl line 6.
</pre>
<p>
You can report this error <a target="bugreport" href="https://github.com/mschlenstedt/Loxberry/issues/new">here</a> if you think it is a general problem and not your fault.
</p>
[Tue Dec 19 19:52:29 2017] test.pl: syntax error at test.pl line 6, near "print"
[Tue Dec 19 19:52:29 2017] test.pl: Can't find string terminator '"' anywhere before EOF at test.pl line 6.
```

**Comment by christianTF** [comment]
CGI-Problem ist ein neuer Issue: #330 
Topic dieses Issues ist gelöst.
