### ISSUE TITLE
Services.php - PHP Config_Lite

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#313]
Hi,
Habe mir überlegt das Services exemplarisch in PHP zu machen. Da man da auch wieder an die ini's muss, spiele ich grad mal etwas mit Config_Lite für PHP.
@christianTF muss ich sonst noch was in PHP beachten? Bezüglich der Templates etc. Im Wiki steht immer nur, dass man das so verwendet wie im Perl?!

**Comment by christianTF** [comment]
Das mit der Hilfe f7üür System-Widgets weiß ich nicht, ob das schon geht (glaube nicht). 
Die PHP-Doku ist außer Web glaub ich vollständig, und da gibt es ja nicht viel.
Für System-Widgets habe ich PHP nicht primär gebaut, also lass dich überraschen!

**Comment by christianTF** [comment]
Bezüglich Configfile gibt es diese Dinge zu beachten:

- Das erstellte File muss UTF-8 (ohne BOM) sein.
- Wenn Kommas vorkommen, muss der String unter Double-quotes, sonst macht Config::Simple einen Array daraus. 
- Double-quotes in Stings müssen mit \ escaped werden.
- Bei parse_ini_file muss man den RAW-Modus nehmen, sonst interpretiert PHP einiges als fehlerhaft.
- Beim Zugriff auf den Array aus parse_ini_file muss man immer is_array, is_string usw. machen, weil PHP beim Zugriff auf leere Array-Keys sonst immer Warnings rausschreibt.

Das sind die Erfahrungen, die ich mit parse_ini_file in den PHP-Modulen gemacht hab.

**Comment by svethi** [comment]
@christianTF Du musst mir mal kurz das Template-System im PHP erklären. Ich hatte es beim Überfliegen des Code so verstanden, dass ich LBWeb::head() dann mein Template ($content = new LBWeb::Template("file") ....... $content::output()) und danach LBWeb::foot() mache. Da kommt aber nur ne schwarze, zerhakte Seite raus. Entweder fehlt da noch was, oder das geht tatsächlich bei core-Modulen nicht?

**Comment by christianTF** [comment]
Mach's genau so: http://www.loxwiki.eu/display/LOXBERRY/PHP+functions+to+create+your+webpage+with+LoxBerry+design
Wie gesagt, das ist für Plugins gebaut.
Ein vollwertiges Template-System wie HTML::Template gibts nicht, wozu auch, du steht bei PHP ja mitten im HTML.

**Comment by svethi** [comment]
Ah, um diese Anleitung bin ich wohl erfolgreich herum geschippert. Jetzt wird da langsam ein Schuh draus. Hab das PHP noch nicht abgeschrieben ;-)

**Comment by christianTF** [comment]
Das http://loxberry/admin/plugins/phptest/ hast du dir auch noch nicht angesehen?

Ich wäre auf Whatsapp wenn du willst. Muss sowieso TVOG nebenbei mitschauen.
