### ISSUE TITLE
Synlinks auf Config-Dateien per setenvironment.sh setzen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#315]
setenvironment.sh benutzen, um (die meisten) Aktionen aus http://www.loxwiki.eu:80/x/VoU_AQ zu setzen. @christianTF  hat das für die sudoers schon eingepflegt.

Man müsste nur jeweils prüfen, ob die Aktion eventuell schon ausgeführt worden ist und sie dann überspringen (wenn setenvironment.sh mehrmals ausgeführt wird). Sehr häufig wird das nur die Überprüfung sein, ob das Ziel schon ein Symlink ist oder nicht.

**Comment by christianTF** [comment]
Ich habe eine zweite Datei, ~/sbin/resetpermissions.sh angelegt, die ich beim Update brauche.
Die Datei enthält schon die Rechteänderungen (chmod und chown) aus der Image-Anleitung (beim Übertragen aus der Anleitung trotzdem prüfen).

Das sudoers-File muss owner root:root sein, damit es funktioniert (https://github.com/mschlenstedt/Loxberry/issues/320).
