### ISSUE TITLE
Setup-Assistent sollte auch ohne Miniserver durchlaufen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#316]
Wenn der Miniserver nicht erreichbar ist, sollte der Setup-Assistent trotzdem durchlaufen. Es gab User, die den LoxBerry ohne Miniserver aufsetzen und/oder nutzen wollten.

**Comment by christianTF** [comment]
Abgeschlossen mit dem neuen Assistenten https://github.com/mschlenstedt/Loxberry/commit/e5ec2191e165be55f9a028af319019f0c46eeceb
