### ISSUE TITLE
NETWORK.FRIENDLYNAME not defined.

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#319]
Wenn der Friendlyname nicht gesetzt ist wirft LoxBerry::System immer eine Fehlermeldung aus:

```bash
loxberry@loxberrydev:~/sbin $ ./plugininstall.pl folder=test
[Tue Dec 19 15:35:33 2017] plugininstall.pl: NETWORK.FRIENDLYNAME not defined.
[Tue Dec 19 15:35:33 2017] plugininstall.pl:  at ./plugininstall.pl line 56.
de
```

Könnte man das abfangen?

**Comment by christianTF** [comment]
Das braucht man nicht abfangen, die Meldung werfe ich selbst ;-)

Ich geb es heraus - auch den Apache WEBPORT. Ist noch Debugging Code.
