### ISSUE TITLE
Zugriff aus Perl auf ~/webfrontend/html/tmp/ geht nicht

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#321]
Hi Michael @mschlenstedt 

Du hast ja das ~/webfrontend/html/tmp geändert, dass es auf /tmp/ zeigt.
Ist das ein Softlink?

Bei mir funktioniert der Zugriff per Perl auf /opt/loxberry/webfrontend/html/tmp nicht.

Kannst du mal das hier probieren:
```
#!/usr/bin/perl
my $handle;
open ($handle,'>','/opt/loxberry/webfrontend/html/tmp/LUSTIGESFILE') or die("Cant open");
print $handle "Hallo";
close ($handle) or die ("Unable to close");
```
Und dann schauen, ob das im /tmp/ ankommt?
Bei mir hat er das File irgendwo (irgendein Apache Tempordner) angelegt, aber nicht im /tmp/.

Vielleicht hat das aber auch nur bei mir nicht funktioniert, weil ich den Link auf /tmp/ falsch gemacht hab.

Danke, Christian

**Comment by mschlenstedt** [comment]
Das Skript geht bei mir. Komich - eigentlich gehen SymLinks mit GIT (habe ich zumindest schon öfter gemacht).

Gestern wurde der Link aber von irgendjemanden (eventuell auch Du) durch einen Commit überschrieben. Ich habe ihn daraufhin nochmal neu committed. Versuche mal ihn manuell anzulegen:

`ln -s /tmp/ /opt/loxberry/webfrontend/html/tmp`

**Comment by svethi** [comment]
Christian arbeitet ja nicht direkt im Filesystem sondern kopiert die Dateien nur rüber. Wahrscheinlich muss er die Symlinks dann ja auch selber manuell bei sich anlegen

**Comment by christianTF** [comment]
Richtig - da fehlt meinem LB wahrscheinlich schon irgendwas. Dann bin ich eh beruhigt, wenn's grundsätzlich geht, nur bei mir nicht. 
Ich werde einfach mal ein Update über meinen LB fahren.
