### ISSUE TITLE
Permissions und sudoers

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#322]
Hi,

alle Dateien, die im sudoers-File eingetragen sind, müssen aus Sicherheitsgründen dem User root gehören. Ansonsten könnte jemand, der Zugriff als "loxberry" zum System hat, sich beliebige Rechte verschaffen, indem er eines der Skripte anpasst (z. B. "rm -rf /" reinschreibt und dann per sudoers mit Rootrechten ausführt).

Ich habe das in resetpermissions.sh angepasst. Bitte testet mal, ob damit noch alles funktioniert. Wichtig auch bei eventuellen Upgrades, da diese Dateien dann auch nur von Root überschrieben werden können.

**Comment by svethi** [comment]
Habe mir das mit dem sudoers file noch nicht angesehen, werde da aber auch noch ranmüssen. Liegen die denn grundsätzlich auch unter /opt/loxberry und sind verlinkt, oder muss man ein script schreiben, welches die dann entsprechend einträgt?

**Comment by christianTF** [comment]
Das System-Sudoers ist jetzt ~/system/sudoers/lbdefaults 

Ich werde im Update noch einbauen, dass man nicht nur excluden, sondern auch includen kann.

**Comment by mschlenstedt** [comment]
Erledigt mit Pluginschnittstelle V2.
