### ISSUE TITLE
LoxBerry::System und sudo

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#323]
Hallo @christianTF ,

Deine Update-Skripte laufen doch auch per sudo/root, oder? Wenn ich mein plugininstall.pl per sudo starte, bekomme ich:

```bash
loxberry@loxberrydev:~/sbin/system $ sudo ./plugininstall.pl
Can't locate LoxBerry/System.pm in @INC (you may need to install the LoxBerry::System module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/arm-linux-gnueabihf/perl5/5.24 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at /opt/loxberry/sbin/system/plugininstall.pl line 35.
BEGIN failed--compilation aborted at /opt/loxberry/sbin/system/plugininstall.pl line 35.
```

**Comment by christianTF** [comment]
Das geht bei mir:
```
loxberry@loxberry:~/sbin/system $ sudo ./plugininstall.pl
ERROR: You have to specify 'action=install' OR 'action=uninstall'.
```
Diese sch*** environments....
Hab auch nach Reboot getestet, funktioniert.

Mach mal als root `sudo -V`, da listet er auf, welche Environments er übernommen hat und welche sudo blockiert. Diese Zeile ist verantwortlich, dass sudo die Perl-Variablen nicht stripped: https://github.com/mschlenstedt/Loxberry/blob/9201521f1983a66b91c53f8f0cd7160e2851549c/system/sudoers/lbdefaults#L3

Ich bin schon schwer am überlegen, ob ich die Perl-Module nicht in einen der Pfade, die beim Fehler immer angegeben sind, einlinke. Die sind mit Perl einkompiliert, da gäbe es nie wieder Probleme. Z.b nach /etc/perl/LoxBerry

**Comment by mschlenstedt** [comment]
Da liegt sicherlich der Fehler. Habe ich aber vermasselt - ich habe mich um die Environments lange nicht gekümmert.
