### ISSUE TITLE
Wiki-Anleitung zum lokalen Git Klonen von LB

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#324]
Hi!

Kann wer von euch eine kurze Anleitung im Wiki schreiben, wie man direkt am LB git einrichtet, und klont und pushed usw.

Ich als DAU weiß nicht wie das geht. Wäre fein!

Danke

**Comment by mschlenstedt** [comment]
Kein Problem, mach ich heute Abend.

**Comment by mschlenstedt** [comment]
Ich habe mal schnell etwas heruntergetippt: http://www.loxwiki.eu:80/x/7QR7AQ

Kann man sicher für später ausbauen. Zudem muss es sicherlich noch Korrekturgelesen werden - ich bin kein GIT-Profi und habe da sicherlich nicht immer die korrekten Bezeichnugnen oder Beschreibungen gewählt. Aber ihr werdet verstehen was ich meine :-)

**Comment by christianTF** [comment]
Einfacher als ich dachte!
Dank dir!
