### ISSUE TITLE
Perl / PHP Plugin Variablen gleichziehen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#325]
@mschlenstedt @svethi 

Ich habe jetzt ein bisschen eine Inkonsistenz bei den Variablenbezeichnungen:

- In Perl gibt es die Präfixe `lb....` (z.B. lbplugindir) für Plugins und `lbs...` für Systemverzeichnisse (lbshtmldir). Ein potentielles bin-Verzeichnis fürs System (`lbsbindir`) heißt gleich wie das sbin-Verzeichnis des Plugins (`lbsbindir`).
- In PHP sind die Variablen alle groß geschrieben, in Perl klein.

Glaubt ihr, gibt es ein Problem, wenn ich das jetzt noch gerade ziehe?
Sprich:

- Plugins bekommen das Präfix lbp (statt jetzt lb)
- Die PHP-Variablen werden lowercase ($lbplugindir statt $LBPLUGINDIR).
- Die PHP-Konstanten hingegen bleiben uppercase 
- $lbhomedir ist $lbhomedir bleibt $lbhomedir

Bei PHP bin ich unschlüssig: Die Konstanten **muss** man fast groß lassen, weil die im Code nicht explizit erkennbar sind (z.B. funktioniert dort `echo LBHOMEDIR` --> gibt das Homeverzeichnis aus).

Weil's nur die Pluginvariablen und PHP-Variablen betrifft, glaube ich, dass der größte Aufwand bei meinen eigenen Plugins besteht, und nichtmal da (liefern für 0.23 die Module noch selbst mit)

**Comment by svethi** [comment]
Also ich habe da ja auch was in Verwendung. Muss ich dann auch kontrollieren und anpassen.

**Comment by christianTF** [comment]
Mit der Suche von GitHub hat man's eh schnell gefunden. Ich mach das jetzt einfach.
Entweder jetzt oder nie.

**Comment by christianTF** [comment]
Alle Wiki-Artikel nachgezogen, die die alten Variablen enthalten haben.

Die Übersicht der jetzt gültigen Variablen:

- http://www.loxwiki.eu/display/LOXBERRY/Perl-Modul+LoxBerry%3A%3ASystem
- http://www.loxwiki.eu/display/LOXBERRY/PHP+Module+loxberry_system.php

**Comment by christianTF** [comment]
@svethi  Das sind die Dateien, die ich von dir gefunden habe:

-https://github.com/mschlenstedt/Loxberry/blob/7308fd5d5136e8905674a14facd5a366e5c0bbfb/webfrontend/html/system/ssdpdesc.php

Eh nur eine, und halt das, was noch nicht im Repo ist.
Schließt du ab, wenn du das bei dir nachgezogen hast?

**Comment by svethi** [comment]
Ja, mein Services Widget was ja noch nicjt gepusht ist. Du hast übrigens schon wieder die general.cfg commited und gepusht

**Comment by christianTF** [comment]
Vor 2 Tagen, da hab ich die Update-Settings ergänzt

**Comment by svethi** [comment]
@christianTF hast aber da noch nichts in der Richtung gepusht, oder?

**Comment by christianTF** [comment]
Du meinst wegen dem Services? Nein, nichts.
Die LB-Module mit den neuen Variablen sind schon gepusht: https://github.com/mschlenstedt/Loxberry/commit/a26c76ee17ecfb31ca16d662b37aabfe652e5e6a

**Comment by svethi** [comment]
Wann hast Du die gepusht? Gestern war da beim pull nichts dabei

**Comment by christianTF** [comment]
https://github.com/mschlenstedt/Loxberry/commit/a26c76ee17ecfb31ca16d662b37aabfe652e5e6a

Ist auch in diesem Issue ziemlich weit oben verlinkt

**Comment by svethi** [comment]
Hab jetzt glaube ich angepasst und da Michael eh kein PHP-er ist, mach ich das mal zu
