### ISSUE TITLE
LoxBerry::System::get_binaries(): Chown hinzufügen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#326]
Fehlte noch komplett. In general.cfg habe ich es schon mit eingefügt.

**Comment by christianTF** [comment]
Das hab ich bei der Implementierung schon bedacht:
Du bekommst es zurück, sobald du es in den `[BINARIES]` Block in der general.cfg schreibst.
Die ganzen Keys kommen also nicht im Code vor.
Geht so bei Perl und PHP.

Die beiden Wiki-Artikel sind ergänzt.

**Comment by mschlenstedt** [comment]
Sehr cool!
