### ISSUE TITLE
Auslieferungs-Configs als Vorlagen oder on-the-fly erzeugen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#327]
Ich möchte vorschlagen, dass wir LoxBerry Config-Dateien, die wir im Image als Standard mit ausliefern (z.B. die general.cfg), nicht mehr direkt, sondern als Vorlage mit ausliefern.

Das heißt:

- Im Repo liegt eine general.cfg.default. Die passen wir nach "Herzenslust" an.
- Am LB wird in der initloxberry.sh geprüft, ob es eine general.cfg gibt, und wenn nicht, die general.cfg.default kopiert.
- Das betrifft ggf. noch weitere Dateien wie die Timezones usw.

Der Vorteil ist, wir können die general.cfg.default nach Belieben erweitern, ohne dass sich ein anderer Core-Entwickler fürchten muss. Außerdem könnte man die general.cfg dann endgültig bei Git ausschließen.

Ein anderer, vielleicht noch besserer Weg wäre, dass die general.cfg grundsätzlich _immer_ aus einem Script heraus erzeugt bzw. überarbeitet wird. Das könnte man dann auch fürs Update verwenden.
Realisieren würde ich das als ein Perl-Script, das die general.cfg öffnet (ggf. erzeugt) und alle Standardparameter hineinschreibt, wenn diese nicht existieren. 
Als Option könnte man darin (z.B. via Update-Script) nicht nur nicht existierende Werte erzeugen, sondern sogar Änderungen forcen (z.B. einen Pfad eines Binaries ändern). 
In einem schlauen sub implementiert, wäre das im Erzeugungs- und/oder Updatescript dann pro Parameter eine Zeile.

Die Option 2 gefällt mir sogar besser, weil es eben Update-tauglich ist.

**Comment by svethi** [comment]
Ja, das ist nicht schlecht. Die wirklich notwendigen Dinge kann man ja aus einem Template holen. Ich versuche es bei meinen Scripts immer so zu handhaben dass es auch ohne Eintrag geht und wenn defaults geändert werden, werden die Werte dann angelegt.

**Comment by mschlenstedt** [comment]
Finde ich auch gut. Ich wäre aber dafür irgendwo ein einfaches Default abzulegen welches dann per Skript ins „echte“ General.cfg implementiert wird. Das erleichtert die Pflege.

**Comment by svethi** [comment]
Und schon wieder ist die general.cfg geändert worden und ich muss hier wieder ne hinunherkopier -Orgie und Git index-Updates machen. Da muss unbedingt was passieren, das nervt total.

**Comment by christianTF** [comment]
ich habe das jetzt mal für die general.cfg.default und mail.cfg.default umgesetzt und im .gitignore eingefügt.
Ganz gefällt mir die Lösung mit dem Perl-Modul doch nicht.
Es funktioniert jetzt mal für die beiden Dateien, aber ggf. ändere ich das nochmal, und erweitere es auch um die ganzen .dat Files, die da drin liegen.

**Comment by christianTF** [comment]
Ich habe - wie angedacht - das Perl-Modul wieder gekippt und ein normales pl-File daraus gemacht:
~/bin/createconfig.pl

Es kopiert:

- 

- htusers.dat.default
- securepin.dat.default
- installpin.dat.default
- mail.cfg.default
- general.cfg.default

Bei General und Mail werden die neuen Einträge der dafault-Files übernommen.

Derzeit wird es nur in index.cgi getriggert, wenn eines der Files fehlt.
Man kann das Script auch an der Shell ausführen und es werden alle Dateien verarbeitet (wenn nicht vorhanden, kopiert bzw. die cfgs upgedated).
PS: Leere Einträge in den cfg's werden immer verarbeitet, weil ich zwischen leer und nicht vorhanden nicht unterscheiden kann. Es passt aber, was das Script tut.

WICHTIG: rsync des Auto-Updates schließt im Config/system nur noch Dateien mit der Erweiterung .cfg und .dat beim Syncen aus. Alles andere wird überschrieben.
