### ISSUE TITLE
PHP Module LBSystem::lbwebserverport just return 80

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#328]
Es wird nur Port 80 zurückgeliefert.

**Comment by christianTF** [comment]
Ich bin Grad nicht am PC - kannst du Mal schauen:

https://github.com/mschlenstedt/Loxberry/blob/f8ed1b9feaf158d5fd34d8b03ec4c428ab85e9af/libs/phplib/loxberry_system.php#L518

Die Variable habe ich hier vergessen:

https://github.com/mschlenstedt/Loxberry/blob/f8ed1b9feaf158d5fd34d8b03ec4c428ab85e9af/libs/phplib/loxberry_system.php#L294

**Comment by svethi** [comment]
Das fehlte nicht nur dort, sondern auch bei den Globals.
Hab auch noch einen weiteren Bug durch Zufall gesehen und beseitigt
