### ISSUE TITLE
resetpermissions.sh: Plugin-Verzeichnisse ausschließen?

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#331]
Muss man prüfen - kann sein, dass das eh schon berücksichtigt ist oder irrelevant ist:
in resetpermissions.sh darf es nicht passieren, dass Berechtigungen von Dateien in den plugin-Verzeichnissen grob verändert werden.
Bzw. ist zu überlegen, wie weit wir das machen dürfen, ohne dass wir dadurch vielleich Plugins abschießen.

**Comment by mschlenstedt** [comment]
Ich würde die Pluginverzeichnisse generell ausschließen bzw. anders gesagt nicht mit einbeziehen. Bei der Installation werden Berechtigungen und Ownership korrekt gesetzt. Letztendlich beschränkt sich das aber auch darauf einige Dateien aus Sicherheitsgründen root.root zu setzen und alle *.cgi und *.pl in html und htmlauth auf +x zu setzen.

Was das Plugin nachher macht ist die Verantwortung des Plugins - finde ich.

**Comment by christianTF** [comment]
Derzeit ist ja ein chown -R loxberry:loxberry /opt/LoxBerry drin.
Nach dem rsync mit root muss ich zurücksetzen.
Das muss man dann entsprechend auf mehrere Kommandos für die einzelnen Verzeichnisse aufteilen.

**Comment by mschlenstedt** [comment]
Das würde ich als ersten Schritt auch drin lassen. Daran darf ein Plugin nichts ändern! Anschließend müssen dann nur wieder die einzelnen Dinge auf root.root gesetzt werden. 

Lass uns das fertig machen wenn die Pluginschnittstelle fertig ist. Wird denke ich morgen soweit sein. Dann ist auch klar was root sein muss und was locberry.
