### ISSUE TITLE
PHP parse_ini_file Probleme

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#332]
Irgendwie hat parse_ini_file Probleme mit zumindest, Euren on/off bools. Die werden irgendwie gar nicht interpretiert. Das bringt PHP in Schwierigkeiten, denn wenn man dann das File wieder schreibt, sind diese Werte alle empty.
Ich habe jetzt noch nicht probiert was passiert wenn die gequotet sind, doch kann man die nicht einfach nur als 1/0 schreiben?

**Comment by christianTF** [comment]
Lies mit parse_ini_file im RAW Modus und verwende is_enabled($value) von loxberry_system.php
Ein Bug ist das irgendwie nicht.

**Comment by svethi** [comment]
Mist, stimmt, wenn ich parse_ini_file selbst per RAW nutze, kommt der Wert.
Das Problem ist innerhalb der Config/Lite Class. Diese läd auch per parse_ini_file. Ich bin auch schon soweit das ich weiß dass das interne Array in Ordnung ist. Jetzt arbeiten die mit ArrayAccess und dies scheint das Problem zu erzeugen, denn da kommt die leere Rückgabe. Bin noch auf der Suche

**Comment by christianTF** [comment]
Dann schreib Config/Lite einfach um, dass es RAW liest. Dann kommen nur Strings zurück, oder?
Zumindest das parse_ini_file Array passt dann.

**Comment by svethi** [comment]
Nee, so einfach ist das nicht ;-). Wie gesagt, das interne Array im Config/Lite stimmt wenn man RAW mit angibt. Die implementieren in der Class ArrayAccess. Damit kannst Du direkt $class['Wert']['Wert'] benutzen intern werden dafür definierten Funktionen aufgerufen. Die aber auch nur auf das funktionierende Array zugreifen. Allerdings kommt aus diesem ArrayAccess NULL heraus, obwohl im Wert off steht 👀.
Egal, wenn das interne Array iO ist, habe ich festgestellt, dass das Schreiben dann auch noch passt. Nur der Zugriff auf derartige Werte ist halt speziell. Muss man dann halt in der Doku festhalten.

Dieser Mist hat mich leider wieder sehr viel Zeit gekostet.
