### ISSUE TITLE
Apache not starting at systemstart 

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#333]
Hi, ich habe den Dev-Loxberry mal neu starten müssen und nun startet der Apache nicht mehr automatisch. Ich kann jetzt natürlich nicht sagen seit wann das so ist. Beim Systemstart wird versucht zu starten, doch er steigt mit einer Fehlermeldung zur Zeile 74 der apache2.conf aus. In dieser Zeile wird auf eine Variable verwiesen. Scheinbar stehen diese Variablen zu diesem Zeitpunkt noch nicht zur Verfügung. Starte ich nach dem Sysstart den Apache von Hand neu ist alles iO. Bis auf fehlende Einträge in der Hosts aber das ist nicht schlimm.
Wer hat an der Apache-Conf gedreht?

**Comment by christianTF** [comment]
Ich glaube nicht, dass die Variable wer von uns eingebaut hat, aber es könnte mit dem Umlegen des tmp von @mschlenstedt zu tun haben?
PS: Mein Apache startet, aber ich habe das tmp bisher nicht gefixt.

7138b4e52d146e849ebb0b50ce5a359d13de65aa

**Comment by christianTF** [comment]
@mschlenstedt Wie siehst du deine Resourcen, Noch ein 0.3.2 Image zu machen? Ich glaube, unsere LBs laufen wegen Systemeinstellungen schon ziemlich auseinander, und ein "Neustart" mit 0.3.1 ist schwer.

**Comment by mschlenstedt** [comment]
Mmmhhh, also an der Apache-Konfig habe ich lange nichts geändert. Müssen wir uns mal anschauen.

Ein Image muss auf jeden Fall nochmal kommen. Ich habe in den letzten Tagen arg an den Dateiownern und Berechtigungen rumgeschraubt (wegen der Plugin-Schnittstelle V2). Das müssen wir auf jeden Fall nochmal sauber testen.

Sobald die Schnittstelle steht (bin bereits beim Debugging) kommt ein neues Image zum Testen des Cores. Wir sollten uns dann irgendwann überlegen einen "Feature Freeze" zu machen und nur noch Bugfixes zu machen und vor allem die WebGUI all der ganzen neuen Funktionen zubauen. Da fehlt ja noch einiges bzgl. der Auto-Updates (zumindestens bei den Plugins).

**Comment by christianTF** [comment]
Ich bin am Testen/Debuggen des Autoupdates von LB und werde morgen die ganzen dryrun's rausnehmen. 
Bezüglich Raspberry-Sachen müsste dann Feature-Freeze sein, und alles weitere (z.B. Services von @svethi ) muss dann über Autoupdates kommen (ggf. auch mit Update-Script). Das wäre dann auch gleich der Test, und ich könnte Mal einen zweiten LB damit fahren.
Ab 0.3.2 gehen wir alle Bugs an, die noch offen sind bzw. wir noch finden.
Das wäre danach aus meiner Sicht auch der Zeitpunkt, eine Closed-Beta mit den Plugin-Entwicklern zu machen. Da wird dann eh noch genug herein kommen. Während dieser Phase gehen wir den Wizard an.

**Comment by christianTF** [comment]
Ich habe gerade aufgeräumt (rm -r /opt/loxberry) und mit git clone gezogen, weil mein Auto-Update plötzlich keine Rechte mehr in /tmp hatte.

Mein Apache startet jetzt auch nicht mehr von selbst und muss restartet werden.

**Comment by svethi** [comment]
Ah, OK, hatte schon befürchtet, dass ich mir meinen hier zerschossen habe. Kann aber irgendwie nicht am tmpfs liegen, denn dann kann ja nicht über git geändert werden. Die envvars werden verarbeitet. Irgendwie bekomme ich aber gar keine Fehlermeldung mehr dazu.  Nur das der Start daneben gegangen ist

**Comment by christianTF** [comment]
Ich habe gerade den Symlink `/opt/loxberry/webfrontend/html/tmp` entfernt und wieder ein normales Verzeichnis angelegt (auch `chown loxberry:loxberry tmp`), und alles läuft wieder normal.
