### ISSUE TITLE
BITTE TESTEN: Pluginschnittstelle V2

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#336]
Hallo @christianTF  @svethi 

Könntet ihr bitte mal die neue Pluginschnittstelle testen? Bitte insbesonder darauf achten, ob Dateien an der richtigen Stelle landen und vor allem Permissions und Fileowner korrekt sind? Ich setze jetzt bei der Installation explizit Permissions und Fileowner.

Es sollten alte Plugins (V1.0) als auch neue Plugins (V2.0, https://github.com/mschlenstedt/LoxBerry-Plugin-SamplePlugin-V2-Perl) korrekt installiert werden.

Das WebGUI funktioniert noch nicht, nur Kommandozeile:

Installation:
sudo ~/sbin/plugininstall.pl action=install folder=LoxBerry-Plugin-SamplePlugin-V2-Perl
sudo ~/sbin/plugininstall.pl action=install file=master.zip

Deinstallation:
sudo ~/sbin/plugininstall.pl action=uninstall pid=46ff6e064056e9f364be2b9aa8f691c0
Die PID ist die 1. Spalte aus der plugindatabase.dat.

Bereinigung für use warnings; use strict; fehlt noch.

**Comment by christianTF** [comment]
squeezelite Plugin 0.4.1:

- Die DEPRECIATED Meldungen würde ich nicht als Error bringen, sondern als WARNING. Der User selbst kann ja gar nichts dagegen tun, und wir sagen ja, dass wir Plugin-kompatibel sind, also finde ich ERROR zu viel.

- Bei $ARGV1 ist was anders: Da habe ich im Plugin eine Zeile `find /tmp/uploads/$ARGV1 -type f -print0 | xargs -0 dos2unix -q`, da bekomme ich jetzt `find: ‘/tmp/uploads//tmp/tjmuEQ7f1U’: No such file or directory` - Das $ARGV1 hat bisher nur einen Ordner gebracht, jetzt kommt offenbar der ganze Pfad.

- Im Cron setzt du die Permissions von allen Dateien, nicht nur vom Plugin. So gewollt? 

- Bei '/opt/loxberry/system/cron/cron.d/*' kommt für chown und chmod jeweils ein ERROR, weil dort keine Dateien existieren. Die Fehler kommen dann auch am Schluss bei der Übersicht. Das ist eigentlich ein Nicht-wirklicher-Fehler. (PS: resetpermissions.sh müssen wir auch korrigieren, weil Loxberry Update meldet dessen Aufruf auch mit Fehler wegen der nicht existierenden Dateien)

- Die in meinem Plugin-Install ausgegebenen Tags `<WARNING>`, `<INFO>` und `<OK>` werden an der Shell nicht mehr gestrippt/coloriert (ich weiß aber nicht, ob das eh nicht immer so war)

- Im Logfile im GUI sind meine Meldungen aus den Scripts dann überhaupt weg (z.B. `<WARNING> Please REBOOT your LoxBerry after installation.`).

- Die Fehlerübersicht am Schluss finde ich super!

- Squeezelite funktioniert. Das Gateway funktioniert auch. Beide lassen sich auch per Web wieder neu starten.

**Comment by christianTF** [comment]
Nochwas - ich glaub, das Sichern der Settings beim Update hat nicht mehr funktioniert.
Oder gibt's fürs Update eine andere action=?

**Comment by mschlenstedt** [comment]
Danke für's Testen!

> Die DEPRECIATED Meldungen würde ich nicht als Error bringen, sondern als WARNING. Der User selbst > kann ja gar nichts dagegen tun, und wir sagen ja, dass wir Plugin-kompatibel sind, also finde ich 
> ERROR zu viel.

Stimmt, ich mache Warnings daraus.

> Das $ARGV1 hat bisher nur einen Ordner gebracht, jetzt kommt offenbar der ganze Pfad.

Schaue ich mir an.

> Im Cron setzt du die Permissions von allen Dateien, nicht nur vom Plugin. So gewollt?

Ja, das ist Absicht. cron.d und sudoers ist eine "Schwachstelle" im System. Sobald ich darauf Schreibzugriff habe, habe ich Rootrechte. Daher bügel ich jedesmal die kompletten Berechtigungen wieder drüber.

> Bei '/opt/loxberry/system/cron/cron.d/*' kommt für chown und chmod jeweils ein ERROR, weil dort keine Dateien existieren. 

Ich baue eine Überprüfung mit ein.

> Die in meinem Plugin-Install ausgegebenen Tags <WARNING>, <INFO> und <OK> werden an der Shell nicht mehr gestrippt/coloriert (ich weiß aber nicht, ob das eh nicht immer so war)

Ja, das war schon immer so, weil diese Meldungen aus den Bashskripten des Plugins kommen und nicht geparst werden. Im WebGUI passt das wieder, weil dort die Ausgaben noch einmal geparst werden bevor sie angezeigt werden.

> Im Logfile im GUI sind meine Meldungen aus den Scripts dann überhaupt weg (z.B. <WARNING> Please REBOOT your LoxBerry after installation.).

Das ist mir auch schon aufgefallen. Wenn ich auf der KOmmandozeile bin müsste ich es irdendwie schaffen sowohl nach STDOUT/STDERR auszugeben und zusätzlich quasi als Kopie ins Logfile schreiben. Keine Ahnung ob das überhaupt geht. Im WebGUI gibt's das problem dann nicht. Da kann ich einfach komplett ins Logfile umleiten.

**Comment by christianTF** [comment]
Bezügl. Logfile: Wenn's nur an der Shell fehlt, ist das wurscht. Das ist ja nicht der Standardweg, Plugins zu installieren.

**Comment by svethi** [comment]
Da hab ich ja mal nicht richtig gelesen und die Plugins per WebGUI installiert ;-) Hat funktioniert.

Bezgl. der Meldungen, das geht. Das hab ich auch schon gemacht. Muss ich mal nachsehen. War aber gar nicht so dramatisch.

**Comment by mschlenstedt** [comment]
Kann nochmal getestet werden (nur von der Kommandozeile aus!). Das WebGUI benutzt noch die alte Routine.

zur Installation muss jetzt noch die SecurePIN mit "pin=0000" als Parameter mitgegeben werden. Auslieferungszustand ist "0000".

WebGUI kommt jetzt dran.

**Comment by svethi** [comment]
FAIL: You have to secify the secure PIN for installation.
;-)

**Comment by svethi** [comment]
[1m[31mERROR:[0m Not all file(s) could be installed successfully.
Ähm, ich bin die Liste mal durchgegangen, konnte aber weiter oben nirgends einen Error finden. Nur DEPRECIATED
Wie kommts?

**Comment by svethi** [comment]
Jetzt bekomme ich auch noch gesagt, dass mein Plugin not allowed ist :-)

Komisch, beim Nächsten kommt die Errormeldung zu nicht installierten Dateien nicht. Das Erste funktioniert, das Zweite nicht. verdrehte Welt

**Comment by svethi** [comment]
Übrigens Meldungen auf Bildschirm und in Datei > tee
shellbefehl | tee meldung.txt
wenn Du auch STDERR haben willst shellbefehl 2>&1 | tee meldung.txt

**Comment by svethi** [comment]
Und übrigens ... für locale Test hatte ich /opt/loxberry drin, der aber auskommentiert ist. Ein reines Suchen nach /opt/loxberry ist also nicht korrekt ;-)

**Comment by christianTF** [comment]
Bezüglich /opt/loxberry Suche: Besser als nichts. False-Positives sind dabei nicht so tragisch. Wird bei meinen Plugins auch überall kommen, weil ich überall ein Fallback im Code habe.

**Comment by svethi** [comment]
@mschlenstedt wie kann ich denn jetzt herausfinden wieso der meint dass nicht alles installiert wurde?

**Comment by mschlenstedt** [comment]
Kannst du mal das Log posten? Dann schaue ich mal. Vielleicht ist da auch noch ein Fehler drin.

**Comment by svethi** [comment]
[install.txt.gz](https://github.com/mschlenstedt/Loxberry/files/1607880/install.txt.gz)

Ich vermute mal, dass das an dem cp *.sh Filmes liegt, die ich nicht habe und somit der cp fehlschlägt.
Wenn dem so ist, muss das noch gefixt werden ;-)

**Comment by svethi** [comment]
Habe jetzt auch mal 2 Updates gefahren mit config Rückspielung etc. hat soweit wohl alles geklappt und das 'p' bei secify ist ja auch eingefügt :-)

**Comment by christianTF** [comment]
Ich habe das Sample-Plugin-V2, Dateidatum 07.01. probiert und bekomme "Falsche Architektur".
Bin ich noch/wieder veraltet, oder fehlte das im 0.3.3 Image, oder stimmt was mit der Pi2-Erkennung nicht,

![image](https://user-images.githubusercontent.com/14220265/34750195-15d5c02e-f5a6-11e7-8ab4-691bf083e3e7.png)

 @Woersty PS: Und die class im CSS für CRITICAL ist noch Mist ;-) Deine Spezialität!

**Comment by christianTF** [comment]
Installation Any 0.11

Hier funktioniert das Setup. Was hier komisch ist, ist dass "Finished" kommt, dann die Error-Zusammenfassung, aber dann doch noch ein bissl was, und dann einfach "Goodbye".
Als würde die Reihenfolge nicht ganz stimmen - die finale OK-Meldung sollte meiner Meinung nach ganz unten stehen.

Vielleicht kann man die Erfolgsmeldung (über dem Logviewer) herunter, unter den Logviewer, holen, die ist so unauffällig, ich hab sie erst am Screenshot gesehen.

[any.log](https://github.com/mschlenstedt/Loxberry/files/1617130/any.log)

![image](https://user-images.githubusercontent.com/14220265/34750430-5603b0ce-f5a7-11e7-8fbe-5a54eda10f44.png)
![image](https://user-images.githubusercontent.com/14220265/34750444-6c1899d8-f5a7-11e7-8b26-6a830b7f0817.png)


Und der Loglevel geht mir ab in der Übersicht:
![image](https://user-images.githubusercontent.com/14220265/34750598-2cb5ed44-f5a8-11e7-8547-d3ecc5931be2.png)

**Comment by mschlenstedt** [comment]
Fehlermeldung baue ich um. 

Mit dem Good bye und der Reihenfolge: Das ist unschön - stimmt. Schaue ich mir an.

Schau mal, ob in config die datei "is_raspberry.cfg" liegt. Die fehlte bei mir. Kann sein, dass das Image kaputt ist.

**Comment by Woersty** [comment]
Critical angepasst
