### ISSUE TITLE
Loxberries oder Loxberry‘s

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#337]
@christianTF hat im Wiki die Mehrzahl von Loxberry überall in Loxberry‘s geändert. 

Ich glaube, dass das nicht richtig ist und es müsste Loxberries heißen, oder?

Das Apostrophe wird meiner Meinung nach im Englischen für eine Besitzanzeige verwendet:

This is Peter‘s book. 

Die Mehrzahl von Nomen, die auf y enden, wird meist mit ies gebildet:

One ferry, but a lot of ferries.

Oder?

**Comment by christianTF** [comment]
Ich hab alle Artikel geändert, weil ich das selbst inkonsistent gemacht habe.
Meiner Ansicht nach ist LoxBerry ein Eigenname (wie Peter).
Ich hab auch überall LoxBerry statt Loxberry geschrieben (meine Autokorrektur ändert das sogar schon um ;-) )

We met at Ben’s party.
instead of saying the party of Ben or the weather of yesterday, you can write Ben’s party and yesterday’s weather.

Mir ist es egal, ob so oder so. Ich mag‘s halt gern einheitlich.

**Comment by mschlenstedt** [comment]
Genau wie du im Beispiel schreibst ist es richtig: ist es eine Besitzanzeige, dann muss ein Apostrophe hin:

This is Loxberry‘s GIT repository. 

Aber:

„I have installed several Loxberries“ oder eventuell „I have installed several Loxberry“. Aber kein Apostrophe, da es Mehrzahl ist und keine Besitzanzeige.

Deine Autokorrektur ist kein Maßstab: die glaubt dir alles, wenn du es nur oft genug wiederholst :-)

**Comment by christianTF** [comment]
Es geht eigentlich nicht um Besitzanzeige, sondern um Eigennamen.

englisch Volkwagens oder Volkswagen's?
Canterbury's oder Canterburies? ;-)

PS: "I have installed several Loxberry" ist auf jeden Fall falsch :-)

**Comment by mschlenstedt** [comment]
Du hast recht: irgendwie war ich der Meinung, dass du überall die Mehrzahl geändert hast. Stimmt aber nicht. 

Daher kann das hier zu. Ich schreibe mal noch etwas ins Wiki zum Namen. Dann vergessen wir es nicht :-)

**Comment by christianTF** [comment]
Ich hatte alle LoxBerries auf LoxBerry's geändert (war hauptsächlich in englischen Artikeln).

Jetzt haben wir im Wiki immer noch LoxBerrys und LoxBerry's, wobei in deutsch LoxBerrys sicher richtig ist, im englischen ist es zweifelhaft ob mit oder ohne Apostroph, aber LoxBerries ist jedenfalls sehr komisch, und deswegen ist das jetzt weg.

**Comment by christianTF** [comment]
Bezüglich LoxBerry und Loxberry gibt's auch Inkonsequenzen/Inkonsistenzen.

**Comment by mschlenstedt** [comment]
Ich würde jetzt mal folgende Regeln aufstellen:

- Loxberry und nicht LoxBerry (analog RaspberryPi)
- Die Mehrzahl von LoxBerry ist Loxberries (analog raspberries im Englischen: https://www.dict.cc/englisch-deutsch/raspberry.html)
- Bei Genitiv / Besitzangaben: Loxberry's (https://www.englisch-hilfen.de/grammar/genitiv.htm). Nach neuer deutscher Rechtschreibung ist das auch im Deutschen korrekt.

**Comment by christianTF** [comment]
Die Raspberries finde ich nicht gut. Das Wörterbuch ist da eine schlechte Referenz, weil Himbeeren sind Himbeeren, und Raspberry Pi's sind keine Himbeer Pi's sondern bleiben Raspberry Pi's.
Volkswagen bleibt Volkswagen und wird nicht Folkswagon.
Eigenname ist Eigenname.

Im Englischen schreibt man auch Pi's und nicht Pis.

**Comment by mschlenstedt** [comment]
Aber die Mehrzahl von Eigennamen wird auch nciht mit Apostroph gebildet: https://www.gutefrage.net/frage/englische-mehrzahl-von-namen-mit-oder-ohne-apostroph

Dann müsste man bei vielen Loxberrys eben ohne Apostroph arbeiten und beim Genitiv/Besitz mit Apostroph.

Aber die Mehrzahl von Loxberry ist nicht Loxberry's.

**Comment by christianTF** [comment]
Bezüglich Loxberry/LoxBerry:
Das musst du schnell machen, weil die Libs heißen LoxBerry::System usw. und im Code steht das ungefähr 1000x drin.
Du fährst über den Code drüber, ich mach ein Pre-Release und wir testen gleich das automatische Update.

**Comment by mschlenstedt** [comment]
Das ist blöd. Dann lassen wir es einfach bei LoxBerry und gut ist. Im Logo von Wörsty ist es auch noch so. 

Da steht der Aufwand in keinem Verhältnis zum Nutzen.

**Comment by mschlenstedt** [comment]
Habe es geändert. Ich mache das jetzt zu - gibt jetzt wichtigeres :-)
