### ISSUE TITLE
Bei mir funktionieren cronjobs nicht richtig

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#338]
Ich habe jetzt in `/opt/loxberry/system/cron/cron.01min/` folgenden Softlink erstellt:
`ln -s /opt/loxberry/sbin/loxberryupdate_cron.sh loxberryupdate_cron.sh`

Im File, das ich testweise angepasst habe, steht jetzt:
```
#!/bin/bash
echo hallo >/opt/loxberry/log/system/loxberryupdatecron.log
sudo -n /opt/loxberry/sbin/loxberryupdatecheck.pl cron=1
```
Selbst das echo erstellt kein File.
Manuell ausgeführt natürlich schon.
Versteh ich nicht....
@mschlenstedt Könntest du das mal probieren?

**Comment by mschlenstedt** [comment]
Teste ich nachher. 

Aber schau mal ob dein Bashskript auf ausführbar gesetzt ist. Alles was von dir im Repo ankommt ist meist nicht auf ausführbar gesetzt. Liegt denke ich daran, dass du von Windows aus committest.

**Comment by christianTF** [comment]
Hmmm - dann würde es manuell nicht funktionieren.

**Comment by mschlenstedt** [comment]
Auch wieder wahr. Ich probiere nachher mal. Bin gerade nicht am Rechner.

**Comment by christianTF** [comment]
bei mir funktioniert 
`run-parts /opt/loxberry/system/cron/cron.01min`
schon nicht. Ich schau mal weiter

**Comment by christianTF** [comment]
So ein Mist! run-parts führt nur Dateien ohne Fileextension aus! 
Gibt's ja nicht ;-)

**Comment by christianTF** [comment]
Changed symlinks
https://github.com/mschlenstedt/Loxberry/commit/5072112f1db8ffc9a09a37390257a8114d84b71f
