### ISSUE TITLE
Versionierung

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#339]
@christianTF  Du hattest im Wiki schon etwas zu den Versionsnummern geschrieben (http://www.loxwiki.eu:80/x/bgR7AQ).

Ich habe das jetzt mal in ein "Regelwerk" gepackt: http://www.loxwiki.eu:80/x/YoOO

 Schaust Du es Dir bitte mal an? Passt das so?

**Comment by christianTF** [comment]
Ist das Auto-Update dann immer die 4. Stelle?

Wie schaut das dann aus:
Du released 1.0 mit Image, ich bessere einen Fehler in einem Modul mit Auto-Update als Pre-Release aus, bekommt das 1.0.0.1?
Ich bin gerade überfordert mit der Tabelle, auch mit Stable/Unstable.
Wenn ich nochwas nachfixe per Auto-Update, muss dass dann 1.0.0.3 bekommen, oder darf ich einfach weiterzählen (1.0.0.2)?

LoxBerry auf Loxberry zu ändern, wird interessant.

**Comment by mschlenstedt** [comment]
Zu LoxBerry: 
Ja, habe ich auch schon gesehen... Egal, mit LoxBerry 3.0.0 haben wir alle Stellen gefunden :-) Und die Sourcen mache ich per find+sed :-)

Zur Versionierung:
Ich hatte es mir so gedacht: Du fixt etwas per Auto-Update. Dann wird es erst einmal 1.0.0.1 (fortlaufend!). Wenn Du x Bugs per Autoupdate gefixt hast, z. B. bist Du dann bei 1.0.0.876, entscheiden wir, dass es ein neues Image gibt. Damit wird beim nächsten Fix auf 1.0.1 angehoben. Das wird auch per Auto-update ausgeliefert! Aber ich mache parallel ein neues Image. Dann geht es weiter nur per Autoupdate: 1.0.1.1, 1.0.1.2, 1.0.1.3 usw. Wenn wir ein neues Feature einbauen, dann wird immer die 3. Stelle erhöht, also z. B. 1.0.2. Auch das würde aber sowohl als Image als auch als Autoupdate ausgeliefert werden.

Parallel dazu kann(!) ein Entwicklungszweig eröffnet werden. Der würde 1.1.1 werden (also an der 2, Stelle eine ungerade Nummer). Ansonsten würde es weiter gehen wie oben im Stable. Ich gehe aber mal davon aus, dass es relativ lange kein Entwicklungszweig gibt. Den würde ich nur eröffnen, wenn wir größe Änderungen machen. So wie z. B. jetzt beim Schritt 0.2 zu 0.3

Zudem würde ich vorschlagen, dass Du "der Herr der Releases per Autoupdate" wirst und ich "der Herr der Images". Dann ist auch klar, wer wo was schaltet und released :-)

**Comment by christianTF** [comment]
Das passt! 
Zu einem Image soll es aber auch immer einen Release bei GitHub geben, dessen Versionsnummer identisch mit der general.cfg des Images ist. Sonst wissen wir nicht mehr, wo wir sind. 
Wenn du also einen Release baust, mach auch bei GitHub einen Release (dann ist es kein Pre-Release) mit der gleichen Versionsnummer.

**Comment by mschlenstedt** [comment]
Genauso habe ich es mir gedacht.

**Comment by mschlenstedt** [comment]
@christiantf was sind denn nach deinem Verständnis Pre-Releases?

**Comment by christianTF** [comment]
Alles was kein Release ist? ;-)

Mein Verständnis ist:
Alles was Release oder Pre-Release ist, darf grundsätzlich die Funktionalität nicht brechen.
Pre-Releases können neue Fixes, oder neue Funktionen enthalten, die noch nicht (vollständig) getestet sind.
Wenn neue Features/Fixes in Pre-Releases in Ordnung sind, kommen sie in einen Release.
Bei Github kann man einen Pre-Release auch in einen Release ändern, wenn dieser ausreichend stable ist.

Anfangs würde ich sehr häufig Pre-Releases erstellen, und ggf. nachträglich auf Release ändern.
Wenn zb @svethi die Services fertig hat, wäre das ein Pre-Release. Wenn alles funktioniert, ändert man das später auf Release.

**Comment by mschlenstedt** [comment]
Ah ok. Das heißt ein prerelease und ein release könnten theoretisch die gleiche Versionsnummer haben?

**Comment by christianTF** [comment]
Genau. Zb. kommt etwas Neues in einem Prerelease. Man bessert noch was nach und macht einen neuen Prerelease. Wenn der dann passt, kann man ihn zum Release machen
