### ISSUE TITLE
Apache client denied by server configuration

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#340]
```
[Tue Dec 26 16:26:26.845841 2017] [access_compat:error] [pid 924] [client 192.168.0.199:64948] AH01797: client denied by server configuration: /opt/loxberry/webfrontend/htmlauth/system/tools/logfile.cgi, referer: http://loxberry/admin/system/tools/logfile.cgi?logfile=system/loxberryupdate/20171226_161844_check.log&header=html&format=template
[Tue Dec 26 16:26:26.846261 2017] [access_compat:error] [pid 921] [client 192.168.0.199:64950] AH01797: client denied by server configuration: /opt/loxberry/webfrontend/htmlauth/system/tools/logfile.cgi, referer: http://loxberry/admin/system/tools/logfile.cgi?logfile=system/loxberryupdate/20171226_161844_check.log&header=html&format=template
```
Das bekomme ich auch bei anderen Sachen, z.B. beim ajax-config-handler

**Comment by christianTF** [comment]
Ich glaube, das ist auch eine Nebenwirkung vom Symlink tmp im ~/webfrontend/html

**Comment by christianTF** [comment]
Nein, das hängt doch nicht zusammen - kommt immer noch.

**Comment by svethi** [comment]
Stimmt, die Meldung war mir auch schon einmal aufgefallen, doch irgendwie geht ja doch alles.

**Comment by mschlenstedt** [comment]
Irgendetwas müllt da auch ganz schön das Error-Log voll. Sieht mir so aus als ob das aus den Header-Dateien kommt:

```
[Wed Dec 27 10:54:38 2017] index.cgi: Use of uninitialized value $R::form in string ne at /opt/loxberry/webfrontend/htmla
== head == prints html head including <body> start =================

Detected language: de
main::templatetitle:
friendlyname:
[Wed Dec 27 10:54:38 2017] index.cgi: Use of uninitialized value $R::form in string ne at /opt/loxberry/webfrontend/htmla
== pagestart == prints page including panels =================

Detected language: de
friendlyname:
-- SYSTEM Help Template --
We are in LEGACY help mode
templatepath:
[Wed Dec 27 10:54:38 2017] index.cgi: Help template $templatepath is empty - continuing without help.
[Wed Dec 27 10:54:38 2017] index.cgi:  at /opt/loxberry/webfrontend/htmlauth/system/index.cgi line 292.
template_title:  LoxBerry Toolbox <span class='hint'>V0.3.1</span>
helplink:       http://www.loxwiki.eu/display/LOXBERRY/LoxBerry
Home string: Home
```

**Comment by mschlenstedt** [comment]
@christianTF  Kann es sein, dass Du soetwas in der Art in den Libs verwendest? http://perldoc.perl.org/5.8.9/CGI/Carp.html

Ich kriege die Meldungen nicht weg, obwohl ich in der Apache Config schon das Errorlevel auf "emerg" gesetzt habe.

**Comment by christianTF** [comment]
Ja, das muss es sein.
Ist das gleiche wie die HTML-Fehlermeldungen in LoxBerry::Web.
Ich schau mir das an.

**Comment by christianTF** [comment]
Es sind (außer dem Carp) Noch haufenweise Debug-Code im LoxBerry::Web.
Da miste ich auch aus.
#342

**Comment by christianTF** [comment]
Ich hab jetzt CGI::Carp aus der Web.pm rausgehaut, und der Fehler kommt noch immer.

Lt. Internet kommt der Fehler, wenn man in .htaccess Dateien oder der Apache Config alte und neue Rechtevergabe mischt. 
Das Apache-File ist ja von Jessie mitgenommen, vielleicht hat's doch da drin was.

Mit dem Entfernen von CGI::Carp bekomm ich es jedenfalls nicht weg.

**Comment by mschlenstedt** [comment]
Irgendetwas haut bei euch nicht hin. Ich habe den Fehler nicht!

Wartet mal das neue Image ab. Dann schauen wir weiter.
