### ISSUE TITLE
LoxBerry Update: Keine Verbindung zu GitHub / Please wait bleibt stehen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#343]
Das müssen wir debuggen, bevor Michael das neue Image erstellt.

**Bei Fehler 500 / https:://api.github.com:**
Prüfen, ob nach Re-check was geht oder nicht.
Prüfen, ob das mit curl am LB funktioniert (loxberry und root).

**Bei "Please wait" bleibt stehen:**

1. Mit F12, Network den ajax_config_handler.pl Request heraussuchen und schauen, ob und welchen Response es gegeben hat. Da müsste ein JSON zurückkommen. Wenn da kein JSON sondern was anderes kommt, oder vor oder nach dem JSON irgendwas falsches dortsteht, dann bricht jQuery ab und es wird nie was angezeigt.

2. Im apache2 Errorlog schauen, ob es irgendwelche Fehler. Der ajax_config_handler.pl ruft loxberryupdatecheck.pl auf, und das liefert dann das JSON zurück.

PS: Der Fehler 500 wird bereits vom loxberryupdatecheck.pl als Fehler-JSON zurückgeliefert, d.h. zumindest der AJAX-Request ist erfolgreich durch. Bleibt nur die Frage, warum loxberryupdatecheck.pl nicht zu Github kommt.

**Comment by christianTF** [comment]
Ich habe gerade noch commited, dass er fürs Holen der Releaselist drei Versuche macht.

**Comment by svethi** [comment]
Das ist eine gute Frage. Ich habe nun mal meine Plugins installiert und CalDAV und fritzlox, mehr habe ich nicht getestet, laufen nicht.
Ich nutze bei CalDAV IO::Socket::INET um die lokale IP zu bekommen. Das funktioniert nicht mehr. Das IO::Socket::INET wird nicht geladen und daher scheitert das nachfolgende $sock->sockhost();
Ich vermute beim Fritzlox ein ähnliches Problem. Irgendwie vermute ich mal, dass hier auch das Updateproblem zu suchen ist. Der LWP::UserAgent scheint hier ja ebenso ein Problem zu haben. Curl funktioniert problemlos.

**Comment by svethi** [comment]
Kannst Du mal bei Dir das CalDAV4Lox installieren und sehen ob Du die Pluginseite bekommst?

**Comment by christianTF** [comment]
WhatsApp?

**Comment by christianTF** [comment]
Startseite geht bei mir

**Comment by christianTF** [comment]
Hab mit dem neuen Installer installiert

**Comment by christianTF** [comment]
@mschlenstedt @svethi 
Da bin ich gerade darüber gestolpert!
Nachdem Michael die Apache Config bereinigt hat, muss man neu das ~/sbin/setenvironment.sh ausführen und Apache restarten.
In der Apache-Config werden explizit die lokalen Environments an Apache durchgereicht.

Ob das was mit dem Update zu tun hat, weiß ich nicht, jedenfalls war mein Apache beleidigt, und resetpermissions.sh via Apache hat $LBHOMEDIR nicht mehr gesehen.

**Comment by mschlenstedt** [comment]
Bei mir läuft setenvironment.sh überhaupt nicht mehr. ich kriege nur "segfaults" beim Aufruf von awk:
```
root@loxberrydev:~# cd /opt/loxberry/sbin/
root@loxberrydev:/opt/loxberry/sbin# ./setenvironment.sh
awk: fatal error: internal error: segfault
./setenvironment.sh: line 6: 15008 Aborted                 awk -v s="LBHOMEDIR=$LBHOME" '/^LBHOMEDIR=/{$0=s;f=1} {a[++n]=$0} END{if(!f)a[++n]=s;for(i=1;i<=n;i++)print a[i]>ARGV[1]}' /etc/environment
awk: fatal error: internal error: segfault
./setenvironment.sh: line 10: 15009 Aborted                 awk -v s="LBPHTMLAUTH=$LBHOME/webfrontend/htmlauth/plugins" '/^LBPHTMLAUTH=/{$0=s;f=1} {a[++n]=$0} END{if(!f)a[++n]=s;for(i=1;i<=n;i++)print a[i]>ARGV[1]}' /etc/environment
...
```

@christianTF  Ich habe gestern noch die php.ini ins LoxBerry-Systemverzeichnis verlegt. Wollen wir das mit /etc/php/7.0/cli/conf.d/20-loxberry.ini auch so machen?

**Comment by mschlenstedt** [comment]
Könnte sein, dass ich ein ganz anderes Problem habe :-( Sieht so aus als ob meine SDKarte zerschossen ist:

```
loxberry@loxberrydev:/ $ ls
-bash: /bin/ls: No such file or directory
loxberry@loxberrydev:/ $
```

**Comment by mschlenstedt** [comment]
@christianTF  Kann es sein, dass LWP::UserAgent am HTTPS scheitert? Ich kann es ja gerade nicht testen, aber Du könntest mal probieren das zu debuggen bzw. in einem kurzen Testskript zu versuchen. Ich hatte mal so einen Fall und musste diverse Verifications rausnehmen;

```
$ua = LWP::UserAgent->new(ssl_opts => { verify_hostname => 0 });
```

**Comment by christianTF** [comment]
Segfault hatte mal wer im Forum, da war die SD platt.

Bezüglich https:
Bei mir geht's, bei euch nicht, deswegen würde ich erstmal sagen, am Code selbst liegt es nicht.

Wo die PHP-Config liegen, da habe ich keine Präferenzen.

**Comment by christianTF** [comment]
Es kann aber wirklich mit SSL und UserAgent zu tun haben, wie ich lese. Hab was gelesen dass Loadbalancer was schlucken könnten, und ich bin wahrscheinlich in einem anderen Netz/ Infrastruktur wie ihr.
Ich kann's halt schwer testen wenn's bei mir funktioniert.

Das mit der SD war ein Wink mit dem Zaunpfahl *gg*

**Comment by svethi** [comment]
Irgendwie bin ich der Meinung, dass wir alle mal den DevLox neu aufbauen müssen. Da gibts irgendwelche Diffs und es passt alles nicht mehr zusammen. Des Weiteren überlege ich es so zu machen wie Christian und in einer anderen Struktur zu entwickeln um die git Problematik zu umgehen, auf der anderen Seite hat man dann gewisse Anpassungen nicht immer aktuell

**Comment by christianTF** [comment]
Für LBUpdate ist es ohne zwei Strukturen gar nicht gegangen (ohne zweiten LB), weil das Update alles neue einfach plättet. 
Und Settings in Raspbian kommen so oder so nicht an (bei mir garnicht, bei euch nur halb). 
Ich gehe immer die commit-Liste durch und ziehe nach, was wichtig ist (z.B. Sprachfiles usw.).
Wenn z.B. Michael einen SymLink in /etc/ setzt, dann fehlt der überall.

Für Updates müssen dann konsequent solche Änderungen gescriptet werden in Update-Scripts.

**Comment by mschlenstedt** [comment]
@christianTF  Kannsz Du mir mal den Inhalt von /etc/php/7.0/apache2/conf.d/20-loxberry.ini posten?

**Comment by christianTF** [comment]
/etc/php/7.0/apache2/php.ini
[php.zip](https://github.com/mschlenstedt/Loxberry/files/1591141/php.zip)

**Comment by christianTF** [comment]
Geht Updates mit LB0.3.2 jetzt bei euch?

**Comment by svethi** [comment]
Geht jetzt scheinbar.
