### ISSUE TITLE
Plugin-Installation: Warnings bei /opt/loxberry

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#346]
Das Verwenden von hardcoded /opt/loxberry ist ja nicht gewünscht.
Cool wäre - wenn das geht - eine Text search über alle Textfiles des Plugins während der Installation, ob dort hardcoded /opt/loxberry vorkommt, und entsprechende Warnings im Log. (evt. mit Link zu den Wiki-Artikeln)
Das hilft auch Plugin-Entwicklern beim Testen.

Auch die Plugin-Entwickler müssen hier dynamisch werden, sonst ist das ein ewiges Problem mit kleinsten Anpassungen der Verzeichnisstruktur.

**Comment by mschlenstedt** [comment]
Müsste relativ einfach gehen. Ich probiere das mit einzubauen.

**Comment by svethi** [comment]
Grep macht sowas
