### ISSUE TITLE
libossp-uuid-perl in Image

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#347]
Wird benötigt von ssdpd

Fehlt in 0.3.2

**Comment by svethi** [comment]
Nö, eigentlich libdata-uuid-perl steht aber auch in dem einen Report den Du geschlossen hast, oder wurde data jetzt durch ossp

**Comment by mschlenstedt** [comment]
Ach, das libdata-uuid-perl hatte ich darin ganz überlesen. Hatt nur das libio-irgendwas installiert.

**Comment by svethi** [comment]
Wie hast du das festgestellt? Finde ich witzig ;-)

**Comment by mschlenstedt** [comment]
Ich habe ein neues Image und im syslog poppen ein Haufen Fehlermmeldungen auf. Die arbeite ich gerade alle ab.

Aber der Apache macht mich wahnsinnig. Ich bin jetzt soweit, dass es daran liegt, das wir /tmp, /var/tmp usw. in die RAMDISK geschoben haben. Das mag der irgendwie nicht.

**Comment by christianTF** [comment]
Das hatte ich ja schon festgestellt mit dem tmp Link.

**Comment by svethi** [comment]
Den Eindruck hatte ich auch. Bzw. kommt es mir so vor als werden die RAM Disks zu spät erstellt.

**Comment by svethi** [comment]
Vllt mal dem Apache sagen, dass er erst ganz am Ende starten soll
