### ISSUE TITLE
LightHTTPD: Please test

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#349]
Im neuen Image 0.3.2 ist der Lighttpd standardmäßig aktiviert. Bitte mal sowohl PHP als auch CGI testen. Bei Perl habe ich FastCGI noch nicht aktiviert. 

Ist noch nicht alles zu Ende konfiguriert (es fehlen z. B. noch die Envars), aber das meiste sollte gehen. Auch der Apache2 läuft nun hoffentlich wieder.

Man kann zwischen Apache und LightHTTPD wechseln:

Apache:
service lighttpd stop
update-rc.d -f lighttpd disable
update-rc.d -f apache2 defaults
systemctl enable apache2

Lighttpd:
service apache2 stop
update-rc.d -f apache2 disable
update-rc.d -f lighttpd defaults
systemctl enable lighttpd

**Comment by christianTF** [comment]
Bootet leider nicht (Pi2/Sandisk Extreme 32GB, also das gleiche wie für das 3.1 Image).
Muss Mal schauen, ob ich den Pi auf den Schirm bekomme. 
Es leuchtet kurz grün, dann geht das rote LED kurz aus und wieder an, und dann bleibt er mit rotrr Led stehen. Als würde er nach der Boot-Partition crashen.

**Comment by christianTF** [comment]
Bildschirm:
Erst kommt das Regenbogen-Bild, dann bleibt zeigt er 4 Raspberries an und bleibt dort stehen.
Ich kann dort auch was tippen, aber keine Kommandos oder so (zeigt das einfach an).

**Comment by christianTF** [comment]
Anderer PC, anderer Card Reader, gleiches Problem :-(

**Comment by christianTF** [comment]
Und ich habs auch schon gefixt:

cmdline.txt neu:
```dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet init=/usr/lib/raspi-config/init_resize.sh```

cmdline.txt alt:
```dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=37665771-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet init=/usr/lib/raspi-config/init_resize.sh```

Er kommt offenbar mit der PARTUUID nicht klar.

**Comment by christianTF** [comment]
/bin/createconfig.pl ist nicht +x, deswegen schlagen beide Webserver auf.
PS: Korrektur, schlagen nicht auf. Mein Fehler, hatte gleich die general.cfg gelöscht. Ein resetpermission bei einem Update behebt das dann eh.

**Comment by christianTF** [comment]
@mschlenstedt Wie schaltet man FastCGI für Perl ein? Damit lighttpd wenigstens einen Vorteil hat.

**Comment by christianTF** [comment]
Lighttpd startet bei mir beim Reboot nicht. Muss ich manuell starten, wie wir es kurz bei Apache hatten.
Lighttpd schreibt bei mir nichts ins :/opt/loxberry/log/system/lighttpd/error.log

**Comment by mschlenstedt** [comment]
Hast du die GIT Quellen schon gepullt? Ich glaube ich hatte im Image gestern noch etwas an der Config geändert ohne zu pushen.

Ansonsten kommentiere bitte mal die tmpfs-Einträge aus /etc/fstab aus.

**Comment by christianTF** [comment]
`systemctl enable lighttpd` scheint gefehlt zu haben bei deiner Anleitung zum Hin- und Herswitchen. 
Jetzt tut's

**Comment by christianTF** [comment]
lighttpd: Definitiv fehlt Scripts, die übers Web aufgerufen werden, wieder die Environments.

```
INFO: Restoring permissions of /opt/loxberry of your LoxBerry...
Variable LBHOMEDIR is empty. Exiting.
```
D.h. resetpermission.sh über Web hat keine Environment.

**Comment by mschlenstedt** [comment]
Environments fehlen noch. Hatte ich oben geschrieben. 

Service enable dachte ich wird mit Update-rc.d gemacht....

**Comment by christianTF** [comment]
Bei Debian nicht mehr in den letzten Jahren --> systemd

**Comment by mschlenstedt** [comment]
Habe jetzt auch das Image das erste mal gestartet. lighttpd ist direkt nach dem Booten gestartet. Sollten wir mal beobachten. Vielleicht nur ein Thema beim Umschalten zwischen Apache und lighttpd?

**Comment by christianTF** [comment]
Wahrscheinlich.

**Comment by mschlenstedt** [comment]
Ich habe jetzt etwas getestet und ergänzt:

1. Environments

setenvironments.sh setzt jetzt die Environments auch beim lighttpd. Bitte mal testen, ob die Variablen jetzt da sind.

2. FastCGI 

FastCGI funktioniert auch mit Perl, aber irgendwie passt das mit den Modulen noch nicht. Es kommen keine Language Phrases an. Vermutloch auch wieder irgend so ein Problem mit den Environments. FastCGI für Perl funktioniert über ein dispatch-File (liegen in ~/system/lighttpd/), welches das Original-CGI über FastCGI ausführt. Ich habe zwei verschiedene getestet, aber bei beiden funktioniert die Übersetzung nicht. Ich kriege im Error.log folgende Meldungen:

```
2017-12-30 23:00:59: (log.c.217) server started
2017-12-30 23:01:18: (mod_fastcgi.c.2543) FastCGI-stderr: [Sat Dec 30 23:01:18 2017] dispatch.fcgi: ERROR: Could not read any language phrases.
2017-12-30 23:01:18: (mod_fastcgi.c.2543) FastCGI-stderr: [Sat Dec 30 23:01:18 2017] dispatch.fcgi:  at /opt/loxberry/webfrontend/htmlauth/system/index.cgi line 88.
2017-12-30 23:01:18: (mod_fastcgi.c.2543) FastCGI-stderr: [Sat Dec 30 23:01:18 2017] dispatch.fcgi: Use of uninitialized value $SL{"COMMON.LOXBERRY_MAIN_TITLE"} in string at /opt/loxberry/webfrontend/htmlauth/system/index.cgi line 90.
2017-12-30 23:01:18: (mod_fastcgi.c.3574) child exited: 0 unix:/tmp/cgi.socket-0
```

Jetzt habe ich erst einmal keine Lust mehr zu suchen ;-)

Wenn ihr FastCGI testen wollt, folgendes ausführen:
```
lighty-disable-mod cgi
lighty-enable-mod fastcgi-perl
service lighttpd force-reload (als root)
```
Rückgängig machen:
```
lighty-enable-mod cgi
lighty-disable-mod fastcgi-perl
service lighttpd force-reload (als root)
```

**Comment by christianTF** [comment]
Passt, danke fürs Testen. 
Das mit FastCGI schau ich mir mal an, wenn Zeit ist.

**Comment by christianTF** [comment]
Environments funktionieren nicht. 
Ich hab jetzt einen Testaufruf erstellt, siehe https://github.com/mschlenstedt/Loxberry/commit/addc82285d114392a41df5856b835eb9adf8014a

Mit Apache hab ich einige Nächte verbracht, bis es endlich funktioniert hat. Irgendwie hab ich überhaupt keinen Bock mehr, wieder von vorn zu beginnen. Vielleicht findet's wer schnell heraus.

**Comment by christianTF** [comment]
Environments funktionieren jetzt - ich war gerade am Verzweifeln....

Für die Zukunft, hier ein Testaufruf:
http://loxberry/admin/system/tools/ajax-config-handler.cgi?action=testenvironment

aus commit https://github.com/mschlenstedt/Loxberry/commit/addc82285d114392a41df5856b835eb9adf8014a

**Comment by mschlenstedt** [comment]
Kann ich verstehen. So ging es mir nach 3 Tagen Apache2 debugging ohne vernünftige Fehlermeldungen und Suche in 1000 aufgesplitteten Configfiles.

**Comment by mschlenstedt** [comment]
FastCGI: Die Variablen werden laut Deinem Testskript korrekt gesetzt:

![31-12-_2017_08-13-12](https://user-images.githubusercontent.com/16830799/34460025-7ef5050c-ee02-11e7-81b0-79730e38caee.jpg)

Trotzdem meckert er, dass er keine Language Phrases lesen kann und ein paar andere Fehler bzgl. shared variables:

```
2017-12-31 08:15:38: (log.c.217) server started
2017-12-31 08:15:46: (mod_fastcgi.c.2543) FastCGI-stderr: [Sun Dec 31 08:15:46 2017] dispatch.fcgi: Variable "$sversion" will not stay shared at (eval 5) line 281, <DATA> line 1.
2017-12-31 08:15:46: (mod_fastcgi.c.2543) FastCGI-stderr: [Sun Dec 31 08:15:46 2017] dispatch.fcgi: Variable "$template_title" will not stay shared at (eval 5) line 282, <DATA> line 1.
2017-12-31 08:15:46: (mod_fastcgi.c.2543) FastCGI-stderr: [Sun Dec 31 08:15:46 2017] dispatch.fcgi: Variable "$helplink" will not stay shared at (eval 5) line 295, <DATA> line 1.
2017-12-31 08:15:46: (mod_fastcgi.c.2543) FastCGI-stderr: [Sun Dec 31 08:15:46 2017] dispatch.fcgi: Variable "$helptemplate" will not stay shared at (eval 5) line 295, <DATA> line 1.
2017-12-31 08:15:46: (mod_fastcgi.c.2543) FastCGI-stderr: [Sun Dec 3
2017-12-31 08:15:47: (mod_fastcgi.c.2543) FastCGI-stderr: 1 08:15:47 2017] dispatch.fcgi: ERROR: Could not read any language phrases.
2017-12-31 08:15:47: (mod_fastcgi.c.2543) FastCGI-stderr: [Sun Dec 31 08:15:47 2017] dispatch.fcgi:  at (eval 5) line 88.
2017-12-31 08:15:47: (mod_fastcgi.c.2543) FastCGI-stderr: [Sun Dec 31 08:15:47 2017] dispatch.fcgi: Use of uninitialized value $Embed::opt::loxberry::webfrontend::htmlauth::system::index_2ecgi::SL{"COMMON.LOXBERRY_MAIN_TITLE"} in string at (eval 5) line 90.
2017-12-31 08:15:47: (mod_fastcgi.c.3574) child exited: 0 unix:/tmp/cgi.socket-0
```

Wenn ich das richtig sehe müsste das Problem irgendwo um Zeile 467 in ~/libs/perllib/LoxBerry/Web.pm liegen.

**Comment by christianTF** [comment]
Da Stimmt was nicht, weil lt. Output des Tests die sbin/testenvironment.pl und sbin/testenvironment.sh gar nicht aufgerufen wird.
Hast du das sudoers/lbdefaults nachgezogen und alles +x?

**Comment by christianTF** [comment]
![screenshot_2017-12-31-08-42-32](https://user-images.githubusercontent.com/14220265/34460131-a299d68c-ee06-11e7-906a-c7c7b1114c82.png)

**Comment by svethi** [comment]
Übrigens funktioniert in der command.txt schon das PARTUUID, doch die ID ist falsch. In der fstab steht die richtige. Habe das gerade mal bei mir getestet. Hab den Dev jetzt wieder auf ne Platte verfrachtet :-)

Jetzt kann ich mir die Sachen mal ansehen.

**Comment by christianTF** [comment]
Bezügl. partuuid ist die Frage, ob die dann bei jedem anders ist oder woran's liegt

**Comment by christianTF** [comment]
FastCGI: ich weiß nicht in welchem Log diese Logeinträge stehen, so kann ich nichts fixen. Ich bekomme auch keine Translations, aber auch keine Fehler. Zumindest weiß ich nicht, wo die stehen.

**Comment by mschlenstedt** [comment]
Ja, die ändert sich nach der Installation. 

Wir nehmen deine Lösung. Damit gehts immer. So war das früher vor stretch auch.

**Comment by svethi** [comment]
Glaube nicht, dass die bei jedem anders ist. In der fstab steht die ja richtig drin. In der command.txt nicht. Kann es sein, dass beim resizefs die ID geändert wird und das Script dann die richtigen ID's in die fstab schreibt??

**Comment by mschlenstedt** [comment]
Ich schließe das hier mal. Bitte Bugs in separaten Issues posten.
