### ISSUE TITLE
Delete Minisever not working

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#35]
Delete Miniserver geht nicht.

**Comment by mschlenstedt** [comment]
Geht bei mir sowohl im DE als auch EN Template (Browser: Chrome).

Kannst Du das bitte nochmal testen?

**Comment by Woersty** [comment]
Delete geht auch, aber das Abspeichern nicht. Außerdem würde ich es besser finden, wenn man einen Miniserver gezielt löschen kann. Also einen Delete Button hinter jedem Miniserver-Eintrag.

**Comment by mschlenstedt** [comment]
Abspeichern nach einem Delete geht bei mir auch (gerade nur DE-Template getestet).

Einen Miniserver gezielt abzuwählen hatte ich erst vor, dann würde sich aber im Config-File config/system/general.cfg jedesmal die Nummerierung ändern. Eventuell kommen dann aber später Plugins, die die Daten aus dem Config-File nutzen, nicht damit klar.

Ich habe mich daher dagegen entschieden - so oft kommt das Hinzufügen bzw. Löschen von miniservern in den Installationen nicht vor, sodass man, denke ich, damit leben kann.

**Comment by Woersty** [comment]
Du wirst lachen, den Gedanken hatte ich auch schon. Dann muss man halt den letzten notfalls an die Stelle schreiben wo einer gelöscht wird und fertig. Mach zu.

**Comment by Woersty** [comment]
Achso - wollte ja noch das mit dem Delete mal testen

**Comment by mschlenstedt** [comment]
Dann laß' ich es noch offen ;-)
