### ISSUE TITLE
LoxBerry Update: Muss jetzt aus der general.cfg.default lesen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#350]

**Comment by christianTF** [comment]
...und createconfig.pl aufrufen

**Comment by svethi** [comment]
Hat das was damit zu tun, dass im Log Warnings stehen, dass Variablen nicht gesetzt sind?

**Comment by christianTF** [comment]
Welches Log? Welche Variablen?

Das hat damit zu tun, dass die general.cfg grundsätzlich nicht mehr mitgeliefert werden muss/soll, sondern nur noch die general.cfg.default.
Die general.cfg.default ist dann die von uns gepflegte Standardkonfiguration, und der individuelle LB hat die general.cfg. Bei jedem Update ziehen wir die neuen Settings der default in die cfg rüber.

**Comment by christianTF** [comment]
Fixed with https://github.com/mschlenstedt/Loxberry/commit/7460a604bac5df80d1661964dfceed224d7db769
