### ISSUE TITLE
Port-Wechsel: Apache2 und lighttpd

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#352]
Hallo Svethi,

ich will Dir da nicht im services.php rumfummeln (ich kann auch kein PHP :-)), aber ich würde es so machen:

**1. Prüfung, _bevor_ Port gewechselt werden soll:**

Testen, ob der Apache läuft mit: 

`service apache2 status`

Wenn Exitcode = 0, dann läuft er, wenn Exitcode > 0, dann läuft er nicht.

Wenn Apache läuft, dann Deine bisherige Routine verwenden. Wenn er nicht läuft muss der lighttpd aktiv sein.

Wenn lighttpd läuft, dann prüfen ob der neue Port belegt ist:

`netstat -tanp | grep NEUERPORT`

Wenn Exitcode = 0, dann ist der Port bereits in Benutzung, wenn Exitcode >0, dann ist er noch frei. Wenn Port belegt ist, dann Fehlermeldung ausgeben. Diese Routine könntest Du natürlich auch beim Apache verwenden.

**2. Port-Wechsel:**

Würde ich immer in beide Configs eintragen. Für den Lighttpd ist es die Datei /opt/loxberry/system/lighttpd/port.conf:

```server.port = 80```

Dann Apache oder lighttpd neu starten (Wieder Prüfung, wer von beiden aktiv ist und dann neu starten.

**Comment by mschlenstedt** [comment]
Oder soll ich das umbauen? Schließlich will ich den lighttpd ja :-)

**Comment by svethi** [comment]
Die Abfrage des aktiven Webserver mache ich nur beim restart. Der Port soll immer in Beiden geändert werden, damit man problemlos zwischen Beiden hinundher schalten kann.

**Comment by mschlenstedt** [comment]
Ja, so war das auch gemeint. Du musst dann, nachdem Du in beide Configs eingetragen hast, nur prüfen, welchen Webserver Du neu starten musst.
