### ISSUE TITLE
Wrong log directories for apache2 and lighttpd

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#354]
Bin gerade über ein Problem gestolpert, was wahrscheinlich auch das Problem des Apache erzeugt.
Durch Git Genörgel habe ich das Logdir des lighttpd gelöscht nach dem pull startete der lighttpd nicht mehr.
Ich habe dann herausgefunden, dass unter /opt/loxberry/log/system die Logverzeichnisse für apache2 und lighttpd nicht vorhanden waren. Anstatt der Verzeichnisse, gab es für Beide je eine Datei. Das funktioniert natürlich nicht. Nachdem ich diese Dateien gelöscht und dafür die Verzeichnisse angelegt hatte, lief der lighttpd wieder.

**Comment by mschlenstedt** [comment]
Das ist eine Vorbereitung auf das nächste Image. In /opt/loxberry/log/system liegen nur noch Symlinks für das Apache und lighttpd Logdir, die auf /opt/loxberry/log/system_tmpfs zeigen.

/opt/loxberry/log/system_tmpfs wird eine Ramdisk sein.

**Comment by christianTF** [comment]
Ich ent-assigne mich wieder - ich bin unschuldig! 😉

**Comment by christianTF** [comment]
Yeah, ein tempfs für system! Das bräuchte ich eh schon.

**Comment by mschlenstedt** [comment]
Noch ein letzter Fix in plugininstall.pl (15 Minuten), dann baue ich das neue Image :-) Da ist es dann drin.

**Comment by svethi** [comment]
Oh man, ich komme hier immer nur kurz zu was und muss mich dann immer um irgendwelche Merkwürdigkeiten kümmern, ich hoffte endlich mal das Services Widget fertig zu bekommen.

Gibt's was Neues zum fastcgi? Hatte da auch grad schon wieder ein Problem. Wenn man dem lighty einen weiteren Port zum lauschen gibt, dann kam über den 2.Port nur 401 Zugriff verweigert. Einen User/PW Abfrage kam nicht.
Aktiviere ich cgi, geht es.
Jemand eine Idee dazu?

**Comment by mschlenstedt** [comment]
FastCGI schauen wir uns später an - zurückgestellt. Wusste gar nicht, dass man dem lighty einen zweiten Port mitgeben kann.
