### ISSUE TITLE
ssdpd ohne general.cfg

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#355]
Wenn eine eneral.cfg nicht mit ausgeliefert wird (zukünftig standard), startet der ssdpd nicht.

```
Jan  1 22:16:54 loxberry systemd[1]: Started SSDP Service Publisher.
Jan  1 22:16:55 loxberry ssdpd[1172]: Can't call method "param" on an undefined value at /opt/loxberry/sbin/ssdpd line 17, <DATA> line 1.
Jan  1 22:16:56 loxberry systemd[1]: ssdpd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan  1 22:16:56 loxberry systemd[1]: ssdpd.service: Unit entered failed state.
Jan  1 22:16:56 loxberry systemd[1]: ssdpd.service: Failed with result 'exit-code'.
```

**Comment by svethi** [comment]
Hmm, ssdpd ist extra so konzipiert, dass es keine Werte benötigt. Wenn natürlich die ganze general.cfg nicht da ist, läuft das Config::Simple natürlich gegen die Wand. Ich dachte die sollen aus den defaults erstellt werden?

**Comment by christianTF** [comment]
Das createconfig.pl wird jetzt ganz am Anfang von loxberryinit.sh aufgerufen.
Ich habe in ssdpd jetzt auch noch eingebaut, dass er die general.cfg.default nehmen soll, wenn die general.cfg nicht existiert.

@svethi btw, warum steigst du nicht aus, wenn ssdpd deaktiviert ist, sondern hältst einen Perl-Prozess offen?
https://github.com/mschlenstedt/Loxberry/blob/325f675f7dae4dd0be09fd6606a9c016738f83ab/sbin/ssdpd#L23
