### ISSUE TITLE
Erster Aufruf von index.cgi

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#356]
Funktioniert nicht, wenn htusers.dat nicht mit ausgeliefert wird. Fehler 401: Anmeldung erforderlich.

Vorschlag: createconfig.pl beim Booten ausführen und nicht erst mit Aufruf von index.cgi.

Siehe auch #355

**Comment by christianTF** [comment]
Mist...

**Comment by svethi** [comment]
Habe gerade das Problem, dass ich auch nur noch den 401 bekomme. Die htpasswd gibt es. Ich war ja auch eingeloggt und es lief. Nachdem ich ne Zeit lang nicht drauf war und die Session nun abgelaufen ist, kommt nur der 401 und kein Anmeldefenster

**Comment by christianTF** [comment]
Sven hat Recht - wenn du die index.cgi aufrufst, musst du dich ja vorher schon authentifizieren. Das hat dann nichts mit der createconfig.pl zu tun. Ohne Auth kannst du die index.cgi ja garnicht öffnen.

**Comment by mschlenstedt** [comment]
Genau. Deswegen muss meiner Meinung nach createconfig.pl schon beim Booten aufgerufen werden und nicht erst, wenn index.cgi aufgerufen wird (geht ja nicht, weil keine Authentifizierung).

Müsste ins Initskript.

**Comment by svethi** [comment]
Das ist auch richtig, Doch mit der Authentifizierung am lighttpd gibts dennoch ein Problem. Ich bin Loxberry angemeldet. Wenn ich dann den Port wechsel, geht nichts mehr. Ich bekomme nur noch die 401 ohne Aufforderung die Zugangsdaten einzugeben. So wird das nichts mit dem Portwechsel.

**Comment by mschlenstedt** [comment]
Ich teste das mal im Image. Welchen Browser verwendest du?

Warum macht ihr den Portwechsel so kompliziert? Das macht man höchstens einmal. Und dann nie wieder. Wenn das Probleme bereitet würde ich einfach nur prüfen, ob der Port frei ist. Dann beide Configurationen schreiben und zum Reboot auffordern. Fertig. Ohne Lifeumschaltung.

**Comment by christianTF** [comment]
Das createconfig.pl ist jetzt im init-Script, aber auch noch im Index.
Wenn der Fehler auftritt, im Index einfach mal auskommentieren und schauen, obs dann geht.

**Comment by svethi** [comment]
Das ist egal, das hab ich am iPad wie auch am PC mit Firefox

**Comment by svethi** [comment]
Ich habe mit dem Portwechsel selbst kein Problem. Ich habe immer nur mal kurz Zeit mich darum zu kümmern und hänge dann jedesmal an irgendwelchen peripheren Problemen. So z.B. Mit lighttpd und der Authentisierung. ich weiß nicht was der da macht, doch wenn Du aus der Session geflogen bist, kommste nimmer rein. Das übersteht einen Restart/LBRestart. Erst wenn Du mal auf den Apache gewechselt und Dich wieder angemeldet hast, geht's wieder. Mit dem Apache geht's übrigens immer.

**Comment by christianTF** [comment]
Ich bin (wie immer) nicht auf dem letzten Stand, was die lighttpd Config angeht.
Ich habe FastCGI AUS und gerade meine general.cfg gelöscht - beim Öffnen mit FF bekomme ich den Anmeldedialog, melde mich an und alles funktioniert, und die general.cfg ist erzeugt.

Ich weiß nicht, was bei euch schon wieder los ist ;-)

**Comment by mschlenstedt** [comment]
Bei der Anmeldung ging es um die fehlende htuser.dat. Da steht das Passwort drin. Auf einem frischen Image gibts die noch nicht. Also kannst du dich nicht anmelden, und damit wird die auch nicht erzeugt ;-)

**Comment by mschlenstedt** [comment]
Bei der Anmeldung ging es um die fehlende htuser.dat. Da steht das Passwort drin. Auf einem frischen Image gibts die noch nicht. Also kannst du dich nicht anmelden, und damit wird die auch nicht erzeugt ;-)

**Comment by mschlenstedt** [comment]
Das wäre übrigens bei Apache ganz genau so :-)

**Comment by christianTF** [comment]
Ok, dann muss die htuser.dat.default weg, die bringt dann nichts, und die htuser.dat wird wie bisher mit ausgeliefert. Da steht sowieso nur das Passwort drin. Das löst alles, oder?
Das createconfig.pl ist jetzt ja schon in loxberryinit drin, damit sollte es trotzdem jetzt schon funktionieren?

**Comment by svethi** [comment]
Nee, lass mal für git die default und kopier die nur rein.

**Comment by mschlenstedt** [comment]
Ich hatte da glaube ich auch einen Denkfehler:

Wenn ich das Image baue, dann kann ich doch die createconfig.pl einfach ausführen? Der Aufruf könnte doch in setenvironment.sh. Damit müsste doch alles erschlagen sein.

Und zur Sicherheit würde ich die beiden Aufrufe beim Boot und in index.cgi auch belassen. Die prüfen doch, ob die Zieldateien schon existieren und tun dann nichts (bzw. ergänzen nur fehlendes), oder?

**Comment by christianTF** [comment]
Das Verhalten ist so:
index.cgi:
- Createconfig wird nur aufgerufen, wenn eine der Configs FEHLT.

initloxberry:
- Createconfig wird immer aufgerufen

LoxBerry Update: 
- Createconfig wird immer aufgerufen

Der Unterschied ist, dass - weil ich bei Config::Simple nicht zwischen leer und nicht vorhanden unterscheiden kann - beim Aufruf von Createconfig immer die general.cfg (sinnlos weil identisch) geschrieben wird.

Das stimmt, man kann das direkt beim Image erstellen aufrufen. Kommt ja aufs gleiche raus ob vorher oder nachher. 
Die Unique ID wird eh anders erzeugt.

**Comment by mschlenstedt** [comment]
OK, dann baue ich das noch in setenvironment.sh mit ein.

**Comment by mschlenstedt** [comment]
@svethi  Kommentiere mal folgende Zeile aus system/lighttpd/lighttpd.conf aus und starte neu:

```server.error-handler        = "/system/error/apache_error.php"```

Damit waren meine Authentifizierungsprobleme weg.

**Comment by svethi** [comment]
Hat das auch irgend einen Hintergrund, oder ist das ein Test?

**Comment by mschlenstedt** [comment]
Seit dem ich das auskommentiert habe sind die Authentifizierungsproblene weg. 

Ist jetzt in GIT so drin. Wir müssten testen was passiert wenn wir es wieder aktivieren

**Comment by svethi** [comment]
Ich hatte zwar einmal kurz wieder die 401, doch bei einem Reload fragte er dann richtig die Zugangsdaten ab. Scheint soweit also iO.

**Comment by christianTF** [comment]
Zusammengefasst:

- createconfig.pl muss dann noch in die Image-Erstellungsanleitung an der richtigen Stelle. Die Environments müssen da schon funktionieren.
