### ISSUE TITLE
stylesheet error on firefox

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#357]
Ich bin mir nicht sicher, aber das ist glaube ich erst seit der "Info 1"

![lb_css_error_1](https://user-images.githubusercontent.com/22625669/34477789-f55749da-ef9c-11e7-806c-891d8ebba621.jpg)

**Comment by christianTF** [comment]
Gute Idee, Mal andere Browser als Chrome zu probieren

**Comment by svethi** [comment]
Chrome? Wer benutzt denn sowas ;-)
