### ISSUE TITLE
Missing Environment constants in PHP-exec in lighttpd

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#358]
Hmm,

Merkwürdiges Problem. @mschlenstedt wieder was für Dich zu Ärgern ;-). Ich hänge schon wieder fest weil mir die Umgebung Steine in den Weg legt.
Shell Aufruf aus PHP aus. Alles läuft unter Loxberry mit dem Apache funktioniert alles, mit dem lighty nicht. Auf der Suche nach dem Fehler musste ich feststellen, dass mit shell Aufruf aus dem PHP des lighty heraus die Envs fehlen.
Eine Idee?

**Comment by svethi** [comment]
Okay, hab rausgefunden wo es hakt.

Die ganzen Envs müssten auch noch in LBHOMEDIR/system/lighttpd/conf-available/15-fastcgi-PHP.conf eingetragen werden.

**Comment by christianTF** [comment]
Wir sind ja garnicht mehr auf FastCGI

**Comment by svethi** [comment]
Doch das PHP läuft rein dadrüber. Nicht das Perl

**Comment by svethi** [comment]
Oder geht das PHP auch anders? Muss ich mal probieren

**Comment by christianTF** [comment]
Stimmt, hast Recht

**Comment by mschlenstedt** [comment]
Ich verstehe dieses olle PHP nicht :-) Das hat doch nun extra ein eigenes Config-File unter system/php, wo die ganzen ENVs drin stehen. Warum nutzt es das dann nicht?

Schau mal ins fast-cgi-perl, dort habe ich die ENVs schon mal alle testweise manuell eingetragen. Wenn Du das für PHP überträgst und den lighty neu startest, geht es dann?

**Comment by svethi** [comment]
Das hat nicht viel mit PHP zu tun. Es geht um einen Shell-Aufruf aus PHP heraus. Im PHP selbst sind die Envs ja da. Und im Apache isses auch OK. Da im Lighttpd für PHP aber ein Server gestartet wird, sieht das wohl dann etwas anders aus.
Ich brauchte erst einmal nur LBHOMEDIR. Das habe ich bei mir eingetragen und es geht.
Ich dachte nur dass das auch ins setenvironment rein muss?

**Comment by christianTF** [comment]
Kannst du die etc/enviroment dort sourcen? Oder geht das auch nicht?

**Comment by mschlenstedt** [comment]
Man kann Variablen durchreichen.

**Comment by mschlenstedt** [comment]
Ich war gestern nicht mehr am Rechner, daher konnte ich nicht schauen.

@svethi : Kannst Du mal probieren LBHOMEDIR anstatt neu zu setzen einfach nur durchzureichen? Das geht unter "bin-copy-environment" in der Datei https://github.com/mschlenstedt/Loxberry/blob/loxberry-0.3.0-saruman/system/lighttpd/conf-available/15-fastcgi-php.conf Anschließend musst Du lighty neu starten.

Das wäre deutlich einfacher, dann müssten wir die lighttpd.conf nicht separat über setenvironment.conf bearbeiten,

**Comment by svethi** [comment]
Du, das hatte ich als erstes probiert. Funktionierte aber nicht. Ich kann es aber gern noch einmal versuchen.
Wenn ich das richtig verstehe, muss doch da dann auch der Name der Variablen rein, also LBHOMEDIR, oder ist das irgend ein übergeordneter Name?

**Comment by mschlenstedt** [comment]
Ich war davon ausgegangen, dass wir die ENV-Variablen in der PHP Config setzen: ~/system/php/7.0/cgi/conf.d20-loxberry.ini

Das tun wir aber gar nicht... Könnte man das nicht dort mit einfügen?

**Comment by christianTF** [comment]
@svethi Kannst du ein Test-Script machen, damit sich das reproduzieren bzw. testen lässt?
Oder ist das überhaupt noch offen?

**Comment by svethi** [comment]
Ähm, PHP wird vom lighty über cli aufgerufen. Wenn, dann müsste das ins cli

**Comment by svethi** [comment]
Sollte kein Problem sein ein Script zu machen, doch im Grunde ist ja schon klar was zu tun ist. Ich hab das LBHOMEDIR auch schon drin, damit das Services luppt

**Comment by mschlenstedt** [comment]
Weiß nicht was cli ist. Aber laut phpinfo() werden folgedne Verzeichnisse verwendet:

/etc/php/7.0/cgi
/etc/php/7.0/cgi/php.ini
/etc/php/7.0/cgi/conf.d

Bei phpinfo() sieht man auch, welche Environments mit übergeben werden:

![image](https://user-images.githubusercontent.com/16830799/34906189-2f2b4ca0-f868-11e7-88a1-4a7c340004fc.png)

**Comment by svethi** [comment]
admin/system/testenv.php added

**Comment by christianTF** [comment]
@mschlenstedt PHP hat (in einer Apache-Config) zwei unterschiedliche php-Ordner mit unterschiedlichen PHP.ini:
CLI ist Command line interface, z.B. von der Bash
Apache wär dann die PHP-Config für Apache

Damit kann man unterschiedliche Rechte/Module/Settings für Web und CLI definieren.
