### ISSUE TITLE
Perl Module Performance Testing/Report

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#359]
**Raspberry Pi 2 / Sandisk Extreme 32GB**

## mailserver.cgi
# Current module version Web.pm 0.3.1.19
Avg. Load Time: 
1st Call: 2680ms
Avg. Call (5 tests): 2658ms

# HTML::Template mit file_cache
Should work with CGI (no FastCGI or mod required)
File cache in /tmp
1st Call: 2710ms
Avg. Call (5 tests): 2684ms (**+1%**)

# HTML::Template mit IPC::SharedCache
Should work with CGI (no FastCGI or mod required)
Benötigt libipc-sharedcache-perl
1st Call: 2730ms
Avg. Call (5 tests): 2702ms (**+2%**)

## Timing-Aufzeichnung mit Time::HiRes
Zeit in Sekunden (0.001 = 1ms)
```
==============================================================
 TIME MESUREMENT (currtime HiRes: 1514909468.86802)

 0.00000 / 0 : use LoxBerry::System
 0.00003 / 0.00003 : use LoxBerry::Web
 0.00004 / 0.00001 : use CGI::Carp
 0.00005 / 0.00001 : use CGI
 0.00005 / 0.00001 : use LWP::UserAgent
 0.00006 / 0.00001 : use Config::Simple
 0.00007 / 0.00001 : use File::HomeDir
 0.00008 / 0.00001 : use warnings
 0.00009 / 0.00001 : use strict
 0.00010 / 0.00001 : All modules loaded.
 0.00012 / 0.00001 : Open general.cfg
 0.00990 / 0.00978 : Finished
 0.01000 / 0.00011 : Open mail.cfg
 0.01187 / 0.00186 : Finished
 0.01222 / 0.00036 : Parse query string
 0.01225 / 0.00002 : Query $saveformdata and lang
 0.01486 / 0.00261 : lblanguage()
 0.02323 / 0.00837 : Finished
 0.02324 / 0.00001 : sub form()
 0.02326 / 0.00001 : Initialize HTML::Template
 0.03755 / 0.01430 : readlanguage()
 0.15050 / 0.11295 : Filling parameters to template
 0.15103 / 0.00053 : Finished
 0.15106 / 0.00003 : Call head()
 0.17766 / 0.02660 : Call pagestart()
 0.20150 / 0.02384 : Print template
 0.20409 / 0.00259 : Call pageend()
 0.22204 / 0.01795 : Call foot()
 0.22339 / 0.00135 : Finished, before exit
==============================================================
```
Laufzeit laut Browser: **2,66 Sekunden**

**Comment by christianTF** [comment]
## Analyse mit dprofpp
'dprofpp -S -p mailserver.cgi' 
gibt die Laufzeit jeder Funktion auch während der Compile-Time aus.
Auffällig: DateTime::BEGIN (1,2 sek.)
Mit cpan nachinstalliert: 
`cpan Devel::TraceUse`, danach
` perl -d:TraceUse mailserver.cgi'
Gibt einen rekursiven Tree aus, welche Module welche Module laden.
--> DateTime wird direkt in Web.pm geuse'd zum Parsen der Notification Zeiten
--> use DateTime und den Code auskommentiert

Neue Laufzeit laut Webbrowser: **1,12 Sekunden**

---> sub parsedatestring muss ohne DateTime implementiert werden, und die abhängigen Funktionen.

**Comment by christianTF** [comment]
# Neue Baseline
## mailserver.cgi
## Current module version Web.pm 0.3.2.1
Avg. Load Time: 
1st Call: 1150ms
Avg. Call (5 tests): 1154ms

# HTML::Template mit file_cache
Should work with CGI (no FastCGI or mod required)
File cache in /tmp
1st Call: 1200ms
Avg. Call (5 tests): 1164ms 
(**+1%**)

# HTML::Template mit IPC::SharedCache
Should work with CGI (no FastCGI or mod required)
Benötigt libipc-sharedcache-perl
1st Call: 1190ms
Avg. Call (5 tests): 1180ms (**+2%**)

# HTML::Template mit file_cache auch für mailserver.cgi
Filecache auch für das mailserver.cgi Template (nicht nur Web.pm)
Should work with CGI (no FastCGI or mod required)
File cache in /tmp
1st Call: 1180ms
Avg. Call (5 tests): 1148ms 
(**-0,5%**)

## Optimized readlanguage()
Baseline: 114ms
Optimized: 104ms (**-9%**)

--> Web.pm 0.3.2.2

**Comment by christianTF** [comment]
Optimierungen:
https://github.com/mschlenstedt/Loxberry/commit/4dfe7022a82b582500bc35394d41478ca280d1c3
https://github.com/mschlenstedt/Loxberry/commit/8611ec26cee142628e78688d944cd50e17e8bfa9
https://github.com/mschlenstedt/Loxberry/commit/ea16fe2f8998e7ddb2d570c5cd180f7f08a8d2d2
https://github.com/mschlenstedt/Loxberry/commit/a71115b98427f4682ab117a840383f63e233f827

Aufrufzeit der mailserver.cgi im Browser jetzt ca. **1,05 Sekunden**.

**Comment by svethi** [comment]
Hast Du auch die 15-fastcgi-perl.conf im lighttpd aktiviert?

**Comment by christianTF** [comment]
Das war nicht der Plan.
Ich hab schon wieder vergessen, warum fastcgi mit Perl nicht (richtig?) geht.

Aber von 2,66 auf 1,05 Sekunden bei  🐌 "SnailCGI" ist schon recht cool 

PS: Achja, weiß es schon wieder - STDOUT von system() und exec() kommen beim Client nicht an.
PPS: Und das FastCGI schafft keine zwei Requests gleichzeitig (1x Ajax, 1x normal --> Fehler 500)

**Comment by svethi** [comment]
Hmm,

Das mit dem Standard Out muss sich ja machen lassen. Geht ja bei PHP auch. PHP ist ja genauso eingebunden wie es das Perl damit wäre. Die gleichzeitigen Request, kann sein, doch im Gegensatz zu PHP werden im Standard hier nur 1 Server gestartet. Bei PHP sind's 5. Ich würde fast denken, man sollte sich das mal nächer ansehen.
