### ISSUE TITLE
Neues Image LB 0.3.3

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#360]
Ich habe ein neues Image hochgeladen. Bugmeldungen bitte in separaten Issues erfassen.

Änderungen:

- Tmpfs für /var/log und einige andere Verzeichnisse wieder aktiviert
- Fürs System gibt es jetzt 2 Logverzeichnisse: $LBHOME/log/system und $LBHOME/log/system_tmpfs
- Beim Booten werden Verzeichnisse in den tmpfs-Logverzeichnissen automatisch aus einem "skeleton"-Verzeichnis erstellt, da viele Dienste diese nicht selbst anlegen (Apache, Samba). Das Skeletonverzeichnis soll nach apt-Läufen jeweils neu erstellt werden.
- lighttpd ist jetzt Standard, ohne FastCGI für Perl.

Das Image soll bzgl. des Betriebssystems "Feature Freeze" sein. Nur noch Bugfixing.

Nachdem ihr gebootet habt kann per @christianTF 's Update auf die letzte Version hochgezogen werden. Wer direkt aus GIT clonen möchte, muss folgende Befehle als Root durchführen:

- service lighttpd stop
- umount /opt/loxberry/log/system_tmpfs
- umount /opt/loxberry/log/plugins
- cp -ra /opt/loxberry/log /tmp
- cd /opt
- rm -r /opt/loxberry
- git clone https://github.com/mschlenstedt/Loxberry.git -b loxberry-0.3.0-saruman loxberry
- mount /opt/loxberry/log/system_tmpfs
- mount /opt/loxberry/log/plugins
- cp -ra /tmp/log/system_tmpfs/* /opt/loxberry/log/system_tmpfs/
- /opt/loxberry/bin/createconfig.pl
- /opt/loxberry/sbin/resetpermissions.sh
- service lighttpd start

**Comment by christianTF** [comment]
Dazu nochmal der Hinweis, wie das mit den Update-Scripts funktioniert:
http://www.loxwiki.eu/pages/viewpage.action?pageId=24839278

Das ~/system ist "updatefreie Zone" und muss explizit per Update-File geändert werden.

**Comment by svethi** [comment]
Ähm, wenn ich als root git verwende, dann legt das Dateien bei mir auch als root an. Müsste da nach dem git nicht noch die Owner richtig gesetzt werden?

**Comment by christianTF** [comment]
Das macht resetpermissions.sh

**Comment by svethi** [comment]
Isses denn besser das Image zu verwenden, oder kann ich auch mit meinem weiter machen?

**Comment by christianTF** [comment]
Du solltest schon das neue (hoffentlich letzte) Image vor Release verwenden, das soll ja auch ein Test sein, und es soll auch nichts mehr an Raspbian geschraubt werden, wenn's kein Fehler ist.
Alle Features müssen mit Raspbian "as-is" (0.3.3) probiert werden.
Sonst kann man in ~ ändern "was man will", und mit LBUpdate können wir auch testen, ob dann alles so geht wie es soll, ohne ein neues Image zu ziehen.

**Comment by christianTF** [comment]
@mschlenstedt General.cfg.default nicht vergessen beim Image erstellen.
Ich hab's eben geändert -> 0.3.3

**Comment by svethi** [comment]
Der nimmt die Zugangsdaten nicht an?

**Comment by svethi** [comment]
Das Passwort in der htusers.dat sieht mir nach einem Linux PW und nicht nach einem Apache PW aus.
