### ISSUE TITLE
Portwechsel: Alter Port wird als belegt gemeldet

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#361]
Ich habe einen Portwechsel auf 8080 durchgeführt -> Hat funktioniert.

Dann wollte ich ohne Neustart zurück auf den alten Port "80" wechseln. Meldung:

The port you've given is already in use. You have to choose another port.
Your settings have been discarded.

Der Port ist aber definitiv frei:

```
loxberry@loxberry:~/config/system $ netstat -tanp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -
tcp        0      0 192.168.3.36:8080       192.168.3.29:52127      TIME_WAIT   -
tcp        0     64 192.168.3.36:22         192.168.3.29:52030      ESTABLISHED -
tcp        0      0 192.168.3.36:8080       192.168.3.29:52131      TIME_WAIT   -
tcp        0      0 192.168.3.36:8080       192.168.3.29:52128      TIME_WAIT   -
tcp        0      0 192.168.3.36:8080       192.168.3.29:52126      TIME_WAIT   -
tcp        0      0 192.168.3.36:8080       192.168.3.29:52129      TIME_WAIT   -
tcp        0      0 192.168.3.36:8080       192.168.3.29:52125      TIME_WAIT   -
tcp6       0      0 :::22                   :::*                    LISTEN      -
tcp6       0      0 :::445                  :::*                    LISTEN      -
tcp6       0      0 :::139                  :::*                    LISTEN      -
tcp6       0      0 :::8080                 :::*                    LISTEN      -
loxberry@loxberry:~/config/system $
```

**Comment by svethi** [comment]
Hmm, probiert hatte ich die 8080 nicht, aber ich hatte extra ein Leerzeichen an den Port angehängt, damit sowas nicht passiert. Klappt wohl nicht. Muss ich mir ansehen.

**Comment by christianTF** [comment]
Warum macht ihr das so kompliziert mit netstat, das ist ein Zweizeiler mit PHP und Perl, den Port zu öffnen.

**Comment by christianTF** [comment]
https://github.com/christianTF/LoxBerry-Plugin-squeezelite/blob/8e14293db22c9e900750b7caaf75b66b0164593b/webfrontend/cgi/bin/lms2udp.pl#L922

**Comment by svethi** [comment]
2-Zeiler?? Aber selbst wenn es nur 2 Zeilen wären, ich mache es in Einer ;-)

**Comment by christianTF** [comment]
Dafür falsch :)

**Comment by svethi** [comment]
Nix ist falsch, Das funktioniert schon richtig. Und hätte @mschlenstedt mal etwas gewartet oder es nochmals probiert nachdem er das netstat gepostet hatte, hätte es auch bei Ihm geklappt :-)
Hab es bei mir getestet und zuerst nicht gefunden wo das Problem sein soll da bei mir alles klappte. Bin dann eher durch Zufall drauf gestoßen. Wenn Du das zu schnell hintereinander machst, hängen im netstat noch alte TIME_WAIT und FIN2_WAIT Verbindungen mit den alten Ports. Diese hatte er dann gesehen und Port in use geschmissen. Habe die Portabfrage auf LISTEN angepasst. Sollte nun auch bei Hecktigern funktionieren ;-) Einzeilig ;-)
