### ISSUE TITLE
power.cgi: POST statt GET

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#362]
Aktuell wird der Reboot per GET ausgelöst. Das hat zur Folge, dass der Browser beim Neuladen der Seite den Reboot erneut auslöst.

Das Problem gab es von einigen Usern, weil sie längere Zeit auf der LB-Webseite inaktiv waren. Da hat der Browser dann neu geladen.

Ich finde das Original-Thema nicht mehr (war auf GIT oder im Forum), haben aber 2-3 Leute gemeldet.

Ein Wechsel auf POST sollte das Problem beheben.

**Comment by christianTF** [comment]
Hast du das selbst probiert?
Der Reboot ist jetzt AJAX, das geht gar nicht mehr wie beschrieben.

**Comment by christianTF** [comment]
https://github.com/mschlenstedt/Loxberry/issues/148

Bzw. https://github.com/mschlenstedt/Loxberry/commit/73860b8565eeb20f6c893475b1c9ffbe79bbe295

**Comment by mschlenstedt** [comment]
Nö, hab ich nicht getestet :-) Dann kann das hier zu,
