### ISSUE TITLE
LBHOMEDIR not set im resetpermissions aus dem Update

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#363]
Hi @mschlenstedt @Woersty @svethi 
Ich hab meinen LB heute doch noch auf 0.32 gelassen, weil das bei mir noch funktioniert.

Das ~/sbin/resetpermissions.sh wurde definitiv mit root ausgeführt, weil das im reset-Script schon vorher abgefangen würde.

Wenn Michael den Fehler nicht schon vorher findet, könnten wir mit meiner Config vergleichen. 
Bei mir funktioniert das definitiv auch, unmittelbar nachdem ich rebooted habe.

**Comment by mschlenstedt** [comment]
Das wäre sinnvoll. Ich hatte gestern den Fork in Verdacht, habe da aber nicht mehr weitergemacht (zu spät).

**Comment by mschlenstedt** [comment]
Hab's gelöst. Ich source die /etc/environment jetzt direkt im Shellskript resetpermissions.sh:

```bash
# set environment
if [ -f /etc/environment ]; then
                . /etc/environment
fi
```

Damit funktioniert es. Ich vermute, dass die Datei bei einigen Aufrufen aus PHP und Perl heraus nicht gesourct wird (siehe auch #358). Das Sourcen habe ich in folgende Dateien eingetragen:

/root/.profile
/opt/loxberry/.profile
/etc/profile.d/loxberry.sh

Damit hatte ich gedacht, dass das auf jeden Fall bei einem Shellaufruf (genauer: Bash) gesourct werden müsste. Scheint aber nicht (immer) der Fall zu sein.

Ein Würg-Around könnte sein die Datei erst einmal in jedem Skript zu sourcen.

**Comment by svethi** [comment]
Der Witz ist ja, dass ich den 0.3.3 aufgesetzt hatte und hatte das Problem nicht.
Da ich aber auch nicht ins Webinterface kam und mich erst an der Konsole anmelden musst, ist die Frage ob es notwendig ist dass root sich schon einmal am pi angemeldet hat?

**Comment by christianTF** [comment]
Gute Frage, vielleicht hat es damit zu tun!

**Comment by mschlenstedt** [comment]
Nein, das kann es nicht sein. In jedem vermeintlich frischem Image war root schon mal angemeldet. Nämlich ich beim Image bauen.
