### ISSUE TITLE
power: Success-Seite in JS anzeigen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#364]
Der Shutdown selbst wird bereits mit JavaScript/AJAX bei der Button-Aktion ausgeführt. Ein Reload der Seite (auch der Success-Seite, wenn diese kommt) führt keinen weiteren Shutdown/Reboot durch.

Allerdings ist der Shutdown/Reboot jetzt so schnell ausgeführt, dass es gar nicht mehr bis zur serverseitig gelieferten Success-Seite kommt. 

Der Success-Status der Button-Aktionen soll als versteckter DIV ins HTML und vom CallBack des AJAX-Requests eingeblendet werden.

**Comment by mschlenstedt** [comment]
Bei mir kam da gestern übrigens ein Error Loading Page, wenn ich auf Reboot geklickt habe. Habe ich mir aber noch nicht genauer angeschaut.

**Comment by svethi** [comment]
Ja, weil der Server dann schon längst weg war :-)
Ich habe nicht reingesehen wie Du es machst, aber ich mache das mit dem Webserver restart so, dass ich das entsprechende Shellscript im Hintergrund ausführen lasse und zur Sicherheit noch ne 2 Sekunden Verzögerung eingebaut habe.

**Comment by christianTF** [comment]
Ich schaffe im ajax-config-handler.pl nicht, irgendwas als unabhängigen Prozess zu starten.
Deswegen steht z.B. beim Update so lange "Bitte warten" dort, weil der das Update dort schon fertig macht. Ich forke sogar schon, aber hilft nix.
Eigentlich sollte sofort zurückkommen, dass jetzt upgedated wird, und das Update im Hintergrund laufen.

Beim Reboot ist es dad gleiche - er wartet, bis reboot zurückkommt, und da ist es schon zu spät.

Vielleicht kann sich das wer von euch ansehen?

**Comment by svethi** [comment]
Sehe ich mir mal an

**Comment by christianTF** [comment]
Reboot/Shutdown ist auch im Ajax-Config-handler.pl

**Comment by mschlenstedt** [comment]
Schau mal ins alte Plugininstall.cgi da steht in Code wie es geht - soweit ich mich erinnere habe ich es auch sauber kommentiert, weil es eine etwas schräge Lösung wer und ich lange danach gesucht habe.

**Comment by mschlenstedt** [comment]
Den Code findest Du ab Zeile 536:

```perl
# Without the following workaround
# the script cannot be executed as
# background process via CGI
my $pid = fork();
die "Fork failed: $!" if !defined $pid;

if ($pid == 0) {
  # do this in the child
  open STDIN, "</dev/null";
  open STDOUT, ">$logfile";
  #open STDERR, ">$logfile";
  open STDERR, ">/dev/null";

  # Starting

[...]

# End Child process
}

**Comment by mschlenstedt** [comment]
Wichtig ist das Umlenken von STDIN etc.

**Comment by svethi** [comment]
So, Reboot und shutdown geht jetzt daher mache ich das mal zu hier

**Comment by christianTF** [comment]
Da hab ich wohl zu wenig Pipes herumgelenkt :-)
Danke, over and out.
