### ISSUE TITLE
Translationen macht Murks 

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#365]
Das Problem der Translation Schnittstelle ist derzeit, dass nicht übersetzt Wert jetzt als "" in der Datei stehen und somit auch auf der Seite dann die Texte fehlen. Das geht gar nicht.

**Comment by christianTF** [comment]
Ups! Da habe ich dann nur die Sachen angeschaut, die schon übersetzt waren.
Und readlanguages fängt es nicht ab, weil "" nicht gleich nix ist.

**Comment by svethi** [comment]
Sieh mal in Dein Update Widget da gibts keinen einzigen Text :-)
