### ISSUE TITLE
Updatelog page hangs

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#366]
Hi,
Bei mir ist es so, dass die Seite mit dem Update log nicht bedienbar ist. Zumindest nicht so lange das Autoscroll an ist. Schalte ich es aus dauert es noch immer ne ganze Zeit bis ich scrollen kann. Der Firefox ist in der Zeit richtig eingefroren. Kennt Ihr das auch mit anderen Browsern und ist das bekannt?
Ich hatte diese Fenster man unbemerkt ne ganze Zeit im Hintergrund noch offen was dazu führte, dass dann auch mein Pi3 kaum noch reagierte. Liegt das jetzt nur daran, dass da die kompletten debug Infos mit drin sind? Es würde doch eigentlich reichen das Log einfach nur als txt auszuliefern, oder? Okay, dann wäre es nicht gefärbt.

**Comment by christianTF** [comment]
Ich hab das logfile.cgi und Template eh schon verbessert, weil man nichts markieren könnte. Wenn du in den Text klickst, wird automatisch auch Autoscroll abgeschaltet. Wenn Autoscroll aus ist, wird nicht nur das Scrollen, sondern auch das Reloaden komplett abgeschaltet.
Beim Chrome scheint das Reloaden nicht so schlimm zu sein, aber dieses Log ist schon ziemlich riesig.

Das ist aber eine gute Idee, den Datei-Timestamp mit der Datei auszuliefern, und beim Reload-Request mitzuschicken. Dann braucht das ganze Lesen, server- und clientseitige Parsen nur noch bei Änderung durchgeführt werden.
