### ISSUE TITLE
use CGI::Carp qw(fatalsToBrowser) wieder aktivieren

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#367]
Hi,

`use CGI::Carp qw(fatalsToBrowser);`

Das Modul zeigt (zusätzlich zum Eintrag im Errorlog) im Webfrontend Perl-Fehler direkt an, statt "Fehler 500" auszugeben.

Ich habe das aus LoxBerry::Web entfernt, weil Ausgaben an STDERR in HTML codiert waren.
Mit Lighty scheint dieses Problem im Errorlog nicht mehr zu existieren.

Ich möchte das Modul in LoxBerry::Web wieder aktivieren (und dann auch aus allen Widgets explizit entfernen), weil die Benutzer auf der Suche nach dem Webserver-Log überfordert sind.

Was sagt ihr?

PS:
Außerdem werde ich im UI von LoxBerry::Log auch Links zu den wichtigsten Logs setzen, damit man sich die Logs im UI ansehen kann.

**Comment by svethi** [comment]
Naja, wenn das im Lighty geht, aber im Apache nicht, ist die Frage ob man es aktiviert. Man kann ja umschalten.
Auf der anderen Seite könnte man natürlich sagen Okay, wer aus bestimmten Gründen den Apache nutzt muss damit klar kommen.

**Comment by christianTF** [comment]
Ich glaub, ich verstehe jetzt erst die Hintergründe des Ganzen:

Wenn CGI::Carp eingebunden ist und eine Webseite einen Fehler wirft, kommt (sowohl in Apache als auch in Lighty) ein "schöner" Fehler am Webinterface und ein normaler im Errorlog.

Wenn jedoch CGI::Carp eingebunden und das Perl-Script an der Konsole gestartet wird, dann wird die "schöne", HTML-codierte Meldung, an STDOUT geschrieben und erscheint dann an in der Shell.

Michael hat für readlanguage() das LoxBerry::Web und damit implizit CGI::Carp geladen für das Plugininstall-Script, somit hat er an der Shell die HTML-Fehler bekommen. 

Die use-Sachen von Perl werden beim Compilen ausgeführt, somit hat man im Code normalerweise keine Möglichkeit, abhängig von irgendwas (z.B. ob es eine URL gibt) das selektiv ein- bzw. auszuschalten.

Ich probier mal, ob ich das mit eval {} irgendwie hinbekomme.

**Comment by mschlenstedt** [comment]
Bin sehr dafür. Das dürfte auch #330 lösen.

**Comment by mschlenstedt** [comment]
Ich würde mich nicht darauf konzentrieren. Lieber readlanguage in Loxberry::System integrieren. Ist aber auch nicht so wichtig, da Konsole die Ausnahme für Entwickler ist.

**Comment by christianTF** [comment]
Ja, das mache ich. Geht schnell und lässt sich (für Legacy) sauber verlagern.
