### ISSUE TITLE
PHP->error.log, Perl->cgierr.log

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#368]
Das cgierr.log habe ich in der lighty-Config instanziert, weil es lt. Lighty-Doku nicht erlaubt ist, ins Lighty-Log zu schreiben (File locked).
Allerdings loggt PHP schon ins error.log.

Das sollten wir konsolidieren, weil ich selbst bin schon völlig verwirrt, ein User blickt da nie durch.

**Comment by svethi** [comment]
Was? Ich habe meine PHP Fehler im cgierr.log gefunden.
2 Fragen noch. Das error.log wird sehr vollgeknallt, kann man das noch veringern?
Kann man für Test auch ein access.log aktivieren?

**Comment by christianTF** [comment]
Ok, dann liegt das an meinem veralteteteteten 0.3.2 Image. 

So Sachen wie `Undefined variable: notify in /opt/loxberry/libs/phplib/loxberry_web.php`, da darfst du gerne drüber gehen und alle Variablen abprüfen. 
Sonst mach ich das mal später.

Für access.log muss man glaub ich mod_accesslog einbinden, und noch eine Zeile machen
```
accesslog.filename  = "pfad/access.log"
```
https://redmine.lighttpd.net/projects/1/wiki/Docs_ModAccesslog

**Comment by svethi** [comment]
Bin nicht zu Hause

**Comment by christianTF** [comment]
Macht ja nix. Die Issues sind geduldig :-)

**Comment by mschlenstedt** [comment]
Das Errorlog machen wir zum Release wieder weiter zu. Im Moment sind noch 2 Debugging-Einstellungen an und von @christianTF glaube ich das Carb-Modul:

```
debug.log-file-not-found          = "enable"
debug.log-condition-handling      = "enable"
```

**Comment by christianTF** [comment]
Zur Info: Das Carp-Modul von Perl selbst schreibt nichts hinaus.
Carp ist praktisch ein Ersatz für warn bzw. die.
Wenn ich in einem Modul ein warn mache, steht in der Meldung "Warning in System.pm line 555", gleiches mit die.
Wenn ich allerdings statt warn ein carp mache, kommt "Warning in myplugin.cgi Line 111", also die Stelle, wo der Plugin-Entwickler was falsch gemacht hat, und nicht der Ort, wo das Modul meldet.
In den Perl-Modulen ist schon alles draußen außer Sachen, die wirkl8ch kritisch wind. 
In PHP auch, aber so "uninitialized" Meldungen müssen noch abgefangen werden.

**Comment by svethi** [comment]
Nee, heute waren die Meldungen auf einmal im error.log

**Comment by mschlenstedt** [comment]
Noch aktuell? Müssen wir cgierr auch im Apache irgendwie einbauen?

**Comment by christianTF** [comment]
Apache schreibt alles in sein error.log.
