### ISSUE TITLE
Reboot redirect countdown

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#373]
Reboot redirect countdown

**Comment by mschlenstedt** [comment]
Geht das schon? Bei mir laufen die Sekunden nicht runter (Chrome).

**Comment by Woersty** [comment]
Ja eben.  Geht nicht. Mach ich dann mal.

**Comment by mschlenstedt** [comment]
Ach so. Ich dachte der Issue wäre ein Feature Request :-) Mir mir wird der Countdown angezeigt, aber nicht runtergezählt.

**Comment by Woersty** [comment]
Beides.

**Comment by svethi** [comment]
Hä, bei mir zählte das

**Comment by mschlenstedt** [comment]
> Hä, bei mir zählte das

Das kann ja jeder sagen :-)
