### ISSUE TITLE
Kein Titel beim Reboot Screen

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#374]
Kein Titel beim Reboot Screen
![notitle](https://user-images.githubusercontent.com/20454116/34643737-aa7e4e78-f329-11e7-9bb5-c1ed1c4010a7.jpg)

**Comment by Woersty** [comment]
Zurück ist auch deutsch der Rest nicht

**Comment by christianTF** [comment]
Das ist mir letztens auch aufgefallen, das ist bei ein paar Widgets so.
Ich habe %SL beim Umstellen der Languagefunktionen von LoxBerry::Web auf LoxBerry::System nicht mehr als globale Variable definiert.
Der Fix ist einfach, man muss bei read_language() ein my %SL = davor setzen. Mach ich gleich.

Das mit dem Denglisch ist kein Bug, sondern ein Feature! :sunglasses:
Das Translate-Widget wartet auf Bekanntschaften :-)

**Comment by mschlenstedt** [comment]
Das war beim Admin-Widget auch so. In Zeile 82 steht:

`LoxBerry::Web::readlanguage($maintemplate);`

Wenn man es wie folgt abändert geht es:

`my %SL = LoxBerry::Web::readlanguage($maintemplate);`

**Comment by mschlenstedt** [comment]
Fixed with bac5ba873977f4c5fae75e5caeb42103f8571875
