### ISSUE TITLE
Plugin directory has wrong permissions

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#375]
```
loxberry@loxberry:~/log $ ls -l
total 4
drwxrwxrwt 2 root     root       40 Jan  6 21:33 plugins
drwxr-xr-x 7 loxberry loxberry 4096 Jan  6 06:25 system

```

**Comment by Woersty** [comment]
@mschlenstedt guckst du danach?

**Comment by Woersty** [comment]
Achso - ich mein das in **/opt/loxberry/log/plugins** - sieht man am Prompt nicht gleich...

**Comment by mschlenstedt** [comment]
Das muss ein Fehler im Image sein. Hab's gerade getestet: resetpermissions.sh setzt das Verzeichnis korrekt auf loxberry:loxberry.

Ich laß es mal als Erinnerung fürs nächste Image hier offen.

**Comment by mschlenstedt** [comment]
Wobei ich gerade sehe, dass das Verzeichnis bei Dir heute angelegt worden ist?

**Comment by christianTF** [comment]
was macht denn das skelscript (das läuft im Update ja als root), bzw. auch beim Booten.
Und was heißt das überhaupt ;-)
log/plugins ist ja in der Ram-Disk, wird wohl so beim Booten passieren

**Comment by mschlenstedt** [comment]
Skel steht für skeleton, analog zu /etc/skel. 

Das Skript kopiert jeweils nach möglichen Nachinstallationen durch apt (also beim Update oder bei der Plugininstallation) alle Log-Unterverzeichnisse  aus den zentralen Logverzeichnissen in ein "Skeleton-Verzeichnis".

Aktuell sind das:

/var/log -> ~/log/skel_syslog
~/log/system_tmpfs -> skel_system

Das ist nötig, weil die meisten Programme (wie Apache, Samba und auch lighty) zwar ihre eigenen Logdateien anlegen, nicht aber ihre Logverzeichnisse. Und die sind nach einem Reboot in den TMPFS-Verzeichnissen ja nicht mehr da.

Das Skript läuft mit Rootrechten, damit die korrekten Permissions/Ownerships mit kopiert werden (cp -ra ....).

Beim Booten werden dann über das Init-Skript ~/sbin/createtmpfsfoldersinit.sh die skel-Verzeichnisse zurück in die Log-Verzeichnisse auf das TMPFS kopiert (wieder mit cp -ra ....). Das passiert ganz am Anfang des Bootprozesses, bevor die einzelnen Daemons starten.

Da hab ich ziemlich lange dran rumgetüftelt bis es ging (einige Nächte sozusagen :-))
