### ISSUE TITLE
listnetworks.cgi (Suche nach WLAN-Netzen) ist kaputt

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#376]
Hat irgendjemand kaputt gespielt :-) Hatte ich neulich (vor ein paar wochen) schon mal repariert.

Wer war da dran? :-)

**Comment by mschlenstedt** [comment]
lshwnetwork.cgi ist auch kaupuut (Suche nach Netzwerk-Hardware).

**Comment by christianTF** [comment]
Ich, ich, ich! (lshwnetwork.cgi)
Was geht nicht?
Irgendwas mit WiFi? 
Ich hab die Aufdröselung der driver-Zeile auf split umgebaut und die IP dazugenommen.
https://github.com/mschlenstedt/Loxberry/commit/5b62a326a1ceadaadc518bb9ef306b5039e51396
Bei mir geht's noch (hab aber kein WiFi)

Listnetworks da war niemand dran.

**Comment by mschlenstedt** [comment]
Du also wieder :-)

Bei mir sehen beide Fenster so aus (Safarie und Chrome):

![504665a2-8c06-4827-84b7-1ee7c7110b9c](https://user-images.githubusercontent.com/16830799/34647022-1f530746-f377-11e7-8728-5f826e50a302.jpeg)
![29c247dd-a2e6-44a9-b6d7-f26eaa5399ac](https://user-images.githubusercontent.com/16830799/34647023-1f75d56e-f377-11e7-96ab-2b1cd3dd2b83.jpeg)

**Comment by Woersty** [comment]
Bei mir geht der Network adapter Button aber ich würde die Defaultfenstergröße etwas höher machen oder den Abstand zwischen 1. und 2. kleiner. Dann fällt der scrollbar weg

**Comment by mschlenstedt** [comment]
Vermutlich ein Berechtigungsthema.

**Comment by Woersty** [comment]
![pop](https://user-images.githubusercontent.com/20454116/34647736-49c0018c-f38b-11e7-927e-5123c76c563b.jpg)

**Comment by mschlenstedt** [comment]
Ich habe gestern den Standard-Sudo dircht gemacht. Vielleicht ist es das. Ich schaue mal...

**Comment by mschlenstedt** [comment]
Aha:

```
loxberry@loxberry:~/webfrontend/htmlauth/system/tools $ sudo /usr/bin/lshw -class network
sudo: /etc/sudoers.d/lbdefaults is owned by uid 1001, should be 0
[sudo] password for loxberry:
```

**Comment by Woersty** [comment]
Bei Search networks würde ich den Refresh button nach oben nehmen

**Comment by mschlenstedt** [comment]
Lass Dich aus :-)

**Comment by Woersty** [comment]
Sowas kleines kann man selbstbestimmt machen oder?
Notfalls nimmt man die Änderung halt zurück.

**Comment by mschlenstedt** [comment]
Ja sicher! Auch größere Dinge. Wir sind alle gleichberechtigt :-) Meist wollen nur alle bei Icons und Logo-Themen mitreden :-)

**Comment by mschlenstedt** [comment]
Das Berechtigungsthema war ein spezielles in meinem Image. Ich hatte es kaputtgespielt... :-(
