### ISSUE TITLE
Feature Request: dns.loxonecloud.com - Support für Miniserverbackup-Plugin

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#38]
Ich würde es begrüßen, wenn das Script die dns.loxonecloud.com/504F12345678 schreibweise unterstützt.
Sprich wenn ein / im IP/Hostname-Feld enthalten ist, wird der Port ignoriert und dafür der URL vor 
der Adressierung abgefragt und die zurückgelieferten Werte für IP und Port werden dann verwendet.

Was hälst du davon?

**Comment by Woersty** [comment]
So könnte man das abfragen:
 curl -I  dns.loxonecloud.com/504F12345678 --connect-timeout 2 -m 3 2>/dev/null |grep Location |awk -F/ '{print $3}'|awk -F: '{print "IP:" $1 " Port:" $2}'
IP:88.78.68.58 Port:7000

**Comment by mschlenstedt** [comment]
Find eich prinzipiell gut, damit müsste aber das komplette Setup die dns.loxonecloud.com-Schreibweise unterstützen.

Die Frage ist: Lohnt sich der Aufwand (jetzt)? Wieviele Leute setzen einen RaspPi außerhalb des Netzwerkes Ihrer Miniserver auf?
