### ISSUE TITLE
Wenn man ein Plugin deinstalliert, welches nicht da ist kommt nur eine leere Seite.

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#380]
Hatte gestern ein Plugin installiert und dann ein LB Update gemacht und dann war es nicht mehr aufrufbar und dann habe ich es deinstallieren wollen und dann kam nur eine leere Seite.

**Comment by christianTF** [comment]
@Woersty Hängst du bitte das Updatelog dieses Updates an, wonach das Plugin nicht mehr gegangen ist.
Und welches Plugin es war.

**Comment by mschlenstedt** [comment]
Die Deinstallation geht noch nicht. plugininstall.cgi ist noch nicht fertig.
