### ISSUE TITLE
RAMDISK bzw. /tmp zu klein

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#381]
```
/tmp/uploads/x7vSNRmeZ2/LoxBerry-Plugin-Text2SIP-master/data/libttspico-data_1.0+git20130326-3_all.deb: write error (disk full?). Continue? (y/n/^C) 
warning: /tmp/uploads/x7vSNRmeZ2/LoxBerry-Plugin-Text2SIP-master/data/libttspico-data_1.0+git20130326-3_all.deb is probably truncated
FAIL: Error when extracting from Plugin-Archive.
```

**Comment by Woersty** [comment]
Das Plugin ist uninstalliert schon über 20 MB groß

**Comment by christianTF** [comment]
In https://github.com/mschlenstedt/Loxberry/commit/c25b7269922053c66d6024d636c761cfe72fa58d wird jetzt bei Loxberry Update aufgeräumt:

- Das ZIP, nachdem es entzippt wurde
- Das updatedir, nachdem aktualisiert wurde

Wenn ein Update frühzeitig abbricht, bleibt das updatedir für Analysezwecke in /tmp/loxberryupdate liegen.
Wenn das ZIP nicht extrahiert werden kann, bleibt das ZIP für Analysezwecke liegen.

Das ZIP braucht derzeit ca. 3MB, extrahiert sind es ca. 17MB, also ca. 20MB weniger Platz in /tmp.

**Comment by mschlenstedt** [comment]
Tmp muss größer. Plguins dürfen als ZIP schon 50 MB haben.

**Comment by christianTF** [comment]
Kann man eh ohne schlechtes Gewissen größer machen - genutzt wird nur, was drin liegt. Es muss halt sauber aufgeräumt werden, so wie ich es vergessen hab :-)

**Comment by christianTF** [comment]
Soll ich das Entzippen in LB:System geben? Ich hab auch alle Fehlercodes von unzip.
Oder besser Code kopieren, das braucht wirklich nicht jeder
Unzip ist eine Funktion in loxberryupdatecheck.pl

**Comment by mschlenstedt** [comment]
Ich denke das muss nicht in ::System. Wird zu selten benutzt.

Ich hab den Code auch schon in pluginstall drin (mache ich über system(). Fehlercodes brauche ich nicht, da Verbose Ausgabe ins Log. Ich prüfe nur ob erfolgreich oder nicht.

**Comment by mschlenstedt** [comment]
Was ist sinnvoll? 100 MB?

Wieviel RAM hat der Pi1 noch? 500 MB?

**Comment by christianTF** [comment]
Ja, 500MB. 
100MB ist sinnvoll. Es ist ja nur während der Installation.

**Comment by christianTF** [comment]
Das Limit war damals glaub ich 100MB für das ZIP beim Upload.
Das müsste man trotzdem drastisch senken auf z.B. 30 MB, sonst ist kein Platz mehr zum Entzippen.

**Comment by christianTF** [comment]
Diskspaceinfo einbauen.
Wenn 5x Zipgröße nicht frei ist, ggf. auf SD Entzippen?

http://www.loxwiki.eu/display/LOXBERRY/LoxBerry%3A%3ASystem%3A%3Adiskspaceinfo
