### ISSUE TITLE
LoxBerry::System: Check SecurePIN

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#382]
Hallo Christian,

die SecurePIN soll für alle Dinge in der WebUI verwendet werden, die man mit einer zusätzlichen Sicherheitsabfrage ausstatten will. Ich habe es aktuell in der Plugin-Installation und beim Admin-Widget integriert.

kannst Du das in LoxBerry::System integrieren? Ich mache es aktuell so:

```Perl
# $securepin is the submitted Pin from the form
open (F, "<$lbsconfigdir/securepin.dat");
  my $securepinsaved = <F>;
close (F);

if (crypt($securepin,$securepinsaved) ne $securepinpinsaved) {
        # Error
} else {
        # Success
}
```

**Comment by christianTF** [comment]
Ok

**Comment by christianTF** [comment]
Wiki: http://www.loxwiki.eu/display/LOXBERRY/LoxBerry%3A%3ASystem%3A%3Acheck_securepin

 Nur in Perl implementiert
