### ISSUE TITLE
reboot.required: Sollte auf tmpfs liegen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#386]
Hallo Christian,

aktuell wird vom Update die Datei reboot.required in ~/log/system erwartet und ausgewertet. Das habe ich in der Plugin-Installation so übernommen.

Die Datei sollte aber besser in ~/log/system_tmpfs liegen.

**Comment by christianTF** [comment]
Richtig
Sollte ursprünglich in /tmp liegen, aber das hat zur Implementierungszeit wegen Rechtsproblemen aus dem Web mit Lighty nicht funktioniert.

**Comment by mschlenstedt** [comment]
Gibt's das tmpfs denn schon als Environmentvariable?

**Comment by christianTF** [comment]
Nein, noch nicht

**Comment by christianTF** [comment]
Das muss man sehr genau testen.
Ich hatte aus einem CGI heraus das File /tmp/reboot.required erzeugt, und angelegt wurde es jedoch nicht dort, sondern ich glaub im Apache Temp-Verzeichnis (war wohl noch unter Apache).
Wenn das geht, dann könntest du sofort alle Vorkommen von Reboot.required ändern.
 (Oder es war so, dass ich auf der Shell /tmp/Reboot.required erstellt habe, und aus index.cgi wurde es dort einfach nicht gefunden.)
