### ISSUE TITLE
plugininstall.pl: Reboot.required nach system_tmpfs

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#391]
Erst wenn Christian soweit ist.

Siehe #386

**Comment by christianTF** [comment]
Das File liegt jetzt in `~/log/system_tmpfs/reboot.required`.
Für Perl und PHP kann man `reboot_required($message);` aufrufen.
In der Bash einfach ins genannte File einen netten Text hineinpasten (mit `>>`).

In power.cgi werden alle Meldungen, da da hineingepastet wurden, angezeigt.

**Comment by christianTF** [comment]
Das war ja deins.
Meins ist geschlossen

**Comment by mschlenstedt** [comment]
plugininstall nutzt Library-Funktion.
