### ISSUE TITLE
generateconfig.pl kills configs if disk is full

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#393]
Config::Simple schlägt beim Schreiben auf und hinterlässt 0-Byte-Files.

Weiß jemand, wie man mit Perl den freien Speicher in diesem Ordner prüfen kann?
Das gehört in createconfig.pl, bevor tatsächlich etwas ausgeführt wird.

**Comment by mschlenstedt** [comment]
https://perl-howto.github.io/2013/12/filesysdf-und-filesysdfportable---freien-speicherplatz-auf-einem-dateisystem-ermitteln.html

Oder Ausgabe von df parsen.

**Comment by christianTF** [comment]
```
 df -P $path | tail -l
```
für die Ausgabe der Diskinfo für das angegebene Verzeichnis

```
 df -P | tail -l
```
für alle Disks.

Das Modul müsste man explizit mitliefern.
Ich bau das mit df ein.

**Comment by mschlenstedt** [comment]
Wenn du Ausgaben direkt parst, setz vorher sicherheitshalber die LANG noch auf Standard GB. Kann grad nicht schauen aber in admin.cgi habe ich das gemacht. Schau einfach mal bei den system() Aufrufen. 

Ich habe damals einige Stunden damit zugebracht, bis rauskam das der User auf de_DE umgeschaltet hatte.

**Comment by christianTF** [comment]
In dem Fall wirds egal sein, weil es kommen einfach nur Zahlen, und df lässt sich mit -P in den POSIX-Standard-Output schalten, womit es bei allen Betriebssystemen gleich sein sollte.

Im plugininstall.pl hab ich jetzt spontan nichts gefunden, aber wie gesagt, ich glaub es ist bei df egal.
