### ISSUE TITLE
Hintergrundlogo muss dunkler

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#394]
Am Firmenmonitor sieht man nur die Sonnenbrille

**Comment by mschlenstedt** [comment]
Ich finds gut so, sonst ist das Logo zu markant bzw. alles viel zu unruhig. Auf meinem schlechten Laptop Display kann man das Haus auch nur gerade eben erkennen. Das ist gut!

**Comment by christianTF** [comment]
Ich finde auch, dass es passt, sonst stört es den darüber liegenden Text.
