### ISSUE TITLE
Changehostname validate funktioniert nicht mehr richtig

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#395]
![screenshot_2018-01-08-19-36-53](https://user-images.githubusercontent.com/14220265/34686351-8d2d7b5e-f4ab-11e7-8b1e-e16d83b24815.png)

@Woersty Ich weiß nicht, was Du geändert hast, aber das funktioniert überhaupt nicht mehr richtig. 
Obwohl der Hostname gleich ist, ist er grün. Und wenn ich Submit sage, kommt meine Servermeldung, dass der Name leer war.
  
Kannst du das bitte wieder raus nehmen, das hat vorher (serverseitig) alles richtig funktioniert. Du reißt hier unnötig neue Baustellen auf, und wir wollen releasen!

**Comment by christianTF** [comment]
![image](https://user-images.githubusercontent.com/14220265/34814093-c41276ee-f6ac-11e7-9ef8-d5a36a5ba474.png)

@Woersty Kannst du das bitte fixen, dass das Popup das Feld nicht überlagert. Das Overlay lässt sich nicht mehr wegbringen.
Bitte auch selbst ordentlich durchtesten!
Wenn es kompliziert ist, oder es noch andere Probleme gibt, dann changehostname erstmal wieder reverten und später nochmal überarbeiten.

**Comment by Woersty** [comment]
Ich glaube jetzt passt es. Kannst du ja nochmal prüfen und dann schließen.
Ich bin schon betriebsblind. :shipit:

**Comment by christianTF** [comment]
Popup passt. 
Jetzt löscht du mir meine Eingabe raus, wenn ein Fehler kommt. 
Wenn das überall so ist, würd ich dich erwürgen ;-) (z.B. wenn das so wäre: IP eingegeben, einmal am Beistrich angekommen, alles gelöscht....)

Könntest du den Fehlertext auch noch ändern. Ich hab so schöne Texte in der Translation, was alles erlaubt ist, ein Verweis auf RFC 1123 ist aber nicht sehr hilfreich ;-)
(Hier, lies mal: https://tools.ietf.org/html/rfc1123 hat nichtmal 100 Seiten, nur 98)

**Comment by Woersty** [comment]
Ich nehme das automatische Löschen raus.

**Comment by Woersty** [comment]
Text ändere ich.

**Comment by Woersty** [comment]
Jetzt zufrieden?

**Comment by christianTF** [comment]
Jep!

**Comment by Woersty** [comment]
Ich nicht. Nochmal geändert.

**Comment by christianTF** [comment]
Text hab ich nicht gelesen, nur das nicht mehr löschen bei dir ausprobiert :-)
