### ISSUE TITLE
Setup - Schritt 1 - Umlaute beim Benutzernamen erlauben

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#4]
1. Schritt: Warum keine Umlaute beim Usernamen? 

Würde z.B. gern Wörsty verwenden. Realisierbar?

**Comment by mschlenstedt** [comment]
Fixed: öäüßÖÄÜ sind jetzt möglich.

**Comment by Woersty** [comment]
Geht nicht. Kommt "Der Benutzername muss 3-20 Zeichen lang sein und aus alphanumerischen Zeichen bestehen"
