### ISSUE TITLE
Logviewer: ZIPs (Logrotate) erkennen und öffnen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#400]
-T Check if textfile
-B Check if binary

**Comment by christianTF** [comment]
Wär das nichts @Woersty ? ;-)
Passt so schön zum Aufhübschen des Log Managers

**Comment by mschlenstedt** [comment]
Brauchen wir doch eigentlich nich mehr, oder?

**Comment by christianTF** [comment]
Nein, derzeit obsolet.
