### ISSUE TITLE
LBUpdate: Updates schöner anzeigen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#401]
- Link zum Commit (bei Release macht's keinen Sinn, steht nie was dort)
- \n formatieren
- Titel und Text auftrennen
  
Das JSON kommt von loxberryupdatecheck.pl, das Template updates.html wäre entsprechend anzupassen.

**Comment by mschlenstedt** [comment]
Noch aktuell?

**Comment by christianTF** [comment]
Nein, alles erledigt von Wörsty und mir
