### ISSUE TITLE
Logfileviewer: Autoscroll deaktivieren

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#402]
Autoscroll gleich per GET in der URL deaktivieren: &autoscroll=0

Sinnvoll für bereits gespeicherte Logfiles (Updates, Plugininstall)

**Comment by mschlenstedt** [comment]
Optimierungen auch für plugininstall_log.html prüfen. 

Oder mit HTML::Template alles in ein einziges Template packen.

**Comment by christianTF** [comment]
ich lass mir was einfallen, wie wir das Logviewer-Template so gestalten kann, dass man es komplett in jede Seite einbinden kann ohne doppelt gemoppelt.

**Comment by mschlenstedt** [comment]
Muss aber für mich nicht mehr vor dem Release sein. Ich passe die Optimierungen einfach schnell bei mir ab. Der Rest kommt später. 

Lieber testen und bugfixing!

**Comment by christianTF** [comment]
Jep!

**Comment by christianTF** [comment]
Ich schließe mal ab. Das Logfile bei der Plugin-Installation ist jetzt ok (außer #493) und wird nicht so oft verwendet wie der normale Logviewer.
