### ISSUE TITLE
Neues Design auch für Legacy Footer.

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#403]
Siehe oben.

**Comment by christianTF** [comment]
Legacy Footer wird generiert.
createlegacytemplates.pl wird bei einem Update und Reboot ausgeführt, und wenn man den friendlyname ändert.
Tatsächlich muss ich mir aber was überlegen wegen Translate.

Was passt nicht, und hast du eines der Dinge schon gemacht?

**Comment by mschlenstedt** [comment]
Nein, habe ich nicht. Bin vermutlich auf dem Stand des "Original-Image". Damit hat sich das Thema erledigt.
