### ISSUE TITLE
error.html als Legacy

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#404]
Nur damit ich es nicht vergesse: Ich nutze in meinen Plugins error.html aus dem System. Ob andere Plugins auch weiß ich nicht. Das muss auch als legacy gehen. Vermutlich einfach den alten tag  dazu geben.

**Comment by christianTF** [comment]
Kommt auch aus generatelegacytemplates.pl, und success.html auch.
Mit legacy-Variablen.
