### ISSUE TITLE
translate: generatelegacytemplates.pl muss irgendwo getriggert werden

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#406]
Wenn neue Sprachen erstellt werden, muss irgendwo generatelegacytemplates.pl getriggert werden, um die Templates für alte Plugins zu erstellen.

Weil translate.cgi on-the-fly speichert, und nicht bei jedem Wort die Templates neu erstellt werden können, muss man das irgendwo berücksichtigen. Ein Button dafür ist uncool und versteht keiner.

Möglichkeiten:

- reboot.required setzen (Templates werden beim Reboot geprüft und ggf. neu erzeugt)
- Im Translation Guide darauf hinweisen (Workaround für den User wäre, den Friendlyname zu ändern, löst generatelegacytemplates aus)
- Doch ein Button

Eine weitere Prüfung im index.cgi soll jedenfalls nicht stattfinden (Performance).

**Comment by christianTF** [comment]
Einfacher Weg: 
Im Wiki Translation Guide erklärt, man soll einmal den Namen in My LoxBerry ändern, dann passt wieder alles. Es erstellt sich ja nicht jeden Tag jemand eine neue Sprache.

**Comment by mschlenstedt** [comment]
Oder einfach bei jedem Reboot? Und im Guide der Hinweis: einmal rebooten? 

Finde ich eben so gut, und die 2 Sekunden beim Booten sind verschmerzbar.

**Comment by christianTF** [comment]
Beim Booten ist es eh schon drin. Es schreibt auch nur, wenn sich was geändert hat.

**Comment by mschlenstedt** [comment]
Mmmmh, dann muss ich bei mir mal schauen. Bei mir wurde trotz Reboot der Footer nicht auf das neue Design angepasst und auch error.html funktioniert bei meinen alten Plugins nicht.

Ich mach mich heute Abend mal auf die Suche.

**Comment by christianTF** [comment]
Ich auch

**Comment by christianTF** [comment]
Mir kommt gerade noch ein potentieller Issue in den Sinn:

generatelegacytemplate prüft (zum Reduzieren sinnloser Schreibzugriffe) alle neuen Templates und Sprachfiles per Timestamp gegen alle Alt-Templates, und führt nur aus, wenn eines der neuen Files geändert wurde.

Ich muss mir ansehen, welche Timestamps unzip bzw. rsync in LBUpdate setzt - weil wenn alles gleich ist, wird nichts aktualisiert. 

Zwei Optionen zur Behebung:

- Billige Variante: --force beim Aufruf, ignoriert Timestamps und macht immer alles neu
- Schlaue Variante: Evt. über Hash oder Filesize

**Comment by christianTF** [comment]
@mschlenstedt kannst du mal die Timestamps generell auf deinem LB anschauen, ob die alle gleich sind.

Wenn ja, dann ist das von einem LBUpdate, weil GitHub alle Files mit dem Download-Timestamp ausliefert. 
Dann wäre das auch schon der Fix: https://github.com/mschlenstedt/Loxberry/commit/e1d64ce3cfe24f66a0ef672146982520ae7c9376

**Comment by christianTF** [comment]
Ich hab das schon gecheckt - Im GitHub-Download ist der Timestamp jedes Files gleich dem Download-Zeitpunkt.
Damit kann generatelegacytemplates keinen Unterschied erkennen und skipped die Generierung. 
Das ist jetzt damit gefixt, dass in LBUpdate `generatelegacytemplates.pl --force` aufgerufen wird, womit die Timestamp-Prüfung übersprungen wird.
