### ISSUE TITLE
Usage Statistic: Intervall auf 3 Tage (statt 7) stellen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#407]
Damit das Sampling stabil wird. Bei einer Wochenstatistik ist doppelte Samplingfrequenz sicherer

**Comment by christianTF** [comment]
Abgeschlossen mit https://github.com/mschlenstedt/Loxberry/commit/2d5461658f364d867d5db36f1dae4e2e590a4664
und https://github.com/mschlenstedt/Loxberry/commit/efdaedace7d45f110ecba2be2cfe5261a05119b0

Der alte Job hat übrigens nicht funktioniert, weil /bin/sh genutzt wurde, das kein $RANDOM kennt.

Das Delay ist jetzt direkt in Perl implementiert und wird mit `-d` bzw. `--delay` für eine Random-Verzögerung bis 3600 aufgerufen.

Der Zeitplan ist 
```
10 3 */3 * *       loxberry /opt/loxberry/sbin/setloxberryid.pl -d > /dev/null 2>&1
@reboot          loxberry /opt/loxberry/sbin/setloxberryid.pl > /dev/null 2>&1
```

Im zugehörigen Updatescript auf 0.3.3.3 habe ich spaßeshalber Reboot-Required gesetzt (wäre ansich nicht notwendig), zum Probieren.

**Comment by mschlenstedt** [comment]
UPdate hat funktioniert und auch Aufforderung zum Reboot (sehr schön designt!). Ich würde die Meldung aber weniger "technisch" gestalten:

`LoxBerry Update script /opt/loxberry/sbin/loxberryupdate/update_0.3.3.3.pl requests a reboot to initialize setloxberryid.`

Das verstehen nur wir, aber kein normaler User. Schreib einfach, dass das LoxBerry Update ein Reboot benötigt. Die Details welches Skript und warum muss ins Logfile.

**Comment by christianTF** [comment]
Ok, ist geändert.
