### ISSUE TITLE
Plugin WU4Lox: Error-Seite leer

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#408]
Legacy Template: /templates/system/de/error.htm

HTML Code ist drin, wird aber nicht angezeigt (HTML-Syntax/DIV-Problem?):

![image](https://user-images.githubusercontent.com/16830799/34808805-7c34e502-f691-11e7-9bf9-78c83b500755.png)

**Comment by christianTF** [comment]
Viel besser:
![image](https://user-images.githubusercontent.com/14220265/34815382-6901b81e-f6b1-11e7-9325-e692ed93d0be.png)

error.html und success.html war mit Header und Footer generiert, das ist natürlich falsch.
Sollte nach Update gehen.
