### ISSUE TITLE
Reboot-Message wird im Footer nicht mehr angezeigt

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#409]
![image](https://user-images.githubusercontent.com/16830799/34808988-50914c82-f692-11e7-8d3f-a9f96ae68218.png)

**Comment by christianTF** [comment]
Das schaut jetzt anders aus, da ist jetzt eine Grafik, aber die wird irgendwie vom Update Exclude-File geschluckt. Hab ich schon am Radar.

**Comment by christianTF** [comment]
Hat doch nichts mit dem Update zu tun

@Woersty reboot_required.svg und reboot_required_big.svg sind nicht im Repo:
https://github.com/mschlenstedt/Loxberry/tree/loxberry-0.3.0-saruman/webfrontend/html/system/images

**Comment by christianTF** [comment]
Wörsty hat die Bilder commited https://github.com/mschlenstedt/Loxberry/commit/6cb108810cd1e377b281efe92bad30511f465b07
