### ISSUE TITLE
Cam Connect Plugin

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#41]
Ich würde noch eine Kurzerklärung auf der Konfigurstionsseite geben wie es funktioniert, z. B. dass der Link http://LOXBERRY/plugins/cam-connect/ lautet usw.

Oder ein Link auf eine Wiki-Hilfe: Unterseite von http://www.loxwiki.eu/display/LOXBERRY/Plugins mit Hilfe wie es funktioniert.

**Comment by Woersty** [comment]
Ich schreibe morgen noch eine kurze Info, wie es technisch funktioniert und dann schließe ich das hier mit dem Pull.
