### ISSUE TITLE
Password-PopUp Chrome bei Plugininstallation

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#410]
Habt ihr auch jedes mal dieses dämliche Password-Popup bei Chrome, wenn ihr ein Plugin installiert? Liegt am Password-Feld (SecurePIN). kann man das irgendwie abstellen?

![image](https://user-images.githubusercontent.com/16830799/34809069-07a53046-f693-11e7-8b6c-ff7be0d6f0b4.png)

**Comment by christianTF** [comment]
Probier Mal im Input den Tag autocomplete="off", vielleicht funktionierts auch beim Passwort.

**Comment by Woersty** [comment]
Ich schau mal. autocomplete geht jedenfalls nicht.

**Comment by Woersty** [comment]
So okay?

**Comment by mschlenstedt** [comment]
@Woersty Perfekt. Kannst Du das bitte in admin.html auch ändern?

**Comment by mschlenstedt** [comment]
Und könnte man den Text etwas breiter machen wenn das fehlt < x Pixel ist und mit kleinerer Schrift?

![image](https://user-images.githubusercontent.com/16830799/34906282-bf5ec034-f86a-11e7-87e9-92a2edf039e9.png)

**Comment by mschlenstedt** [comment]
Mmhhh, jetzt poppt der Validator auch auf, wenn ich unten in der tabelle etwas klicke. Das ist blöd, weil ich zu dem Zeitpunkt ja gar kein Plugin installieren wollte. Da hat mir die Lösung mit dem ausgegrauten Install-Button irgendwie besser gefallen...

![image](https://user-images.githubusercontent.com/16830799/34913955-714ebe7c-f909-11e7-98fd-171d3cf3ad9a.png)

**Comment by christianTF** [comment]
Ist gefixt von Wörsty

**Comment by Woersty** [comment]
Baue eh alles um.
