### ISSUE TITLE
Update History: Handling von Logrotate

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#411]
![image](https://user-images.githubusercontent.com/14220265/34813543-a63b7762-f6aa-11e7-9df0-c96cb02db179.png)

Logrotate räumt auf und History zeigt deswegen auf lauter 0 Byte Files

**Comment by christianTF** [comment]
https://github.com/mschlenstedt/Loxberry/commit/ef3bd9fda148b38b36e272dc25fdacdc38bd2f6d

Der Viewer zeigt jetzt zumindest an, was los ist, und lässt einen nicht im Ungewissen.:
![image](https://user-images.githubusercontent.com/14220265/34813648-1388f9fc-f6ab-11e7-81ca-704c46e1c928.png)

**Comment by mschlenstedt** [comment]
Lass doch den Link auf das .1 file zeigen wenn das .log 0 Byte hat.

**Comment by christianTF** [comment]
Ja, da gehört noch mehr dazu, weil morgen ist es ein .2 und gezippt

**Comment by christianTF** [comment]
Er zippt es offenbar nicht, wo wie's derzeit ausschaut
