### ISSUE TITLE
Splash screen für Webseite, Wiki und Wizard

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#414]
Vorgestellt hab ich mir:

- Ein Rechteck mit abgerundeten Ecken mit unserem Grau als Hintergrund, etwa (2:1) oder so, das auf der Website und im Wizard das volle Breite angezeigt werden kann (skalierbar). Das grau könnte auch einen _dezenten_ Farbverlauf haben.
- Dann links Haus und rechts LoxBerry, unter LoxBerry kleiner VERSION 1.0
- Unter Haus und Schriftzug dann der Slogan.
- Fürs Wiki brauchen wir glaub ich eine Version in PNG, da geht denk ich kein SVG.

Vielleicht unten noch in winziger Schrift, so wie bei einem Copyright, "2016-2018 LoxBerry und irgendwas. Und die Open Source Lizenz"

Eine Version mit Versionsnummer, eine ohne. Vielleicht lässt sich die Versionsnummer (als Variable) im Wizard auch per CSS richtig ins Bild platzieren. Das ist ein Issue, dass im Wizard gleich die Versionsnummer angezeigt wird.

**Comment by Woersty** [comment]
Ok, kommt auf ToDo

**Comment by Woersty** [comment]
Hast du mal die Links für wo das sein soll?

**Comment by christianTF** [comment]
Fürs Wiki, für loxberry.de und für den Wizard.
Aber noch nichts einstellen.
