### ISSUE TITLE
admin Widget: Username

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#415]
Soll man den Usernamen überhaupt ändern können?
Das geht doch gar nicht, wo wir überall loxberry:loxberry bei chmod/chown verwenden.

![image](https://user-images.githubusercontent.com/14220265/34871768-1d3beff6-f78f-11e7-8126-03b9f948aa66.png)

**Comment by mschlenstedt** [comment]
Es wird nur der Loginname im UI geändert. Der Linux-Benutzername bleibt Loxberry. 

Da der normale LoxBerry User gar nicht auf die Kommandozeile soll ist das aus meiner Sicht ok.

**Comment by christianTF** [comment]
Ah, ok. Das Label passe ich an, damit das klarer wird.

**Comment by mschlenstedt** [comment]
Noch ein Hinweis: Das Passwort wird für beide geändert. Das heißt: ändert man Passwort und Usernamen, muss man nur daran denken, dass auf der Console der Username immer loxberry ist bzw. bleibt.

**Comment by Woersty** [comment]
Kann ich machen. Will eigentlich die Validation eh noch einbauen.

**Comment by christianTF** [comment]
Abgeschlossen  - der Linux-User bleibt immer loxberry
