### ISSUE TITLE
updates: LoxBerry Upgrade ausblenden

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#416]
@mschlenstedt 
Wenn ich das bei den Commits richtig interpretiert habe, hast du das alte Upgrade aus loxberryinit entfernt?

Dann den Bereich LoxBerry Upgrade in updates.cgi ausblenden.

**Comment by mschlenstedt** [comment]
Ich war der Meinung, dass wir mit dem neuen Update das alte Upgrade nicht mehr benötigen. Oder ist das dann noch zu irgendetwas gut?

**Comment by christianTF** [comment]
Wissen kann man nie, ich Blende es im Template Mal aus.
