### ISSUE TITLE
LoxBerry::Log Notification: Funktion das ein HTML-DIV für Notifications zurückgibt

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#418]
Angelehnt an die Power-Meldung am Bildschirmanfang, soll ein Funktionsaufruf ein fixfertiges HTML-DIV zurückliefern, wo entsprechend des Aufrufs die Notifications enthalten sind.
Wörsty hat mir dafür auch schon ein i-Symbol gezeichnet (
https://github.com/mschlenstedt/Loxberry/blob/loxberry-0.3.0-saruman/webfrontend/html/system/images/info_bommel_big.svg)

get_notifications_html($Package, $group); --> Alle Notifications dieser Gruppe
get_notifications_html($Package, $group, 'errors'); --> Alle Fehler dieser Gruppe
get_notifications_html($Package, $group, 'infos'); --> Alle Infos dieser Gruppe
get_notifications_html($Package, $group, 'errors', 1); --> Alle Fehler dieser Gruppe, KEINEN Close-Button

Das Fenster soll standardmäßig einen "Akzeptieren"-Button enthalten, der per AJAX die Notifications löscht und den DIV ausblendet. Dafür muss die Funktion im HTML auch JS-Code mitliefern.
Der Akzeptieren-Button kann mit dem vierten Parameter unterdrückt werden. 

Das Format für Infos, Errors und gemischt muss unterschiedlich aussehen (gemischt müssen die Notifys nach Datum sortiert sein, also kommen die Notifys gemischt als Fehler und Info).

Hintergrund ist, dass es für Entwickler einfach möglich sein muss, die Notifications anzuzeigen und dem User entfernen zu lassen. 

Evt. werde ich den Funktionsaufruf im OO-Style machen, weil benannte Optionen leichter zu verstehen und zu erweitern sind wie irgendwelche Parameterfolgen in festgelegter Reihenfolge.

![image](https://user-images.githubusercontent.com/14220265/34885164-684caf64-f7bf-11e7-8c64-be33c9f74626.png)

**Comment by Woersty** [comment]
Ich bin irgendwie mit dem jquery mobile nicht so glücklich aber auch da gibt es
eine eingebaute Popup Funktion. Willst du die nicht gleich nehmen?

**Comment by christianTF** [comment]
Eigentlich nicht - ich wüsste nicht, wie die in den Use-Case passt.

**Comment by Woersty** [comment]
Dann habe ich nicht verstanden was du machen wolltest. ok :)

**Comment by mschlenstedt** [comment]
Nur um es sicherzustellen: Wir werden auf keinen Fall von JQueryMobile 
weg wechseln! Das ist gesetzt - auch, wenn es manchmal rumzickt.

Und bitte nach Möglichkeit immer die Standardfunktionen von JQueryMobile 
verwenden und nix eigenes bauen. Ich möchte ein einheitliches Look and 
Feel der Bedienoberfläche haben. Und die haben wir schon jetzt an 
verschiedenen Stellen deutlich verlassen (z. B. UpdateWidget. Das weicht 
von der Struktur von allen anderen Widgets ab). Wir müssen aufpassen, 
dass das nicht irgendwann alles zusammengestückelt und nach "Kraut und 
Rüben" ausschaut.

**Comment by christianTF** [comment]
Ich kann das Updates-Layout nachziehen - meinst zu wegen des dreispaltigen Layouts, oder wegen des gelben Feldes?
(Jetzt spontan würde ich es eh nicht ändern, müssten wir dann in Ruhe absprechen)
Wegen jQuery Mobile hab ich nichts gesagt, und die ganzen LBWeb-Funktionen nutzen jQm.

**Comment by christianTF** [comment]
get_notifications_html gibt's jetzt mit Buttons.
Button-Settings braucht man eigentlich nicht.
