### ISSUE TITLE
Weather theme

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#419]
https://github.com/mschlenstedt/Loxberry/tree/loxberry-0.3.0-saruman/webfrontend/html/system/scripts/jquery/themes/weather

@mschlenstedt Verwendest du dieses Theme, das der LB mitliefert und meiner Ansicht nach nicht genutzt wird, irgendwo (z.B. im Wetter-Plugin)?

**Comment by mschlenstedt** [comment]
Das ist garantiert irgendeine Altlast. Schmeiß es raus!
