### ISSUE TITLE
Logfile.cgi produziert einen Fehler in Zeile 171

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#420]
[Fri Jan 12 21:15:47 2018] logfile.cgi: Argument "undefined" isn't numeric in numeric ne (!=) at /opt/loxberry/webfrontend/htmlauth/system/tools/logfile.cgi line 171.

**Comment by christianTF** [comment]
Welches Log?
Immer oder nur manchmal?
Welcher Browser?

**Comment by christianTF** [comment]
Ah, hab's gerade gesehen :-)

Und wo? Im Logviewer natürlich ;-)

![image](https://user-images.githubusercontent.com/14220265/34898856-94414838-f7f5-11e7-953f-79f56e9731c9.png)
