### ISSUE TITLE
PHP: curl funktionert nach apt-get install php-curl nicht

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#422]
Auf einem "normalen" Image funktioniert nach einem `apt-get install php-curl` sofort curl auf einer PHP-Webseite.

Wie @svethi schreibt, eben auch bei mir probiert:
curl ist nicht ohne manuellen Eingriff zum Laufen zu bringen. Das Paketmanagement scheint mit der PHP7/lighty-Installation nicht zurecht zu kommen.

Ich habe diesen Artikel gefunden, die PHP mit lighty zu installieren ist:
http://raspberrypimaker.com/installing-php-lighttpd-debian-stretch/
Evt. muss PHP am LB anders installiert werden, oder es ist ein Image-Problem.

Ein Curl-Beispielscript von PHP.net funktioniert am LB23 ohne dass ich bewusst curl installiert habe, nicht aber im LB30 legacy-Verzeichnis (nach `apt-get install php-curl` und lighty-Restart:
```
<?php 
        echo "Hallo";
        $ch = curl_init(); 
        curl_setopt($ch, CURLOPT_URL, "example.com"); 
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
        $output = curl_exec($ch); 
		echo $output;
        curl_close($ch);      
?>
```

Fehler am LB30:
```
2018-01-13 00:22:48: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Fatal error: Uncaught Error: Call to undefined function curl_init() in /opt/loxberry/webfrontend/legacy/test.php:3
2018-01-13 00:22:48: (mod_fastcgi.c.2543) FastCGI-stderr: Stack trace:
2018-01-13 00:22:48: (mod_fastcgi.c.2543) FastCGI-stderr: #0 {main}
2018-01-13 00:22:48: (mod_fastcgi.c.2543) FastCGI-stderr: thrown in /opt/loxberry/webfrontend/legacy/test.php on line 3
```

**Comment by svethi** [comment]
Ich habe jetzt bei mir mal den apache2 wieder nachinstalliert. Nur damit er da ist. Installation klappt auch nicht. Lighty gestoppt und Apache gestartet, Installation geht auch nicht. Es gibt Probleme beim Ausführen der Apachescripts. Also ist die nächste Frage, geht es auf einem normalen Image?

**Comment by svethi** [comment]
Also blankes Strech -> apt-get install apache2 -> apt-get install php -> apt-get install php-curl -> funktioniert.
@mschlenstedt wie hast Du denn den Apache rausgenommen? Nachträglich? Hier scheint es ja schon ein Problem mit dem Image zu geben. Die Installation von PHP Modulen muss funktionieren

**Comment by Woersty** [comment]
@svethi Ich glaube deshalb wurde gewechselt. Irgendwas mit Variablen oder so. Welche Probleme beim Ausführen der Apachescripts kommen weißt du nicht genauer?

**Comment by mschlenstedt** [comment]
Todo nächstes Image (Erinnerung für mich):

- Apache2 mit installieren und deaktivieren (Abhängigkeiten einiger Pakete)
- Installation wie von @svethi beschrieben:

> @Schlenn aktueller Stand ... wie hast Du denn das Image aufgebaut? Wenn ich apt-get install php 
> versuche, soll unbedingt apache2 installiert werden. Das Komplettpaket ist also vom apache sogar 
> abhängig. Okay, habe dann explizit erst einmal php7.0-cli installiert und danach php7.0-cgi. Dafür 
> brauchte keinen Apache.
> Habe dann apt-get install php-curl funktioniert problemlos

- Test von PHP-Modulen, z. B. php-curl

**Comment by svethi** [comment]
Habe mit einem blanken System das Problem nicht gehabt. Ist vielleicht nur ein Problem des Testsystems/Letzten Images. Habe auch gesehen, dass lighttpd apache2-tools installiert. Wenn Du das mit rausgeschmissen hast, isses wohl klar ;-)
php7.0-curl steht in der aktuellen packages mit drin. Nimm das doch für das nächste Image mal noch wieder raus und wenn der LB "fertig" ist, dann nochmal versuchen zu installieren. Das muss ja gehen. Unabhängig von php-curl. Gibt ja auch noch andere Dinge
