### ISSUE TITLE
Plugininstall V1 - Ersetzen geht nicht mehr

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#423]
Das hätte eigentlich in der postinstall passieren sollen.
https://github.com/Woersty/LoxBerry-Plugin-BLE-Scanner/blob/master/postinstall.sh#L19-L20 

root@loxberrydev:/opt/loxberry# /opt/loxberry/system/daemons/plugins/BLE-Scanner
/opt/loxberry/system/daemons/plugins/BLE-Scanner: 52: /opt/loxberry/system/daemons/plugins/BLE-Scanner: cannot create REPLACEBYBASEFOLDER/log/plugins/REPLACEBYSUBFOLDER/BLE-Scanner.log: Directory nonexistent
[....] Update remove syslog errors rule but not restarting syslog: OK
/opt/loxberry/system/daemons/plugins/BLE-Scanner: 63: /opt/loxberry/system/daemons/plugins/BLE-Scanner: cannot create REPLACEBYBASEFOLDER/log/plugins/REPLACEBYSUBFOLDER/BLE-Scanner.log: Directory nonexistent
/opt/loxberry/system/daemons/plugins/BLE-Scanner: 64: /opt/loxberry/system/daemons/plugins/BLE-Scanner: cannot create REPLACEBYBASEFOLDER/log/plugins/REPLACEBYSUBFOLDER/BLE-Scanner.log: Directory nonexistent
/opt/loxberry/system/daemons/plugins/BLE-Scanner: 65: /opt/loxberry/system/daemons/plugins/BLE-Scanner: cannot create REPLACEBYBASEFOLDER/log/plugins/REPLACEBYSUBFOLDER/BLE-Scanner.log: Directory nonexistent
/opt/loxberry/system/daemons/plugins/BLE-Scanner: 87: /opt/loxberry/system/daemons/plugins/BLE-Scanner: cannot create REPLACEBYBASEFOLDER/log/plugins/REPLACEBYSUBFOLDER/BLE-Scanner.log: Directory nonexistent
/opt/loxberry/system/daemons/plugins/BLE-Scanner: 88: /opt/loxberry/system/daemons/plugins/BLE-Scanner: cannot create REPLACEBYBASEFOLDER/log/plugins/REPLACEBYSUBFOLDER/BLE-Scanner.log: Directory nonexistent
/opt/loxberry/system/daemons/plugins/BLE-Scanner: 90: /opt/loxberry/system/daemons/plugins/BLE-Scanner: cannot create REPLACEBYBASEFOLDER/log/plugins/REPLACEBYSUBFOLDER/BLE-Scanner.log: Directory nonexistent
/opt/loxberry/system/daemons/plugins/BLE-Scanner: 91: /opt/loxberry/system/daemons/plugins/BLE-Scanner: cannot create REPLACEBYBASEFOLDER/log/plugins/REPLACEBYSUBFOLDER/BLE-Scanner.log: Directory nonexistent
[info] Try to start BLE-Scanner daemon.
/opt/loxberry/system/daemons/plugins/BLE-Scanner: 121: /opt/loxberry/system/daemons/plugins/BLE-Scanner: cannot create REPLACEBYBASEFOLDER/log/plugins/REPLACEBYSUBFOLDER/BLE-Scanner.log: Directory nonexistent
/opt/loxberry/system/daemons/plugins/BLE-Scanner: 145: /opt/loxberry/system/daemons/plugins/BLE-Scanner: cannot create REPLACEBYBASEFOLDER/log/plugins/REPLACEBYSUBFOLDER/BLE-Scanner.log: Directory nonexistent
[ ok ] BLE-Scanner Daemon started: OK.

**Comment by christianTF** [comment]
@mschlenstedt Ist das das, was ich auch schon hatte?

`ARGV3=$3 # Third argument is Plugin installation folder`

Ich hatte das Problem, dass argv3 den gesamten Pfad und nicht nur den einzelnen Pluginfolder geliefert hat.
Hab aber seitdem nicht in diese Richtung getestet.

**Comment by christianTF** [comment]
Nein, das ist es nicht.

Sondern, postinstall.sh (ausgeführt als loxberry) hat wahrscheinlich keine Rechte auf das daemon-Script

**Comment by christianTF** [comment]
Ist definitiv ein Rechtsproblemen:
```
INFO: Installing DAEMON.
'/tmp/uploads/FpYWVRLoVp/LoxBerry-Plugin-Any-master/daemon/daemon' -> '/opt/loxberry/system/daemons/plugins/anyplugin'
OK: All file(s) were installed successfully.
INFO: Setting file permissions: /bin/chmod -v 755 /opt/loxberry/system/daemons/plugins/anyplugin
mode of '/opt/loxberry/system/daemons/plugins/anyplugin' changed from 0644 (rw-r--r--) to 0755 (rwxr-xr-x)
```

Postinstall kommt erst später, daemon gehört aber root.

**Comment by christianTF** [comment]
Das Any-Plugin stolpert auch drüber, dass es zum Zeitpunkt von Postinstall keine Rechte mehr hat (auch sed).

Ich hab in meinen daemons aber überall sowas drin:
```
loxberryhome=REPLACEINSTALLFOLDER
pluginname=REPLACEFOLDERNAME

# Directory/Pluginname fallback
if [ ! -d $loxberryhome ]; then
	loxberryhome=/opt/loxberry
fi
if [ ! -d $pluginname ]; then
	pluginname=anyplugin
fi
```
HA HA! :stuck_out_tongue_closed_eyes:
Mein Plugin geht trotzdem! ;-)

PS: Leider doch nicht, anderer Bug :flushed:

**Comment by Woersty** [comment]
Ja, aber da es ja abwärtskompatibel sein soll muss @mschlenstedt ran.

**Comment by mschlenstedt** [comment]
Ja, das muss gefixt werden.

**Comment by christianTF** [comment]
Klar, hab's nur vor-analysiert.

**Comment by mschlenstedt** [comment]
@christianTF Das sollte keine Kritik sein :-) Nur die Aussage, dass wir das so nicht lassen können :-) Bzgl. Deines alten Problems mit ARGV3=$3: Das hatte ich vor längerer Zeit schon mal gefixt. Das sollte jetzt stimmen. 

Das Rechte-Problem kommt mit dem nächsten Commit.

**Comment by mschlenstedt** [comment]
Warum hab' ich das Setzen der Permissions eigentlich so kompliziert gemacht?!? Es müsste doch gehen, wenn ich einfach zum Schluss der Plugininstallation "resetpermissions.sh" aufrufe.

**Comment by christianTF** [comment]
Schneller gehts wenn die einzelnen Ordner gesetzt werden. 
Resetpermissions dauert bei mir am Pi2 / SanDisk Extreme etwa 25 Sekunden, am Pi1 ... ?
Technisch sollte es aber kein Problem sein.

**Comment by mschlenstedt** [comment]
(Hopefully) fixed with 2b34dc6748c4b2d3d1a13bfaacd21055db6756ff

**Comment by christianTF** [comment]
Hat sich nichts verändert.

Das File gehört immer noch root, und postinstall läuft mit loxberry.

**Comment by mschlenstedt** [comment]
Dürfte nicht sein. Hast du ein Upgrade oder eine frische Installation gemacht?

**Comment by mschlenstedt** [comment]
Noch dazu kommt, dass 90% des Logs von resetpermission kommt. Ich mach das rückgängig und setze die permissions einfach am Ende.

**Comment by christianTF** [comment]
Ich mache nie frische Installationen (die sind dann immer irgendwie mehr kaputt als vorher) ;-)
Ich meine, du kopierst die Files als root hinein, dann kommt postinstall als loxberry und darf nicht sed'en, das hätte ich als Problem ausgemacht.
Dh. für mich, beim Daemon muss man nach dem Kopieren explizit dem loxberry Rechte geben, und am Schluss wieder wegnehmen.
Hab's jetzt aber noch nicht neu probiert.

**Comment by christianTF** [comment]
![image](https://user-images.githubusercontent.com/14220265/34920870-1f813b3a-f97a-11e7-9d15-898a24b08b57.png)

sed legt bei `-i` offenbar ein temporäres File im daemon-Ordner an, das darf er aber nicht.

Das sind meine Aufrufe:
```
/bin/sed -i "s:REPLACEFOLDERNAME:$ARGV3:g" $ARGV5/system/daemons/plugins/$ARGV2
/bin/sed -i "s:REPLACEINSTALLFOLDER:$ARGV5:g" $ARGV5/system/daemons/plugins/$ARGV2
```
