### ISSUE TITLE
Plugin-Installation: Alternativ URL-Angabe zusätzlich zum Upload

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#424]
Um direkt mit einem Link zu installieren.
Und irgendwann zeigen wir die verfügbaren Plugins mit Install-Button direkt im LB an.

**Comment by Woersty** [comment]
Hatte ich auch schon die Idee. Kann man dein Loxberry Update eigentlich auch für Plugins anbieten?
Dachte da an die Möglichkeit, in der plugin.cfg das GitHub Repository zu hinterlegen und dann erkennt er das und benutzt dein Backend - oder eine Kopie für Plugins angepasst.

**Comment by mschlenstedt** [comment]
Plugin-Update ist schon vorgesehen in V2.

Zur URL-Angabe: Kann man recht einfach implementieren, man kann bei den modernen Browsern aber auch einfach die URL ins Upload-Input pasten. Dann geht das schon heute.

**Comment by Woersty** [comment]
>URL ins Upload-Input 

Ja, mach isch schon länger so.

**Comment by christianTF** [comment]
@Woersty http://www.loxwiki.eu/display/LOXBERRY/What%27s+New+in+LoxBerry+0.3.x ;-)

**Comment by Woersty** [comment]
>Und irgendwann zeigen wir die verfügbaren Plugins mit Install-Button direkt im LB an.

Ich würde sagen für den Moment kann das zu. Wenn die komplett überarbeitete Plugin-Installation kommt muss man da eh nochmal ran.

**Comment by christianTF** [comment]
Ist nicht umgesetzt, also lassen wir es mal offen. 
(Ob wir das heute oder in einem Jahr umsetzen, oder vielleicht obsolet wird, das sehen wir dann eh).
Der Milestone steht ja auf "Later future". Das ist alles, was nett aber nicht wichtig ist.

**Comment by mschlenstedt** [comment]
Fixed with 53203fd57bbb81f6c7262590373773364080aebc
