### ISSUE TITLE
php-curl ins Image

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#428]
https://www.cyberciti.biz/faq/php-fatal-error-call-to-undefined-function-curl_init-in-homehttpdaincludesfunctions-php1/

**Comment by svethi** [comment]
Wäre erst einmal ne Lösung, doch irgend etwas stimmt mit dem Image nicht. Ich habe. Es jetzt soweit hingebogen, dass die Installation von php-curl fehlerfrei durchläuft. Dennoch ist curl nicht unter php -m verfügbar. Das funktioniert aber unter einem Debian latest sehr wohl. Kann es sein, dass bei der Installation vom lighty auch Apache Scripts "überschrieben" wurden oder andere Dinge ersetzt wurden? Die komplette Modulinstallation funktioniert ja nicht richtig

**Comment by christianTF** [comment]
Michael hat sich diesen Issue nur gemacht, weil curl dann sowieso ins Image soll (sobald das PHP-Install-Thema gelöst ist). Das ist kein Workaround-Issue für php-curl

**Comment by svethi** [comment]
Okay ;-)
