### ISSUE TITLE
php Config zurück nach /etc/php

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#429]
Geht sonst nicht.

**Comment by svethi** [comment]
Sicher? Hast Du das probiert? Ich hatte ja allein schon, dass apt-get install php-curl ohne apache nicht einmal automatisch php7.0-curl installiert hat. Die Installation meckert ja explizit die fehlenden Apachescripts an

**Comment by svethi** [comment]
Woher hast Du denn Dein "/etc/php"? Kann es sein, dass Dein Verzeichnis älter ist? Denn obwohl php-curl nicht installiert ist, gibt es in der Sicherung php.old bereits die curl.ini. Bei der Installation meckert er ja auch die nicht vorhandene curl.ini an.

**Comment by mschlenstedt** [comment]
Ich meine mich zu Erinnern das während der Imageinstallation gesichert zu haben. Aber irgendwas haut da nicht hin.

Ich schaue mir das bei der Neuerstellung des Images nochmal an.
