### ISSUE TITLE
Logviewer: Footer fehlt

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#430]
Beim Logvier fehlt der Footer:

![image](https://user-images.githubusercontent.com/16830799/34906275-7ed91f14-f86a-11e7-9642-276d36848cac.png)

**Comment by christianTF** [comment]
Absolut!

**Comment by christianTF** [comment]
@mschlenstedt Ist es schlimm, wenn's unten nur einen grünen Balken gibt?

Es geht darum, dass wir ja in einem externen Fenster sind und da dürfen keine Buttons sein - deswegen kann ich den Standardfooter nicht aufrufen.
Sollen aber alle Grafiken usw. da sein, müssen wir Änderungen derer zukünftig auch im logfile.html pflegen.
Deswegen würde ich einfach den grünen Footer machen mit unserem Farbverlauf Grau-Grün-Grau.

**Comment by mschlenstedt** [comment]
Ach so, daran hatte ich gar nicht gedacht. Lass es so - dann passt das.

**Comment by christianTF** [comment]
zu spät

**Comment by christianTF** [comment]
![image](https://user-images.githubusercontent.com/14220265/34907127-0e75f336-f87a-11e7-8aaa-567f338a447b.png)

**Comment by christianTF** [comment]
Ich könnte den Farbverlauf auch laufen lassen.... ;-)
Aber das ist wohl zu viel des Guten :-)
