### ISSUE TITLE
Check password rules in Admin backend 

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#431]
Prüfen der Passwortregeln.
Momentan habe ich diese Regel:
Passwort mit 5 bis 20 Zeichen 
und mindestens 1 Großbuchstaben
zwei Kleinbuchstaben
einer Ziffer 
und eins der folgenden Sonderzeichen: .!@#$&*-_ 
und ohne Umlaute
 
Ok ?!

**Comment by christianTF** [comment]
Weiß nicht, was sagt denn die alte Validation I'm Web?
Warum _zwei_ Kleinbuchstaben, aber ein Großbuchstabe?

**Comment by Woersty** [comment]
Strength 2
Müsste nachlesen 

Lass uns einfach abstimmen 
Die Regel kann ich ja frei definieren

**Comment by christianTF** [comment]
Ich halt mich raus, ich bin sowieso gegen die pseudo-sicheren Policies auf unserem unverschlüsselten LoxBerry.
Ich bin schon froh, wenn ich mir Test123! merke.
Nur das mit den Kleinbuchstaben ist unlogisch ;-)

**Comment by christianTF** [comment]
Abgeschlossen mit:
https://github.com/mschlenstedt/Loxberry/commit/50282962284f965283ca83f9bcf22300e8b2193e
https://github.com/mschlenstedt/Loxberry/commit/847c4799726e641e9189d39d9e1381de10bd9c17
https://github.com/mschlenstedt/Loxberry/commit/e2193c9f23deb99415e029f60cfc8c266ce0e76e
https://github.com/mschlenstedt/Loxberry/commit/3a4d22dab5d4f5ef8709d9f0bc5553c70e4b2274
https://github.com/mschlenstedt/Loxberry/commit/a62af89f7808b4ee3cc2916738cdde0d5f3fcb5d
https://github.com/mschlenstedt/Loxberry/commit/3836d16999947e302a627b92fbf5cf619d3fb196
