### ISSUE TITLE
Server validation for htusers.dat missing

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#433]
Wenn ich ein leeres Passwort sende, komme ich via Web nicht mehr ans System.

**Comment by Woersty** [comment]
Das 
https://github.com/mschlenstedt/Loxberry/blob/loxberry-0.3.0-saruman/webfrontend/htmlauth/system/admin.cgi#L291-L292
ist ein Problem, wenn am Server folgendes ankommt:
`saveformdata:1
adminuser:loxberry
adminpassold:
adminpass1:
adminpass2:
securepin1:1111
securepin2:1111
securepinold:0000`

**Comment by Woersty** [comment]
Vorschlag für admin.cgi
```

# Save Username/Password for Webarea
if ($adminpass1) {
	$output = qx(/usr/bin/htpasswd -b $lbhomedir/config/system/htusers.dat $adminuser $adminpass1);
	# For Apache: /usr/bin/htpasswd -n -b -B -C 5 $adminuser $adminpass1
	#open(F,">$lbhomedir/config/system/htusers.dat") || die "Missing file: config/system/htusers.dat";
	# flock(F,2);
	# print F "$adminpasscrypted";
	# flock(F,8);
	#close(F);
} else {
	if ($adminpassold) 
	{
	$output = qx(/usr/bin/htpasswd -b $lbhomedir/config/system/htusers.dat $adminuser $adminpassold);
	# For Apache: /usr/bin/htpasswd -n -b -B -C 5 $adminuser $adminpass1
	#open(F,">$lbhomedir/config/system/htusers.dat") || die "Missing file: config/system/htusers.dat";
	# flock(F,2);
	# print F "$adminpasscrypted";
	# flock(F,8);
	#close(F);
	}
	else
	{
		# don't change Webarea pass
	}
}
```

**Comment by christianTF** [comment]
Abgeschlossen mit:
https://github.com/mschlenstedt/Loxberry/commit/50282962284f965283ca83f9bcf22300e8b2193e
https://github.com/mschlenstedt/Loxberry/commit/847c4799726e641e9189d39d9e1381de10bd9c17
https://github.com/mschlenstedt/Loxberry/commit/e2193c9f23deb99415e029f60cfc8c266ce0e76e
https://github.com/mschlenstedt/Loxberry/commit/3a4d22dab5d4f5ef8709d9f0bc5553c70e4b2274
https://github.com/mschlenstedt/Loxberry/commit/a62af89f7808b4ee3cc2916738cdde0d5f3fcb5d
https://github.com/mschlenstedt/Loxberry/commit/3836d16999947e302a627b92fbf5cf619d3fb196
