### ISSUE TITLE
Setsecurepin via Admin page doesn't work

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#434]
/opt/loxberry/sbin/setsecurepin.pl xxxx yyyy funktioniert, aber nur von der Shell aus.
Mache ich es über admin.cgi geht es nicht.

**Comment by christianTF** [comment]
Abgeschlossen mit:
https://github.com/mschlenstedt/Loxberry/commit/50282962284f965283ca83f9bcf22300e8b2193e
https://github.com/mschlenstedt/Loxberry/commit/847c4799726e641e9189d39d9e1381de10bd9c17
https://github.com/mschlenstedt/Loxberry/commit/e2193c9f23deb99415e029f60cfc8c266ce0e76e
https://github.com/mschlenstedt/Loxberry/commit/3a4d22dab5d4f5ef8709d9f0bc5553c70e4b2274
https://github.com/mschlenstedt/Loxberry/commit/a62af89f7808b4ee3cc2916738cdde0d5f3fcb5d
https://github.com/mschlenstedt/Loxberry/commit/3836d16999947e302a627b92fbf5cf619d3fb196
