### ISSUE TITLE
admin.cgi: Change Secure PIN only => Unuseful infopage

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#435]
Wenn ich nur die Secure PIN ändere, kommt eine leere Meldung:
 
The new account information have been successfully taken into account. These passwords were set:

Save these credentials on a save place.Download textfile

Und die PIN wird nicht geändert. Siehe auch #434

**Comment by christianTF** [comment]
Den Text hab ich geändert, aber die Seite ist noch kaputt.
Es wird der geänderte SecurePIN zwar im Downloadfile angeboten, aber nicht angezeigt.

**Comment by christianTF** [comment]
Abgeschlossen mit:
https://github.com/mschlenstedt/Loxberry/commit/50282962284f965283ca83f9bcf22300e8b2193e
https://github.com/mschlenstedt/Loxberry/commit/847c4799726e641e9189d39d9e1381de10bd9c17
https://github.com/mschlenstedt/Loxberry/commit/e2193c9f23deb99415e029f60cfc8c266ce0e76e
https://github.com/mschlenstedt/Loxberry/commit/3a4d22dab5d4f5ef8709d9f0bc5553c70e4b2274
https://github.com/mschlenstedt/Loxberry/commit/a62af89f7808b4ee3cc2916738cdde0d5f3fcb5d
https://github.com/mschlenstedt/Loxberry/commit/3836d16999947e302a627b92fbf5cf619d3fb196
