### ISSUE TITLE
Admin: changing just username doesn't work

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#436]
Wenn ich nur den username ändere kommt:

`Nothing should be changed? No new password and no new SecurePIN? So what should be done? Never change a running system. We love you! 
`

Außerdem ändert sich der username nicht wenn ich auch das Passwort ändere.

Kann an meiner Anpassung im Dev System liegen aber da muss nochmal jemand schauen.

**Comment by christianTF** [comment]
Den Text habe ich geändert auf "Nothing was changed".

Das Ändern des Benutzernamens ohne sonstige Eingaben wäre auch nicht erlaubt.

**Comment by christianTF** [comment]
Abgeschlossen mit:
https://github.com/mschlenstedt/Loxberry/commit/50282962284f965283ca83f9bcf22300e8b2193e
https://github.com/mschlenstedt/Loxberry/commit/847c4799726e641e9189d39d9e1381de10bd9c17
https://github.com/mschlenstedt/Loxberry/commit/e2193c9f23deb99415e029f60cfc8c266ce0e76e
https://github.com/mschlenstedt/Loxberry/commit/3a4d22dab5d4f5ef8709d9f0bc5553c70e4b2274
https://github.com/mschlenstedt/Loxberry/commit/a62af89f7808b4ee3cc2916738cdde0d5f3fcb5d
https://github.com/mschlenstedt/Loxberry/commit/3836d16999947e302a627b92fbf5cf619d3fb196
