### ISSUE TITLE
plugininstall: Das crontab-File ist vom Plugin nicht änderbar

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#440]
Gehört root und ist nicht änderbar

#203 

http://www.loxwiki.eu/display/LOXBERRY/Eigene+Cronjobs+im+Plugin-Code+pflegen

**Comment by christianTF** [comment]
Betrifft wahrscheinlich auch resetpermissions

**Comment by mschlenstedt** [comment]
Es gibt ein entsprechendes Skript in sbin, was eine neue crontab installiert. Ist leider notwendig da sich sonst ein Plugin selbst rootrechte geben könnte. Hab gerade keinen Zugriff, erkläre später wie es geht.

**Comment by christianTF** [comment]
ok.
Ein Plugin kann sich zwar sowieso immer root-Rechte geben, aber wenn's abstrahiert ist, gibts auch weniger Fehler.

**Comment by christianTF** [comment]
Hab mir das Script angesehen.

Ich finde es, wie es jetzt gedacht ist, in dreierlei Hinsicht umständlich, eher eine Behinderung die zu neuen Workarounds führt, und vom Sicherheitsaspekt wenig nützlich.

Es ist immerhin ein Serverscript eines Plugins, das einen Cronjob anlegen will, und kein User.

**Comment by mschlenstedt** [comment]
Das Problem ist folgendes:

Der Webserver läuft als User loxberry. Kann also ein crontab-File anlegen. Die Crontab-Files unter /etc/cron.d haben den gleichen Aufbau wie /etc/crontab, d. h. sie haben den Usereintrag als zusätzliche Spalte, sodass sie Befehle unter einem anderen User ausführen können. Damit kann ein Skript soetwas reinschreiben:

```* * * * * root rm -rf /```

Sobald jemand Zugriff auf den Webserver hat, hat er damit quasi root-Rechte. Das ist etwas anderes als eine Plugininstallation, wo ich explizit noch einmal etwas auf dem Server installieren muss, ein Reboot durchführen muss etc.

Wenn wir das freigeben, hätten wir uns das ganze Thema mit Berechtigungen, SecurePIN usw. sparen können und den Webserver einfach unter root laufen lassen können.

Das Skript stellt nur sicher, dass alle Befehle in den Files unter /etc/cron.d immer als User loxberry ausgeführt werden (wenn auch sehr rudimentär umgesetzt - zugegeben. Etwas besseres ist mir nicht eingefallen). Leider kann man das anscheinend über die Konfiguration von cron nicht abstellen. Ich habe zumindest mit Google nichts entpsrechendes gefunden.

So kompliziert finde ich das aber auch nicht: Ich erzeuge eine temporäre Crontab in /tmp (z. B. mit einem Perl-/PHP-Modul) und führe dann das Skript aus. Wenn man das noch in die Bibliotheken implementiert kriegt der User/Pluginentwickler quasi nix davon mit.

**Comment by christianTF** [comment]
Stimmt eh... weils ja zur Laufzeit passiert.

**Comment by christianTF** [comment]
Wiki-Artikel aktualisiert: http://www.loxwiki.eu/display/LOXBERRY/Eigene+Cronjobs+im+Plugin-Code+pflegen

@mschlenstedt Kannst du noch kurz drüber schauen, ob ich das richtig beschrieben habe.

**Comment by mschlenstedt** [comment]
Passt.
