### ISSUE TITLE
Reboot funktioniert nicht zuverlässig

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#443]
- Any-Plugin installiert
- Auf Reboot Seite gegangen
- Reboot geklickt
--> Reboot-Countdown läuft.

Nur rebootet der LoxBerry nicht.

![image](https://user-images.githubusercontent.com/14220265/34966742-3c231bde-fa5e-11e7-8406-6ba68a73a4f9.png)

Beim zweiten Versuch hat's geklappt.
Man kriegt aber nicht mit, dass er nicht rebootet hat, wenn man nicht zufällig eine Shell offen hat, die terminated oder eben nicht terminated.

Das ist bei mir schon 2x aufgetreten.

**Comment by svethi** [comment]
Muss ich sehen, aber ich habe den Kram da nicht eingebaut

**Comment by christianTF** [comment]
Und ich hab ihn nicht umgebaut :-)
Es bleibt eh nichts anderes übrig, als den Fall mit F12-Netzwerkmonitor zu analysieren, um mal zu sehen, ob der AJAX-Request für den Reboot überhaupt hinausgeht, damit man weiß, ob der AJAX-Request am Client nicht geht, oder die Funktion am Server nicht geht.

Der ajax-config-handler.pl schreibt bei jedem Aufruf nach STDERR:
`print STDERR "Action: $action // Value: $value\n";`
Im Reboot-Sub dann noch:
`print STDERR "ajax-config-handler: ajax reboot\n";`

D.h. im Log müsste man schon sehen, ob der aufgerufen wurde.
Wenn das alles kommt, nur der Shutdown selbst nicht geht, muss man diesen evt. mit irgendeinem Parameter forcen, oder einfach zwei-, dreimal aufrufen ;-)

**Comment by svethi** [comment]
Ich denke erst einmal eher, dass das ein Timing Problem ist und bin jetzt auf Nummer sicher gegangen und habe geforkt und exec verwendet. Kannst mal probieren?

**Comment by svethi** [comment]
Hier gibt's ein Problem mit der HTML Seite. Um das Timing zu verbessern und dem Webserver die Zeit zu geben die Seite komplett auszuliefern, habe ich das sleep von 2 auf 5 Sekunden gestellt. Seit dem gibt es eine Weiterleitung, die dann natürlich ins leere läuft, da der Webserver dann weg ist.
Wieso der Browser meint weiterzuleiten ist mir derzeit auch noch nicht ganz klar.

**Comment by svethi** [comment]
Handling nochmals geändert, Problem aber vom html/js
