### ISSUE TITLE
PIN / PW Felder im Edge / Firefox nicht ok

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#445]

**Comment by Woersty** [comment]
Alles umgebaut. Jetzt ist zwar wieder das Autofill Chrome Problem da aber da finde ich keine Lösung.

**Comment by christianTF** [comment]
Ich habe gerade nochwas gelesen:
`<form autocomplete="off"> `

Also das Autocomplete gleich am Form abdrehen.
Müssen wir noch probieren.

**Comment by mschlenstedt** [comment]
Das geht alles unter Chrome nicht. Ich vermute eher ein Bug ist „Feature“ in Chrome. 

Off wird nicht mehr unterstützt, unter chrome soll man „new-password“ oder „user-password“ nehmen. Teilweise soll man ein verstecktes DIV einbauen. Google ist voll mit dem Problem. 

Funktionierte alles bei mir nicht.  Ich investiere keine Zeit mehr darin.

**Comment by christianTF** [comment]
Die Felder selbst wurden von Wörsty gefixt.

Für das AutoComplete (was nicht das ursächliche Topic des Issues ist) gibt es derzeit keine Lösung.

**Comment by christianTF** [comment]
Zur Info:
Auf der Miniserver-Seite hat mir Chrome beim Kennwort-Feld das vom Server _ins Formular eingesetzte_ Kennwort durch das _Chrome-gespeicherte_ Kennwort ersetzt. Das hat dazu geführt, dass das immer falsch war.

In dieser Situation hat `autocomplete="new-password"` beim Feld geholfen.

**Comment by Woersty** [comment]
Ah ok. War mir nicht aufgefallen. Ist das schon überall drin?

**Comment by christianTF** [comment]
Noch nirgends, die miniserver-Seite wo ich das getestet hab, ist noch nicht commited.
