### ISSUE TITLE
Software error: Can't call method "param" on an undefined value at /opt/loxberry/webfrontend/htmlauth/plugins/miniserverbackup/index.cgi line 333. For help, please send mail to this site's webmaster, giving this error message and the time and date of the error.

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#446]
Das ging früher...
Da ich am Plugin ja nichts ändern soll bitte prüfen.

**Comment by Woersty** [comment]
https://github.com/Woersty/LoxBerry-Plugin-miniserverbackup/blob/master/webfrontend/cgi/index.cgi#L333

**Comment by Woersty** [comment]
`$phraseplugin = new Config::Simple($languagefileplugin);
`
Scheint nicht mehr zu gehen.

**Comment by christianTF** [comment]
Probier mal das ZIP von hier: https://github.com/christianTF/LoxBerry-Plugin-miniserverbackup/tree/master

Ist wahrscheinlich mein Bug (im Plugin), und das Ding hat wohl noch nie jemand mit englischer Sprache eingesetzt. Im index.cgi meines Forks sollte es jetzt passen, es kann aber sein, dass es noch in einem anderen Script vorkommt.

**Comment by christianTF** [comment]
Gefixt - war ein Bug im Plugin mit dem Multilang-Sprach-Phrasen auslesen.

Und definitiv hat noch nie jemand das Plugin in Englisch benutzt :-)
