### ISSUE TITLE
MS-Passwort wird jetzt immer angezeigt

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#447]
@Woersty 
Seit deiner Formular-Änderung in Miniserver wird das Passwort jetzt _immer_ angezeigt.

Zuvor war das ein Passwortfeld, und mit dem Button unten konnte man das PW einblenden.

**Comment by christianTF** [comment]
![image](https://user-images.githubusercontent.com/14220265/35070848-01d735c8-fbdf-11e7-8fc2-0a09ad570244.png)

@Woersty Das musst du dir bitte sofort ansehen, jetzt stimmt bei Miniserver nichts mehr....
(Passwort wird angezeigt, Validierungsfehler wird angezeigt).

Mach die Validierung bei den MS-Passwortfeldern einfach komplett heraus - da gibt es nichts zu validieren, das ist nicht unser Passwort.

**Comment by Woersty** [comment]
Sollte wieder gehen.

**Comment by christianTF** [comment]
Geht immer noch nicht
Hau das validate aus dem Passwort raus, du brauchst dort nichts zu validieren, das muss der Miniserver machen!
Bestenfalls validierst du nur, dass das Feld nicht leer ist. 

![image](https://user-images.githubusercontent.com/14220265/35181319-f2459180-fdbf-11e7-9313-46f2e59652f1.png)
Siehe vor 2 Tagen:
![image](https://user-images.githubusercontent.com/14220265/35181326-28f2e4f8-fdc0-11e7-90df-8a3f05c622c8.png)

**Comment by christianTF** [comment]
Gefixt mit https://github.com/mschlenstedt/Loxberry/commit/425d820d72ded643ad893fdf535ad9ad3be5b6d5
