### ISSUE TITLE
Architektur mit Statistik erfassen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#448]
Raspberry, x64, x86

**Comment by christianTF** [comment]
@svethi Du musst dein VM-Architecture-File umbenennen, es muss .cfg heißen, sonst wird es beim Update gelöscht. (in der Anleitung habe ich das schon geändert - war nicht konsistent).

Implementiert mit https://github.com/mschlenstedt/Loxberry/commit/81679076e4e5dbd65594691b2430c7b0f174298d und in der DB und im Collect-File.

Grafik kann man später machen.

**Comment by svethi** [comment]
War schon wech Habs neu angelegt und neu gestartet. Solltest also Response haben.
