### ISSUE TITLE
Mailservereinrichtung kann nicht gespeichert werden

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#449]
Error loading page kommt
Test aber ok

**Comment by svethi** [comment]
Hast Du resetpermissions nochmal durchlaufen lassen?

**Comment by christianTF** [comment]
Kann ich bestätigen (Fehler beim Speichern).
Muss ich mir ansehen - ich habe so viel mit den Testmails probiert, aber dass Speichern nicht mehr geht, ist mir nicht aufgefallen...
