### ISSUE TITLE
Idee: APC Back UPS Plugin

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#45]
http://www.loxwiki.eu/display/LOX/Einbindung+einer+APC+Back-UPS+USV+%28USB%29+in+Loxone

Was hälst du davon, das auch als Plugin einzubauen?
Wie lässt sich das dann später über die PluginSchnittstelle machen, dass man Module im OS nachinstalliert? Ist das geplant?
Ich habe das schon ziemlich lange an meinem 2. Raspberry problemlos laufen.
Und die USB USV ist preiswerter als die LAN Version. Damit macht man sie dann netzwerkfähig.
Da könnte man sich richtig austoben.

**Comment by mschlenstedt** [comment]
siehe http://www.loxwiki.eu:80/x/pIG4
