### ISSUE TITLE
Anacron Fehler

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#451]
![75c31139-7d6d-468c-977b-c1e4203d2c6f](https://user-images.githubusercontent.com/14220265/35141342-f4f9c7ea-fcfa-11e7-8297-ed6d217cacdd.png)

Das bekomme ich, seit ich gestern am LB E-Mail eingerichtet hab.

**Comment by christianTF** [comment]
Inhalt von /etc/cron.daily/lighttpd
```
#!/bin/sh
# Cleanup lighttpd compress cache

cache=/var/cache/lighttpd
if test -d "$cache/compress"; then
    su -s /bin/sh -c "find $cache/compress -type f -atime +30 -print0 | xargs -0 -r rm" www-data
fi
if test -d "$cache/uploads"; then
    su -s /bin/sh -c "find $cache/uploads -type f -atime +1 -print0 | xargs -0 -r rm" www-data
fi
```

Im Verzeichnis `/var/cache/lighttpd/compress` liegen die komprimierten HTML-Seiten von lighty (das sollte eigentlich auch gleich ins tmpfs).
Führe ich die find-Zeile als root aus, bekomme ich
`find: Failed to restore initial working directory: /var/cache/lighttpd/compress: Permission denied`
Ehrlich gesagt weiß ich nicht, was dieses find genau tut (Dateien älter einem Tag löschen) bzw. warum rm  www-data

Ich klink mich hier aus, da trau ich mich nicht drüber.

**Comment by mschlenstedt** [comment]
Fixed with 64fcc368624459f8cb8ad9bae3330c45464a836d

**Comment by mschlenstedt** [comment]
Das Anacron file habe ich blöderweise doch übersehen. Den Cache habe ich nach /tmp verschoben.

**Comment by mschlenstedt** [comment]
Das find listet meiner Meinung nach alle Dateien auf die älter als 30 bzw. 1 Minute(n) sind und löscht diese als User www-data. Das ist schon wichtig, aber die PATHs passen nicht mehr und www-data ist auch falsch (deswegen Permission denied).

Ich integriere das direkt ins Image.
