### ISSUE TITLE
Port ändern in services.php geht nicht

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#455]

**Comment by svethi** [comment]
Siehe https://github.com/mschlenstedt/Loxberry/issues/457

**Comment by svethi** [comment]
Hab das auf mehreren Systemen getestet.
Könntet Ihr das auch nochmal testen?

**Comment by christianTF** [comment]
Bei mir problemlos 
Wörsty hat imho noch eine nicht 100% gleiche Lighty-Config

**Comment by svethi** [comment]
Im neuen Image nochmal geprüft ... geht.
