### ISSUE TITLE
admin.cgi: used only once: possible typo

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#456]
[Sat Jan 20 00:30:44 2018] admin.cgi: Name "R::adminuser" used only once: possible typo at /opt/loxberry/webfrontend/htmlauth/system/admin.cgi line 169.
[Sat Jan 20 00:30:44 2018] admin.cgi: Name "R::adminpass1" used only once: possible typo at /opt/loxberry/webfrontend/htmlauth/system/admin.cgi line 170.
[Sat Jan 20 00:30:44 2018] admin.cgi: Name "R::saveformdata" used only once: possible typo at /opt/loxberry/webfrontend/htmlauth/system/admin.cgi line 124.
[Sat Jan 20 00:30:44 2018] admin.cgi: Name "R::adminpass2" used only once: possible typo at /opt/loxberry/webfrontend/htmlauth/system/admin.cgi line 171.
[Sat Jan 20 00:30:44 2018] admin.cgi: Name "R::securepin1" used only once: possible typo at /opt/loxberry/webfrontend/htmlauth/system/admin.cgi line 173.
[Sat Jan 20 00:30:44 2018] admin.cgi: Name "R::adminuserold" used only once: possible typo at /opt/loxberry/webfrontend/htmlauth/system/admin.cgi line 168.
[Sat Jan 20 00:30:44 2018] admin.cgi: Name "R::do" used only once: possible typo at /opt/loxberry/webfrontend/htmlauth/system/admin.cgi line 124.
[Sat Jan 20 00:30:44 2018] admin.cgi: Name "R::securepin2" used only once: possible typo at /opt/loxberry/webfrontend/htmlauth/system/admin.cgi line 174.
[Sat Jan 20 00:30:44 2018] admin.cgi: Name "R::securepinold" used only once: possible typo at /opt/loxberry/webfrontend/htmlauth/system/admin.cgi line 175.

**Comment by Woersty** [comment]
@mschlenstedt ist das Normal?

**Comment by christianTF** [comment]
use warning meldet das, wenn eine Variable im Code nur ein einziges Mal verwendet wird.
Ich hab das so ausgeblendet:
https://github.com/mschlenstedt/Loxberry/commit/45fe5ad5191dd9e468733fa2f2eba2f580d40298#diff-a547b0bf9ff8ff23e7169fe43d2058d0R186

Müssen wir Mal nachliefern.

**Comment by Woersty** [comment]
Eingebaut.
Aber das ist noch übrig:
`[Sat Jan 20 15:11:42 2018] admin.cgi: Use of uninitialized value $R::do in string eq at /opt/loxberry/webfrontend/htmlauth/system/admin.cgi line 127.
`

**Comment by Woersty** [comment]
```
[Sat Jan 20 15:14:18 2018] loxberryupdatecheck.pl: Use of uninitialized value $download_size in concatenation (.) or string at /opt/loxberry/sbin/loxberryupdatecheck.pl line 598.
[Sat Jan 20 15:14:22 2018] loxberryupdatecheck.pl: Use of uninitialized value $dryrun in concatenation (.) or string at /opt/loxberry/sbin/loxberryupdatecheck.pl line 568.
[Sat Jan 20 15:14:22 2018] loxberryupdatecheck.pl: Use of uninitialized value $cron in concatenation (.) or string at /opt/loxberry/sbin/loxberryupdatecheck.pl line 568.


```

**Comment by Woersty** [comment]
```

[Sat Jan 20 15:14:15 2018] loxberryupdatecheck.pl: Use of uninitialized value $cron in concatenation (.) or string at /opt/loxberry/sbin/loxberryupdatecheck.pl line 144.
<INFO>    cron:

[Sat Jan 20 15:14:15 2018] loxberryupdatecheck.pl: Use of uninitialized value in concatenation (.) or string at /opt/loxberry/sbin/loxberryupdatecheck.pl line 145.
<INFO>    keepupdatefiles:
[Sat Jan 20 15:14:15 2018] loxberryupdatecheck.pl: Use of uninitialized value in concatenation (.) or string at /opt/loxberry/sbin/loxberryupdatecheck.pl line 146.

```

**Comment by Woersty** [comment]
`
[Sat Jan 20 15:14:06 2018] updates.cgi: Use of uninitialized value $saveformdata in substr at /opt/loxberry/webfrontend/htmlauth/system/updates.cgi line 168.
[Sat Jan 20 15:14:06 2018] updates.cgi: Use of uninitialized value $do in string eq at /opt/loxberry/webfrontend/htmlauth/system/updates.cgi line 180.
[Sat Jan 20 15:14:06 2018] updates.cgi: Use of uninitialized value $do in string eq at /opt/loxberry/webfrontend/htmlauth/system/updates.cgi line 187.
`

**Comment by Woersty** [comment]
Das Log ist noch ganz schön vollgemüllt....

**Comment by christianTF** [comment]
Das muss man einmal komplett machen. Z.B. alle Variablen oben entfernen, und dann nur noch die reinnehmen, die wirklich noch verwendet werden.
Das ist alles für später geplant gewesen, also nach Release.

**Comment by christianTF** [comment]
Hui, du hast ja mehr eingesammelt als ich vorher gesehen habe :-)

**Comment by christianTF** [comment]
Es beschwert sich keiner -> Close
