### ISSUE TITLE
general.cfg leer

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#457]
Leute, durch irgend ein Update ist nun die general.gfg leer. Das ist natürlich großer Mist

**Comment by christianTF** [comment]
0 Byte leer oder Default?
SD voll?

**Comment by svethi** [comment]
Scheint ja nur ein einzelnes nicht reproduzierbares Problem auf einem der Systeme gewesen zu sein.
Daher schließe ich das mal wieder
