### ISSUE TITLE
Idee: Bluetooth Plugin für BLE/G-Tags

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#46]
http://www.loxwiki.eu/display/LOX/Anwesenheitserkennung+via+Bluetooth+%28BLE%29+und+G-Tags

Was meinst du dazu? Ist leider keine 100% ige Lösung aber kannst ja mal drüber nachdenken ob das als Plugin interessant sein könnte. Reichweite sehr begrenzt. Hier bei mir max. 10 m
Und ab und zu (selten) verschwindet mal ein Tag obwohl er da ist.
Aber das könnte man im Code abfangen.

**Comment by mschlenstedt** [comment]
Ist auch ok. MIt der Pluginschnittstelle kann man letztendlich alles umsetzen.

Ich plane, sobald die Schnittstelle fertig ist, mit dem Loxberry nur noch das reine Grundsystem auszuliefern. Alle Plugins sollen dann separat installiert werden können (also ganz nach Bedarf der Nutzer).

Mir schwebt so eine Art Gallerie vor, wo die Leute auf der Webseite nach Plugins suchen können und sich die dann herunterladen können (so wie das auch die Shopsysteme, Wordpress etc. machen).

Ich habe nur noch keine passende Software, die auch Multiusertauglich ist dafür gefunden...

**Comment by Woersty** [comment]
Basisplugin soweit fertig.
http://www.loxwiki.eu/display/LOXBERRY/BLE-Scanner

Bugs bitte auf https://github.com/Woersty/LoxBerry-Plugin-BLE-Scanner/issues melden.

**Comment by Woersty** [comment]
RPi3 Bluetooth Unterstützung im nächsten Image überarbeiten
```
sudo apt-get -y remove raspberrypi-sys-mods
sudo apt-get -y install raspberrypi-sys-mods
sudo apt-get -y --reinstall install pi-bluetooth
```

**Comment by mschlenstedt** [comment]
Erledigt.
