### ISSUE TITLE
smb.conf

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#460]
workgroup sollte zu WORKGROUP umbenannt werden, da Windows die Loxberrys sonst meist nicht auflistet

**Comment by christianTF** [comment]
Das wäre auch was für Services.cgi

**Comment by mschlenstedt** [comment]
Also bei mir steht:

```workgroup = LOXBERRY```

**Comment by mschlenstedt** [comment]
Fixed.
