### ISSUE TITLE
FTP per Services an-/abstellstbar machen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#463]
Erst anfangen wenn FTP Server gefixt ist.

**Comment by christianTF** [comment]
im Services Widget

**Comment by christianTF** [comment]
Ich habe das Ein-/Ausschalten vom FTP Server umgesetzt (Services / Weitere Optionen).

@mschlenstedt Was ist denn mit "Erst anfangen wenn FTP Server gefixt ist" gemeint?

**Comment by mschlenstedt** [comment]
Da gab es nach irgend einem Update mal ein Problem mit dem vsftp. Das ist aber schon lange behoben.
