### ISSUE TITLE
Idee: SML Plugin für Stromzähler

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#47]
http://haus.woerstenfeld.de/?p=3420

Nutze ich seit längerem stabil an meinem 2. Raspberry, (Vattenfall Berlin)
Ist eine sehr preiswerte Lösung um intelligente Zähler mit Infrarotschnittstelle auszulesen.
Allerdings funktionieren nicht alle USB Hubs.
Musste etwas herumprobieren.

Meinste könnte als Plugin interessant sein?
Würde den Code dann noch aufhübschen natürlich.

**Comment by mschlenstedt** [comment]
Habe ich auch schon überlegt - ich nutze dazu ein Perlskript und den USB-Lesekopf von Volkszaehler.org Da aber anscheinend jeder Zähler sein "etwas" anderes Süppchen kocht, hatte ich imme retwas Respekt vor der Umsetzung.

Aber der Bedarf ist da - mit Deinem und meinem Zähler hätten wir schon 2 unterstützte Zähler :-)

**Comment by mschlenstedt** [comment]
Siehe http://www.loxwiki.eu:80/x/pIG4
