### ISSUE TITLE
general.cfg could not read by parse_ini_file

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#471]
PHP kann die ini's nicht lesen wenn da ungequotete Sonderzeichen drin sind. Der hat z.B. bei mir das WLAN Passwort reingeschrieben was ! enthält. Das Ganze nicht gequotet und damit konnte parse_ini_file die config nicht lesen. Sowas muss irgendwie gequotet werden.

**Comment by christianTF** [comment]
Gefixt mit:
https://github.com/mschlenstedt/Loxberry/commit/b7745afa1a935da004418b032bd62720b4a9381f
und
https://github.com/mschlenstedt/Loxberry/commit/c0309d05d34597d187c1cdbedc63f2197335c447

- SSID und WPA wird jetzt URI-encoded gespeichert.
- loxberry_system.php liest general.cfg nun im RAW-Modus

Beim Mailserver-Passwort (in mail.cfg) wäre das auch ein Thema, betrifft aber nicht die general.cfg und die PHP-Module.
