### ISSUE TITLE
php-soap ins Image

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#477]
Olivers Sonos-Plugin hat nicht mehr funktioniert, weil PHP-Soap gefehlt hat.

Wir haben mit `apt-get install php-soap` (installiert korrekt Soap für PHP7) nachinstalliert, danach hat's funktioniert.

Das muss ins Image rein, war in LB023 auch dabei.

**Comment by svethi** [comment]
Das verrückte daran ist, dass ich es für Fritz.Lox auch brauche, nie extra installieren musste, doch so 1-2 User scheinbar das Problem hatten, dass es fehlt. Angeblich mit originalem Loxberry 0.2.3.

**Comment by christianTF** [comment]
5779365505df8e2bc124d473d695ac93408d3150 installiert das jetzt mal nach, es muss dennoch ins Image rein.
