### ISSUE TITLE
LBUpdate History - Die Links zu Logfile und Download sind falsch

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#478]
Sind immer die gleichen Links zum ältesten File

**Comment by christianTF** [comment]
Das Update Check Log kann man nicht mehr im Logviewer für Live aufmachen

**Comment by Woersty** [comment]
Dann parst die CGI das aber falsch?!

**Comment by Woersty** [comment]
Ah gefunden.

**Comment by christianTF** [comment]
Das Update Check Log kann man nicht mehr im Logviewer für Live aufmachen
