### ISSUE TITLE
LoxBerry::System: Alternative Plugindatabase einlesen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#479]
Hallo Christian,

könntest Du in LoxBerry::System::get_plugins als Option hinzufügen, dass man eine alternative Datei für die pluginsdatabase.dat übergeben kann?

Ich habe noch eine Sicherheitslücke im Pluginsupdate entdeckt: Da cih für das Autoupdate die SecurePIN deaktivieren muss, muss ich die Update-URLs aus einer gesicherten, nicht manipulierbaren pluginsdatabase.dat auslesen, sonst kann man dem System eine andere Update-URL unterschieben. Dazu werde ich eine Art "shadow plugindatabase.dat" bei der Plugininstallation anlegen, auf die nur Root Zugriff hat. Aus der möchte ich die UpdateURLs auslesen.

**Comment by christianTF** [comment]
Verwendung: 
```
$shadowdb = '/tmp/shadow_plugindatabase.dat';
LoxBerry::System::get_plugins(undef, undef, $shadowdb);
```
Die anderen Parameter bleiben gleich, wobei bei Angabe eines Dateinamens jeder neuerliche Aufruf die Datei immer neu liest.

Du kannst übrigens zu Debuggingzwecken generell folgendes machen:
`$LoxBerry::System::DEBUG = 1;`
bzw. 
`$LoxBerry::Web::DEBUG = 1;`
Dann werden bei allen Funktionen mehr Meldungen ins Errorlog geschrieben.
