### ISSUE TITLE
Feature: Tweak the Loxberry

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#48]
Ich habe bei mir aus I/O Performancegründen das Filesystem auf einem schnellen USB Stick.
Boote nur von der SD Karte.
Gab auch noch 1,2 weitere Tipps im Netz wie man dem Raspberry Beine machen kann.
Soll ich da mal was zusammensammeln?
Könnte man dann als Tweak Plugin anbieten.
So in der Art -  Stick erkannt. Soll das Dateisystem umgeschrieben werden? bla bla

**Comment by mschlenstedt** [comment]
Finde ich gut!

**Comment by christianTF** [comment]
Das Overclocking stünde da bei mir an erster Stelle :-) (RPi1)

Bezüglich Logs leite ich auf meinen produktiven Minicomputern viele Logfiles in /run/shm (RAMDisk), um die Schreibzugriffe zu minimieren. Nach Reboot ist zwar alles weg, aber das vermisse ich nicht :-)
So könnte man zur "Verbesserung der Datensicherheit" (der SD-Karte) das logs/plugins/ dort hineinlinken.

**Comment by mschlenstedt** [comment]
Finde ich als Plugin gut.

**Comment by christianTF** [comment]
Kein direktes LB-Thema --> Plugin

Mounten anderer Medien ist ein eigener Issue, deswegen schließe ich das hier.
