### ISSUE TITLE
SD wird nicht vergrößert

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#480]
> [20:42, 21.1.2018] Michael Schlenstedt: Zur resize-Funktion: Früher hatte ich das im loxberry Init-Skript. Aber seit Stretch ist das standardmässig dabei. In /boot/cmdline.txt muss daher folgendes stehen: init=/usr/lib/raspi-config/init_resize.sh

Auch mehrmaliges Rebooten hat die SD nicht vergrößert.
Im 0.3.5.1 Image steht diese Zeile nicht in der cmdline.txt.

Manuelles Ausführen von /usr/lib/raspi-config/init_resize.sh hat zwar automatisch rebootet, aber nichts vergrößert.

**Comment by mschlenstedt** [comment]
Wenn du ein frisches Image auf die SDKarte schiebst, sollte der Eintrag da sein. Nach dem ersten Reboot (und eigentlich resize) löscht die Routine den Eintrag aus der cmdline.txt raus.

Beim alten 0.3.3er hat das meine ich auch funktioniert. Wenn das nicht geht nehmen wir wieder die alte Routine aus 0.2.3. 

Ich teste das nachher mal.

**Comment by christianTF** [comment]
Das ist noch offen. Mein 0.3.5 Image hat sich nicht vergrößert.

**Comment by mschlenstedt** [comment]
Fixed.

**Comment by christianTF** [comment]
Nun endgültig gefixt.
