### ISSUE TITLE
"Legacy" Reboot-Required bei Plugins V1.0

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#487]
Keine Idee, ob das technisch geht.
Output von Postinstall parsen, und wenn das Reboot oder Neustart oder boot oder sowas steht, dann den Reboot anbieten.

oder

Einfach bei Pluginschnittstelle V1.0 immer den Reboot vorschlagen.

Außerdem (für alle Plugins):
Bei Reboot Required auch textuell (evt. rot mit Rufzeichen) über dem Button auf den nötigen Reboot hinweisen.

**Comment by mschlenstedt** [comment]
Ist schon drin:

```bash
# Check for a reboot for older plugins (V1)
system ("cat /tmp/$tempfile.log | grep -iq 'Please reboot' 2>&1");
if ($? eq 0) {
        $preboot = 1;
}
```

**Comment by christianTF** [comment]
Darf ich's auf nur `reboot` ändern?
Die Formulierungen sind zu vielfältig.

**Comment by christianTF** [comment]
Ich habe die Zeile folgendermaßen geändert:
`system ("cat /tmp/$tempfile.log | grep -E -iq 'reboot|restart|neustart|neu starten' 2>&1");`

Das -E erlaubt oder's im String. Hab es damit auf Textfiles getestet und scheint zu funktionieren.
False-Positives sind Pech, dann muss der User halt neu starten.
