### ISSUE TITLE
LbUpdate funktioniert nicht per Cron (Lt. Sven)

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#490]
Auf Svens VM hat das automatische Update nicht funktioniert.

@svethi Kannst du schauen, ob du in ~/system/cron/cron.daily ein lbupdate-scripts (Softlink) hast?

@svethi Kannst du das Check Log hier uploaden.

Installation hätte in der Nacht von 22.1. auf 23.1. Passieren müssen.

**Comment by svethi** [comment]
Nein, da ist nur ein .dummy drin

**Comment by svethi** [comment]
Ich kann in Deinem Code eigentlich auch nirgends finden dass da ein softlink gesetzt werden soll. Im Ajax-Handler werden nur die Werte in der cfg gesetzt. Weiter passiert da nichts.

**Comment by christianTF** [comment]
Das wird wohl der Grund sein ;-)

**Comment by christianTF** [comment]
Issue 1:
Cron-Jobs werden in loxberryinit.sh nicht wiederhergestellt.

Issue 2:
Umstellen des Typs (Disable/Notify/Install) führt das Erstellen/Ändern der Softlinks nicht durch (nur der Zeitplan ändert die Links) --> Hintergrund dürfte gewesen sein, dass die Annahme war, dass der Link immer existent bleibt, weil die Routine selbst abbricht, wenn auf AUS. Prüfen.

**Comment by christianTF** [comment]
:neckbeard:
