### ISSUE TITLE
Plugininstall.html: Autoscroll dreht auch die Aktualisierung des Progress ab

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#493]
Weil Autoscroll jetzt generell den SetInterval abschaltet, wird dann auch die Progress-Ansicht nicht weiter aktualisiert.
Muss man sich ansehen, wie man den Intervall weiterlaufen lässt, ohne das Log zu aktualisieren.

**Comment by Woersty** [comment]
Verstehe nicht was nicht geht. Bei mir läuft das.

**Comment by christianTF** [comment]
Michael hat unter dem Installlog ein Feld, dass den aktuellen Status der Installation anzeigt. Das wird mit dem selben Interval aktualisiert wie das Log.

Wenn du Autoscroll abschaltet, aktualisiert sich auch der Progress nicht mehr. Demnach wird die Installation "nie fertig" (ist natürlich schon fertig), weil dieser Progress nicht mehr aktuell ist.
