### ISSUE TITLE
admin.cgi: SSH-Passwort-Policy ist strenger als unsere Policy

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#496]
4 Zeichen sind bei passwd zu wenig - Passwortänderung über admin.cgi bleibt hängen

**Comment by Woersty** [comment]
Wie ist sie denn?

**Comment by christianTF** [comment]
Keine Ahnung :-)

@mschlenstedt  Ich habe setloxberrypasswd.exp aktualisiert - es liefert jetzt zuverlässig einen Exitcode zurück, wenn etwas nicht passt.

admin.cgi sammelt die Fehler ein und stellt sie dar - Sehr hübsch und auffällig ist die Fehleranzeige aber nicht.
![image](https://user-images.githubusercontent.com/14220265/35305633-53aebc44-009a-11e8-90cf-11d9dd77abc7.png)
(das Gelbe hab ich mit der Hand markiert)

**Comment by mschlenstedt** [comment]
Das müsste vermutlich irgendwo in /etc/pam.d stehen.

**Comment by mschlenstedt** [comment]
Es ist die Datei /etc/pam.d/common-password, dort muss die Zeile im Primary block wie folgt angepasst werden:

```password        [success=1 default=ignore]      pam_unix.so sha512 minlen=4```

Ich nehme das in die Anleitung zur Imageerstellung mit auf. @Woersty Wie ist denn jetzt unsere aktuelle PW-Policy?

**Comment by christianTF** [comment]
Soweit ich mich erinnern kann:
2 klein
1 groß
1 Digit

Es gibt jedoch (wie ich gestern gelernt hab) eine Ausnahme, dass 'loxberry' immer gesetzt werden darf. Entsprechend ist minlen=4 ausreichend, sonst funktioniert die Ausnahme nicht mehr.

**Comment by mschlenstedt** [comment]
In die Imageanleitung übernommen.
