### ISSUE TITLE
Ms-Credentials am Mac testen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#498]
Bezugnehmend auf https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/139820-ersteinrichtung-miniserver-nicht-erreichbar-loxberry-erreichbar

MS-Einrichtung im LB am Mac probieren, mit/ohne Sonderzeichen 
Chrome und Safari

**Comment by christianTF** [comment]
@Woersty Du hast nen Mac?

**Comment by Woersty** [comment]
@Mac mini aber alt und Windows drauf. 👎 
https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/139820-ersteinrichtung-miniserver-nicht-erreichbar-loxberry-erreichbar?p=147577#post147577

**Comment by Woersty** [comment]
Scheint keinen mehr zu interessieren.
