### ISSUE TITLE
Setup - Schritt 2 - Fehler im Text

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#5]
Beim 2. Schritt steht 'notwenidig' statt 'notwendig'

Und aus 'LoxConfig' würde ich 'Loxone Config' machen.

Und der Hilfetext zur IP-Adresse ist teschnisch falsch:
-Falsch: \* Du scheinst keine gültige IP-Adresse eingegeben zu haben. Eine IP-Adresse hat die Form xxx.xxx.xxx.xxx, z. B. 192.168.001.100
-Besser: \* Du scheinst keine gültige IP-Adresse eingegeben zu haben. Eine IP-Adresse hat die Form xxx.xxx.xxx.xxx, z. B. 192.168.1.100

**Comment by mschlenstedt** [comment]
Fixed
