### ISSUE TITLE
Funktion zum Schreiben in die Plugin-DB (plugindatabase.dat)

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#501]
Die plugindatabase.dat wird jetzt an zumindest diesen Stellen beschrieben:

- ~/webfrontend/htmlauth/system/tools/ajax-config-handler.cgi (Ändern der Updates und des Loglevels)
- ~/sbin/plugininstall.pl (Installation und Update)
- ~/sbin/pluginupdate.pl (Automatisches Plugin-Update)

und gelesen

- LoxBerry::System (get_plugins)
- LBSystem (get_plugins)
- ~/sbin/plugininstall.pl (?)
- ~/sbin/pluginupdate.pl (?)

Das Lesen und Schreiben sollte alleine aus einem Modul passieren.

Optimal wäre:
- Mit get_plugins wird vom Entwickler die Pluginliste geholt
- Der Entwickler nimmt sich die Zeile, die er ändern will, und ändert direkt die Werte im Hash
- Die Schreibfunktion wird mit dem Zeilen-Hash als Parameter übergeben
- set_plugin schreibt die Datei neu, sucht dabei den md5 des geänderten Plugins und ersetzt sie mit dem Hash

**Comment by mschlenstedt** [comment]
Noch Notwendig? Oder fixen wir das, wenn wir von ASCII auf SQLite umstellen?

**Comment by christianTF** [comment]
Bewerten wir in der Zukunft neu.

**Comment by christianTF** [comment]
Umgesetzt mit https://github.com/mschlenstedt/Loxberry/issues/1018

Fürs Erzeugen/Ändern/Löschen von Plugins: LoxBerry::System::PluginDB https://www.loxwiki.eu/x/HAKCAw
