### ISSUE TITLE
Layout (Update) passt am iPhone im Portrait gar nicht

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#502]
![abba226b-45f2-4174-9ac8-7b27b2a61c06](https://user-images.githubusercontent.com/22625669/35381290-11898c68-01bc-11e8-9c5f-2ca000843df5.png)

**Comment by christianTF** [comment]
Ich habe mich unglücklicherweise zu einem Tabellenlayout hinreisen lassen.  --> das habt ihr nun davon!
Den Bug nehme ich dir weg, das ist eine nette Änderung für verregnete Tage im Sommer.
PS: Ist sogar schon als Pseudo-Tabelle mit `<div>`'s gestyled.

**Comment by christianTF** [comment]
Das Layout ist überarbeitet. Alle Buttons sind untereinander.
Bei Latest ist der Hash so lange (habe ich auch schon gekürzt), aber bei Release/Prerelease sollte alles passen.

![2affc761-5da1-48e3-95b2-b25c29e45a6c](https://user-images.githubusercontent.com/14220265/35765507-46a17f90-08c5-11e8-87e7-f96390387fc4.png)
![805f2f70-95ba-4f40-b99b-57027485bfbb](https://user-images.githubusercontent.com/14220265/35765508-46cc87d0-08c5-11e8-9a9b-6c90ad6702b9.png)
