### ISSUE TITLE
Errortemplate has nobreak

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#504]
Should be possible to have line breaks in error messages.

**Comment by christianTF** [comment]
Mit dem Template aufpassen, das wird ja auch für Legacy verwendet.
Gleiches Problem gibt's sicher auch in success.html (wird auch für Legacy verwendet).

**Comment by christianTF** [comment]
BTW rufe ich persönlich statt einer Fehlerseite lieber die selbe Seite wieder auf und schreibe den Fehler oben hin, oder zu den Formularfeldern.

Da gibt es einen netten Trick bezüglich der Formularfelder mit HTML::Template und CGI:
```Perl
use CGI;
my $cgi = CGI->new;

my $maintemplate = HTML::Template->new(
		filename => "$lbptemplatedir/index.html",
		global_vars => 1,
		loop_context_vars => 1,
		die_on_bad_params=> 0,
		associate => $cgi,
		%htmltemplate_options,
);
```
Interessant ist hier das ```associate => $cgi```:
Wenn du im Template einen Tag `<TMPL_VAR namefield_error>` hast, und per post `namefield_error="Fehler im Namen"` schickst, befüllt dir HTML::Template automatisch diese Variable im Formular.

Damit kannst du alle Formfields oder auch Fehlerfelder per Post mitschicken und direkt anzeigen ohne Code zum Auslesen und ins Template schreiben.
Nur Select-Fields, Checkboxen usw. muss man trotzdem 'klassisch' befüllen.

In den Widgets verwenden wir nicht `associate => $cgi` sondern `associate => $cfg` und befüllen damit automatisch das Template mit den Variablen aus der general.cfg.

**Comment by mschlenstedt** [comment]
Was machen wir jetzt hier? Oder zu?

**Comment by christianTF** [comment]
Ich weiß nicht genau, worums geht oder wo das Problem ist. Hab das jetzt von Bug zu Enhancement geändert.

**Comment by Woersty** [comment]
Ich komme inzwischen klar wie es ist. Kann zu.
