### ISSUE TITLE
symlink statt copy (pluginsupdate.pl)

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#506]
Hab von pluginsupdate.pl versehentlich ein copy statt eines symlinks in system/cron/cron.weekly/ gemacht.

Beim nächsten Updatescript fixen.

**Comment by mschlenstedt** [comment]
Hattest du das gemacht?

**Comment by christianTF** [comment]
Ich hab das nicht gefixt, ist fürs neue Image aber nicht mehr relevant.
Die 0.3.5er Installationen nehmen wir wegen Apache nicht "mit", alle müssen das neue Image nehmen.
