### ISSUE TITLE
Reboot page zeigt bei reload/Browser neustart wieder den Countdown

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#507]

**Comment by christianTF** [comment]
Lässt sich nicht verhindern.
Wenn die gleiche Seite neu geladen wird, wird auch dessen Inhalt wieder angezeigt.
Wichtig ist, dass dies keinen Neustart des LB auslöst, was auch nicht möglich ist (weil da ja jetzt bereits auf der Power-Übersichtsseite getriggert wird).

**Comment by christianTF** [comment]
Eine Möglichkeit gibt es natürlich doch:

Nachdem die sh-Reboot-Zwangspause von 5 Sekunden vorbei ist, macht man mit JS ein SetInterval mit z.B. 1 Sekunde, und führt damit im Sekundentakt ein $.get gegen den LoxBerry aus.
Im success-Callback-Fall beendet man das Interval und öffnet einfach die Startseite. Solange der Fehlerfall bleibt, probiert man's weiter.

Ein Issue für den Spaßfaktor :-)

**Comment by svethi** [comment]
Geht nicht gibt's nicht

**Comment by Woersty** [comment]
Ja, ja, ja. Bau ich ein.

**Comment by svethi** [comment]
Bist schon raus. Hab ich fertig

**Comment by svethi** [comment]
@christianTF gibt übrigens noch andere Möglichkeiten ;-)

**Comment by christianTF** [comment]
Hab's gesehen :-)
Aber läuft denn der Kill schon, wenn die Seite geladen wird?

**Comment by svethi** [comment]
Nee, der Kill/Restart läuft da noch nicht, würdest ja keine Seite bekommen, aber der Sleeper mit dem Reboot im Anhang ;-)

**Comment by svethi** [comment]
Also ganz klappt das so auch noch nicht. Der Firefox z.B. holt die Datei anscheinend immer aus dem Cache und dadurch läuft die Uhr dennoch immer.
Ebenso lief die Uhr auch immer wenn man reloadet und der LB nicht erreichbar ist sowie wenn das Login abgelaufen ist.
Geht also noch besser.

**Comment by christianTF** [comment]
Macht es mit AJAX. Ist eleganter und stabiler. Außerdem ist man vom Countdown weg, wenn der LB wirklich wieder erreichbar ist, und nicht erst/schon nach 30 Sekunden

**Comment by svethi** [comment]
Also den Counter ganz raus?! Ich hatte auch schon überlegt den refresh zu machen wenn der LB wieder da ist. Ich hab ja eh das Problem, dass die 30 Sekunden bei mir nicht reichen. Müsste dann aber Wörsty machen

**Comment by christianTF** [comment]
Nein, muss nicht ganz raus.
Man könnte ihn aber auf 60 Sek setzen, und wenn die Website per Ajax früher verfügbar ist, redirected man einfach früher
