### ISSUE TITLE
Timing Issue mit dem Logviewer beim Plugininstall

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#510]
Wenn der Logviewer öffnet, bevor etwas ins Log geschrieben wurde, kommt die 0-Byte Meldung.

Das muss man prüfen, ob logview und plugininstall dann den Intervall weiterlaufen lassen, oder generell das Neuladen abbrechen.

**Comment by mschlenstedt** [comment]
Verstehe ich nicht.

**Comment by christianTF** [comment]
Jemand hatte die Meldung, dass das Log beim Installieren eines Plugins 0 Byte hat.

Ich hab den Log Viewer nochmal gecheckt: Selbst wenn ein 0-Byte Log geladen wird, läuft der Refresh weiter und zeigt an, wenn etwas kommt.

Wenn das nochmal Auftritt, muss es derjenige besser erklären, was passiert ist.
