### ISSUE TITLE
GET http://xxx.xxx.xxx.xx/admin/system/images/reboot_required.svg 404 (Not Found)

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#512]
Aus Plugins heraus ist der Pfad falsch.

**Comment by christianTF** [comment]
?

**Comment by Woersty** [comment]
Mach den Debug Mode vom Browser an und ruf ein Plugin auf, wenn reboot_required aktiv ist.

**Comment by christianTF** [comment]
nein, ich assigne es einfach dir, der Code kommt eh von dir :-)

**Comment by christianTF** [comment]
Hat Wörsty schon gefixt mit https://github.com/mschlenstedt/Loxberry/commit/f44defe077197a453241479567094a6242078257#diff-8db13e6f58dee545e15da348fc2d7070

@Woersty Wenn du in den Commit hineinscheibst:
`Fixes #512` dann macht es den Issue automatisch zu und verlinkt zum Commit. 
Sonst ist das sehr mühselig, wenn man eh bereits gefixte Issues anschaut und versucht zu reproduzieren.
