### ISSUE TITLE
Validate: validate_chk_object mit ODER.Verknüpfung

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#514]
Ich habe zwei Felder: Feld1 und Feld2

Beim Abschicken muss nur Feld1 ODER Feld2 validiert sein. Dann soll das Formular erfolgreich abgeschickt werden.

**Comment by Woersty** [comment]
Mach ich. Später. Bald.

**Comment by Woersty** [comment]
http://www.loxwiki.eu/display/LOXBERRY/Validierung+von+Eingabefeldern#ValidierungvonEingabefeldern-1)Voraussetzungenf%C3%BCrdieValidierung
