### ISSUE TITLE
DHCP - IP wird gewechselt

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#515]
Von Peter - sein LB wechselt trotz DHCP bei jedem Reboot die IP. Der alte LB macht das anscheinend nicht.

Dreimal rebooten, und wenn's nciht auftritt, abschließen - dann ist es Sache des DHCP

**Comment by svethi** [comment]
Mehrfache restarts PowerOff PowerOn sowie Umschaltung auf static ip und wieder zurück auf DHCP konnten das Problem nicht reproduzieren. Der LB erhielt stets die selbe IP vom DHCP Server. Problem muss am DHCP Server gesucht werden.
