### ISSUE TITLE
Reboot und Plugininstall verhindern, während ein Update läuft

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#516]
Im Update-Script selbst prüfe ich das so:
```perl
my $pids = `pidof loxberryupdate.pl`;
		# LOGINF "PIDOF LENGTH: " . length($pids) . "\n";
		if (length($pids) > 0) {
			$joutput{'info'} = $SL{'UPDATES.UPGRADE_ERROR_ANOTHER_UPDATE_RUNNING'};
			&err;
			LOGCRIT $joutput{'info'};
			exit(1);
		} 
		LOGOK "No other update running.";			
```

Das sollte gleich im power.cgi alles ausblenden und sagen, da läuft noch was.
PS: Ich hoffe, das geht auch ohne root.

**Comment by christianTF** [comment]
PS: Auch Plugininstall verhindern

**Comment by christianTF** [comment]
Bei Peter am Pi1 dauert das Update von 17:18:16 bis 17:24:06, also 5:50 Minuten.
In der Zeit müssen wir alles verhindern, weil u.a. auch das Resetpermissions so lange dauert (17:19:18-17:21:12), und in der Zeit passen die Rechte nicht, weil zwischen rsync und resetpermissions alles dem loxberry statt root gehört wird.

**Comment by mschlenstedt** [comment]
Setzt ein Lockfile in /var/lock. Darauf prüfen wir und verhindern das Starten.

**Comment by mschlenstedt** [comment]
System::Lock implementieren in Reboot.
