### ISSUE TITLE
Vereinzelt wird bei der Plugin Installation die plugindatabase geschrottet. 

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#517]
Titel sagt schon alles aus. Passiert auch ohne Update im Hintergrund.

**Comment by christianTF** [comment]
Ich glaube das Problem gefunden zu haben - eine Verkettung unglücklicher Umstände.

Aus Faulheit lasse ich Loglevel und Auto-Update Setting per JS im Formular setzen, statt es bereits markiert vom Server zu senden.
Dummerweise triggert aber bereits das Setzen eine Änderung, d.h. bei zwei Plugins mit Auto-Update werden gleichzeitig vier AJAX-Requests abgesetzt.
Und dummerweise habe ich im ajax-config-handler gar nicht abgeprüft, ob sich überhaupt was geändert hat, und immer neu geschrieben.....

Mit dem Commit von oben wird geprüft, ob der gesendete Wert überhaupt eine Änderung enthält. Beim Laden des Formulars kann das gar nicht sein, deswegen wird nichts mehr geschrieben.

Das sollte das Problem schon mal lösen, ich werde aber trotzdem morgen noch das Formular anpassen, damit die Werte vorher schon gesetzt sind.

Ein Locking könnte man noch einbauen, aber es kann damit trotzdem noch potentieller Datenverlust (nicht der ganzen DB) auftreten, weil es müsste schon das parallele **Lesen** der Plugindatenbank mit einem Lock unterbunden werden.

**Comment by mschlenstedt** [comment]
Ich würde trotzdem ein Lock einbauen und das komplette Plugin Management deaktivieren wenn das Lock existiert. 

Zudem müssen wir flock verwenden, wenn wir in die Datenbank schreiben, falls noch nicht geschehen.

**Comment by mschlenstedt** [comment]
Ich habe jetzt bei den PERL-Libs und im Ajax-Handler flock implementiert. In plugininstall.pl fehlte es nur bei den Logfiles (unkritisch). An die LB-Updateskripte unter ~/sbin traue ich mich nicht ran. @christianTF Machst Du das bitte?

```Perl
open (FILEHANDLE);
flock (FILEHANDLE,2);
.......
flock (FILEHANDLE,8);
close (FILEHANDLE);
```

**Comment by mschlenstedt** [comment]
Und dann bitte LOCK-Files in lbupdate implementieren (in plugininstall und pluginsupdate mache ich das). Bitte folgende LOCK-files verwenden und auf die Existenz prüfen:

/var/lock/plugininstall.lock
/var/lock/pluginsupdate.lock
/var/lock/lbupdate.lock

Bei Existenz einer der Lockfiles keine Aktionen ausführen. Zudem werde ich eine entsprechende Meldung im PluginManagement anzeigen und die komplette Seite deaktivieren.

**Comment by christianTF** [comment]
Fürs Locking von Prozessen (Updates usw.), siehe http://www.loxwiki.eu/x/KIOdAQ bzw. https://github.com/mschlenstedt/Loxberry/commit/b3248634a23c09784406d38aa1ea948f1fb9298a

Das müssen wir dann entsprechend an den richtigen Stellen einsetzen:
- Natürlich in den wichtigen Prozessen selbst, und
- Überall, wo wir verhindern müssen, dass etwas passiert, wenn einer der wichtigen Prozesse läuft.

**Comment by christianTF** [comment]
Der concurrency-Issue ist durch meine Anpassung fürs Schreiben der Plugin-Database, sowie durch Michaels Implementieren von File Locking, gefixt.

Das Erstellen von Lock-Files muss man sich in #527 noch anschauen.
