### ISSUE TITLE
Benutzernamen WebAdmin mit Umlauten gehen nur im Chrome

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#52]
Wenn ich mit dem iPad oder IE komme kann ich mich nicht anmelden.
Vielleicht war das mit den Umlauten doch keine so gute Idee?

**Comment by mschlenstedt** [comment]
Ich nehme es wieder raus. "Woersty" ist doch auch nicht so schlecht :-)

**Comment by Woersty** [comment]
Einverstanden.
