### ISSUE TITLE
DNS nicht bereit bei Start von daemon der Plugins

### ISSUE THREAD

**Issue by gahujipo** [mschlenstedt/Loxberry#522]
die DNS-Auflösung funktioniert nicht sofort beim Start der dameon-file von Plugins.

**Comment by svethi** [comment]
Nicht nur DNS ... Netzwerk noch nicht komplett konfiguriert

**Comment by christianTF** [comment]
Cron betrifft es auch - für die Statistik hab ich dafür ein 60-Sek Delay eingebaut.
Das Script bekam Cannot resolve loxberry.de

**Comment by svethi** [comment]
Cron ist ein eigener Dienst, da kann der Start der Loxberry Dienste nicht viel ausrichten.
Die Loxberry Dienste sollten nun auf alle Fälle funktionieren
