### ISSUE TITLE
lighttpd / PHP doesn't stop after closing client browser

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#524]
Test code:
```
<?php
error_reporting(~E_ALL & ~E_STRICT);     // Alle Fehler reporten (Außer E_STRICT)
ini_set("display_errors", false);        // Fehler nicht direkt via PHP ausgeben
ini_set("log_errors", 1);
ini_set("error_log", "/opt/loxberry/log/test.log");
$boundary = "mjpeg_stream";
header("Cache-Control: no-cache");
header("Cache-Control: private");
header("Pragma: no-cache");
header("Content-type: multipart/x-mixed-replace; boundary=$boundary");
print "--$boundary\n";
set_time_limit(0);
@ini_set('zlib.output_compression', 0);
@ini_set('implicit_flush', 1);
for ($i = 0; $i < ob_get_level(); $i++)
ob_end_flush();
ob_implicit_flush(1);
$maxloops=1000;
while ($maxloops > 0)
{
	$maxloops = $maxloops - 1;
	print "Content-type: image/jpeg\n\n";
	$error_image      = @ImageCreate (100, 100);
	$background_color = ImageColorAllocate ($error_image, 0, 0, 0);
	$text_color       = ImageColorAllocate ($error_image, 255, 0, 0);
	ImageString ($error_image, 20, 10, 10, $maxloops, $text_color);
	ImageJPEG ($error_image);
	ImageDestroy($error_image);
	print "--$boundary\n";
	Error_log($maxloops);
	usleep(150000);
}
```

Mit **tail -f /opt/loxberry/log/test.log** könnt ihr dann schauen wie es weiter geht nachdem der Browser zu ist...

**Comment by Woersty** [comment]
Kurze Beschreibung:
Wenn ich Apache + PHP nehme und den Browser schließe ist Ende. So soll es sein.
Wenn ich Lighttpd + PHP nehme und den Browser schließe arbeitet er weiter. Das ist nicht gewollt.
Fragen? Mich fragen!

**Comment by Woersty** [comment]
Achso ich habe einfach eine test.php in einem Pluginverzeichnis erstellt und sie aufgerufen.
`http://loxberry/plugins/pluginname/test.php`

**Comment by Woersty** [comment]
Angezeigt werden müsste ein MJPEG Stream der runterzählt. 
Im Log ebenfalls die Nummer des Druchlaufs.

**Comment by svethi** [comment]
Naja, wenn ich den Code so sehe, ist das ja normal. Der Apache beendet wahrscheinlich den Prozess und würgt das Script damit ab. Sauber ist das aber nicht

**Comment by christianTF** [comment]
Das scheint jedenfalls in diese Kerbe zu schlagen: 
https://redmine.lighttpd.net/issues/2058

Wir haben zwar schon eine neuere Version, wo das gefixt ist, aber entweder unser FastCGI für PHP passt noch immer nicht, oder der Lighty bringt das Abwürgen des Threads nicht zusammen.

Bei mod_php von Apache geht das leichter, weil da PHP ja _wirklich_ im Prozess von Apache läuft.

**Comment by christianTF** [comment]
Die Situation lässt sich wahrscheinlich auch ganz einfach nachstellen per:
```php
<?php
while(1) {
    $i++;
    echo "Hallo $i<br>";
    error_log("Log $i");
    sleep(1);
}
?>
```

**Comment by Woersty** [comment]
> ganz einfach

Vermutlich ja.
Und php-gd muss noch installiert werden, wenn man was sehen will.
Und egal wie was warum - ist doof so.

**Comment by Woersty** [comment]
> Status wurde von Wontfix zu Patch Pending geändert
> Zielversion wurde auf 1.4.40 gesetzt 

Vor 2 Jahren - na toll

**Comment by svethi** [comment]
Problem vom Lighty, das derzeit auch noch nicht in der Entwicklung gefixt ist -> Rücksprung auf apache2

**Comment by mschlenstedt** [comment]
Ich mach's zu. Wir nehmen jetzt Apache und gut.
