### ISSUE TITLE
setenvironment.sh setzt die document-root's der Webserver nicht

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#525]

**Comment by svethi** [comment]
Webserver nutzen nun Variablen für Pfadangaben.
Wird erst aktiv bei neuem Image oder manuellem Wechsel der Dateien

**Comment by svethi** [comment]
Michael, nur für Dich für den Imagebau zur Info. Und vielleicht ein genauer Blick, ob das richtig arbeitet

**Comment by mschlenstedt** [comment]
Teste den Webserver intensiv beim Imagebau. Daher mach ich das zu hier.
