### ISSUE TITLE
Neue OR-Funktion für Validate im Wiki dokumentieren

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#531]
Siehe Betreff.

**Comment by Woersty** [comment]
Schon lange passiert siehe WhatsApp

**Comment by Woersty** [comment]
> data-validation-or - Wenn zwei Felder ODER-verknüpft werden sollen ist im Attribut data-validation-or das jeweilige Partnerobjekt einzutragen. Also zum Beispiel in Feld1: data-validation-or="#Feld2"

**Comment by mschlenstedt** [comment]
Vielleicht bin ich blind und sehe es nur nicht. Aber es muss auf jeden Fall ins WIKI, Whats App und hier nützt nix.

http://www.loxwiki.eu/display/LOXBERRY/Validierung+von+Eingabefeldern

Steht das da orgendwo und ich hab's nur überlesen?

**Comment by Woersty** [comment]
Steht da.

**Comment by Woersty** [comment]
![or](https://user-images.githubusercontent.com/20454116/36048529-d1269f46-0ddf-11e8-97c2-8e20e8fcfdc6.jpg)
