### ISSUE TITLE
Norify und Umlaute gehen nicht?

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#534]
![image](https://user-images.githubusercontent.com/16830799/35775072-e93623a2-0981-11e8-8fc8-8b869196993f.png)

**Comment by christianTF** [comment]
Ich weiß nicht, ob ich das mit dem Umlaut fixen kann. Ich hab jetzt mal versucht, den Commit-Content von Github explizit als UTF-8 anzufordern (ist meiner Ansicht nach aber Standard).
Lt. Notepad++ ist das Notify-File ANSI-Codiert, aber nur dieses. 

Mal sehen, ob das mit dem Content-Type (aus dem referenzierten Commit) hilft. Bei der Ausgabe kann ich nichts ändern, das ist alles UTF8.
_Ob_ es geholfen hat, sieht man erst bei _neuen_ Notifys.

**Comment by christianTF** [comment]
@Woersty Verstehe den Zusammenhang des referenzierten Commits nicht.
Seit diesem Commit hatte ich übrigens einen JS-Fehler wegen eines 0x00h Zeichens am Ende.
