### ISSUE TITLE
Schließen-Button auf "Netzwerkadapter"

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#537]
Bessere Usability bei Handy-Nutzung

![image](https://user-images.githubusercontent.com/14220265/35793065-64f79eca-0a50-11e8-90e2-f0a5995d2bfe.png)

**Comment by Woersty** [comment]
Achso. Das habe ich auch noch gleich angepasst: https://github.com/mschlenstedt/Loxberry/commit/f19f6729601f0ff81055d7cb3276ee5e437180d6
