### ISSUE TITLE
Plugin Management: Notifications

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#539]
1. Aktuell kein Error-Handling (Notifications), wenn ein update fehlschlägt.

2. Notifications sollten beim Plugin erscheinen und nicht oben auf der Seite.

**Comment by christianTF** [comment]
Ist das noch relevant?

**Comment by Woersty** [comment]
Ist es denn gelöst?

**Comment by mschlenstedt** [comment]
Wollen wir hier noch was machen oder zu?
