### ISSUE TITLE
Rasp 3 image 17.07.2016 23:24 not work

### ISSUE THREAD

**Issue by mzsoldos** [mschlenstedt/Loxberry#54]
das image lädt sich am Raspberry nicht starten.

![img_4572](https://cloud.githubusercontent.com/assets/20563463/16996513/edf4885c-4eb1-11e6-9fd2-a21b2401b770.jpeg)

**Comment by mschlenstedt** [comment]
Ist bekannt, wird im nächsten Image behoben. Workaround: https://www.loxforum.com/forum/hardware-zubehör-sensorik/19159-vorstellung-loxberry-projekt-und-umfrage?p=48541#post48541

**Comment by mschlenstedt** [comment]
Fixed.
