### ISSUE TITLE
miniserver.html: Validierung reaktivieren

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#542]
@Woersty 
Für #541 habe ich temporär die Validierung im HTML deaktiviert (auskommentiert), damit die Add und Delete Buttons funktionieren.

Ziel:
Beim Klick der Buttons `addbtn` und `delbtn` soll die Validerung komplett abgeschaltet werden (zumindest aber beim delbtn für den letzten MS der Liste).

https://github.com/mschlenstedt/Loxberry/blob/b261b7b28fcf79a0eb709f84dae5d9d21c2a4907/templates/system/miniserver.html#L312

**Comment by Woersty** [comment]
```
	// If window.validate_override is set, retrun true
	if ( typeof window.validate_override != 'undefined' && window.validate_override == 1 ) 
	{
		return true;
	}

```
Bau das oben in function validate_all() ein in validate.js 
und setze beim Button var window.validate_override = 1;

**Comment by Woersty** [comment]
Umgebaut.
