### ISSUE TITLE
Loxberry_system php notice while retrieving bins

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#547]
PHP Notice:  Undefined variable: miniservers in /opt/loxberry/libs/phplib/loxberry_system.php on line 255

Warum wird da denn überhaupt nach den Miniservern gefragt? Ist auch einer eingegeben.

**Comment by christianTF** [comment]
Abgerufen wird es deswegen, weil ich nur einmal die komplette Config lese und cache, auch wenn du im Script 10x eine der Modulfunktionen aufrufst.

Ich muss mir das aber ansehen, weil ich in Perl schon etwas umgeschichtet habe,  aber in PHP nicht alles nachgezogen.

**Comment by svethi** [comment]
Okay, ich benötige da ausgerechnet nur die bins welche auch korrekt ausgeliefert werden und danach lädst Du erst noch die Miniserver. Ist ja auch nur ein Notice und im Apachelog taucht es nicht auf
