### ISSUE TITLE
plugininstall: Unflexible Größenabfrage

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#548]
https://github.com/mschlenstedt/Loxberry/blob/cb10454628a9759b64fbd0bfa2dc5bd3c23d8cc0/sbin/plugininstall.pl#L253

Die Abfrage auf ein statisches Limit ist schlecht, außerdem geht bei <1.0 Image nichts mehr.

**Comment by mschlenstedt** [comment]
Ja, müssen wir flexibel gestalten.

**Comment by christianTF** [comment]
Mit `unzip -l <file>` bekommt man eine Dateiliste mit komprimierter und unkomprimierter Größe.
Zusammengezählt wüsste man, wieviel Platz (+~10%) noch erforderlich wäre.

**Comment by mschlenstedt** [comment]
So ein grabben der Ausgabe mache ich nicht gerne - da ändert sich das Interface oder LANG ändert sich und schon fällst du auf die Klappe.

**Comment by christianTF** [comment]
Am einfachsten wirklich Größe x 5
Es ist davon auszugehen, dass die Größe des Zips umgekehrt proportional zur entpackten Größe ist, soll heißen: Je größer das ZIP, desto schlechter der Kompressionsfaktor.
Das entpacken schlägt außerdem eh auf, wenn die Disk voll ist.

**Comment by mschlenstedt** [comment]
Ja, aber ein ZIP darf 50 MB haben. D. h. ich müsste maximal 250 MB zur Verfügung stellen.
