### ISSUE TITLE
/usr/bin/xauth:  file /opt/loxberry/.Xauthority does not exist

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#553]
Nervt irgendwie ...

**Comment by mschlenstedt** [comment]
xauth ist für XSessions. Das brauchen wir eigentlich gar nicht... Deswegen gibt's die Vorlage in /etc/skel auch gar nicht.

**Comment by Woersty** [comment]
Weiß ich - darum in `/etc/ssh/sshd_config`
`X11Forwarding yes `
auf
`#X11Forwarding yes `
ändern

**Comment by Woersty** [comment]
Ach ist ja schon gelöst seh ich gerade.

**Comment by Woersty** [comment]
Ach nee - er hat es angelegt.

**Comment by mschlenstedt** [comment]
Siehe #563
