### ISSUE TITLE
Test Mail text

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#556]
LoxBerry hat eine Test Mail verschickt, bitte **prÃŒfe** deinen Mail Posteingang. Eine Zusammenfassung findest du weiter unten.

**Comment by Woersty** [comment]
MAILSERVER.MSG_TEST_INTRO ist aber okay

**Comment by christianTF** [comment]
Das Mail wird wahrscheinlich ohne Encoding Header UTF8 versandt.
