### ISSUE TITLE
Back-Buttons im Wizard (Image)

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#559]
Im 1.0 Image sind die Back-Button im Wizard noch drin (Admin.html)

**Comment by Woersty** [comment]
Raff ich nicht.

**Comment by mschlenstedt** [comment]
Fixed

**Comment by christianTF** [comment]
@Woersty Wir hatten besprochen, dass die Back-Buttons bei einem Wizard mit einer Seite keinen Sinn haben.
Vor allem war auf der Passwort-Übersicht auch noch ein Back-Button, da waren aber schon alle PWs gesetzt. Damit denkt der User, er kann noch zurück, das geht aber nicht, und seine PWs sind dann auch (vom Bildschirm) verloren.

Deswegen haben wir die Back's rausgenommen (und Michael hatte im ersten Image vergessen, dafür die admin.html zu kopieren)
