### ISSUE TITLE
Image fixes

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#561]
```
system/logrotate/logrotate
templates/system/plugininstall_log.html
templates/system/admin.html
templates/system/lang/language_de.ini
templates/system/lang/language_en.ini
webfrontend/htmlauth/system/wizard.cgi
```

`/boot/rootfsresized` löschen

Plugininstall: PreRelease wird immer wieder installiert  https://github.com/mschlenstedt/Loxberry/issues/557 ist lt. Github noch nicht gefixt und können wir auch per Update nachliefern.

**Comment by mschlenstedt** [comment]
Fixed - hopefully.
