### ISSUE TITLE
Wizard: Neues Password:

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#567]
mit t im Deutschen

**Comment by christianTF** [comment]
Das ist [ADMIN]

**Comment by christianTF** [comment]
https://github.com/mschlenstedt/Loxberry/commit/5440facb18c44f679157f3248856bee71b3f9cee
https://github.com/mschlenstedt/Loxberry/commit/09aa7f200b26253594428c8d2a4361695becad17
