### ISSUE TITLE
Default Timeserver invalid

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#569]
👎

**Comment by Woersty** [comment]
Muss in validate.js angepasst werden.

**Comment by christianTF** [comment]
Was ist denn der Default-Timeserver?

**Comment by Woersty** [comment]
>Was ist denn der Default-Timeserver?

Neuerdings:  0.europe.pool.ntp.org

Gelöst mit https://github.com/mschlenstedt/Loxberry/commit/f0657157b2dbcfdd4a92a32b3333b6551eb5ec22
