### ISSUE TITLE
credentialshandler.pl changesecurepin 0000 7530 Exitcode 1

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#571]
credentialshandler.pl changesecurepin 0000 7530 Exitcode 1

Kommt evt. wenn man 2x klickt weil man zu ungeduldig war.
PIN wurde nicht geändert.

**Comment by Woersty** [comment]
Oh. Jetzt sind alle SecurePIN falsch. :-(
Ich kopiere mal die default drüber...
Oh trotzdem. Eieiei.

**Comment by Woersty** [comment]
Ah - das mit "immer falsch" ist ein Problem des Admin-Widgets wenn man nur die Secure PIN ändert

**Comment by christianTF** [comment]
Von mir nicht zu reproduzieren, und von Michael auch nicht. 
Kannst du das immer wieder reproduzieren?

**Comment by Woersty** [comment]
Nein. Wer weiß was das war.
