### ISSUE TITLE
rm-Befehle in setenvironment.sh mit IF-exists prüfen

### ISSUE THREAD

**Issue by michaelmiklis** [mschlenstedt/Loxberry#576]
In der Datei setenvironment.sh werden einige "rm"-Befehle für Dateien aufgerufen. Wenn die Dateien nicht existieren wirft dies unschöne Fehler.

Habe es in meinem Fork angepasst:
https://github.com/michaelmiklis/Loxberry/blob/master/sbin/setenvironment.sh

**Comment by mschlenstedt** [comment]
Mache bitte mal einen Pullrequest Deiner Änderungen. Dann können wir das direkt übernehmen.

**Comment by michaelmiklis** [comment]
Ist erstellt

**Comment by Woersty** [comment]
https://github.com/mschlenstedt/Loxberry/commit/7a5331030d598e0743a94a3ab5e0961a9f46d822
