### ISSUE TITLE
install meldet hardkodierten Pfad zu /opt/loxberry auch in textdateien

### ISSUE THREAD

**Issue by andweber** [mschlenstedt/Loxberry#579]
Install sollte nicht bzgl. /opt/loxberry in Textdateien / Beschreibungen meckern, also z.B.:

statt in pluginstall.pl:

`# Checking for hardcoded /opt/loxberry strings`
`if ( $pinterface ne "1.0" ) {`
`     my $chkhcpath = $findbin $tempfolder -type f -exec $grepbin -li '/opt/loxberry' {} \\;`

per exlude:
`	my $chkhcpath = $findbin $tempfolder -type f ! -name "*.md" -exec $grepbin -li '/opt/loxberry' {} \\;`

**Comment by christianTF** [comment]
Geht auch eine Include-Liste?

**Comment by christianTF** [comment]
Wobei, exclude ist sicherer

**Comment by christianTF** [comment]
`-iname` ist wie `-name`, nur case-insensitive

Mehrere Namen:
`-name "*.py" -o -name "*.html"`
Das -o ist OR
