### ISSUE TITLE
Vorschlag zur Verwendung Clouddns

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#58]
Ich würde vorschlagen im Template die Cloud-DNS-Adresse direkt unterhalb der IP-Adresse einzugeben. Wenn "Cloud-DNS" aktiviert ist sollte die IP-Adresse ausgegraut sein und umgekehrt.

Im Config-File /config/system/general.cfg sollte es eine Varrable geben, ob Cloud-DNS oder lokale IP-Adresse verwendet wird, damit Plugins das auslesen können.

[MINISERVER1]
ADMIN=admin
PORT=80
PASS=geHeim
IPADDRESS=192.168.3.210
CLOUDDNS=http://dns.loxonecloud.com/081508150815
USECLOUDDNS=1

**Comment by Woersty** [comment]
Das ist schon so.
CLOUDURL=http://dns.loxonecloud.com/EEE000D804C7
DNS=checked
Ich habe es extra nach unten gepackt, da ich es als optional gesehen habe.
Aber du hast Recht. Ich blende die normale IP dann aus.
Aber ich kann DNS nach USECLOUDDNS umbenennen - aussagekräftiger - und checked nach 1

**Comment by mschlenstedt** [comment]
Perfekt. Ich konnte es nicht richtig testen, da ich CloudDNS bei mir nicht
eingerichtet habe.

BTW: Ich werde unter "tools" noch eine Funktion ablegen, mit der aus Skripten
direkt die CloudDNS-IP-Adresse ermittelt werden kann. Dann braucht das nicht
jedes Plugin/Script selbst zu implementieren. Pushe ich heute Abend.

Grüße,
Michael

**Comment by Woersty** [comment]
Machste zu, wenn tool fertig, oder?

**Comment by mschlenstedt** [comment]
Habe die Cloud DNS-Geschichte heute nochmal etwas bearbeitet und zudem bei der Erstinstallation einige Bugs bereinigt. Bitte mal testen (im Moment ist nur das deutsche Template aktualisiert).

Tool ist ebenfalls fertig und liegt unter /webfrontend/cgi/system/tools/showclouddns.pl

Syntax: showclouddns.pl MACADRESSE
