### ISSUE TITLE
Veraltete Bezeichnungen Environment Bash

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#580]
http://www.loxwiki.eu/x/qgFmAQ

In Perl hängt überall ein "dir" an Verzeichnisbezeichnungen. Das sollte identisch sein oder?

Fehle rim Wiki oder in der Implementierung?

**Comment by christianTF** [comment]
Kein Fehler, das war Absicht
Die Environmentvariablen der Bash haben den Pluginnamen nicht drin.

$lbphtmlauthdir in Perl/PHP ist /opt/LoxBerry/webfrontend/htmlauth/plugins/squeezelite
$LBPHTMLAUTH in Bash Ist /opt/LoxBerry/webfrontend/htmlauth/plugins

Deswegen auch der Unterschied in der Bezeichnung, dass es da keine Missverständnisse gibt.
