### ISSUE TITLE
Plugininstall log nicht auf ramdisk

### ISSUE THREAD

**Issue by andweber** [mschlenstedt/Loxberry#582]
Wenn ich es richtig verstehe, ist das log der Plugin install derzeit auf der Ramdisk.
Es wäre zu überlegen, zumindest dieses permanent zu speichern.

In meinem Fall hing die Installation eines Plugins zweimal in der Nähe der Installation der *.deb Pakete. Offensichtlich hat der RPi auch neu gestartet. Da ich kein log mehr finden kann - lässt sich das Problem schlecht untersuchen. Kann ein Fehler sein - oder hat einfach nur Lange gedauert.

**Comment by christianTF** [comment]
Hallo @andweber ,

War das zufällig beim Sonos-Plugin, wo es hängen geblieben ist?

Während der Installation liegt das log in `/tmp/` (mit einem generierten Namen).
Nach erfolgreicher Installation wird das Log auf die SD-Karte _kopiert_, damit es aus der Plugin-Verwaltung zu öffnen ist. Das File in /tmp wird dabei nicht gelöscht, also auch nach einer gescheiterten Installation ist das Log noch dort.

Einen Reboot macht LoxBerry nur in einem Fall automatisch, das ist, wenn ein Raspbian Security-Update einen Reboot anfordert.
Alle Funktionen von LoxBerry, die einen Reboot benötigen, informieren darüber nur, führen diesen aber nicht selbst aus.

lg, Christian

**Comment by andweber** [comment]
nein, es war mein eigenes Plugin und AnyPlugin, dass ich testweise probiert habe. 
Die Plugininstallation führte bei Beiden regelmäßig zu einem reboot - ungewollt - d.h. das Installskript war noch nicht am Ende.
Ich teste jetzt eine andere SD-Karte - ich glaube derzeit nicht dass es an LoxBerry selbst liegt.

Danke für den Hinweis mit tmp - dort habe ich nicht geschaut.
