### ISSUE TITLE
Wunsch: Plugin-Übersicht "Check now" button für updates

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#585]
:+1:

**Comment by Woersty** [comment]
Dachte, man könnte einfach einen Crontab Job machen, der einmal ausgeführt wird und sich dann beendet.
Oder kann ich aus dem CGI heraus das Updatescript als root triggern? 

+Update Button nicht nur im Notify sondern auch beim Plugin:
![image](https://user-images.githubusercontent.com/20454116/36099353-a707783c-1002-11e8-91fa-7e3594f8ffb2.png)
Mit anderem Icon dann natürlich

**Comment by Woersty** [comment]
Oder Dropdown mit Aktuell installierte Version, Release, Pre-Release und dazugehörig einen Button?

**Comment by Woersty** [comment]
Wofür ist eigentlich der Logging Level?

**Comment by christianTF** [comment]
Logging: http://www.loxwiki.eu/display/LOXBERRY/Usage+of+the+logging+module

**Comment by christianTF** [comment]
Bezüglich Buttons für Update in der Pluginzeile/Notify: Hier keine Energie mehr hineinstecken, das wird mit SQLite basiertem Notify flexibler.

Check Now Button wäre natürlich praktisch

**Comment by Liver64** [comment]
würde ich auch sehr begrüßen

**Comment by christianTF** [comment]
Das wird in 1.0.3 (mit dem neuen Notify) oder 1.0.4 kommen

**Comment by christianTF** [comment]
https://github.com/mschlenstedt/Loxberry/commit/deb9e649aa3866506a9858534e89118e97fe9847
