### ISSUE TITLE
Nach update auf 1.0.1 nicht mehr erreichbar

### ISSUE THREAD

**Issue by Strike1988** [mschlenstedt/Loxberry#590]
Nach update auf 1.0.1 ist der Loxberry nicht mehr erreichbar.

**Comment by christianTF** [comment]
Bootet er? SSH?

**Comment by Strike1988** [comment]
SSH ist erreichbar

**Comment by christianTF** [comment]
Behebt sich das auch nicht nach einem weiteren Reboot?

Dann bitte 
- Als root anmelden
- `service apache2 restart` ausführen
- Wenn Apache dann geht, bitte nochmal rebooten und testen
- Wenn nicht, bitte ` apachectl configtest` ausführen. Außer ` Could not reliably determine the server's fully qualified domain name` sollte kein Fehler kommen.

Wenn alles nichts hilft, bitte das Image nochmal ziehen.

Das Update hast du auf "Release" ausgeführt, oder auf einen anderen Stand (Pre-Release, Latest)?

**Comment by Strike1988** [comment]
Nach `service apache2 restart` ist er wieder erreichbar. Jedoch nach einen Neustart nicht.

`apachectl configtest` hat folgendes ausgegeben:

![image](https://user-images.githubusercontent.com/22750878/36247436-4f486258-1234-11e8-83be-683e4c92aa27.png)

**Comment by Strike1988** [comment]
Kann das was mit der Netzwerkconfig zu tun haben? Da ich bereits vorher die 1.0.1 version installiert hatte und da lief alles bis ich die Adresse statisch gemacht habe. Dies ist jetzt schon der zweite Anlauf der Installation.

**Comment by christianTF** [comment]
Ich habe das bei mir mit einer fixen IP probiert, aber klappt alles.

Bitte im `/var/log/syslog` nachschauen, ob es irgendwelche Meldungen in Bezug auf Apache2 gibt.
Ebenso im Apache-Log `/opt/loxberry/log/system_tmpfs/apache2/error.log`.

Ist das Pi 1, 2 oder 3, und verbindest du mit LAN oder Wifi?

lg, Christian

**Comment by Strike1988** [comment]
Raspi 3 / LAN
Folgendes wurde ausgegeben. Kannst du damit was anfangen?

/opt/loxberry/log/system_tmpfs/apache2/error.log : 

[Thu Feb 15 20:06:43.530852 2018] [mpm_prefork:notice] [pid 608] AH00163: Apache/2.4.25 (Raspbian) configured -- resuming normal operations
[Thu Feb 15 20:06:43.531037 2018] [core:notice] [pid 608] AH00094: Command line: '/usr/sbin/apache2'
[Thu Feb 15 20:06:51.324818 2018] [mpm_prefork:notice] [pid 608] AH00169: caught SIGTERM, shutting down
[Thu Feb 15 20:06:51.738438 2018] [mpm_prefork:notice] [pid 890] AH00163: Apache/2.4.25 (Raspbian) configured -- resuming normal operations
[Thu Feb 15 20:06:51.738579 2018] [core:notice] [pid 890] AH00094: Command line: '/usr/sbin/apache2'
[Thu Feb 15 20:06:54.562178 2018] [mpm_prefork:emerg] [pid 904] (43)Identifier removed: AH00144: couldn't grab the accept mutex
[Thu Feb 15 20:06:54.571319 2018] [mpm_prefork:emerg] [pid 906] (43)Identifier removed: AH00144: couldn't grab the accept mutex
[Thu Feb 15 20:06:54.571287 2018] [mpm_prefork:emerg] [pid 905] (43)Identifier removed: AH00144: couldn't grab the accept mutex
[Thu Feb 15 20:06:54.746693 2018] [core:alert] [pid 890] AH00050: Child 904 returned a Fatal error... Apache is exiting!
[Thu Feb 15 20:06:54.746806 2018] [:emerg] [pid 890] AH02818: MPM run failed, exiting
[Thu Feb 15 20:06:54.748187 2018] [mpm_prefork:emerg] [pid 932] (22)Invalid argument: AH00144: couldn't grab the accept mutex
[Thu Feb 15 20:09:19.036955 2018] [core:warn] [pid 1064] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Thu Feb 15 20:09:19.049414 2018] [mpm_prefork:notice] [pid 1064] AH00163: Apache/2.4.25 (Raspbian) configured -- resuming normal operations
[Thu Feb 15 20:09:19.049494 2018] [core:notice] [pid 1064] AH00094: Command line: '/usr/sbin/apache2'

**Comment by christianTF** [comment]
@svethi hat das gleiche angesprochen.
Hast du schon Plugins drauf (wenn das Problem Auftritt)? (Welche?)
Vielleicht können wir das mit Sven abgleichen.

Wir machen uns Mal auf die Suche bei Google.

**Comment by Strike1988** [comment]
Lediglich "Wunderground 4 Loxone" in der  Version 4.0-BETA.

**Comment by christianTF** [comment]
https://help.directadmin.com/item.php?id=411

Könntest du diese Optionen bei dir Mal probieren, ob das was hilft.

Unsere Apache-Config liegt unter /opt/loxberry/system/apache2/apache2.conf

Wenn's hilft, bitte kurz sagen, welche Option es gebracht hat.
Wir können das dann für andere mit ausliefern.

PS: WU4LOX ist kritisch, weil Michael meines Wissens da auch die Config anpasst - vielleicht liegt es daran.

@svethi Was hast du drauf, auch WU4LOX?

**Comment by svethi** [comment]
Also meiner hat das heute noch nicht wieder gemacht. Was habe ich gemacht?! Ich hatte zum Test wunderground4beta installiert. Beim deinstallieren wurde nicht alles korrekt deinstalliert. Unter /opt/loxberry/system/apache2/sites-enabled gab es die Config für wu4lox noch. Diese habe ich gelöscht, jetzt ist ist er noch nicht wieder ausgefallen

**Comment by svethi** [comment]
Das ist ja komisch. Als ich meinen Kommentar geschrieben habe, waren die beiden Vorherigen noch nicht da.
Nun, es scheint ja doch irgendwie am wu4lox zu liegen. Ich kann mir nur nicht erklären warum.

**Comment by Strike1988** [comment]
Ich habe mittels (als Superuser)
`nano /opt/loxberry/system/apache2/apache2.conf`
am Ende folgendes eingefügt
> #Loxberry
> Mutex posixsem

Und nun läuft es auch nach einen neustart. Ich kann es aber nicht beurteilen, ob die Deinstallation von WU4LOX und Entfernung der datei oder diese Variante sauberer ist?! Ich könnte die Variante von @svethi auch nochmal testen, wenn euch das bei der Entwicklung hilft.

/opt/loxberry/log/system_tmpfs/apache2/error.log :

[Fri Feb 16 09:35:14.763504 2018] [mpm_prefork:notice] [pid 16937] AH00163: Apache/2.4.25 (Raspbian) configured -- resuming normal operations
[Fri Feb 16 09:35:14.763672 2018] [core:notice] [pid 16937] AH00094: Command line: '/usr/sbin/apache2'
[Fri Feb 16 09:36:40 2018] power.cgi: Use of uninitialized value in transliteration (tr///) at /opt/loxberry/webfrontend/htmlauth/system/pow$
[Fri Feb 16 09:36:40 2018] power.cgi: Use of uninitialized value $query{"lang"} in substr at /opt/loxberry/webfrontend/htmlauth/system/power$
[Fri Feb 16 09:36:40 2018] power.cgi: Use of uninitialized value $do in string eq at /opt/loxberry/webfrontend/htmlauth/system/power.cgi lin$
[Fri Feb 16 09:36:40 2018] power.cgi: Use of uninitialized value $do in string eq at /opt/loxberry/webfrontend/htmlauth/system/power.cgi lin$
MENU called

**Comment by Strike1988** [comment]
Jetzt funktioniert das WU4LOX plugin nicht mehr. Daten werden nicht gesendet und die Webanzeige des Wetters.

![image](https://user-images.githubusercontent.com/22750878/36300062-01791aa0-1300-11e8-808e-82550f306425.png)

**Comment by christianTF** [comment]
@Strike1988 Wenn bestätigt das WU4LOX das Problem verursacht, ist es kein Problem von LoxBerry.

WU4LOX 4 (Beta) ist für LoxBerry 1.0 noch nicht freigegeben.

Ich hab das als Issue bei wu4lox angelegt: 
https://github.com/mschlenstedt/LoxBerry-Plugin-WU4Lox/issues/13

**Comment by svethi** [comment]
Ja, genau, das Plugin hat leider mit LB1 mehrere Baustellen. Diese jetzt rührt daher, dass zum Schutz der SD-Karte vieles in tmpfs ausgelagert wurde. Das bedeutet, dass alles was in tmpfs Verzeichnisse abgelegt wird nach einem Neustart einfach weg ist.
Du kannst das beheben, indem Du in das Verzeichnis /opt/loxberry/data/plugins/wu4lox/ gehst und dort die 3 defekten Links löschst. Also 'unlink current.dat hourlyforecast.dat dailyforecast.da' (ich hoffe, ich habe die Namen noch richtig im Kopf).
Diese werden dann als Dateien neu angelegt. Dann sollte das funktionieren.
Das mit dem Mutex, kannst Du wahrscheinlich wieder rausnehmen. Das Problem ist scheinbar, dass die Emu Seite mit Accesslog eingerichtet ist. Das Accesslog wird aber gar nicht geführt und daher gibt's dies nicht. Er versucht es zwar anzulegen, doch macht er dies als root und der Apache kann dann da nicht reinschreiben. Die Fehlermeldung ist leider nicht sehr zielführend. Du musst einfach nur in der Datei /etc/apache2/sites-aveilable/001-wu4lox.conf die Zeile mit dem access.log auskommentieren (Raute davor)

**Comment by Strike1988** [comment]
Ich habe jetzt die normale Version installiert, bevor ich mir hier alles kaputt mache. Hatte mir das wegen den Cloud Emulator installiert.
