### ISSUE TITLE
Plugininstallation Upgrade erzeugt Duplikat in der Pluginliste

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#593]

**Comment by mschlenstedt** [comment]
Welches Plugin? Oder ist das bei allen so?

**Comment by svethi** [comment]
Ja, kann ich reproduzieren.
Weiß auch schon wo das Problem liegt. Das passiert wenn der Autor seine E-Mail ändert

**Comment by mschlenstedt** [comment]
Das ist klar, die geht in die MD5 Checksumme mit ein. 

Steht auch so in der Beschreibung :-)

Dann ist das kein Bug und das kann zu hier.

**Comment by svethi** [comment]
Naja, also ganz so einfach ist das auch nicht. Wenn der Installer also davon ausgeht dass das 2 verschiedene sind, dann darf er aber auch nicht das andere Verzeichnis nehmen. Jetzt habe ich den Fall, dass das selbe Plugin doppelt in der Liste steht, es aber nur einmal installiert ist. Lösche ich das Eine, ist das andere kaputt.
Das geht aber auch nicht.

**Comment by mschlenstedt** [comment]
Da stimmt. Das muss ich mir anschauen. Er müsste 2 unterschiedliche Namen und Verzeichnisse nehmen.

**Comment by christianTF** [comment]
Die Frage, die ich in den Raum stelle: Sollen wir das MD5-System mittelfristig aufgeben. 
Können wir uns nicht darauf verlassen bzw. festlegen, dass der foldername aus der plugin.cfg (gegenüber anderen Plugins) unique sein muss.
Der "ganze" LoxBerry basiert jetzt auf den foldername des Plugins, um zu erkennen, _dass_ und _welches_ Plugin es ist.

**Comment by svethi** [comment]
Viele ändern auch immer mal wieder die email Adresse. Es gibt dann kein Upgrade, alle Einstellungen sind weg und man hat das Plugin doppelt in der Liste. Das finde ich nicht gerade sinnvoll. Okay, wenn es denn wirklich separat ist, auf der anderen Seite muss man dann überall die URL's ändern.

**Comment by mschlenstedt** [comment]
Das können wir auf jedenfall nicht einfach ändern. Dann kommt alles durcheinander. Einfach die E-Mail-Adresse nicht ändern :-)

**Comment by mschlenstedt** [comment]
Der Foldername alleine geht nicht, da dieser bei Doppelung geändert sein kann, z. B. fritz4lox01, falls es schon ein fritz4lox gibt. Das funktioniet zum Zeitpunkt der Installation nicht.

**Comment by christianTF** [comment]
Logisch - Aber wenn by design der Foldername vom Plugin-Autor unique sein muss, fällt das alles weg.

**Comment by christianTF** [comment]
PS: Aber ich greif da jetzt sowieso nix an.

**Comment by christianTF** [comment]
Schließe ich jetzt, weil das eh nicht einfach geändert werden kann, sondern dafür ein neues Konzept entwickelt werden müsste, wo dann die Plugin-Datenbank, die Plugin-Installation und alle Module angepasst werden müssten.
