### ISSUE TITLE
Image-Anleitung soll Releases/Tags zum Clonen verwenden

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#595]
Branchen ist zusätzliche Arbeit (und ich hab nicht herausgefunden, wie es geht)
In der Anleitung soll stehen, wie man ab einem Tag cloned, und dass man den letzten "Release" (nicht Pre-Release) nehmen soll

**Comment by mschlenstedt** [comment]
Hier steht etwas dazu: https://stackoverflow.com/questions/791959/download-a-specific-tag-with-git

Kann es hier gerade nicht testen, aber vielleicht kann man auch einfach das tar Archiv des Release nehmen. Da müssten die Symlinks eigentlich passen.

**Comment by christianTF** [comment]
Close - Michael hat's dazugeschrieben, wie's richtig geht.
