### ISSUE TITLE
Form validation auch für selects/checkboxen/dropdwon und radiobutton

### ISSUE THREAD

**Issue by Liver64** [mschlenstedt/Loxberry#597]
die Form Validierung umfasst leider nicht die o.g. Typen. Es wäre durchaus sinnvoll prüfen zu können ob ein Eintrag auch ausgewählt wurde.

**Comment by Woersty** [comment]
Eine CHECKBOX hat doch immer nur einen von 2 Werten: an oder aus 
Was soll da validiert werden?
Außerdem kannst du dich doch im Code einfach dran binden und mit **if** testen:
` if ( $(this).is(':checked') ) { bla } else { blub };`

Bei SELECT kannst du einfach **required** setzen.
Siehe am Ende von https://github.com/Woersty/LoxBerry-Plugin-cam-connect/blob/master/templates/cam_connect.html#L154-L155

**Comment by Woersty** [comment]
Beim Radiobutton kann man auch nichts falsches auswählen, oder?
Das Validate war eher dafür gedacht, ungültige Werte abzufangen.
Bei den o.g. Typen gibt der Programmierer ja die Werte fest vor.

**Comment by Liver64** [comment]
raidobutton und checkbox hast du recht, nur select geht nicht da a: dynamisch während der runtime aus JSON Dateien gefüllt und b: in Abhängigkeit vom Radiobutton unterschiedliche Validierung.
Klar kann ich die mit Code umschiffen bzw. realisieren, nur weiß ich nicht ob es im Sinne des Erfinders ist sich ggf. eine eigene Validierung zu coden.
Macht es da nicht eher Sinn eines der vielen guten Validierungs Plugins als Standard zu wählen? Deine/eure Arbeit in allen Ehren, ist wirklich TOP

**Comment by Woersty** [comment]
Die Frage ist, was du brauchst. Dann bau ich das nach. Die Validierungs Plugins haben alle nicht das gemacht was ich wollte oder waren Overkill.

**Comment by christianTF** [comment]
Frage in die Runde: Noch aktuell?

**Comment by Liver64** [comment]
ja, langfristig wäre es durchaus hilfreich, muss aber nicht unbedingt eine hohe Priorität haben

**Comment by Woersty** [comment]
Ich habe nochmal drüber nachgedacht und weiß nicht genau wie das realisierbar wäre.
Nochmal: Was genau wäre der "use-case"?
Ich habe es bisher nicht gebraucht oder mit wenigen Zeilen Code selbst gebaut.
