### ISSUE TITLE
plugindatabase.dat auf SQLLite umstellen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#602]
Umstellen auf SQLLite und Schreiben der Datenbank in die Libs verlagern.

**Comment by mschlenstedt** [comment]
Och nöööö..... Die paar Spalten und Zeilen sind in der Textdatei gut aufgehoben (finde ich). Die Probleme an der Notification-SQL sind auch erheblich.

Wir lassen das erst einmal wie es ist. Vielleicht später mal.

**Comment by christianTF** [comment]
Notify hat noch nie Probleme gemacht - die LogDB, Jep - die hat Probleme gemacht.
Wenn’s mal Bedarf an vielen neuen Spalten gibt, greifen wir das wieder auf.

**Comment by christianTF** [comment]
Umgesetzt als json: https://github.com/mschlenstedt/Loxberry/issues/1018
