### ISSUE TITLE
Datum im Notify nicht laut Zeitzone

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#603]
Notify von 19:45 h aber es ist 20:45 h

**Comment by christianTF** [comment]
Gefixt mit https://github.com/mschlenstedt/Loxberry/commit/6442c868f0571d530147a855d29a6a8684df7db0

Du musst die Datenbank `/opt/loxberry/system/data/notifications_sqlite.dat` löschen.
Das Update 1.0.3 Script wird die DB bei allen "Lastest Commit" users auch nochmal löschen.

Die timestamp Column wird jetzt per Default als localtime statt GMT befüllt. Das ist besser als es beim Auslesen umzurechnen.
