### ISSUE TITLE
eMail Notify

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#604]
![image](https://user-images.githubusercontent.com/20454116/36566366-9371df78-1823-11e8-90a9-08a630f31de6.png)

-Betreff
-UTF-8
-loxberry LoxBerry (http://loxberry:80/)

**Comment by christianTF** [comment]
1. Betreff: Kannst du mir sagen, wie dein Notify aussieht?
Der Betreff setzt sich zusammen aus 
`$friendlyname LoxBerry Info/Error in $package $name`
oder 
`$hostname LoxBerry Info/Error in $package $name`

2. Muss ich fixen
3. Gehört so (Hostname:Port)

**Comment by Woersty** [comment]
Bau ich mal um

**Comment by Woersty** [comment]
https://tools.ietf.org/html/rfc6531

**Comment by Woersty** [comment]
Funktioniert alles nicht. Habe keine Lust mehr.
