### ISSUE TITLE
Umlaute noch kaputt

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#607]
25.02.2018 10:52: LoxBerry Updatecheck: New commit from **WÃ¶rsty** on 2018-02-25T09:46:50Z, message validate.js: Validation rule 'domainname_or_ipaddr' changed<br> <br> -Support more subdomains now.

**Comment by Woersty** [comment]
\<br\> sind auch noch drin

**Comment by christianTF** [comment]
Umlaute gefixt, <br> gefixt, mit https://github.com/mschlenstedt/Loxberry/commit/f27ba35cad29d47fe57b61163acb7a6a619c56be
