### ISSUE TITLE
loxberryupdatecheck.pl Notify mit 133

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#608]
Wenn Github 403 forbidden (zu oft angefragt) liefert kommt ne Mail mit "133" als Text.

**Comment by christianTF** [comment]
Bei Latest, oder?

**Comment by christianTF** [comment]
War wahrscheinlich, weil $SL zu dem Zeitpunkt noch nicht initialisiert war. Das hat sich mal geändert, $SL wird jetzt früher initialisiert.
Kann aber nichts genaueres sagen, weil ich die Umstände und den genauen Output wissen müsste.
