### ISSUE TITLE
Emails von root wegen blöder Rechte

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#610]
![2e2c2b35-e1fb-4362-b1d8-8d110c989cf0](https://user-images.githubusercontent.com/20454116/36656745-010691e8-1aca-11e8-81b8-0832fce7638b.jpg)
![7543653d-577c-4f7f-8bbe-d199a15b97a2](https://user-images.githubusercontent.com/20454116/36656746-011e9ac2-1aca-11e8-9947-acd4dc1d478b.jpg)
![ef1dfaad-698c-48b4-8edb-f6a2380e34a1](https://user-images.githubusercontent.com/20454116/36656748-013b2a66-1aca-11e8-81c3-8738cf211ad3.jpg)

**Comment by Woersty** [comment]
Kannst du da was mit chmod 6755 verbiegen? (Sticky Bit)

**Comment by mschlenstedt** [comment]
Habe ich auch schon gekriegt. Wann schlägt das auf? Beim Update?

**Comment by christianTF** [comment]
Das kommt, wenn genau ein cronjob zwischen rsync und resetpermissions dran kommt.
Das $updatedir in /tmp/ gehört loxberry, es wird in $lbhomedir hinübergesynct, und dann kann es dazu kommen, dass kurzzeitig irgendwo der Eigentümer nicht passt.

In diesem Fall war es /system/sudoers/lbdefaults. Das wird überhaupt nur "manuell" per Update-Script angefasst, sonst gar nicht. Aus meiner Sicht fällt das in die Kategorie "Bad luck".

Eventuell würde sich das mit https://github.com/mschlenstedt/Loxberry/issues/399 beheben lassen, allerdings will ich kein zweites Resetpermissions bauen, sondern - wenn - dann müsste das gleiche Script für beide Ordner funktionieren.

**Comment by christianTF** [comment]
lbupdate setzt jetzt im temporären $updatedir ein paar Dateien auf root:root, bevor sie mit rsync kopiert werden. 
Mal sehen, ob das ausreicht, oder ob noch was fehlt.

**Comment by christianTF** [comment]
Nix mehr gehört seit langem -> Close
