### ISSUE TITLE
String "Logging Level" in plugininstall cgi not in language.ini

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#611]

**Comment by Woersty** [comment]
![image](https://user-images.githubusercontent.com/20454116/36662784-d3798a12-1adf-11e8-98a8-3c3e0609f11c.png)

**Comment by Woersty** [comment]
Automatic Updates auch nicht.

**Comment by Woersty** [comment]
Die Level auch nicht.

**Comment by christianTF** [comment]
Ich hab's damals nicht für nötig gehalten, weil das eh immer gleich ist. Kann man anpassen

**Comment by Woersty** [comment]
https://github.com/mschlenstedt/Loxberry/commit/d60b55e5b341d187c73546a9256aacb4f6da42ed
