### ISSUE TITLE
Meldung jeden Tag 

### ISSUE THREAD

**Issue by Fuxifux** [mschlenstedt/Loxberry#614]
Hallo bekomme per Mail jeden Tag in der früh diese Meldung:

/etc/cron.daily/logrotate:
Warning: apache2.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: apache2.service changed on disk. Run 'systemctl daemon-reload' to reload units.

**Comment by christianTF** [comment]
Evt. https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=160476

**Comment by christianTF** [comment]
Hallo @Fuxifux 

Könntest du das bei dir probieren:

Datei /opt/loxberry/system/logrotate/logrotate bearbeiten:
Beim apache2-Block die systemctl-Zeile ergänzen.

```
postrotate
if /etc/init.d/apache2 status > /dev/null ; then \
/bin/systemctl daemon-reload; \
/etc/init.d/apache2 reload > /dev/null; \
fi; \
endscript
```

Wenn das bei dir hilft, nehmen wir das mit hinein ins nächste Update.

LG Christian

**Comment by Fuxifux** [comment]
Werde ich testen. Danke. Melde mich asap.

**Comment by Fuxifux** [comment]
Habe die Zeile gestern ergänzt. Der Fehler kommt noch, aber nurmehr einmal:

/etc/cron.daily/logrotate:
Warning: apache2.service changed on disk. Run 'systemctl daemon-reload' to reload units.

**Comment by Fuxifux** [comment]
Habe natürlich gemeint nicht einmal, sondern ein anderer.

**Comment by mschlenstedt** [comment]
Bei mir funktioniert Christian's Tipp:

```
        postrotate
                if /etc/init.d/apache2 status > /dev/null ; then \
                    /bin/systemctl daemon-reload; \
                    /etc/init.d/apache2 reload > /dev/null; \
                fi;
        endscript

```

**Comment by mschlenstedt** [comment]
Zusätzlich habe ich noch /etc/logrotate.d/apache2 gelöscht. Die Datei wird nicht benötigt.

**Comment by christianTF** [comment]
@mschlenstedt Nimmst du die beiden Änderungen in 1.0.4 rein?

**Comment by mschlenstedt** [comment]
So geht's bei mir seit ein paar Tagen:

```
        postrotate
                if /etc/init.d/apache2 status > /dev/null ; then \
                    /bin/systemctl daemon-reload; \
                    /etc/init.d/apache2 reload > /dev/null; \
                fi;
        endscript
        prerotate
                /bin/systemctl daemon-reload; \
                if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
                        run-parts /etc/logrotate.d/httpd-prerotate; \
                fi; \
        endscript
```
