### ISSUE TITLE
logfile.cgi: Übergabe eines absoluten Pfades unterstützen ($lbplogdir)

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#619]
Das logfile.cgi soll die Übergabe eines absoluten Pfades unterstützten, damit die Übergabe von `$lbplogdir/logfile.log` funktioniert.

**Comment by mschlenstedt** [comment]
Aber aufpassen, dass keine Sicherheitslücke entsteht, z. B.  /etc/passwd 

Es dürfen trotzdem nur ausgewählte absolute Pfade erlaubt sein.

**Comment by christianTF** [comment]
Umgesetzt mit https://github.com/mschlenstedt/Loxberry/commit/16e7c20745cea64f91b3fd060cc54aaa3f379ced#diff-39553f50450ee45eeed051edd5b583a2
