### ISSUE TITLE
Plugininstall Daemon Dateiname 

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#623]
Bei Olivers Sonos heißt der Daemon nicht PLUGINFOLDER sondern PLUGINNAME.

Das dürfte so nicht richtig sein, oder?

**Comment by mschlenstedt** [comment]
Ist richtig so: Dateien heissen PUGINNAME, Verzeichnisse heissen PLUGINFOLDER.

**Comment by christianTF** [comment]
Dateien die derzeit Unique sein müssten:

- daemon
- sudoers
- crontab
- uninstall

**Comment by mschlenstedt** [comment]
Können wir nicht umsetzen ohne die Kompatibilität zu verlieren -> es gibt zahlreiche Plugins, die NAME und FOLDER unterschiedlich benannt haben. Wenn einer dieser Plugins auf die Dateien direkt zugreift, wäre das Plugin bei Änderung kaputt.

Die Dateien heissen (wie schon immer) NAME, das Pluginverzeichnis FOLDER.

Nachteil: 

Aus Skripten (betrifft aktuell den DAEMON und die Skripte unter cron.d) kann das Pluginverzeichnis nicht mit "basename" ermittelt werden. Es muss zwingend (wie es die Anleitung zur Entwicklung von Plugins http://www.loxwiki.eu/x/-QJmAQ auch empfiehlt) mit REPLACELBPPLUGINDIR gearbeitet werden. Basename funktioniert nur, wenn NAME und FOLDER gleichgesetzt werden.

Siehe http://www.loxwiki.eu/x/J4K3AQ
