### ISSUE TITLE
Plugin-Samba-Config einbinden

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#624]
Möglichkeit bereitstellen, dass ein Plugin eigene smb.conf Abschnitte mitliefern kann.

Apache kann mit `include=` andere Dateien einbinden.

Man könnte

- Einen festen Pfad festlegen, wo ein Plugin seine smb.conf hat (z.B. $lbpdatadir/smb.conf.include)
- Eine Routine schreiben, die diese Dateien sucht, prüft (ich glaube es gibt ein Samba-Config-Check-Tool) und in die System-smb.conf included.
- Die Routine wird beim Plugininstall ausgeführt
- Die Routine wird bei LBUpdate ausgeführt

**Comment by mschlenstedt** [comment]
Wird voererst nicht umgesetzt. Wir haben jetzt ~/data/plugins als ReadOnly-Share ohne Authentifizierung freigegeben (speziell für das Sonos-Plugin).
