### ISSUE TITLE
bashlib: Wenn logdatei aus daemon gestartet wird, gehört es root.

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#625]
...und ich kann nicht mehr reinschreiben. Die lib sollte sowas in der Art machen: 
touch ${LBPLOG}/${PACKAGE}/BLE-Scanner.log
chown loxberry ${LBPLOG}/${PACKAGE}/BLE-Scanner.log
chgrp loxberry ${LBPLOG}/${PACKAGE}/BLE-Scanner.log
chmod 0660 ${LBPLOG}/${PACKAGE}/BLE-Scanner.log

**Comment by svethi** [comment]
Die Logdatei wird nicht vom Bashscript erstellt. Daher muss sich Christian darum kümmern.

**Comment by christianTF** [comment]
Achja, stimmt. Das ist Perl nicht Bash
