### ISSUE TITLE
Updates benachrichtigt Ã¼ber die folgende System-INFORMATION:

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#626]
UTF8 ....

**Comment by christianTF** [comment]
http://www.logikdev.com/2010/02/02/locale-settings-for-your-cron-job/

**Comment by mschlenstedt** [comment]
Das müsste gehen, wenn man LANG vor dem ausführen des Befehls setzt. Von wo wird der cronjob gestartet?

**Comment by christianTF** [comment]
![31560_kacke_das_kannste_schon_so_machen_aber_dann_isses_halt_kacke_shirt_women_clikezebra_schwarz_front01 1](https://user-images.githubusercontent.com/14220265/37147866-a4f37a2c-22c8-11e8-90aa-728a3d011416.jpg)


--> Das muss man irgendwie systemweit setzen. Andere locales als UTF8 sind ein Fehler.

Ich bau da mal einen Test-Job

PS: Linux ist einfach ein bescheidenes Betriebssystem, wo man sowas an 20 verschiedenen Orten setzen muss, und dann immer noch irgendwo was anders ist.... *gggrrrr* Immer noch das Bastlerbetriebssystem wie vor 20 Jahren.

**Comment by mschlenstedt** [comment]
Das ist systemweit gesetzt. Aber im Cron wird $LANG ignoriert.

**Comment by mschlenstedt** [comment]
User loxberry:
```
loxberry@lbdevil2:~ $ echo $LANG
en_GB.UTF-8
loxberry@lbdevil2:~ 
```

User root:
```
loxberry@lbdevil2:~ $ su -
Password:
root@lbdevil2:~# echo $LANG
en_GB.UTF-8
root@lbdevil2:~#
```

System-Default:
```
root@lbdevil2:~# cat /etc/default/locale
#  File generated by update-locale
LANG=en_GB.UTF-8
root@lbdevil2:~#
```

"printenv" aus einem Cronjob heraus:
```
LBPCONFIG=/opt/loxberry/config/plugins
LBPDATA=/opt/loxberry/data/plugins
LANG=en_GB.UTF-8
LBSTMPFSLOG=/opt/loxberry/log/system_tmpfs
LBPHTMLAUTH=/opt/loxberry/webfrontend/htmlauth/plugins
LBSDATA=/opt/loxberry/data/system
PWD=/root
LBSTEMPL=/opt/loxberry/templates/system
HOME=/root
LBPLOG=/opt/loxberry/log/plugins
LBHOMEDIR=/opt/loxberry
LBPTEMPL=/opt/loxberry/templates/plugins
LBPHTML=/opt/loxberry/webfrontend/html/plugins
SHELL=/bin/sh
PERL5LIB=/opt/loxberry/libs/perllib
SHLVL=1
LBSCONFIG=/opt/loxberry/config/system
LBSHTML=/opt/loxberry/webfrontend/html/system
LOGNAME=root
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
LBSHTMLAUTH=/opt/loxberry/webfrontend/htmlauth/system
LBSLOG=/opt/loxberry/log/system
_=/usr/bin/printenv
```

ich kann keinen Fehler finden.

**Comment by christianTF** [comment]
SQLite Config geändert, bisserl dort geschraubt, bisserl da geschraubt, bei mir gehts, bei Wörsty erstmal nicht, dann aber schon.
Es könnte jetzt besser sein, oder auch nicht. Wir werden sehen.
Schlechter sollte es nicht sein.
