### ISSUE TITLE
Idee: Disable Deinstallieren Button onclick bei Plugindeinstallation

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#627]
Wenn das Deinstallieren eine Weile dauert, ist es verwirrend, dass nix passiert.

**Comment by christianTF** [comment]
Da kommt doch eine Sicherheitsabfrage dazwischen?

**Comment by Woersty** [comment]
Genau. Und wenn ich **da** klicke passiert scheinbar nix. Also nix sichtbares.

**Comment by mschlenstedt** [comment]
Find ich gut. Machste es rein?

Vielleicht auch noch ein "Plugin wird deinstalliert. Bitte warten..." oder so ähnlich.

**Comment by Woersty** [comment]
👍
