### ISSUE TITLE
Plugininstallation hängt sich auf

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#628]
```
mkdir /opt/loxberry/data/plugins/rpi_monitor: File exists at /opt/loxberry/sbin/plugininstall.pl line 935.
OK: Datei-Eigentümer wurde erfolgreich geändert.
```
Danach passiert nix mehr

**Comment by Woersty** [comment]
[log.txt](https://github.com/mschlenstedt/Loxberry/files/1778383/log.txt)

**Comment by Woersty** [comment]
Reboot geht dann auch nur noch von der Shell 
`plugininstall: Cannot unlock`

**Comment by Woersty** [comment]
Und Pluginverwaltung ist nicht erreichbar.
`Es läuft bereits eine Plugin-Installation oder ein Update. Sei geduldig und warte auf den Abschluss der bereits laufenden Installation. 
`

**Comment by mschlenstedt** [comment]
Ja, das Locking ist aktiv durch den Absturz. Bei booten hilft. Ist natürlich blöd wenn das über die WebGui nicht mehr geht. 

Ich weiß nicht ob Christian da einen Timeout eingebaut hat. 

Den Absturz schaue ich mir an.

**Comment by christianTF** [comment]
Das Locking basiert auf der PID. Das „Timeout“ ist: Die PID muss weg sein. 
Jeder Lock-Versuch testet auf die PID.

**Comment by Woersty** [comment]
Wie auch immer. Geht nicht. Bleibt hängen. Nach 15 Minuten oder so hab ich über SSH gebootet.

**Comment by Woersty** [comment]
Immer noch so.

**Comment by mschlenstedt** [comment]
Keine Ahnung. Kannst Du das reproduzieren? Wenn ja: Wie?

**Comment by Woersty** [comment]
Ja, kann ich.
Knxd Plugin

**Comment by mschlenstedt** [comment]
Das liegt daran, dass das Locking nie freigegeben wird solange plugininstall.cgi in der Schleife hängt.

**Comment by mschlenstedt** [comment]
Zu Deinem ersten Posting hier im Thread:

Was hast Du da gemacht? Das Verzeichnis darf nicht exisiteren, außer Du hast irgendwelche Dateileichen.

**Comment by Woersty** [comment]
Gelöst.
