### ISSUE TITLE
miniserverbackup - Current plugin status

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#63]
Was hälst du davon, den Status des Backups mit einer Art Statusfile zu überwachen und anzuzeigen?

**Comment by mschlenstedt** [comment]
Du meinst damit man sieht ob ein Backup läuft oder nicht?

**Comment by Woersty** [comment]
Ja

**Comment by mschlenstedt** [comment]
Finde ich eine sehr gute Idee - man weiß manchmal nicht was das Modul gerade macht oder ob es überhaupt etwas macht. Wobei mit dem Live-Logfile ist das schon sehr viel besser geworden.

ich brauche aber das Gleiche für die Plugin-Installation. Ich habe daher für diese Art Logfiles ein temporäres Verzeichnis unterhalb des Webverzeichnisses angelegt: webfrontend/html/tmp
