### ISSUE TITLE
Linfo-Modul: Sprachabhängigkeit aktivieren

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#632]
- Sprachfiles werden mitgeliefert
- Einbauen der LB-Library-Funktion zum ermitteln der Systemsprache

**Comment by christianTF** [comment]
Ich weiß nicht genau, was Linfo ist, aber die LB-Sprache bekommt man mit lblanguage http://www.loxwiki.eu/display/LOXBERRY/LoxBerry%3A%3ASystem%3A%3Alblanguage

**Comment by mschlenstedt** [comment]
Mach mal latest Commit und schaue dir MyLoxberry an. Dort ist Linfo per iFrame eingebunden. 

Letztendlich habe ich mir aber überlegt, dass man das nativ ins LoxBerry Templatesystem einbinden muss. IFrame ist Mist. 

Ich stelle mir das so vor, dass man weiterhin die Linfo Module verwendet, aber das Ausgabemodul entsprechend umgestaltet.
