### ISSUE TITLE
Kaputte general.cfg darf System nicht zerstören

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#635]
- Wir müssten regelmäßig (täglich?) ein Backup der Datei machen
- Eine zerstörte oder nicht mehr gültige general.cfg müssten wir abfangen 
- Der User muss zur Auswahl haben die alte Sicherung wieder herzustellen 
- Der User muss die Auswahl haben den Default wieder herzustellen
- Die defekte general.cfg muss mit dem Hinweis auf's Forum zum Download zur Verfügung stehen

**Comment by Woersty** [comment]
Erste Version
https://github.com/mschlenstedt/Loxberry/commit/91f9886639142268d4c108cc5115ecdba7c89abe

**Comment by Woersty** [comment]
Hab schon wieder vergessen was du alles ändern wolltest. 
Du machst das schon. Irgendwann. Eilt ja nicht.
Der Fall tritt vermutlich eh so gut wie nie auf.

**Comment by christianTF** [comment]
Ich wollte gar nichts machen.

Aber wenn ich es machten _wollte_, dann hätte ich ein eigenes .cgi als Webseite angelegt, worin die Routinen zum Reparieren sind.
Beim normalen Öffnen der general.cfg in irgendwelchen Seiten wird im Fehlerfall direkt ein Redirect auf dieses CGI gemacht, Da drin ist dann das ganze Fehlerhandling.
