### ISSUE TITLE
Sonderzeichen im MS Passwort

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#636]
https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/73503-loxberry-findet-miniserver-nicht?p=147156#post147156

**Comment by christianTF** [comment]
`%` im PW geht scheinbar nicht.

In der general.cfg wird es richtig als `%25` codiert (Uri-encoded)

Der Fehler liegt höchstwahrscheinlich im ajax-check-miniserver.cgi:

Zeile 56/57 nimmt $R::User und $R::pass
Da CGI selbst url-decoded, muss User/pass vorher wieder url-encoded werden, bevor der request an den MS geht

Betrifft daher nur Check-Script, in der general.cfg ist es richtig.

**Comment by christianTF** [comment]
http://www.logikdev.com/2010/02/02/locale-settings-for-your-cron-job/
