### ISSUE TITLE
Plugininstall: ~/system/sudoers/<file> wird in /etc/sudoers.d nicht gelinkt

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#637]
Plugininstall kopiert das sudoers-File nach ~/system/sudoers/<pluginname>

Jedoch ist /etc/sudoers.d-Verzeichnis kein Symlink auf ~/system/sudoers, sondern das ~/system/sudoers/lbdefaults wird als File gelinkt. 
Deswegen funktionieren die sudoers-Files nicht in ~/system/sudoers/

**Comment by christianTF** [comment]
https://www.loxforum.com/forum/projektforen/loxberry/plugins/122935-plugin-loxberry-backup?p=147342#post147342

**Comment by mschlenstedt** [comment]
Fixed with 94d3e17c0a31389809be3cf8f5ba96d7bcbd9e5a

**Comment by christianTF** [comment]
Du musst schon auch die enthaltenen Files mitnehmen!
So killst du alle Plugins (jedenfalls Squeezelite, lbbackup, Any,...), die das verwenden, per Auto-Update
