### ISSUE TITLE
Dateimanager: Rahmen in grün ohne Header und Footer

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#639]
Damit es nach "LoxBerry" aussieht.

**Comment by Woersty** [comment]
Mache ich

**Comment by Woersty** [comment]
Aus #638 entstanden

**Comment by mschlenstedt** [comment]
Top! Dazu habe ich immer keinen Bock ;-)

**Comment by Woersty** [comment]
So oder den grünen Balken unter den Icons noch weiß?

**Comment by Woersty** [comment]
Habs doch weiß gemacht.
https://github.com/mschlenstedt/Loxberry/commit/b740f5801bfe3b39ce482877e6de73ee28a3c97b
