### ISSUE TITLE
Infotexte in Hilfe packen

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#640]
Die Infotexte zerhacken und überfrachten die Seite.
Verschiebung zur Hilfe.

**Comment by Woersty** [comment]
![41cce586-3435-4ad4-9cd3-7eb67ba10037](https://user-images.githubusercontent.com/20454116/37251253-f7d10ac0-250c-11e8-8e34-8abf33b12ec2.png)

**Comment by christianTF** [comment]
Wie gesagt, ich würde es nicht in die Hilfe geben - dafür ist das zu wichtig.

—> Flexbox verwenden, damit die Hints am Handy nach unten rutschen. Dann haben die Texte auch volle Breite. Und am Desktop bleibt es dadurch wie es war.

**Comment by Woersty** [comment]
Habe ich versucht. Geht nicht. Bin zu blöd. Sieht alles Scheiße aus.

**Comment by Woersty** [comment]
Hab noch ne Idee

**Comment by christianTF** [comment]
Nimmst das Handy halt quer in die Hand.
