### ISSUE TITLE
Uninstall loopt sich tot

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#642]
UINSTALL called
Asking for uninstallation.UINSTALL called
Doing uninstallation of 6854527d3e6265cb0fb524874acedd30.

Dann loopt er sich tot.

**Comment by Woersty** [comment]
Wo ist das Logfile der Uninstallation eigentlich zu finden?

**Comment by mschlenstedt** [comment]
Gibts aktuell nicht.

**Comment by Woersty** [comment]
@mschlenstedt schon eine Idee, woran es liegt?

**Comment by mschlenstedt** [comment]
Nö, noch keine Zeit gehabt.

**Comment by Woersty** [comment]
https://github.com/Woersty/LoxBerry-Plugin-KNXd/tree/master/uninstall
