### ISSUE TITLE
Kein Log Fehlermeldung UTF8 issue

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#643]
Die Log Datei existiert nicht. Es kann sein dass das entsprechende Plugin noch nichts sendet oder fehlerhaft ist. ÃœberprÃ¼fe noch einmal das logfile Verzeichnis: ~/log, ~/webfrontend/html/tmp or /tmp. Use relative path started from these folders.

**Comment by christianTF** [comment]
Wie ist die URL dieses Aufrufs?
Ist relevant wegen der mitgegeben Header.
