### ISSUE TITLE
MySQL morgens öfter mal nicht verfügbar (stats)

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#644]
![5394eeda-9cd9-4556-b556-b97bea1d8b1e](https://user-images.githubusercontent.com/14220265/37268179-f71b64fa-25c4-11e8-9b38-2dcbeec6ecce.png)

Am Morgen (~7-9 Uhr) ist öfter die MySQL Datenbank der Stats-Website längere Zeit nicht erreichbar.

Ist das die Backup-Zeit?

**Comment by mschlenstedt** [comment]
Der Backup-Cronjob läuft 3:27 Uhr. Kann es eigentlich nicht sein.

**Comment by christianTF** [comment]
Gefixt von @mschlenstedt (irgendwas mit dem Sync-Job)
