### ISSUE TITLE
Storage-Lib für PHP anlegen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#645]
loxberry_storage.php fehlt, aktuell nur für Perl verfügbar (LoxBerry::Storage).

**Comment by christianTF** [comment]
Die Funktion get_storage_html gibt's für PHP (V1.2.1).
Das ermöglicht die Pfadauswahl wie bei der gleichnamigen Perl-Funktion für den Benutzer. 

Ich sehe derzeit keinen Bedarf, die anderen Perl-Funktionen von LoxBerry::Storage zu implementieren.
