### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by zmata** [mschlenstedt/Loxberry#647]
My language is set to English. If I go to Squeezelite Player plugin, that has English translation, system automaticaly switch to Germany.
LoxBerry  1.0.3.2 
Squeezelite Player plugin 0.5.1

**Comment by christianTF** [comment]
This is a Squeezelite Plugin problem.

@zmata, could you please try this update, if it fixes the issue for you? If yes, I will release it as 0.5.2
https://github.com/christianTF/LoxBerry-Plugin-squeezelite/archive/dev.zip

cu, Christian

**Comment by zmata** [comment]
Hi Christian, thanks, this partly solved the problem.
Plugin is in EN, but widgets are in DE.
Additionaly I tried to make translation of the LoxBerry and Squeeze Lite plugin to Czech. But - in Czech language - plugin continue to fall back to DE.
Thanks for suport.
Zmata

**Comment by christianTF** [comment]
Thanks for your feedback. I give it another try this weekend ;-)

**Comment by christianTF** [comment]
The Squeezelite Plugin issue is fixed, but indeed there is also a language issue with the legacy templates for 0.2.x plugins.
I close this issue and continue in #661
