### ISSUE TITLE
Netzwerkfreigaben Bearbeiten

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#649]
Bearbeiten-Option für Server/Shares fehlt.

**Comment by mschlenstedt** [comment]
Ist das überhaupt notwendig? Hat nie jemand nachgefragt oder vermisst...

**Comment by christianTF** [comment]
Nein.
Eine Kleinigkeit wäre trotzdem interessant, nämlich vielleicht eine (readonly) Liste
Server: User
Server: User
Oder dass im Drop-down steht `Server (User)`

**Comment by christianTF** [comment]
Derzeit kein Bedarf.
Neu zu diskutieren, wenn mal jemand danach fragt.
