### ISSUE TITLE
Notify: eMails wieder HTML

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#654]
Nach 1.0.4 würde ich das mit den Notify eMails gern nochmal aufgreifen.
Ich hätte die gern in html (etwas hübscher, nichts großes).

**Comment by christianTF** [comment]
Möchte ich auch, aber das muss einfacher gehen als über Tempfiles zu erstellen, sondern irgendwie als String zu übergeben.
Auch möchte ich den Mailclient nicht wechseln, weil das funktioniert jetzt. Es muss auch mit mailx gehen.

**Comment by mschlenstedt** [comment]
Noch aktuell?

**Comment by mschlenstedt** [comment]
Noch aktuell?

**Comment by Woersty** [comment]
Ja gerne. Aber ich habe da keinen Nerv für. Stehe mit UTF-8 auf Kriegsfuß.

**Comment by christianTF** [comment]
Meins!

**Comment by christianTF** [comment]
Umgesetzt mit https://github.com/mschlenstedt/Loxberry/commit/4c5fefc41949833b13fa7fae09c64a3141a1d38e

Bitte testen.

@Woersty Gerne darfst du das Layout des Mails optimieren - wobei wie immer - nicht übertreiben :-)

Files:
- ~/bin/notifyproviders/email.pl (Email-Routine, wo der MIME-Content erstellt wird)
- ~/templates/system/notifyproviders/notify_email_template.html (HTML::Template)

Im .pl sind auskommentiert schon Routinen zum Hinzufügen von Inline-Bildern. CSS muss in Mails inline erfolgen (`<div style="...">`). Bei der Größe von Bildern nicht übertreiben.
Bei Anpassung der Mail-Texte aus dem languagefile optimalerweise die alten Keys löschen und neue Keys verwenden, damit der Satzbau in den anderen Sprachen nicht "auseinanderbricht" (muss dann neu übersetzt werden).
