### ISSUE TITLE
PHP-Log-Lib: Unwanted quotes in Log message

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#655]
Ich habe " in meiner Logmessage:
language:
`INF_0024_FILE_TIMESTAMP="Guessed file time is" `
PHP:
debug($L["ERRORS.INF_0024_FILE_TIMESTAMP"],5);

Wenn ich ein  str_ireplace drum mache gehts:
`debug(str_ireplace('"','',$L["ERRORS.INF_0024_FILE_TIMESTAMP"]),5)`

**Comment by Woersty** [comment]
![image](https://user-images.githubusercontent.com/20454116/37559830-fbcfcb14-2a2c-11e8-8adc-2b89e3e7fd20.png)

**Comment by christianTF** [comment]
Ich verstehe gerade nur Bahnhof.

Was ist denn, wenn du `error_log($L["ERRORS.INF_0024_FILE_TIMESTAMP"]);` oder `echo $L["ERRORS.INF_0024_FILE_TIMESTAMP"];` machst, stehen dann auch die Anführungszeichen dort?

**Comment by Woersty** [comment]
ja

**Comment by Woersty** [comment]
```
root@loxberrydev:/opt/loxberry/webfrontend/html/plugins/miniserverbackup# php -f /opt/loxberry/webfrontend/html/plugins/miniserverbackup/index.php
"Guessed file time is" 
```

**Comment by christianTF** [comment]
Ich kann das nicht reproduzieren.

Testscript in `/opt/loxberry/webfrontend/htmlauth/plugins/lbbackup`:
```php
#!/usr/bin/env php
<?php
require_once "loxberry_system.php";

$L = LBSystem::readlanguage("language.ini");
echo $L["TGZ.LABEL"] . "\n";
?>
```
Language File:
```
[TGZ]
LABEL="Komprimiertes Dateibackup (TGZ)"
JITSELECT="TGZ (komprimierter Tarball)"
```

Ausgabe:
`Komprimiertes Dateibackup (TGZ)`

**Comment by christianTF** [comment]
PS: Das services.php Widget von Sven verwendet auch durchgängig die LBSystem::readlanguage Funktion und nirgends werden im UI Anführungszeichen angezeigt.
Vielleicht irgendein Bug in deinem Plugin?

**Comment by christianTF** [comment]
@Woersty Hattest du dazu noch was herausgefunden? Sonst mach ich zu - bei mir funzt das ohne Anführungszeichen.

**Comment by Woersty** [comment]
Nee. Habe ich nicht. Falls ich nochmal drüber stolper gucke ich mal genauer.
