### ISSUE TITLE
PHP-Log-Lib: Keep multiple spaces

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#656]
Keep multiple spaces (convert to &nbsp; if header=html)
In shell and logfile keep them as spaces 
![image](https://user-images.githubusercontent.com/20454116/37560563-2c142fdc-2a3b-11e8-90b7-0b92210ad5b4.png)

[Möchte die Werte gern untereinander haben und die _ durch Leerzeichen ersetzen]

**Comment by christianTF** [comment]
Ich weiß nicht genau, worum's geht. Es gibt noch gar keine PHP-Lib für Logging.

Geht's um den Log-Viewer? Da könnte ich mir vorstellen, dass das die HTML-Darstellung ist. Zwei Blanks werden in HTML nicht dargestellt. Da müsste man alle Leerzeichen in `&nbsp;` konvertieren. Meinst du das?

**Comment by christianTF** [comment]
Commits Von Wörsty:

https://github.com/mschlenstedt/Loxberry/commit/8219ea14a0d29b63b3e6aa6c148f295a3131827b

https://github.com/mschlenstedt/Loxberry/commit/91f084a45c5f09eaa111dc1daa189a96284081d7
