### ISSUE TITLE
Mail-Notifications deaktivieren geht nicht

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#659]
![image](https://user-images.githubusercontent.com/16830799/37577677-da996c2c-2b33-11e8-8bc3-5c1a0303441f.png)

Man kann das Formular nicht absenden ohne Angabe von Mailadresse und SMTP-Server. Damit kann ich die Notifications nicht deaktivieren.

**Comment by Woersty** [comment]
Speichert sofort aber die Info fehlt

**Comment by Woersty** [comment]
https://github.com/mschlenstedt/Loxberry/commit/6dfb0fe3a73fff89fe1499edad3f8c38b625f28a
