### ISSUE TITLE
Please add our Loxberry Czech Translation

### ISSUE THREAD

**Issue by zmata** [mschlenstedt/Loxberry#660]
Hi, can you please add my Czech translation to next build of LoxBerry. File language_cs.ini is in https://github.com/zmata/LoxBerryCz.
Thanks
Zmata

**Comment by mschlenstedt** [comment]
Yes of course! Thanks a lot!

**Comment by Woersty** [comment]
I've changed HINT_NOTIFICATIONS in [MAILSERVER] today.
https://github.com/mschlenstedt/Loxberry/commit/6dfb0fe3a73fff89fe1499edad3f8c38b625f28a

**Comment by Woersty** [comment]
@mschlenstedt do you see a useful way to inform translation helper like zmata about new language strings.
Maybe a mailinglist which compares en and all other languages and shows differences.

I have changed HINT_NOTIFICATIONS under [MAILSERVER] today.

**Comment by christianTF** [comment]
This question also goes to @zmata, what way you would like to prefer if single phrases changes in the EN source language, or new phrases are introduced.

Of course, we can implement some kind of diff between (Pre-)Release versions. Possibly I could figure out a way to have this done directly within GitHub.

**Comment by Woersty** [comment]
I have an idea and will test it. If it works, I will post my suggestion here.

**Comment by Woersty** [comment]
I've written a little script to create comments automatically if the English translation changes.
Example: https://github.com/mschlenstedt/Loxberry/commit/68bbe27c3c4861dc97aa88b81f88d4e7a2e35155

The global issue from now is issue 666 for that.

**Comment by christianTF** [comment]
For my understanding: What adds the comment, and is this version (=tag) based or commit based?

**Comment by christianTF** [comment]
btw, adequate issue number ;-)
https://en.wikipedia.org/wiki/Number_of_the_Beast

**Comment by Woersty** [comment]
I know. That's why I've dropped 665 and re-created as 666  👍
