### ISSUE TITLE
Translation function doesn't work

### ISSUE THREAD

**Issue by zmata** [mschlenstedt/Loxberry#667]
- Translated phrases are not transfered from "Destination language" column into ini file. (both - system and plugin translation)
- Download button return: 405 Method Not Allowed (system translation only)
Zmata

**Comment by christianTF** [comment]
"405 Method not allowed" is fixed

When the translation files are not saved, this is an issue of permissions, possibly of copying the files manually as root user.
Please verify that your files belong to user loxberry with the correct permissions:

LoxBerry:
`chown loxberry:loxberry /opt/loxberry/templates/system/lang/*`
`chmod 644 /opt/loxberry/templates/system/lang/*`
(LoxBerry Update sets this permissions automatically)

Squeezelite Plugin:
`chown loxberry:loxberry /opt/loxberry/templates/plugins/squeezelite/lang/*`
`chmod 644 /opt/loxberry/templates/plugins/squeezelite/lang/*`

**Comment by zmata** [comment]
@christianTF "405 Method not allowed" is fixed
Permision is correct. loxberry:loxberry 644.
If I use button for Coppiing source phrase to destination, transfer of this phrase is done, but if I add own phrase, nothing happens

**Comment by Woersty** [comment]
Maybe an issue with special Czech characters?
You have to leave the input field to save the value (on blur event)

**Comment by christianTF** [comment]
I don’t believe in an encoding issue (as this would happen in German too).

But as Wörsty says, saving is done on leaving the field.
Or does this happen only in a field that was copied before?

**Comment by zmata** [comment]
Problem occures using Firefox (Debian 9, Win10). With Edge (Win10) it works correctly.
Firefox ESR 52.7.2 (64 bit) from standard Debian Repo
Firefox 59.0.1 (64 bit) in Win10

**Comment by Woersty** [comment]
Got it. Will have a look.

**Comment by Woersty** [comment]
You can try it with the latest Commit version or replace just the translate.html.
Get it from [here](https://raw.githubusercontent.com/mschlenstedt/Loxberry/23a402ed69e5226854c5a224006e45aeb9377363/templates/system/translate.html) and put it in the \templates\system\ folder of the Samba fileshare.

**Comment by zmata** [comment]
@Woersty Fixed!

**Comment by zmata** [comment]
I think you can close this issue.
I'll update Czech language according to DEV version tomorow and I'll let you know in separate issue.
Thanks

**Comment by zmata** [comment]
I think, it was great work with translation issues last 2 days. So thank you guys!
