### ISSUE TITLE
Reihenfolge Button OK/Cancel ändern?

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#669]
Wir haben eine nicht-standardkonforme Reihenfolge:

![image](https://user-images.githubusercontent.com/16830799/37752359-1231b0a2-2d98-11e8-82ca-992518c7569c.png)

Üblich ist:

![image](https://user-images.githubusercontent.com/16830799/37752380-2fc31d86-2d98-11e8-8a43-ed4e3c47ef28.png)

Positive Bestätigung ist üblicherweise links, rechts ist Abbrechen.

**Comment by christianTF** [comment]
Seit es mobile Geräte gibt, hat sich das alles ein wenig gewandelt. Einen „Standard“ gibt es eigentlich nicht mehr.

In WebApps sind die Buttons meist oben, und rechts ist dann normalerweise die Speichern-/Weiter-Aktion, und links das Abbrechen/Schließen.

Deswegen hätte ich erstmal nichts gegen die jetzige Reihenfolge einzuwenden.

**Comment by Woersty** [comment]
Mir egal.

**Comment by christianTF** [comment]
Ist das noch relevant?
