### ISSUE TITLE
Translation files update

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#671]
-Function / button for system translation to update to the latest language files from GitHub.

Meinungen?

**Comment by mschlenstedt** [comment]
Ich denke das ist nicht nötig. Neue Phrases kommen nur mit neuen Funktionen, die auch per Update kommen. 

Wäre eigentlich nur bei Korrekturen vorhandener Phrases sinnvoll oder neuen Übersetzungen. Aber da kann man meiner Meinung nach auch bis zum nächsten Update warten. Bzw. wir können auch ein Udate zwischenschieben, wenn es viele neue Languages gibt.
