### ISSUE TITLE
Button zum Update wiederholen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#672]
![image](https://user-images.githubusercontent.com/16830799/37851900-df1fb9b2-2ee0-11e8-8a20-cba5d22725ed.png)

Button:
![image](https://user-images.githubusercontent.com/16830799/37851917-f28d7c5a-2ee0-11e8-9206-ab2c2da011d9.png)

Header:
![image](https://user-images.githubusercontent.com/16830799/37851964-1d830830-2ee1-11e8-99e5-290523444c23.png)

**Comment by christianTF** [comment]
Ein paar Infos dazu:

1. Die Versionsnummer muss derzeit im Button stehen, weil von dort wird sie ausgelesen. (Kann man auch in irgendein verstecktes DIV verschieben)
2. Die Versionsnummer muss irgendwo sichtbar stehen, weil wie sollen wir sie sonst wissen, wenn jemand sich meldet.
3. Die Versionsnummer, die dort angezeigt wird, kommt per json von lbupdatecheck/Ajax-Config-Händler zurück, nicht vom Updates.cgi.
4. Der Button tut nur die Versionsnummer zurücksetzen, aber startet keine Installation (und auch keine Deinstallation). Das sollte auch klar bleiben.
5. Das ist alles rein in JS im Updates.html implementiert. Es gibt keinen Code in Updates.cgi.
6. Schön wäre natürlich, wenn nicht .999 gesetzt würde, sondern die letzte Vorversion. Dann muss aber jemand implementieren, die letzte Vorversion bei GitHub auszulesen. Das Script vor dem fehlgeschlagenen Script ist NICHT der vorige Release.

**Comment by Woersty** [comment]
Warum so kompliziert? Setzt doch die Version automatisch zurück und Meldung für Update fehlerhaft + wiederholen und fertig.

**Comment by Woersty** [comment]
Pollt der ajax Configuration handler nicht sowieso die ganze Zeit? Der könnte das färben der Titelleiste mitmachen.

**Comment by Woersty** [comment]
Zu 6. hier könnte man einen Cookie setzen für die Version welche vor dem Update drauf war. Oder Datei irgendwo.

**Comment by christianTF** [comment]
1. Nicht automatisch zurücksetzen, weil sich sonst niemand mehr auskennt, welche Version tatsächlich drauf ist, und dann durch das Auto-Update ständig erfolglos installiert wird. Der Benutzer soll das bewusst drücken.
2. Nein, nicht dass ich wüsste 
3. Das Update läuft nicht im Browser. Beim 2. Versuch stimmt es nicht mehr.
4. Warum so kompliziert? Da ist ein Button und da drückt man drauf. Fertig.

**Comment by christianTF** [comment]
PS: Ich hab mir schon was dabei gedacht, wie ich das gemacht hab.

Mach dir bewusst: 

- Das Update wird auf Wunsch vollständig automatisch installiert, je nach Einstellung sogar täglich.
- Die Update-Scripts sind optional. Sie sagen nichts darüber aus, welche Versionen es gegeben hat.
- Das Update installiert _immer_ den (Pre-)Release-Stand, und keinen Zwischenstand. Z.B. *ist* die Version tatsächlich 1.2, auch wenn das 1.0.4-Script hängen geblieben ist.
- Wer loxberryupdate kaputt macht, darf selbst den 500 Benutzern erklären, wie man es manuell fixt ;-)

**Comment by mschlenstedt** [comment]
Ist das noch aktuell oder kann das zu?
