### ISSUE TITLE
client min protocol = SMB2 client max protocol = SMB3

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#676]
Bei Zugriff auf Windows10 Shares sind bei einigen Windows10 Installationen folgende Samba-Optionen notwendig:

```
[global]
client min protocol = SMB2
client max protocol = SMB3
```

Zudem ist die options "syslog" obsolete. Diese sollte entfernt werden. Haben die oben genannten Optionen Nachteile? Welche Clients sperren sie aus? Sollen sie Stadard werden?

**Comment by Woersty** [comment]
```
[global]
client max protocol = SMB3
```

geht auch
