### ISSUE TITLE
Wrong SecurePIN Meldung

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#679]
![image](https://user-images.githubusercontent.com/20454116/37876063-d480a01c-3047-11e8-8830-f21eb7c0c2ca.png)

**Comment by mschlenstedt** [comment]
Kann ich hier nicht reproduzieren. Ist doch noch irgendein Cache-Thema?

**Comment by mschlenstedt** [comment]
@Woersty Hast Du das nochmal getestet? Ich kann das nicht reproduzieren.

**Comment by mschlenstedt** [comment]
Ok, ich mach es zu. Scheint kein Thema mehr zu sein.
