### ISSUE TITLE
deb package not instaled during plugin instalation

### ISSUE THREAD

**Issue by zmata** [mschlenstedt/Loxberry#683]
Hi, I try to develop Modbus TCP/RTU Gateway plugin ( https://github.com/zmata/LoxBerry-Plugin-ModbusGateway ) according to http://www.loxwiki.eu/display/LOXBERRY/Entwickler . 
I need to install deb package that I've created from https://github.com/3cky/mbusd . Deb package is in /dpkg/raspberry/ directory, but instalation proces does not run dpkg -i ...
Can you help me, please? Deb package is OK. I tried to install it before. 
I use mbusd instead of the modbus extension for long time without any problems, so I think it could be interesting for LoxBerry project.
Thanks

**Comment by mschlenstedt** [comment]
I will check this tonight. Which LoxBerry Version do you use?

**Comment by zmata** [comment]
1.0.4.2, but not problem to switch to Latest commit. It should be possible to do workaround using preinstall script, but according to "Entwickler" manual it should work as it is. I can also add you to the repository as collaborator.

**Comment by mschlenstedt** [comment]
Mi, 1.0.4 should be fine - we had a bug in 1.0.0. Let me check that tonight.

**Comment by Woersty** [comment]
I use the same in my KNXd plugin and have done the job via the daemon called by the postroot.sh
You could do it in postroot.sh, too.
See https://github.com/Woersty/LoxBerry-Plugin-KNXd/blob/master/postroot.sh and https://github.com/Woersty/LoxBerry-Plugin-KNXd/blob/master/daemon/daemon#L42

**Comment by christianTF** [comment]
The error is in the plugininstall.sh Code in here:
```perl
if (-e "$lbsconfigdir/is_raspberry.cfg") {
		my $thisarch = "raspberry";
	}
```

The code defines the variable my $thisarch inside the if, therefore the variable context is lost after the {}.

```perl
my $thisarch;
if (-e "$lbsconfigdir/is_raspberry.cfg") {
		$thisarch = "raspberry";
	}
```
That way it should work.

**Comment by christianTF** [comment]
@zmata I changed the code I've mentioned above.
Could you update to latest commit and retry the installation.

**Comment by zmata** [comment]
@christianTF  No, it doesn't resolved the problem.

**Comment by mschlenstedt** [comment]
I hadn't had the time yesterday - sorry. I will check this tonight. Please don't use a workaround. It should work with the standard way. We must fix this.

**Comment by mschlenstedt** [comment]
@christianTF  fixed one bug yesterday and I found another one right now. I checked the fixed version with your plugin and it installed your deb package without problems. 

The fix will be included in the next version. You can also install to "Latest Commit" with LoxBerry update (use at own risk!) - this will also install the fix.

**Comment by christianTF** [comment]
@zmata As the fix will be in 1.2.0.2, you should set this as minimum version in your plugin.cfg when releasing your plugin.

**Comment by mschlenstedt** [comment]
It is 1.2.0.1

**Comment by zmata** [comment]
OK, I understand. Thanks
