### ISSUE TITLE
Rechte für LoxBerry Gruppe

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#684]
Die Gruppe "loxberry" sollte Schreibrechte haben (für Kodi, LMS, etc.).

```
Was anderes: Rechte beim mounten von Netshares: In /etc/auto.smb Zeile 41 wie folgt abändern: opts="-fstype=cifs,file_mode=0664,dir_mode=0775"
```

Zudem muss vermutlich "resetpermissions" angepasst werden. Unbedingt Test, ob der User "loxberry" danach die Berechtigung hat Files anderer Nutzer aus der Gruppe "loxberry" zu löschen.

**Comment by mschlenstedt** [comment]
Netshares werden jetzt mit Schreibrechten für die Gruppe loxberry gemountet: 8f59c2fe669de90292c567cba26e656aaeefaeab

USB-Devices werden ebenfalls mit Schreibrechten für alle gemountet. Bitte mal durchtesten.

**Comment by christianTF** [comment]
Nix Negatives dazu mehr gehört.
