### ISSUE TITLE
Zwangsreboot vor erstem Update 

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#685]
Bevor man das erste Update macht, muss unbedingt ein Reboot erfolgen. Sonst schlägt das Update fehl und die Configfiles haben 0 Byte Größe.

Im Forum hat jemand das Image aufgespielt und ohne Reboot upgedatet. Danach ist der LoxBerry kaputt. Habe ich auch schon gehabt.

Eigentlich macht doch das Update eine Speicherplatzuberprüfung? Funktioniert das eventuell nicht richtig?

**Comment by christianTF** [comment]
Reboot-Button statt LBUpdate-Button https://github.com/mschlenstedt/Loxberry/commit/a9218ec0d01fed80377918779e8c6cb60314f499

**Comment by christianTF** [comment]
Außerdem wird nun zusätzlich vor jedem Update-Script auf <100MB geprüft und abgebrochen
