### ISSUE TITLE
Reihenfolge Widgets im Systemmenü

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#686]
Hat jemand eine Idee für eine sinnvolle Reihenfolge der Icons?

**Comment by svethi** [comment]
Vllt die Reihenfolge, in der man den Loxberry einrichten sollte?

**Comment by christianTF** [comment]
Was mir einfällt, wäre, die Power an den Schluss vor Donate zu setzen, weil das sowieso auch aus der Fußleiste erreichbar ist.
Translate würde ich ggf. auch hinter den Storage-Sachen ansiedeln - das war früher auch das vorletzte.
Ebenso den Setup-Assistent ganz nach hinten, weil man den i.d.R. nicht mehr braucht, wenn einmal eingerichtet wurde.

**Comment by christianTF** [comment]
Bereits erledigt mit 1.0
