### ISSUE TITLE
How to start service from plugin?

### ISSUE THREAD

**Issue by zmata** [mschlenstedt/Loxberry#689]
Hi, I need to start and enable service mbusd from plugin's GUI. Is it possible if systemctl can be run by root only? Thanks for help

**Comment by christianTF** [comment]
Create a script in your plugin's bin directory, that calls the systemctl commands.

In the sudoers directory (http://www.loxwiki.eu/pages/viewpage.action?pageId=23462653#Pluginf%C3%BCrdenLoxberryentwickeln(Version1.x)-Unterverzeichnis:sudoersYellowOptional) place a sudoers file that allows your script to be sudo'd.

On the UI script, sudo the bin script.

**Example**
Sudoers file:
https://github.com/christianTF/LoxBerry-Plugin-Kodi/blob/master/sudoers/sudoers

Call with sudo:
https://github.com/christianTF/LoxBerry-Plugin-Kodi/blob/5c4d7ce80267fcf7878e7833107e01bdd1b16e0c/webfrontend/htmlauth/ajax.cgi#L15

**Comment by zmata** [comment]
It helps. Thanks
