### ISSUE TITLE
Filemanager: Irgendwo den absoluten Pfad hinschreiben

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#694]
Die Breadcrumb zeigt nur einen relativen Pfad ab /opt/loxberry an.
Wäre gut, wenn irgendwo auch der absolute Pfad angezeigt würde.

**Comment by mschlenstedt** [comment]
Man könnte auch einfach das gesamte Filesystem freigeben:

https://github.com/mschlenstedt/Loxberry/blob/a205f52b4e2e69deba57b768dc50cdfa55cd5408/webfrontend/htmlauth/system/tools/filemanager/filemanager.php#L36

Allerdings nimmt er ein einfaches / nicht als Pfad an - warum auch immer - olles PHP ;-)
