### ISSUE TITLE
Leerzeilen in /etc/fstab

### ISSUE THREAD

**Issue by scharrin2** [mschlenstedt/Loxberry#695]
Hallo,

wenn ich in die /etc/fstab einen eigenen mount eintrage und dabei Leerzeilen in der Datei mache, werden diese nach einem Neustart mit

    ,nofail

gefüllt.

Dies führt beim "Mounten" zu einem Fehler.

![bildschirmfoto 2018-04-04 um 21 07 48](https://user-images.githubusercontent.com/22325491/38328850-434f6a3a-384c-11e8-9848-95b902bfe767.png)

Ich habe die Version V1.2.0.2

Viele Grüße,
Christian

**Comment by Woersty** [comment]
Er hat im issue Leerzeile geschrieben dein regex  macht Leerzeichen

**Comment by mschlenstedt** [comment]
Fixed with ad935274
