### ISSUE TITLE
mount in /etc/fstab wird nicht ausgeführt

### ISSUE THREAD

**Issue by scharrin2** [mschlenstedt/Loxberry#696]
Ich habe in der /etc/fstab einen NFS-Share zum mounten eingetragen.

Nach dem Neustart des Loxberry wird dieser nicht gemountet.

Wenn ich allerdings als root einen mount -all ausführe, wird das Verzeichnis gemountet.

Meine Version des Loxberry: V1.2.0.2

![bildschirmfoto 2018-04-04 um 21 23 18](https://user-images.githubusercontent.com/22325491/38329563-70ee5a44-384e-11e8-82dc-796121513004.png)

**Comment by Woersty** [comment]
Wird laut Michael nur bei Zugriff gemountet. Ich habe das gleiche Thema mit Samba aber bin noch nicht dazu gekommen weiter zu testen.

**Comment by mschlenstedt** [comment]
Das ist nicht richtig. Nur per AutoFS eingebundene Shares werden erst bei Zugriff gemountet. Direkt in fstab eingetragene Shares verhalten sich standardmäßig und müssten sofort und permanent gemountet werden. 

Kann mir höchstens vorstellen dass zu dem Zeitpunkt das Netzwerk noch nicht iben ist. Könnte man umgehen, indem man in etc/rc.local ein mount -a schreibt.

**Comment by scharrin2** [comment]
Vielleicht hilft es weiter:

Beim Loxberry 1.0.4.2 hat es genau auf diese Art noch funktioniert.

**Comment by mschlenstedt** [comment]
Hast du da auch schon die nofail Option benutzt?

**Comment by scharrin2** [comment]
ja - die Zeile, die ich verwende, ist immer gleich:
192.168.3.3:/backup /backup nfs nolock,rsize=8192,wsize=8192,timeo=14,intr,nofail 0 0

**Comment by scharrin2** [comment]
Ich habe heute das Update von 1.2.0.2 auf 1.2.0.3 gemacht.

Leider ist der Fehler noch immer vorhanden.

**Comment by mschlenstedt** [comment]
Die Lösung ist:

/opt/loxberry/system/network/interfaces:

auto eth0

**Comment by Woersty** [comment]
```
root@loxberrydev:/opt/loxberry# cat /opt/loxberry/system/network/interfaces*
auto lo
iface lo inet loopback

allow-hotplug eth0
iface eth0 inet static
  address 192.168.178.50
  netmask 255.255.255.0
  gateway 192.168.178.1
  dns-domain loxberry.local
  dns-nameservers 192.168.178.254
auto lo
iface lo inet loopback

allow-hotplug eth0
iface eth0 inet dhcp
auto lo
iface lo inet loopback

allow-hotplug eth0
iface eth0 inet static
  address <TMPL_VAR netzwerkipadresse>
  netmask <TMPL_VAR netzwerkipmaske>
  gateway <TMPL_VAR netzwerkgateway>
  dns-domain <TMPL_VAR netzwerkdnsdomain>
  dns-nameservers <TMPL_VAR netzwerknameserver>
auto lo
iface lo inet loopback

allow-hotplug wlan0
iface wlan0 inet dhcp
 wpa-ssid <TMPL_VAR netzwerkssid>
 wpa-psk <TMPL_VAR netzwerkschluessel>
auto lo
iface lo inet loopback

allow-hotplug wlan0
iface wlan0 inet static
  wpa-ssid <TMPL_VAR netzwerkssid>
  wpa-psk <TMPL_VAR netzwerkschluessel>
  address <TMPL_VAR netzwerkipadresse>
  netmask <TMPL_VAR netzwerkipmaske>
  gateway <TMPL_VAR netzwerkgateway>
  dns-domain <TMPL_VAR netzwerkdnsdomain>
  dns-nameservers <TMPL_VAR netzwerknameserver>

```

**Comment by mschlenstedt** [comment]
Habe es als neuen Issue aufgenommen: #804
