### ISSUE TITLE
Riesige daemon.log

### ISSUE THREAD

**Issue by Strike1988** [mschlenstedt/Loxberry#698]
LoxBerry Version: **1.2.0.2**

**Betreff:** Cron root@loxberry test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )

**Nachricht:**
/etc/cron.daily/logrotate:
error: Compressing program wrote following message to stderr when compressing log /var/log/syslog.1:

gzip: stdout: No space left on device
error: failed to compress log /var/log/syslog.1
run-parts: /etc/cron.daily/logrotate exited with return code 1

**Comment by Woersty** [comment]
So ein Zufall 👍

**Comment by mschlenstedt** [comment]
Ich habe dazu mal ein separates Issue #700 eröffnet.

**Comment by Woersty** [comment]
Sag mal, was hat das bei dir denn so voll geschrieben?
Kannst du mal ein `ls -Sahrl /var/log` posten`?

**Comment by Woersty** [comment]
@mschlenstedt  diskutiere ich noch eben aus und übernehme das Ergebnis in #700

**Comment by Woersty** [comment]
Noch besser wäre:
`find /var/log/  -exec ls -Sahrl {} \;|egrep -v "^d"`

**Comment by Strike1988** [comment]
loxberry@loxberry:~ $ ls -Sahrl /var/log
total 50M
-rw-r-----  1 root     adm         0 Apr  7 14:17 mail.log
-rw-r-----  1 root     adm         0 Apr  7 14:17 mail.info
-rw-------  1 root     utmp        0 Apr  1 20:21 btmp
drwxr-x---  2 loxberry loxberry   40 Feb  7 05:35 lighttpd
drwxr-xr-x  2 loxberry loxberry   40 Feb  7 05:35 fsck
drwxr-xr-x  2 loxberry loxberry   40 Apr  1 20:13 apt
drwxr-x---  2 loxberry loxberry   40 Feb  7 05:35 apache2
drwxr-x---  2 loxberry loxberry   60 Apr  2 06:55 unattended-upgrades
drwxr-x---  3 loxberry loxberry  200 Apr  2 21:42 samba
-rw-r--r--  1 root     root      224 Apr  1 20:21 rpimonitor.log
drwxr-xr-x  8 daemon   daemon    420 Apr  7 06:25 .
-rw-r-----  1 root     adm       809 Apr  7 13:40 user.log
-rw-r-----  1 root     adm      1.2K Apr  1 20:21 debug
-rw-rw-r--  1 root     utmp     1.9K Apr  7 14:19 wtmp
-rw-r-----  1 root     adm      4.0K Apr  7 14:19 syslog
drwxr-xr-x 11 root     root     4.0K Feb  7 05:40 ..
-rw-r-----  1 root     adm       24K Apr  7 14:19 messages
-rw-r-----  1 root     adm       24K Apr  4 22:35 kern.log
-rw-r-----  1 root     adm       25K Apr  1 20:27 syslog.1
-rw-r-----  1 root     adm       11M Apr  7 14:19 auth.log
-rw-r-----  1 root     adm       40M Apr  7 14:19 daemon.log

**Comment by Woersty** [comment]
Hatte mich vertippt. Bitte so:
`find /var/log/  -exec ls -Sahrl {} \;|egrep -v "^d"`

**Comment by Woersty** [comment]
Aber sehe gerade  **daemon.log** ist es

**Comment by Woersty** [comment]
Kannst du die mal zippen und hochladen?

**Comment by Strike1988** [comment]
loxberry@loxberry:~ $ find /var/log/ -exec ls -Sahrl {} \;|egrep -v "^d"
total 316K
-rw-------  1 root     utmp        0 Apr  7 14:22 btmp
-rw-r--r--  1 root     root      224 Apr  7 14:22 rpimonitor.log
-rw-r-----  1 root     adm       364 Apr  7 14:23 user.log
-rw-r-----  1 root     adm      1.2K Apr  7 14:22 debug
-rw-rw-r--  1 root     utmp     1.9K Apr  7 14:29 wtmp
-rw-r-----  1 root     adm       23K Apr  7 14:23 messages
-rw-r-----  1 root     adm       24K Apr  7 14:22 kern.log
-rw-r-----  1 root     adm       25K Apr  7 14:23 syslog
-rw-r-----  1 root     adm       44K Apr  7 14:30 auth.log
-rw-r-----  1 root     adm      175K Apr  7 14:30 daemon.log
-rw-r--r-- 1 root root 224 Apr  7 14:22 /var/log/rpimonitor.log
total 0
total 8.0K
-rw-r--r-- 1 root     root       0 Apr  7 14:22 log.
-rw-r--r-- 1 root     root     154 Apr  7 14:22 log.smbd
-rw-r--r-- 1 root     root     382 Apr  7 14:24 log.nmbd
-rw-r--r-- 1 root root 154 Apr  7 14:22 /var/log/samba/log.smbd
-rw-r--r-- 1 root root 0 Apr  7 14:22 /var/log/samba/log.
-rw-r--r-- 1 root root 382 Apr  7 14:24 /var/log/samba/log.nmbd
total 0
total 0
total 0
total 0
total 0
total 0
total 0
-rw-r----- 1 root adm 44K Apr  7 14:30 /var/log/auth.log
-rw-r----- 1 root adm 364 Apr  7 14:23 /var/log/user.log
-rw-r----- 1 root adm 23K Apr  7 14:23 /var/log/messages
-rw-r----- 1 root adm 1.2K Apr  7 14:22 /var/log/debug
-rw-r----- 1 root adm 24K Apr  7 14:22 /var/log/kern.log
-rw-r----- 1 root adm 25K Apr  7 14:23 /var/log/syslog
-rw-r----- 1 root adm 175K Apr  7 14:30 /var/log/daemon.log
-rw------- 1 root utmp 0 Apr  7 14:22 /var/log/btmp
-rw-rw-r-- 1 root utmp 1.9K Apr  7 14:29 /var/log/wtmp

**Comment by Woersty** [comment]
Ok. Die Unterverzeichnisse waren sauber. Habs gelöscht damit der Issue nicht so riesig wird...

**Comment by Strike1988** [comment]
Als root komme ich nicht über WinSCP drauf. und im loxberry browser sehe ich die Ordner nicht

**Comment by Woersty** [comment]
Kopiere sie einfach nach /opt/loxberry/  dann über Samba / Windows Freigabe oder WinSCP
`cp /var/log/daemon.log /opt/loxberry/; chown 1001:1001 /opt/loxberry/daemon.log`

**Comment by Strike1988** [comment]
der opt Ordner wird mir unter samba nicht angezeigt

**Comment by Woersty** [comment]
Opt /opt/loxberry/ ist der Ordner

**Comment by Strike1988** [comment]
So nun habe ich es. Sorry. Bin nicht so bewandert mit sowas.
[daemon.zip](https://github.com/mschlenstedt/Loxberry/files/1886381/daemon.zip)

**Comment by Woersty** [comment]
hinter /opt/loxberry/ ist ein / das bedeutet er kopiert die deamon.log da hin

**Comment by Woersty** [comment]
ok Danke passt

**Comment by Woersty** [comment]
Ist ein 1-wire Problem 
@mschlenstedt Idee?

**Comment by Woersty** [comment]
@Strike1988 welche Plugins benutzt du?

**Comment by Woersty** [comment]
Der rödelt sich in einer Schleife tot:
```
Apr  7 15:05:03 loxberry systemd[1]: Started LSB: Loxberry Plugin 1Wire.
Apr  7 15:05:03 loxberry systemd[1]: Stopping LSB: 1-wire TCP server...
Apr  7 15:05:04 loxberry owserver[7519]: Stopping 1-Wire TCP Server: owserver.
Apr  7 15:05:04 loxberry systemd[1]: Stopped LSB: 1-wire TCP server.
Apr  7 15:05:04 loxberry systemd[1]: Starting LSB: 1-wire TCP server...
Apr  7 15:05:04 loxberry OWFS[7533]: DEFAULT: ow_daemon.c:(144) Entered background mode, quitting.
Apr  7 15:05:04 loxberry OWFS[7533]: DEFAULT: owlib.c:(208) Cannot open USB bus master
Apr  7 15:05:04 loxberry OWFS[7533]: DEFAULT: owlib.c:(52) No valid 1-wire buses found
Apr  7 15:05:05 loxberry owserver[7527]: Starting 1-Wire TCP Server: owserver failed!
Apr  7 15:05:05 loxberry systemd[1]: Started LSB: 1-wire TCP server.
Apr  7 15:05:05 loxberry systemd[1]: Stopping LSB: 1-wire HTTP server...
Apr  7 15:05:06 loxberry owhttpd[7542]: Stopping 1-Wire HTTP Daemon: owhttpd.
Apr  7 15:05:06 loxberry systemd[1]: Stopped LSB: 1-wire HTTP server.
Apr  7 15:05:06 loxberry systemd[1]: Starting LSB: 1-wire HTTP server...
Apr  7 15:05:06 loxberry OWFS[7560]: DEFAULT: ow_daemon.c:(144) Entered background mode, quitting.
Apr  7 15:05:07 loxberry owhttpd[7554]: Starting 1-Wire HTTP Daemon: owhttpd.
Apr  7 15:05:07 loxberry systemd[1]: Started LSB: 1-wire HTTP server.
Apr  7 15:05:07 loxberry systemd[1]: Stopping LSB: Loxberry Plugin 1Wire...
Apr  7 15:05:08 loxberry 1wire[7569]: Service 1wire wird beendet
Apr  7 15:05:08 loxberry systemd[1]: Stopped LSB: Loxberry Plugin 1Wire.
Apr  7 15:05:08 loxberry systemd[1]: Starting LSB: Loxberry Plugin 1Wire...
Apr  7 15:05:08 loxberry systemd[1]: Started Session c493 of user root.
Apr  7 15:05:08 loxberry 1wire[7598]: Service 1wire gestartet
Apr  7 15:05:08 loxberry systemd[1]: Started LSB: Loxberry Plugin 1Wire.
Apr  7 15:05:08 loxberry systemd[1]: Stopping LSB: 1-wire TCP server...
Apr  7 15:05:09 loxberry owserver[7722]: Stopping 1-Wire TCP Server: owserver.
Apr  7 15:05:09 loxberry systemd[1]: Stopped LSB: 1-wire TCP server.
Apr  7 15:05:09 loxberry systemd[1]: Starting LSB: 1-wire TCP server...
Apr  7 15:05:09 loxberry OWFS[7736]: DEFAULT: ow_daemon.c:(144) Entered background mode, quitting.
Apr  7 15:05:09 loxberry OWFS[7736]: DEFAULT: owlib.c:(208) Cannot open USB bus master
Apr  7 15:05:09 loxberry OWFS[7736]: DEFAULT: owlib.c:(52) No valid 1-wire buses found
Apr  7 15:05:10 loxberry owserver[7730]: Starting 1-Wire TCP Server: owserver failed!
Apr  7 15:05:10 loxberry systemd[1]: Started LSB: 1-wire TCP server.
Apr  7 15:05:10 loxberry systemd[1]: Stopping LSB: 1-wire HTTP server...

```

**Comment by Strike1988** [comment]
Ich habe noch kein 1-Wire gerät angeschlossen, weder i2c oder usb.

**Comment by Woersty** [comment]
Das ist ein Problem... wie du siehst:
```
Apr  7 15:05:09 loxberry OWFS[7736]: DEFAULT: owlib.c:(208) Cannot open USB bus master
Apr  7 15:05:09 loxberry OWFS[7736]: DEFAULT: owlib.c:(52) No valid 1-wire buses found
```

**Comment by Strike1988** [comment]
Deinstallieren des 1 Wire Plugins hat geholfen. Sprich erst installieren, wenn die entsprechende 1-Wire Hardware angeschlossen ist. Eventuell nach zukünftigen Plugin-Update möglich ohne Hardware.

**Comment by Woersty** [comment]
Von wem ist das Plugin? Melde es dort als issue. Ich kann gerade nicht. Bin unterwegs.

**Comment by Strike1988** [comment]
Von Dieter Schmidberger aka Hismastervoice, den hab ich schon über einen Forumbeitrag bescheid gegeben.  Da er kein GITHUB verwendet.
