### ISSUE TITLE
Logrotate - No space left on device

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#699]
```
/etc/cron.daily/logrotate:
error: Compressing program wrote following message to stderr when compressing log /opt/loxberry/log/system_tmpfs/apache2/error.log.1:

gzip: stdout: No space left on device
error: failed to compress log /opt/loxberry/log/system_tmpfs/apache2/error.log.1
run-parts: /etc/cron.daily/logrotate exited with return code 1
```
Können wir das nicht vorher / besser abfangen?

`tmpfs                               25M   25M     0 100% /opt/loxberry/log/system_tmpfs
`

**Comment by mschlenstedt** [comment]
Ja, das wäre gut. Ist ja ein bash-Skript: Man könnte aufräumen, wenn der Platz < 5 MB ist. Z. B. die ältesten Dateien löschen.

**Comment by mschlenstedt** [comment]
Für @svethi  ist das ein Einzeiler :-)

**Comment by Strike1988** [comment]
Ich habe wohl zeitgleich den gleichen Issue eröffnet, könnt ihr dann bitte löschen/schließen. #698

**Comment by Woersty** [comment]
Wurde zwar bei mir durch einen Programmierfehler ausgelöst (loop) aber trotzdem wäre das schön, wenn man das mal so 1x die Stunde oder so prüft.

**Comment by Woersty** [comment]
Gleiches Thema bei `/var/log`

**Comment by mschlenstedt** [comment]
Ich habe dazu mal ein separates Issue #700  eröffnet.
