### ISSUE TITLE
Freien Speicherplatz in tmpfs prüfen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#700]
Der freie Speicherplatz müsste 1x Stunde in den tmpfs geprüft werden. Wenn der Platz kleiner < X MB ist, soll aufgeräumt werden. Die ältesten Dateien sollen gelöscht werden, bis der Platz wieder > x MB ist.

Siehe auch #698  und #699

**Comment by christianTF** [comment]
Das müssten wir über logrotate abfangen, glaub ich.
Wir haben dort derzeit einen Parameter Daily, d.h. er rotiert die Logs nur täglich.
Bei irgendwas hab ich das schon auf MAXMB (oder so irgendwie) geändert, statt Daily. Das ziehe ich für die anderen Sachen nach.
Wenn es schneller als in einer Stunde passiert, ist das sowieso irgendwo ein Bug.

**Comment by christianTF** [comment]
```
/opt/loxberry/log/system/*/*.log {
	missingok
	rotate 4
	compress
	delaycompress
	notifempty
	nomail
	maxsize 1M
	maxage 5
	create 644 loxberry loxberry
}
```
Das ist, was wir (nur) für `system/*/*.log` derzeit live haben.
Anders als bei den anderen Einträgen gibt es hier kein **daily** sondern nur **maxsize**, d.h. logrotate schaut stündlich und rotiert, wenn das File größer als 1MB ist.
**rotate 4** heißt, viermal rotieren, und **maxage 5** bedeutet, nach 5 Tagen löschen.
Wenn wir **compress** weglassen, erledigt sich auch #400

**Comment by christianTF** [comment]
Logfile-Cleanup https://github.com/mschlenstedt/Loxberry/commit/241c81137781c7116ba8815ca3238025399709fb

- Wird derzeit getriggert vom LOGEND-Event von LoxBerry::Log / LBLog
- Prüft alle Mountpoints, die tmpfs sind
- Wenn der freie Speicher kleiner 25% ist, beginnt für diesen Mountpoint das housekeeping
- Housekeeping heißt:
- Alle Dateien, die .log enthalten suchen
- Nach Creation Date aufsteigend sortieren
- So lange Datei für Datei löschen, bis die 25% erreicht/überschritten sind

Die Routine behandelt **alle** Logfiles in **allen** tmpfs-Mountpoints. Es beschränkt sich **nicht** auf die Logfiles des SDKs.
