### ISSUE TITLE
Probleme beim mount über /etc/fstab

### ISSUE THREAD

**Issue by scharrin2** [mschlenstedt/Loxberry#701]
Ich habe heute das Update von 1.2.0.2 auf 1.2.0.3 gemacht.

Leider ist der Fehler aus den Issues 695 und 696 noch immer vorhanden.

**Comment by mschlenstedt** [comment]
Poste mal deine fstab. Also die mit den Leerzeilen. Bei meinen Tests ging das.

**Comment by scharrin2** [comment]
Hallo,

anbei die /etc/fstab vor dem Neustart und einmal nach dem Neustart.

Viele Grüße,

[fstab_vor_Neustart.txt](https://github.com/mschlenstedt/Loxberry/files/1891038/fstab_vor_Neustart.txt)
[fstab_nach_Neustart.txt](https://github.com/mschlenstedt/Loxberry/files/1891040/fstab_nach_Neustart.txt)

**Comment by christianTF** [comment]
@scharrin2 Ist das noch aktuell?

**Comment by scharrin2** [comment]
@christianTF Die /etc/fstab wird jetzt durch einen Neustart nicht mehr verändert
