### ISSUE TITLE
Storage-Lib: Mehrzahl oder Einzahl?

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#702]
Ich hatte angefangen die Funktionen als Mehrzahl zu benennen:

LoxBerry::Storage::get_netserver**s**
LoxBerry::Storage::get_netshare**s**
LoxBerry::Storage::get_usbstorage**s**

Um konsistent zu sein müssten die neuen Funktionen ebenfalls Mehrzahl sein oder wir benennen die bestehenden Funktionen in Einzahl um.

LoxBerry::Storage::get_storage**s**_html
LoxBerry::Storage::get_storage**s**

**Comment by christianTF** [comment]
Siehst du, das wollte ich auch schon fragen, wie wir das nennen.

Ich hatte/habe das Gefühl, dass _storages_ irgendwie nicht richtiges Englisch ist (storage im Sinne von Speicher ist schon eine Mehrzahl), so wie es keine Mehrzahl von Schotter in deutsch gibt.

Im Grunde ist es mir aber nicht besonders wichtig - get_storage ist noch nicht "live", und get_storage_html existiert nur als Stub.

**Comment by mschlenstedt** [comment]
Storages gibt es schon - klingt aber rigendwie etwas "ungelenk": https://www.google.de/search?q=storages&oq=storages&aqs=chrome..69i57j69i61j69i60l3j69i61.1312j0j7&sourceid=chrome&ie=UTF-8

Ich wäre dafür Einzahl zu verwenden. Bei den bestehenden Funktionen müssten wir aber aus Kompatibilität auch die alte Schreibweise (Mehrzahl) beibehalten. Wenige (niemand?) dürften das schon in Plugins benutzen. Ich glaube der einzigste war @Woersty

**Comment by christianTF** [comment]
LoxBerry::Storage::get_usbstorages --> LoxBerry::Storage::get_usbstorage

Die jetzt dazukommenden Funktionen heißen dann:
LoxBerry::Storage::get_storage
LoxBerry::Storage::get_storage_html

Betrifft jedenfalls:
- Modul Storage
- Widget USB-Storage
- @Woersty's Plugin(s)

netservers und netshares bleibt gleich, weil da ist die Mehrzahl stimmig.

**Comment by mschlenstedt** [comment]
Lib Erledigt mit e880da8b848735a1c14909409c79c3407abb6979

**Comment by mschlenstedt** [comment]
@Woersty könnte dann aber gleich auf LoxBerry::Storage::get_storage_html umbauen.

**Comment by christianTF** [comment]
Das muss erst mal fertig werden! :-)
Komm zu nix - heute ist wieder GNTM, da sollt ich wieder 2-3 Stunden reinquetschen können :-)

**Comment by christianTF** [comment]
LoxBerry-Core-seitig ist ja das alles geändert - @Wörsty nicht vergessen, das bei dir nachzuziehen!
