### ISSUE TITLE
setloxberryid: Bei fehlenden Werten keine Daten senden

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#704]
z. B. fehlende Architektur:

![image](https://user-images.githubusercontent.com/16830799/38967330-cc437abc-4386-11e8-916e-c287cff21c1a.png)

**Comment by christianTF** [comment]
Wir filtern das serverseitig, ist sicherer.

**Comment by christianTF** [comment]
collect.php am Server:
- Wenn leere Architektur --> "ARM"

Leere Einträge aus der Datenbank gelöscht.
