### ISSUE TITLE
In /etc/environments fehlt LBPBIN, LBSBIN, LBSSBIN

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#705]
LBPBIN=/opt/loxberry/bin/plugins
LBSBIN=/opt/loxberry/bin
LBSSBIN=/opt/loxberry/sbin

Muss im Update integriert werden und in setenvironments.sh

**Comment by christianTF** [comment]
Info für mich selbst:
setenvironment.sh patched:

-  [x] /etc/environment
-  [x] $LBHOME/system/apache2/envvars
-  [x] $LBHOME/system/lighttpd/conf-available/15-fastcgi-php.conf

Update-Script muss zusätzlich patchen:
-  [x] system/apache2/sites-available/000-default.conf
-  [x] system/sudoers/lbdefaults
-  [x] system/lighttpd/conf-available/15-fastcgi-perl.conf
-  [x] system/lighttpd/conf-available/15-fastcgi-php.conf
