### ISSUE TITLE
Issue #696 wurde geschlossen

### ISSUE THREAD

**Issue by scharrin2** [mschlenstedt/Loxberry#706]
Hallo zusammen,

der Issue #696 wurde geschlossen.

Ich habe heute auf einem neuen Raspberry Pi 3 B das Loxberry-Image 1.2.0.2 isnatlliert und ein Update auf 1.2.0.3 gemacht.
Der mount in der /etc/fstab wird aber nach wie vor nicht nach einem Neustart ausgeführt.
Nur ein manuelles "mount -a" unter roor mountet das Verzeichnis.

Mount:
192.168.3.3:/backup /backup nfs nolock,rsize=8192,wsize=8192,timeo=14,intr,nofail 0 0

Viele Grüße,
Christian

**Comment by christianTF** [comment]
Hi Christian! Ist das noch aktuell?

**Comment by scharrin2** [comment]
@christianTF Dieses Problem existiert nach wie vor.

Wenn ich "mount -a" ausführe, wird das Filesystem unter /backup gemountet.

Nach einem Neustart wird dies aber nicht automatisch gemacht.

**Comment by christianTF** [comment]
Ich glaube nicht, dass das was LoxBerry-Spezifisches ist, sondern irgendein Timing-Issue oder ein Issue mit dem Eintrag in der fstab (ich selbst nutze kein NFS, kann dazu nichts Konkretes sagen).

In `/etc/rcS.d/` ist ein File namens S12mountnfs.sh, das durch systemd ausgeführt wird und die fstab parsed und mountet. Dieses Script schreibt ins syslog, dort müsste man was finden.

Es gibt ein zweites File in `/etc/network/if-up.d` namens mountnfs, das eigentlich das gleiche macht wie das oben beschriebene. Das wird glaub ich nicht benutzt, wenn systemd die NFS-Mounts durchführt.

Das sind alles Standardsachen von Raspbian, ohne eine Anpassung von uns.

Was Michael im anderen Issue eingebaut hat, ist ein zusätzliches mount -a am Ende des Bootens. 

Schau bitte mal ins Syslog, ob da was zu finden ist. 

lg, Christian

**Comment by scharrin2** [comment]
Hallo Christian,

in /var/log/messages habe ich dazu keinen Fehler gefunden.

Mittlerweile habe ich mir das Verzeichnis per SMB gemountet und mache dorthin die Backups.

Persönlich hätte mir NFS besser gefallen, da ich hier keinen User und Passwort brauche – aber so geht es auch.



Viele Grüße,
Christian

Von: Christian Fenzl <notifications@github.com>
Antworten an: mschlenstedt/Loxberry <reply@reply.github.com>
Datum: Dienstag, 31. Juli 2018 um 17:25
An: mschlenstedt/Loxberry <Loxberry@noreply.github.com>
Cc: Christian Scharringer <christian@scharringer.de>, Author <author@noreply.github.com>
Betreff: Re: [mschlenstedt/Loxberry] Issue #696 wurde geschlossen (#706)


Ich glaube nicht, dass das was LoxBerry-Spezifisches ist, sondern irgendein Timing-Issue oder ein Issue mit dem Eintrag in der fstab (ich selbst nutze kein NFS, kann dazu nichts Konkretes sagen).

In /etc/rcS.d/ ist ein File namens S12mountnfs.sh, das durch systemd ausgeführt wird und die fstab parsed und mountet. Dieses Script schreibt ins syslog, dort müsste man was finden.

Es gibt ein zweites File in /etc/network/if-up.d namens mountnfs, das eigentlich das gleiche macht wie das oben beschriebene. Das wird glaub ich nicht benutzt, wenn systemd die NFS-Mounts durchführt.

Das sind alles Standardsachen von Raspbian, ohne eine Anpassung von uns.

Was Michael im anderen Issue eingebaut hat, ist ein zusätzliches mount -a am Ende des Bootens.

Schau bitte mal ins Syslog, ob da was zu finden ist.

lg, Christian

**Comment by mschlenstedt** [comment]
Fixed in dbc7e454c7cc63bff84ff4b19915e1284d72b190
