### ISSUE TITLE
Logrotate: Nur ein nicht-gezipptes Logfile aufbewahren

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#707]
Logrotate umstellen, sodass nur ein nicht-gzipptes Logfile aufbewahrt wird (das aktuelle). zudem überprüfung wie viele Logfiles wirklich aufbewahrt werden müssen. Max. 1 archiviertes?

Das spart bei großen Logfiles Platz im tmpfs.

```
-rw-rw-rw- 1 loxberry loxberry 2383226 Apr 22 05:12 wu4lox.log
-rw-rw-rw- 1 loxberry loxberry 2515284 Apr 21 06:24 wu4lox.log.1
-rw-rw-rw- 1 loxberry loxberry    2589 Apr 20 06:24 wu4lox.log.2.gz
```

**Comment by mschlenstedt** [comment]
Siehe auch #700

**Comment by christianTF** [comment]
Config angepasst per https://github.com/mschlenstedt/Loxberry/commit/c8c7666aae36f48ad1e2a8311afb68c58e699a8f
