### ISSUE TITLE
Update Spanish Translation

### ISSUE THREAD

**Issue by madito** [mschlenstedt/Loxberry#709]
Add
[language_es.zip](https://github.com/mschlenstedt/Loxberry/files/1939792/language_es.zip)

**Comment by christianTF** [comment]
Thanks a lot!
Christian

**Comment by Woersty** [comment]
@madito Please subscribe to https://github.com/mschlenstedt/Loxberry/issues/666 to keep your translation up2date if not already the case... 
¡gracias!
