### ISSUE TITLE
Wiki-Artikel zum Templatesystem kaputt

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#710]
Irgendwie sind einige Screenshots kaputt:

http://www.loxwiki.eu/display/LOXBERRY/Perl+Template-System+ab+LoxBerry+1.0

**Comment by mschlenstedt** [comment]
![image](https://user-images.githubusercontent.com/16830799/39164673-0a4e7e6c-4781-11e8-9916-905c7cfb9b39.png)


![image](https://user-images.githubusercontent.com/16830799/39164683-1d448d5e-4781-11e8-8c4a-7602225d4f47.png)

**Comment by mschlenstedt** [comment]
![image](https://user-images.githubusercontent.com/16830799/39164696-2fa36038-4781-11e8-87bd-d1c75db7b241.png)

Muss das /lang/help_special_de.**html** heissen?

**Comment by christianTF** [comment]
Hmmm - ich weiß nicht, wie das kaputt werden konnte....

Ganz unten habe ich eine Tabelle dran gehängt, wie die Parameter und Dateien aussehen und liegen müssen:
http://www.loxwiki.eu/display/LOXBERRY/Funktionen+zum+Erstellen+des+Templates
http://www.loxwiki.eu/display/LOXBERRY/PHP+functions+to+create+your+webpage+with+LoxBerry+design

**Comment by christianTF** [comment]
Ich hab den Artikel nochmal ganz durchgelesen, korrigiert, optimiert, ergänzt.
