### ISSUE TITLE
Plugins wo NAME != FOLDER

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#712]
[lbplugins.pdf](https://github.com/mschlenstedt/Loxberry/files/1953874/lbplugins.pdf)

Spalten sind:
**Title, name, folder**
- "BLE-Scanner","BLE-Scanner","ble_scanner"
- "Sonos","Sonos","sonos4lox"
- "APC-UPS","APC-UPS","apc_ups"
- "DynDNS-Refresher","DynDNS-Refresher","dyndns_refresher"
- "RPi-Monitor","RPi-Monitor","rpi_monitor"
- "Sample Plugin","sampleplugin_name","sampleplugin_folder"
- "Alexa&lt;-&gt;Lox2.0.5","alexalox20","alex2lox"
- "Sample Plugin","sampleplugin_name","ebus"
- "Fritz.Lox2","fritzlox","fritzlox2"
- "Raumserver","loxberry-plugin-raumserver","raumserver"
- "SML-eMon","SML-eMon","sml_emon"
- "A-cab Sonos Music","SonosMusic","a-cabMusic"

Interessant auch, dass die Hälfte davon im NAME nicht die Vorgabe einhält (*Keine Leerzeichen, keine Sonderzeichen, nur Kleinbuchstaben!*).

Die Frage ist, ob wir es schaffen, 
- im plugininstall/pluginupdate den NAME = FOLDER zu setzen (als Schritt 1), und
- die Plugin-Database und alle (laufenden) Plugin-Files auf FOLDER zu ändern - ggf. nur im Rahmen eines Plugin-Updates.
Wir müssten den NAME nicht aus der Plugin-DB werfen, sondern beim Plugin-Setup einfach gar nicht verwenden.

**Comment by christianTF** [comment]
{| cellpadding="10" cellspacing="0" border="1" style="text-align:center;"
|+'''lbplugins'''
|- style="background:#ffdead;"
! style="background:#ffffff" | 
 | pluginmd5
 | plugintitle
 | pluginname
 | plugindir
 | pluginauthor
 | pluginemail
 | currtime
 | disabled
|- style="background:#f9f9f9;"
! style="background:#f2f2f2" | Type
 | varchar(32)
 | varchar(60)
 | varchar(40)
 | varchar(40)
 | varchar(60)
 | varchar(60)
 | datetime
 | tinyint(1)
|- style="background:#f9f9f9;"
! style="background:#f2f2f2" | Null
 | NO
 | NO
 | NO
 | NO
 | NO
 | NO
 | NO
 | YES
|- style="background:#f9f9f9;"
! style="background:#f2f2f2" | Default
 | 
 | 
 | 
 | 
 | 
 | 
 | 
 | 
|- style="background:#f9f9f9;"
! style="background:#f2f2f2" | Extra
 | 
 | 
 | 
 | 
 | 
 | 
 | 
 | 
|}

**Comment by mschlenstedt** [comment]
Das hatte ich schon mal überlegt. Bin dann aber zum Schluss gekommen dass man bestehende Installationen schrottet. Das Update wird dabei zerschossen. 

Muss nochmal genau überlegen wie ich darauf gekommen bin. Aber den Versuch habe ich damals bei der Entwicklung von LB1.0 sehrninzensiv betrieben.

**Comment by mschlenstedt** [comment]
https://github.com/mschlenstedt/Loxberry/issues/623

**Comment by christianTF** [comment]
Ich mach's wieder zu und hoffe, dass die Anmerkung in der Anleitung ("sollte gleich sein") bei den Neueintwicklungen ankommt.
