### ISSUE TITLE
Übernahme der network.txt

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#713]
Beim Aufsetzen eines LB hat man die Möglichkeit das Netzwerksetup über die network.txt bereitzustellen. Diese Informationen müssten allerdings auch in die Einstellungen des LB übernommen werden

**Comment by christianTF** [comment]
Ist das nicht schon?

**Comment by christianTF** [comment]
Weiß nicht, wie das jetzt ist, jedenfalls wäre es am besten, die Network-Config on-The-fly zu parsen und nicht auch noch extra irgendwo zu speichern.

**Comment by mschlenstedt** [comment]
Jetzt steht sie in general.cfg

**Comment by mschlenstedt** [comment]
Ich schreibe sie erstmal von network,txt in die general.cfg. "Online parsen" machen wir später.

**Comment by christianTF** [comment]
Doppeldeutig: Hast du das schon umgesetzt, oder nur vorgenommen? ;-)

**Comment by mschlenstedt** [comment]
Nein, ist noch nicht erledigt. Muss ins Initskript und müsste deswegen Bash sein. Hab noch keinen einfachen weg gefunden aus der Bash in die general.cfg zu schreiben. Vermutlich am einfachsten mit sed/awk.

**Comment by mschlenstedt** [comment]
Zu kompliziert - insbesondere auch mit IPv6. Wer diese "Notlösung" verwendet, muss anschließend noch einmal über das Widget konfigurieren.
