### ISSUE TITLE
Fehler in Plugin-Installation korrekt behandeln

### ISSUE THREAD

**Issue by andweber** [mschlenstedt/Loxberry#716]
als Feature Wunsch;

scheitert die Installation eines Plugins - wird dieses derzeit nicht aufgeräumt (gelöscht) sondern erscheint anschließend in der Plugin-Verwaltung. Ich gehe davon aus - dass dies bewusst ist.

Es wäre gut, wenn dieses Plugin dann z.B. mit einem "Achtungszeichen" markiert wird, um deutlich zu machen, dass ggf. ein Problem existieren kann.

**Comment by christianTF** [comment]
Hi Andreas,

war das der Installationsversuch mit dem fehlerhaften Logging von #717, das mit Fehler _CRITICAL: Fehler während der Script-Installation, die Installation wurde beendet._ beendet wurde, oder war das ein anderer Fehler?

Grundsätzlich ist ein Fehlerhandling in der Plugininstallation enthalten, die aufräumt und keinen Eintrag in der Plugininstallation erzeugt. 

Es kommt auch noch darauf an, ob es ein Update oder eine Neuinstallation ist.

Wie war das bei dir?
- Neuinstallation oder Update?
- Welches Installscript ist aufgeschlagen?

Danke,
Christian

**Comment by andweber** [comment]
Ja, es war genau dieser Installversuch, bei einer Neuinstallation, in der preinstall.sh - direkt am Anfang (beim Einschalten des logs)

Das Skript erkennt auch den Fehler und räumt auf. Dennoch existiert dann das nicht installierte Plugin in der Pluginverwaltung.

Das Verhalten ist glaube ich analog, wenn die Installation im postinstall.sh abbricht.

**Comment by christianTF** [comment]
Reproduziert:

![image](https://user-images.githubusercontent.com/14220265/49727872-99677b80-fc71-11e8-99e6-398e573f340c.png)

![image](https://user-images.githubusercontent.com/14220265/49727928-b603b380-fc71-11e8-8ebd-741c6cf0d3d7.png)

Im angehängten Sample-Plugin wird im preinstall.sh mit `exit 1` beendet, um einen Fehler zu generieren. Dabei zeigt das Setup den Fehler korrekt an, es wird aber trotzdem in die PluginDB geschrieben.
Das müsste für alle Install-Scripts abgefangen werden.
Beim Update muss das speziell gehandhabt werden, weil da soll natürlich nicht "aufgeräumt" werden.

[LoxBerry-Plugin-SamplePlugin-V2-PHP-FAIL.zip](https://github.com/mschlenstedt/Loxberry/files/2662792/LoxBerry-Plugin-SamplePlugin-V2-PHP-FAIL.zip)

**Comment by mschlenstedt** [comment]
Das Verhalten bei Exit 1 ist so gewollt: https://www.loxwiki.eu/pages/viewpage.action?pageId=23462653#Pluginf%C3%BCrdenLoxberryentwickeln(Version1.x)-Rootverzeichnis-Datei:preinstall.shYellowOptional

```Das Skript muss mit einem Exit-Status von "0" (Null) enden, damit es als erfolgreich beendet wird. Bei einem Exit-Statis von 1 wird ein Fehler ausgegeben, aber die Installation wird fortgesetzt. Bei einem Exit-Status > 1 wird die weitere Installation des Plugins abgebrochen.```

Allerdings bleibt das Problem, dass eine fehlerhafte Plugininstallation aktuell nicht rückabgewickelt oder sonstwie markiert wird.

**Comment by mschlenstedt** [comment]
Siehe auch #539

Ich baue erst einmal Notifications bei Fehlern ein. Ich denke, das reicht für den ersten Schritt.
