### ISSUE TITLE
Bashlog NoFile funktioniert nicht

### ISSUE THREAD

**Issue by andweber** [mschlenstedt/Loxberry#717]
folgendes funktioniert bei mir in 1.2.1 nicht mehr, ging mal in 1.0.x

> . $LBHOMEDIR/libs/bashlib/loxberry_log.sh
PACKAGE=$PSHNAME
NAME=kalliope
NOFILE=1 
LOGSTART "kalliope preinstall started."

Bei der Installation des Plugins kommt folgender Fehler:

>initlog.pl Commandline: /opt/loxberry/libs/bashlib/initlog.pl --name=kalliope --package=kalliope_loxscontrol --nofile --message=kalliope preinstall started.
Cannot determine plugin log directory at /opt/loxberry/libs/bashlib/initlog.pl line 62.
Log could not be started
CRITICAL: Fehler während der Script-Installation, die Installation wurde beendet.

Ohne NOFILE, aber dafür mit einer Definition eines FILENAME funktioniert die Plugininstallation.

**Comment by christianTF** [comment]
Hallo Andreas,

sorry dass ich dein Plugin geschreddert habe. @svethi hatte mich vor Änderungen an der Loglib gewarnt.... (@svethi Darfst es sagen: "Hab ich dir gleich gesagt!") 

Ich habe gerade einen Commit gemacht, womit es (glaube ich) wieder funktionieren sollte.
Kannst du das bitte mal probieren.

Bist du nicht in unserer LB-Plugins WhatsApp-Gruppe? Das wäre praktisch.

Wenn es funktioniert, mache ich einen Hotfix-Release (1.2.1.x), damit das schnell draußen ist.

lg, Christian

**Comment by christianTF** [comment]
https://github.com/mschlenstedt/Loxberry/commit/f6a83d14a2bdabe44db49ed97434844204b0a985

**Comment by svethi** [comment]
@christian: Hab ich Dir doch gleich gesagt ;-)

**Comment by andweber** [comment]
ja dies behebt das Problem. Der Fix funktioniert. 

WhatsApp benutze ich nicht.

**Comment by christianTF** [comment]
V1.2.1.5 als Release mit dem Bashlog-Fix
https://github.com/mschlenstedt/Loxberry/releases/tag/1.2.1.5
