### ISSUE TITLE
/var/log wird nicht aufgeräumt

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#719]
Überprüfen der Logrotate-Einstellungen für /var/log.

https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/157811-fehler-beim-komprimieren-des-protokolls

**Comment by mschlenstedt** [comment]
Ist das noch aktuell?

**Comment by christianTF** [comment]
Wenn logrotate einen Fehler wirft, wird es ja offensichtlich rotiert.

Ich bin dem nachgegangen:
- Es wird dafür die Debian-Standard-Config verwendet: `/etc/logrotate.d/rsyslog`
- Standard ist `daily` und `rotate 7`, d.h. die Files werden täglich rotiert, komprimiert und nach 7 Tagen gelöscht.

Produktiver Pi:
```
root@buepi:/var/log# df -h /var/log
Filesystem      Size  Used Avail Use% Mounted on
tmpfs            50M  5.9M   45M  12% /var/log
```
Da muss auf Tico's Pi schon was Besonderes schiefgelaufen sein, dass das voll wurde.

Corner-Case, Einzelfall, bisher nicht nochmal vorgekommen.
