### ISSUE TITLE
Backup: Passwort im Klartext in Logdatei bei Loglevel "Debug"

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#72]
Steht der Loglevel auf "Debug" kommt teilweise das Passwort im Klartext in die Logdatei:

`converted 'ftp://admin:KLARTEXTPASSWORT@192.168.3.210:21/log' (ANSI_X3.4-1968) -> 'ftp://admin:KLARTEXTPASSWORT@192.168.3.210:21/log' (UTF-8)`

**Comment by Woersty** [comment]
Ähm.. Usernamen lassen oder auch weg? Habe momentan beides durch xxx ersetzt

**Comment by Woersty** [comment]
Mist, der Statuscode stimmt nun nicht mehr.

**Comment by Woersty** [comment]
Gelöst mit #73

**Comment by mschlenstedt** [comment]
Usernamen fand ich ok, letztendlich ist es aber vielleicht sicherer beides durch XXX zu ersetzen.
