### ISSUE TITLE
/admin/system/tools/showalllogs.cgi bleibt hängen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#724]
Nach langer Ladezeit kommt ein Fehler 500.

"Muss in einen Cronjob"

"Es gibt 2 unterschiedliche Cleanups, das muss ich mir im Detail anschauen"

**Comment by christianTF** [comment]
@mschlenstedt 
Kannst du nach Update auf Latest bitte probieren:
```/opt/loxberry/bin/db_maint.pl action=cleanup_logfiles```

Das könnte etwas dauern - danach sollte showalllogs.cgi wieder in angemessener Zeit reagieren.

**Comment by mschlenstedt** [comment]
Der obige Befehl war innerhalb einer halben Sekunde ausgeführt.

http://loxberry/admin/system/tools/showalllogs.cgi?package=PLUGINNAME&name=

läd trotzdem noch unendlich und bringt dann Fehler 500.

**Comment by christianTF** [comment]
Hi @mschlenstedt ,

Kannst du hier 
https://github.com/mschlenstedt/Loxberry/blob/c0cbabe35f3bec10f031be7e5a2a7f5982c6bd8b/webfrontend/htmlauth/system/tools/showalllogs.cgi#L18 das Debug 1 setzen und mir das Log anhängen. 

Mal schauen, wo der hängt...

**Comment by christianTF** [comment]
Zweiter Test:
```
sqlite3 /opt/loxberry/data/system/logs_sqlite.dat
select count(*) from logs;
select count(*) from logs_attr;
```
Das gibt die Anzahl der DB-Einträge und generischen Attribute aus.
Bei mir sind das 33 / 1064.

**Comment by mschlenstedt** [comment]
Hier das error.log. Es wird mit diesen Einträgen vollgeschrieben:

```
<--- log_db_delete_logkey
   Commit
<--- log_db_delete_logkey
   Commit
```

Zweiter Test:

```
loxberry@loxberrydevil:~ $ sqlite3 /opt/loxberry/data/system/logs_sqlite.dat
SQLite version 3.16.2 2017-01-06 16:32:41
Enter ".help" for usage hints.
sqlite> select count(*) from logs;
67543
sqlite> select count(*) from logs_attr;
1625169
sqlite>
```

[debug_error.zip](https://github.com/mschlenstedt/Loxberry/files/2254271/debug_error.zip)

**Comment by mschlenstedt** [comment]
Auf einem zweiten LB (einer meiner Produktiv-LBs):

```
loxberry@loxberrykeller:~ $ sqlite3 /opt/loxberry/data/system/logs_sqlite.dat
SQLite version 3.16.2 2017-01-06 16:32:41
Enter ".help" for usage hints.
sqlite> select count(*) from logs;
27079
sqlite> select count(*) from logs_attr;
475898
sqlite>
```

**Comment by christianTF** [comment]
https://github.com/mschlenstedt/Loxberry/commit/5c81fd902f285e3541b37bc65d0f38847a5fa0fa

Bulk delete
2 Minuten für die 67500/1,6Mio. Einträge
