### ISSUE TITLE
setdatetime.pl zerschiesst Timezone-Config

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#725]
Seit jessie ist /etc/localtime keine Datei mehr sondern ein SymLink. Damit zerschiesst das Skript /sbin/setdatetime.pl die Systemkonfiguration.

Entweder ebenfalls einen Symlink setzen oder (besser) gleich timedatectl nehmen:

>@Schlenn kann man nicht einfach timedatectl set-timezone „neue Zeitzone“ nehmen? Dann brauchste 
>Dich nicht mehr um die Systeminterna kümmern

**Comment by christianTF** [comment]
![image](https://user-images.githubusercontent.com/14220265/43509250-65142baa-9572-11e8-80a0-79b75c71c20c.png)
`reboot_required("Text");`  einbauen
