### ISSUE TITLE
Translation-Request

### ISSUE THREAD

**Issue by gmkey** [mschlenstedt/Loxberry#726]
I have a new or changed translation file for the LoxBerry in Dutch
[language_nl.ini.zip](https://github.com/mschlenstedt/Loxberry/files/2280511/language_nl.ini.zip)

**Comment by gmkey** [comment]
[language_nl.ini.zip](https://github.com/mschlenstedt/Loxberry/files/2280519/language_nl.ini.zip)
A newer version with some minor improvements

**Comment by christianTF** [comment]
Thanks for your translation! 
https://www.loxwiki.eu/display/LOXBERRY/What%27s+New+in+V1.2.3

Dutch will be available from v1.2.3.1

Changes to the English base language files are automatically collected in
https://github.com/mschlenstedt/Loxberry/issues/666
