### ISSUE TITLE
Kommunikation Webseite --> daemon

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#727]
Irgendwelche Ideen, wie man es rasch und unkompliziert erreichen könnte, dass mittels eines http-Calls (via Apache) ein eigener Daemon gesteuert werden kann?

Beispielsweise ein Daemon pollt alle 60 Minuten irgendeine Webseite, und jetzt möchte ich per HTTP (entweder direkt vom Plugin-GUI, oder vom Miniserver aus) einen Poll triggern. 
Wie rede ich am besten mit dem Daemon? 

Wie auch immer das gemacht werden könnte, das sollte in irgendeiner Weise eine Modul-Funktion werden.

**Comment by Woersty** [comment]
Ich mache es so:
https://github.com/Woersty/LoxBerry-Plugin-KNXd/blob/master/webfrontend/htmlauth/bin/server_control.pl
bzw.
https://github.com/Woersty/LoxBerry-Plugin-KNXd/blob/master/webfrontend/htmlauth/index.cgi#L280

**Comment by christianTF** [comment]
Wie du schreibst: Unix-Socket, sicher das einfachste.
