### ISSUE TITLE
Some minor improvements to Dutch translation

### ISSUE THREAD

**Issue by gmkey** [mschlenstedt/Loxberry#728]
After your addition of the dutch translation I noticed that there were some inconsistencies. Please add new translation.
[language_nl.ini.zip](https://github.com/mschlenstedt/Loxberry/files/2287893/language_nl.ini.zip)

**Comment by Woersty** [comment]
Done via https://github.com/mschlenstedt/Loxberry/commit/11bf6fd378c1f5fa84390d74622d472c207e6f21

**Comment by Woersty** [comment]
Please subscribe to https://github.com/mschlenstedt/Loxberry/issues/666 to keep your translation up2date.
