### ISSUE TITLE
are all the HTML files in templates/system/{language}/ still needed?

### ISSUE THREAD

**Issue by gmkey** [mschlenstedt/Loxberry#729]
I'm trying to extend the NL translation to extend more than just the ini file.
Just wondering if I should copy and amend all files from templates/system/en/ to templates/system/nl/ ?
Or should I limit to templates/system/nl/help/ and templates/system/nl/setup/ ?

Thanks. 

PS - Do you think you could extract this dirty hack from the front-page and include it in the language.ini files?

	```
	} else {
			//error_log("gethelp: No help found. Returning default text.");
			if ($lang === "de") {
				$helptext = "Keine weitere Hilfe verfügbar.";
			elseif ($lang === "nl") {
				$helptext = "Geen verdere help beschikbaar.";
			} else {
				$helptext = "No further help available.";
			}
			return $helptext; 
```
PS: I'm preparing separate Pull requests for some UK and NL translations

**Comment by christianTF** [comment]
LoxBerry completely reads it’s translation from the ini file. The html files are from LoxBerry 0.2.x and not used anymore, but some of the files are automatically generated for plugin compability.
You don’t need to do anything in the template folders.

The language_en.ini file is LoxBerrys main language and managed by us.

I take a look about the code you‘ve mentioned.


Christian

**Comment by gmkey** [comment]
Thanks!

**Comment by christianTF** [comment]
I will close this issue, and created a new one #731

I haven't added your nl code, because this needs to be fixed for every language, and I don't want to start adding workaround code for every language.

**Comment by gmkey** [comment]
Makes sense. I noticed it only when I tried to translate that particular phrase.
