### ISSUE TITLE
plugininstall.pl: sub purge_installation

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#733]
Ich habe das Problem, dass ich im postroot.sh etwas ins `$lbpdatadir` herunterlade.
Wenn ich ein Update durchführe, bekomme ich Fehler im Log, dass er Dateien nicht gelöscht werden können. 

![image](https://user-images.githubusercontent.com/14220265/44444454-35934700-a5dd-11e8-8cea-448e5490d6ef.png)

Ich hab mir das angeschaut, und das ist die Funktion purge_installation https://github.com/mschlenstedt/Loxberry/blob/27ecb278b0715d8fe09cc890f4c9d11a77601ed1/sbin/plugininstall.pl#L1518

Da hat es mich jetzt gewundert, dass das plugininstall.pl ja als root läuft, aber dort explizit mit dem User `loxberry` aufgeräumt wird. Deswegen kann er beim Update (und wahrscheinlich auch beim Deinstallieren) die Verzeichnisse nicht löschen.

Hat es einen speziellen Hintergrund, dass das nicht einfach per `root` gelöscht wird?

**Comment by mschlenstedt** [comment]
Nur, dass ich möglichst wenig mit root Rechten machen will. Aber postinstall wird doch auch als loxberry ausgeführt, oder? Warum gehören die Dateien dann root?

Lösung könnte ein chown loxberry in deinem Skript sein.

**Comment by christianTF** [comment]
Ich downloade im postroot was ins data, deswegen gehört es root. Ist natürlich doof, wenn es dann genau das Aufräumen trifft.

Ich hab als Workaround jetzt direkt ein chown loxberry:loxberry nach dem Download drin, jetzt passt es. Ist aber eine potentielle Fehlerquelle.
