### ISSUE TITLE
/etc/init.d/loxberry init script - network up detection does not work everywhere

### ISSUE THREAD

**Issue by p3root** [mschlenstedt/Loxberry#734]
Hey guys!

I was contacted from guy from china, that my habridge plugin doesn't start on his loxberry. So I investigated the issue. I found out that the loxberry init script waits for an network connection by trying to contact google.com.

` # wait for network completely up
       log_action_begin_msg "waiting for network comming completely up"

        COUNTER=0
       wget -q --spider http://google.com
       while [ "$?" -ne 0 ] && [ "$COUNTER" -lt 24 ]; do
               log_action_cont_msg "waiting 5 seconds an retest"
               sleep 5
               COUNTER=$((COUNTER + 1))
               wget -q --spider http://google.com
       done
       log_action_end_msg 0
`

That won't work in china. The init script hung at this point. I commented the code out at this loxberry instance that he can use the loxberry properly.

Isn't there any better way to check if there is an internet connection?

**Comment by christianTF** [comment]
https://github.com/mschlenstedt/Loxberry/blob/851ead4d3f2a8f8b4904062712ee60d91fcdb945/sbin/loxberryinit.sh#L116
https://github.com/mschlenstedt/Loxberry/blob/851ead4d3f2a8f8b4904062712ee60d91fcdb945/sbin/loxberryinit.sh#L121

Nicht sehr schön. Würde nicht ein Ping auf den gesetzten DNS reichen?

**Comment by p3root** [comment]
Why wating anyway for an internet connection? What it the loxberry runs offline? The script is anyway marked with required $network. 

`Required-Start:    $remote_fs $syslog $network `

**Comment by christianTF** [comment]
Patrick, fyi gleich vorweg, wie auch immer wir das fixen, benötigt es ein neues Image, und das steht derzeit nicht auf dem Plan.
Muss @mschlenstedt beurteilen, wie der Aufwand dafür ist.

**Comment by p3root** [comment]
@christianTF ist in meinen Augen ein Blocker. Wie schon gesagt, was wenn der Loxberry/MS Offline laufen soll? dann startet der Rest auch nicht.

**Comment by christianTF** [comment]
We realized problems with the network, as despite of the requirements, LoxBerry booted further and daemons failed because of no internet connection.

Many plugins install packages from the Debian repo during setup, therefore LoxBerry mainly is seen as a “connected” device.

**Comment by p3root** [comment]
Allgemein: Bin gewohnt issues in Englisch zu kommentieren. Kann aber auch auf Deutsch schreiben -> finde es nur besser für nicht Deutschsprachige da Englisch in diesem Bereich mehr verbreitet ist. Dient ja auch etwas als Doku ;)

Therefore it is an issue by the daemon who needs an active internet connection? What if (i'm sure it will never happen but you can't know) google.com is down?

**Comment by christianTF** [comment]
Kein Problem :-) Solange wir uns auf eine Sprache einigen *gg*

As I proposed, a check against the locally set DNS may do the job.
As I see the code, it waits for a maximum of two minutes, and then continues. So it should not die in this routine, but only idle for 2 minutes. 

Daemons are started directly behind this code, and LoxBerry claims to try to hand over to the daemons with a running internet connection.

The way with DNS needs to be tested, and it would be interesting, if the mentioned installation stalled at this point, or was simply delayed.

**Comment by christianTF** [comment]
https://github.com/mschlenstedt/Loxberry/commit/3a4cc6591cf93316ce749a16f0159f74634e888f
@svethi

**Comment by svethi** [comment]
Ist mir jetzt zu kompliziert in english. Dieses Warten auf die Netzwerkverbindung wurde aufgrund diverser Pluginfehler eingebaut, die beim Aufstarten hängen geblieben sind, da das Netzwerk noch nicht da war. Das Problem ist, wir haben es hier mit SystemD zu tun und da kann man sich nun leider nicht sicher sein, auch wenn da steht, dass es erst nach dem Netzwerk gestartet werden soll. SystemD arbeitet multithreaded. Man könnte das natürlich wieder rausnehmen und dem Plugin Programmierer das überlassen. Dann würde das Problem nur bei dem Plugin auftreten, was ganz offensichtlich Netzwerk braucht. Man könnte mal versuchen das Gateway oder den lokalen DNS zu erreichen. DNS ist natürlich schwierig, da UDP. Für Ping muss die Gegenstelle natürlich drauf reagieren. Das kann alles ebenso scheitern. Und dann??

**Comment by johny-mnemonic** [comment]
I am not sure what are you trying to achieve, but in case you want to make sure Loxberry is connected to the network, then pinging the default gateway should be sufficient.
As was already mentioned, checking for internet connectivity is not a best idea, as you want to have your smart home working even when the internet is down.
Having few failed plugins (like weather forecast) till internet connection gets up is not a big deal, but whole Loxberry down can be an issue.

**Comment by christianTF** [comment]
For reference, this is the issue #522 we tried to solve.

**Comment by johny-mnemonic** [comment]
That definitely looks to me like you want to only wait for loxberry to become online on local network.
I am not sure, whether you would like to deal with this on our own, or use systemd, but you can use `systemd-networkd-wait-online` binary either way it seems. More details on how to do this in systemd are here: https://unix.stackexchange.com/a/126146, but it seems, that you should be able to call that binary from your script as well. Check `/lib/systemd/systemd-networkd-wait-online --help`.

**Comment by svethi** [comment]
Thanks. I'll have a look on this. I remember reading that already, but somehow that did not work, or the network-online was not yet integrated into the raspbian. In any case, this way had to be gone.

**Comment by johny-mnemonic** [comment]
@svethi Maybe you tried it with older version of systemd where it didn't automatically start `systemd-networkd-wait-online` service, when another unit wants it.
With older versions of systemd one had to manually enable `systemd-networkd-wait-online` service for the dependency to start working.

**Comment by christianTF** [comment]
@svethi today did this commit: https://github.com/mschlenstedt/Loxberry/commit/8fdda3d4ee02201390cf492b67e6a7809eed5b6e

**Comment by mschlenstedt** [comment]
I just found this discussion here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826886

> allow-hotplug does not block the boot process until network is available, this is by design. If you use "auto eth0", your NFS mounts should work.

We currently use "allow-hotplug". Changing this to "auto eth0" may solve this problem (and also the problem that some network shares do not mount during boot time).

**Comment by mschlenstedt** [comment]
Fixed in dbc7e454c7cc63bff84ff4b19915e1284d72b190
