### ISSUE TITLE
LBUpdate History - Komischer Inhalt wird angezeigt

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#738]
![image](https://user-images.githubusercontent.com/14220265/44731998-b1f9be80-aae4-11e8-9979-ff9552d1e6fe.png)

@Woersty , du hast in die Logfileliste von LBUpdate ja was eingebaut, dass eine Zeile aus dem Logfile dort angezeigt wird.
Weil sich der Logfile-Inhalt geändert hat, ist das jetzt irreführend, weil jetzt genau die Zeile angezeigt wird mit der aktuellen Version. Sprich, die Übersicht über die Updates zeigt die alte Version an.

Das sollte gefixt werden.

**Comment by christianTF** [comment]
Das könnte man heute grundsätzlich anders machen, weil wir die Logfiles jetzt in der Datenbank haben.
Die History könnte direkt showalllogs.cgi verwenden, und bei LOGCRIT könnte ich noch einen Status für "Fehlgeschlagen" in die Datenbank aufnehmen für ein Symbol.

**Comment by Woersty** [comment]
Äh ja.
