### ISSUE TITLE
LBUpdate auch per manueller Upload-Datei.

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#739]
Falls keine Internetverbindung oder Downloadroutine kaputt.

**Comment by christianTF** [comment]
Man könnte - pragmatisch - das manuelle Update aus der Plugin-Verwaltung ausführen. Dort ist eigentlich schon alles drin: 
WebIf, Upload, Entpacken, Prüfung des Inhalts, Log viewer.

Ein ZIP des Repos ließe sich leicht erkennen: Keine plugin.cfg, dafür eine General.cfg.default usw.
Dort müsste man abbiegen in loxberryupdate.pl.

Ein paar hätten es ja sogar schon auf diesen Weg versucht, scheint also naheliegend zu sein ;-)

**Comment by mschlenstedt** [comment]
Finde ich nicht so "schön" und irgendwie inkonsistent. So schwierig ist der Upload nicht - das ist recht wenig Code. Und in den lbupdate-Prozess müsste man es sowieso hineinfummeln.

**Comment by christianTF** [comment]
Stimmt, ist nicht schön. Passt dort nicht hin.
Es sollte jedenfalls etwas untergeordnet sein, damit nicht die Leute anfangen, herumzuprobieren, sondern das nur im Notfall nutzen.

**Comment by Woersty** [comment]
Man könnte einen billigen DAU-Schutz einbauen indem man solche Updates als ZIP mit Passwort bereitstellt.
Das PW ist dann einfach hardcoded und fertig. Die Cracks hält das natürlich nicht auf. Aber Oma Erna.

**Comment by christianTF** [comment]
Das ist nicht die Absicht, eine zusätzliche Installroutine zu bauen, und auch nicht, Benutzer aktiv von der Verwendung auszuschließen.

Es muss einen Plan B für den "LoxBerry Update-Fehler" Fall geben, es soll sich aber wirklich um einen Notfallweg handeln. Die Installation muss mit LBUpdate passieren, die enthaltenen Routinen sind sehr komplex und das brauchen wir nicht nochmal neu bauen. 

Für mich wäre es ausreichend, wenn es eine unabhängige Uploadseite (zb in tools/) gibt, die im UI gar nicht verlinkt ist. Wenn LBUpdate wieder stirbt, kann den Link auch jemand im Forum/Wiki nachlesen.

**Comment by mschlenstedt** [comment]
Da es nur für den Notfall ist, würde auch die alte Updateroutine des LB 0.2.x ausreichen. Dort konnte man ein ZIP hochladen. Das ZIP wurde entpackt und das darin enthaltene Skript ausgeführt.

Das wäre dann an LBUpdate komplett vorbei und hätte nur eingeschränkte Funktionalität. Aber um per "wget" ein neues lbupdate.cgi zu holen reicht's aus.

Wörsty hat aber schon recht: Egal, was wir machen: es ist ein Sicherheitsrisiko. Andererseits ist das jede Plugininstallation auch, da hier Skripte auch mit Root-Rechten ausgeführt werden.

**Comment by christianTF** [comment]
Das Sicherheitsrisiko fangen wir per SecurePIN ab.

Das DAU-Risiko fangen wir mit der unprominenten Platzierung des Manual Update-UIs ab.

**Comment by christianTF** [comment]
Ich schmeiß das weg, weil unsere Updates **so gut wie immer** Internet-bound sind.

Nachdem auch in den Update-Scripts Pakete nachinstalliert werden und dergleichen, ist ein Offline-LoxBerry Update immer eine große Quelle für Fehler und Supportaufwand.

Es kommt nur Kudlmudl heraus, wenn dann Updatescripts aufschlagen und dergleichen.
Auch Plugins lassen sich in der Regel nicht offline installieren, weil fast immer irgendwelche Pakete nachinstalliert werden.

LoxBerry ist aus meiner Sicht ohne Internet nicht installier- und updatebar, und braucht deswegen in diesem Zeitraum immer Internet.
