### ISSUE TITLE
Miniserverbackup: Error 512

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#74]
Hi,

seit https://github.com/mschlenstedt/Loxberry/pull/73 bekomme ich jetzt beim Backup immer die Meldung, dass es fehlgeschlagen sei. Offensichtlich hat er aber alles gesichert...

`2016-07-25 18:10:50 (723 KB/s) - '/tmp/Backup_1_20160725181042_07040414/prog/sps_0111_20160717221649.LoxCC' saved [286590]

FINISHED --2016-07-25 18:10:50--
Total wall clock time: 5.2s
Downloaded: 16 files, 3.1M in 4.6s (700 KB/s)
2016-07-25 18:10:50 Miniserver #1: Error while fetching ftp://xxx:xxx@192.168.3.210:21/prog. Backup may be incomplete. Errorcode: 512`

**Comment by Woersty** [comment]
Ist das mit #75 gelöst?

**Comment by mschlenstedt** [comment]
Das ist gefixt. Aber jetzt habe ich einen Haufen "No such file"-Fehler:

`2016-07-26 13:20:25 URL: ftp://admin:_password_@192.168.3.210/sys/sys [1208] -> "/tmp/Backup_1_20160726132024_07040414/sys/.listing" [1]
No such file 'links.txt'.

No such file 'sys_CAT.zip'.

No such file 'sys_CSY.zip'.

No such file 'sys_DEU.zip'.

No such file 'sys_ENG.zip'.

No such file 'sys_ENU.zip'.

No such file 'sys_ESN.zip'.

No such file 'sys_FIN.zip'.
`

Ist das bei Dir auch so? Ich konnte noch nicht genauer schauen, ob ich ein Problem am Miniserver habe oder beim Backup...

**Comment by Woersty** [comment]
Schau ich nochmal. Ändere mal die createmsbackup.pl so ab:
`system("$wgetbin $quiet -a $home/log/plugins/miniserverbackup/backuplog.log --retry-connrefused --tries=15 --waitretry=5 -c --timeout=30 -nH -r $url -P /tmp/$bkpdir ");`

**Comment by Woersty** [comment]
Ich habe keine No such file mehr. Kannste nochmal probieren?
#78 sollte das lösen.

**Comment by mschlenstedt** [comment]
Ich habe immer noch einige dieser Fehler, ich habe aber aktuell keine Zeit da weiter hinterher zu gehen. Ich programmiere die Plugin-Schnittstelle, daher lasse ich das Backup-Skript gerade mal "links liegen" :-) Vielleicht ist es auch irgendein Problem nur bei mir?

Beispiel:

`--2016-07-27 18:27:38-- ftp://admin:*password*@192.168.3.210/web/commonv2.zip
=> '/tmp/Backup_MS1_192.168.3.210_2016-07-27_18h27m25s_v07.04.04.14/web/commonv2.zip'
==> CWD not required.
==> PASV ... done. ==> RETR commonv2.zip ... 
No such file 'commonv2.zip'.
`

Dann hast Du die ZIP-Dateien samt Ordner umbenannt. Diese waren so benannt, dass LoxoneConfig das entpackte Archiv automatisch als Sicherung erkennt und korrekte Daten zu miniserver, Firmware etc. anzeigt.

Das solltest Du wieder rückgängig machen!

Grüße,
Micha

**Comment by mschlenstedt** [comment]
Noch eine Ergänzung: die alten Backups scheinen nicht mehr sauber gelöscht zu werden. Kannst Du das bestätigen?

**Comment by Woersty** [comment]
Das mit dem Löschen hängt mit der Namenänderung zusammen.
Wenn ich das korrigiert habe, geht das auch wieder.
Bin dran.

**Comment by mschlenstedt** [comment]
Arrrrrrrgghhhhh, ich habe den Fehler bzgl. der "No such file"-Meldungen gefunden. Hat nichts mit dem Backupscript zu tun. Ich hatte im Konfig-Menü des Miniservers vor kurzem mal "FTP, Telnet" auf "nur lokal" gestellt. Laut Beschreibung sollte das den Zugriff auf Anfragen aus dem lokalen Netz beschränken.

Die Folge ist aber bei aktivierter Option,, dass man auch aus dem lokalen Netz keine Dateien per FTP downloaden kann :-( Der Loxone-FTP-Server listet sie ganz normal dem FTP-Client, aber wenn der die Datei dann anfordert kommt ein "FAIL" des Servers. **Das ist wohl definitiv ein Loxone-Bug!**

Eventuell sollten wir noch einen Hinweis ins Backup einbauen, das diese Option auf "Online" stehen muss - zumindest gilt das für die 7.4.4.14.

![28-07-_2016_09-19-05](https://cloud.githubusercontent.com/assets/16830799/17204224/94de119a-54a4-11e6-839d-1428e98c8683.jpg)

**Comment by Woersty** [comment]
Habe ich doch schon eingebaut , aber nicht gepusht evt.

**Comment by Woersty** [comment]
Was ich gerade gepusht habe ist Quatsch - muss ich nochmal überarbeiten.
Wenn der Wert nicht ausgelesen werden kann, kann ich ihn nicht auswerten....

**Comment by Woersty** [comment]
Hinweis mache ich morgen

**Comment by mschlenstedt** [comment]
Schon erledigt - Pull me down :-)

Von meinem iPad gesendet
