### ISSUE TITLE
 CRITICAL: 14:48:56 Error downloading file. 

### ISSUE THREAD

**Issue by gelbetomate** [mschlenstedt/Loxberry#740]
**Update not possible....**

14:48:50 30.08.2018 14:48:50 TASK STARTED
14:48:50 Update from v1.2.1.5 to v1.2.3.2
14:48:50 INFO: LoxBerry Version 1.2.1.5 ( is_raspberry.cfg )
14:48:50 INFO: Loglevel: 7
 INFO: 14:48:50    Version     : v1.2.3.2
 INFO: 14:48:50    Name        : V1.2.3 Bugfix-Release
 INFO: 14:48:50    Description : - New language: Dutch
- Corrects issues with the timezone settings
- Improve deletion speed for old logfile entries
- SDK: Enhanced get_miniservers function

Details: https://www.loxwiki.eu/x/WAA_Ag
 INFO: 14:48:50    Published   : 2018-08-19T13:38:24Z
 INFO: 14:48:50    Releasetype : Release
 INFO: 14:48:50 Checking if another update is running...
 OK: 14:48:50 No other update running.
 OK: 14:48:50 Update auf v1.2.3.2 gestartet. Im LoxBerry Update Verlauf findest du die Logdatei mit Details.
 INFO: 14:48:50 Update auf v1.2.3.2 gestartet. Im LoxBerry Update Verlauf findest du die Logdatei mit Details.
 INFO: 14:48:50 JSON: {"release_name":"V1.2.3 Bugfix-Release","published_at":"2018-08-19T13:38:24Z","releasetype":"release","release_new":1,"release_body":"- New language: Dutch\r\n- Corrects issues with the timezone settings\r\n- Improve deletion speed for old logfile entries\r\n- SDK: Enhanced get_miniservers function\r\n\r\nDetails: https://www.loxwiki.eu/x/WAA_Ag","release_zipurl":"https://api.github.com/repos/mschlenstedt/Loxberry/zipball/1.2.3.2","release_version":"v1.2.3.2","info":"Update auf v1.2.3.2 gestartet. Im LoxBerry Update Verlauf findest du die Logdatei mit Details.","logfile":"/opt/loxberry/log/system/loxberryupdate/20180830_144850_update.log"}
 INFO: 14:48:50 Starting download procedure for /tmp/loxberry.v1.2.3.2.zip...
 INFO: 14:48:50    Download preparing. URL: https://api.github.com/repos/mschlenstedt/Loxberry/zipball/1.2.3.2 Filename: /tmp/loxberry.v1.2.3.2.zip

 INFO: 14:48:50    Try 1: Checking file size of download...
 INFO: 14:48:51    Returned file size: 
 INFO: 14:48:52    Try 2: Checking file size of download...
 INFO: 14:48:53    Returned file size: 
 INFO: 14:48:53    Try 3: Checking file size of download...
 INFO: 14:48:54    Returned file size: 
 INFO: 14:48:54    Try 4: Checking file size of download...
 INFO: 14:48:55    Returned file size: 
 INFO: 14:48:55    Try 5: Checking file size of download...
 INFO: 14:48:56    Returned file size: 
 **CRITICAL: 14:48:56 Error downloading file.**
 INFO: 14:48:56 JSON: {"release_name":"V1.2.3 Bugfix-Release","published_at":"2018-08-19T13:38:24Z","releasetype":"release","release_new":1,"release_body":"- New language: Dutch\r\n- Corrects issues with the timezone settings\r\n- Improve deletion speed for old logfile entries\r\n- SDK: Enhanced get_miniservers function\r\n\r\nDetails: https://www.loxwiki.eu/x/WAA_Ag","release_zipurl":"https://api.github.com/repos/mschlenstedt/Loxberry/zipball/1.2.3.2","release_version":"v1.2.3.2","info":"Update auf v1.2.3.2 gestartet. Im LoxBerry Update Verlauf findest du die Logdatei mit Details.","logfile":"/opt/loxberry/log/system/loxberryupdate/20180830_144850_update.log"}

**wget on Raspi works... but there is no chance to use the downloaded file manually?!**

wget https://api.github.com/repos/mschlenstedt/Loxberry/zipball/1.2.3.2
--2018-08-30 14:38:56--  https://api.github.com/repos/mschlenstedt/Loxberry/zipball/1.2.3.2
Auflsen des Hostnamens api.github.com (api.github.com) ... 192.30.253.117, 192.30.253.116
Verbindungsaufbau zu api.github.com (api.github.com)|192.30.253.117|:443 ... verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet ... 302 Found
Platz: https://codeload.github.com/mschlenstedt/Loxberry/legacy.zip/1.2.3.2 [folgend]
--2018-08-30 14:38:56--  https://codeload.github.com/mschlenstedt/Loxberry/legacy.zip/1.2.3.2
Auflsen des Hostnamens codeload.github.com (codeload.github.com) ... 192.30.253.121, 192.30.253.120
Verbindungsaufbau zu codeload.github.com (codeload.github.com)|192.30.253.121|:443 ... verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet ... 200 OK
Lnge: nicht spezifiziert [application/zip]
Wird in 1.2.3.2 gespeichert.

1.2.3.2                           [     <=>                                          ]   2,59M  3,00MB/s    in 0,9s

2018-08-30 14:38:57 (3,00 MB/s) - 1.2.3.2 gespeichert [2716598]

**Comment by christianTF** [comment]
https://github.com/mschlenstedt/Loxberry/commit/59dfeb02952d4518ab733ff645ccd70ad36344f5

**Comment by christianTF** [comment]
Please use this Fix-Plugin to update the LoxBerry Update routine:
https://github.com/christianTF/LoxBerry-Update-Fix/archive/master.zip

lg, Christian

**Comment by gelbetomate** [comment]
yep, your update plugin to update the update routine worked ;-)


Danke und Grüße
Achim
