### ISSUE TITLE
logdb in RAM-Disk

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#744]
- Script in `/lib/systemd/system-shutdown` linken, das die logdb zurück auf die sd kopiert
- Kopieren auf RAMdisk in initloxberry.sh
- Cronjob der täglich das File kopiert, wenn es sich geändert hat
- DB im initloxberry auch gleich shrinken, bevor sie auf die ramdisk kopiert wird

Pfad für die logdb steht einmal in Log.pm und einmal in loxberry_log.php

**Comment by mschlenstedt** [comment]
Für den Shutdown sollte es reichen den entsprechenden Aufruf hier einzufügen:

https://github.com/mschlenstedt/Loxberry/blob/9363be649bd8ded3f2528829b3eda42f0e1970bc/sbin/loxberryinit.sh#L163

**Comment by christianTF** [comment]
Erledigt mit https://github.com/mschlenstedt/Loxberry/commit/4756a7d5ca0cc4e14f2239bcd036252d4ae8f063
