### ISSUE TITLE
LoxBerry::Web::mslist_select_html

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#745]
Die Funktion LoxBerry::Web::mslist_select_html sollte eine Option NOLABEL erhalten oder es ermöglichen LABEL -> "" zu setzen. Damit sollte der Platz, der für das Label reserviert ist, freigegeben werden:

![image](https://user-images.githubusercontent.com/16830799/45069273-faf4d880-b0cb-11e8-957e-e7eaecc3c9c4.png)

Die Funktion sollte exportiert werden, sodass sie ohne "LoxBerry::Web::" funktioniert.

**Comment by christianTF** [comment]
```
Change the LABEL parameter behaviour (function currently not in use in plugins)
- Without LABEL parameter, no label is printed.
- With LABEL paramter, the label is used
- Perl: Function is exported
```

@mschlenstedt Kannst du bitte probieren, ob das Verhalten ohne Label-Parameter dem entspricht, wie es aussehen soll!
Evt. muss man im HTML auch noch das `<div class="ui-field-contain">` herausnehmen, dann muss ich es nochmal überarbeiten.

**Comment by mschlenstedt** [comment]
Perfekt.

![image](https://user-images.githubusercontent.com/16830799/45110107-a55b1300-b141-11e8-8059-976af9b89b0f.png)
