### ISSUE TITLE
Updatecheck Logs besser darstellen

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#749]
Anzeige optimieren
Momentan sind die Buttons und Größe redundant, da er nur ein Logfile verwendet.

**Comment by christianTF** [comment]
Obsolet durch den genannten Commit: Ab 1.2.5 wird für jeden Check ein eigenes File angelegt und nicht mehr appended, da das Aufräumen nicht mehr von logrotate sondern vom eigenen Cleanup log_maint.pl verwaltet wird.
