### ISSUE TITLE
showalllogs aufhübschen

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#750]
Schicker machen

**Comment by christianTF** [comment]
Ideen dazu:
- [ ] Als „Log Manager“ Widget platzieren (inkl. im Flyout links)
- [ ] Apache Log ganz nach oben setzen (wenn Package/Name nicht übergeben)
- [ ] In Logfile.cgi implementieren, dass bei einem bestimmten Byte eingesetzt werden kann (Byte würde ich aus der DB bereitstellen --> LOGSTARTBYTE https://www.loxwiki.eu/x/zwHgAQ)
- [ ] Logdatei herunterladen 
- [ ] Evt. unten ein Button, der on-demand (Ajax) Logfiles listet, die nicht in der DB sind (alle ~/Log/Plugins/ abklappern, Delta zur DB erstellen, als zusätzliche Tabelle im HTML appended)
- [ ] #752 berücksichtigen (evt. als Popup)
- [ ] evt. Logfile löschen (es braucht nur das File gelöscht werden - get_logs löscht automatisch DB-Einträge, deren File nicht vorhanden ist)

Zu berücksichtigen: 
- loglist_url https://github.com/mschlenstedt/Loxberry/blob/61c4767453b8b7e832fb0f4f053994ca381dcdfa/libs/perllib/LoxBerry/Web.pm#L594
- loglist_button https://github.com/mschlenstedt/Loxberry/blob/61c4767453b8b7e832fb0f4f053994ca381dcdfa/libs/perllib/LoxBerry/Web.pm#L605
(Gibt’s auch in PHP) rufen showallogs mit Parametern auf

Außerdem wäre es schön, wenn man showalllogs irgendwie direkt in eine andere Seite einbetten könnte.
Z.B. wenn ich in der NavBar einen Tab "Logfiles" habe, dass ich auf eine plugineigene Seite irgendwie das html/Ergebnis von Showalllogs einbinden könnte, ohne mein Plugin zu verlassen.

**Comment by christianTF** [comment]
Ersetzt durch Log Manager
