### ISSUE TITLE
PHP: V1.2.4.4 Irgendwas seit 1.2.4.3 bricht Englisch in PHP

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#754]
![f8c19f26-eecb-469d-8605-499aabd827eb](https://user-images.githubusercontent.com/14220265/45340852-8d97ea80-b598-11e8-9e9e-57fe349bab23.png)

**Comment by christianTF** [comment]
Deutsch geht

**Comment by christianTF** [comment]
Ursache: Bei PHP darf ein Key im Ini-File nicht YES oder NO heißen...

**Comment by mschlenstedt** [comment]
Das ist aber sehr fehleranfällig. Kann man das nicht anfangen?

**Comment by christianTF** [comment]
Ich glaube, das ist ein Bug von parse_ini_file.

Das Problem besteht beim Key, nicht beim Value.

```
[TEST]
Hello="Yes"
```
--> funktioniert korrekt

```
[TEST]
YES="Yes"
```
--> Fehler

Bei parse_ini_file ist bereits INI_SCANNER_RAW gesetzt, das verhindert, dass die values in irgendeiner Weise "behandelt" werden.

Man müsste das Lesen des Files selbst implementieren.  Im Translate habe ich das auch schon selbst implementiert, weil Config::Simple genauso fehleranfällig ist.

**Comment by christianTF** [comment]
```Perl

sub readlanguage2 
{
	
	if (%lang) { return %lang; }
	
	my $content_en = read_file('/opt/loxberry/templates/system/lang/language_en.ini');
	my $content_de = read_file('/opt/loxberry/templates/system/lang/language_de.ini');

	parse_lang_file($content_en);
	parse_lang_file($content_de);

}


sub parse_lang_file
{
	my ($content) = @_;
	my @cont = split(/\n/, $content);

	my $section = 'default';

	foreach my $line (@cont) {
		# Trim
		$line =~ s/^\s+|\s+$//g;	
		my $firstletter = substr($line, 0, 1);
		# print "Firstletter: $firstletter\n";
		# Comments
		if($firstletter eq '' or $firstletter eq '#' or $firstletter eq '/' or $firstletter eq ';') {
			next;}
		# Sections
		if ($firstletter eq '[') {
			my $closebracket = index($line, ']', 1);
			if($closebracket == -1) {
				next;
			}
			$section = substr($line, 1, $closebracket-1);
			# print "\n[$section]\n";
			next;
		}
		# Define variables
		my ($param, $value) = split(/=/, $line, 2);
		$param =~ s/^\s+|\s+$//g;	
		next if ($lang{"$section.$param"});
		$value =~ s/^\s+|\s+$//g;
		my $firsthyphen=substr($value, 0, 1);
		my $lasthyphen=substr($value, -1, 1);
		if ($firsthyphen eq '"' and $lasthyphen eq '"') {
			$value = substr($value, 1, -1);
		}
		# print "$param=$value\n";
		$lang{"$section.$param"} = $value;
	}
}

sub read_file
{
	my ($filename) = @_;
	local $/=undef;
	open FILE, $filename or return undef;
	my $string = <FILE>;
	close FILE;
	return $string;
}

```

Einfache Perl-Routine, ungefähr doppelt so schnell wie readlanguage mit Config::Simple
Laufzeit `LoxBerry::System::readlanguage(undef, undef, 1)`: 680ms
Laufzeit `readlanguage2`: 175ms

**Comment by christianTF** [comment]
In einem Request 6X aufgerufen (mit dem eingebauten Caching)

`LoxBerry::System::readlanguage` Original
Laufzeit: (Durchschnitt 10 Versuche): 513ms

`LoxBerry::System::readlanguage' mit eigener Implementierung
Laufzeit: (Durchschnitt 10 Versuche): 373ms
