### ISSUE TITLE
LB sendet eMails, obwohl deaktiviert

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#759]
Ich habe alle Emails deaktiviert:

![image](https://user-images.githubusercontent.com/16830799/45593103-8dc02d80-b97e-11e8-947b-c334064cd732.png)

Trotzdem scheint er zu versuchen Emails zu senden:

![image](https://user-images.githubusercontent.com/16830799/45593108-9f093a00-b97e-11e8-99e6-7530654861ca.png)

Zudem ist die Fehlermeldung in English, obwohl der LB auf Deutsch läuft.

**Comment by christianTF** [comment]
Weißt du, welches (normale) Notify das Mailfehler-Notify ausgelöst hat?

**Comment by christianTF** [comment]
17.7.? Hast du das Mailing evt. erst am 18.7. abgedreht, aber die Notification nicht gelöscht?

**Comment by christianTF** [comment]
Seit 1.0.3 (Feb 2018) ist das Notify-Mail sprachspezifisch.
Kannst du mal deine Loxberry-Id checken, wann du den LB installiert hast.

**Comment by mschlenstedt** [comment]
```
loxberry@loxberrydevil:~/config/system $ ls -l loxberryid.cfg
-rw------- 1 loxberry loxberry 128 Feb  7  2018 loxberryid.cfg
loxberry@loxberrydevil:~/config/system $
```

**Comment by mschlenstedt** [comment]
Mmhh, könnte sein, dass ich die Notifys erst am 18.7, abgedreht hatte. Keine Ahnung mehr :-)

**Comment by christianTF** [comment]
Verjährt ;-)
