### ISSUE TITLE
month off by one on ntp config page

### ISSUE THREAD

**Issue by cavoknosig** [mschlenstedt/Loxberry#76]
on the config page
/admin/system/timeserver.cgi?do=form

the month in the current date/time display appears to be off by one month. (06. instead of 07.)

i did check that the ntp server specified (another local raspberry pi) has the correct date/time.

also, an ssh login to loxberry and command "date" does show the correct date/time. 

awesome project, by the way!!! looking forward to possibly contributing as well!

**Comment by Woersty** [comment]
I've changed the whole page. Please try with the next version. Put a note here if still wrong. (Maybe due to localization)

**Comment by mschlenstedt** [comment]
Closed. Please make a new issue if it is still in the next version.

Thanks,
Michael
