### ISSUE TITLE
/tmp ist nur 200 MB

### ISSUE THREAD

**Issue by andweber** [mschlenstedt/Loxberry#761]
im LoxBerry Image ist das tmp Laufwerk "nur" 200 MB. Mein Plugin benötigt scheinbar mehr als 200 MB zur Installation. Ist es möglich bei Gelegenheit das tmp mal etwas zu vergrößern, z.B. 400 MB.

**Comment by christianTF** [comment]
In 1.2.5 wird das tmpfs-Layout überarbeitet, dann sollte das passen.

@mschlenstedt Wäre zu überlegen, die Plugin-Installation überhaupt von tmpfs auf SD zu verlagern. Das ist in Bezug auf Schreibzugriffe ja eher selten.

**Comment by christianTF** [comment]
@andweber Geht's um Kalliope? Wie groß ist da das ZIP?
EDIT: Kalliope ist nur 200 kB groß - was genau passiert?

**Comment by christianTF** [comment]
Ok, lt. Code deines Plugins legst du einen Cache von WAV-Dateien auf /tmp an.

Wenn dieser Cache persistent ist, lege in besser ins data-Verzeichnis. 
Auch wenn wir tmpfs in 1.2.5 zusammenlegen (statt einzelner kleiner tmpfs-Laufwerke), ist das nur eine Frage der Zeit, dass die RAM-Disk mit WAV-Dateien wieder voll ist.

https://github.com/andweber/loxberry-plugin-kalliope/blob/75fec857dfedbddbc4d6d1636b2a7a91bee135bc/config/de_settings.yml#L59
```
# where we store generated audio files from TTS engine to reuse them
--
59 | cache_path: "/tmp/kalliope_tts_cache"
```

Das Plugin-Setup bricht ab, weil auf /tmp weniger als $pluginsize+10% Platz frei ist - dein /tmp ist also komplett voll.

**Comment by mschlenstedt** [comment]
Bitte nichts persistent in /tmp speichern. tmp ist tmp :-) Zudem ist alles nach einem Reboot weg.

Bitte in ~/data ein tmp-Verzeichnis anlegen und dort speichern. Oder besser noch die neuen Storage-Funktionen nutzen und dem User erlauben, auch ein tmp-Verzeichnis auf einem USB-Datenträger anzulegen. Als Fallback wird dann ~/data genommen, falls USB nicht erreichbar ist. So habe ich das im CamStream4Lox umgesetzt: https://www.loxwiki.eu/display/LOXBERRY/CamStream4Lox

tmp wird mit der nächsten LoxBerry-Version größer, aber als permanenter Cache taugt das nicht. Früher oder später sind auch 500MB voll...

**Comment by andweber** [comment]
Im Prinzip ging es "nur" um die Installation des Plugins. Zip und Kalliope sind selbst nicht groß, allerdings baue ich während der Installation die Abhängigkeiten von Kalliope life - und dies scheint derzeit knapp mehr als 200 MB zu belegen. Nach der erfolgreichen Installtion schrumpft das /tmp wieder auf weniger KB.
Das hat mit dem Plugin cache /tmp/kalliope_tts_cache noch nicht zu tun. 

Für den zweiten Hinweis vielen Dank - es ist richtig. Es ist nicht so klug den plugin cache auf /tmp zu lassen. Im ersten Schritt wollte ich es in den RAM legen - um die SD-Karte zu schonen. Ich schaue mir mal die Storage Funktion und CAMStream an.

**Comment by christianTF** [comment]
Hast du die Möglichkeit, dieses Aufbauen zb in $lbpdatadir durchzuführen? Dann passiert das zwar auf der SD, aber dafür funktioniert es mit allen LB1.x-Versionen.

Die Anpassung der tmpfs‘ wird erst mit 1.2.5 kommen, das dauert aber noch, weil diese Anpassung/Konsolidierung der RAM-Disks wirklich gut getestet sein will, bevor wir das „live“ schalten.
Es ist auch noch gar nicht klar, wie wir das genau machen.

**Comment by andweber** [comment]
ja, habe ich jetzt entsprechend angepasst. Danke für die Hinweise.

**Comment by christianTF** [comment]
Dann schließe ich das ab. lg, Christian
