### ISSUE TITLE
plugininstall.pl im Image ersetzen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#765]
Damit darin die Prüfung auf die LoxBerry-Mindestversion funktioniert.
Die Leute updaten nicht, selbst nach einer Neuinstallation...

Plugins werfen dann Fehler, weil die entsprechenden Funktionen aus den neuen Versionen fehlen.

Die korrigierte LBMIN/LBMAX-Funktion kam leider erst mit 1.2.x und fehlt in 1.2.0.

**Comment by mschlenstedt** [comment]
Erledigt mit Image 1.2.0c
