### ISSUE TITLE
backup failure: unable to fetch firmware version

### ISSUE THREAD

**Issue by cavoknosig** [mschlenstedt/Loxberry#77]
the backup plugin only reaches the following point:

2016-07-26 23:30:09 Starting Backup with Script ./bin/createmsbackup.pl Version 0.0.4
2016-07-26 23:30:09 Starting Backup for Miniserver 
2016-07-26 23:30:10 ERROR: Unable to fetch Firmware Version from Miniserver . Giving up.

the basic url "http://user:pass@miniserverip:miniserverport/dev/cfg/version" 
does produce the expected result.
i use a non-standard port "88" and a fixed IP. also, admin-username and password are not particularly fancy in regards to special characters.

**Comment by Woersty** [comment]
There were some issues. For example the variable name had a typo - miniserverpport instead of miniserverport ...
I've created a version 0.0.8 today. Please try it. As soon as pulled by Michael.
