### ISSUE TITLE
loxberryinit.sh im Image ersetzen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#770]
Damit alle frisch installierte Images ein AutoUpdate durchführen. Zusätzlich die Datei /boot/do_lbupdate anlegen.

**Comment by mschlenstedt** [comment]
Erledigt mit Image 1.2.0c

**Comment by christianTF** [comment]
Welcher Stand der loxberryinit.sh ist das? 
In 1.2.4.5 ist das Hin- und Her-Kopieren der Logdb hineingekommen (inkl. Log.pm Änderung des Pfades).
In 1.2.5 hat sich dann der Pfad der Logdb beim Hinundher-Kopieren geändert.

Ich hoffe, das macht bei LB < 1.2.4 keine Probleme.
