### ISSUE TITLE
Timserver-Live-Uhr stimmt nicht

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#79]
Timserver-Live-Uhr stimmt nicht

**Comment by mschlenstedt** [comment]
Liegt anscheinend am Javascript-Code. Ich konnte das aber bei mir nicht reproduzieren. Eventuell Browser-abhängig?

**Comment by Woersty** [comment]
Kann es auch nicht mehr reproduzieren. Nach Refesh war's ok.
