### ISSUE TITLE
Logging SDK: Log-Events sollen regelmäßig prüfen, ob sich der Loglevel in der Plugin-DB geändert hat

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#795]
Hier ist auch zu berücksichtigen:
- Wurde im Konstruktor ein fester Loglevel mitgegeben?
- Wurde über $log->loglevel(0...7) vom Entwickler der Loglevel angepasst.
In diesen Situationen darf das nicht mehr aus der DB gelesen werden.

**Comment by Woersty** [comment]
https://github.com/mschlenstedt/Loxberry/issues/835
