### ISSUE TITLE
Update to v1.2.5.1 fails

### ISSUE THREAD

**Issue by loxatsonnenberg** [mschlenstedt/Loxberry#798]
got error during update to latest version:

 CRITICAL: LoxBerry Updatecheck exited or terminated with an error. Errorcode: 2
 ERROR: LoxBerry Updatecheck exited or terminated with an error. Errorcode: 2. Please see the Update Check Logfile.
 INFO: JSON: {"release_version":"v1.2.5.1","info":"Neue Version gefunden.","release_body":"See the What's New document in https://www.loxwiki.eu/x/84BYAg","error":"LoxBerry Updatecheck exited or terminated with an error. Errorcode: 2. Please see the Update Check Logfile.","releasetype":"release","release_name":"V1.2.5 Feature and stability release","published_at":"2018-10-28T13:32:12Z","logfile":"/opt/loxberry/log/system_tmpfs/loxberryupdate/updatecheck.log","release_zipurl":"https://api.github.com/repos/mschlenstedt/Loxberry/zipball/1.2.5.1","release_new":1}
[updatecheck.log](https://github.com/mschlenstedt/Loxberry/files/2524260/updatecheck.log)

any idea?

**Comment by loxatsonnenberg** [comment]
Error seems similar to that one:
https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/157948-loxberry-updatecheck-exited-or-terminated-with-an-error

Maybe you can integrate an SD-Card check before update.
I will try a new SD-Card and provide feedback.

**Comment by loxatsonnenberg** [comment]
update was successful after changing the SD-Card with latest LoxBerry Backup.
Backup was also not running since three days.

It seems that SD-Card got corrupted earlier and I was not able to detect this earlier.

**Comment by christianTF** [comment]
It was a pleasure watching you, helping yourself.

Currently we do not plan to do more stuff during the update procedure (it is already quite complicated).
LoxBerry does an fsck every 10th reboot.

Thankfully, the backup worked!
