### ISSUE TITLE
System.pm: Bestimmung von $lbpplugindir ist buggy

### ISSUE THREAD

**Issue by jelmd** [mschlenstedt/Loxberry#799]
Die Bestimmung der Variable **lbpplugindir** ist fehlerhaft, da der verwendete Algorithmus davon ausgeht, daß der absolute Pfad zum ausgeführten Script immer das Prefix `$lbhomedir` hat. Das ist aber z.B. nicht der Fall, wenn das Script z.B. via symlink  nach `/tmp/myscript` in `$lbhomedir/*/plugins/$pname/` eingebettet ist.

Um halbwegs korrekt den Pluginnamen und damit `$lbpplugindir` abzuleiten, sollte zuerst $ENV{SCRIPT_FILENAME}) bzw. $0 (möglicher Weise in kanonischer alias normalisierter Form) und erst als letztes der vollständig aufgelöste Pfad a.k.a. Cwd::abs_path($ENV{SCRIPT_FILENAME}) bzw. Cwd::abs_path($0) verwendet werden.

**Comment by christianTF** [comment]
Kannst du ein konkretes Beispiel mit Pfaden nennen, wie das Script dann als Symlink heißt, und wie das Original?

Aus /tmp/myscript als SymLink weiß ich jetzt nicht, wie man dabei erkennen könnte, dass das in Wahrheit /opt/loxberry/bin/plugins/topplugin/myscript.pl ist.
Deswegen die Frage nach einem konkreten Beispiel.

lg, Christian

**Comment by christianTF** [comment]
Passt schon, hab's ausprobiert - brauch kein Beispiel mehr.

File erstellen, z.B. `/opt/loxberry/bin/plugins/squeezelite/test.pl`
```perl 
#!/usr/bin/perl
use Cwd;
print "ENV: " . $ENV{SCRIPT_FILENAME} . "\n";
print "\$0: " . $0 . "\n";
print "abs_path(\$0): " . Cwd::abs_path($0) . "\n";
```

` ln -s /opt/loxberry/bin/plugins/squeezelite/test.pl myscript.pl`

`perl /tmp/myscript.pl`

Output:
```
ENV:
$0: /tmp/myscript.pl
abs_path($0): /opt/loxberry/bin/plugins/squeezelite/test.pl
```

ENV dürfte dann per Web auch gesetzt sein, müsste man auch noch testen mit abs_path

**Comment by christianTF** [comment]
PS: Ich brauche *doch* ein Beispiel, ich versteh den Unterschied zum bestehenden Code nicht.

https://github.com/mschlenstedt/Loxberry/blob/442be562808f70ac14a43661f8dbd82e88503c97/libs/perllib/LoxBerry/System.pm#L160

Was genau würdest du hier ändern?

**Comment by jelmd** [comment]
Z.B. mal das Repo unter /tmp auschecken und dann symlinken. Ich mach's mit 'nem [kleinen script](https://github.com/jelmd/lbp.cam-connect/blob/master/etc/hotlink.sh), aber manuell für 'nen kleinen Test ist's auch kein Problem. Z.B.:
```
rm -f /opt/loxberry/bin/plugins/squeezelite/test.pl
ln -s /tmp/squeezelite/bin/test.pl /opt/loxberry/bin/plugins/squeezelite/test.pl
```
und dann einfach mal `/opt/loxberry/bin/plugins/squeezelite/test.pl` starten.

**Comment by jelmd** [comment]
BTW: Hab mal 'ne Alternative geschrieben, womit es funktioniert:
```
sub canonical_path {
    my $path = shift;
    my @ret = ();
    $path .= '/' if $path =~ /[.\/]$/;
    for my $tok (split(/\/+/, $path . '-')) {
        next if $tok eq '.';
        if ($tok eq '..') {
            pop @ret;
            next;
        }
        push @ret, $tok if $tok;
    }
    '/' . substr(join('/', @ret), 0, -1)
}

sub get_plugindir {
    use Cwd 'abs_path';
    my $use_abs = shift;
    my @p = ();
    my $s, my $t, my $i;

    $s = $ENV{SCRIPT_FILENAME}; $t = $0;
    if ($s) {
        $s = $use_abs ? Cwd::abs_path($s) : canonical_path($s);
    } else {
        $s = '/';
    }
    if ($s != $t ) {
        $t = $use_abs ? Cwd::abs_path($t) : canonical_path($t);
    } else {
        $t = '/';
    }
    return '' if ($s eq '/' && $t eq '/');

    push @p, $s unless ($s eq '/');
    push @p, $t unless ($t eq '/' || $s eq $t);

    my %parents = (templates => 1, log => 2, data => 3, config => 4, bin => 5);
    foreach $t (@p) {
        print STDERR "Checking '$t' for '/plugins/' ...\n" if ($DEBUG);
        my @pc = split('/', $t);
        pop @pc;
        foreach $i (1..$#pc-1) {
            next unless ($pc[$i] eq 'plugins');
            if ($i >= 2 && $pc[$i-2] eq 'webfrontend') {
                return $pc[$i+1];
            } elsif ($parents{$pc[$i-1]}) {
                return $pc[$i+1];
            } elsif ($i >= 2 && $pc[$i-2] eq 'system'
                && $pc[$i-1] eq 'daemon')
            {
                return $pc[$i+1];
            }
        }
    }
    return ($use_abs) ? '' : get_plugindir(1);
}
our $lbpplugindir = get_plugindir();
```

**Comment by mschlenstedt** [comment]
Repo nach /tmp auschecken? Wieso?
