### ISSUE TITLE
LoxBerry SSH-Login über Keys in den Wizard mit einbauen

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#8]
Ich fänd es Klasse, wenn man für den LoxBerry das SSH-Login auch
über Keys ermöglichen könne und das in den Wizard mit einbauen würde.
Manuell geht es natürlich, aber per Webinterface ist das schicker und DAU sicherer.

**Comment by mschlenstedt** [comment]
Oder Funktionalität als "SSH Plugin" nachrüsten?

**Comment by Woersty** [comment]
Ja, momentan aber zu busy um mich darum zu kümmern.
Falls jemand will bitte, ich melde mich bevor ich anfange damit nicht zwei Leute daran arbeiten.
In absehbarer Zeit wird das aber nix.

**Comment by mschlenstedt** [comment]
Ich persönlich finde es jetzt auch nicht ganz soooo wichtig: Die erfahrenen User (die das vermutlich zu 99% nutzen) wissen wie sie es auf der Konsole aktivieren, alle anderen brauchen es vermutlich nicht/nie.

Der einzigste Vorteil wäre der Sicherheitsgewinn, falls der LoxBerry von Extern erreichbar ist. Von daher finde ich es als Plugin ausreichend.

**Comment by mschlenstedt** [comment]
siehe http://www.loxwiki.eu:80/x/pIG4
