### ISSUE TITLE
Sethosts: Probleme mit mehreren IP‘s

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#803]
Müsste man mal ausprobieren:

https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/174359-update-problem-auf-v1-2-5-1-mit-pi-hole-auf-loxberry?p=174681#post174681

Kann alle VPN‘s usw betreffen.

**Comment by mschlenstedt** [comment]
Das Problem mit apt? Das scheint eher so zu sein, dass er über die apt-Nachfrage (Überschreiben des Config-Files) stolpert. Verstehe ich nur nicht, da wir "-y" mit übergeben.

**Comment by mschlenstedt** [comment]
Ah, du meinst eher das hier:

```Ich hab es dann nochmal aufgerufen und mit N bestätigt. Danach liefen alle Updates mit der Loxberry Oberfläche durch.
Problem ist (bzw. war) allerdings Euer neues Startupscript für die Interfaces. Wenn mehr als eine IP Adresse vorhanden ist, dann funktioniert es nicht nicht mehr sauber und beim Start muss man 5min warten, da das Script hängt.

ich hab jetzt meine Config wieder geändert. 
1. Zweite IP Adresse wieder entfernt (eth0:0)
2. Pi-Hole auf Port 81 verschoben in der nginx Config (/etc/nginx/sites-available/default)

Danach lief alles sauber durch. Pi-hole läuft jetzt auf Port 81 und Loxberry auf Port 80.

Mal schauen, was das nächste Update bringt. :-)```

**Comment by mschlenstedt** [comment]
Sowas will ich nicht supporten. Da kommt keiner mehr mit. Wer manuell am System herumschraubt, muss es auch manuell reparieren, wenn es kaputt ist.

Der LoxBerry ist ein Out of the Box System: Einstecken, Plugin installieren, läuft. Für was anderes war er nie gedacht.

**Comment by svethi** [comment]
Das kommt auch eher nicht vom Script sondern vom dnsmasq. Dieses 5 Minuten Delay hatte ich bevor geprüft wurde ob der dnsmasq läuft und einfach stumpf der dnsmasq einfach restartet wurde

**Comment by svethi** [comment]
Ich habe dieses Zenario bei mir mal nachgespielt und eine weitere IP auf das iface gebunden. Ich hatte da keinerlei delay. Mal abgesehen davon, dass das Script so dennoch nicht korrekt arbeitet, da in den Abfragen pro IP auf dem Gateway Interface eine Zeile mit der IP zurück kommt und damit falsche Zeilen in die /etc/hosts eingetragen werden.

**Comment by Woersty** [comment]
Ähm was soll ich tun? @svethi
