### ISSUE TITLE
Line breaks incorrectly parsed if logformat is text

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#808]
Die \\n aus den Sprachdateien landen als \n im Logtext.

Beispiele: 
http://loxberrydev/admin/system/tools/logfile.cgi?logfile=invalid&header=html&format=txt
oder
http://loxberrydev/admin/system/tools/logfile.cgi?logfile=invalid

Aber ok mit 
http://loxberrydev/admin/system/tools/logfile.cgi?logfile=invalid&header=html&format=template

**Comment by gmkey** [comment]
On my machine, (MacBook Air), all the configuration files for e.g. DNSmasq plugin are displayed as single line, with safari (12.0.1) and Firefox (63.0.3). (I've noticed this behaviour earlier but didn't write down the versions).

in firefox the errors are:
Source map error: request failed with status 404
Resource URL: http:///system/scripts/jquery/jquery.mobile-1.4.5.min.js
Source Map URL: jquery.mobile-1.4.5.min.map
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://c47372a4-4b4f-1045-9b1d-54ad39bb11fa/browser-polyfill.min.js
Source Map URL: browser-polyfill.min.js.map

in safari the errors are:
Failed to load resource: the server responded with a status of 404 (Not Found) http:///system/scripts/jquery/jquery.mobile-1.4.5.min.map

**Comment by gmkey** [comment]
it turns out to be an issue with LoxBerry-Plugin-DNSmasq
I think this issue can be closed

**Comment by Woersty** [comment]
Fixed in https://github.com/Woersty/LoxBerry-Plugin-DNSmasq/issues/5

**Comment by Woersty** [comment]
And in https://github.com/mschlenstedt/Loxberry/commit/94291f12bc2e10761c7ce38a854d28e0747a6324
