### ISSUE TITLE
Diskussion aktuelle Systemzeit

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#81]
Hallo Wörsty!

ich möchte das Anzeigen der aktuellen Systemzeit sowohl im Hauptmenü als auch auf der Konfig-Seite "Timeserver" nochmal zur Diskussion stellen:
1. Es scheint bei einigen Nutzern doch Probleme zu geben, dass die korrekte Zeit nicht angezeigt wird. Eventuell ist das ein Browserproblem, vielleicht hat es auch irgendetwas mit Caching zu tun, oder es ist sonst ein Fehler. Mir ist es bisher nicht gelungen, das zu repoduzieren.
2. Die Anzeige bei der Timeserver-Konfig sieht ohne Frage richtig cool aus, aber nimmt viel Platz weg und die Animationen haben meiner Meinung auch (natürlich neben der schönen Optik) nicht so wirklich einen Mehrwert...
3. Das Gleiche gilt eigentlich für die Uhr im Hauptmenü. Hier habe zudem ich das Problem, dass die Uhr einfach stehen bleibt, wenn ich aus einem Untermenü zurückgespringe. Auch hier vermutlich auf Grund eines Cache-Problemes o.ä. Auch hier glaube ich ist der Mehrwert eher gering: Ich gehe doch später eigentlich nur auf die Config-Seite des LoxBerrys wenn ich irgendetwas einrichten will. Ansonsten brauche ich das nicht.

Frage: Macht es vielleicht Sinn diese Live-Anzeigen wieder rauszuschmeissen? Ich weiß, es war viel Arbeit, aber wenn es nicht sauber funktioniert macht es glaube ich mehr Ärger als es Sinn macht. Und nur für ein Gimmick dort viele Ressourcen reinzustecken halte ich für nicht sinnvoll - zumindestens solange es noch wichtigere Baustellen beim LoxBerry gibt...

Deine Meinung?

**Comment by Woersty** [comment]
Irgendwie muss ich dir da zustimmen. Das mit dem Problem der falschen Uhrzeit konnte ich manchmal nachvollziehen, wenn mein Rechner länger im StandbyModus war. Grundsätzlich habe ich kein Problem damit, das wieder rauszuschmeißen. Habe es eh für was anderes gebraucht und hier "mitbenutzt". Und Spaß hat es auch gemacht. Aber die Uhr bleibt bei mir nicht stehen. Weder auf iPad Air noch im Chrome, Edge oder IE Browser unter Windows 10. Was benutzt du? Die im Hauptmenü würde ich gern retten. Finde sie voll schick. Was genau machst du, dass sie stehen bleibt? 

Gruß

**Comment by mschlenstedt** [comment]
Ok, ich bereinige das Timeserver Template dann mal. Ist für mich ok die Uhr im Hauptmenü zu lassen. Ich nutze Chrome unter Win10. Ich muss mal genau testen, was ich da wie gemacht habe. Ich melde mich dazu.

**Comment by mschlenstedt** [comment]
Erledigt.
