### ISSUE TITLE
Fehler in der .htaccess schrottet den Apachen

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#814]
Wie der Titel schon sagt, würden Änderungen an der .htaccess durchgeführt, die den Apachen zum Absturz bringen und damit der Loxberry nach dem Update unnutzbar ist.

**Comment by christianTF** [comment]
@jelmd Das betrifft dich!

**Comment by christianTF** [comment]
Variable ${LB_BASEDIR} existiert nicht auf LoxBerrys.
Es gibt eine bestehende Umgebungsvariable ${LBHOMEDIR}, die hätte verwendet werden sollen.

**Comment by jelmd** [comment]
Ja - hatte ich als [Kommentar](https://github.com/mschlenstedt/Loxberry/commit/03a3556e9e88de661689e3d10afe7b5ffb3f66eb#commitcomment-31289043) an den commit drangehängt. Ist ein Define innerhalb meiner virtualhost.conf. Könnte man also auch via `httpd -DLB_BASEDIR=${LBHOMEDIR}` setzen.

**Comment by svethi** [comment]
Leider bringt es nichts wenn das in Deiner virtualhost.conf steht und alle anderen LB‘s damit nicht mehr funktionieren. Warum soll man denn für den gleichen Wert eine zusätzliche Variable einführen. Da steigt doch irgendwann keiner mehr durch

**Comment by jelmd** [comment]
Bitte die Kirche im Dorf lassen. Denke, alle die den "heißen"/cutting-edge alias development branch nutzen, sind Profi genug, auch mal durchgeschlüpfte Probleme fix in den Griff zu bekommen, ohne groß in Panik auszubrechen. Im commit Kommentar hatte ich ja bereits darauf hingewiesen und zum besseren Verständnis mein diesbzgl. Setup angegeben. Heißt doch aber nicht, daß man das so machen muß ;-)

BTW: Wenn der Apache httpd wegen sowas abstürzt, dann müßte man sich das mal genauer anschauen. Eigentlich sollte der das einfach nur im Logfile anmeckern und den Zugriff auf das entsprechende Verzeichnis und subs verweigern und normal weitermachen ...

**Comment by svethi** [comment]
Okay, wir werden das Apache.org in die issues schreiben dass der Webserver doch bitte auch bei defekter Config weiterarbeiten sollte. ;-)
Direkt abgestürzt ist er ja nicht er bringt einen 500 und da die .htaccess im Webroot liegt geht in dem Fall gar nichts mehr.

**Comment by jelmd** [comment]
Verhält sich also wie erwartet - ist doch alles gut :)

**Comment by christianTF** [comment]
Sagen wir einfach: 
Der LoxBerry muss nach einem Commit soweit verfügbar bleiben, dass jeder User per WebIf noch LoxBerry Update ausführen kann.
JEDER User hat im WebIf die Möglichkeit, auf den aktuellen Master upzudaten, und den darauf folgenden Support-Marathon macht der „Verbrecher“! Der Vertrauensverlust in die Updates lässt sich sowieso nicht mehr wettmachen, wenn das passiert.

Jens: Deswegen musst du im Forum präsent sein. Wenn du etwas eincheckst, muss jemand erreichbar sein, der weiß, was Sache ist.

**Comment by christianTF** [comment]
PS: Jens, hast du schon einen Forums-Account? Dann ändern wir mal das htaccess-Checkin, damit's funktioniert. Einen echten Raspberry mit LoxBerry solltest du dir jedenfalls besorgen zum Testen.

**Comment by jelmd** [comment]
Ja, offensichtlich geht das Einloggen auch ohne E-Mail-Bestätigung: ist ebenfalls jelmd .
Loxberry zum Spielen hab ich in xxx km über 'nen 3B+. Tunneln nervt nur ein bisl, wenn 1&1 "ständig" die Verbindung kappt - da geht das lokal auf dem Laptop viel flotter vorwärts ... ;-)

**Comment by mschlenstedt** [comment]
Prima! Das wird für den Anfang sicherlich gehen. Super wäre es, wenn Du doch mal ein Handy mit WhatsApp hast :-) Wir haben das alle auf unseren PCs installiert und nutzen das als Chat. Wir diskutieren dann meistens erst einmal Änderungen, die wir machen wollen bevor jemand wirklich loslegt. Dann klärt sich vioeles schon im Vorfeld.

Herzlich willkommen! :-)

**Comment by mschlenstedt** [comment]
Ab jetzt dann im Forum.
