### ISSUE TITLE
Filemanager Widget - Fußzeile

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#818]
Der Filemanager hat keine Fußzeile

**Comment by Woersty** [comment]
War eigentlich Absicht und schon immer so.

**Comment by mschlenstedt** [comment]
Naja, war eigentlich keine Absicht. Ich hatte es damals nur nicht hinbekommen und dann keine Lust mehr zu suchen :-) Der Filemanager ist eine eingebundene "Fremdsoftware", die ich nur für den LoxBerry etwas "verbogen" habe.

Das gleiche gilt für das #859

**Comment by Woersty** [comment]
Bekomme ich nicht hin. Die CSS beißen sich. Ich bin für schließen. iFrame ist nicht schön.

**Comment by mschlenstedt** [comment]
Wont Fix.
