### ISSUE TITLE
LBUpdate: Im UI anzeigen, dass gerade ein Update läuft

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#825]
Es gab jetzt glaub ich drei Tickets in den letzten Tagen, dass Leute kein manuelles LBUpdate ausführen konnten, weil jenes, das bei der Erstinstallation automatisch ausgeführt wird, noch läuft.

Beim Aufruf der AJAX-Aktion zum Prüfen auf Updates soll die Routine ein lock probieren, und wenn eines besteht, sofort zurückgeben, dass gerade ein Update läuft.

Außerdem sollten wir #641 umsetzen, damit sich der Power-Button automatisch aktualisiert.

**Comment by Woersty** [comment]
Update in Fusszeile via Ajax anzeigen

**Comment by Woersty** [comment]
Kann das so bleiben und der Bug geschlossen werden?
