### ISSUE TITLE
Software error: smtppass after update to v1.2.5.5

### ISSUE THREAD

**Issue by SmartBulb67** [mschlenstedt/Loxberry#826]
After updating to the last version of LoxBerry (v1.2.5.5) the following error message appears when opening the "Mailserver" configuration dialog:

Software error: HTML::Template::param() : attempt to set parameter 'smtppass' with an array ref - parameter is not a TMPL_LOOP! at /opt/loxberry/webfrontend/htmlauth/system/mailserver.cgi line 126.  
Depending of what you have done, report this error to the plugin developer or the LoxBerry-Core team.
Further information you may find in the error logs.

The password in the "mail.cfg" file contains a blank ( ) and a comma (,), but is not surrounded by quotes (").
Manually adding the quotes around the password resolves the error. But I had already done this before the update and had to redo it afterwards.

Please have a closer look at the update process in regards to the mail.cfg file.

Many thanks
Daniel

**Comment by christianTF** [comment]
https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/174693-loxberry-fehler-smtppass-bei-einstellung-für-mail-server?p=177874#post177874

**Comment by christianTF** [comment]
Reproduced the behaviour - changing the Notification settings (on the bottom of the Mailserver page) resets the quotation, leading to the initial problem (Error from HTML::Template 'is not TMPL_LOOP').

Will be addressed in LB1.4 by changing the mail.cfg to mail.json. Settings will be migrated.

**Comment by christianTF** [comment]
Fixed with #834 in LoxBerry V1.4.
