### ISSUE TITLE
Admin: Passwörter ändern Fehler (Sonderzeichen)

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#828]
https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/178425-fehler-nach-passwort%C3%A4nderung-login-%C3%BCber-gui-nicht-m%C3%B6glich

Verwendete Sonderzeichen waren:
& # }

Müsste man durchprobieren.

**Comment by Woersty** [comment]
@christianTF @mschlenstedt @svethi  könnt ihr das mal testen?
Bei mir hat es gut geklappt.
Bevor wir das übernehmen sollte das nicht nur durch mich getestet sein...

**Comment by christianTF** [comment]
Das mit den Sonderzeichen scheint bei mir zu funktionieren.

Die vielen Farben lenken imho ein bisschen davon ab, dass man sich die Zugangsdaten herunterladen und speichern soll...?

![image](https://user-images.githubusercontent.com/14220265/49702725-07715b80-fbfc-11e8-841f-e5e61490ee7c.png)

**Comment by Woersty** [comment]
Farben habe ich reduziert auf nur gelb außer den Kasten um Textfile herunterladen.
Kann der Issue zu?

**Comment by Woersty** [comment]
1) Soll der Fehler-Text lieber außerhalb sein?
2) Soll "Die folgenden..." wieder rein? (wird derzeit nur angezeigt, wenn kein Fehler auftrat)
![zwischenstand](https://user-images.githubusercontent.com/20454116/49898760-253bfc00-fe5a-11e8-964f-e8e460e69f88.jpg)

**Comment by christianTF** [comment]
Gefällt mir besser, hab heut schon probiert.
Ob drin oder draußen ... geht beides

**Comment by christianTF** [comment]
Das ist eigentlich erledigt, oder?

**Comment by Woersty** [comment]
Ja. Konnte bei meinen Tests kein Problem feststellen.
