### ISSUE TITLE
LoxBerry::IO::msudp_send_mem: Umlaute

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#829]
Die Funktion LoxBerry::IO::msudp_send_mem überträgt Umlaute nicht korrekt. Aus "ä" wird z. B. \xC3\xA4

LoxBerry::IO::mshttp_send_mem funktioniert korrekt.

**Comment by christianTF** [comment]
Loxone-UDP scheint mit UTF-8 selbst nicht zurecht zu kommen.

![image](https://user-images.githubusercontent.com/14220265/49342647-5c422e80-f65e-11e8-9e5f-6ae58ba56db6.png)

Aktuell mal: wontfix.

Wenn es ein Beispiel gibt, wo das UDP-Senden von Umlauten funktioniert, dann schau ich mir das nochmal an.
