### ISSUE TITLE
plugin Deinstallation unvollständig

### ISSUE THREAD

**Issue by jelmd** [mschlenstedt/Loxberry#830]
Die De-Installation eines plugins ist nicht ganz vollständig: `log/system/plugininstall/${plugin}.log` wird nicht gelöscht und `data/system/notifications_sqlite.dat` scheint auch nicht ordentlich bereinigt zu werden => führt z.B. zu merkwürdigen Effekten bzgl. update infos.

**Comment by christianTF** [comment]
@mschlenstedt Das mit dem Plugin-Log ist deine Baustelle,

Die Notifications muss ich mir anschauen. Die werden wahrscheinlich wirklich bisher nicht gelöscht, und da das Notify für das Handling und auch das Merken der bereits gemeldeten Versionen zuständig ist, wird eine Neuinstallation des gleichen Plugins da sicher einen Wirbel hineinbringen.

**Comment by christianTF** [comment]
@jelmd FYI Mit `http://loxberry/admin/system/tools/showrawnotifications.cgi` kannst du dir den Datenbankinhalt der Notification-DB anschauen.

**Comment by jelmd** [comment]
Ahh danke! Hatte es mir direkt mit sqlite3 angesehen (nachdem ich die `sqlite`-Hürde => Unable to open database "data/system/notifications_sqlite.dat": file is encrypted or is not a database <= genommen hatte ;-)).

**Comment by christianTF** [comment]
Was war denn das für eine Hürde? Hast du sie erst mal geschrottet? 😆
Oder war sie einfach so kaputt?

**Comment by christianTF** [comment]
PS: Hast du dem Christkind schon eine Notification geschickt zwecks des WhatsApp-Telefons? 😉

**Comment by jelmd** [comment]
Hürde: Die sinnlose Fehlermeldung bzgl. `Unable to open ...` - hatte nach ein bisl Grübeln dann halt die Idee, daß `sqlite` nicht wie gewohnt verlinkt ist und tatsächlich 'ne bärtige Version startet. Mit `sqlite3` ging's dann halt (hab das sqlite package gleich weggeflext ;-))

PS: Joh - Wunschzettel ist raus. Mal sehen, ob da was bei rumkommt :)

**Comment by jelmd** [comment]
BTW: `log/system_tmpfs/logs_sqlite.dat` scheint auch Relikte aufzuheben. Da tmpfs impliziert, dass die bei 'nem reboot wieder wegfliegt, vermute ich, dass die alten logs bei Bedarf gescannt und dort wieder reingepumpt werden, oder? Dann wär's bzgl. Logmanager ja nur ein Folgefehler ...

**Comment by christianTF** [comment]
Die logs_sqlite wird bei Shutdown und Boot von tmpfs -> SD und umgekehrt kopiert, sowie regelmäßig per cron auf die SD gesichert.

Der stündliche Maintenance-Job löscht aus der DB alle Einträge, deren Logfiles nicht mehr existieren.

Relikte überstehen somit eigentlich nur für eine Stunde - hast du was Älteres gefunden, wo die Datei nicht mehr existiert?

**Comment by jelmd** [comment]
Aha. Das erklärt das Problem: Das logfile hat den Namen behalten, aber der PLUGIN.NAME (und TITLE) hat sich geändert. Deshalb erscheinen selbst nach einer Deinstallation+Neuinstallation die logs unter altem alias ghost PLUGIN.TITLE (sucks, weil der alte auf 25 Zeichen + '...' durch plugininstall.pl beschnitten, umgemogelt wurde - wieso eigentlich?) und gruppiert nach alten alias ghost PLUGIN.NAMEs. Sehr irritierend ...

**Comment by christianTF** [comment]
Die Logdb-Einträge fliegen nach 30 Tagen raus.

Das Ändern von Name und Title fällt für mich in die Kategorie eines Entwickler-Usecases während der Plugin-Testphase und ist mir - salopp gesagt - gerade egal 😐 

Das 25-Zeichen-Limit steht so in der Plugin.cfg-Spezifikation. Irgendeinen Hintergedanken wird Michael gehabt haben (vielleicht einfach, weil das sonst nicht ordentlich darstellbar ist)
Das mit ... hab ich nicht mal gewusst - hab mich immer an die Spec gehalten 🤗

**Comment by christianTF** [comment]
Das mit dem Cleanup der Logdb und der Notifications beim Uninstall, wäre das was für dich?
Es gibt dafür - soweit ich mich erinnere - schon fertige Funktionen (die meisten intern, also nicht dokumentiert im SDK) zum Löschen von Einträgen.
Man müsste schauen, wo das Uninstall passiert, und vor dem tatsächlichen Löschen der Dateien/Ordner die Aufräum-Funktionen aufrufen.

Es wird demnächst ein neues Image geben - da könnte das gleich mitkommen.

Plugininstall ist grundsätzlich Michaels Baustelle, das Notify und LogDb meine Baustelle - wenn du Hilfe brauchst.

lg, Christian

**Comment by jelmd** [comment]
OK, 30 Tage sollte man ertragen können. Rest kann man ja ggf. auch via preinstall script lösen :) .

**Comment by jelmd** [comment]
Ja, ok - werd dann nächste Woche mal versuchen, da komplett durchzusteigen.

**Comment by christianTF** [comment]
Notify und LogDB spielt sich komplett in der Log.pm ab. 
Alle Funktionen, die irgendwas damit machen, rufen Funktionen aus der Log.pm auf. 

Aus meiner Sicht muss in der Log.pm kein neuer Code geschrieben werden, weil es dafür schon High-Level-Funktionen gibt. Die Log.pm selbst müsste also dafür nicht geändert werden, sondern nur die richtigen Funktionen gefunden.

**Comment by mschlenstedt** [comment]
TITLE und NAME sowie Name/EMAIL des Autors dürfen nicht geändert werden -> siehe Wiki https://www.loxwiki.eu/pages/viewpage.action?pageId=23462653#Pluginf%C3%BCrdenLoxberryentwickeln(Version1.x)-plugin.cfgRootverzeichnis-Datei:plugin.cfgRedPflicht. Dann dürfte sowas auch nicht passieren.

Mit den 25 Zeichen: Das war tatsächlich mal ein Darstellungsthema und wird (wenn ich mich recht erinnere) nur bei TITLE angewendet.

**Comment by jelmd** [comment]
Hatte ich überflogen. Bzgl. PLUGIN.NAME leuchtet's mir ein, für alles andere nicht wirklich - gut: FOLDER ist wahrscheinlich ein Relikt aus früheren Zeiten, aber e-mail kann sich schon mal ändern, oder wenn man den Staffelstab weiterreicht - was ja bei SW ab und zu passiert - kann sich auch die komplette AUTHOR-Sektion ändern. Oder man tüftelt jahrelang an 'nem plugin rum, hat irgendwann 'ne eierlegende Wollmichsau und möchte es dann auch entsprechend im Titel kundtun. Da PLUGIN.NAME nicht wirklich sichtbar ist, kann man den ja behalten/daran alles festmachen und alle anderen Parameter mehr oder weniger als Schall und Rauch betrachten, oder?

Zwecks Einzigartigkeit könnte man notfalls auch analog der IANA port registry 'ne Plugin-Registrierung machen, wo jeder sich 'ne offizielle Loxberry Plugin ID (LPID) für jedes seiner plugins besorgen kann. FOLDER könnte man dann optionalisieren und wenn fehlt durch ${PLUGIN.NAME}_${PLUGIN.LPID} ersetzen und hätte den Pfad über alle Instanzen/Installationen auch konstant ...

Bzgl. TITLE-Länge: dann vielleicht auf "empfohlen" abschwächen und den Cutter rausnehmen? Mit den CSS-Möglichkeiten heutzutage sollte man auch sowas in den Griff bekommen (wenn da überhaupt was in den Griff zu bekommen ist), oder?

**Comment by christianTF** [comment]
Ich sehe aktuell kein Problem damit. Braucht dein Plugin-Titel über 25 Zeichen?

Wir haben mal diskutiert, den FOLDER als Unique einzuführen.

Zum Restlichen, da sind wir wieder bei: Kompatibilität, Kompatibilität, Kompatibilität.
Und: Ressourcen, Ressourcen, Ressourcen. Wir machen das ja nicht hauptberuflich...

**Comment by jelmd** [comment]
Brauchte - hab's dann halt umbenannt, wo die anderen Sachen in Folge hochploppten.
Dachte dann, wozu limitieren, wenn's nicht wirklich 'nen Grund dafür gibt - verwende z.B. PLUGIN.TITLE um Redundanzen/Typos zu vermeiden, die Sachen konsistent zu bekommen ...

Rest ist klar - dito :)

**Comment by mschlenstedt** [comment]
Hallo Jens,

es gibt sicherlich viele Wege, die nach Rom führen. Wir haben uns gegen eine Plugin-Registry entschieden, weil wir dann unnötig die Entwicklung neuer Plugins einschränken würden. Und was ist, wenn der Server nicht mehr erreichbar ist? Oder der Serverbetreiber keine Lust mehr hat? Oder sich jemand nicht registrieren möchte? Oder....?

Aktuell ist es so wie in der Beschreibung erklärt. So sichern wir die Einzigartigkeit, da aus NAME/FOLDER und AUTORNAME/EMAIL ein Hash gebildet wird. So ist dieser Hash auch einzigartig, wenn zwei unterschiedliche Autoren aus Versehen den gleichen Pluginnamen wählen (schon passiert).

Wir müssen zudem die Kompatibilität zu alten Plugins sicherstellen. Und wir müssen sicher gehen, dass nach einer Änderung alle LoxBerrys noch laufen. Daher sind Änderungen hier ganz schwierig. Es gibt hier eine ewig lange Diskussion darüber während wir an LoxBerry 1.0 gearbeitet haben. Am Ende haben wir es so gelassen wie es ist und schon seit LoxBerry 0.1 so ist.

Wir werden das nicht ändern. Ich sehe aktuell auch irgendwie keinen Grund darin. Wo ist das Problem, dass wir auf 25 Zeichen beschneiden? Es gilt wie schon bei den letzten Änderungen von Dir: Wir ändern nur etwas, wenn wir es müssen, damit wir die Kompatibilität audrecht erhalten.

**Comment by jelmd** [comment]
Hi Michael,

Der Hash über die Parameter und dessen Verwendung als ID erklärt natürlich das 'do not change'.

Ein Hash bleibt aber auch selbstredend nur ein Hash, d.h. ist auch nicht vor Kollisionen sicher und bringt halt all die genannten Einschränkungen mit sich, die bei Verwendung einer echten ID halt vollkommen überflüssig wären.

Rom: genau. Einschränkung IMHO überhaupt nicht, im Gegenteil: Kann man wie bei den IP ports handeln: wer will, registriert sein plugin (alias erfragt 'ne neue ID) und hat damit 'ne gewisse Sicherheit/Stabilität/Sichtbarkeit. Wem's egal ist, der kann's auch lassen - bekommt dann wie gehabt, was gehashtes z.B. oberhalb von MAXINT. "Mißbrauch" von ID und [jetzigem] Hash kann ohne weiteren "overhead" eh nicht verhindert werden, also brauchen wir's hier auch nicht weiter betrachten.

Bzgl. registry: Das kann ja eine plain/text, handgepflegte CSV-Datei mit den Spalten #ID NAME EMAIL TITLE sein. Mehr nicht! Klassischen Server braucht man dafür nicht, wäre IMHO eh nur kompletter Overhead. Der zu erwartende Traffic/Aufwand fällt nach dem ersten Schwall vermutlich nicht wirklich mehr ins Gewicht (wieviel neue Plugins/Monat?). Die Datei selbst könnte man via privatem Repo auf bitbucket.org (BB) hosten und somit easy via git warten. Auf github könnte man zudem ein public repo anlegen, wo die Liste ohne e-mail Spalte zwecks Sichtbarkeit "hingespiegelt" wird. Also mehr als 5 min wären pro reg-mail wohl nicht nötig. BTW: Auf BB kann man auch Teams (analog github organizations) anlegen, also muß das ganze dann nicht mal an einer einzelnen Person festgemacht werden ...

Bzgl. 25 Zeichen Limit: dadurch geht mit Sicherheit nicht die Welt unter. Ich empfinde es aber halt als eine unnötige Einschränkung/Gängelung, was aus meiner Sicht durchaus Einfluß auf die Akzeptanz haben kann. Will man seine Plugins z.B. '${Produktreihe}: ${produktname}' betiteln, wird's schon ganz schön eng/unbrauchbar. Dann kann man das für die plugin-Seiten selbst umschiffen, indem man wie bei cam-connect z.B. diesen in den templates/lang/language_* definiert, aber Logmanager, Plugin-Verwaltung, etc. zeigen trotzdem was anderes an - lästige Inkonsistenzen und Redundanzen, die man ja nicht wirklich haben will.

Aber wie du schon sagst, muß man ja nicht alles auf einmal oder sofort ändern. Kann man ja auch auf die Wish-List für 2.x setzen ...

**Comment by christianTF** [comment]
Bei uns in der Firma käme jetzt die Frage: 
"Was bringt's dem Benutzer?"
Und schon ist die Diskussion vorbei.

Können wir bitte über was diskutieren, was den Benutzern oder Entwicklern einen echten Mehrwert bringt, statt funktionierende Sachen neu zu erfinden?

Wenn es ein Bug ist, gehört es gefixt. Ist das ein Bug? NEIN. Steht so in der Spezifikation.

PS: Wenn du das mit der Kompatibilität nicht wahrhaben willst: Geh zu hismastersvoice und sag ihm, er muss seine Plugins ändern, weil du das Plugin-Interface neu machst. Dann berichtest du uns, was er dir gesagt hat.

**Comment by christianTF** [comment]
PPS: Wir verstehen nicht, wofür du das brauchst, und solange es nur rein hypothetische Beispiele sind, werden wir das auch nicht verstehen. Es gibt 25 Plugin-Entwicker, und keiner hat jemals darüber ein Wort verloren, also was willst du, womit andere 25 Entwickler klar kommen?

**Comment by jelmd** [comment]
Ehmm, sorry wenn's nervt, konnte diesbzgl. aber nix finden, und da für mich Verbesserung nicht automat.  Inkompatibilität bedeutet, stell ich als Newbie halt ab und zu mal unorthodoxe oder nervige Fragen :(

Anyway, Verbesserung für den Nutzer wie gesagt:
- bessere Sichtbarkeit/Verständlichkeit
- bessere Wiedererkennbarkeit
- Konsistenz
- Kontinuität

Bzgl. Entwickler:
- einfachere Handhabbarkeit, keine "unsauberen workarounds" 
- echte Eindeutigkeit über alle Installationen hinweg
- weniger Limitierungen
- Freiheit, auch mal seine e-mail Adresse ändern zu können
- Freiheit, Titel dem Entwicklungsstand des Plugins anzupassen
- Konsistenz
- Kontinuität

Wie gesagt, ich hab das 25Z Problem durch Kürzung umschifft, d.h. aber nicht, das es später nicht wieder mal present wird, oder andere neue Entwickler sich dieselben Fragen stellen (Keine Ahnung, ob's bei den ganzen App Stores, die es so gibt, ähnliche Restriktionen gibt ...).

**Comment by christianTF** [comment]
TITLE kannst du ändern wann und wie oft du willst.

FOLDER wird sehr häufig dafür verwendet, das installierte Plugin wiederzuerkennen ( z.b. schon für die Variablen).

Außer die E-Mail zu ändern ist der Rest Bullshit-Bingo, ich kenne kein einziges Beispiel, wo das ein Problem war.
Aber das letzte Wort hat sowieso Michael, und das ist schon gesprochen!

**Comment by christianTF** [comment]
PS: Es nervt wirklich, das mit dir hier zu diskutieren, wenn du die Specs gerade mal "überflogen" hast. 
Du kannst dich ja einbringen, aber komm bitte mit was Sinnvollem, wo nicht alles explodiert.
Der Deinstallations-Issue gehört bereits dir.

**Comment by jelmd** [comment]
OK, die einen sagen so, die anderen so ;-) Dann bleibt's halt, wie es ist und man findet jetzt auch, wieso es so ist :).

**Comment by christianTF** [comment]
Der Uninstall-Issue gehört bereits dir. Bitte nicht alles in die Luft jagen mit dem Pull Request 😉

**Comment by mschlenstedt** [comment]
@christianTF  Die Notifications sollten doch eigentlich in Zeile 163 gelöscht werden, oder? 

https://github.com/mschlenstedt/Loxberry/blob/e4039a317e873cf4ea25046f98d8a9e6824573f4/sbin/plugininstall.pl#L163

**Comment by mschlenstedt** [comment]
Ah, Moment: Ich springe aus der &purge_installation-Subroutine nicht mehr zurück. Damit wird das vermutlich nie ausgeführt.

Ich ändere das Mal -> bitte testen.
