### ISSUE TITLE
Loxberry page is gone

### ISSUE THREAD

**Issue by pmatos** [mschlenstedt/Loxberry#831]
`http://www.loxwiki.eu/display/LOXBERRY`

returns 404

**Comment by johny-mnemonic** [comment]
@pmatos This doesn't seem to be isolated to Loxberry. Whole loxwiki.eu doesn't work...

**Comment by pmatos** [comment]
@johny-mnemonic Correct, but I really only care about loxberry since it's also where loxberry stores the plugin archive.

**Comment by christianTF** [comment]
LoxWiki switched server yesterday to fully integrate https.
The http to https redirection should again be in place already.

`http://www.loxwiki.eu/display/LOXBERRY` should now return a 
`301 Moved Permanently` with a redirect to `https://www.loxwiki.eu/display/LOXBERRY`

**Comment by pmatos** [comment]
It's back, thanks.
