### ISSUE TITLE
Der LoxBerry soll ein Watchdog Service bekommen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#840]
https://smarthome-blogger.de/kurztipps/raspberry-watchdog/

man watchdog
/usr/share/doc/watchdog/example/repair.sh

**Comment by mschlenstedt** [comment]
Überwachung von
- Temperatur
- Speicherauslastung
- Load
- Netzwerk (muss zwischen eth0 und wlan0 unterscheiden -> Anpassung der Watchdog-Config über das Netzwerk Widget notwendig)

**Comment by Woersty** [comment]
Wozu? Macht das Rpi Monitor Plugin doch schon alles. Dann Erweitere den doch lieber um eine Alarmierung.

**Comment by Woersty** [comment]
Nagut. Hängt nah am Kernel und würde auch greifen wenn er in verschiedenen Freeze Problemen hängt. Ok. Bin dafür.

**Comment by christianTF** [comment]
Ist das ein "clean reboot", also ein normaler Shutdown, wo auch unser Shutdown-Script läuft?
Evt. deaktivierbar über das LoxBerry Services Widget.

Der Benutzer sollte erfahren, dass das passiert ist, und warum (z.B. Notify).

(Hab glaub ich noch nie die Situation gehabt, dass mir ein Pi aufgrund der genannten Kriterien gestorben ist)

**Comment by mschlenstedt** [comment]
Denke ja. 

Ich würde sogar ein eigenes Widget machen, wo das aktivierst ist und auch konfigurierbar ist (Temperatur, Load etc.).

**Comment by christianTF** [comment]
Ich würde es als NavBar-Tab in die Dienste packen. Zumindest war das Widget mal für kleinere Sachen gedacht. Kommt halt drauf an, wieviel man einstellen kann. Wenn es so viel ist, dass es mehrere Seiten braucht, dann geht's eh nicht anders.
Wir haben vor lauter Widgets schon keinen Platz mehr ;-)

**Comment by mschlenstedt** [comment]
Auch ok.

**Comment by mschlenstedt** [comment]
Done with c28b879e6b8e8a0f019382723303dc40ac8b2c14
