### ISSUE TITLE
Der LoxBerry soll ein Remote Support Widget bekommen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#841]
Erste Ideen:

- Auf loxberry.de läuft ein OpenVPN Server
- Für Core Mitglieder gibt es eine Webseite, über die man ein "Support Key" erzeugen kann (5-stellige Zufallszahl)
- Der Server generiert ein z. B. 3 Tage lang gültiges Zertifikat für den OpenVPN Zugang und erzeugt auch eine passende OpenVPN-Client-Config, packt alles zusammen und legt es als Download ab
- Der Support Key wird dem User mitgeteilt
- Der User gibt den Support Key im Widget ein. Das Widget holt sich auf dem loxberry.de Server die generierte Config samt Zertifikat ab und installiert es
- Der User kann nun die OpenVPN Verbindung aktivieren und der LB wählt sich ins VPN ein
- Ein Cronjob deaktiviert automatisch nach 24h den Zugang und löscht automatisch nach 3 Tagen die OpenVPN Config auf dem LB wieder

**Comment by christianTF** [comment]
SoftEther VPN
VPN over HTTPS, das geht immer irgendwie durch
Und NAT Traversal integriert
https://www.softether.org/1-features/1._Ultimate_Powerful_VPN_Connectivity#1.5._NAT_Traversal


https://www.softether.org/

**Comment by mschlenstedt** [comment]
Habe es jetzt erst einmal mit OpenVPN implementiert. Das sollte von Innen nach Außen auch immer gehen.

**Comment by mschlenstedt** [comment]
Closed with 40cec1210b83bbe39ad824eab8a572460c4aaa46
