### ISSUE TITLE
Sudoers mit hardcodiertem Pfad

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#843]
https://github.com/mschlenstedt/Loxberry/blob/master/system/sudoers/lbdefaults

Hardcodierte Pfade auf /opt/loxberry

**Comment by christianTF** [comment]
Die hardcodierten Pfade können bleiben, aber sollten bei der Image-Erstellung in setenvironment.sh automatisch durch den korrekten Pfad ersetzt werden.

sudoers unterstützt jedenfalls keine Environment-Variablen, das hätte ich schon mal probiert.

**Comment by christianTF** [comment]
Ergänzung: Mit LBUpdate ersetzen wir das regelmäßig, müsste man auch speziell behandeln
