### ISSUE TITLE
LoxBerry Dienste Hilfe fehlt

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#850]

**Comment by christianTF** [comment]
#272

**Comment by christianTF** [comment]
- lbheader für PHP unterstützt derzeit nur Plugin-Hilfe (keine System-Hilfe)
- Kann die Code-Änderung nicht debuggen https://github.com/mschlenstedt/Loxberry/issues/923, hab die Erweiterung deswegen nicht eingecheckt.

**Comment by christianTF** [comment]
Closed with https://github.com/mschlenstedt/Loxberry/commit/643d736a2442bf527a6ea177165c39f53ca8e118
