### ISSUE TITLE
Perl: LoxBerry::System $lbstmpfslogdir fehlt

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#861]
Es gibt nur $lbslogdir. Es fehlt wie in der Bash $lbstmpfslogdir

PHP?

**Comment by christianTF** [comment]
Kenn ich überhaupt nicht

**Comment by mschlenstedt** [comment]
Muss auf /opt/loxberry/log/system_tmpfs/ zeigen.

$lbslogdir zeigt auf /opt/loxberry/log/system/

**Comment by christianTF** [comment]
Das wird wieder aufwändig.... 

Ich mach mir ne Liste zum Checken/Implementieren/Testen:
- [x] System.pm
- [x] loxberry_system.php 
- [x] setenvironment.sh (schon da)
- [x] sudoers/lbdefaults
- [x] apache2/envvars (war schon da)
- [x] apache2/sites-available/000-default.conf (war schon da)
- [x] Updatescript

**Comment by mschlenstedt** [comment]
Wir können das auch sein lassen. Habe es mir jetzt aus $lbhomedir eh schon selbst zusammengebaut. Bin nur drüber gestolpert, weil es im Bash Environment verfügbar ist aber in Perl nicht.

**Comment by christianTF** [comment]
Da die Environments schon da waren, war's doch nicht so schlimm. Außer den Libs hat's nur in sudoers/lbdefaults gefehlt. 
Das Updatescript kopiert jetzt die neue sudoers/lbdefaults schon mit
