### ISSUE TITLE
resetpermissions.sh: Erzeugt die sudoers-Meldungen, bremst LBUpdate

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#862]
Die Zeile im resetpermissions.sh 
`find $LBHOMEDIR -not -path "*skel_syslog*" -exec chown -Rc loxberry:loxberry {} \;`
ist verantwortlich dafür, dass es immer noch zu Fehlern wie "user is 1001 should be 0" kommt.

Obwohl in LBUpdate vor dem rsync bereits die Permission partiell vor-korrigiert werden, wird dadurch wieder alles auf loxberry:loxberry gesetzt.
Am Pi 2 dauert dieses find (wenn keine Änderungen mehr durchgeführt werden) 59 Sekunden.
```
root@loxberry-dev:/opt/loxberry/sbin# time find $LBHOMEDIR -not -path "*skel_syslog*" -exec chown -Rc loxberry:loxberry {} \;
real    0m58.584s
```

Da chown sowieso -R ausgeführt wird, eine mögliche Optimierung auf Einschränkung auf Directories:
```
root@loxberry-dev:/opt/loxberry/sbin# time find $LBHOMEDIR -type d -not -path "*skel_syslog*" -exec chown -Rc loxberry:loxberry {} \;
real    0m8.558s
```

@mschlenstedt Kann das aus deiner Sicht funktionieren, wenn chown -R nur auf die Verzeichnisse ausgeführt wird?

Was ich absolut nicht geschafft habe, ist ~/system/sudoers als zweites Verzeichnis auszunehmen.
Ich mag 'find' nicht mehr, viel zu undurchschaubare Syntax.
Vielleicht gibt es ein besseres Tool - wir müssten optimalerweise etwa eine Hand voll oder mehr Verzeichnisse ausnehmen.

**Comment by christianTF** [comment]
Das könnte funktionieren:
```
time find $LBHOMEDIR -type d -print | grep -v -f /tmp/excludelist.txt | xargs chown loxberry:loxberry -Rc
real    0m1.712s
```
Die Excludelist liefern wir mit oder erzeugen Sie im tmpfs zur Laufzeit.

PS: Das Exclude funktioniert damit auch noch nicht ganz richtig - ich brauch eine Pause.

**Comment by christianTF** [comment]
Neuer Versuch:

`find $LBHOMEDIR -type d -print | grep -z -v /tmp/excludelist.txt | while read line ; do chown -c loxberry:loxberry $line ; chown -c loxberry:loxberry $line/* ; done`
Ändere in allen Verzeichnissen alle Dateien ohne -R

**Comment by mschlenstedt** [comment]
Der find Befehl ist glaube ich nur reingekommen, weil "/log/skel_syslog" ausgelassen werden muss. Sonst könnte man auch einfach

```chown -Rv loxberry:loxberry $LBHOMEDIR```

machen. Da muss es noch einen einfachereren Weg als mit der excludelist usw. geben. Das ist mir zu kompliziert (und fehleranfällig).

Laß mich mal drüber nachdenken...
