### ISSUE TITLE
add own hostname to /etc/hosts

### ISSUE THREAD

**Issue by gahujipo** [mschlenstedt/Loxberry#866]
i know that running Loxberry is not supported on a VM but I'd like to inform you that the hostname resolution of the Loxberry-machine itself does not work. (running on Debian 9-amd64)

I'm not sure if the hostname should be resolved via /etc/hosts. But i can confirm that the hostname is written in /etc/hosts at the end of the file: 
![image](https://user-images.githubusercontent.com/26710574/49942323-472e9080-fee5-11e8-9404-8be47d8ec40d.png)

**Comment by christianTF** [comment]
Reproduced on Raspberry loxberry-dev (Pre-1.4.0) / Pi2:
```
#cat /etc/hosts
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters



        loxberry-dev
```

Something's wrong with our "set hostname in hosts" script? (I currently don't find this code, it was from @svethi?)

Possibly depends to https://github.com/mschlenstedt/Loxberry/issues/803


![image](https://user-images.githubusercontent.com/14220265/49946512-6df1c480-feef-11e8-9f51-8522c83ae895.png)

**Comment by christianTF** [comment]
After rebooting, the settings were ok. 
It seems that the hosts update routine fails sometimes for some reason. It can also be reasoned from the remote tests.

**Comment by christianTF** [comment]
@gahujipo 
If it never writes the hostname to your hosts file, it is an error of the vm.
This is - as far as I remember - done by a dhcp trigger, or static when using a static ip.

**Comment by gahujipo** [comment]
https://github.com/mschlenstedt/Loxberry/pull/867

you are right. This pr fixes the interface determination. Could you verify if it works on the pi too?

**Comment by Woersty** [comment]
I will have a look when at home.

**Comment by Woersty** [comment]
https://github.com/mschlenstedt/Loxberry/commit/19dcea205d0027ec21c2d131db9644a539d5a949

**Comment by Woersty** [comment]
@gahujipo I forgot: Thanks! 😃

**Comment by christianTF** [comment]
Pull requests need to be tested on original Raspberry hardware.
Don’t play with code changes on unsupported platforms risking hundreds of production installations.

Please study the https://github.com/mschlenstedt/Loxberry/blob/master/CODE_OF_CONDUCT.md

**Comment by gahujipo** [comment]
> Pull requests need to be tested on original Raspberry hardware.

sorry. I vow betterment in the future.

**Comment by Woersty** [comment]
I have tested it before merging the commit.
