### ISSUE TITLE
V0.1.3: Logfile Viewer Plugin

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#87]
Irgendwas stimmt da nicht. Wieso startet er das cgi 6 Mal?
Außerdem ist der LoxBerry dann mehrere Minuten blockiert und nicht via Web erreichbar.
(Waiting for Socket)

**Comment by mschlenstedt** [comment]
Mmmhh, kann ich nicht reproduzieren. Ist das immer so?

**Comment by Woersty** [comment]
Habe es heute noch mal probiert und kann es jetzt nicht nachvollziehen.
Gestern war es immer so und dann wurde der Raspberry extrem lahm.
Komisch.

**Comment by Woersty** [comment]
Jetzt ist es wieder so - nach erneuter Plugin Installation

**Comment by mschlenstedt** [comment]
Kannst du mal genau beschreiben was du machst? Betrifft es nur ein Plugin oder alle?

**Comment by Woersty** [comment]
Ich installiere das Plugin und dann spinnt er rum. Betrifft alle. Sieht man auch mit ps -ef
Bin jetzt aber erstmal wieder im Urlaub.

**Comment by mschlenstedt** [comment]
Konnte es jetzt reproduzieren. Das logfile.cgi Script wird über JQUERY aufgerufen:

` $('#Logfile').load('/admin/system/tools/logfile.cgi?logfile=&head=none&format=html');

Das ist letztendlich identisch mit dem Standard-Javascript .get (soweit ich gelesen habe). Das ganze ist in einer Scheife, die alle 1000ms angearbeitet wird.

Somit sind zwei Instanzen normal, solange eine Installation läuft: Eine fürs Logfile, eine fürs Statusfile.

Interessanterweise werden die beiden Prozesse auch noch weiter aufgerufen, nachdem die Installation beendet ist und man auch die Seite längst geschlossen hat. Ich denke, dass das ein Cache-Thema ist. Wenn man jetzt schnell hintereinander Plugins installiert, dann summieren sich die Prozesse immer weiter, bis sie dann beendet werden (weil die Daten aus dem Browser-Cache gelöscht sind?).

Strange....

Könnte man als Workaround vielleicht so lösen, dass man die Instanzen alle killt, wenn man sie nicht mehr braucht. Ist aber nicht sehr "sauber".

Eventuell hilft es anstelle JQUERY nur das Javascript .get zu verwenden. Ich teste das mal.

**Comment by mschlenstedt** [comment]
Mache das erstmal zzu (siehe #115)
