### ISSUE TITLE
Validierung geht nicht mit Punkt in ID

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#872]
Wenn man als id eine Variable mit Punkt verwendet (id="Watchdog.Ping"), geht die Validierung nicht mehr.  Die Validierung aktiviert man dann mit "validate_enable('#Watchdog\\.Ping');", aber der Errortext wird nicht angezeigt.

**Comment by Woersty** [comment]
Wer macht denn auch sowas? Das macht doch nur Probleme. Kannst du die Variable nicht umbenennen?

**Comment by mschlenstedt** [comment]
Ja, habe ich gemacht. Ist @christianTF Beispielcode für die neue JSON-Lib :-) 

Ich brauch das nicht, aber wir sollten es fixen, falls da nochmal jemand auf so eine Idee kommt, oder?

**Comment by christianTF** [comment]
https://learn.jquery.com/using-jquery-core/faq/how-do-i-select-an-element-by-an-id-that-has-characters-used-in-css-notation/
