### ISSUE TITLE
LB::JSON: Verbessern

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#873]
- JSON-*Teil* direkt aus Datei lesen
- Und direkt als Template-Variable übergeben

**Comment by mschlenstedt** [comment]
Ich würde zwei Vereinfachungen gut finden:

**1. Ersatz für das alte "associate => $cfg"**

Z. B. hier: https://github.com/mschlenstedt/Loxberry/blob/36ee860a997f23c06370cba52599a0e2b18c7eb1/webfrontend/htmlauth/system/admin.cgi#L100

Ich könnte mir vorstellen, dass es so funktioniert:
```
my $cfgfile = $lbpplugindir."/pluginconfig.json";
$jsonobj = LoxBerry::JSON->new();
$cfg = $jsonobj->open(filename => $cfgfile);
$jsonobj->associate(CFG);
```
Das erzeugt HTML::Template-Variablen mit dem Prefix CFG, z. B. <TMPL_VAR CFG.REMOTE.HTTPPORT>

CFG soll ein Präfix sein. Zu den Hierarchien: Ich dachte man macht das so: <TMPL_VAR PRÄFIX.GRUPPE1.GRUPPE2.VAR>, also z. B. <TMPL_VAR CFG.REMOTE.HTTPPORT>

**2. Automatisch Javascript-Block erzeugen**

Z. B, hier: 
https://github.com/christianTF/LoxBerry-Plugin-MQTT-Gateway/blob/79421437b4b77d413386f1232cd3b3c5f0b756a3/templates/mqtt.html#L468

Ich könnte mir vorstellen, dass es so funktioniert:
```
my $cfgfile = $lbpplugindir."/pluginconfig.json";
$jsonobj = LoxBerry::JSON->new();
$cfg = $jsonobj->open(filename => $cfgfile);
$jsonobj->jsblock(PARSECFG);
```

Erzeugt eine HTML::Template-Variable <TMPL_VAR PARSECFG>, die obigen JS-Block enthält. Hier müssen wir aber noch beachten, dass es vermutlich recht viele Sonderfälle gibt. Ich brauche z. B. $("#"+elemname).flipswitch( "refresh" ); anstelle von checkboxradio, weil ich die Checkbox-Elemente als FlipSwitch nutze. Zudem muss bei der else-Verzweigung der ElementType "file" ausgenommen werden (Sicherheitsbedingungen aller moderner Browser).

**Comment by christianTF** [comment]
Ich glaub, alles drin:
Neu in V1.4.3:
- `$jsonobj->flatten` liefert die Datenstruktur als flachen Hash, Hierarchien mit . getrennt. 
- `$jsonobj` kann direkt bei HTML::Tempate mit associate =>$jsonobj mitgegeben werden.
- `$jsonobj->encode` liefert den aktuellen Daten-Hash als json-String (opt. mit pretty => 1)
- `$jsonobj->jsblock` liefert ein JS-Statement, korrekt escaped, mit dem Variablennamen varname => "jsvarname"

https://www.loxwiki.eu/display/LOXBERRY/Perl+Modul+LoxBerry%3A%3AJSON
