### ISSUE TITLE
Logfiles in Logmanager ohne Autoscroll öffnen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#876]
Logfiles in LBUpdate können ohne Autoscroll geöffnet werden (spart Ressourcen insbesondere auf zero/Raspi1):

&only=once

**Comment by christianTF** [comment]
Meinst du den Logfile-Button, nachdem man Install geklickt hat?
Dort hab ich das explizit nicht gesetzt, weil man davon ausgehen kann, dass die Installation läuft und man zuschauen möchte.

Oder meinst du woanders?

**Comment by mschlenstedt** [comment]
Nee, da ist es richtig. Ich meine im Logmanager die Öffnen-Button. Und in LBUpdate die Logfile Übersicht (auch hier die Öffnen Button).
