### ISSUE TITLE
Logmanager: "Mehr Logfiles" soll auch Core-Logfiles anzeigen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#877]
Im Abschnitt "Mehr Logfiles" sollten auch die Core-Logfiles, die nicht über die Lib angelegt werden, mit angezeigt werden.

Beispiele:
~/log/system_tmpfs/openvpn.log
~/log/system_tmpfs/watchdog.log

**Comment by christianTF** [comment]
~/log/system und ~/log/system_tmpfs ?

**Comment by mschlenstedt** [comment]
Ja. Inkl. Unterverzeichnisse.
