### ISSUE TITLE
Pluginsupdate: Besser dokumentieren (Hilfe, Link ins Wiki)

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#879]

**Comment by mschlenstedt** [comment]
Was meinst Du genau? Eine Anleitung für die Pluginentwickler?

**Comment by christianTF** [comment]
Für Benutzer.
Hatte kurz hintereinander zwei Fälle, wo ich erklärt hab, wie das funktioniert. Es scheint nicht ganz klar zu sein.

Ich weiß auch nicht mehr, wie wir benachrichtigen.

**Comment by christianTF** [comment]
Ich schreib was im Wiki. Im UI könnten wir einen Link neben dem Update-Button setzen, der das Hilfe-Flyout öffnet, dort kurz erklären mit Link ins Wiki.

**Comment by christianTF** [comment]
Info zum Notify über neue Versionen:
- Hier wird ein Notify an 'plugininstall' abgesetzt, wenn eine neue Version verfügbar ist: https://github.com/mschlenstedt/Loxberry/blob/43efe756e4ba52ab247e55debd15d6eed554b01a/sbin/pluginsupdate.pl#L240
- Hier werden im Plugininstall-Widget die Notifications oben angezeigt: https://github.com/mschlenstedt/Loxberry/blob/43efe756e4ba52ab247e55debd15d6eed554b01a/webfrontend/htmlauth/system/plugininstall.cgi#L175

**Comment by christianTF** [comment]
Wiki-Artikel deutsch: https://www.loxwiki.eu/display/LOXBERRY/Automatische+und+manuelle+Plugin-Updates
Wiki-Artikel englisch: https://www.loxwiki.eu/display/LOXBERRY/Automatic+and+manual+plugin+updates

**Comment by mschlenstedt** [comment]
Fixed with d5e2fddda5dd05e4c298f3d27052b4b8b886a892

:-)

**Comment by christianTF** [comment]
Also fixes #848 :-)
