### ISSUE TITLE
Automatische Sicherheitsupdates lassen sich nicht speichern

### ISSUE THREAD

**Issue by andylox** [mschlenstedt/Loxberry#882]
Egal welche Option ich bei den automatischen Sicherheitsupdates anklicke, wenn ich danach wieder auf die Seite gehe bleibt der Knopf auf aus. Einen Speichernknopf gibt es ja nicht. Was mache ich falsch?

**Comment by christianTF** [comment]
- Repro auf LoxBerry PRE-1.4: Funktioniert korrekt
- Repro auf LoxBerry 1.2.5.5 --> Funktioniert korrekt

Bitte Infrastruktur angeben. 
Die Funktion liest die Settings direkt aus der Debian AutoUpdate-Konfiguration aus. Wenn es diese Config nicht gibt (weil die VM(?) unvollständig ist), lässt sich die Funktion mangels der entsprechenden Config-Files natürlich nicht aktivieren.

lg, Christian

**Comment by andylox** [comment]
Sorry, hab den 1.2.5.5 installiert, ist aber schon ziemlich lange so. dachte jetzt ich mache mal nen issue, damit ihr es in 1.3 mit aufnehmen könnt. Ich habe klassich den Loxberry installiert glaube mit Version 1.2 oder so.
Läuft auf einem Pi 3+B

**Comment by christianTF** [comment]
Wenn du F12 im Browser drückst, auf Network gehst, und eine Option änderst, kommt beim ajax-config-handler dann ein 200 OK zurück?

![image](https://user-images.githubusercontent.com/14220265/50211158-331ce000-0378-11e9-9a01-df5ccdc29d6d.png)

**Comment by christianTF** [comment]
Weitere Analyse-Schritte:
- An der Shell anmelden
- Prüfen, ob die Files `/etc/apt/apt.conf.d/02periodic` und `/etc/apt/apt.conf.d/50unattended-upgrades` vorhanden sind
- Wenn vorhanden, bitte hier anhängen.

lg, Christian

**Comment by andylox** [comment]
Ja das Axaj meldet eine 200 zurück!
Habe grade auch beim testen gemerkt auch unter Loxberry Update kann ich keine Optionen ändern, also ändern schon aber wird nicht gespeichert.

Die 02periodic ist da aber leer, die andere siehe hier:

` // Unattended-Upgrade::Origins-Pattern controls which packages are
// upgraded.
//
// Lines below have the format format is "keyword=value,...".  A
// package will be upgraded only if the values in its metadata match
// all the supplied keywords in a line.  (In other words, omitted
// keywords are wild cards.) The keywords originate from the Release
// file, but several aliases are accepted.  The accepted keywords are:
//   a,archive,suite (eg, "stable")
//   c,component     (eg, "main", "contrib", "non-free")
//   l,label         (eg, "Debian", "Debian-Security")
//   o,origin        (eg, "Debian", "Unofficial Multimedia Packages")
//   n,codename      (eg, "jessie", "jessie-updates")
//     site          (eg, "http.debian.net")
// The available values on the system are printed by the command
// "apt-cache policy", and can be debugged by running
// "unattended-upgrades -d" and looking at the log file.
//
// Within lines unattended-upgrades allows 2 macros whose values are
// derived from /etc/debian_version:
//   ${distro_id}            Installed origin.
//   ${distro_codename}      Installed codename (eg, "jessie")
Unattended-Upgrade::Origins-Pattern {
        // Codename based matching:
        // This will follow the migration of a release through different
        // archives (e.g. from testing to stable and later oldstable).
//      "o=Debian,n=jessie";
//      "o=Debian,n=jessie-updates";
//      "o=Debian,n=jessie-proposed-updates";
//      "o=Debian,n=jessie,l=Debian-Security";
                                                                                                                                       
        // Archive or Suite based matching:
        // Note that this will silently match a different release after
        // migration to the specified archive (e.g. testing becomes the
        // new stable).
//      "o=Debian,a=stable";
//      "o=Debian,a=stable-updates";
//      "o=Debian,a=proposed-updates";
        "origin=Debian,codename=${distro_codename},label=Debian-Security";
};
                                                                                                                                       
// List of packages to not update (regexp are supported)
Unattended-Upgrade::Package-Blacklist {
//      "vim";
//      "libc6";
//      "libc6-dev";
//      "libc6-i686";
};
                                                                                                                                       
// This option allows you to control if on a unclean dpkg exit
// unattended-upgrades will automatically run 
//   dpkg --force-confold --configure -a
// The default is true, to ensure updates keep getting installed
//Unattended-Upgrade::AutoFixInterruptedDpkg "false";
                                                                                                                                       
// Split the upgrade into the smallest possible chunks so that
// they can be interrupted with SIGUSR1. This makes the upgrade
// a bit slower but it has the benefit that shutdown while a upgrade
// is running is possible (with a small delay)
//Unattended-Upgrade::MinimalSteps "true";
                                                                                                                                       
// Install all unattended-upgrades when the machine is shuting down
// instead of doing it in the background while the machine is running
// This will (obviously) make shutdown slower
//Unattended-Upgrade::InstallOnShutdown "true";
                                                                                                                                       
// Send email to this address for problems or packages upgrades
// If empty or unset then no email is sent, make sure that you
// have a working mail setup on your system. A package that provides
// 'mailx' must be installed. E.g. "user@example.com"
//Unattended-Upgrade::Mail "root";
                                                                                                                                       
// Set this value to "true" to get emails only on errors. Default
// is to always send a mail if Unattended-Upgrade::Mail is set
//Unattended-Upgrade::MailOnlyOnError "true";
                                                                                                                                       
// Do automatic removal of new unused dependencies after the upgrade
// (equivalent to apt-get autoremove)
//Unattended-Upgrade::Remove-Unused-Dependencies "false";
                                                                                                                                       
// Automatically reboot *WITHOUT CONFIRMATION* if
//  the file /var/run/reboot-required is found after the upgrade 
//Unattended-Upgrade::Automatic-Reboot "false";
                                                                                                                                       
// Automatically reboot even if there are users currently logged in.
Unattended-Upgrade::Automatic-Reboot-WithUsers "true";
                                                                                                                                       
// If automatic reboot is enabled and needed, reboot at the specific
// time instead of immediately
//  Default: "now"
//Unattended-Upgrade::Automatic-Reboot-Time "02:00";
                                                                                                                                       
// Use apt bandwidth limit feature, this example limits the download
// speed to 70kb/sec
//Acquire::http::Dl-Limit "70";
                                                                                                                                       
// Enable logging to syslog. Default is False
// Unattended-Upgrade::SyslogEnable "false";
                                                                                                                                       
// Specify syslog facility. Default is daemon
// Unattended-Upgrade::SyslogFacility "daemon";`

**Comment by christianTF** [comment]
#884 

Kannst du bitte diese beiden Ausgaben noch prüfen:

```
ls -l /opt/loxberry/system/unattended-upgrades/
total 12
-rw-rw---- 1 loxberry loxberry  940 Dec  4 18:00 periodic.conf
-rw-rw---- 1 loxberry loxberry 4257 Dec 19 10:06 unattended-upgrades.conf
loxberry@loxberry-dev:/ $
```
und
```
ls -l /etc/apt/apt.conf.d/
total 28
-rw-r--r-- 1 root root  769 Sep 13  2017 01autoremove
-r--r--r-- 1 root root 1282 Apr  1  2018 01autoremove-kernels
lrwxrwxrwx 1 root root   54 Feb  7  2018 02periodic -> /opt/loxberry/system/unattended-upgrades/periodic.conf
-rw-r--r-- 1 root root   80 Dec 11  2016 20auto-upgrades
-rw-r--r-- 1 root root  202 Apr 10  2017 20listchanges
-rw-r--r-- 1 root root  161 Nov 29  2017 50raspi
lrwxrwxrwx 1 root root   65 Feb  7  2018 50unattended-upgrades -> /opt/loxberry/system/unattended-upgrades/unattended-upgrades.conf
-rw-r--r-- 1 root root  182 May 21  2017 70debconf
```

Die beiden Dateien müssen von etc ins /opt/loxberry/system/unattended-upgrades linken.

Wenn die Links stimmen, kannst du die angehängten Dateien *als root* in /opt/loxberry/system/unattended-upgrades kopieren.
[unattended.zip](https://github.com/mschlenstedt/Loxberry/files/2694317/unattended.zip)

lg, Christian

**Comment by andylox** [comment]
Also die periodic.conf war bei mir komplett leer und i nder unattended-upgraded.conf stand
Unattended-Upgrade::Automatic-Reboot-WithUsers "false"; statt true drin.

Ersetzt und alles geht! Danke Dir. Woher kann sowas kommen?

**Comment by christianTF** [comment]
Dass das File leer war, könnte davon gekommen sein, dass früher die Files während der Änderung nicht gelockt waren. So besteht die Chance, dass mehrere Threads gleichzeitig in die gleiche Datei schreiben, bis sie kaputt ist.

Warum es beim existierenden File nicht funktioniert hat, kann ich leider nicht sagen.
