### ISSUE TITLE
Apache startet jede Stunde neu

### ISSUE THREAD

**Issue by andylox** [mschlenstedt/Loxberry#883]
In den Systemlogs des Apache sehe ich, dass er stündlich neustartet, das kann ja nicht Sinn der Sache sein oder?
Version 1.2.5.5
`[Tue Dec 18 16:13:11.437153 2018] [mpm_prefork:notice] [pid 941] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.178.50. Set the 'ServerName' directive globally to suppress this message
[Tue Dec 18 16:13:11.665658 2018] [mpm_prefork:notice] [pid 941] AH00163: Apache/2.4.25 (Raspbian) configured -- resuming normal operations
[Tue Dec 18 16:13:11.665700 2018] [core:notice] [pid 941] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 18 17:13:10.599029 2018] [mpm_prefork:notice] [pid 941] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.178.50. Set the 'ServerName' directive globally to suppress this message
[Tue Dec 18 17:13:10.813740 2018] [mpm_prefork:notice] [pid 941] AH00163: Apache/2.4.25 (Raspbian) configured -- resuming normal operations
[Tue Dec 18 17:13:10.813780 2018] [core:notice] [pid 941] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 18 18:13:10.818085 2018] [mpm_prefork:notice] [pid 941] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.178.50. Set the 'ServerName' directive globally to suppress this message
[Tue Dec 18 18:13:11.095231 2018] [mpm_prefork:notice] [pid 941] AH00163: Apache/2.4.25 (Raspbian) configured -- resuming normal operations
[Tue Dec 18 18:13:11.095281 2018] [core:notice] [pid 941] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 18 19:13:11.369072 2018] [mpm_prefork:notice] [pid 941] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.178.50. Set the 'ServerName' directive globally to suppress this message
[Tue Dec 18 19:13:11.594234 2018] [mpm_prefork:notice] [pid 941] AH00163: Apache/2.4.25 (Raspbian) configured -- resuming normal operations
[Tue Dec 18 19:13:11.594275 2018] [core:notice] [pid 941] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 18 20:13:10.496904 2018] [mpm_prefork:notice] [pid 941] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.178.50. Set the 'ServerName' directive globally to suppress this message
[Tue Dec 18 20:13:10.697969 2018] [mpm_prefork:notice] [pid 941] AH00163: Apache/2.4.25 (Raspbian) configured -- resuming normal operations
[Tue Dec 18 20:13:10.698007 2018] [core:notice] [pid 941] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 18 21:13:10.532998 2018] [mpm_prefork:notice] [pid 941] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.178.50. Set the 'ServerName' directive globally to suppress this message
[Tue Dec 18 21:13:10.740860 2018] [mpm_prefork:notice] [pid 941] AH00163: Apache/2.4.25 (Raspbian) configured -- resuming normal operations
[Tue Dec 18 21:13:10.740899 2018] [core:notice] [pid 941] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 18 22:13:10.740121 2018] [mpm_prefork:notice] [pid 941] AH00171: Graceful restart requested, doing restart`

**Comment by christianTF** [comment]
Das ist kein Restart, sondern ein Reload der Config.
Muss so gemacht werden, sonst können wir sein Log nicht aufräumen. 
Tut ihm nix, ist Standard (so wie das auch Logrotate macht) - deswegen auch "graceful".

**Comment by andylox** [comment]
Ok danke, und das mit dem FQDN? Wo kann ich den eintragen?

**Comment by christianTF** [comment]
Keine Ahnung, googeln :-)

**Comment by svethi** [comment]
In /etc/hosts

**Comment by andylox** [comment]
Ok, da steht 192.168.178.50 loxberry schon drin. Hab dort mal nen zweiten eintrag gemacht mit loxberry.fritz.box. Mal sehen obs was bringt. Danke

**Comment by andylox** [comment]
Also das hat nix gebracht, aber in /etc/apache2/apache2.conf folgendes hat es gelöst:

ServerName loxberry.fritz.box
