### ISSUE TITLE
Servername in /etc/apache2/apache2.conf 

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#886]
Das könnte man in div. Scripte hineinnehmen, damit die Meldungen von Apache verschwinden
`AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.178.50. Set the 'ServerName' directive globally to suppress this message`

in /etc/apache2/apache2.conf
ServerName loxberry.fritz.box

_Originally posted by @andylox in https://github.com/mschlenstedt/Loxberry/issues/883#issuecomment-448947199_

**Comment by mschlenstedt** [comment]
Das müsste in ~/sbin/changehostname.sh?

Sollte nicht so schwierig sein. Noch in 1.4 mit hineinnehmen?

**Comment by christianTF** [comment]
Ich weiß nicht, wie am besten.
In changehostname könnte man es geben, aber es müsste auch initial hineingesetzt werden.

**Comment by jelmd** [comment]
Kann in diesem Zusammenhang gleich sbin/changehostname.sh bzgl. /etc/ssmtp/ssmtp.conf gefixt werden? hostname=foo*.local* ist i.d.R. immer falsch. Dort sollte IMHO stattdessen die erste Zeile von `hostname -A` erscheinen.

**Comment by svethi** [comment]
Ist in die default eingetragen und auch im changehostname dazugefügt.
Jetzt muss nur noch ein updatescript die Zeile ServerName loxberry.home.local, oder den aktuellen hostname in die /etc/apache2/apache2.conf eintragen.

**Comment by mschlenstedt** [comment]
Fixed in aa1fc1e163ec02e5ae82def2c735a1c4ebc2ff1b
