### ISSUE TITLE
Watchdog config changes not taken into account on save

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#887]
Wenn ich die Werte anpasse, greifen sie erst, wenn ich den Watchdog stoppe und starte.
Das sollte automatisch bei Save passieren.

Bekommen wir hin, dass wir auch Forkbombs und Filesystem freezes abfangen?
z.B. via kernel panic bzw /etc/sysctl.conf

Grüße

**Comment by Woersty** [comment]
Ansonsten cool:
```
Dec 21 01:00:05 loxberrydev watchdog[3061]: temperature: maximum = 70
...
Dec 21 01:00:05 loxberrydev watchdog[3061]: alive=[none] heartbeat=[none] to=loxberry@loxberry.woerstenfeld.de no_act=no force=no
Dec 21 01:00:05 loxberrydev watchdog[3061]: temperature increases above 68 (/sys/class/thermal/thermal_zone0/temp)
Dec 21 01:00:05 loxberrydev watchdog[3061]: it is too hot inside (temperature = 77 >= 70 for /sys/class/thermal/thermal_zone0/temp)
Dec 21 01:00:05 loxberrydev watchdog[3061]: shutting down the system because of error 252 = 'too hot'
```

**Comment by mschlenstedt** [comment]
Forkbombs erkennt er über Free Memory wenn ich es richtig verstanden habe. Habe es nicht selbst getestet, aber probiere mal https://askubuntu.com/questions/159491/why-did-the-command-make-my-system-lag-so-badly-i-had-to-reboot

Filesystem Freezes: Das könnte man über "file=" implementieren, Man brähcte eine Datei, die definitiv regelmäßig beschrieben wird. Diese würde der Watchdog auf Änderungen überwachen. Ideen welche man nehmen könnte?

**Comment by mschlenstedt** [comment]
Neustart beim Speichern in ba74c1a4c28d7fb70c1b9f5aa1d8508321c1c10a

**Comment by mschlenstedt** [comment]
Die Forkbomb funktioniert und wird abgefangen :-)

![image](https://user-images.githubusercontent.com/16830799/50325005-81e68900-04e2-11e9-92c0-b1364ff79227.png)

**Comment by mschlenstedt** [comment]
Fixed with ba74c1a4c28d7fb70c1b9f5aa1d8508321c1c10a

Wer noch Ideen für das Überwachen des Filesystems hat -> neuen Issue aufmachen
