### ISSUE TITLE
Image 1.4.0: Passwort "loxberry" geht nicht (im Wizard)

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#888]
Gibt man im Wizard "loxberry" als neues Passwort ein, so erkennt es zwar der Wizard, aber trotzdem kann man sich anschließend nicht mehr auf dem LB einloggen. loxberry:loxberry funktioniert nicht.

![image](https://user-images.githubusercontent.com/16830799/50374495-7765e580-05ef-11e9-9d6e-06b0c1ca2fa8.png)

**Comment by mschlenstedt** [comment]
Nachtrag: 

Direkt auf der Konsole geht loxberry:loxberry

Der Weblogin geht NICHT.

Das Root-Passwort geht NICHT.

**Comment by Woersty** [comment]
Benutzt der Wizard anderen Code als die Admin Seite?

**Comment by mschlenstedt** [comment]
Das ist komplett kaputt. Jetzt habe ich ein neues Passwort gesetzt: gEheim56

Er setzt im Webif trotzdem loxberry:loxberry!!! Und ich kann mich nicht mehr einloggen.

![image](https://user-images.githubusercontent.com/16830799/50374648-cc0a6000-05f1-11e9-9df7-69ed3ce303d8.png)

Nur hier geht jetzt auch der Login auf der Konsole nicht mehr. Und root geht auch nicht mehr.

**Comment by Woersty** [comment]
Wizard cgi habe ich nicht angefasst.
Übernimm die Änderungen aus admin cgi 
Dann sollte es gehen

**Comment by mschlenstedt** [comment]
Grrrggh, die Templates übernimmt er im Wizard automatisch, daber die "Logik nicht - die steckt in admin.cgi.

**Comment by mschlenstedt** [comment]
Das müsst ihr bitte fixen, keine Ahnung, was ihr im admin.cgi alles geändert habt.

**Comment by Woersty** [comment]
Heute Nacht. Bin unterwegs.
