### ISSUE TITLE
Plugin: HTTPS2HTTP für Virtuellen HTTP-Eingang

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#89]
Idee für Simples Plugin: HTTPS2HTTP für virtuellen HTTP-Eingang

**Comment by Woersty** [comment]
Fertig, wie kann ich es veröffentlichen?

**Comment by Woersty** [comment]
https://loxberry.woerstenfeld.de/

**Comment by mschlenstedt** [comment]
Siehe Email.
