### ISSUE TITLE
icecast2 Server Fehler nach Reboot + Lösung [Logging Error]

### ISSUE THREAD

**Issue by blacklightprism** [mschlenstedt/Loxberry#893]
Hallo @all,

habe bei mir auf den Loxberry zusätzlich Mopidy installiert, um Zugriff auf Spotify zu erhalten.
Für Multiroom-Audio wurde der snapcast server installiert. Um den Audiostream auch per http abfangen zu können (dann aber nichtmehr synchron), um so beispielsweise am Windows PC Musik hören zu können, habe ich kurzerhand den icecast2 Server installiert. Dieser läuft parallel mit dem snapcast server, was so auch funktioniert.

Einziges Problem (was mich in etwa 4 Stunden Fehlersuche gekostet hat) war, dass der Icecast Server nach einem Reboot des Loxberry nicht mehr funktionierte. Nach ausgiebigem Herumgebastle liegt dies wohl daran, dass das Verzeichnis /var/log/icecast2 nach einem Neustart nicht mehr existiert.

Nachdem in der Icecast Config Datei nun der Pfad der Logdateien umgebogen wurde zu /usr/share/icecast2/log und entsprechende Dateien (error.log & access.log) manuell angelegt wurden funktioniert alles (bisher).

**Comment by mschlenstedt** [comment]
Das liegt daran, dass sich /var/log zur Schonung der SD-Karte in einer Ramdisk befindet. Du kannst ein entsprechendes Verzeichnis mit dem korrekten Eigentümer und Schreibberechtigungen einfach in /opt/loxberry/log/skel_syslog anlegen (skel steht für skeleton). Der Inhalt dieses Verzeichnisses wird beim Systemstart nach /var/log kopiert, sodass die Logverzeichnisse wieder existieren.

Das skel-Verzeichnis wird nach einer Plugininstallation aktualisiert, aber wenn Du etwas manuell installierst wird das nicht getriggert. Wir müssten das per Cronjob regelmäßig antriggern.

**Comment by christianTF** [comment]
@mschlenstedt Wie schaut dafür deine Lösungs-Idee aus?

**Comment by mschlenstedt** [comment]
Ich würde beim Neustart/Herunterfahren die Verzeichnisse aus /var/log in log/skelsyslog/ sichern und dann noch stündlich per Cron.

Was besseres fällt mir nicht ein. Direkt nach einem apt-Lauf kann man das AFAIK nicht triggern.

**Comment by christianTF** [comment]
@mschlenstedt Müsste sich das nicht in LB20 durch das Kopieren der Log-Verzeichnisse vor Shutdown/Reboot erledigen, oder betrifft das nur besondere Verzeichnisse?

**Comment by mschlenstedt** [comment]
Vermutlich.

**Comment by christianTF** [comment]
Sollte mit LoxBerry 2.0 behoben sein (/var/log/ wird beim Shutdown gesichert und beim Boot wiederhergestellt).
Sollte das Problem weiter bestehen, bitte den Issue wieder öffnen.
