### ISSUE TITLE
Fehlende Datei in Apache log

### ISSUE THREAD

**Issue by andylox** [mschlenstedt/Loxberry#894]
Nach dem Update auf 1.4.0.2 kommt diese Fehlermedlung im Apache Log:
logmanager.cgi: couldn't open /opt/loxberry/templates/system/lang/_en.ini: No such file or directory at /opt/loxberry/webfrontend/htmlauth/system/logmanager.cgi line 85.

**Comment by christianTF** [comment]
helpfile 
#849
