### ISSUE TITLE
Unendlicher Kreis nach Abschluss des Wizards

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#9]
Nach der Einrichtung startet der LoxBerry neu und ein Kreis dreht unendlich auf der Webseite.
Ein Neuladen der Seite nach Timeout wäre schöner.

**Comment by Woersty** [comment]
Reboot Message wird jetzt angezeigt. Aber dann rödelt sich der Kreis trotzdem tot.
Hätte gedacht, dass man via Ajax oder so alle 3 Sekunden prüft,
ob er wieder da ist und dann die Seite neu geladen wird.

**Comment by mschlenstedt** [comment]
Mmhh, bei mir wird die Reboot Message nicht mal angezeigt. Eigentlich soll es so sein:

Kreis kommt und Rebootmessage wird geladen. Seite ist vollständig gelande (kein Kreis mehr) und nach 5 Sekunden rebootet das System. So wie es auch funktioniert, wenn man aus dem Hauptmenü heraus rebootet. Aber irgendetwas klappt da nicht.

Man könnte auch eine Überprüfung einbauen, meine Ajax-/Javascriptkenntnisse sind sehr beschränkt. Und man müsste auch abfangen wenn sich die IP-Adresse ändert.

**Comment by Woersty** [comment]
> Und man müsste auch abfangen wenn sich die IP-Adresse ändert.

Iiih, dann würde ich einfach eine Meldung anzeigen, dass der Anwender 
sich neu verbinden soll.

Fertig. Was soll der Aufwand... Macht man ja nicht täglich.

Mit freundlichem Gruß
Christian Wörstenfeld

---

Christian Wörstenfeld
Kalkbergeweg 10
D-12589 Berlin
Telefon: +49 30 50 15 8484
Mailbox: +49 30 55 15 1230
Fax:     +49 30 55 15 1232
Handy:   +49 30 55 15 1234
e-mail:christian@woerstenfeld.de
Threema: SV3C7MUX
Web: www.woerstenfeld.de
¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯

Am 14.07.2016 um 15:56 schrieb mschlenstedt:

**Comment by Woersty** [comment]
Sollte erledigt sein.
