### ISSUE TITLE
Validierung auf Sonderzeichen bei Friendlyname + Quotes

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#902]
Beim Firendlyname eine strengere Validierung und Quotes in general.cfg: https://www.loxwiki.eu/x/iYixAg

Eventuell bei dieser Gelegenheit gleich auf general.json umstellen und FRIENDLYNAME unter BASE und nicht unter NETWORK eintragen.

Nach Erledigung den Wikiartikel löschen.

**Comment by Woersty** [comment]
Erster Teil der Korrektur in https://github.com/mschlenstedt/Loxberry/commit/0b8e96e34b2bcdc4f4e350032df620814b2e6b58

Das mit dem JSON kann Micha machen 😁

**Comment by christianTF** [comment]
Lassen wir erstmal so.
