### ISSUE TITLE
Remote-Support: Weiterleitung auf Miniserver und Router

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#904]
Per iptables soll automatisch eine Portweiterleitung auf den Router (Gateway) und alle konfigurierten Miniserver erfolgen.

z. B. ab Port 64000: Alle Miniserver
z. B. ab Port 64500: Router

So kann man im Supportfall auch auf den Router und die Miniserver (auch per LoxConfig).

**Comment by christianTF** [comment]
Obsolet
