### ISSUE TITLE
Raspberry 3B+ bluetooth findet keine Geräte

### ISSUE THREAD

**Issue by defcore** [mschlenstedt/Loxberry#909]
Auf meinen Raspberry 3 B+ werden keine Bluetooth Geräte gefunden. 

`hcitool scan` findet nichts. 

Habe es auf meinen Raspberry PI 2 getestet, dort werden die Geräte gefunden.

**Comment by christianTF** [comment]
Das können wir nicht beantworten. Fragestellung unklar.
- Pi 2 hat kein Bluetooth on board.
- Mein Pi 3+ findet auch keine Bluetooth-Geräte, ich hab aber auch keine.

Am besten im Web suchen.

lg, Christian
