### ISSUE TITLE
Hauptmenu bei lang=en nicht Englisch

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#91]
Hauptmenu bei lang=en nicht Englisch

**Comment by mschlenstedt** [comment]
Geht bei mir.

![lang](https://cloud.githubusercontent.com/assets/16830799/17505261/5a7088c0-5e00-11e6-8c23-89af1a9f7565.png)

**Comment by Woersty** [comment]
Nicht per GET in URL sondern in .cfg

Gruß

**Comment by Woersty** [comment]
Ich meinte general.cfg
[BASE]
LANG=en

**Comment by mschlenstedt** [comment]
Ah ok. 

Fixed :-)
