### ISSUE TITLE
Copy hidden files

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#911]

**Comment by Woersty** [comment]
Vielleicht shopt -s dotglob benutzen?

Oder sowas wie cp -r /Quelle/{.,}* /Ziel oder so

**Comment by christianTF** [comment]
Worum geht's hier?

**Comment by Woersty** [comment]
Egal. War eher für miniserverbackup relevant.
Habe es da direkt in den Scripts gemacht
