### ISSUE TITLE
The logfile database sends an error and cannot automatically be recovered

### ISSUE THREAD

**Issue by vplustute** [mschlenstedt/Loxberry#914]
Hallo,

ich habe jetzt schon ein paar mal den Fehler gehabt, dass meine Loxberry über den Browser nicht mehr erreichbar war.
Nach dem Neustart über SSH wurde mir unter Log Manager Folgender Fehler angezeigt 

25.02.2019 15:46: The logfile database sends an error and cannot automatically be recovered. Please inform the LoxBerry-Core team about this error:
Error ()

Auf meinem Pi läuft die folgende Version vom Loxberry
Loxberry Version 1.4.03

**Comment by christianTF** [comment]
Dass die Logfile-Datenbank kaputt ist, ist mit ziemlicher Sicherheit ein Folgefehler.

Der eigentliche Fehler ist, dass Apache nicht mehr läuft, und das wiederum lässt mich eine volle RAM-Disk vermuten.

Du kannst die Log-DB erstmal löschen:
https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/188231-loxberry-fehler-nach-update-auf-1-4?p=189075#post189075

Danach bitte regelmäßig den freien Platz der tmpfs-Volumes checken (Widget „Mein LoxBerry“) und bei Auffälligkeiten prüfen, welche Dateien/Ordner genau deine RAM-Disk anfüllen.

**Comment by vplustute** [comment]
Ich habe die /opt/LoxBerry/log/system_tmpfs/logs_sqlite.dat aber die war nur ein paar Kilobyte groß.

Die SD Karte kann nicht voll sein. Laut "Mein LoxBerry" sind von den 60GB 19% belegt. Somit sollte genug platz sein, oder?

**Comment by christianTF** [comment]
Es geht um die tmpfs-Laufwerke.
Nach Reboot sind die immer leer.
Es gilt herausfinden, was deine RAM-Disk im Betrieb auffüllt.

**Comment by vplustute** [comment]
Ne ganz blöde Frage, mit RAM-Disk ist die SD Karte gemeint?

**Comment by vplustute** [comment]
Welches ist nun genau die RAM-Disk?

**Comment by christianTF** [comment]
KB-Artikel zur Analyse des Fehlers, bzw. zum Löschen der Logfile-Datenbank:
https://www.loxwiki.eu/x/oIMKAw
