### ISSUE TITLE
SDK Libs doesn't work with more than a few Cloud DNS MiniServers

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#919]
Leider funktioniert der ganze Cloud DNS Kram nicht mit ein paar mehr Miniservern, da der Dienst dicht macht.
Habe noch keine Idee wie man das im Core löst.
Ich baue das miniserverbackup Plugin dahingehend erstmal um.

Related to #917

**Comment by christianTF** [comment]
@Woersty Schick mir bitte in WhatsApp eine MAC, dann probier ich meinen neuen Caching Code.

**Comment by christianTF** [comment]
https://github.com/mschlenstedt/Loxberry/commit/aabd2ce6873268778d15931dab16551d83b0dd99

- Jeder CloudDNS wird im Cachefile (/run/shm/clouddns_cache.json) gespeichert
- Cache jedes einzelnen MS wird aktualisiert alle 60-120 Minuten (Random pro MS)
- get_miniservers ist durch den Cache jetzt viel schneller

Es löst *nicht*, dass bei Abruf von 50 CloudDNS-MS der Loxone-Server blockt. Mit wiederholenden Aufrufen jedoch sollte sich irgendwann der Cache füllen, und neuerliche Abrufe weniger werden.

**Comment by svethi** [comment]
Das Problem bleibt doch also genauso bestehen. Wenn 2 Stunden lang get_miniservers nicht aufgerufen wurde, sind alle IP‘s alt und er muss alle neu laden. Ich bin noch immer dafür die Abfrage ab einer gewissen Anzahl zu blocken. Das Plugin müsste dann entweder get_miniservers erneut aufrufen, damit der Cache weiter gefüllt wird, oder explizit den entsprechenden MiniServer abfragen lassen. Wenn man erst einmal geblockt ist, ist für eine ganze Zeit Feierabend.

**Comment by christianTF** [comment]
Mal schauen, wie das läuft. Sonst ist’s halt so, wenn Loxone das blockt.

Ich kann die Cachezeit in der General.cfg einstellbar machen.
Ich kann nach x Requests für x Minuten blocken.

Das ist dann eh genug Aufwand für 2 aus 2000 Loxberrys 😉

**Comment by christianTF** [comment]
CloudDNS-Cache beim Shutdown/Boot auf/von SD-Karte sichern
https://github.com/mschlenstedt/Loxberry/commit/db19f750274a54ca2bc5ab5b02d78196e5df31eb

**Comment by christianTF** [comment]
Ich schließe das ab. Stundenlang kann die Lib sowieso nicht auf die IP's warten, und der Cache hilft schon mal bei ein paar CloudDNS-Miniservern.
