### ISSUE TITLE
PHP via Apache loggt nicht mehr ins Apache error.log

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#923]
Wenn ich in PHP mit
```php
error_log("loxberry_web: pagestart function called -->");
```
ins Errorlog schreiben möchte, kommt das nicht mehr im Apache-Log an.

Ich kann das PHP-SDK nicht mehr debuggen.

**Comment by svethi** [comment]
Ähm, ja, das kommt nicht mehr im Apachelog an, seit das Apachelog verschoben wurde ins tmpfs.
Es müsste error_log = ${LBSTMPFSLOG}/apache2/error.log in die php Config

**Comment by christianTF** [comment]
Das gehört noch genauer erhoben.
Ich hab 6 php.ini's auf dem LoxBerry:
```
root@loxberry-dev:/etc/php/7.0/cgi# locate php.ini
/etc/php/7.0/apache2/php.ini
/etc/php/7.0/cgi/php.ini
/etc/php/7.0/cli/php.ini
/opt/loxberry/system/php/7.0/apache2/php.ini
/opt/loxberry/system/php/7.0/cgi/php.ini
/opt/loxberry/system/php/7.0/cli/php.ini
```

**Comment by mschlenstedt** [comment]
Wir sollten gleich die Gelegenheit nutzen und die PHP.ini bei uns ins system-Verzeichnis verlinken.

**Comment by christianTF** [comment]
Nach meinen Tests mit `/etc/php/7.0/apache2/php.ini`:
- error_log Eintrag ist erforderlich
- error.log muss Owner loxberry:loxberry sein (Standard ist root:root)

Evt. sind auch nur die Rechte Schuld, aber ohne den error_log Eintrag hab ich nicht hinbekommen.

**Comment by svethi** [comment]
So,
- system/php ist bereinigt
- system/php/20-loxberry.ini wurde angelegt
- wegen schreibrechteprobleme logt php ins apache2/php.log

ToDo:
- Update-Script muss system/php aufräumen und 20-loxberry.ini ausliefern
- Update-Script muss /etc/php/7.0/.../conf.d/20-loxberry.ini durch Link auf system/php/20-loxberry.ini ersetzen
- Apache2 muss nach den Änderungen neu gestartet werden
- Änderungen müssen für‘s nächste Image gemerkt werden.

**Comment by christianTF** [comment]
Durchlaufen tut's. Bitte um Review:
https://github.com/mschlenstedt/Loxberry/blob/master/sbin/loxberryupdate/update_v1.4.2.pl

**Comment by christianTF** [comment]
Gefixt im Update-Script 1.4.2:
https://github.com/mschlenstedt/Loxberry/blob/master/sbin/loxberryupdate/update_v1.4.2.pl

Follow-Up ist #957 (für setenvironments bzw. Image)
