### ISSUE TITLE
Verbesserungsvorschlag Plugins

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#93]
Installation auch möglich, wenn in der Zip das Plugin in einem Unterordner ist.
also nicht 
\config
\icons
...
sondern 
\xxxx\config
\xxxx\icons

z.B.
LoxBerry-Plugin-cam-connect-master\config
LoxBerry-Plugin-cam-connect-master\icons

wobei der Name egal ist.
Das ermöglicht ein sauberes Packen und Entpacken und die Installation der ZIP direkt von GitHub Export.

**Comment by mschlenstedt** [comment]
Ich wollte eigentlich keine neuen Features mehr in die aktuelle Version einbauen, aber das finde ich eine sehr gute Idee. Und da ich an die Pluginschnittstelle später erst einmal nicht mehr ran möchte werde ich das noch einbauen und dann doch noch eine Testversion veröffentlichen.

**Comment by Woersty** [comment]
https://github.com/mschlenstedt/Loxberry/issues/92

Mit freundlichem Gruß
Christian Wörstenfeld

---

Christian Wörstenfeld
Kalkbergeweg 10
D-12589 Berlin
Telefon: +49 30 50 15 8484
Mailbox: +49 30 55 15 1230
Fax:     +49 30 55 15 1232
Handy:   +49 30 55 15 1234
e-mail:christian@woerstenfeld.de
Threema: SV3C7MUX
Web: www.woerstenfeld.de
¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯

Am 15.08.2016 um 21:43 schrieb mschlenstedt:

**Comment by mschlenstedt** [comment]
Hinzugefügt.
