### ISSUE TITLE
Logmanager: Dateigröße ist immer die der letzten Datei

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#930]
Wurde das nicht schon mal gefixt?

**Comment by Woersty** [comment]
Ah. Verguckt.

**Comment by christianTF** [comment]
Wenn's nur ein File gibt, und jede Log-Session in das eine File geschrieben wird, wird jede Session natürlich mit der Dateigröße dieses Files angezeigt.
Ich hatte aber tatsächlich mal einen Bug in der Loop für den Logmanager, wo auch überall das gleiche stand :-) (auch wenn's nicht gleich war)
