### ISSUE TITLE
Plugininstall: Check ob URL ein ZIP-File enthält

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#935]
https://www.loxforum.com/forum/projektforen/loxberry/plugins/199867-installation-vom-gpio-plugin-funktioniert-nicht?p=199869#post199869

Im Webformular per Regex auf .zip$ kontrollieren und nach dem Download per" file FILE.zip | grep -E " zip " (oder so ähnlich).

**Comment by Woersty** [comment]
Keine Ahnung wie man das sinnvoll abfangen soll. Vorschlag habe ich committed

**Comment by Woersty** [comment]
```
We are in CGI mode.
02.05.2019 00:38:59 INFO: Statusfile: /tmp/9CGL1tmoOL.status
02.05.2019 00:38:59 CRITICAL: Das angegebene Archiv ist nicht im erforderlichen Format. Bitte kontaktiere den Author oder probiere die Installation erneut.
removed '/tmp/9CGL1tmoOL.zip'
Create notification: No NAME defined
at /opt/loxberry/sbin/plugininstall.pl line 1754.
```
Vielleicht könnte @christianTF das mit dem No NAME defined nochmal ansehen.
Ist das, da er noch nicht weiß, welches Plugin?

**Comment by mschlenstedt** [comment]
Ich hätte einfach ein

```$output = qx( file wrong.zip | grep -E " zip " );```

ausgewertet. Deine Lösung ist unabhängig und macht vermutlich genau das Gleiche wie "file" ;-) Find ich gut so.

**Comment by mschlenstedt** [comment]
@christianTF  Der obige Fehler kommt, weil "$pname" zu dem Zeitpunkt noch nicht gesetzt ist (denke ich). Der Notify soll im Plugininstall-Widget erscheinen. Was müssten wir dazu machen? 

Hätte im erstern Schritt $pname = "Unknown" am Anfang von plugininstall.cgi gesetzt, damit wäre es erst einmal definiert. Aber wo erscheint das Notify dann?

**Comment by mschlenstedt** [comment]
Hat sich erledigt - geht ;-)

**Comment by Woersty** [comment]
Getestet. Perfekt. Lösche wrong.zip wieder.
