### ISSUE TITLE
node.js und yarn mitliefern

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#937]
https://github.com/nodesource/distributions/blob/master/README.md#debinstall

Für node.js 12 (wird bald LTS):
```
curl -sL https://deb.nodesource.com/setup_12.x | bash -
```

Für yarn (als root):
```
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
apt-get update && apt-get install yarn
```

**Comment by christianTF** [comment]
Node.js V12 und Yarn wird installiert mit LBUpdate update_v1.5.0.1.pl:
https://github.com/mschlenstedt/Loxberry/commit/e3ccb8dc5295f7c16538e0ef48e2da48da38e7d6
https://github.com/mschlenstedt/Loxberry/commit/6d46aab83f1e82d0e4fc641249d56d8b6ac51bcd
https://github.com/mschlenstedt/Loxberry/commit/966b829b54e0a2f23d509dc01aca502df0639b7c

Beim Mergen der Update-Scripts für LB2.0 muss man darauf achten, dass die Installations-Routine erst NACH dem Buster-Update #969 durchgeführt wird, weil die Routinen die Paketquellen sonst für stretch eintragen.

**Comment by mschlenstedt** [comment]
Erledigt.
