### ISSUE TITLE
PHP 7.1 Support

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#940]
Mal schauen warum PHP 7.1 zickt

**Comment by Woersty** [comment]
Hat keine Prio. Nur mal schauen!

**Comment by Woersty** [comment]
https://github.com/mschlenstedt/Loxberry/blob/5c3deb37a2c3e9dcca092a8dead48ac492acd17e/sbin/setenvironment.sh#L277 usw.

**Comment by christianTF** [comment]
LoxBerry-Environments stehen in der 7.0er php.ini, wird durchgeführt in 
https://github.com/mschlenstedt/Loxberry/blob/5c3deb37a2c3e9dcca092a8dead48ac492acd17e/sbin/setenvironment.sh#L277

"Class SQLITE3 not found" -> PHP nicht sauber/vollständig installiert

**Comment by svethi** [comment]
7.1 ist doch auch gar nicht installiert, oder hat das ein Update draufgenudelt?

**Comment by christianTF** [comment]
Hat einer irgendwie draufgenudelt.

**Comment by Woersty** [comment]
> Hab dir Pfade geändert und die Pakete 
> Php7.1-cgi 
> Php7.1-sqlite3 
> nachinstalliert und das Script ausgeführt. Apache neugestartet und ... läuft. 

Von mir aus kannst es schließen und wir greifen es wieder auf wenn wir auf PHP 7.1 gehen.
Er hat es wegen Unify was mit PHP7.0 Probleme machte auf 7.1 aktualisiert

**Comment by christianTF** [comment]
Jep, erstmal close. Jetzt wissen wir‘s bei Bedarf.
