### ISSUE TITLE
Prüfen ob Root-Filesystem ReadOnly ist

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#942]
Per Cronjob 1x pro Stunde prüfen und Notify absetzen. Ist meist nicht offensichtlich, siehe hier: https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/201658-pugin-datenbank-defekt

Sollte ohne Schreibzugriff getestet werden, z. B. so (müsste eigentlich auch in einer VM so funktionieren):

``` mount | grep -e "on / type ext4 (rw"```

**Comment by christianTF** [comment]
Stündlich finde ich viel - das löst ja auch dauernd ein E-Mail aus.
Täglich?

**Comment by mschlenstedt** [comment]
Im healthcheck integriert.
