### ISSUE TITLE
healthcheck.pl: Der Schlüssel {sub} sollte von der aufrufenden Routine gesetzt werden

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#943]
https://github.com/mschlenstedt/Loxberry/blob/2577e725f4210bae7467a3e50e65d8e7a782b51b/sbin/healthcheck.pl#L126

Die Variable 'sub' sollte nicht im jeweiligen Check selbst, sondern von `performchecks` aus dem `@checks`-Array befüllt werden. Wenn man sich beim Definieren im Check vertut (Typo), funktioniert wahrscheinlich einiges nicht richtig. 
Im WebIf/Ajax ist 'sub' nach der Abfrage der `action=titles` der Key für alle Felder eines Checks und den Aufruf des Checks selbst.

**Comment by mschlenstedt** [comment]
Mach ich.
