### ISSUE TITLE
Healthcheck.pl: output=json should submit Logfile content

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#947]
The json output should include an attribute ‘logfilecontent’ with the content of the logfile, if file exists and is not empty.

The download button then can create the logfile in js, including the content of the logfiles.

**Comment by mschlenstedt** [comment]
Ich wäre dafür, dass das sub, welches ein Logfile erzeugt, den Content gleich in logfilecontent schreibt. Wenn man das erst in der Output-Routine macht, müsste man den gesamten Hash auseinander nehmen, prüfen, content einlesen, ins array schreiben und zum Schluss wieder den Hash zusammenbauen.

Finde ich extrem aufwendig für aktuell null Funktionen, die ein Logfile erzeugen...

Im sub kann man das Logfile direkt einlesen und nach $result{logfilecontent} schreiben.

**Comment by mschlenstedt** [comment]
Hab's schon...
