### ISSUE TITLE
Epoche2lox

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#949]
@⁨Schlenn⁩ Wenn du die Loxone Zeitrechnung kennst, magst du in LoxBerry::System zwei Funktionen epoch2lox und lox2epoch einbauen? Oder hat sonst jemand schon so einen Code fertig?

**Comment by mschlenstedt** [comment]
Commit: 828a60b47d6e9da13e0da8e8f7f83ef6339ad410

**Comment by christianTF** [comment]
TZ-Korrektur in https://github.com/mschlenstedt/Loxberry/commit/6f19d16666ab3beaadcba8908408e19cb36beac6
