### ISSUE TITLE
Healthcheck Spannung

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#952]
Web-Recherche/Tests:
Im kern.log kommt ein Fehler `Under-voltage detected! (0x00050005)`, allerdings ist das kern.log für loxberry nicht lesbar.

Andere Möglichkeit:
cat /sys/devices/platform/soc/soc:firmware/get_throttled
Bits:
| Bit | Meaning |
|:---:|---------|
| 0   | Under-voltage detected |
| 1   | Arm frequency capped |
| 2   | Currently throttled |
| 3   | Soft temperature limit active |
| 16  | Under-voltage has occurred |
| 17  | Arm frequency capped has occurred |
| 18  | Throttling has occurred |
| 19  | Soft temperature limit has occurred |

Evt. ist die 16 ein persistenter Indikator, dass es seit dem Boot irgendwann mal passiert ist.

Hab ein bisschen mit `sysbench` rumprobiert, konnte aber kein Event auslösen.

Quellen:
https://github.com/raspberrypi/documentation/blob/JamesH65-patch-vcgencmd-vcdbg-docs/raspbian/applications/vcgencmd.md
https://github.com/raspberrypi/linux/pull/2397
https://www.raspberrypi.org/forums/viewtopic.php?t=224896

**Comment by christianTF** [comment]
Bit Samplecode
```perl
#!/usr/bin/perl
my $val = "5005";
my @bits;
$bits[0] = ($val >> 0) & 0x01;
$bits[1] = ($val >> 1) & 0x01;
$bits[2] = ($val >> 2) & 0x01;
$bits[3] = ($val >> 3) & 0x01;
$bits[16] = ($val >> 16) & 0x01;
$bits[17] = ($val >> 17) & 0x01;
$bits[18] = ($val >> 18) & 0x01;
$bits[19] = ($val >> 19) & 0x01;

if($bits[3]) { print "Soft-Temp limit currently active"; }
if($bits[19]) { print "Soft-Temp limit has exceeded since last reboot"; }
```

**Comment by mschlenstedt** [comment]
Aus https://github.com/raspberrypi/linux/issues/2367: größer 16 ist sticky,  kleiner 16 ist aktueller Wert:

```
What:		/sys/devices/platform/soc/soc:firmware/get_throttled
Description:	This file returns the firmware get_throttled value which is 
		divided into 2 parts:
		- lower 16-bits are the live value
		- upper 16-bits are the history or sticky value

		Bits:
		0: under-voltage
		1: arm frequency capped
		2: currently throttled 
		16: under-voltage has occurred
		17: arm frequency capped has occurred
		18: throttling has occurred

		This file can be polled for changes.

What:		/sys/devices/platform/soc/soc:firmware/get_throttled_mask
Description:	This file does two things:
		1. Describes which bits should denote a change when polling
		2. The upper part is used when clearing the sticky bits

		Default value is 1 << 16.

What:		/sys/devices/platform/soc/soc:firmware/get_throttled_poll_ms
Description:	Specifies the get_throttled polling interval in milliseconds 
		(default 2000ms). The kernel polls this value to detect 
		under-voltage and to support polling the get_throttled file for 
		changes. Setting this to zero disables polling.
```

**Comment by mschlenstedt** [comment]
```
#!/bin/bash

#Flag Bits
UNDERVOLTED=0x1
CAPPED=0x2
THROTTLED=0x4
HAS_UNDERVOLTED=0x10000
HAS_CAPPED=0x20000
HAS_THROTTLED=0x40000

#Text Colors
GREEN=`tput setaf 2`
RED=`tput setaf 1`
NC=`tput sgr0`

#Output Strings
GOOD="${GREEN}NO${NC}"
BAD="${RED}YES${NC}"

#Get Status, extract hex
STATUS=$(vcgencmd get_throttled)
STATUS=${STATUS#*=}

echo -n "Status: "
(($STATUS!=0)) && echo "${RED}${STATUS}${NC}" || echo "${GREEN}${STATUS}${NC}"

echo "Undervolted:"
echo -n "   Now: "
((($STATUS&UNDERVOLTED)!=0)) && echo "${BAD}" || echo "${GOOD}"
echo -n "   Run: "
((($STATUS&HAS_UNDERVOLTED)!=0)) && echo "${BAD}" || echo "${GOOD}"

echo "Throttled:"
echo -n "   Now: "
((($STATUS&THROTTLED)!=0)) && echo "${BAD}" || echo "${GOOD}"
echo -n "   Run: "
((($STATUS&HAS_THROTTLED)!=0)) && echo "${BAD}" || echo "${GOOD}"

echo "Frequency Capped:"
echo -n "   Now: "
((($STATUS&CAPPED)!=0)) && echo "${BAD}" || echo "${GOOD}"
echo -n "   Run: "
((($STATUS&HAS_CAPPED)!=0)) && echo "${BAD}" || echo "${GOOD}"
```

**Comment by mschlenstedt** [comment]
Erledigt.

**Comment by JsBergbau** [comment]
> Hab ein bisschen mit `sysbench` rumprobiert, konnte aber kein Event auslösen.

Nimm CPU-Burn damit kriegst du den Prozessor innerhalb kürzester Zeit heiß https://github.com/ssvb/cpuburn-arm 
Wenn du ein schwaches Netzteil hast, gibt es einen Undervolt-Error auch noch dazu.

Das "| 3 | Soft temperature limit active |" gibt es nur beim B+ Ab 60 °C tritt das auf. Kann aber auf 70°C erhöht werden. Dieses Limit wurde von den ursprünglichen 70 auf 60 °C verringert, kann aber wieder erhöht werden mit temp_soft_limit=70 in /boot/config.txt  https://www.raspberrypi.org/documentation/configuration/config-txt/overclocking.md

**Comment by mschlenstedt** [comment]
Danke für den Hinweis. Das Thema hier ist allerdings schon gelöst. Diskussionen bitte im LoxForum: https://www.loxforum.com/
