### ISSUE TITLE
Feature-Request: Logs nach Datum aufräumen

### ISSUE THREAD

**Issue by scharrin2** [mschlenstedt/Loxberry#953]
Da es bestimmte Log-Kategorien gibt, welche irgendwann wegfallen, wäre es hilfreich das Log-Management wie folgt zu verändern:

1. Von jeder Kategorie x Log-Einträge behalten (ist jetzt schon so)
2. Logs älter ls x Tage löschen (wäre eine neue Funktion)

Zum Beispiel werden die Logs von Wetterdiensten, welche ich nicht mehr nutze, nie gelöscht. Darunter leidet die Übersichtlichkeit.

Viele Grüße,
Christian

**Comment by christianTF** [comment]
@mschlenstedt Du bist aus dem Schneider, du löscht die Logs nach 30 (.log) /60 (.gz) Tagen.

Da Oliver die Loggroup gewechselt hat, aber den gleichen Filenamen weiterverwendet, fliegen die Einträge nicht aus der LogDB (Kriterium ist >24 pro Gruppe oder Logfile nicht mehr vorhanden).

Ich hänge mich mit den 30 Tagen an. 
https://github.com/mschlenstedt/Loxberry/blob/318b32e58bacf3f7428be185d813b884a1f800e7/sbin/log_maint.pl#L330

**Comment by christianTF** [comment]
So ist das derzeit: https://www.loxwiki.eu/pages/viewpage.action?pageId=39355200

**Comment by christianTF** [comment]
Die aus logischen (nicht technischen) Gründen ist das nicht vollständig umsetzbar.

- Wenn ein Plugin kein Ende-Ereignis sendet, ist das aus Sicht der Datenbank ein offenes Logfile.
- Nur aufgrund des Startdatums (wenn kein Ende existiert) kann ich die Session in der Datenbank nicht löschen, weil der Dienst immer noch aktiv sein könnte. Das würde zu Datenbankfehlern führen, bzw. würden aktive Logfiles einfach "verschwinden".
- Wenn das Plugin das gleiche Logfile weiterverwendet, ist das Änderungsdatum des Logfiles aktuell, und somit die Log Session nicht "veraltet".
- Auch Logs von LoxBerry Update und der Plugin-Installationen würden entfernt.

Einzig sicher ausführbares Löschen geht nur, wenn ein End-Ereignis vorliegt (=Enddatum im Log Manager sichtbar), oder über den bisherigen Mechanismus, dass das File auch tatsächlich gelöscht wird.

Irgendwelche Ideen?

**Comment by christianTF** [comment]
@scharrin2 Schaust du dir das in 1.4.2.x mal an, ob jetzt alles wegkommt, was du weghaben willst?

**Comment by scharrin2** [comment]
Hallo Christian,
bei den Plugin-Logs sieht es gut aus - Danke.

Unter „Mehr Logfiles“ sind noch einige aus dem letzten Jahr drin. Auffällig ist, dass diese alle eine Größe von 0 Bytes haben.

Viele Grüße,
Christian

![IMG_0010](https://user-images.githubusercontent.com/22325491/58758084-7af28680-8516-11e9-87e0-7d6d3bc561fb.png)

**Comment by christianTF** [comment]
@mschlenstedt Das nonempty könnten wir eigentlich weglassen?
https://github.com/mschlenstedt/Loxberry/blob/5d8fb2ec3d241d7fed8b207ad998a00fb1ef0e01/sbin/log_maint.pl#L142

**Comment by christianTF** [comment]
Ab V1.4.3 werden die alten 0-Byte Logfiles auch weggeschmissen (älter 30 Tage).
Ich schließe damit diesen Issue ab.

lg, Christian
