### ISSUE TITLE
Plugin-Log bleibt bei Installation lange leer

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#958]
Bei einer Installation eines Plugins bleibt das Log sehr lange leer, bevor etwas angezeigt wird (am 3A+ etwa 2-3 Minuten).
Danach kommt der normale Installationsprozess.

Hier wäre nachzusehen, was zwischen dem Install-Button und dem "We are in CGI mode" läuft, und ob man da schon irgendeine Log-Ausgabe machen kann.

![image](https://user-images.githubusercontent.com/14220265/58730274-ea1f8c00-83eb-11e9-8735-bfe053a5be10.png)

![image](https://user-images.githubusercontent.com/14220265/58730358-2ce16400-83ec-11e9-9d29-860c8c866fbd.png)

**Comment by mschlenstedt** [comment]
Ist bei mir nicht so. Installation startet nach 1-3 SEK.

**Comment by christianTF** [comment]
Kann’s sein, dass der Download des ZIPs vor dem Start des Log ist?
Weil im Squeezelite die Binaries drin sind, ist das Archiv größer.

**Comment by mschlenstedt** [comment]
Kann sein. Kriege ich vielleicht mit VDSL nicht so mit. Schaue ich mir an.

**Comment by christianTF** [comment]
https://github.com/mschlenstedt/Loxberry/blob/5d8fb2ec3d241d7fed8b207ad998a00fb1ef0e01/webfrontend/htmlauth/system/plugininstall.cgi#L327

Nachdem das Logfile da schon offen ist, könnte man eine Zeile „Download...“ hineinschreiben.

Bei mir ging’s bei einem späteren Versuch auch schnell, es ist mir aber nicht zum ersten Mal aufgefallen.
