### ISSUE TITLE
Zeitsynchronisation

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#96]
Geht nicht mehr seit mehrere Miniserver möglich sind (korrekte Optionen des ersten Miniservers müssen gelesen werden).

Es fehlt zudem CloudDNS Unterstützung.

**Comment by Woersty** [comment]
Machst du?

**Comment by mschlenstedt** [comment]
Ja.

Von meinem iPad gesendet

**Comment by mschlenstedt** [comment]
Erledigt.
