### ISSUE TITLE
Mailconfig ISCONFIGURED parameter missing

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#961]
Siehe https://github.com/Woersty/LoxBerry-Plugin-cam-connect/issues/39

Wird gar nicht mehr gespeichert seit Umstellung auf mail.json?!

https://github.com/mschlenstedt/Loxberry/blob/master/webfrontend/htmlauth/system/mailserver.cgi#L200

**Comment by christianTF** [comment]
Machen wir für Legacy wieder rein (gleich gesetzt wie ACTIVATE_EMAIL).
Wenn der Parameter ganz fehlt, dürfte er - soweit ich mich erinnere - beim Reboot oder so, wieder aus der mail.json.default übernommen werden. Glaub ich.
