### ISSUE TITLE
Plugin installation link - allow query parameters after .zip

### ISSUE THREAD

**Issue by VVlasy** [mschlenstedt/Loxberry#962]
I am working on an ebusd plugin and I use GitLab instead of GitHub. Before a recent update, I was able to install it from URL as well as update. See sample link below.

https://gitlab.com/VVlasy/loxberry-plugin-ebusd/-/jobs/227554799/artifacts/raw/loxberry-plugin-ebusd.zip?inline=false

The issue seems to be the query parameters ?inline=false
Do you think it is possible to ignore query parameters in plugin link validation?

**Comment by christianTF** [comment]
https://github.com/mschlenstedt/Loxberry/commit/5df48bbe25e1a6aae7e19e0085c5bf05df03621c
@Woersty

**Comment by Woersty** [comment]
Will have a look.

**Comment by Woersty** [comment]
@VVlasy please try the current "Latest Commit" version.
http://loxberry/admin/system/updates.cgi

**Comment by VVlasy** [comment]
Works great! Thanks alot @Woersty !
