### ISSUE TITLE
Notifys bzgl. LogDB zu oft 

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#963]
Postfach wird minütlich vollgespamt mit Notify über defekte LogDB. Maximal 1x pro Tag wäre ok. 

Logmanager benachrichtigt über den folgenden System-FEHLER:

The logfile database sends an error and cannot automatically be recovered. Please inform the LoxBerry-Core team about this error:
Error -2 (attempt to do on inactive database handle)

![76A3EEDD-0F9C-4CEC-98AE-785B9E5E85FC](https://user-images.githubusercontent.com/16830799/59189562-a4488d80-8b7a-11e9-9a30-928c51bf4dbb.png)

**Comment by mschlenstedt** [comment]
Am besten soll sich das Ding gleich selbst reparieren.

**Comment by christianTF** [comment]
Das Notify nehm ich raus (wegen Healthcheck obsolet).
Selbst reparieren tut es eigentlich, aber nur beim Corruption-Fehler, nicht bei anderen Fehlern. 
Ich muss über das Fehlerhandling generell drüber sehen, das gefällt mir nicht, dass der eigentliche Fehler aus der init-Routine nicht durchkommt. (Weil Error -2 dann nur ein Folgefehler ist - den echten Fehler schluckt die init-Routine).

**Comment by christianTF** [comment]
Commit https://github.com/mschlenstedt/Loxberry/commit/c1e949758d67a3baec9df2dc7bd614689d793dc8 entfernt das Notify aus der Datenbankroutine, da dies nun der Healthcheck meldet.

Die generelle Überarbeitung des Fehlerhandlings ist noch offen.

**Comment by christianTF** [comment]
Bisher keine Rückmeldungen zu der Änderung. Wenn was reinkommt, mach ich wieder auf.
