### ISSUE TITLE
ErrorCode 2 bei Kernel- and Firmware-Update in update_v1.4.pl

### ISSUE THREAD

**Issue by nolamesu** [mschlenstedt/Loxberry#964]
Beim Aktualisieren von Loxberry auf das neueste Release bekomme ich einen Error mit ErrorCode 2, während der Installation des Kernels bzw. der Firmware.

Hier der Update-Log: ['20190614_094305_572_update.log'](https://github.com/mschlenstedt/Loxberry/files/3290130/20190614_094305_572_update.log)

**Comment by Woersty** [comment]
Was passiert denn, wenn du das Update als root manuell von der Shell probierst?
```
SKIP_WARNING=1 
SKIP_BACKUP=1 
BRANCH=stable 
/usr/bin/rpi-update 3678d3dba62d8d4ad9cce5ceeab3b377e0ee059d
```

**Comment by Woersty** [comment]
@christianTF vielleicht sollten wir auch denn Error Output ins log redirecten?
Also 2>&1 bei https://github.com/mschlenstedt/Loxberry/blob/master/sbin/loxberryupdate/update_v1.4.pl#L226

**Comment by Woersty** [comment]
Noch als Nachtrag: So sieht es bei mir mit einem Raspberry Pi 3 Model B Rev 1.2 aus: (zum Vergleich)
```
loxberry@loxberry:~ $ su
Password:
root@loxberry:/opt/loxberry# SKIP_WARNING=1
root@loxberry:/opt/loxberry# SKIP_BACKUP=1
root@loxberry:/opt/loxberry# BRANCH=stable
root@loxberry:/opt/loxberry# /usr/bin/rpi-update 3678d3dba62d8d4ad9cce5ceeab3b37                                                                                                         7e0ee059d
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
 *** Relaunching after update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
#############################################################
This update bumps to rpi-4.14.y linux tree
Be aware there could be compatibility issues with some drivers
Discussion here:
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=197689
##############################################################
 *** Downloading specific firmware revision (this will take a few minutes)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   168    0   168    0     0    446      0 --:--:-- --:--:-- --:--:--   446
100 56.2M    0 56.2M    0     0  1275k      0 --:--:--  0:00:45 --:--:--  734k
 *** Updating firmware
 *** Updating kernel modules
 *** depmod 4.14.87+
 *** depmod 4.14.87-v7+
 *** Updating VideoCore libraries
 *** Using HardFP libraries
 *** Updating SDK
 *** Running ldconfig
 *** Storing current firmware revision
 *** Deleting downloaded files
 *** Syncing changes to disk
 *** If no errors appeared, your firmware was successfully updated to 3678d3dba62d8d4ad9cce5ceeab3b377e0ee059d
 *** A reboot is needed to activate the new firmware
```

Welches Modell hast du? 
`cat /sys/firmware/devicetree/base/model`

**Comment by nolamesu** [comment]
Ich hab wie du das Modell Raspberry Pi 3 Model B Rev 1.2.
Das Update manuell als root funktioniert. Der Output ist derselbe wie bei dir.
Jetzt funktioniert auch das Update aus Loxberry heraus. 
['20190615_083716_478_update.log'](https://github.com/mschlenstedt/Loxberry/files/3292803/20190615_083716_478_update.log)

Kann es damit zusammenhängen, dass ich noch ebusd laufen hatte während des Updates?
Jetzt habe ich es mal nach einem loxberry-Neustart ohne laufendes ebusd probiert und das hatte  nun geklappt.

**Comment by Woersty** [comment]
Okay. Ursache ist mir nicht ganz klar aber ich würde, da ich das bisher von keinem anderen Benutzer gehört habe, sagen wir belassen es mal dabei.

**Comment by nolamesu** [comment]
In Ordnung. Vielen Dank dennoch und großes DANKE an euch Entwickler für dieses spitze Projekt!!
