### ISSUE TITLE
PHP 7.3

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#968]
Mit Buster

**Comment by Woersty** [comment]
Wenn es ein erstes Testimage gibt, teste ich mal meine PHP Plugins.

**Comment by mschlenstedt** [comment]
Beie gerade ein erstes Image. Habe beim Upgrade gesehen, dass anscheinend php7.3 gleich mitinstalliert wird. Warum beim ersten Test noch php7.0 aktiv war kann ich nicht sagen. Müssen wir uns anschauen.

**Comment by mschlenstedt** [comment]
apt-get remove php7.0-common
a2enmod php7.3
systemctl restart apache2

Config liegt noch unter /etc/php/7.3/

**Comment by mschlenstedt** [comment]
https://github.com/mschlenstedt/Loxberry/issues/969#issuecomment-507425504

**Comment by mschlenstedt** [comment]
- [ ] Deinstallation von PHP7.0 ins Update-Skript
- [ ] Links auf loxberry.ini ins Update-Skript
- [ ] Module nachinstallieren ins Update-Skript

**Comment by svethi** [comment]
dpkg --get-selections | grep php7
Damit bekommst Du die Liste der installierten Module

**Comment by mschlenstedt** [comment]
Auf einem 1.4.0.2 System:

```
root@loxberry:/# dpkg --get-selections | grep php7
libapache2-mod-php7.0                           install
php7.0                                          install
php7.0-bz2                                      install
php7.0-cgi                                      install
php7.0-cli                                      install
php7.0-common                                   install
php7.0-curl                                     install
php7.0-json                                     install
php7.0-mbstring                                 install
php7.0-mysql                                    install
php7.0-opcache                                  install
php7.0-readline                                 install
php7.0-soap                                     install
php7.0-sqlite3                                  install
php7.0-xml                                      install
php7.0-zip                                      install
root@loxberry:/#
```

**Comment by mschlenstedt** [comment]
Erledigt mit Upgrade auf 1.5.0.2
