### ISSUE TITLE
Stretch->Buster

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#969]
Dist-Upgrade to Buster for Pi4

**Comment by mschlenstedt** [comment]
https://www.tomshardware.com/news/raspbian-buster-upgrade,39735.html
https://serverfault.com/questions/48724/100-non-interactive-debian-dist-upgrade

**Comment by mschlenstedt** [comment]
Fehlermeldungen bei LBUpdate (ausgeführt nach dist-upgrade) -> eventuell umgekehrte Reihenfolge.

- [x] /opt/loxberry/sbin/loxberryupdate/update_v1.4.0.3.pl: <ERROR> Error installing libemail-mime-perl and/or libemail-sender-perl - Error 100
- [x] /opt/loxberry/sbin/loxberryupdate/update_v1.4.1.pl: <ERROR> Error upgrading kernel and firmware - Error 1
- [x] Logrotate Error nach Upgrade Prüfen.
- [x] NotifyDB nachAnpassung des Images löschen. Image-Anleitung anpassen

**Comment by svethi** [comment]
Logrotate Error nach Upgrade Prüfen.

/etc/cron.hourly/logrotate:
error: /etc/logrotate.conf:18 duplicate log entry for /var/log/wtmp
error: /etc/logrotate.conf:25 duplicate log entry for /var/log/btmp
run-parts: /etc/cron.hourly/logrotate exited with return code 1

**Comment by svethi** [comment]
Nach Upgrade muss der LB neu gestartet werden, da das WebIF nicht mehr funktioniert

**Comment by svethi** [comment]
Installierte PHP7.0 Module müssen für PHP7.3 nachgezogen werden.

**Comment by svethi** [comment]
Die 20-loxberry.ini aus /opt/loxberry/system/php/ muss nach /etc/php/7.3/apache2/conf.d, /etc/php/7.3/cli/conf.d/ und /etc/php/7.3/cgi/conf.d/ gelinkt werden

**Comment by mschlenstedt** [comment]
In setenvironments.sh werden noch Dateien anstelle der Links erzeugt. Zudem muss 7.0 und 7.3 (und vielleicht auch gleich 7.1 und 7.2 ergänzt werden.

Bin bereits dabei.

EDIT: erledigt mit 3af9e12727bb733ae26396193b8e3587d7c06cab

**Comment by mschlenstedt** [comment]
Erledigt mit Upgrade auf 1.5.0.2

**Comment by Woersty** [comment]
Nix erledigt. Geht bei mir immer noch nicht. Aber dafür funktioniert eMail nun nicht mehr und somit kommt die eMail nicht mehr an. 
In der /etc/logrotate.conf steht es noch und die /var/log/wtmp und btmp sind auch noch da.

```
root@loxberry:/etc/logrotate.d#  /etc/cron.hourly/logrotate
error: /etc/logrotate.conf:18 duplicate log entry for /var/log/wtmp
error: /etc/logrotate.conf:25 duplicate log entry for /var/log/btmp

```

**Comment by mschlenstedt** [comment]
Logrotate gefixt in 1d7678e4d37e6901fac510dff6b37453c371d198

@Woersty  Rest kann ich nicht nachvollziehen. Sauberes Image nehmen, hochziehen und dann nochmal Testen. Mail geht inkl. Migration. PHP geht ebenfalls.

**Comment by Woersty** [comment]
Das Image war ja sauber bis zum Update 🌝 
Momentan knapp bei Zeit. 
Schaue mal wann ich es schaffe. Momentan geht jedenfalls nix mehr.
Zum Glück war der nur DEVel

**Comment by mschlenstedt** [comment]
Konnte es hier auf jeden Fall nicht nachstellen. Vielleicht hat sich das auch schon längst erledigt. Logrotate habe ich gestern noch gefixt.
