### ISSUE TITLE
packages.txt aktualisieren

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#973]
Lighty wurde entfernt, PHP auf 7.3 gehoben.

Aktualisierung von packages_amd64.txt und packages.txt

**Comment by mschlenstedt** [comment]
@svethi  Wenn ich die ":armhf" im Paketnamen wegfiltere, dann bräuchten wir keine separate packages_amd64.txt mehr, oder? 

Dann würden nur noch die Raspberry spezifischen Pakete einen Fehler verursachen (raspi-config z. B.). Da gäbe es 2 Möglichkeiten:

1. Ich checke vor jedem Paket mit "apt-cache", ob es das Paket gibt
2. oder wir leben einfach damit und geben am Ende alle nicht installierbaren Pakete aus. Dann kann der Image-Maintainer selbst entscheiden, was er damit macht.

**Comment by svethi** [comment]
Ja, so habe ich das auch immer gemacht. Ich habe allerdings, wenn ich eine VM gebaut habe, zusätzlich noch contrib in den Repos hinzugefügt. Das hatte ich in irgendeiner Version gesehen und da findet er tatsächlich noch mehr Pakete. Es fehlen dann wirklich nur noch RPi speziellen, aber das ist klar.
Ja, ich würde nur ausgeben, was fehlt.

**Comment by mschlenstedt** [comment]
Ok, contrib ist auf dem Raspberry auch standardmäßig drin. Ich passe  ~/sbin/installpackages.pl entsprechend an. Dann brauchen wir nicht 2 "packages.txt" zu pflegen.

**Comment by mschlenstedt** [comment]
Fixed in 314f09c81ea048a796919ddd1707b4f60ee31349
