### ISSUE TITLE
Network.html: JS-Validation

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#974]
Nach der Integration von IPv6 muss dort die Validierung angepasst/ergänzt werden.

Ich habe die Validierungs-Tags und Texte+Übersetzungen bereits erstellt, jedoch im HTML/JS-Code auskommentiert.

Es benötigt ein neues „special“ IPv6 für IP und DNS.
Die Mask ist eine ganze Zahl zwischen 0 und 128.

**Comment by mschlenstedt** [comment]
Ist das nicht schon erledigt?

**Comment by christianTF** [comment]
Nein, ist noch offen (@Woersty 😉)

**Comment by Woersty** [comment]
Habe es soweit ich konnte getestet. Könnt ja nochmal probieren.
