### ISSUE TITLE
rfkill in Buster

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#979]
Nach Upgrade kommt folgende Meldung nach dem Einloggen:

```
rfkill: cannot open /dev/rfkill: No such file or directory
rfkill: cannot read /dev/rfkill: Bad file descriptor
```

**Comment by christianTF** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?t=243623#p1496914

> FYI -- This happens as well when on an original PI and you disable dhcpcd. 
> Re-enabling dhcpcd fixes it.. (at least in my case)

**Comment by mschlenstedt** [comment]
Verstehe ich noch nicht so ganz... dhcpd ist doch bei uns aktiviert, oder?

Anderer Tipp den ich gefunden habe: apt-get install rfkill

**Comment by mschlenstedt** [comment]
Wurde anscheinend in der Distribution gefixt,
