### ISSUE TITLE
Reboot Widget springt hin und her

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#980]
- Ausrufezeichen am Icon springt
- Daraus resultiert ein Ein- und Ausblenden der vertikalen Scrollleiste

![reboot1](https://user-images.githubusercontent.com/16830799/61180836-80ff7b00-a61d-11e9-987e-f50d81648c76.jpg)
![reboot2](https://user-images.githubusercontent.com/16830799/61180837-82c93e80-a61d-11e9-9c88-de1a29e9bc92.jpg)

**Comment by christianTF** [comment]
Ich kann nicht viel beitragen.
Ich kann das Problem nicht nachstellen, was ich aber sehe, ist, dass beim Resizen des Fensters das Rufzeichen wie angeklebt stehen bleiben, während sich der Powerbutton dynamisch richtig verschiebt. 

Vielleicht löst sich das Problem, wenn die Platzierung des Icons nicht absolut und in JS berechnet und gesetzt wird, sondern "statisch" relativ zum #btnpower, per CSS (nicht per JS-Manipulation).

**Comment by christianTF** [comment]
@mschlenstedt Kannst du mal probieren, ob die absolute Positionierung was geändert hat?
Zumindest bewegt sich das Symbol jetzt beim Skalieren sauber mit.

**Comment by christianTF** [comment]
#985

**Comment by Woersty** [comment]
@mschlenstedt Probier mal jetzt.
