### ISSUE TITLE
Update-Webserver Style/Funktionalität

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#981]
![image](https://user-images.githubusercontent.com/14220265/61312794-6e419d80-a7f9-11e9-9b28-cdcfb228b962.png)

Das hier soll schöner werden, und sich automatisch aktualisieren.

Lt. Michael:
Das ist das Template, was er verwendet https://github.com/mschlenstedt/Loxberry/blob/loxberry-1.5.0-grima/templates/system/reboot_updaterunning.html

Webserver ausprobieren: Apache stoppen, sicherheitshalber Port freiräumen (fuser -k 80/tcp). Ich muss dann teilweise 30-60 Sekunden warten, bis der Port wirklich frei ist.
Dann als Root /opt/loxberry/sbin/loxberryupdate/updaterebootwebserver.pl starten

**Comment by Woersty** [comment]
http://loxberrydev/logfile => Die Adresse /logfile gibt es hier leider nicht. 
Das Log war plötzlich weg.
Die Seite **An update is running. Please be patient - this can take a really long time...**  bleibt

**Comment by Woersty** [comment]
Ah! Apache2 läuft wieder aber das UI ist natürlich nicht da sondern auf http://loxberrydev/admin/system/index.cgi
Vielleicht sollte man da auf http://loxberrydev/ ein redirect auf /admin/system/index.cgi machen?

**Comment by Woersty** [comment]
Verstehe ich nicht. Da ist ja sogar eins.

**Comment by mschlenstedt** [comment]
Die Adresse /logfile gibt es, wenn das Update läuft: https://github.com/mschlenstedt/Loxberry/blob/5990ffeb43d791a9ce583ec95b80ebf6f9882490/sbin/loxberryupdate/updaterebootwebserver.pl#L16

Ist ein Link auf das Logfile während des Updates. Kannst Du als Parameter mitgeben, wenn Du den Webserver manuell startest:

```
/opt/loxberry/sbin/loxberryupdate/updaterebootwebserver.pl MEINLOGFILE
```

**Comment by mschlenstedt** [comment]
Das Thema mit dem Redirect verstehe ich nicht.

**Comment by Woersty** [comment]
Ich auch nicht. Ist nämlich schon da, greift aber nicht. Keine Ahnung warum die Update läuft Seite bleibt und man /admin/system/ eingeben muss 😔

**Comment by christianTF** [comment]
Ich hab jetzt ein bissl was am Style angepasst, und es wird sowas wie ein Live-Log angezeigt.
Wenn der Apache wieder läuft, sollte die Seite automatisch einen Reload machen.
