### ISSUE TITLE
Der Power Button geht in 1.5.0 nicht

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/Loxberry#985]
Da scheint ein Div drüber zu liegen oder so.

**Comment by christianTF** [comment]
Achso! Draufklicken soll man auch können 😂
Ab ich damit verhunzt: https://github.com/mschlenstedt/Loxberry/commit/060888b60e65a82e29a42ff73673950ff9c9ac0d

Das !-Bild ist so groß (30x30), dass es komplett über dem Button liegt.
