### ISSUE TITLE
Update löscht reboot.required

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#990]
Wenn ein reboot.required ansteht und man ein Update z. B. auf latest macht, ist die Rebootanforderung gelöscht.

**Comment by mschlenstedt** [comment]
Bei mir wird überhaupt kein reboot.rquired mehr angezeigt?! Egal was ich jetzt nach mache.

Update auf latest, vorher (1.5.0.3) ging's noch.

**Comment by christianTF** [comment]
Das müsstest du bitte nochmal genauer prüfen, ob:
1. Das reboot.required File weg ist (`/opt/loxberry/log/system_tmpfs/reboot.required`), bzw. mit F12 schauen, was der Response vom `ajax-footer-icons-handler.php` sagt, oder
2. das Footer-Symbol nicht richtig angezeigt wird.

Für 2. könnte es eine Browsercache-Sache sein, weil wir den Footer inkl. JS geändert haben.

Für 1. gibt es im Code zwei Stellen, wo das reboot.required File angegriffen wird:
1.  `/opt/loxberry/webfrontend/htmlauth/system/tools/generatelegacytemplates.pl` benennt das File um und wieder zurück, damit das Symbol nicht im Legacy-Footer ist (das Umbenennen ist in der Zwischenzeit eigentlich obsolet) - da hat sich nie was geändert, hab's getestet, funktioniert.
2. `sbin/loxberryinit.sh` löscht das File in der Start-Routine, sollte das Verzeichnis aus irgendwelchen Gründen den Reboot überleben.

**Comment by Woersty** [comment]
Teste ich wenn ich neu aufgesetzt habe.

**Comment by Woersty** [comment]
@mschlenstedt also bei mir geht's. 
Hast du das tmpfs leer Problem von dem @christianTF geschrieben hatte?

**Comment by mschlenstedt** [comment]
Nein, das gabs anscheinend nur in der VM. Ich hab hier auch nicht mehr weitergetrstet - keine Zeit. 

Wenn’s bei Christian auch ok ist machen wir es zu.
