### ISSUE TITLE
Samba unter "More Options" einfügen?

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#991]
Samba hat jetzt ein eigenes Tab, aber auch nur eine einzige Konfigurations-Option. Wollen wir das unter "More Options" analog zum FTP-Server packen?

Spart Platz für spätere (größere) Dinge.

**Comment by christianTF** [comment]
War die Idee, dass man auch Shares verwalten kann, dafür war der Platz vorgesehen.
Vom Backend-Code habe ich die gesamte Samba-Config „in der Hand“, dass ich Sachen sofort anzeigen könnte.

„More Options“ ist außerdem PHP, DH den Samba-Code müsste man neu schreiben.

Mir gefällt „More Options“ derzeit grundsätzlich nicht. In einem Save-Code werden jetzt drei unterschiedliche Dinge gespeichert. Für FTP hab ich extra Code drin, um überhaupt zu erkennen, dass der Benutzer an dieser Einstellung was geändert hat. Die Seite hat gar kein Fehlerhandling bei Save, und wenn ein Fehler auftritt, was passt dann und was nicht.
Es müsste alles per JS gemacht werden, und direkt gespeichert werden.
