### ISSUE TITLE
Disk Check / Repair

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#992]
Irgendein Script, mit dem man irgendwie das root unmounten und reparieren lassen kann. (Zumindest Reparaturversuch)
... wenn das FS readonly gemountet wurde

Vielleicht geht das irgendwie durch Ausführung von tmpfs, unmounten, Reparaturversuch, Reboot

**Comment by Woersty** [comment]
Bitte nochmal rüberschauen, da relativ kritisch, wenn es Mist ist.

**Comment by christianTF** [comment]
Muss rebootet werden?
Ich fürchte eine Reboot-Loop, wenn irgendwas schief geht.

**Comment by Woersty** [comment]
Man könnte auch ein Must-reboot setzen und ne Benachrichtigung versenden oder so. ￼ Er würde aber eigentlich nur in einer Loop hängen wenn des Filesystem read only bleibt￼￼ also eh futsch ist

**Comment by mschlenstedt** [comment]
Ein Reboot-Loop bitte vermeiden. Ich würde z. B. 10x rebooten und dann abbrechen. Habe mir den Code nicht angeschaut, aber vielleicht ein allerletztes Mal noch einmal mit "--force" und was noch so geht versuchen den Pi zu retten, dann aber abbrechen.

HIer mach ich auch 10 Versuche, könnte man so übernehmen: https://github.com/mschlenstedt/Loxberry/blob/03d7f714c71f0e29c2f6f71826e2626241762fb2/sbin/loxberryupdate/updatereboot_v2.2.0.pl#L52

Ich würde irgendwie per LED signalisieren, dass wir versuchen den Pi/das Dateisystem zu reparieren und nach dem 10. Versuch auch per LED signalisieren, dass wir aufgegeben haben und der Pi tot ist.

Man müsste sich eindeutige Blink-Codes dazu ausdenken und ins Wiki packen. Die LEDs lassen sich steuern: https://kofler.info/on-board-leds-des-raspberry-pi-steuern/

Und bitte schauen, ob bei einem defekten Dateisystem der LoxBerry überhaupt bis zum LoxBerry Initskript kommt, oder wird schon vorher im Bootprozess abgebrochen? Dann müssten wir "die Rettung" weiter vorne im Bootprozess einbauen.

**Comment by mschlenstedt** [comment]
Ist das noch aktuell? Seitdem wir auf DietPi gewechselt sind, will ich soweas eigentlich nicht mehr selbst bauen... Außerdem gibt's Backup-Möglichkeiten,
