### ISSUE TITLE
ssdpd: Exception handling für Sockets einbauen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#995]
ssdp wirft eine Exception, wenn er keinen Socket bekommt:
```
Jul 26 08:14:18 loxberry ssdpd[17333]: Can't call method "mcast_add" on an undefined value at /opt/loxberry/sbin/ssdpd line 31.
```
Systemd startet den Dienst dann alle zwei Sekunden neu und das Log wird voll.

--> Exception handling mit Sleep und Retry

**Comment by svethi** [comment]
Error handling habe ich eingefügt und den Service geändert.
Jetzt müsste ein Updatescript /etc/systemd/system/ssdpd.service unlinken und wenn es keinen LB Neustart gibt einmal systemctl stop ssdpd und $lbhomedir/system/daemons/system/01-ssdpd ausführen

**Comment by svethi** [comment]
Ist ja Quatsch. Ist ja ein Link. Der muss nicht neu angelegt werden. Es muss nur ein systemctl daemon-reload erfolgen

**Comment by mschlenstedt** [comment]
systemctl daemon-reload kommt in update_v1.5.0.7 mehrmals. Passt also.

**Comment by mschlenstedt** [comment]
Äh. Moment, Erstmal hast Du es in den master gebrancht - wir sind aber in loxberry-1.5.0-grima. Aber da hatte ich sowieso das Thema mit dem hardcoded Path schon gefixt.

Aber ein Error Handling bzgl. der Sockets ist da gar nicht committet (auch nicht im Master). Schaust Du bitte noch mal?

**Comment by svethi** [comment]
Doch, guck Du mal richtig ;-)
