### ISSUE TITLE
tmpfs on /opt/loxberry/log/plugins not mounted correctly.

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#996]
Unter /dev/shm/loxberry/log/ gibt es kein plugins Verzeichnis (sicher fehlen da noch andere). Daher funktioniert der tmpfs mount zu /opt/loxberry/log/plugins nicht.
Das ganze tmpfs muss wohl überprüft und korrigiert werden.

**Comment by mschlenstedt** [comment]
Ich mach hier zu. Weiter mit #1000
