### ISSUE TITLE
/boot partition not big enough

### ISSUE THREAD

**Issue by svethi** [mschlenstedt/Loxberry#997]
Auf meinem alten dev Image war die /boot Partition ganz offensichtlich nur 41MB groß. Dieser ist mittlerweile zu 96% belegt. Das kann bei updates zu Probleme führen. Wie wollen wir damit umgehen? Sollte mindestens in Zukunft größer sein.

**Comment by mschlenstedt** [comment]
Keine Idee wie ich das nachträglich im Image machen kann. Die Boot-Partition ist die erste auf dem Laufwerk.

Könnte vielleicht gehen, in dem man neide Partitionen des Images mit dd sichert und dann das Image komplett neu aufbaut. 

Beschäftigen wir uns mit, wenn es zum Problem wird, würde ich vorschlagen :-)

**Comment by mschlenstedt** [comment]
http://sirlagz.net/2012/06/20/how-to-resize-partitions-on-an-image-file/

Vergrößrn im Image geht. Aber wie gehen wir mit existierenden LBs um? Boot-Partition ist mit der PI4-Firmware nahezu voll (40MB).

**Comment by svethi** [comment]
Ja, das ist tricky und eigentlich nichts für Jedermann. Wenn genügend Platz auf dem Rest der SD ist, wäre der Weg root partition verkleinern, neue Partition hinter der root anlegen, Daten da rein verschieben, Daten von boot sichern, boot und altes root löschen, neues boot in richtiger Größe anlegen, Daten wieder reinschreiben, root hinter boot wieder anlegen, Daten da auch wieder rein verschieben, letztes root wieder löschen, richtiges root auf richtige Größe vergrößern.
Mit Ausweichdatenträger alles sichern, alle Partitionen löschen, neue Partitionen entsprechend anlegen und Daten zurückschreiben

**Comment by svethi** [comment]
Achja und nein, ich mache da keinen Einzeiler davon ;-)

**Comment by BigJohnson68** [comment]
Hallo Jungs
ich teste es gerade mit gParted live-CD
melde mich morgen wieder - mir ist das Selbe passiert und kann boot mit meinen Kenntnissen nicht vergrößern - gParted war bis jetzt bei anderen Systemen immer mein Freund

**Comment by mschlenstedt** [comment]
Ich vermute das wird nicht klappen. Gparted kann nur eine Partition vergrößern, wenn dahinter noch Platz ist. Das ist aber hier nicht der Fall.

Aktuell ist /Boot aber auch noch groß genug. Wir haben noch kein Problem. Erst wenn es einen echten 64Bit Kernel zusätzlich geben wird, wird unsere /boot Partition zu klein.

**Comment by mschlenstedt** [comment]
Mit LoxBerry Version 3.0 reicht nun die /boot Partition auf den alten LoxBerrys nicht mehr aus (Kernel zu groß).

**Comment by mschlenstedt** [comment]
Wird mit Zwischenlösung 2.4 in 3.0 umgesetzt.
