### ISSUE TITLE
Loxberryinit.sh als vollwertiger Systemd Service

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#999]
Wollten wir längst mal nachziehen.

**Comment by mschlenstedt** [comment]
https://wiki.debian.org/systemd

**Comment by svethi** [comment]
Ich weiß wie das geht ;-)

**Comment by mschlenstedt** [comment]
Ich weiß, war eher für mich, weil ich log2ram gleich als Service machen will :-)

**Comment by mschlenstedt** [comment]
Da ich log2ram jetzt doch in das bestehende createtmpfsfoldersinit.sh eingefügt habe, bleibt es erst einmal wie es ist.

**Comment by mschlenstedt** [comment]
Erledigt.
